### ISSUE TITLE
SGE jobs remain in running state after compute instance is terminated

### ISSUE THREAD

**Issue by tkainrad** [aws/aws-parallelcluster#1004]
**Environment:**
 - AWS ParallelCluster 2.2.1
 - base_os: Ubuntu 16.04
 - Scheduler: SGE
 - Master instance type: default
 - Compute instance type: c5.large

When a compute instance is manually terminated or because it is a spot instance, jobs running on those nodes will not get properly cancelled or marked as failed. Instead they continue being in the running state forever.

Also, the instances are not removed from SGE, e.g. `qhost` gives the following output:

```
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
ip-                               lx-amd64        2    1    1    2  0.00    3.6G  241.0M     0.0     0.0
ip-                               lx-amd64        2    1    1    2     -    3.6G       -     0.0       -
ip-                               lx-amd64        2    1    1    2     -    3.6G       -     0.0       -
ip-                               lx-amd64        2    1    1    2  0.00    3.6G  242.0M     0.0     0.0
```

I understand that variants of this problem have been mentioned in closed issues already (#687, #148). However, those fixes either do not apply to my environment or there is a new problem.

**Comment by tkainrad** [comment]
I see now an additional issue (#334) where it is said that this is expected behavior if there is still a job running on a terminated instance. Is there any way to delete all jobs running on an instance before it is terminated?

Would you consider this new feature? I think it is quite important to enable work with spot instances and fault tolerant applications.

**Comment by lukeseawalker** [comment]
Hi @tkainrad 
a better handling of the cases when an instance is reclaimed by spot (or manually terminated) is in the roadmap. Right now you would have to (force) delete the jobs and the hosts will be removed in the next sqswatcher cycle.

**Comment by tkainrad** [comment]
Thank you for the clarification. I am glad it is being considered.
At the moment, (force) deleting the jobs would be perfectly fine with me. Do you maybe have a recommendation regarding how to do this automatically when a node is terminated?

**Comment by tanantharaman** [comment]
I run the following /bin/csh script as part of the post_install script on the master node, to delete any jobs running on nodes that SGE considers non-responsive ( see /opt/sge/bin/dead-nodes).  My python job scripts use DRMAA which returns an exception code 24 (no job exit code available) from SGE which I use to resubmit the job.  I tested this by manually deleting instances OR picking spot instances that are in short supply (eg c5n.18xlarge in us-east-2c) resulting in many spot cancellations and my jobs recover on their own.

#!/bin/csh -f
setenv SGE_ROOT /opt/sge
setenv PATH "${PATH}:/opt/sge/bin/lx-amd64:/opt/sge/bin"
while ( 1 )
    foreach X ( `dead-nodes` )
        qmod -d all.q@$X
        foreach J ( `qstat -u \* | egrep $X | awk '{print $1}'` )
           qdel -f $J
        end 
    end
    sleep 5
end

**Comment by tkainrad** [comment]
Thank you @tanantharaman ! Looks great.

**Comment by xzy3** [comment]
you can set `reschedule_unknown` in sge_conf which will cause jobs to be automatically rescheduled if the executing node is in an unknown state for long enough. See `man sge_conf` this has been handling 99% of my rescheduling for me without intervention.

**Comment by demartinofra** [comment]
Yep and this option will be enabled by default starting with the next release of ParallelCluster!

**Comment by nstornetta** [comment]
Because we have announced that we will be deprecating support for SGE in the near-future (see: https://github.com/aws/aws-parallelcluster/wiki/Deprecation-of-SGE-and-Torque-in-ParallelCluster), we will not be performing additional enhancements specific to SGE.

I am going to close this issue. If you would like to request a similar enhancement for one of our other supported schedulers (Slurm or AWS Batch), please feel free to create a new issue.
