### ISSUE TITLE
Non-urgent guidance: Why is minimum fleet size now 2 in v2.3.1 ? 

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#1016]
This is non urgent / delete or close if the team is slammed! Just wondering if there was a technical reason for aws parallelcluster 2.3.1 now enforcing a minimum fleet size of 2? 

I have a use case for an elastic parallelcluster running SGE where legacy code can't deal with the "your job cannot be run at this time" STDERR that SGE spits out when there are no compute nodes scaled in. 

Because of this we had been using "initial_queue_size = 1"  and "maintain_initial_size = true" enabled so that our grid would always have at least 1 compute node running even if the grid was idle. 

But it looks like the default is now 2 and this is enforced at the ASG template level now? 

**Environment:**
 - AWS ParallelCluster 2.3.1
 - OS: CentOS 7
 - Scheduler: SGE
 - Master instance type: m4.4xlarge
 - Compute instance type: m5.2xlarge

**Bug description and how to reproduce:**

**
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Desired capacity:1 must be between the specified min size:2 and max size:20 (Service: AmazonAutoScaling; Status Code: 400; Error Code: 
**

**Comment by sean-smith** [comment]
Can you post your config? This should be perfectly valid. Min defaults to 2 but can be overridden to be lower.

**Comment by chrisdag** [comment]
Thanks! I have a history of embarrassing queries on here so I'm prepared for this one to be on me. Here was the config that generated the "_AWS::AutoScaling::AutoScalingGroup ComputeFleet Desired capacity:1 must be between the specified min size:2 and max size:20_" error ...

`[aws]
aws_region_name = us-east-1
aws_access_key_id = ##REMOVED##
aws_secret_access_key = ##REMOVED##

[cluster gblup-m4v2]
vpc_settings = vpc-##REMOVED##
key_name = ##REMOVED##
compute_instance_type = m4.4xlarge
master_instance_type = m5.2xlarge
custom_ami = ami-##REMOVED##
base_os = centos7
initial_queue_size = 1
max_queue_size = 20
maintain_initial_size = true
scheduler = sge
cluster_type = ondemand
proxy_server = http://##REMOVED##
ephemeral_dir = /scratch
encrypted_ephemeral = false
master_root_volume_size = 50
compute_root_volume_size = 50
ec2_iam_role = ec2InstanceRole-HPC-##REMOVED##
tags = { "Description" : "##REMOVED## centos7 aws-parallelcluster v2.3.1 HPC grid for ##REMOVED## tests running on m4.4xlarge instance types", "Jira" : "CE-3657", "Contact2" : "##REMOVED## ##REMOVED##", "Contact" : "Chris Dagdigian", "Platform" : "##REMOVED##",
 "ClusterName" : "##REMOVED##" }

pre_install = https://##REMOVED##.##REMOVED##.##REMOVED##/pub/##REMOVED##/##REMOVED##/scripts/pre_install-gblup-parallelcluster_v231_01.sh

[vpc vpc-ee8d9c8b]
master_subnet_id = subnet-##REMOVED##
compute_subnet_id = subnet-##REMOVED##
vpc_id = vpc-##REMOVED##
vpc_security_group_id = sg-##REMOVED##
additional_sg = sg-##REMOVED##
use_public_ips = false



[global]
update_check = true
sanity_check = false
cluster_template = gblup-##REMOVED##

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}`

**Comment by sean-smith** [comment]
Is this after a create or update?

**Comment by chrisdag** [comment]
Cluster create -- I've got a new cluster to deploy (along with my custom AMI and proxy baggage) so I updated my environment to v2.3.1 and started fresh. That error was the first thing I saw after fixing IAM permissions on the deploy user. 

I am up and running now with 2 fleet nodes so this is not an urgent thing for me. More of a curiosity

**Comment by sean-smith** [comment]
Thanks @chrisdag,

This is weird behaviour, we didn't make any code changes that would prevent this. Using a 1 ... or 0 node compute fleet is common behaviour. Here's the relevant section: [cfnconfig.py #L474](https://github.com/aws/aws-parallelcluster/blob/develop/cli/pcluster/cfnconfig.py#L474)

On your note about the `your job cannot be run at this time` warning message. We plan to address that soon. Usually the job can still be scheduled anyways, however I know the error message is confusing to users.

**Comment by chrisdag** [comment]
Thanks for looking into this; if I can find anything more concrete I'll let you know. This is the first of several v2.3.1 systems I need to deploy. I'll close/resolve this one so as not to take more team time

**Comment by sean-smith** [comment]
Ah ok, problem is here: https://github.com/aws/aws-parallelcluster/blob/develop/cli/pcluster/cfnconfig.py#L475

We set the `DesiredSize` parameter to default to `2`. Then we set `MinSize` based on the `DesiredSize`, assuming that we already set `DesiredSize` based on `initial_queue_size`. It looks like this is caused by the parser not ordering the arguments correctly. 

We use `OrderedDict` which was introduced in Python 2.7. What version of python are you running the cli with?

**Comment by chrisdag** [comment]
Looks like Python 3.5.2 in in the venv where I installed parallelcluster-2.3.1

**Comment by sean-smith** [comment]
Yep, just did a simple test and that's the problem (on our side, not yours):

```python
$ python3.5
>>> from collections import OrderedDict
>>> size_parameters = OrderedDict(
...             initial_queue_size=("InitialQueueSize", None),
...             maintain_initial_size=("MaintainInitialSize", None),
...             max_queue_size=("MaxQueueSize", None),
...         )
>>> for key in size_parameters:
...     print(key)
...
maintain_initial_size
max_queue_size
initial_queue_size
```

With 2.7 that's:
```python
...
>>> for key in size_parameters:
...     print(key)
...
initial_queue_size
maintain_initial_size
max_queue_size
```

Python 3.5 changes the order of OrderedDict.

**Comment by chrisdag** [comment]
Hah! and I thought I was being clever using python3. Thanks for finding this!

**Comment by sean-smith** [comment]
I'll create a PR to fix this behaviour, it looks like the order that parameters are initialized in a function changed between python 2 -> 3, causing the parameters to be initialized in a different order. I'm changing this to use a list.
