### ISSUE TITLE
skip account limit check during cluster create

### ISSUE THREAD

**Issue by keien** [aws/aws-parallelcluster#1035]
**Environment:**
 - AWS ParallelCluster / CfnCluster version : 2.3.1

**Bug description and how to reproduce:**

Recently upgraded to version 2.3.1, and noticed that I couldn't create new clusters due to the account limit check imposed by #872

We usually do a sort of blue-green deployment for our clusters, where we deploy a new set of clusters with some changes to replace the existing ones, and allow jobs to transition from new to old. This new account limit check means that we would have to have account limits that are double what we want the `max_queue_size` of the clusters to be for us to do this deployment.

Is there a way to skip the check? If not, could you add an option to do so?

**Comment by sean-smith** [comment]
Hi @keien 

You can disable the checks with:
```ini
[global]
sanity_check = false
```
but I assume you already know this and are asking for a specific way to disable the account limit check only. I've added a feature request flag and will discuss with the team.

Is it's important to note that the account limit check is only done on a per-cluster basis, so if you have, let's say a limit of 10 `c5n` instances, you can have two clusters each with `max_queue_size = 10`

**Comment by keien** [comment]
right, this is more of an issue when there’s an existing cluster that already has some instances, and we want to provision a new cluster with the same instance type. For example, I have a m5.large cluster with a max queue of 100, with 10 instances running in the cluster. I then want to create a new cluster with the same m5.large instances and also a max queue of 100. However, my account limit for m5.large is also 100, so the pcluster create will fail saying that I am asking for more instances (110) than my account limit (100). In the worst case, if I have an existing cluster with the max number of instances, I would need to double my account limit just to provision another cluster.

**Comment by enrico-usai** [comment]
I'm going to close this issue because we added the possibility to skip AWS limits check and then we improved the sanity check to be a configuration tester rather than a limit checker: https://github.com/aws/aws-parallelcluster/pull/1779
