### ISSUE TITLE
X11 support missing for Slurm

### ISSUE THREAD

**Issue by PrivoSkadberg** [aws/aws-parallelcluster#1038]
**Environment:**
 - aws-parallelcluster 2.3.1
 - OS: CentOS 7
 - Scheduler: Slurm
 - Master instance type: t2.small
 - Compute instance type: c5.2xlarge

**Bug description and how to reproduce:**
Slurm 17.X and above have native x11 support.  It appears to be disabled on the version packaged with parallel cluster.  Is there any way it can be turned on?

**Additional context:**
Packaged version:
```
[centos@ip-172-31-14-252 ~]$ /opt/slurm/bin/srun -n1 --pty --x11 xclock
/opt/slurm/bin/srun: unrecognized option '--x11'
Try "srun --help" for more information
```

Self-compiled version:
```
[centos@ip-172-31-14-252 slurm-18.08.7]$ ./src/srun/.libs/srun -n1 --pty --x11 xclock
srun: error: No DISPLAY variable set, cannot setup x11 forwarding.
```

(Didn't have X11 up yet, just wanted to make sure the command accepted it)

FAQ answer on this:
https://slurm.schedmd.com/faq.html#x11

**Comment by demartinofra** [comment]
Hi @PrivoSkadberg,

thanks for opening this request! 
Currently the x11 support is disabled because of libssh2 is missing as you can see from the compile output below:
```
checking whether Slurm internal X11 support is enabled... yes
checking for libssh2 installation...
configure: WARNING: unable to locate libssh2 installation
configure: WARNING: Slurm internal X11 support disabled
```

I will mark this as an enhancement so that we can add this support to the upcoming versions of ParallelCluster.

**Comment by PrivoSkadberg** [comment]
Thanks Francesco!!

Can you tell me what options are used to compile this currently (and if those are in a file somewhere in the repo)? I want to install my own version as you said, but don't want to break any settings parallel cluster might be using to configure slurm.

Thanks!

**Comment by demartinofra** [comment]
Sure, here are the chef recipes used to install and configure Slurm:
* https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/recipes/slurm_install.rb
* https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/recipes/slurm_config.rb

And in particular these are the lines executed to install Slurm: https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/recipes/slurm_install.rb#L39-L45

**Comment by PrivoSkadberg** [comment]
Thanks so much!  Didn't know that second repo existed.

**Comment by demartinofra** [comment]
Actually there is also a [third one](https://github.com/aws/aws-parallelcluster-node) that contains the code for the daemons that take care of dynamically scaling the cluster :)

**Comment by lukeseawalker** [comment]
missing libssh2-devel package will be shipped in next version, closing.
