### ISSUE TITLE
How to create an HPC cluster with EFA instance using aws-parallelcluster

### ISSUE THREAD

**Issue by Smahane** [aws/aws-parallelcluster#1047]
Hello,

It looks like they are multiple steps to follow in order to manually have an HPC cluster with EFA:
[https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-enable](url)

I need to create and configure an HPC cluster with these new EFA instances. I'm wondering if aws-parallelcluster ( which i will be using for the first time) support this instances . If it does, any configuration file i can use as an example?

Thank you,

**Comment by sean-smith** [comment]
Coming soon!

**Comment by Smahane** [comment]
@sean-smith I'm sure it will take time for the team to get this instances added. Is there anyway or workaround i can get this to work sooner? I'm in need of a cluster ASAP. 

Thank you,

**Comment by lukeseawalker** [comment]
ParallelCluster 2.4.0 is out
