### ISSUE TITLE
Turn off master node after pcluster stop

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#1053]
We would like to stop the master instance after running `pcluster stop <clustername>`. We can turn on the master instance before we run `pcluster start <clustername>`. Could you assist us with the changes that we need to take care of for `pcluster start` to work?

**Comment by lukeseawalker** [comment]
Are you experiencing any issue? What scheduler are you using? I have just verified with SGE and I didn't have to change anything before `pcluster start`.

**Comment by adavanisanti** [comment]
@lukeseawalker I am not experiencing any issue. It was more of a question. Instead of keeping the master node running, I would like to turn it off when it is not needed. I understand that it is not supported out of the box. If we explicitly shut down the master node, what are the aspects we need to take care of when we turn on the master node?

**Comment by lukeseawalker** [comment]
Before executing `pcluster start` verify that the master is up and running, in particular verify that the NFS share is active.

**Comment by adavanisanti** [comment]
@lukeseawalker master ip address will change after stop/start. Do we need to handle this ip address change for `pcluster start` to work?

**Comment by lukeseawalker** [comment]
That is one of the reason it's not supported out of the box, it depends on different variables. What IP address is changing? The public or the private? For example using SGE, if the private IP stays the same then it works. If the private IP changes, then the master node (from the scheduler point of view) must be reconfigured.

**Comment by adavanisanti** [comment]
I believe the private IP address won't change when we stop/start. Does parallel cluster EIP for master node so that the public IP doesn't change either? We are using slurm scheduler. Anything, in particular, to keep in mind? Thanks @lukeseawalker

**Comment by lukeseawalker** [comment]
The use of the EIP for the master depends from the [use-public-ips config variable](https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#use-public-ips). 
Before executing `pcluster start `verify that the master is up and running, in particular verify that the NFS share is active.

**Comment by adavanisanti** [comment]
Got it! Thanks.
