### ISSUE TITLE
Troubleshooting Spot Instance Jobs

### ISSUE THREAD

**Issue by zadelman** [aws/aws-parallelcluster#1077]
**Environment:**
 - aws-parallelcluster-2.3.1
 - OS: alinux
 - Scheduler: SGE
 - Master instance type: c4.large
 - Compute instance type:c4.4xlarge

**Bug description and how to reproduce:**
I'm trying to figure out why my spot instance jobs are hanging.  I'm running a weather model called WRF on 16 CPUs with MPI (OpenMPI 3.1.3). WRF runs through a series of model timesteps, outputting to data files each model hour. It has fairly extensive logging, including diagnostic logs that help troubleshoot if you've run up against numerical errors (like a divide by zero) or I/O errors during a simulation.  

The problem that I'm having is that the model runs fine for some variable number of output time steps, sometimes 10, 20, 30 model hours and then the WRF logs show that it remains in the running state with no errors but it stops outputting data, including messages to the logs.  It basically just freezes at some point and I can't tell what's going on. 

I'm wondering if I'm losing the spot queue and the job just doesn't restart after they become available again? My job shows that it's still in the running state at the command line, but it hasn't written anything for the past couple of days.  When I look at the EC2 and Spot Instance Consoles, there are no running compute nodes either, just the master. 

Any insights into how I may be able to troubleshoot this problem would be appreciated.  Also any pointers to documentation on what happens/how to configure spot instances with pcluster to control the behavior when jobs get pulled out of the queue. I did some searching through your docs and I can't find how pcluster spot jobs get stopped/restarted/terminated.   

The qstat output and my pcluster config files are below.  I don't have any trouble getting the cluster to start up, or in getting my jobs to start running. The problem is that they just hang up and I need to figure out how to make these runs more stable so that I can fire off 60-70 of them at once and have some confidence that most, or all, of them will run to completion (which is 132 output time steps). 
 
```
[ec2-user@ip-172-31-9-98 2016161]$ qstat
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
-----------------------------------------------------------------------------------------------------------------
      4 0.55500 GFS3hr     ec2-user     r     05/24/2019 14:29:35 all.q@ip-172-31-5-117.us-east-    16  
```      

**Additional context:**

```
[aws]
aws_region_name = us-east-2

[cluster ladcoaws]
vpc_settings = public
ebs_settings = data,input
scheduler = sge
master_instance_type = c4.large
compute_instance_type = c4.4xlarge
master_root_volume_size = 20
cluster_type =  spot
spot_price = 0.2
base_os = alinux
key_name =*****
#extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }
s3_read_write_resource = arn:aws:s3:::ladco-wrf/*
# Base AMI for Pcluster 2.3.1
custom_ami = ami-049afa5b53a7880d8

[ebs data]
shared_dir = data
volume_type = sc1
volume_size = 8000
encrypted = false

[ebs input]
shared_dir = input
ebs_volume_id = *****

[vpc public]
master_subnet_id = *****
vpc_id = *****

[global]
update_check = true
sanity_check = true
cluster_template = ladcoaws

[aliases]
ssh = ssh -Y {CFN_USER}@{MASTER_IP} {ARGS}
```

**Comment by sean-smith** [comment]
Hi @zadelman 

There's a logfile `/var/log/sqswatcher` that logs every time compute nodes are added and removed to the cluster. Can you post that contents of that logfile?

And to confirm you're not seeing any nodes when you run `qhost` correct?

We don't have any special logic to restart the jobs when spot instances are reclaimed so it seems like the most likely scenario is the spot instance is reclaimed, compute node is cleaned up but the scheduler isn't failing the job.

**Comment by zadelman** [comment]
[sqswatcher.txt](https://github.com/aws/aws-parallelcluster/files/3229234/sqswatcher.txt)

Thanks for the reply @sean-smith. That's right, qhost does not show any nodes as active.  

Are there any plans to allow an automatic restart of jobs from a spot checkpoint?  Being able to take advantage of that feature of the Spot Instances would be really nice.  It's actually critical to this application that I'm using. 

Have you had any requests for this feature before?

**Comment by demartinofra** [comment]
Hi @zadelman 

we definitely plan in the future to improve the overall experience of customers using spot clusters. Not clear yet to what extent we want to automate job checkpoints and restarts since the behaviour of each job is very application specific.
With the new upcoming release together with a series of enhancements for SGE, that improve the behaviour of the scaling logic and cluster recovery in case of instances termination, you can submit a job with the rerun option (`-r y`) and have it rescheduled for you in case the instance is reclaimed. However it's up to the job logic to periodically snapshot its status to a shared drive or persistent storage.

If you have any additional feedback or remarks do no hesitate to share it with us :)

**Comment by zadelman** [comment]
When do you expect the new release with the SGE restart feature to go live? Will this also have the checkpointing features of SGE enabled? 

I'm not really invested in one scheduler over another.  Do you recommend a different scheduler that may work better for checkpointing and restart than SGE?

**Comment by sean-smith** [comment]
@zadelman Early June. And no on the checkpointing feature.

One option for checkpointing is to write the files to S3, then when the job gets restarted, fetch the latest state from S3 and resume. A sample script for detection is included below:

```bash
#!/bin/bash
while true
do
  if [ -z $(curl http://169.254.169.254/latest/meta-data/spot/termination-time | head -1 | grep 404 | cut -d \ -f 2) ] then
    # 2 minute warning received. Push state to S3.
    break
  else
     # Still running fine, sleep and then check again
    sleep 3
  fi
done
```
I'd also checkout Berkeley Lab Checkpoint Restart (BLCR), though I'm not familiar with how it works.

See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#spot-instance-termination-notices

**Comment by zadelman** [comment]
I looked into BLCR and it's not compatible with Linux kernels newer than 3.7.1. 

It turns out that MPI checkpointing is not a straightforward install.  I'm still researching the best way to do this.  

To be clear, at this point with pcluster and spot instances, the user will need to figure out how to do checkpointing and restart and you all don't yet have any specifics on if/when you may enable fault tolerant tools (with MPI support?) on the instance templates.  I'm trying to figure out how much time I want to spend on this, vs just using the On Demand instances.

**Comment by sean-smith** [comment]
@zadelman In the next version of parallelcluster, your job will fail instead of hanging, see [#320](https://github.com/aws/aws-parallelcluster-cookbook/pull/320/files). This combined with the fact that you already write a datafile every hour should be all you need to recover runs. 

Write the checkpointing datafile into the shared drive `/data`, then rerun jobs with the `-r y` sge flag. 

Another note, you can also remove `spot_price` from your config file. This is an optional parameter, when it's not specified you get the spot market price which is capped at on-demand. This will reduce instance reclamation. Read more about it here: https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/

I also noticed you're using `sc1`, you'll get better performance out of the `st1` for such a large shared drive for not too much more money.

**Comment by zadelman** [comment]
Thanks, sean-smith, those are great tips.  We're going to try to build in fault tolerance to our application by using the software restart files.

Regarding the spot_price setting: do I need to create a new spot instance to implement this change, or is there a way to change this in an existing, running instance?

**Comment by notestaff** [comment]
" in case of instances termination, you can submit a job with the rerun option (-r y) and have it rescheduled for you in case the instance is reclaimed" -- if this is already implemented, would it be possible to tag a 2.3.2a2 alpha release with this feature?

**Comment by sean-smith** [comment]
@zadelman You should be able to use `pcluster update [cluster_name]` but I can't confirm that'll work. Run the update and check the launch template to see if it was updated to **not** include a spot Max Price.

@notestaff Coming soon I promise!

**Comment by sean-smith** [comment]
@zadelman Here's how you do that, go to the Cloudformation stack > Resources > LaunchTemplate, grab the launch template id from the resources tab:

![image](https://user-images.githubusercontent.com/5545980/59062882-bc0ed180-885b-11e9-944c-0a8a2d41ae34.png)

Then go to EC2 > Launch Templates > [lt id] and check the Max Spot Price Parameter

![image](https://user-images.githubusercontent.com/5545980/59062768-7ce08080-885b-11e9-8404-d080be9316bc.png)

**Comment by zadelman** [comment]
I didn't know about the cloudformation web interface.  That's really cool, thanks!  The update command doesn't like my attached EBS volume:

```
Updating: ladcoaws
Config sanity error on resource EC2Volume: Volume vol-**** is in state 'in-use' not 'available'
```
I'll try to launch a new instance with the tips provided by sean-smith.

**Comment by demartinofra** [comment]
Hi @zadelman 

were you able to solve the encountered issue?

**Comment by zadelman** [comment]
Hi @demartinofra, thanks for checking in.  If you're asking about updating the instance to change the spot-price setting, no that didn't work because of the EC2 Volume error above.  I just went and started a new instance where I removed the spot-price.  

Regarding the original issue with losing the spot queue, I'm still testing.  We've run into some software/data issues that are not related to AWS.  I think we've found a way around those, and will be running some jobs today to test the persistence of the spot queue now that I haven't set a spot price. I'll check back with you when we have results to share on this test.

Regarding the checkpointing/fault tolerance, I went down the road of trying to set up application checkpoint and restart using a few different options (BLCR, SCR, LAM, DMTCP). I was out of my league with the linux admin skills needed to set this up to work with MPI jobs, so I abandoned ship after a couple of days trying.  @sean-smith suggested making the restart work using the modeling software, and I think we may be able to build this into our workflow as an alternative to having checkpointing infrastructure on the system. Still exploring this one.

**Comment by demartinofra** [comment]
@notestaff version 2.4.0 was released and has support for the feature you were waiting for.

@zadelman with version 2.4.0 a series of improvements related to SGE scheduler were released. If possible I would recommend you to create a cluster with the newer version.

**Comment by notestaff** [comment]
@demartinofra thanks a lot!

**Comment by lukeseawalker** [comment]
Hi @zadelman,
were you able to solve the initial post issue?

To recap, the following is the current behaviour (2.4.1) in the management of forced shutdown of the compute nodes (e.g. Spot)

Node with single node running job/s:
- job is killed, marked as failed and eventually rescheduled in case the rerun flag is used (`qsub -r y`) or the queue is configured with the rerun flag enabled. The compute node is correctly removed from the scheduler queue. This behaviour is dictated by the following SGE configuration parameters:
```
    * reschedule_unknown 00:00:30
    * ENABLE_FORCED_QDEL_IF_UNKNOWN
    * ENABLE_RESCHEDULE_KILL=1
```

Node with a multi-node running job/s:
- the job is not terminated and keeps running on the available nodes. The compute node is removed from the scheduler queue but will appear in the hosts list as an orphaned and unavailable node.
It is responsibility of the user to delete the job when this occurs (`qdel <jobid>`). The node will be still displayed in the hosts list (`qhost`) although this will not affect the scaling of the cluster or any ParallelCluster feature.
`sqswatcher` daemon will retry to remove the host for three times. After that, to remove the host from the list you could execute the following command after having replaced `<hostname>` accordingly:
```sudo -- bash -c 'source /etc/profile.d/sge.sh; qconf -dattr hostgroup hostlist <hostname> @allhosts; qconf -de <hostname>'```

Luca

**Comment by zadelman** [comment]
Hi All

Any thoughts on this question about harvesting the system termination message.

**Comment by demartinofra** [comment]
Hi,

probably you need to slightly adjust your script according to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#spot-instance-termination-notices.

```
```
