### ISSUE TITLE
load balancing for job placement can prevent scale down of cluster

### ISSUE THREAD

**Issue by tkuzuhara** [aws/aws-parallelcluster#1084]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.1.1
 - OS: Centos
 - Scheduler: SGE
 - Master instance type: N/A
 - Compute instance type: N/A

Less if a bug report, but more of a question and perhaps a feature request:

We tend to launch clusters with high slot counts.  For example m5-24xlarge has 48 slots available.  The main motivation for this is because instance start up time with parallelcluster is rather high, so we want to make it more likely that a slot will be available when jobs are submitted.

At times a cluster may scale up due to high demand, but the scale down can take a long amount of time.  The reason for this is that once a cluster has scaled up to N instances, the job scheduler (we use SGE) will try to load balance the jobs across the cluster.  Even though job demand has subsided after the scale up, what we end up with is N instances each with 1 slot being taken, which means a large amount of the compute available is wasted.

Is there a way to influence the job scheduler to prefer packing jobs into the same instance when possible, rather than attempting to load balance?  This would allow a much faster scale down since instances with 0 slots used can be spun down.  I'm not sure if this is something we would consider a job scheduler (SGE) responsibility or something built into parallelcluster.

Does there exist an easy solution to this?  And if not can this be considered as a feature request?

**Comment by sean-smith** [comment]
Ya, this is a SGE parameter. Let me look it up and see which one

**Comment by sean-smith** [comment]
Ok, SGE is already configured with `$fill_up` which is what you want. Here's what you can check:

```
$ sudo su # must be root, not just sudo
$ qconf -mp mpi
pe_name            mpi
slots              99999
user_lists         NONE
xuser_lists        NONE
start_proc_args    NONE
stop_proc_args     NONE
allocation_rule    $fill_up  <------------- This can be round_robin or fill_up
control_slaves     TRUE
job_is_first_task  TRUE
urgency_slots      min
accounting_summary TRUE
qsort_args         NONE
```

See http://star.mit.edu/cluster/docs/0.93.3/guides/sge.html#round-robin-vs-fill-up-modes (weird to link to starcluster but they have an excellent explanation of it)

**Comment by sean-smith** [comment]
ok, I just tested and this does what you want. 

### fill_up
```bash
[ec2-user@ip-172-31-31-70 ~]$ qhost
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
ip-172-31-21-163        lx-amd64       72    2   36   72  0.01  184.7G   10.8G     0.0     0.0
ip-172-31-31-127        lx-amd64       72    2   36   72  0.00  184.7G   10.9G     0.0     0.0
[ec2-user@ip-172-31-31-70 ~]$ qrsh -pe mpi 73 /opt/amazon/efa/bin/mpirun hostname | grep ip-172-31-31-127 | wc -l
72
```

### round_robin
```
[ec2-user@ip-172-31-31-70 ~]$ qhost
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
ip-172-31-21-163        lx-amd64       72    2   36   72  0.01  184.7G   10.8G     0.0     0.0
ip-172-31-31-127        lx-amd64       72    2   36   72  0.00  184.7G   10.9G     0.0     0.0
[ec2-user@ip-172-31-31-70 ~]$ qrsh -pe mpi 73 /opt/amazon/efa/bin/mpirun hostname | grep ip-172-31-31-127 | wc -l
37
```

**Comment by tkuzuhara** [comment]
Awesome, we'll try it out.  Thanks so much @sean-smith for the quick response and testing!  I wonder whether this should be how SGE should be configured by default by parallelcluster.  It seems that round-robin default works against the intent of cluster scaling.

I'll go ahead and close this since the original question has been answered.  Thanks again!

**Comment by sean-smith** [comment]
It defaults to `fill_up`, hence my confusion as to why it wasn't behaving the way I expected. Check the `qconf` and let me know what's configured there.

**Comment by tkuzuhara** [comment]
Oh I see.  Yes, default for `mpi` is at fill-up:

```
$ qconf -sp mpi
pe_name            mpi
slots              99999
user_lists         NONE
xuser_lists        NONE
start_proc_args    NONE
stop_proc_args     NONE
allocation_rule    $fill_up
control_slaves     TRUE
job_is_first_task  TRUE
urgency_slots      min
accounting_summary TRUE
qsort_args         NONE
```

It looks like we are actually using the smp parallel environment for our jobs:
```
$ qconf -sp smp
pe_name            smp
slots              99999
user_lists         NONE
xuser_lists        NONE
start_proc_args    NONE
stop_proc_args     NONE
allocation_rule    $pe_slots
control_slaves     TRUE
job_is_first_task  TRUE
urgency_slots      min
accounting_summary TRUE
qsort_args         NONE
```

We can try changing the allocation_rule to $fill_up and we'll see if it helps.
