### ISSUE TITLE
Feature Request: (Optionally) Provision Central Logging and Dashboards in CloudWatch for Cluster

### ISSUE THREAD

**Issue by senorkrabs** [aws/aws-parallelcluster#1085]
Adding central logging capabilities to CloudWatch would be a huge help for troubleshooting/monitoring. Are there plans to build this into ParallelCluster as a config option, rather than having to deploy yourself per the Wiki?
https://github.com/aws/aws-parallelcluster/wiki/CloudWatch-Logs

**Comment by enrico-usai** [comment]
Hi @senorkrabs, 
yes, it is planned but we don't have yet a timeline to share for it for it. 
I'm marking this as a feature enhancement.

Thank you

**Comment by tapaswenipathak** [comment]
Hi @enrico-usai, interested in adding the feature? Doing it.

**Comment by tapaswenipathak** [comment]
Hi @enrico-usai, interested in adding the feature. Doing it.

**Comment by enrico-usai** [comment]
Hi @tapaswenipathak, thank you for sharing your approach!

**Comment by Perif** [comment]
@tapaswenipathak , see here: https://github.com/aws/aws-parallelcluster/wiki/CloudWatch-Logs

**Comment by tapaswenipathak** [comment]
Thanks folks, please let me know if my PR is correct and helps fixing the issue.

**Comment by demartinofra** [comment]
Support for CloudWatch logging has been implemented and will be part of the next minor version of ParallelCluster.

**Comment by lukeseawalker** [comment]
AWS ParallelCluster 2.6.0 with CloudWatch logging capability to collect cluster and job scheduler logs has been released
