### ISSUE TITLE
for spot clusters, option to launch master node as on-demand or as defined-duration spot

### ISSUE THREAD

**Issue by notestaff** [aws/aws-parallelcluster#1092]
Currently, to use spot instances, all nodes must be Spot, including the master node.
Could you add the ability to launch the master node as defined-duration spot, or as on-demand instance, while still launching the compute nodes as Spot?
Thanks!

**Comment by sean-smith** [comment]
The master is an on-demand ec2 instance, only the compute nodes are spot.

**Comment by notestaff** [comment]
Ah, ok.  Maybe clarify that in the docs?  Also, it'd still be useful to be able to launch the master as a defined-duration spot instance.  Thanks!

**Comment by sean-smith** [comment]
@notestaff Ya, we can definitely clarify that in the docs. I believe we have another github issue for defined-duration spot, but for the compute instances. Let me dig that up

**Comment by sean-smith** [comment]
What's the reason for having the master as a defined-duration spot instance as opposed to ondemand?

**Comment by notestaff** [comment]
Cheaper, if you're only running the cluster for a defined time?

**Comment by sean-smith** [comment]
Thanks @notestaff 

This leads down the path of having a time to live attribute on a cluster, since when the master expires, the cluster is unusable. I can see the value prop of having defined-duration spot for the compute, for defined length workloads. I'm having trouble seeing the value of having the master be defined-duration spot. I'm eager to hear your opinion on this.

My best advice for cost savings is set the master to a small instance (if you're using efs / fsx as your shared filesystem) and set `maintain_initial_size = false`.

**Comment by notestaff** [comment]
Ideally I'd just use the master as my dev/work machine.  Currently for dev/work I run spot instances; I find the frequency of interruptions acceptable.  The master will have the shared EBS volumes mounted, whereas if my work machine is separate from master, I have to jump through hoops to access them.  Jobs I run tend to be idempotent, so it's no big deal if the cluster suddenly dies, as long as it can be re-created.
.  
Ideally, you'd let master even be a non-defined-duration spot instance, and use the spot termination notification to shut down the cluster.  But if that's not feasible,

**Comment by notestaff** [comment]
Also, if I understand correctly, if using NFS as the shared filesystem, the size of the master can strongly affect the performance.  So it's useful to be able to use a higher-end node, but that quickly gets expensive without Spot.

**Comment by sean-smith** [comment]
@notestaff That's correct, however if you use EFS/FSx, it doesn't matter the size of the master instance. Of course this means you're paying for EFS (fairly inexpensive) or FSx (expensive) so you have to balance that with the cost of the master instance.

Thanks for the valuable suggestion. I'm going to mark this with the `enhancement` flag.

**Comment by notestaff** [comment]
Btw, I'm likely missing something, but why is FSx more expensive than EFS?  The pricing page says EFS is $0.30 per GB-month while FSx for Lustre is $0.14 per GB-month.

**Comment by sean-smith** [comment]
You mean why is EFS more expensive than FSx?

**Comment by notestaff** [comment]
I was trying to understand your comment above, that said "EFS (fairly inexpensive) or FSx (expensive)"

**Comment by lukeseawalker** [comment]
I think that @sean-smith is referring to the fact that with FSx you provision storage capacity in advance.

**Comment by enrico-usai** [comment]
I'm going to close this issue. We are retaining for now the definition of clusters as persistent, which requires for head node to be launched as on-demand instance.

As part of [3.0.0 release](https://github.com/aws/aws-parallelcluster/releases/tag/v3.0.0) we introduced the possibility to restart / reboot the head node also for instance types with [instance store](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html). Those operations remain anyway managed by the user that is responsible for the status of the cluster while operating
on the head node, e.g. stopping the compute fleet first.

This feature plus the introduction of the new revamped CLI simplify the creation of workflows on which a cluster can be created, deleted and then re-created when needed in an automated way.
