### ISSUE TITLE
Question on AWS ParallelCluster in a single private subnet connected using Direct Connect

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#1102]
**Environment:**
 - AWS ParallelCluster 2.2.1
 - OS: ubuntu 1604
 - Scheduler: Slurm
 - Master instance type:  m5.xlarge
 - Compute instance type: c5.8xlarge

**Question**
Can I create multiple parallel clusters with a single private subnet connected using Direct Connect gateway?  If so, are there any modifications I need to do the settings described [here](https://aws-parallelcluster.readthedocs.io/en/latest/networking.html#aws-parallelcluster-in-a-single-private-subnet-connected-using-direct-connect)?

Thanks
Santi

**Comment by enrico-usai** [comment]
Hi @adavanisanti ,
this should be possible. 

As you can see in the doc, you need to setup a proxy to make the cluster able to contact AWS endpoint and to download some required packages from the web.

Let us know if you have issues with this configuration.

**Comment by adavanisanti** [comment]
@enrico-usai Is the below setting needed if we can ssh to private IP directly from the network?

```
[cluster private-proxy]
proxy_server = http://proxy.corp.net:8080
```

Thanks
Santi

**Comment by lukeseawalker** [comment]
Hi @adavanisanti,
the proxy is needed because master and compute nodes need to access resources on the Web.
We have plans to minimize (or even remove) external internet access in the future when using ParallelCluster cooked AMI

**Comment by adavanisanti** [comment]
Hi @lukeseawalker, I have the following questions:
1. Is outbound internet access sufficient?
2. Are the resources you are referring to S3 and DynamoDB? If so, is a VPC gateway endpoint setup be sufficient instead of setting up a proxy?

Thanks
Santi

**Comment by lukeseawalker** [comment]
Resources like
* pypi.python.org
* bootstrap.pypa.io
* supermarket.chef.io
* mirrorlist.centos.org
* etc.

**Comment by adavanisanti** [comment]
@lukeseawalker - If I understand right, _only outbound internet access_ is used to the above sites as part of creating the parallel cluster. Is that correct?

**Comment by lukeseawalker** [comment]
@adavanisanti correct

**Comment by adavanisanti** [comment]
Thanks @lukeseawalker

**Comment by adavanisanti** [comment]
@lukeseawalker, if I have outbound internet access, do I still need this parameter in the configuration from the [documentation](https://aws-parallelcluster.readthedocs.io/en/latest/networking.html#aws-parallelcluster-in-a-single-private-subnet-connected-using-direct-connect)?

```
[cluster private-proxy]
proxy_server = http://proxy.corp.net:8080
```

**Comment by demartinofra** [comment]
You shouldn't need a proxy configuration if you have outbound internet access configured at the vpc/subnet level (e.g. you configured a NAT Gateway). The proxy config is needed only if you want to explicitly use a specific endpoint as a proxy.

**Comment by vabd222** [comment]
Hey just wanted to know if there is any way to access internet resources by putting them all in a S3 bucket instead of reaching out to the internet.
