### ISSUE TITLE
conda-forge recipe -- co-maintainers?

### ISSUE THREAD

**Issue by notestaff** [aws/aws-parallelcluster#1113]
FYI, aws-parallelcluster is now installable via [conda-forge ](https://conda-forge.org/) .  Would any of the aws-parallelcluster developers be interested in being listed as co-maintainers of the recipe ( https://github.com/conda-forge/aws-parallelcluster-feedstock )?  This just means you'll be able to update the recipe for new versions, check that the dependencies are correct, etc.

@demartinofra @dougalb @sean-smith @enrico-usai @lukeseawalker

**Comment by sean-smith** [comment]
Hi @notestaff Sure! You can add me

**Comment by lukeseawalker** [comment]
Hi @notestaff,
you can add me too. Please notice that AWS ParallelCluster 2.3.2a1 is an alpha version. Better switch to 2.3.1 or wait for the new release coming soon.

**Comment by notestaff** [comment]
@lukeseawalker great, thanks-- i'll add you when I update the recipe for the next release (which I understand should be soon?)

**Comment by lukeseawalker** [comment]
Thank you. Yes, coming soon

**Comment by notestaff** [comment]
"AWS ParallelCluster 2.3.2a1 is an alpha version. Better switch to 2.3.1 " -- I've added a post-link script that prints a warning to this effect when an alpha version is installed into a conda environment.  The 2.3.1 version is on conda-forge as well.
Also, the maintainer list has now been updated.

**Comment by lukeseawalker** [comment]
2.4.0 is out

**Comment by enrico-usai** [comment]
Me too, thank you!
