### ISSUE TITLE
tag code version for v2.3.2a1

### ISSUE THREAD

**Issue by notestaff** [aws/aws-parallelcluster#1114]
Could you add a tag for the code version corresponding to the release 2.3.2a1 on pypi?
I'm specifically looking for the matching version of amis.txt .  Thanks!

**Comment by lukeseawalker** [comment]
Hi @notestaff,
it's an alpha version made for test, so we don't usually tag those versions.
Btw this should be the commit of the AMI you are looking for https://github.com/aws/aws-parallelcluster/commit/9fc747627012e30df534226335ee489da1a2ef80
