### ISSUE TITLE
Cluster can't launch more than 99 nodes

### ISSUE THREAD

**Issue by vbosquier** [aws/aws-parallelcluster#1115]
**Environment:**
 - aws-parallelcluster-2.1.1
 - OS: centos7
 - Scheduler: Slurm
 - Master instance type: g3s.xlarge]
 - Compute instance type: t3.small

**Bug description and how to reproduce:**
Hi,
I have launched a cluster supposed to have a huge number of small nodes, but the cluster never showed more than 99 nodes...
The EC2 limits was raised on our account to 500 t3.small for that.
The VPC/Subnet environment is OK (more than 2000 IP addresses available in the subnet).
The cluster was started with 1 compute node (min_size & desired_size = 1, max_size = 500). Then I changed the values for "min_size" and "desired_size" in the ASG using the console to 200 (first target for testing). 99 nodes was the maximum number of nodes I've got...
Is there any reason for that limit? Please can you help? 

**Additional context:**
I need this cluster with 500 nodes to be up and running on tuesday morning 9AM (Paris timezone).

**Comment by sean-smith** [comment]
Can you post your config file and the contents of `/var/log/sqswatcher`? Can you check that the nodes are being launched by going to the EC2 console > autoscaling > parallelcluster-[cluster_name] and clicking on the instances tab. 

I want to isolate the issue, perhaps you already know, are the nodes coming online and not getting attached to the scheduler or are they not coming online at all?

**Comment by sean-smith** [comment]
For context, we have customers with several hundred node clusters, so it’s not a built in limit to parallelcluster

**Comment by vbosquier** [comment]
Hi Sean,

Quick reply:
- No access to the logs anymore for this time, the cluster is terminated
- Compute nodes are supposed to be SPOT instances (may it be part of the reason?)
- The config file is attached
- I have used the EC2>ASG console to see the nodes being started:
    + initially the stack started normally with 1 functional node
    + then I modified the ASG to update the min_size and desired_size to the expected cluster size (200)
    + then, the nodes started by pack of 10 very quickly up to 80
    + then, the nodes were started more slowly up to 90 then 1 at a time approximately every 10 minutes (no clear measure was taken)...
    + as soon as there were 99 nodes up, no more node was added to the cluster...
- all the nodes which were started have been added to the job scheduler's configuration correctly

Best regards,
Vincent.
[pcluster-teratec.config.txt](https://github.com/aws/aws-parallelcluster/files/3269977/pcluster-teratec.config.txt)

**Comment by sean-smith** [comment]
Ah, thanks for clarifying SPOT. Yes the adding instances 10 at a time is a normal ASG behavior. My guess is that you hit spot instance limits which is separate from EC2 on demand limits, you can check in the EC2 console > Limits. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html

**Comment by vbosquier** [comment]
Hi Sean.Thanks for the link to the doc. Considering the fact we want to launch a cluster made of 500 t3.small compute nodes in Dublin (eu-west-1), what would you recommend?Vincent BosquierUCit[Envoyé de mon Smartphone]Le 9 juin 2019 23:47, Sean Smith <notifications@github.com> a écrit :Ah, thanks for clarifying SPOT. Yes the adding instances 10 at a time is a normal ASG behavior. My guess is that you hit spot instance limits which is separate from EC2 on demand limits, you can check in the EC2 console > Limits. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html

**Comment by lukeseawalker** [comment]
Hi @vbosquier,
as @sean-smith suggested, I would look at the spot instance limits, that is different from the on-demand limits.
Also check at the activity history of the EC2>ASG console

**Comment by vbosquier** [comment]
Ciao Luca.Ben (Depardon) has sent a request on the support of our AWS account to raise the Spot limits...I will start the targeted cluster tomorrow morning. Let's hope everything will work fine this time.I will let you know anyway. Keep the ticket open for now, please.Best regards.Vincent BosquierUCit[Envoyé de mon Smartphone]Le 10 juin 2019 15:05, Luca Carrogu <notifications@github.com> a écrit :Hi @vbosquier,
as @sean-smith suggested, I would look at the spot instance limits, that is different from the on-demand limits.
Also check at the activity history of the EC2>ASG console

**Comment by vbosquier** [comment]
Ciao Luca.

 

Here is the output of the ASG activity history:

 


Failure

Launching a new EC2 instance

2019 June 11 09:37:25 UTC+2

2019 June 11 09:37:25 UTC+2



Description:DescriptionLaunching a new EC2 instance. Status Reason: Max spot instance count exceeded. Launching EC2 instance failed.


Cause:CauseAt 2019-06-11T07:37:17Z a user request update of AutoScalingGroup constraints to min: 100, max: 500, desired: 100 changing the desired capacity from 200 to 100. At 2019-06-11T07:37:23Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 97 to 100.

 

We have a limit to 100 on the number of spot instances in the account.
Benjamin has opened a ticket on the support of the account: https://console.aws.amazon.com/support/home?#/case/?caseId=6150390111 <https://console.aws.amazon.com/support/home?#/case/?caseId=6150390111&displayId=6150390111&language=en> &displayId=6150390111&language=en

 

Please can you help as fast as possible on this ticket to increase our Spot Limit to 500, so that we can go on with our cluster: we are at TERATEC showing how easy it is to launch a HPC cluster on AWS! ;-)

 

Best regards,

Vincent.

__________________________________________________________

Vincent BOSQUIER

Discover UCit at www.ucit.fr <http://www.ucit.fr/> 

 

The information in this email is confidential and may be legally privileged. If you are not the intended recipient of this message, any review, disclosure, copying, distribution, retention, or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. If you are not the intended

 

De : Luca Carrogu <notifications@github.com> 
Envoyé : lundi 10 juin 2019 15:06
À : aws/aws-parallelcluster <aws-parallelcluster@noreply.github.com>
Cc : vbosquier <vincent.bosquier@ucit.fr>; Mention <mention@noreply.github.com>
Objet : Re: [aws/aws-parallelcluster] Cluster can't launch more than 99 nodes (#1115)

 

Hi @vbosquier <https://github.com/vbosquier> ,
as @sean-smith <https://github.com/sean-smith>  suggested, I would look at the spot instance limits, that is different from the on-demand limits.
Also check at the activity history of the EC2>ASG console

**Comment by lukeseawalker** [comment]
Limit increased, please check

**Comment by lukeseawalker** [comment]
confirmed working. closing.
