### ISSUE TITLE
Combined spot/ondemand fleet

### ISSUE THREAD

**Issue by chambm** [aws/aws-parallelcluster#112]
Could cfncluster automagically handle two AWS ASGs so that we could use spot instances for short jobs that it won't hurt to have to restart, and ondemand instances for long jobs (e.g. > 1h)? It's worth paying a little bit more to not have to wait for a long job to rerun.

Also, is there a way to get CFN or cfncluster to automatically determine a good spot price for an AZ and instance type based on relative parameters, like "less than ondemand price" or "less than 2*ondemand price"? Could code such a thing up myself, but I'm not sure how it would plug in to cfncluster to make it easy for my end users to use without learning about the intricacies of spot pricing.

**Comment by mohanasudhan** [comment]
Easy way to achieve two ASG here is have two different cfncluster cluster. But take you point of having multiple different compute config in single cluster. I will add to enhancement will prioritize it.

**Comment by demartinofra** [comment]
This was addressed by ParallelCluster 2.9 that introduced support for multiple queues and multiple instance types with Slurm.
