### ISSUE TITLE
Shared EBS volume deleted by another cluster before mounting

### ISSUE THREAD

**Issue by tgjohnst** [aws/aws-parallelcluster#1121]
**Environment:**
 - AWS ParallelCluster version 2.3.1
 - OS: ubuntu1604
 - Scheduler: sge
 - Master instance type: r3.2xlarge
 - Compute instance type: r3.2xlarge

**Bug description and how to reproduce:**
My team are long-time users of parallelcluster/cfncluster and are migrating to a new AWS environment so I've been working on updating and recreating our cluster. In doing so, I'm encountering errors during the master node creation step where parallelcluster is trying to attach a volume (the shared ebs volume) that does not actually exist. I checked in the AWS console and it looks like this shared 20GB volume is not being created during cluster creation. When the _master_base_config recipe is run during setup and pulls the volume name from /etc/parallelcluster/cfnconfig (where does that come from?), it tries to attach this nonexistent volume resulting in an error.

I have tried our usual template (see config_redacted.txt) below which uses default EBS settings, as well as uncommenting the ebs custom1 section and using that instead, same error. 

Notable changes since we last had this working are:
- we're working within a new account/vpc
- we've upgraded from 2.1.1 to 2.3.1

**Additional context:**

[config_redacted.txt](https://github.com/aws/aws-parallelcluster/files/3274029/config_redacted.txt)

[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/3274009/cloud-init.log)

[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/3274010/cloud-init-output.log)

[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/3274006/cfn-init.log)

Any ideas or suggestions as I continue to troubleshoot this?

Thanks in advance!

**Comment by tgjohnst** [comment]
Update - I tried with a 2.4.0-based AMI and pcluster 2.4.0 and am still encountering the issue.

**Comment by lukeseawalker** [comment]
Looking into it.
/etc/parallelcluster/cfnconfig contains the configuration.

The configuration is not well formed, you are using section that are commented out, e.g. 
"efs_settings = customfs" points to "#[efs customfs]"

(minor) the configuration is an old one, because the scaling parameters changed since 1.6.0

Can you check the events of the "EBS CFN stack" in the CloudFormation console?

**Comment by tgjohnst** [comment]
Thanks @lukeseawalker  for the config suggestions! The EFS section was commented out recently during some testing but I wasn't aware of the changes to scaling parameters, will update those to the latest. 

I've confirmed via CloudTrail that the other cluster in the same subnet is the source of the DeleteVolume API call, and am confirming with the maintainer the details of that cluster. In the meantime, I tried again and took a look at the CFN stack events and it looks normal - the stack still thinks the volume is there, and there is no delete event logged (screenshots are after the volume disappears). 

![pcluster_cfnstack_events](https://user-images.githubusercontent.com/5710633/59384056-2a4d0b80-8d16-11e9-8307-f18b93442a42.png)
![pcluster_cfnstack_resources](https://user-images.githubusercontent.com/5710633/59384057-2a4d0b80-8d16-11e9-8e32-2a95772e9629.png)
![cloudtrail_log_volume521](https://user-images.githubusercontent.com/5710633/59384054-2a4d0b80-8d16-11e9-9a7a-6c8f8c217937.png)

**Comment by tgjohnst** [comment]
Looked into this further and it turns out the other cluster was running a cleanup script that checked for and deleted unattached volumes matching certain specs every few minutes. The problem was not related to parallelcluster itself, so I am going to close this issue.

**Comment by lukeseawalker** [comment]
Cool! Thank you for the update!
