### ISSUE TITLE
Cluster Builds With No Public IPs Fail

### ISSUE THREAD

**Issue by CloudlightCoUk** [aws/aws-parallelcluster#1129]
**Environment:**
 - AWS ParallelCluster 2.4.0
 - OS: Any
 - Scheduler: Any
 - Master instance type: Any
 - Compute instance type: Any

**Bug description and how to reproduce:**
Build a cluster in a private subnet with no public IP option set (use_public_ips = false). The build will failwith this CFN error:
"Attribute: PublicIp was not found for resource: i-074c51c75c04e858d. Rollback requested by user."

This seems to be a bug introduced in the latest version, and relates to the 'MasterPublicIp' condition not being set on the template outputs for the public IP related items (MasterPublicIP, GangliaPublicURL). Both these outputs do a get attribute on the master server public IP, as it doesn't have one, bad things happen.

This is easily seen by comparing lines 4749-4795 in the CFN template for version 2.3.1 with lines 4850-4894 in 2.4.0

**Comment by sean-smith** [comment]
Hi @CloudlightCoUk, thanks for reporting this. I'm looking at your updated lines now

https://github.com/aws/aws-parallelcluster/blame/develop/cloudformation/aws-parallelcluster.cfn.json#L4850

**Comment by sean-smith** [comment]
Ah ok, I made a change to display the public ip address on instances even when `use_public_ips = false` so that `pcluster ssh` will work for those clusters (not through EIP)  https://github.com/aws/aws-parallelcluster/commit/183a4ed86022e318e28662e0acf7246bf744af3a

**Comment by CloudlightCoUk** [comment]
That makes sense. The issue is when you build a cluster with no public IPs. This is the case for the project I'm working on. The clusters are reached via a VPN from the customer's premises. We have no need for public IPs so build our nodes in a private subnet.

**Comment by sean-smith** [comment]
Ok, I'll post a PR shortly

**Comment by sean-smith** [comment]
Ok, it's fixed. You can re-create a cluster and it'll work
