### ISSUE TITLE
Additional permission needed for EFS sanity checks

### ISSUE THREAD

**Issue by tgjohnst** [aws/aws-parallelcluster#1139]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 2.4.0
 - OS: ubuntu
 - Scheduler: sge
 - Master instance type: r3.2xlarge
 - Compute instance type: r3.2xlarge

**Bug description and how to reproduce:**
Using the ParallelClusterUserPolicy permissions specified in docs, I get an error during sanity checking if an EFS volume is specified. 
`Config sanity error on resource EFSFSId: User is not authorized to perform that action on the specified resource`

In CloudTrail, it looks like this is due to a call to describeMountTargetSecurityGroups. I can recapitulate the error by calling that directly in awscli while using an instance role with ParallelClusterUserPolicy attached:
`aws efs describe-mount-target-security-groups --region us-east-1 --mount-target-id fsmt-abcd1234`
`An error occurred (AccessDeniedException) when calling the DescribeMountTargetSecurityGroups operation: User is not authorized to perform that action on the specified resource`

In the [AWS docs for that endpoint](https://docs.aws.amazon.com/efs/latest/ug/API_DescribeMountTargetSecurityGroups.html), it looks like there is an additional EC2 permission required (ec2:DescribeNetworkInterfaceAttribute) which is not specified in the parallelcluster IAM docs. I'm adding a pull request momentarily to include that permission.

**Comment by lukeseawalker** [comment]
Thank you @tgjohnst

**Comment by lukeseawalker** [comment]
Hi @tgjohnst,
the docs changed location, see https://github.com/aws/aws-parallelcluster#documentation for details

I have created a PR for your issue https://github.com/awsdocs/aws-parallelcluster-user-guide/pull/1
