### ISSUE TITLE
awsbatch sanity_check broken in 2.4.0

### ISSUE THREAD

**Issue by jojje** [aws/aws-parallelcluster#1144]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.4.0
 - OS: alinux
 - Scheduler: awsbatch
 - Master instance type: m5.xlarge
 - Compute instance type: optimal

**Bug description and how to reproduce:**
pcluster's instance validation does not accept its own default value when scheduler awsbatch is chosen. Instead the program raises the following exception:  `Unexpected error of type AttributeError: 'NoneType' object has no attribute 'get'`.

The error originates from [this](https://github.com/aws/aws-parallelcluster/blob/11985943eab85104467353f23727c8dfb378bf86/cli/pcluster/config_sanity.py#L619) location in the code.

To reproduce:

1. Ensure a clean environment by deleting `~/.parallelcluster`
2. Run `pcluster configure` to setup the default values.
3. Specify `awsbatch` as the scheduler to use,  but rely on pcluster's own defaults for the scheduler's configuration: `sed -i'' '/cluster default/a scheduler = awsbatch' ~/.parallelcluster/config`
4. Run `pcluster configure` again. Accept the suggested values and once all prompts are done with and the program performs validation of the input values, the exception is raised. The same error happens if you try to create a cluster.

**Additional context:**
Here is a sample config file with vpc and subnet masked.
```
[aws]
aws_region_name = eu-west-1

[cluster default]
scheduler = awsbatch
vpc_settings = public
key_name = mykey
scheduler = awsbatch

[vpc public]
vpc_id = vpc-<snip>
master_subnet_id = subnet-<snip>

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

**Comment by sean-smith** [comment]
Thanks for reporting this. We'll fix it asap

**Comment by jojje** [comment]
Thanks shawn, the workaround allowed me to _create_ a batch cluster.

**Comment by sean-smith** [comment]
It's been fixed, you can re-enable `config_sanity` and it'll work now

**Comment by jojje** [comment]
Well not now, but hopefully soon, since there are still a few gates left before the proposed change makes it into the public.  PR #1146 has to be merged. Then a new package has to be built and pushed out to [pypi](https://pypi.org/project/aws-parallelcluster/).

**Comment by sean-smith** [comment]
Actually this doesn’t need to be published on pypi. We just updated the s3 file it pulls from

**Comment by demartinofra** [comment]
Just to clarify the issue was with the sanity_check for awsbatch and not the support for awsbatch itself. sanity_check is fixed and should be working right now. Resolving...Feel free to reopen if needed and thanks again for reporting this.
