### ISSUE TITLE
Unable to launch cluster- on-demand capacity exceeded

### ISSUE THREAD

**Issue by azzaea** [aws/aws-parallelcluster#1151]
**Environment:**
 - AWS ParallelCluster [ aws-parallelcluster-2.4.0]
 - OS: [ubuntu1604]
 - Scheduler: [slurm]
 - Master instance type: [t2.micor]
 - Compute instance type: [m5a.24xlarge]
- initial_queue_size = 36
- max_queue_size = 36
- maintain_initial_size = true

**Bug description and how to reproduce:**
With the setting above on my configuration file, I get the error:
```
$ pcluster create -c pcluster.config aws-slurm-cluster
Beginning cluster creation for cluster: aws-slurm-cluster
ERROR: The configured max size parameter 36 exceeds the On-Demand capacity on AWS.
Insufficient capacity.
```

**Comment by demartinofra** [comment]
This error means that there aren't 36 m5a.24xlarge in the region/az you are trying to create the cluster in. What is the region/az you are using for your cluster (this depends on the az used for the compute subnet)?

If you still want to create a cluster in this AZ you could disable this check by adding `sanity_check = false` in the global config section or you could use a lower max_queue_size and then eventually raise it in the ASG. But be aware that probably you are not gonna get the expected capacity due to unavailability.

**Comment by demartinofra** [comment]
Also I would discourage you to pick such a small instance as master node. See https://github.com/aws/aws-parallelcluster/wiki/Best-Practices#master-instance-type

**Comment by azzaea** [comment]
That was quick! Thank you

I'm on `us-east-2` AZ, and requested to increase the `m5a.24xlarge` instances limit to 36 (which I can see propagated to my EC2 interface).

**Comment by azzaea** [comment]
Ideally, I would have all my machines up at the same time (without interruption), so my scalability analysis is not confounded by the instantiation and termination of instances overhead.

By requesting an increase on the m5a.24xlarge limit to 36, I'm understanding that I will can have up to this number of instances up at once. Is this logic not right?

On a relevant note, now I'm changing my master note type to `m5a.2xlarge`. 

The objective of my set up is to stress-test a couple of workflow management systems (nextflow, cromwell, toil, swift/t..) with many tasks (to see where they break), so not a lot of data will be generated anyway. 
Would  `m5a.2xlarge` as a master note still not be enough?

**Comment by demartinofra** [comment]
Your account limits are ok, the problem is the AWS capacity in that AZ which is insufficient for that specific instance type. 

If you could switch region, that capacity should be available in `us-east-1` and specifically in the AZs with the following ZoneId: `use1-az2, use1-az4, use1-az5`. You can get the mapping between az and zone id by using the following aws cli command: `aws ec2 describe-availability-zones --region us-east-1`

I think `m5a.2xlarge` is more than a reasonable choice for this use case.

**Comment by azzaea** [comment]
Nice, thank you. in this case, I will request increasing the limit on `m5a.24xlarg` on the `us-east-1` region, and relaunch.

I don't see a way to specify the  `ZoneId` as part of the configuration options [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/aws.html), so can I assume that pcluster will natively take care of it?

**Comment by azzaea** [comment]
Thank you for the help @demartinofra ! I figured I could specify the ZoneId via the subnet- and it worked :)

I'm closing this ticket now.

**Comment by azzaea** [comment]
Actually, I'm reopening the issue. I got a little more greedy and increased my queue size to 100. What happens now is that I get the error below. Is this to say I should lower my queue size?
```
$ pcluster create -c pcluster.config aws-slurm-cluster
Beginning cluster creation for cluster: aws-slurm-cluster
Creating stack named: parallelcluster-aws-slurm-cluster
Status: ComputeFleet - CREATE_IN_PROGRESS                                       
Rate exceeded
```

**Comment by demartinofra** [comment]
I'm afraid you simply reached the limit on the CloudFormation API call for describe_stack but stack creation shouldn't have been affected. 

You can run a `pcluster status cluster-name` or a `pcluster list` to see if the cluster got created correctly. Alternatively you can look at the CloudFormation console in your AWS account.

**Comment by azzaea** [comment]
Well, then how to work around that? I can confirm the same thing from the CloudFormation console.
```
$ pcluster status aws-slurm-cluster
Status: ROLLBACK_COMPLETEws-slurm-cluster - ROLLBACK_COMPLETE                   
2019-06-19 19:24:50.040000+00:00 CREATE_FAILED AWS::AutoScaling::AutoScalingGroup ComputeFleet Your quota allows for 0 more running instance(s). You requested at least 1. Launching EC2 instance failed.
$
$ pcluster list
aws-slurm-cluster  ROLLBACK_COMPLETE  2.4.0
```

**Comment by demartinofra** [comment]
That error appears when you hit the limit of EC2 instances for your account.
- First of all you could use [TrustedAdvisor](https://console.aws.amazon.com/trustedadvisor/home?region=us-east-1#/category/service-limits) to understand if the limits for the instance type you are trying to use are the expected ones
- Also you can look at [EC2 limits](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Limits) to understand if you are allowed to run the requested on-demand capacity.

Just to confirm: do you still have `sanity_check = true` in your global section of the config? Cause that should have detected account limits before starting the creation of the cluster. Maybe the limit you are hitting is on the number of EC2 instances you can run and we might not be verifying this upfront.

**Comment by azzaea** [comment]
Hello again,
I do confirm the following:
* Yes, I have `samity_check = true` in the configuration file I use to create the cluster.
* The limit on my account for `m5a.24xlarge` is actually 100 (which is the value listed for both "Running On-Demand EC2 instances" and "Running On-Demand m5a.24xlarge instances" on the EC2 limits page).
* On the TrustedAdvisor link, I don't see limits on pcluster per say, but on CloudFormation, my limit is 200 resources, 100 mappings, 200 stacks, 500 stack instances per stack set)

**Comment by demartinofra** [comment]
The error is coming from EC2 AutoScaling which seems to be unable to allocate the requested capacity although ParallelCluster sanity_check should verify the account limits.

If you confirmed that the limit for Running On-Demand m5a.24xlarge instances in the us-east-1 region is 100 then you might open an [AWS technical support case](https://console.aws.amazon.com/support/cases?#/create) to understand why ASG is unable to provide those and we might be able to follow up internally.

What we can do here is to double check that the subnet used for the compute nodes of the cluster matches one of the zone-ids I provided above. 

Let's check the output of the following command: `aws ec2 describe-availability-zones --region us-east-1` and also let's verify what is the AZ of the subnet used for the cluster. This depends on your cluster config: for example if you are specifying only master_subnet_id than that is the subnet we need to look for otherwise if you are using compute_subnet_id we need to look into this. Could you please attach your cluster config as well?

**Comment by azzaea** [comment]
Thank you @demartinofra 
I'm attaching the cluster configuration file [here](https://github.com/aws/aws-parallelcluster/files/3315456/pcluster.config.txt), but here are a few comments to the points above:
* I do confirm that the limit on the `us-east-1` regoin of the `m5.24xlarge` is actually 100 (snapshot below) 
![image](https://user-images.githubusercontent.com/11329665/59940179-4e1cf980-945a-11e9-8883-43b5c5b67242.png)
* The `ec2 describe-availability-zones` command in the specified region gives the 6 expected availability zone (also attached [here](https://github.com/aws/aws-parallelcluster/files/3315472/describe_AZ.txt) )
* I'm only using 1 subnet_id, `subnet-29c01f61` which corresponds to zoneID `us-east-1c`

I will opent the technical support case too

**Comment by sean-smith** [comment]
Ok, there's one more limit here that you're hitting, which is `Running on-demand EC2 Instances`. When ParallelCluster launches a cluster, it launches 100 compute and 1 instance for the head node. Please request a limit increase for that limit through the EC2 console.

**Comment by azzaea** [comment]
I'm not sure what the appropriate choice would be in the menu [here](https://console.aws.amazon.com/support/cases#/create?issueType=service-limit-increase&limitType=ec2-instances), but I just submitted an increase for `Limit Increase: EC2 Reserved Instance Purchase Instances`, and explained in the chat box.

This might partially solve the problem though, because I still hit a limit when requesting as few as 80 compute instances with the same configuration file:
```
$ pcluster create -c pcluster.config aws-slurm-cluster    # The same error message with queue size of 100, 90, 86,80 in pcluster.config
Beginning cluster creation for cluster: aws-slurm-cluster
Creating stack named: parallelcluster-aws-slurm-cluster
Status: ComputeFleet - CREATE_IN_PROGRESS                                       Rate exceeded
```

**Comment by sean-smith** [comment]
`Rate Exceeded` is not the issue, all that's saying is the CloudFormation describe stack call (to show stack status) has exceeded the api rate limit. The CloudFormation create is happening asynchronously in the background, you can Ctrl-c out of it and it'll continue creating. 

The `Limit Increase: EC2 Reserved Instance Purchase Instances` is not the correct limit.

Change `Running On-Demand EC2 instances` to something higher than 100, for example 200. This is the number of instances you can launch concurrently. At this moment it's 100 and you tried to launch 101 which failed.

**Comment by azzaea** [comment]
I submitted another request for this. I can't be granted 200 at the moment (already tried that before), but maybe the ondemand instances can be increased to 101.

Meanwhile, I do confirm that pcluster still fails when the cluster size is much smaller (80 compute and 1 head instances), which is well below my current limit of 100 
"Running on-demand EC2 Instances" though.

**Comment by sean-smith** [comment]
What's your limit for `m5a.2xlarge`?

**Comment by azzaea** [comment]
20

**Comment by sean-smith** [comment]
hmmm, and it failed with same error message?

**Comment by azzaea** [comment]
Yes, exactly.

**Comment by sean-smith** [comment]
Please look at the Autoscaling logs, which you can find by going to `EC2 Console > Autoscaling > parallelcluster-[cluster_name]` then click on `Activity History` tab.

**Comment by azzaea** [comment]
Thank you @sean-smith . The `Activity History` shows that 80 instances could be launched, and I'm attaching a snapshot below (my current screen is rather small, but I can switch to another larger screen if-need-be)

![autoscaling_hist](https://user-images.githubusercontent.com/11329665/60042326-bf101b80-96bd-11e9-8a34-a26b5e39eaf5.png)


Note that this is from a cluster I'm trying right now- as the support team has gracefully increased my limit on `Running on-demand EC2 Instances` to 101.

I will wait a bit then refresh the table. Maybe it works?

**Comment by azzaea** [comment]
Wow! It worked!

I just refreshed that table, and it nicely shows the 100 instances launched. Also, checking the command line confirms that everything is as intended:
```
$ pcluster list
aws-slurm-cluster  CREATE_COMPLETE  2.4.0
$
$ pcluster status aws-slurm-cluster
Status: CREATE_COMPLETE
MasterServer: RUNNING
MasterPublicIP: 3.220.80.129
ClusterUser: ubuntu
MasterPrivateIP: 172.31.27.132
```
Thank you for your patience on this one!  It seems that all was needed all along was to actually give it some time. Your hint was right on spot.

Thank you again.
I will now close this issue.
