### ISSUE TITLE
Not able to administer my SGE

### ISSUE THREAD

**Issue by radaniba** [aws/aws-parallelcluster#1159]
**Environment:**
 - AWS ParallelCluster 2.3.1
 - OS: ubuntu 14
 - Scheduler: SGE
 - Master instance type: C4
 - Compute instance type: C4

**Bug description and how to reproduce:**
I am trying to run this command to enable my queue
```
qmod -e all.q@*
```

And when I change to sgeadmin user, I still have permission issues

```
(base) ubuntu@ip-xxxxx:~$ sudo su sgeadmin
sgeadmin@ip-xxxx:/home/ubuntu$ qmod -e all.q@*
ubuntu - you have no permission to modify queue "all.q@ip-xxxx.us-west-2.compute.internal"
```
I tried to add ubuntu as a manager

```
sgeadmin@ip-xxxx:/home/ubuntu$ qconf -am ubuntu
denied: client (ip-xxx.us-west-2.compute.internal/qconf/1) uses old GDI version 6.2u5 while qmaster uses newer version 8.1.9
denied: "ubuntu" must be manager for this operation
```

My all.q seems to be not enabled and I am stuck not being able to edit my SGE cluster created by ParallelCLuster

**Comment by sean-smith** [comment]
Try as root `sudo su`

**Comment by radaniba** [comment]
@sean-smith  but it is still throwing : denied: ubuntu must be manager for this operation

**Comment by sean-smith** [comment]
Hi @radaniba I was able to get this working as root. I only needed to set `SGE_ROOT`.

```bash
ubuntu@ip-172-31-38-29:~$ sudo su
root@ip-172-31-38-29:/home/ubuntu# export SGE_ROOT=/opt/sge
root@ip-172-31-38-29:/home/ubuntu# /opt/sge/bin/lx-amd64/qmod -e all.q@*
Queue instance "all.q@ip-172-31-38-249.ec2.internal" is already in the specified state: enabled
root@ip-172-31-38-29:/home/ubuntu#
```

**Comment by sean-smith** [comment]
Can I ask why you’re using Ubuntu1404 and not Ubuntu1604?

On Jun 27, 2019, at 12:35 PM, Sean Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @radaniba<https://github.com/radaniba> I was able to get this working as root. I only needed to set SGE_ROOT.

ubuntu@ip-172-31-38-29:~$ sudo su
root@ip-172-31-38-29:/home/ubuntu# export SGE_ROOT=/opt/sge
root@ip-172-31-38-29:/home/ubuntu# /opt/sge/bin/lx-amd64/qmod -e all.q@*
Queue instance "all.q@ip-172-31-38-249.ec2.internal<mailto:all.q@ip-172-31-38-249.ec2.internal>" is already in the specified state: enabled
root@ip-172-31-38-29:/home/ubuntu#

**Comment by radaniba** [comment]
Thank you that solved my issue after exporting SGE_ROOT, thank you so much and yes I am using ubuntu 14
