### ISSUE TITLE
Orye lost communucaton

### ISSUE THREAD

**Issue by mukulagrawal78** [aws/aws-parallelcluster#1163]
I am having some serious problems with cfncluster since today morning.

1/ Orte keeps losing connection to one of the nodes and then whole job crashes.

2/ cfn is getting stuck at "Creating Compute Fleet" forever (30+min) ... but not always. I got some attempts go successful. No errors are shown anywhere. Cfn-init has no indications of anything bad.

3/ Erratic behavior in scaling. As soon as I submit an SGE job, cluster scales up to max nodes specified even though job didn't ask for it. And then within 2minutes it started to terminate all nodes. Then it starts some more nodes again but not max this time.

4/ seems like it is starting nodes in pair .. if I asked for 2 nodes it started 4. But MPI processes are running only on 2 and other has activity in them.

Any guess what could be wrong? Have yiu encountered this before? Everything was working sensible until yesterday. 

I also got a quick question:

Does cfn has any dependence on MPI library or can I install something else? Do I need to change any config if I do so?

I believe MPI library on cfn AMI needs to match with the MPI used to compile the application, is that right?

Can above behavior happen if there is a mismatch in MPI version?

Do you only look for jobs waiting in queue or does scaling behavior also depend on "-pe parameter" in sge submission?

**Comment by sean-smith** [comment]
Hi @mukulagrawal78 I'm sorry to hear about all your troubles with cfncluster. Can I ask what version you're using?

We've made a ton of improvements to scaling and to mpi (we install openmpi 3.1.4) in ParallelCluster `2.4.0`. It might be a good time to upgrade.
