### ISSUE TITLE
Master/ComputeFleet CREATE FAILED or CREATE SLOW

### ISSUE THREAD

**Issue by hy714335634** [aws/aws-parallelcluster#1164]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 2.4.0
 - OS: alinux/ubuntu1604
 - Scheduler: SGE
 - Master instance type: m4.xlarge
 - Compute instance type: c5.4xlarge

**Bug description and how to reproduce:**
Last month,I create a cluster by parallelcluster  just need wait about 5min，but now ,I have to wait 20 min or more,and sometimes I will get a failed message , the screenshots is below，```MasterServer/ComputeFleet - CREATE_IN_PROGRESS``` spend too much time . Also the compute node scaling up have spend more time than last month.
By the way， I‘m from china，I am not sure if this problem is related to the package install source.

**Additional context:**
 - configuration
[aws]
aws_region_name = cn-north-1
aws_access_key_id = xxx
aws_secret_access_key = xxx

[vpc public]
vpc_id = vpc-0e66326a
master_subnet_id = subnet-e953c58d

[cluster GATK-pipeline-ubuntu]
base_os = alinux
custom_ami = xxx
vpc_settings = public
key_name = xxx
compute_instance_type = c5.4xlarge
master_instance_type =m4.xlarge
compute_root_volume_size = 50
master_root_volume_size = 50
ebs_settings = genomes
s3_read_resource = xxx
scaling_settings = ASG
initial_queue_size = 1
max_queue_size = 2
maintain_initial_size = false

[scaling ASG]
scaledown_idletime = 2

[ebs genomes]
shared_dir = xxx
ebs_snapshot_id = xxx
volume_type = gp2
volume_size =  1024

- screenshots, if useful
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/17355229/60379626-cee68180-9a68-11e9-837e-cc3dbeaeb0e6.png">

- /var/log/cfn-init.log
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/3341381/cloud-init.log)

- /var/log/cloud-init-output.log
[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/3341384/cloud-init-output.log)

**Comment by sean-smith** [comment]
Hi @hy714335634 

In China we have lots of retries for non-localized resources (which unfortunately we have to have). The best advice I can give is to use one of the [pre-built ami's](https://github.com/aws/aws-parallelcluster/blob/develop/amis.txt). I see from the logs you sent there was SSL failures which are indicative of the great firewall. I'd advice either use one of our pre-built ami's or build your own with `pcluster createami`.

**Comment by hy714335634** [comment]
Hi @sean-smith 
Thanks for your advices.It's work good when I try to use pre-built amis or new ami create by pre-built amis, and then I try to use ```pcluster createami``` to build a new ami, It's return ```Packer status: exit code 0``` and ```AMI ID```，but I got a error message when ```pcluster create``` by this new AMI.
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/17355229/60481832-be7d1380-9cc1-11e9-9813-f0a58c46ac0e.png">

the ami ```ami-xxx``` which have ```CREATE FAILED``` or ```CREATE SLOW``` problem is create by parallelcluster(version 2.3.1) pre-built AMI . I found the pre-built AMI ID is different between different version.Do I need to create a new AMI every time I update the parallelcluster?

**Comment by enrico-usai** [comment]
Hi @hy714335634 ,
yes, you need to re execute the `pcluster createami` command when using a new ParallelCluster version.

**Comment by hy714335634** [comment]
Hi @enrico-usai 
It's create failed when I create cluster use this ami which I get by ```pcluster createami```, and the screenshot is in the previous reply.
