### ISSUE TITLE
ec2-user uid in ParalleCluster AMI is different from standalone AMI

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-parallelcluster#1176]
The ec2-user created in the Amazon Linux AMI has a UID 500.
In standalone Amazon Linux AMI, the UID is 1000.

It can be a problem for EFS: https://docs.aws.amazon.com/en_us/efs/latest/ug/accessing-fs-nfs-permissions.html

**Comment by skypurplecloud** [comment]
I also noticed that AWS have changed this between v28 of the Deep Learning Amazon Linux AMI and v30 of this AMI.  This is causing issues with EFS using ec2-user from both machines.  earlier is 500, later is 1000.  Is this now changed permanently, so if I change all permissions on the EFS mount and only use the new AMIs - will that work going forward?  Did they now standardise UID and GID as 1000?

**Comment by lukeseawalker** [comment]
Closing this since it was probably referring to Amazon Linux 1 (dropped in PCluster version2.11).

For Amazon Linux 2, both PCluster AMI and vanilla Amazon Linux 2 AMI have the same ID for ec2-user:
```
[ec2-user@ip-172-31-46-218 ~]$ id
uid=1000(ec2-user) gid=1000(ec2-user) groups=1000(ec2-user),4(adm),10(wheel),190(systemd-journal)
```
