### ISSUE TITLE
EFA enabled OpenMPI not built with Slurm 

### ISSUE THREAD

**Issue by tamaradanceva** [aws/aws-parallelcluster#1182]
**Environment:**
 - AWS ParallelCluster / CfnCluster version aws-parallelcluster-2.4.0
 - OS: ubuntu1604
 - Scheduler: slurm
 - Master instance type: c5.xlarge
 - Compute instance type: c5n.18xlarge
 - enable_efa = compute
- placement_group = DYNAMIC

**Bug description and how to reproduce:**
EFA enabled openmpi/3.1.4 is not built with Slurm support. I am not sure if this is a bug or not. I tried running with mpirun on multiple nodes as well but it hangs. Ideally, we would like to run jobs with Slurm. Could you please tell me if this is supported and what is the intended workflow?

**Comment by lukeseawalker** [comment]
Hi @tamaradanceva,
can you please run the following commands:
```
module load openmpi/3.1.4
mpirun --version
ompi_info | grep ras
```

The output should report a line containing `MCA ras: slurm [...]` which implies that openmpi is built with Slurm support

**Comment by lukeseawalker** [comment]
Can you send us a sample submission command to reproduce your problem? Thanks

**Comment by tamaradanceva** [comment]
Hi @lukeseawalker , thanks for the quick response. I get the following error when I run 

`srun -N 4 ./hello_mpi`
I have just created the cluster, so I am just testing with a hello world to see if it works. I have the relevant application solver in another cluster, I would like to switch to an efa interface thoughj.

> OPAL ERROR: Not initialized in file pmix2x_client.c at line 112
> 
> The application appears to have been direct launched using "srun",
> but OMPI was not built with SLURM's PMI support and therefore cannot
> execute. There are several options for building PMI support under
> SLURM, depending upon the SLURM version you are using:
> 
>   version 16.05 or later: you can use SLURM's PMIx support. This
>   requires that you configure and build SLURM --with-pmix.
> 
>   Versions earlier than 16.05: you must use either SLURM's PMI-1 or
>   PMI-2 support. SLURM builds PMI-1 by default, or you can manually
>   install PMI-2. You must then build Open MPI using --with-pmi pointing
>   to the SLURM PMI library location.
> 
> Please configure as appropriate and try again

.

The output from --mpi=list is:
srun: MPI types are...
srun: openmpi
srun: pmi2
srun: none

I get same error for both of these types.

**Comment by lukeseawalker** [comment]
You can let Slurm creates the resource allocation for the job and then use mpirun to launch tasks within the allocated resources.

E.g.
have an MPI "hello world" example
```
cat mpi_hello_world.c

// Copyright 2011 www.mpitutorial.com
//
// An intro MPI hello world program that uses MPI_Init, MPI_Comm_size,
// MPI_Comm_rank, MPI_Finalize, and MPI_Get_processor_name.
//
#include <mpi.h>
#include <stdio.h>
#include <stddef.h>

int main(int argc, char** argv) {
  // Initialize the MPI environment. The two arguments to MPI Init are not
  // currently used by MPI implementations, but are there in case future
  // implementations might need the arguments.
  MPI_Init(NULL, NULL);

  // Get the number of processes
  int world_size;
  MPI_Comm_size(MPI_COMM_WORLD, &world_size);

  // Get the rank of the process
  int world_rank;
  MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

  // Get the name of the processor
  char processor_name[MPI_MAX_PROCESSOR_NAME];
  int name_len;
  MPI_Get_processor_name(processor_name, &name_len);

  // Print off a hello world message
  printf("Hello world from processor %s, rank %d out of %d processors\n",
         processor_name, world_rank, world_size);

  // Finalize the MPI environment. No more MPI calls can be made after this
  MPI_Finalize();
}
```

Compile it
```
mpicc -o mpi_hello_world mpi_hello_world.c
```

Prepare a submission script
```
cat mpi_submit.sh

#!/bin/bash
set -e

rm -f /shared/mpi.out
module load openmpi
mpirun --map-by ppr:1:node "mpi_hello_world" >> /shared/mpi.out
```

Submit the script with sbatch
```
sbatch -N 2 mpi_submit.sh
```

Check the output
```
cat /shared/mpi.out
Hello world from processor ip-172-31-69-247, rank 0 out of 2 processors
Hello world from processor ip-172-31-77-207, rank 1 out of 2 processors
```

**Comment by tamaradanceva** [comment]
I see, thank you very much @lukeseawalker, that works. I would just like to ask one more question before closing the issue, why srun doesn't work in this case?

**Comment by lukeseawalker** [comment]
Because we are not building slurm with `--with-pmix` flag, see https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/recipes/slurm_install.rb#L41

Is this a strict requirement for you?

**Comment by tamaradanceva** [comment]
No, it is not. Thanks a lot again. I will close the issue now.

**Comment by lukeseawalker** [comment]
@tamaradanceva thank you.
