### ISSUE TITLE
fail to register compute nodes to SGE

### ISSUE THREAD

**Issue by porcaro33** [aws/aws-parallelcluster#1183]
**Environment:**
 - AWS ParallelCluster : version 2.3.1
 - OS: CentOS7
 - Scheduler: SGE
 - Master instance type: m5.2xlarge
 - Compute instance type: c5.18xlarge

**Bug description and how to reproduce:**
after rebooting the master node, submitted jobs keep qw status.
Jobwatcher and sqswatcher seem to work normally. I can see the compute nodes' host name in DynamoDB. But those host never show up in qhost.
ParallelCluster continue to fail register compute hosts into SGE.

I restarted jobwatacher and sqswatcher once, but the situation did not change.

**Comment by porcaro33** [comment]
[sqswatcher.txt](https://github.com/aws/aws-parallelcluster/files/3372025/sqswatcher.txt)

[jobwatcher.txt](https://github.com/aws/aws-parallelcluster/files/3372028/jobwatcher.txt)

**Comment by porcaro33** [comment]
my config is below

[aws]
aws_region_name = us-west-2

[vpc HPC_VPC]
master_subnet_id = XXXXXXXXX
compute_subnet_id = XXXXXXXXXX
vpc_id = XXXXXXXX
ssh_from = XXXXXXXX
additional_sg = XXXXXXX
use_public_ips = false

[global]
update_check = true
sanity_check = true
cluster_template = default

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
vpc_settings = XXXXXX
key_name = XXXXXXX

master_instance_type = m5.2xlarge
compute_instance_type = c5.18xlarge
initial_queue_size = 0
max_queue_size = 57
maintain_initial_size = false

scheduler = sge
cluster_type = spot
spot_bid_percentage = 100

ephemeral_dir = /scratch
shared_dir = shared
encrypted_ephemeral = false
ebs_settings = shared

master_root_volume_size = 30
compute_root_volume_size = 30
base_os = centos7
ec2_iam_role = parallecluster_EC2_role

scaling_settings = custom

placement_group = DYNAMIC
placement = compute

post_install = XXXXXXXXXX

extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }

[ebs shared]
volume_type = gp2
volume_size = 4000
encrypted = false

[scaling custom]
scaledown_idletime = 40

**Comment by porcaro33** [comment]
sqswatcher says,
`2019-07-09 07:57:46,060 ERROR [sqswatcher:_process_instance_terminate_event] Instance i-0ae0b84c34839c264 not found in the database.`

I checked the instance-id and private ip between EC2 console and DynamoDB. There are lots of unknown host data on DynamoDB. Some instances are already terminated. Some instances are registered double.

I removed doubled or unknown host info from DynamoDB.

**Comment by lukeseawalker** [comment]
Hi @porcaro33,
in sqswatcher there are a lot of EC2_INSTANCE_TERMINATE events, so it sounds like your post_install script is longer than the scaledown_idletime, same issue reported here https://github.com/aws/aws-parallelcluster/issues/1073

In ParallelCluster 2.4.0 we have improved this behaviour, see 
https://github.com/aws/aws-parallelcluster/blame/develop/CHANGELOG.rst#L58-L59
We are also dumping logs of compute instances that fail initialization, see
https://github.com/aws/aws-parallelcluster/blame/develop/CHANGELOG.rst#L30
so it could help to understand issues on compute nodes side.

**Comment by porcaro33** [comment]
Hi @lukeseawalker 
I extended `scaledown_idletime` a little bit and the scale-up feature is back now.
I will plan the upgrade of ParallelCluster to version 2.4.0.
Appreciate your suggestion:)

**Comment by lukeseawalker** [comment]
@porcaro33 thank you
