### ISSUE TITLE
Feature/documentation: pcluster configure -c expects the full path to the configuration file, not relative to where pcluster is run

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1197]
**Environment:**
 -aws-parallelcluster==2.4.0
 - RHEL 7
 - slurm
 - None
 - None

When running `pcluster configure -c <config_file>`, pcluster expects the full path of the config file, not the relative path to where pcluster is ran. Specifying it as a relative path yields the error:
```python
2019-07-15 12:03:19,188 - DEBUG - pcluster.pcluster - pcluster CLI starting
2019-07-15 12:03:19,194 - DEBUG - pcluster.pcluster - Namespace(command='config\
ure', config_file='ParallelClusterConfig', func=<function configure at 0x7f54a0\
ed0d08>)
2019-07-15 12:03:22,722 - ERROR - pcluster.pcluster - Unexpected error of type \
FileNotFoundError: [Errno 2] No such file or directory: ''
```

The documentation does not explicitly state this. I would be fine with either the documentation being updated, or better yet allow relative paths to be specified.

**Comment by joeydumont** [comment]
Documentation referenced above: https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.configure.html

I tried seeing if that documentation was built from this repo so I could PR this, but I couldn't find it.

**Comment by HLeeHart** [comment]
Docs were updated - see https://github.com/awsdocs/aws-parallelcluster-user-guide/commit/3cb8b50ac18d6bc3219e794b1ad2fb6f17aa36dc

**Comment by joeydumont** [comment]
Actually I haven't any issue with create and other commands so far, only with `configure`. Sorry if that wasn't clear.

**Comment by enrico-usai** [comment]
The patch #1208 has been merged. The fixed CLI will be available with the next release.
