### ISSUE TITLE
Heterogenous compute_instance_type

### ISSUE THREAD

**Issue by cancan101** [aws/aws-parallelcluster#120]
Is there any way to specify to have heterogeneous `compute_instance_type` ? ie if I want 2 `m4.large` and 3 `m4.xlarge` ?

**Comment by dougalb** [comment]
This is currently not possible. CfnCluster uses a single [AutoScalingGroup](http://docs.aws.amazon.com/autoscaling/latest/userguide/AutoScalingGroup.html) for the ComputeFleet and this can only contain a single instance type.

**Comment by enrico-usai** [comment]
I'm going to close this in favour of: https://github.com/aws/aws-parallelcluster/issues/307
