### ISSUE TITLE
t3 series instances cannot be used in China region

### ISSUE THREAD

**Issue by frank622** [aws/aws-parallelcluster#1218]
pcluster latest version
$cat  /home/ec2-user/.parallelcluster/config
.......
maintain_initial_size = false
master_instance_type = t3.medium
........

**Comment by sean-smith** [comment]
Thanks @frank622, Can you provide some more details on the failure:

1. What error message did you get?
2. What region were you in? China currently has `cn-north-1` (Beijing) and `cn-northwest-1` (Ningxia) regions.
3. What version of ParallelCluster are you using?

**Comment by frank622** [comment]
ok..
