### ISSUE TITLE
Pass MASTER_IP to post_install_args

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1220]
**Environment:**
 - aws-parallelcluster-2.4.0
 - OS: alinux
 - Scheduler: slutrm
 - Master instance type: t2.micro
 - Compute instance type: t2.micro

Is is possible to pass the MASTER_IP parameter as a `post_install_args`? I've tried `post_install_args = {MASTER_IP}`, following the `[aliases]` section synta, but this results in `cfn_postinstall_args={MASTER_IP}` in `/etc/parallelcluster/cfnconfig`. The actual master IP does not get substituted.

**Comment by sean-smith** [comment]
Hi @joeydumont,

This is a bit tricky as normally I'd tell you to just get the output `MasterServerPublicIP`. However this output isn't going to be there when the post_install script runs, as the stack hasn't finished creating. 

The other option is to get the stack resource, this will work before the stack goes into `CREATE_COMPLETE`

Here's how we do it in the [ssh function](https://github.com/aws/aws-parallelcluster/blob/develop/cli/pcluster/pcluster.py#L653-L665):

```python
import boto3

aws_region = "us-east-1"
stack_name = "[Your stack name]"

cfn = boto3.client(
        "cloudformation",
         region_name=aws_region
)
resources = cfn.describe_stack_resource(StackName="parallelcluster-"+ stack_name, LogicalResourceId="MasterServer")
master_id = resources.get("StackResourceDetail").get("PhysicalResourceId")

ec2 = boto3.client(
        "ec2",
        region_name=aws_region
)
instance = ec2.describe_instances(InstanceIds=[master_id]).get("Reservations")[0].get("Instances")[0]
ip_address = instance.get("PublicIpAddress")

```

Unfortunately we don't substitute the `config` file but rather when we run `pcluster ssh` it reads that section of the config and substitutes it.

**Comment by demartinofra** [comment]
You could also do the following to get the master fqdn on compute nodes:
```
#!/bin/bash

. "/etc/parallelcluster/cfnconfig"

case "${cfn_node_type}" in
    MasterServer)
        echo "I am the master node" >> /tmp/master.txt
    ;;
    ComputeFleet)
        echo "${cfn_master}"
    ;;
    *)
    ;;
esac
```

**Comment by sean-smith** [comment]
Thanks @demartinofra, I forgot the `cfnconfig` contains the `cfn_master`... but only on the compute nodes.

@joeydumont Here's what that file contains:
```bash
stack_name=parallelcluster-intel-mpi
cfn_preinstall=NONE
cfn_preinstall_args=NONE
cfn_postinstall=NONE
cfn_postinstall_args=NONE
cfn_region=us-east-1
cfn_scheduler=sge
cfn_scheduler_slots=vcpus
cfn_instance_slots=72
cfn_encrypted_ephemeral=false
cfn_ephemeral_dir=/scratch
cfn_shared_dir=/shared
cfn_proxy=NONE
cfn_node_type=ComputeFleet
cfn_cluster_user=centos
cfn_sqs_queue=https://sqs.us-east-1.amazonaws.com/822857487308/parallelcluster-intel-mpi-SQS-PD4EN81U2BIL
cfn_master=ip-172-31-43-191.ec2.internal
```
I recommend you use @demartinofra approach

**Comment by joeydumont** [comment]
I put this in the `post_install` script instead:

```bash
# -- Determine the IP of the master node.
MASTER_IP=
if [ ${cfn_node_type}  == "MasterServer" ]; then
	MASTER_IP=$(hostname)

elif [ ${cfn_node_type} == "ComputeFleet" ]; then
	MASTER_IP=${cfn_master}
fi

MASTER_IP=$(echo ${MASTER_IP} | sed 's/.*-\([0-9]\{1,3\}\)-\([0-9]\{1,3\}\)-\([0-9]\{1,3\}\)-\([0-9]\{1,3\}\).*/\1\.\2\.\3\.\4/')

echo "The master IP is ${MASTER_IP}"
```
