### ISSUE TITLE
Post_install script breaks SGE, but works fine when run manually after installation

### ISSUE THREAD

**Issue by mikerossgithub** [aws/aws-parallelcluster#123]
I have a script to install CUDA on Ubuntu 14.04. If I run the script manually on the master node, then "qsub" to each of the compute nodes, it works fine. However, if I point post_install to the script in the cfncluster config, the result is that CUDA is installed correctly, but SGE commands (qsub, qstat, qhost) fail to be recognized by the system. Files here: 
[sample_config.txt](https://github.com/awslabs/cfncluster/files/384353/sample_config.txt)
[install_cuda.sh.txt](https://github.com/awslabs/cfncluster/files/384354/install_cuda.sh.txt)

**Comment by dougalb** [comment]
Can you share the `/var/log/cfn-init.log` and `/var/log/cloud-init-output.log` from the MasterServer. Also when you say the SGE commands failed to be recognized by the system, what does that mean? Are you waiting for the cluster state to reach **CREATE_COMPLETE** before logging in?

**Comment by mikerossgithub** [comment]
Thank you for your response. I am indeed waiting for CREATE_COMPLETE, which runs successfully. To be more clear: when I create the cluster without post_install, I can run the script manually (to install CUDA) then call SGE commands like "qhost".  When the script is called by post_install, it still correctly installs CUDA, but SGE does not appear to be installed. See the bash paste below. I have attached the logs you requested.

Here is the result of calling qhost (or any other sge-command):
$ qhost
The program 'qhost' is currently not installed. You can install it by typing:
sudo apt-get install gridengine-client

[cloud-init-output.log.txt](https://github.com/awslabs/cfncluster/files/387524/cloud-init-output.log.txt)
[cfn-init.log.txt](https://github.com/awslabs/cfncluster/files/387523/cfn-init.log.txt)

**Comment by dougalb** [comment]
Is it possible for you to test using the latest CfnCluster 1.3.1 release? The NVIDIA and CUDA SDK are now included as part of the AMI.

**Comment by demartinofra** [comment]
I'm going to resolve this one due to inactivity. If the problem still persists on the newer versions of ParallelCluster feel free to open a new one.
