### ISSUE TITLE
Master unable to SSH into the Compute the Node.

### ISSUE THREAD

**Issue by ganderaj** [aws/aws-parallelcluster#1230]
**Environment:**
 - AWS ParallelCluster version [2.4.0]
 - OS: CentOS 7.6
 - Scheduler: SGE
 - Master instance type: c5.2xlarge
 - Compute instance type: c5.9xlarge

**Bug description and how to reproduce:**
qhost does not show up the available running Compute Nodes. Every time a compute nodes is brought up, it will stay there for a while, gets terminated, ASG brings up a new compute node and the cycle repeats.

Attached the SQSWatcher log file from the Master.
[sqswatcher.log](https://github.com/aws/aws-parallelcluster/files/3433027/sqswatcher.log)

**Comment by demartinofra** [comment]
Hi,

Compute nodes are replaced when something fails at start-up or if they fail to attach to the scheduler. This might be due to a failing post_install script or custom ami setup.
Could you check and see if there are any files in `/home/logs/compute` and if so attach one of the archives? Also could you please share your cluster config?

Thanks!

**Comment by ganderaj** [comment]
Hi @demartinofra 

Sorry for the delayed response. 
---
The reason why I opened this issue is resolved by running packer on top of exiting custom ami. (NFS Mount was an issue, this lead to no shared home directory, hence couldn't join.)
---
However, I have encountered an issue on another development cluster where I have made a change recently on ASG by adding "Scheduled Action" which I removed later. The issue is that, compute nodes are brought up by the SGE job but the job does stuck in "qw" state while the computes "Live, Die & Repeat". Upon investigating further I have made below findings-

1. Problem with executing the remote commands on sqswatcher. (please refer to logs attached.)
2. Some daemon is failing to add the hosts to @allhosts groups with an error "error writing object "all.q/ip-x.x.x.x.yyyyyy.zzz.com" to spooling database"
3. Error in executing the remote command with a log file attached.

[execd_install_ip-10-246-40-78_2019-07-31_23:15:10.log](https://github.com/aws/aws-parallelcluster/files/3454875/execd_install_ip-10-246-40-78_2019-07-31_23.15.10.log)
[jobwatcher.log](https://github.com/aws/aws-parallelcluster/files/3454876/jobwatcher.log)
[sqswatcher.log](https://github.com/aws/aws-parallelcluster/files/3454877/sqswatcher.log)

**Comment by enrico-usai** [comment]
I'm going to close this issue in favour of https://github.com/aws/aws-parallelcluster/issues/1247
