### ISSUE TITLE
cluster load getting restricted to only one compute node in parallel cluster

### ISSUE THREAD

**Issue by vinkas10** [aws/aws-parallelcluster#1240]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [aws-parallelcluster]
 - OS: [Centos 7]
 - Scheduler: [SGE]
 - Master instance type: [c4.8xlarge]
 - Compute instance type: [c4.8xlarge]

Hi All,

I am running an molecular dynamics simulation using NAMD application. I am using openMPI modules provided by AWS parallel cluster for parallelizing the job across multiple nodes. The job has been successfully scheduled and started to run without any issues, however, qhost command shows all the LOAD is restricted on only compute node and the compute node is slowly ending up in "a" state (alarm status). 
Any help to distribute the load across all the cluster nodes is really appreciated.

HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
ip-172-16-1-22          lx-amd64       36    2   18   36  0.03   58.8G  759.7M     0.0     0.0
ip-172-16-1-56          lx-amd64       36    2   18   36 **59.11**   58.8G    2.9G     0.0     0.0

Thank you,
Vin

**Comment by demartinofra** [comment]
Hi,

by default SGE in ParallelCluster is configured with the fill_up option while probably you want to change this behaviour to round_robin. Take a look at this resolved issue for additional details: https://github.com/aws/aws-parallelcluster/issues/1084.

Let us know if you need further support!

**Comment by vinkas10** [comment]
Thank you very much Demartinofra. It looks more like an NAMD application input parameter issue. I did some additional testing with other MPI jobs and SGE in parallelCluster is behaving as expected.

Thank you,
Vin
