### ISSUE TITLE
Stuck in Compute Fleet CREATION_IN_PROGRESS

### ISSUE THREAD

**Issue by luchetto81** [aws/aws-parallelcluster#1253]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 2.4.1
 - OS: MacOS Mojave
 - Scheduler: SLURM
 - Master instance type: t2.large
 - Compute instance type: t2.large

**Bug description and how to reproduce:**
Selecting t2.large as "compute_instance_type" will make the stack in status CREATION_IN_PROGRESS forever.

**Additional context:**
The t2 types are not supported by the placement_group but if you select t2 type the creation of the cluster does not fail and hangs forever in ComputeFleet CREATION_IN_PROGRESS.
The only way to see what is going on is:
- go to the AWS console in the Autoscaling Group section 
- check the Activity History.
It would be great to have a time-out and an error message after some reasonable time.

**Comment by lukeseawalker** [comment]
Hi @luchetto81,
thank you for the feedback.
The current timeout is 30 minutes.
Here you can find the list of instance types supporting placement group https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/placement-groups.html.
We have marked the issue as feature enhancement.

**Comment by jacobcvt12** [comment]
I'm also experiencing this problem (hangs on ComputeFleet CREATION_IN_PROGRESS) but this occurs regardless of instance type (I've tried A1, which is listed as supported). I end up getting the error message 

Cluster creation failed.  Failed events:
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Resource creation cancelled
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Failed to receive 1 resource signal(s) within the specified duration.

**Comment by gh-amaroo** [comment]
Same issue as above. Using 2.4.1 version.

**Comment by jacobcvt12** [comment]
Also using 2.4.1 (and MacOS Mojave).

**Comment by sean-smith** [comment]
@jacobcvt12 A1 instances are currently not supported by AWS ParallelCluster

**Comment by sean-smith** [comment]
@gh-amaroo What instance type are you using?

**Comment by jacobcvt12** [comment]
@sean-smith is there a way to see which instance types are supported by AWS ParallelCluster?

**Comment by sean-smith** [comment]
@jacobcvt12 Currently that's just A1 instances, we'll update the docs to make this clear.

**Comment by sean-smith** [comment]
@jacobcvt12 We've updated the docs to call this out: https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#master-instance-type

@luchetto81 We've update the `placement_group` docs and called out that not all instance types support placement groups. See https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#placement-group

**Comment by jacobcvt12** [comment]
Thanks @sean-smith

**Comment by acastanedam** [comment]
Good day,
At the moment, I have the same situation as it is described in https://github.com/aws/aws-parallelcluster/issues/1253#issuecomment-533294523, even with a simple configuration:
`[aws]
aws_region_name = eu-west-1

[cluster default]
key_name = $key
vpc_settings = public

[vpc public]
vpc_id = $vpc-id
master_subnet_id = $subnet-id

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}`

I have tried with several changes, but it always stucks at and/or end with the above described failures.
Thanks in advance for your help.

**Comment by enrico-usai** [comment]
Hi @acastanedam 
as a general rule it is better to open a new issue rather than answer to a closed one, because the original issue could be related to another cause, already solved.

BTW I just tested your simple configuration, with ParallelCluster 2.4.1, in the same region, and the cluster has been created correctly.

If your cluster fails creation, please re-execute `create` action using `--norollback` option, create a new issue and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node.

**Comment by enrico-usai** [comment]
Hi @acastanedam ,

[Here](https://docs.aws.amazon.com/parallelcluster/) you can find the official ParallelCluster documentation.

There is a section specific for [network configuration](https://docs.aws.amazon.com/parallelcluster/latest/ug/networking.html).
You can also find some useful information in the [getting started](https://docs.aws.amazon.com/parallelcluster/latest/ug/getting-started-configuring-parallelcluster.html) page.
