### ISSUE TITLE
Possible routes towards hybrid HPC workflow with on-premises machines

### ISSUE THREAD

**Issue by refraction-ray** [aws/aws-parallelcluster#1254]
Hi, there. I am pretty new to AWS and maybe my question is too broad and general.

I was wondering whether parallelcluster could setup on-premises/cloud hybrid HPC infrastructures. Based on what I have read from the doc, the configurations are all about pure cloud HPC solutions. And my ideal setup would be, say, a master head node (and several compute machines) on premises and more elastic scaling compute nodes on the cloud which can be provisioned by submitting tasks on slurm. Besides, it would be a great plus if we can also incorporate these fascinating types of cloud storages (like FSx for Lustre) into such HPC.

Any suggestion on roadmaps to this setup? Or is there any future plans on supporting this by parallelcluster? Is [this example](https://github.com/aws-samples/aws-plugin-for-slurm) a good way to go if I want to try something hybrid?

**Comment by lukeseawalker** [comment]
Hi @refraction-ray,
first of all thank you for you interest.

As you have noticed, AWS ParallelCluster is a AWS native tool that uses AWS resources to build an High Performance Computing environment in the cloud.
For an hybrid approach, there may be different solutions depending on the requirements. The one you linked as example could be one, see [this](https://aws.amazon.com/it/blogs/compute/deploying-a-burstable-and-event-driven-hpc-cluster-on-aws-using-slurm-part-1/) blog post as a starting point. 

If possible, can you share the size of your on prem cluster and the desired for the cloud one? What is your use case in terms of application that you would like to execute?

L

**Comment by refraction-ray** [comment]
Hi @lukeseawalker ,
Thanks for your reply.

Currently, we have maintained two mini clusters in our department: one in the size around 30, the other one in the size around 10 nodes (with newer hardwares). One of our computation needs is to do memory consuming computations (such as full diagonalization of large matrix) whose memory requirements might fall into the range of 300G to 2T. These types of numerical tasks don't need too much internodes communications and are insensitive to any start up overheads (diagonalization of one matrix takes several hours, so other overheads in seconds are irrelevant). Therefore, I believe cloud high performance solutions fit well here: 1. powerful hardware spec (extra large memory); 2. very little communication (avoid bottleneck of communication through the Internet for hybrid scheme); 3. insensitive of overheads (the bulk of the task: a single MKL routine dominates the time).

One can argue that there is no need for hybrid solution here as the user can create a pure cloud HPC and submitting the tasks. And this is true in some sense. But I guess there are at least several benefits by utilizing hybrid architecture with master nodes on premises. 
1. The software stacks have already been installed, configured and fine tuned on the master node, so less work is required for the cloud part. 
2. The learning curve is the most smooth for normal users in this scenario, they don't need to know details of cloud computations. They could just submit their jobs by slurm on the on prem cluster as before (at most a switch of slurm partition). And this brings users the most consistent user experience (they don't need to run tasks on two different clusters and check back and forth, instead, all output data files are saved in the same place, either local storage or cloud storage).
3. Honestly speaking, I am very interested in this solution myself, since I would like to try something challenging and interesting. As I couldn't find much on-line resources of real experience on this topic, I think the architecture itself is very interesting to explore.

Of course, all the above are just my personal thoughts right now. We need some time to try and see what happens.

**Comment by nstornetta** [comment]
Thanks, @refraction-ray for giving us some insight into your use cases and workload. While your use case is a very interesting one, AWS ParallelCluster remains for the time being, an AWS-native product without any official support for hybrid architectures.

If you are committed to pursuing a hybrid approach then I would recommend reviewing the blog post that Luca shared in addition to the Slurm plugin you linked to and seeing whether either might fit your use case.

Marking this issue as closed for now.

**Comment by r-ushil** [comment]
Wondering if there's been any development for OP's question since it was asked? Curious about a similar setup
