### ISSUE TITLE
Post install script preventing deployment completion

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#1266]
**Environment:**
 - aws-parallelcluster-2.4.1
 - OS: CentOS 7
 - Scheduler: SGE
 - Master instance type: t2.micro
 - Compute instance type: c5.large

**Bug description and how to reproduce:**
I've been trying to run the example post_install script outlined at https://aws-parallelcluster.readthedocs.io/en/latest/pre_post_install.html and stored at my S3 bucket. The deployment goes on and on and on. However, and even though the master and compute instances are up and running, the installation never ends and keeps stating the usual "Status: ComputeFleet - CREATE_IN_PROGRESS." I have tried 6 or 7 times at different hours and waited for up to 15 minutes without success. It's likely a minor thing but I'm unsure what else to troubleshoot. Thanks.

**Additional context:**
The pcluster file reads:
```
[aws]
aws_region_name = us-east-1
aws_access_key_id = ___
aws_secret_access_key = ___

[cluster odycluster]
vpc_settings = ___
placement_group = DYNAMIC
placement = compute
key_name = ___
master_instance_type = t2.micro
compute_instance_type = c5.large
cluster_type = spot
extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
scheduler = sge
base_os = centos7
post_install=s3://___/test_apc01.sh
post_install_arg = NONE

[vpc ___]
master_subnet_id = ___
vpc_id = ___

[global]
update_check = true
sanity_check = true
cluster_template = ___

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}


```
The script (test_apc01) reads:
```
#!/bin/bash

. "/etc/parallelcluster/cfnconfig"

case "${cfn_node_type}" in
    MasterServer)
        echo "I am the master" >> /tmp/master.txt
    ;;
    ComputeFleet)
        echo "I am a compute node" >> /tmp/compute.txt
    ;;
    *)
        ;;
esac

```

**Comment by demartinofra** [comment]
Hi,

thank you for reporting this.
A few things you might do that can help identifying the root cause:
1. Create the same cluster without any post_install. Is it succeeding in that case? If so is the bucket you are trying to pull the script from public? If not probably the instances don't have the right permissions to retrieve the post_install script. One way to fix that is to add [s3_read_resource](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#s3-read-resource) config for that bucket or to make the script in the bucket public.
2. By looking at the CloudFormation stack events is ComputeFleet the only resource that is pending creation or also MasterServer?
3. Can you run `pcluster create` with `--norollback` flag, ssh into master and eventually compute and retrieve the following log files: `/var/log/cfn-init-cmd.log`, `/var/log/cfn-init.log`

Francesco

**Comment by afernandezody** [comment]
Hello Francesco.
It has taken me a little while but I think to have figured out what's going on. I'm dividing my info into two sets (original and modified). 
**Original**. My original set-up for the S3-bucket allows access to the owner (a screenshot is attached). My assumption was that this configuration requires to provide the post_install flag as "s3://***.sh" instead of as a secure website address. I'm also attaching a screenshot of the stack information while the deployment is going on. Using the -norollback flag (which I have used for troubleshooting previous issues) doesn't do much because the process never completes. The log for the master node is attached (could not log in on the compute nodes). It's stating that it couldn't read the post-install script but I don't understand why it didn't roll back the installation.
**Modified**. If I change the S3-bucket permission to public (screenshot attached), the deployment still doesn't work when I set the post_install flag to "s3://odyhpc.bucket1/test_apc01.sh' but it completes when I use https://s3-us-west-2.amazonaws.com/odyhpc.bucket1/test_apc01.sh.
 
My theory is that the incompatibility arises because my script is created/assigned to the (default) Oregon region but the cluster is deployed at the N. Virginia region. I can live with this as long as I'm performing some preliminary tests. However, this is something that you might want to look into as some people (including myself) would like their scripts to be compatible across regions and don't want them to be public. Thanks.  

![S3_original_permissions](https://user-images.githubusercontent.com/44442767/62955996-12e6d900-bdc0-11e9-9278-8654bffafca7.png)
![stack_original](https://user-images.githubusercontent.com/44442767/62956018-1d08d780-bdc0-11e9-9ff2-745f93cb1891.png)
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/3497773/cfn-init-cmd.log)

![S3_modified_permissions](https://user-images.githubusercontent.com/44442767/62956047-2b56f380-bdc0-11e9-879f-ed198d475de5.png)

**Comment by afernandezody** [comment]
I'm closing the ticket as the root cause and workaround were identified.

**Comment by enrico-usai** [comment]
Thank you @afernandezody for sharing the workaround and closing the ticket.
