### ISSUE TITLE
ec2_iam_policy instead of ec2_iam_role 

### ISSUE THREAD

**Issue by stephenmsachs** [aws/aws-parallelcluster#1269]
**Environment:**
 - aws-parallelcluster-2.4.1
 - OS: any
 - Scheduler: any
 - Master instance type: any
 - Compute instance type: any

I would like to propose to add custom IAM Policies to ParallelCluster configuration instead of (or additional to) IAM Roles. IAM Policies have the advantage of being independent of changes in the internal ParallelClusterPolicies as they can be added as additional policies to the RootRole.

**Comment by enrico-usai** [comment]
Thank you for asking, I'll set as Feature Enhancement.

**Comment by lukeseawalker** [comment]
coming in the next release
