### ISSUE TITLE
Compute node replacement on stack creation results in CREATE_FAILED

### ISSUE THREAD

**Issue by cccassidy** [aws/aws-parallelcluster#1270]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: [aws-parallelcluster-2.4.1]
 - OS: [alinux]
 - Scheduler: [slurm]
 - Master instance type: [m18.xlarge]
 - Compute instance type: [c5.18xlarge]

**Bug description and how to reproduce:**
When a node fails to initialize during the CloudFormation stack creation it signals the node failure to both the autoscaling group and CloudFormation.  As a result the CloudFormation stack gets into a CREATE_FAILED state.  I have seen some nodes failed due to instance health checks when initializing and that only signals back to the autoscaling group and the CloudFormation stack is able to complete successfully.  It would ideal if the node failure only signals autoscaling so the stack creation can run to completion.

**Additional context:**
I have gotten around this in the interim by setting no-rollback.

**Comment by sean-smith** [comment]
Hi @cccassidy 

You can achieve this behaviour by setting:

```ini
[cluster default]
...
initial_queue_size = 0
```

In the cluster section of the config file. Then after cluster creation, you can submit jobs to cause nodes to scale up, or manually scale up nodes by adjusting the desired value of the autoscaling group, to do so go to the ASG Console > `parallelcluster-[cluster_name]` > Edit.

**Comment by cccassidy** [comment]
Hi @sean-smith

Thanks for the advice, however we spin up the cluster and need the full # of nodes right off the bat.  We also have automated the entire process so manually adjusting through the console after launch would be less than ideal.  Is there a use case for signaling both CloudFormation and the ASG about the node failure that I am not seeing?

Thanks!

**Comment by sean-smith** [comment]
The only time it signals the CloudFormation stack is during cluster creation. 

This shouldn't ever happen, once you've ironed out the details, are you using a post_install script? What's causing these health checks to fail?

**Comment by cccassidy** [comment]
We see sporadic node failures when the Lustre mount fails, typically due to port 988 already in use.  Prior to v2.4.0 the node would just drop out of the ASG.  With 2.4.0 it is able to to replace the node but still fails on the CFN side.  When autoscaling detects a bad node from system-level instance health checks the CFN stack is still able to complete successfully.  However when its a user check (the post install) the CFN stack fails.

I believe this may be the cfn-signal that causes the stack to fail:
https://github.com/aws/aws-parallelcluster/blob/5d3cdd6ef2937746cf33b83056f01766a233c2f5/cloudformation/aws-parallelcluster.cfn.json#L3038

**Comment by enrico-usai** [comment]
Hi @cccassidy 
as you saw the cfn-signal is used to notify the ASG that the user-data part of the compute node initialization ends up correctly.
The user-data is the same in all the compute instances so if one of them fails almost certainly all the others will fail, except for situations like this on which there are random failures.

You found the root cause: the "988 already in use" error.
It happens when Lustre module is unable to grab the 988 port, because already taken from another process. I'm marking this as a bug.

**Comment by cccassidy** [comment]
Hi @enrico-usai,
Thanks for the update, I understand now why you signal CloudFormation as well as the ASG, otherwise it would get stuck in a never-ending provison loop until the stack timeout.  We had only ever experienced the random failure case with Lustre, thanks for marking it as a bug.  Let me know if I can provide any logs that would help track down the cause of the Lustre port issue.

**Comment by demartinofra** [comment]
This patch that is in review might fix the issue with FSx Lustre: https://github.com/aws/aws-parallelcluster-cookbook/pull/380
