### ISSUE TITLE
Fail to create FSx  Lustre on-the-fly with the cluster 

### ISSUE THREAD

**Issue by pos2001** [aws/aws-parallelcluster#1280]
**Environment:**

AWS ParallelCluster 2.4.1
OS: alinux
Scheduler: SGE
Master instance type: c4.4xlarge
Compute instance type: c5n.18xlarge

**Bug description and how to reproduce:**

I was able to use an existing FSx for Lustre, but got an error when trying to create FSx on the fly. Here's the error message:

C:\Users\smcho>pcluster create mycluster
Beginning cluster creation for cluster: mycluster
Creating stack named: parallelcluster-mycluster
Status: parallelcluster-mycluster - ROLLBACK_IN_PROGRESS
Cluster creation failed.  Failed events:
  - AWS::IAM::Policy ParallelClusterPolicies Resource creation cancelled
  - AWS::EC2::EIPAssociation AssociateEIP Resource creation cancelled
  - AWS::IAM::InstanceProfile RootInstanceProfile Resource creation cancelled
  - AWS::CloudFormation::Stack FSXSubstack Embedded stack arn:aws:cloudformation:ap-northeast-1:013288819788:stack/parallelcluster-mycluster-FSXSubstack-JW8PAJ6PO2LU/f1d37440-c624-11e9-9f6d-0a1d3b063294 was not successfully created: The following resource(s) failed to create: [FileSystem].

Also, here is my config. file

[global]
cluster_template = default
update_check = true

[aws]
aws_region_name = ap-northeast-1

[cluster default]
key_name = tokyo

initial_queue_size = 0
max_queue_size = 1
min_queue_size = 0
placement_group = DYNAMIC
cluster_type = spot
master_instance_type = c4.4xlarge
compute_instance_type = c5n.18xlarge
vpc_settings = myvpc
fsx_settings = myfsx

enable_efa =             compute
base_os =                alinux

[vpc myvpc]
vpc_id = vpc-906256f7
master_subnet_id = subnet-3b14e273

[fsx myfsx]
shared_dir = /fsx
storage_capacity = 115520

I think it is sizing problem of FSx Lustre.

If the  storage capacity is lower than 39600, it is okay.
But whenever  the size is larger than 39600, it always generates the error messages.
I tried to change the region (oregon), but it is same.

**Comment by enrico-usai** [comment]
Hi @pos2001 
Have you found the problem?
