### ISSUE TITLE
Master does not see z1d.metal compute instances

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#1283]
- AWS aws-parallelcluster-2.4.1
 - OS: CentOS7
 - Scheduler: SGE
 - Master instance type: t2.micro
 - Compute instance type: z1d.metal

I just wanted to let you know about some issues while trying to deploy a bare metal cluster (3 x z1d.metal) in the Ireland region. The master and compute instances deploy but do not connect (`qhost` returns empty). After deploying dozens of clusters, this was kind of unexpected. A similar deployment in us-west-1 worked without any issue about 10 weeks ago (probably with v2.2.1). Also, I was able to complete my deployment using z1d.12xlarge instead of metal so it's not an issue for me. It might be a glitch or some incompatibility between the new parallecluster version and baremetal, didn't dig deeper.

**Comment by enrico-usai** [comment]
Hi @afernandezody 
thank you for opening this issue.

We need to fix our code to support also this instance type.

**Comment by enrico-usai** [comment]
The bug has been fixed, I just created a cluster with z1d.metal instances on ireland.
