### ISSUE TITLE
Securely pass credentials to ParallelCluster

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1286]
**Environment:**
 - aws-parallelcluster-2.4.1
 - OS: centos7
 - Scheduler: slurm
 - Master instance type: t2.micro
 - Compute instance type: t2.micro

This is not a bug report, but rather a question on best practices for ParallelCluster.

I want to join the instances to a AWS Managed AD domain. I know how to do this. However, I am not sure how to do it without exposing the credentials of the account used to join the domain.

My current (insecure) solution is to store the credentials in Secrets Manager and grant access to the instances via the EC2 role. However, that means that any logged-in user can query those credentials.

Do you have suggestions on how to securely pass credentials to ParallelCluster? Or how to use the permission context of the user that runs the `pcluster` script on the EC2 instances without making use of the EC2 instance profile credentials?

Let me know if this is not the proper channel for this question.

**Comment by demartinofra** [comment]
Hi @joeydumont 

sorry for the late reply. I don't have a valid answer to your problem right away. Let me perform some additional digging and hopefully get back to you with a solution.

**Comment by joeydumont** [comment]
My current idea is to
  * provision a lifecycle hook on the ASG for when the instance boots up
  * trigger a Lambda function from the SNS notification
  * Lambda function triggers Systems Manager RunCommand. 

The credentials would be accessible only to the Systems Manager role.

I haven't tested this though, so there are probably issues I haven't encountered/thought of yet. This also does not solve the problem for the master node, although I suspect that something could be done directly in CloudFormation for the MasterServer. 

Thanks for the reply!

**Comment by demartinofra** [comment]
Your proposal looks reasonable. My only concern regards the fact that System Manger RunCommand uses the EC2 Instance Profile attached to the EC2 instance to authorize its AWS calls. If that's the only way to assign policies to the command ran through System Manager than you are not solving your problem since every user that can ssh into the host can use the instance profile.

**Comment by joeydumont** [comment]
I was thinking that Lambda would query Secrets Manager and pass that as parameters to RunCommand, but I haven't used Systems Manager before, so I'm not sure if that works. If it doesn't, I'll go back to the drawing board.

**Comment by demartinofra** [comment]
Hi @joeydumont 

were you able to come up with any working solution to address this? If so would you mind sharing it with us?

Thanks,
Francesco

**Comment by joeydumont** [comment]
I haven't ironed out all the details yet, and I have only tested domain unjoining, but here's my procedure:
  * provision a lifecycle hook on the ComputeFleet ASG:
  * lifecyclehook triggers Lambda function via SQS;
  * Lambda function is given access to password via Secrets Manager;
  * Lambda function uses the `AWS-RunShellScript` document to run the domain unjoin command.

This works just fine for the domain unjoining, but I still have a couple issues to iron out:
  * Using the `AWS-RunShellScript` document leaks the credentials in the SSM log (it shows the command that was run). This is only a minor issue though, as this client does not have access to the console at all, but still annoyance. 
    * **Proposed solution**: Use a specific document that accesses the secrets via Parameter Store variables with NoEcho. It's untested, but it should prevent the logs to echo the secrets.
  * Instances that are provisioned as part of the initial_size of the ASG might not trigger the lifecycle hook, as it is provisioned as part of the additional_cfn_template.
    * I don't know if that's an issue yet. I think that the ComputeFleet will be fully provisioned before the nested stack starts creating the lifecycle hook for launching instances. The solution is to specify that lifecycle hooks specification directly in the ComputeFleet resource.
  * This doesn't cover the MasterServer.
    * **Proposed solution**: since there are no lifecycle hooks for a standalone instance, I will add a command to be run in the `AWS::CloudFormation::Init` section to join to the domain and pass the secrets via `NoEcho` stack parameters. This is untested, but to my understanding only the person running the stack needs access to the parameters, and NoEcho should insure that there is no way to see them from the instance.

Let me know if I misunderstood or forgot about anything, that'd be much appreciated.

**Comment by joeydumont** [comment]
So I worked on that last week. Here are a couple refinements:
  * Instead of using a custom document, I used references to Parameter Store and Secrets Manager to get the secrets instead of explicitly calling GetParameter. Something like     
  ```python
  response = ssm_client.send_command(
      InstanceIds=["{}".format(data['EC2InstanceId'])],
      DocumentName='AWS-RunShellScript',
      Parameters={
        'commands': ["realm leave --remove -U {{{{ssm:/path/to/JoinDomainServiceAccountUsername}}}} -v mydomain.ca <<< '{{{{ssm:/path/toJoinDomainServiceAccountPassword}}}}'"]
      })
  ```
where `data` is the content of the SQS message triggered by the lifecycle hook. These references are not resolved in the command history log. 

* To solve the two other issues, I have added a section in the `configSets` portion of the CFN template for both the ComputeFleet (in place of Lifecycle Hook) and the MasterServer. Something like:

```json
{
	"joinDomain": {
		"packages": {
			"yum": {
				"sssd": [],
				"realmd": [],
				"oddjob": [],
				"oddjob-mkhomedir": [],
				"adcli": [],
				"samba-common": [],
				"samba-common-tools": [],
				"krb5-workstation": [],
				"openldap-clients": [],
				"policycoreutils-python": [],
				"jq": []
			}
		},
		"commands": {
			"001_joindomain": {
				"command": {
					"Fn::Join": [
						"",
						[{
							"Fn::Sub": "sudo realm join -v -U '{{resolve:ssm:/path/to/JoinDomainServiceAccountUsername:1}}' mydomain.ca <<< '{{resolve:ssm:/path/to/JoinDomainServiceAccountPassword:1}}'"
						}]
					]
				}
			}
		}
	}
}
```

The parameters in `/path/to` are only available to specific IAM roles within the AWS account, and to the lambda function. Being stored in `/var/lib/cfn-init`, it is owned by root and not accessible to every logged-in user as is instance UserData.

Note that I've used two SSM string parameter, not SSM secure strings or Secrets Manager secrets. That is because the `Metadata` section of CFN templates do not support dynamic references to Secrets Manager or to SSM secure strings. While I would prefer to use Secrets Manager, I can live with having parameters that are accessible only to specific roles.

Also note that this solution assumes that only the administrators of the cluster have root access, something that, in my experience, is not always the case in AWS deployments.

**Comment by rexcsn** [comment]
@joeydumont Thanks for the detailed writeup.

**Comment by joeydumont** [comment]
No problem, @rexcsn. I'm still testing some aspects of the solution, so this probably shouldn't be taken as is.

**Comment by demartinofra** [comment]
I'm going to resolve this one since there are no open questions pending our input. Feel free to reopen it if you still need support from us. Also thanks again for sharing your solution with the community.
