### ISSUE TITLE
Why do template_url and additional_cfn_template have to be public objects?

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1299]
**Environment:**
 - aws-parallelcluster-2.4.1
 - OS: centos7
 - Scheduler: slurm
 - Master instance type: t2.micro
 - Compute instance type: t2.micro

It is only because pcluster uses `TemplateURL` instead of `TemplateBody` in the `create_stack` call [here](https://github.com/aws/aws-parallelcluster/blob/d2c9eb311a3b9156dedc4ba23d5e96015db8c8c4/cli/pcluster/pcluster.py#L121) and [here](https://github.com/aws/aws-parallelcluster/blob/a0eb85336483565805df73981f1f3d1d9ab61221/cloudformation/aws-parallelcluster.cfn.json#L3636)?

If so, I have a feature request. I would like to be able to specify these two fields as S3 URLs, with the bucket being accessible by the user running the pcluster CLI. From what I've seen, it should be fairly easy for `template_url`, as that stack is created directly with a `create_stack` call.

For `additonal_cfn_template`, I haven't seen any documentation about using a `TemplateBody` inside a `AWS::CloudFormation::Stack` clause, or how to create a nested stack from the CloudFormation CLI. It would be possible to create a completely separate stack, but that doesn't seem ideal to me.

If you have other ideas, I'd be glad to hear them. I'm also open to opening a PR myself for this work, if there is an agreed-upon solution for this.

**Comment by sean-smith** [comment]
Hi @joeydumont 

Yep, you nailed it. You could technically use pre-signed urls that are not public but that's a huge pain. 

`template_url` is a simple feature, so I'd go ahead and create a PR for that. Looking at the docs I don't see a simple way to do `additonal_cfn_template`. Can you try with a s3 uri? I really doubt that'll work but I'm at a loss for a better way to do it.

**Comment by joeydumont** [comment]
I tried with an S3 URI for both `template_url` and `addditional_cfn_template`, like this:
```ini
template_url = s3://<bucket_name>/pcluster_scripts/aws-parallelcluster-2.4.1.cfn.json
additional_cfn_template = s3://<bucket_name>/pcluster_scripts/additional_cfn_template.json
```
and both give the same error:
```bash
S3 error: Domain name specified in <bucket_name> is not a valid S3 domain
```
I will create a PR to load the `template_url` parameter and then use `TemplateBody` in the create_stack call, but, as you said, this cannot work for `additional_cfn_template`.

That solution is a bit of a hack though, and my opinion is that it stems from a limitation of the CloudFormation API itself. `TemplateURL` should be able to accept S3 URIs, not just links to public objects. Is there a way to open a feature request for the API itself?

I've tried to find where that error originates from in botocore and boto3, but I couldn't find anything of value. It'd be great to see how the `TemplateURL` parameter is processed.

**Comment by sean-smith** [comment]
@joeydumont Your best bet is to generate a pre-signed url before the cluster create. I know it's not ideal but it's the only workaround we have now:

```bash
aws s3 presign s3://<bucket-name>/object
```

If you want to script this, you can use the `-u` flag:

```bash
$ pcluster create mycluster -u $(aws s3 presign s3://<bucket-name>/object)
```

Which imho is a decent workaround.

https://docs.aws.amazon.com/cli/latest/reference/s3/presign.html

**Comment by joeydumont** [comment]
Oh, apparently I didn't post the last comment I wrote. I did have success with using pre-signed URLs. I had a script that modified the config file and then ran pcluster create. Your solution is way better.

Could I something similar for additional_cfn_template?

**Comment by sean-smith** [comment]
We don’t have it as a cli parameter but you could add it. I think the use case makes sense.

On Sep 6, 2019, at 7:53 AM, Joey Dumont <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, apparently I didn't post the last comment I wrote. I did have success with using pre-signed URLs. I had a script that modified the config file and then ran pcluster create. Your solution is way better.

Could I something similar for additional_cfn_template?

**Comment by joeydumont** [comment]
Good, I think I will add it then, and ideally document that somewhere. I must not be the only one who doesn't want to use public S3 objects.

**Comment by sean-smith** [comment]
@joeydumont Let's document on the https://github.com/aws/aws-parallelcluster/wiki
