### ISSUE TITLE
how to update tags

### ISSUE THREAD

**Issue by porcaro33** [aws/aws-parallelcluster#1303]
AWS ParallelCluster / CfnCluster version [aws-parallelcluster-2.4.1]
OS: [CentOS]
Scheduler: [SGE]
Master instance type: [m5.2xlarge]
Compute instance type: [c5.8xlarge]

## this is not bug, just a question
I tried to update EC2 instance's tags of a parallelcluster. I updated tags section of config file.
I did "pcluster stop" -> "pcluster update" ->  "pcluster start". After that I submitted a test job to the cluster and watched compute node's tags. But the tags were not changed. CloudFormation's tag parameter were also not changed. How can I change the tags? Should I use AWSCLI in custom script to change tags?

**Comment by demartinofra** [comment]
Unfortunately at the moment the `pcluster update` command does not support tags updates. One way to achieve that is to manually perform an update from the CloudFormation console, confirm the same parameters and simply add the new tags.

I'm going to mark this as an enhancement

**Comment by porcaro33** [comment]
Got it. Thank you @demartinofra

**Comment by sfurlong** [comment]
> Unfortunately at the moment the `pcluster update` command does not support tags updates. One way to achieve that is to manually perform an update from the CloudFormation console, confirm the same parameters and simply add the new tags.
> 
> I'm going to mark this as an enhancement

Was hoping this would work for me, but seems this only updates the tags in the headnode.  The compute nodes still have the same tags.  I'm trying to update the worker nodes (ephemeral) tags so that I can track compute cost for my separate clusters....and trying to avoid rebuilding the cluster.  Any ideas?  TY!
