### ISSUE TITLE
pcluster create is failing

### ISSUE THREAD

**Issue by amigomc** [aws/aws-parallelcluster#1315]
**Environment:**
 - aws-parallelcluster-2.4.1
 - OS: macOS 10.14.6
 - Master instance type: t2.micro
 - Compute instance type: c4.large

**Bug description and how to reproduce:**
`pcluster create` failed with the following error message:
```
Status: parallelcluster-mat-cluster - CREATE_FAILED                             
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-mat-cluster The following resource(s) failed to create: [MasterServerWaitCondition, ComputeFleet]. 
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Resource creation cancelled
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Failed to receive 1 resource signal(s) within the specified duration
```

**Additional context:**
Config File:
```bash
[aws]
aws_region_name = us-east-1

[cluster default]
key_name = ...
vpc_settings = test
compute_instance_type = c4.large

[vpc test]
vpc_id = ...
master_subnet_id = ...

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```

ssh to Master node is timing out.

**Comment by Palak-15** [comment]
HI @amigomc , 
Create your cluster with this command :
pcluster create _clustername_ --norollback

Then SSH into master node, send the content of /var/log/cfn-init.log

**Comment by amigomc** [comment]
Hi Palak, thank you for your reply. Yes, I have done that, but I can't ssh the master. It times out.

Other hopefully useful information:
- VPC:
```
Classic Link: Disabled
DNS resolution: Enabled
DNS hostnames: Enabled
ClassicLink DNS Support: Disabled
DHCP Options Set: Options: domain-name = ec2.internal; domain-name-servers = AmazonProvidedDNS;
```

- Subnet Route Table:
```
172.31.0.0/16 | local  
0.0.0.0/0 | igw-...
```

**Comment by Palak-15** [comment]
Try this link :
https://aws.amazon.com/blogs/opensource/best-practices-running-ansys-fluent-aws-parallelcluster/

**Comment by Palak-15** [comment]
I mean , create a custom Ami for your region then do the same process.

**Comment by jeyarajsiddhu** [comment]
Hi,

I would like to create a cluster using parallel cluster on AWS. with EFA Enabled Please find the steps which i have followed below,

Steps:

sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm

yum install epel-release

sudo yum install -y python36u python36u-libs python36u-devel python36u-pip

yum install python-pip

sudo pip3.6 install aws-parallelcluster

sudo pip install awscli

aws configure
pcluster configure

nano /root/.parallelcluster/config
aws_region_name = ap-south-1
aws_access_key_id = xxxxxxxxxxxxxxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxxxxxxxx

key_name = CalligoAWS
vpc_settings = public
initial_queue_size = 2
max_queue_size = 2
master_instance_type = c5.large
compute_instance_type = c5.18xlarge
maintain_initial_size = true
cluster_type = spot
scheduler = slurm
placement_group = DYNAMIC
base_os = centos7
enable_efa = compute


vpc_id = vpc-w23rgdb
master_subnet_id = subnet-235ggvd

shared_dir = shared
volume_type = st1
volume_size = 10

cluster_template = CAWS
update_check = true
sanity_check = true



ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

With the above configuration file i tried creating the cluster via the below command,

pcluster create mycluster

Later i see 1 cluster (Master) getting created and get terminated in no time for no reason and the compute is not even getting created ..

Request your help here, not sure what is going wrong with this.

Please suggest !!

Regards,
Jeyaraj.M

**Comment by Palak-15** [comment]
Hello @jeyarajsiddhu ,
First of all, YOur config should have be like this :
[aws]
aws_region_name =_<region name>_ (like -ap-southeast-2)

[cluster CAWS]
key_name = CalligoAWS
vpc_settings = public
initial_queue_size = 2
max_queue_size = 2
master_instance_type = c5.large
compute_instance_type = c5.18xlarge
maintain_initial_size = true
cluster_type = spot
scheduler = slurm
placement_group = DYNAMIC
base_os = centos7
enable_efa = compute

[vpc public]
vpc_id = vpc-w23rgdb
master_subnet_id = subnet-235ggvd

[whatever the group called (place it here)]
shared_dir = shared
volume_type = st1
volume_size = 10

[global]
cluster_template = CAWS
update_check = true
sanity_check = true

ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

Then You can create your cluster 
pcluster create mycluster --norollback and then send ssh to your master node , and send the content of cfn-init.log

**Comment by jeyarajsiddhu** [comment]
Thanks @Palak-15 
For the  quick response . Now i can try this config file.

**Comment by ddeidda** [comment]
@jeyarajsiddhu are you still having problems creating your cluster? Please note that EFA can only be used with the following instances: 
- c5n.18xlarge
- i3en.24xlarge
- p3dn.24xlarge

Here you can find useful information about usinf EFA with ParallelCluster:
https://aws.amazon.com/blogs/opensource/scale-hpc-workloads-elastic-fabric-adapter-and-aws-parallelcluster/

**Comment by ddeidda** [comment]
@amigomc your config file seems OK to me. Were you able to proceed further?

**Comment by jeyarajsiddhu** [comment]
@ddeidda @Palak-15 
Hi Thanks for the information shared, 
I tried/ followed the steps which were shared by you.
I was able to create the cluster and it did showed on the dashboard under the instances.
Later for sometime, for no reason the created computes were terminated.
And i am stuck royally here.

Could you please help me out or share me the reason behind the computes getting terminated.
Also, how do i  ssh from Master node to compute node, if all the computes are created successfully.

Please find attached my configuration file below, 

![aws 1](https://user-images.githubusercontent.com/22903798/65678725-79bf0980-e071-11e9-8c98-ac681485da06.PNG)
![aws 2](https://user-images.githubusercontent.com/22903798/65678726-79bf0980-e071-11e9-8dbd-ea49ab4189bb.PNG)

*********************************************************************************************
[aws]
aws_region_name = ap-south-1
aws_access_key_id = xxxxxxxxxxxxxxxxxxxxxxxx
aws_secret_access_key =xxxxxxxxxxxxxxxxxxxxxxxxxxx

[cluster default]
key_name = test123
vpc_settings = public
initial_queue_size = 2
max_queue_size = 2
master_instance_type = c5.large
compute_instance_type = c5n.18xlarge
maintain_initial_size = false
cluster_type = ondemand
scheduler = slurm
placement_group = DYNAMIC
placement = compute
base_os = centos7
enable_efa = compute
master_root_volume_size = 20
compute_root_volume_size = 20
ebs_settings = shared
scaling_settings = custom

[ebs shared]
shared_dir = /shared
volume_type = gp2
encrypted = true


[scaling custom]
scaledown_idletime = 10

[vpc public]
vpc_id =xxxxxxxxxxxx
master_subnet_id = xxxxxxxxxxxxxx

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

Regards,
Jeyaraj.M

**Comment by enrico-usai** [comment]
Hi @jeyarajsiddhu ,
I answered to your latest question in the https://github.com/aws/aws-parallelcluster/issues/1332.

**Comment by medcelerate** [comment]
I am having this same issue, launched a cluster a week and a half ago with no issues, not deploying with the same AMI I used produced this exact error.

**Comment by enrico-usai** [comment]
Hi @medcelerate ,
you see the same "MasterServerWaitCondition" error but it just means the master creation failed and it can be caused by different factors.

To debug your issue we need your configuration and the logs too, you can retrieve them from the master node by starting the cluster with the  `--norollback` option.

Could you please open a new issue and attach the details requested by the [New issue template](https://github.com/aws/aws-parallelcluster/issues/new?assignees=&labels=&template=bug_report.md) ?

**Comment by jeyarajsiddhu** [comment]
> Hi @jeyarajsiddhu ,
> I answered to your latest question in the #1332.
> 
> You did the right thing opening a new issue for this different problem.
> 
> In any case, you can connect to the master instance by executing the [pcluster ssh](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.ssh.html) command.
> 
> Thank you

Hi @enrico-usai ,

Thanks for the quick information.

**Comment by wleepang** [comment]
I am having the same issue.  I am using the `default` template in the config that is created after `pcluster configure` and am getting the following:

```
$ pcluster create -t default --norollback default
Beginning cluster creation for cluster: default
Creating stack named: parallelcluster-default
Status: parallelcluster-default - CREATE_FAILED
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-default The following resource(s) failed to create: [MasterServerWaitCondition].
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Failed to receive 1 resource signal(s) within the specified duration
```

Inspecting `cfn-init.log` on the Master instance I see the following:

```
Recipe: aws-parallelcluster::_master_base_config
  * execute[run_configure-pat] action run
    - execute /usr/local/sbin/configure-pat.sh
  * execute[add_configure-pat] action run
    - execute echo -e "\n# Enable PAT\n/usr/local/sbin/configure-pat.sh\n\n" >> /etc/rc.local
  * execute[attach_volume_0] action run

    ================================================================================
    Error executing action `run` on resource 'execute[attach_volume_0]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/python /usr/local/sbin/attachVolume.py vol-0d4361c8619ac7035 ----
    STDOUT:
    STDERR: Traceback (most recent call last):
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
        raise err
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
        sock.connect(sa)
    socket.timeout: timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/botocore/httpsession.py", line 263, in send
        chunked=self._chunked(request.headers),
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/util/retry.py", line 376, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
        raise value
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
        chunked=chunked,
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
        self._validate_conn(conn)
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
        conn.connect()
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/connection.py", line 334, in connect
        conn = self._new_conn()
      File "/root/.pyenv/versions/3.6.9/envs/cookbook_virtualenv/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
        % (self.host, self.timeout),
    urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPSConnection object at 0x7fc59961a320>, 'Connection to ec2.us-east-1.amazonaws.com timed out. (connect timeout=60)')
```

The volume in question was created, and the instance as the correct IAM permissions to attach the volume.

**Comment by wleepang** [comment]
Update - The above was for deploying to `us-east-1`.
I tried again in `us-east-2` and was successful there.
