### ISSUE TITLE
Parallel cluster compute node Terminated

### ISSUE THREAD

**Issue by jeyarajsiddhu** [aws/aws-parallelcluster#1332]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.4.1]
 - OS: [e.g. alinux]
 - Scheduler: [e.g. SGE]
 - Master instance type: [e.g. m5.xlarge]
 - Compute instance type: [e.g. c5.8xlarge]

I was able to create the cluster and it did showed on the dashboard under the instances.
Later for sometime, for no reason the created computes were terminated.
And i am stuck royally here.

Could you please help me out or share me the reason behind the computes getting terminated.
Also, how do i ssh from Master node to compute node, if all the computes are created successfully.

Please find attached my configuration file below,

aws 1
aws 2

[aws]
aws_region_name = ap-south-1
aws_access_key_id = xxxxxxxxxxxxxxxxxxxxxxxx
aws_secret_access_key =xxxxxxxxxxxxxxxxxxxxxxxxxxx

[cluster default]
key_name = test123
vpc_settings = public
initial_queue_size = 2
max_queue_size = 2
master_instance_type = c5.large
compute_instance_type = c5n.18xlarge
maintain_initial_size = false
cluster_type = ondemand
scheduler = slurm
placement_group = DYNAMIC
placement = compute
base_os = centos7
enable_efa = compute
master_root_volume_size = 20
compute_root_volume_size = 20
ebs_settings = shared
scaling_settings = custom

[ebs shared]
shared_dir = /shared
volume_type = gp2
encrypted = true

[scaling custom]
scaledown_idletime = 10

[vpc public]
vpc_id =xxxxxxxxxxxx
master_subnet_id = xxxxxxxxxxxxxx

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

Regards,
Jeyaraj.M
![aws 1](https://user-images.githubusercontent.com/22903798/65687338-d5e05880-e086-11e9-82bd-18e847d4e582.PNG)
![aws 2](https://user-images.githubusercontent.com/22903798/65687339-d5e05880-e086-11e9-936d-f48891a2c4be.PNG)

**Comment by enrico-usai** [comment]
Hi @jeyarajsiddhu 

It is the [standard behaviour](https://docs.aws.amazon.com/parallelcluster/latest/ug/autoscaling.html) of ParallelCluster: when the instances are not used they will be terminated for you. When you submit a n ew job, new instances will came up.

If you need to have a fixed size you can set the [maintain_initial_size](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#maintain-initial-size) parameter to _true_,
or you can just change the [scaledown_idletime](https://docs.aws.amazon.com/parallelcluster/latest/ug/scaling-section.html#scaledown-idletime) parameter to keep your instances as long as you want.

Let us know if it helps.

**Comment by jeyarajsiddhu** [comment]
Hi @enrico-usai ,
Thanks for the very useful information . once is done i will let you know sir.

--Jeyaraj--

**Comment by enrico-usai** [comment]
I'm going to close the issue. 
Feel free to open a new one if you encounter other problems.
Thank you
