### ISSUE TITLE
feature request: add 'EnforcePartLimits=ALL' to slurm.conf

### ISSUE THREAD

**Issue by nolta** [aws/aws-parallelcluster#1338]
Currently, if a slurm job requests too many nodes (i.e., more than `max_queue_size`), it's accepted but sits in the queue and never runs.

Adding `EnforcePartLimits=ALL` to `/opt/slurm/etc/slurm.conf` causes the job to be rejected at submission. For example, if `max_queue_size=2`:
```
$ sbatch -N 3 job.sh 
sbatch: error: Batch job submission failed: Node count specification invalid
```

**Comment by demartinofra** [comment]
Hi @nolta 

thanks for proposing this valid enhancement. I think it's reasonable for us to add this to slurm default config. In the meanwhile feel free to modify your cluster slurm config and add that option to it.

**Comment by lukeseawalker** [comment]
coming in next release https://github.com/aws/aws-parallelcluster-cookbook/pull/410
