### ISSUE TITLE
question: What to troubleshoot when "pcluster list" does not show all clusters

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#1341]
Sorry for asking tech questions in Issues but this one has been interesting ...

We have a strange issue with parallelcluster v2.3.1 and 2.4.1 where the "pcluster list" command is not showing anywhere close to the # of grids we have running in same region / account / VPC

The docs at https://aws-parallelcluster.readthedocs.io/en/latest/commands.html are refreshingly clear about what "list" command actually does: _"_This command lists the names of any CloudFormation stacks named parallelcluster-*"_ 

That is very simple and obvious but in our environment "pcluster list" shows only 3 running grids while the AWS CloudFormation console shows 18 different CF stacks that match the name pattern "cloudformation-*" 

The difference does not seem to correlate to either IAM user invoking the list command or the version of pcluster we use. 

At the same time I noticed that **we have a heck of a of cloudformation stacks running. The AWS console shows "100+" rather than give me a real count.** 

Do you think we just have a simple of "too many cloudformation templates" and maybe the pcluster list command is not able to iterate over all of them or perhaps gets a truncated response back? 

This is not a showstopper for us at all, just a curiosity for us -- we are basically trying to figure out what is happening behind the scenes with the list call.

**Comment by sean-smith** [comment]
Hi @chrisdag 

We don't do a paginated response on that call, so it's entirely likely that the results are truncated and the clusters you have are in the next "page" of the paginated response. That call is [here](https://github.com/aws/aws-parallelcluster/blob/develop/cli/pcluster/pcluster.py#L406)

From the docs:
> If the output exceeds 1 MB in size, a string that identifies the next page of stacks. If no additional page exists, this value is null.

I've created a patch to fix this. If you want to get the patch, you could use the develop version of this repo (after I merge), until the next release. 

Sorry about this.

**Comment by chrisdag** [comment]
No need for apologies at all; parallelcluster is awesome and the responses to my oddball issues have come super fast!   

No urgency on our end but if you would like some confirmation testing on the patch I'll grab it and test it out in our environment. Thanks!

**Comment by chrisdag** [comment]
Ok rather than use the developer version I added your paginate_boto3 method to utils.py in my v2.4.1 install and made the minor pcluster.py changes as well.

Can confirm it works fine. The output from "pcluster list" now matches what I see on the AWS CloudFormation Stack page if I (a) search for "parallelcluster-" with "view nested" disabled. The numbers match and the cluster names match.

Thanks again for the fast response on this. I will close this issue.
