### ISSUE TITLE
Unable to start cluster with anything other than t2 instances.

### ISSUE THREAD

**Issue by jacobcvt12** [aws/aws-parallelcluster#1343]
**Environment:**
 - AWS ParallelCluster / CfnCluster version aws-parallelcluster-2.4.1
 - OS: alinux for cluster, macOS local
 - Scheduler: SGE
 - Master instance type: c5.2xlarge
 - Compute instance type: c5.2xlarge

**Bug description and how to reproduce:**
When I try to start the cluster with 

`pcluster create --config config.aws clustername`

I get

Beginning cluster creation for cluster: galp
ERROR: Unable to check AWS Account limits. Please double check your cluster configuration.
Your requested instance type (c5.2xlarge) is not supported in your requested Availability Zone (us-east-1e). Please retry your request by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f.

I've checked and my limit for this instance type is 20. I also get this error with t3.2xlarge. I'm able to create the cluster with a variety of t2 instance types. 

Cluster config below.

**Additional context:**

```
[aws]
aws_region_name = us-east-1

[cluster default]
key_name = cluster
vpc_settings = public
compute_instance_type = c5.2xlarge
master_instance_type = c5.2xlarge
# spawn 2 compute instances by default
initial_queue_size = 1
# maximum number of instances
max_queue_size = 2
# allow down-scaling of the initial number of instances
maintain_initial_size = false
# use custom AMI
custom_ami = ami-***
# use 200GB for root volume size of master and compute
master_root_volume_size = 200
compute_root_volume_size = 200
s3_read_resource = ***
s3_read_write_resource = ***

[vpc public]
vpc_id = ***
master_subnet_id = ***

[scaling custom]
scaledown_idletime = 2

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```

Custom AMI was created using the alinux base image for 2.4.1 in us-east-1 (ami-0fd18b144da8357b7) as a base, and then modifying and running the cleanup script and creating a new image from the (stopped) instance.

I read through some similar issues and saw suggestions about the sanity_check option. I tried turning that off and `pcluster` doesn't immediately stop, but eventually gets to a similar error:

Cluster creation failed.  Failed events:
  - AWS::EC2::Instance MasterServer Your requested instance type (c5.2xlarge) is not
supported in your requested Availability Zone (us-east-1e). Please retry your request
 by not specifying an Availability Zone or choosing us-east-1a, us-east-1b, us-east-1
c, us-east-1d, us-east-1f. (Service: AmazonEC2; Status Code: 400; Error Code: Unsuppo
rted; Request ID: 123fd69c-f8c2-4947-bd94-e80d2061b851)

**Comment by demartinofra** [comment]
From the error message it seems like the instance type you are trying to use is not available in the specific AZ (us-east-1e) associated to your subnet. Since you are not specifying a compute_subnet_id then the master_subnet_id is used for compute as well. You could try to create a new subnet in a different AZ and use that for the cluster.

**Comment by jacobcvt12** [comment]
This worked. Thanks @demartinofra ! For others with a similar problem, I created another subnet (same VPC), and used us-east-1a as the AZ.
