### ISSUE TITLE
Cluster creation stuck in CreateMaster step with spot requests

### ISSUE THREAD

**Issue by thvasilo** [aws/aws-parallelcluster#1344]
**Environment:**
 - AWS ParallelCluster / CfnCluster version  aws-parallelcluster-2.4.1
 - OS: ubuntu1604
 - Scheduler: slurm
 - Master instance type: m4.xlarge
 - Compute instance type: m4.xlarge

**Bug description and how to reproduce:**
The past couple of days (two days ago and just now) I tried to create a spot cluster but both times it got stuck in the CreateMaster step, showing no progress.

I then changed the configuration to ondemand and the cluster was created normally. The weird part is that yesterday and for days before that I was able to create spot clusters just fine. And given that the master is an on-demand instance anyway, whether the cluster is spot or ondemand should not affect the master's creation, correct?

When this happened I tried creating both ondemand and spot instances by hand in my console to see if there was an issue with zone availability, but they both completed just fine.

**Additional context:**
Any other context about the problem. E.g.:
 - configuration file 

```
[aws]
aws_region_name = us-east-1

[ebs default]
volume_size = 40

[cluster default]
key_name = <redacted>
initial_queue_size = 3
max_queue_size = 3
maintain_initial_size = 3
master_instance_type = m4.xlarge
compute_instance_type = m4.xlarge
cluster_type = spot
vpc_settings = public
ebs_settings = default
base_os = ubuntu1604
scheduler = slurm
placement_group = DYNAMIC
s3_read_write_resource = <>

[vpc public]
vpc_id = vpc-56fd132f
master_subnet_id = subnet-10683d2c

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```
 - pre/post-install scripts, if any
 - screenshots, if useful

 - if the cluster fails creation, please re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node

The --norollback option had no effect, the master is never created, hence no logs.

**Comment by demartinofra** [comment]
Hi,

Could you share the stack events with us in order to better understand where the failure is occurring and what resources are still pending creation? Also are you waiting for the stack timeout or just deleting the stack when it hangs? Did you check in the EC2 console to see if any node is coming up?

Here is a command you could use to retrieve stack events:
```
aws cloudformation describe-stack-events --stack-name parallelcluster-stackname
```

**Comment by thvasilo** [comment]
Hello @demartinofra , sure you can find the stack events [here](https://gist.github.com/thvasilo/f36b4ce90818d550a1b44fa582072562).

Not sure how long the stack timeout is, I'm pretty sure I've waited more than 15-30 minutes for the MasterServer step to complete.

No EC2 nodes are coming up, as I said I can manually create instances so not sure why none are coming up.

Today I tried launching both on-demand and spot clusters and both were stuck in the `Status: MasterServer - CREATE_IN_PROGRESS` step.

**Comment by ddeidda** [comment]
Hi, 

looks like the availability zone where your subnet resides is not supporting m5 instances.
You could try choosing a different subnet for compute instances if you want to keep the master in the current subnet, or choosing another subnet for both master and compute instances by specifying only mster_subnet_id. See here: https://docs.aws.amazon.com/parallelcluster/latest/ug/vpc-section.html#compute-subnet-id

**Comment by thvasilo** [comment]
Thank you @ddeidda . Is there a way to tell if a specific subnet support the instances I'm trying to launch?

When I run `pcluster configure` I get a list of subnets to choose from and I can't tell the differences between them.

**Comment by ddeidda** [comment]
You can run this command to check if you can launch an instance type on your subnet:
aws ec2 run-instances --instance-type <INSTANCE_TYPE> --dry-run --image-id <AMI_ID> --subnet-id <SUBNET_ID>

More details here: 
https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-INSTANCE_TYPE_NOT_SUPPORTED-error.html

**Comment by thvasilo** [comment]
Thanks.

BTW I tried using the AMI from the [2.4.1 branch](https://github.com/aws/aws-parallelcluster/blob/v2.4.1/amis.txt) (linked to from the [docs](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html)) list like this:

`aws ec2 run-instances --instance-type m5.xlarge --dry-run --image-id ami-0eacbde87adcd79a4 --subnet-id subnet-15d56619`

but got:

`An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0eacbde87adcd79a4]' does not exist
`

using the AMI from the [master branch](https://github.com/aws/aws-parallelcluster/blob/master/amis.txt) `ami-0c535eb8c5a80b962` seems to have worked fine:

```
>aws ec2 run-instances --instance-type m5.xlarge --dry-run --image-id ami-0c535eb8c5a80b962 --subnet-id subnet-15d56619

An error occurred (DryRunOperation) when calling the RunInstances operation: Request would have succeeded, but DryRun flag is set.
```

**Comment by thvasilo** [comment]
I'm closing this for now because it's hard to replicate, if I run into the same issues with the `CreateMaster` step I'll re-open.
