### ISSUE TITLE
 Task launch fails Can't find an address, check slurm.conf

### ISSUE THREAD

**Issue by bioinformaticscro-aws** [aws/aws-parallelcluster#1347]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.4.1
 - OS: default
 - Scheduler: SLURM
 - Master instance type: t3a.medium
 - Compute instance type: t3a.medium

**Bug description and how to reproduce:**

When the cluster first boots up it's fine, but over time we always receive an error like this:

```
srun: Required node not available (down, drained or reserved)
srun: job 44 queued and waiting for resources
srun: job 44 has been allocated resources
srun: error: fwd_tree_thread: can't find address for host ip-172-31-7-136, check slurm.conf
srun: error: Task launch for 44.0 failed on node ip-172-31-7-136: Can't find an address, check slurm.conf
srun: error: Application launch failed: Can't find an address, check slurm.conf
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: Timed out waiting for job step to complete
```

The only thing that resolves the error is to run `pcluster stop` followed by `pcluster start`.

I have a post install script that creates users, but besides that there's nothing special happening here.

**Additional context:**
Any other context about the problem. E.g.:
 - configuration file without any credentials or personal data.
 - pre/post-install scripts, if any
 - screenshots, if useful
 - if the cluster fails creation, please re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node
 - if a compute node was terminated due to failure, there will be a directory `/home/logs/compute`. Attach one of the `instance-id.tar.gz` from that directory
 - if you encounter scaling problems please attach `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node

**Config**

```
[cluster default]
vpc_settings = public
scheduler = slurm

master_instance_type = t3a.medium
compute_instance_type = t3a.medium
```

**Comment by demartinofra** [comment]
Hi,

thanks for reporting this. AWS ParallelCluster scaling logic is not fully compatible with interactive commands. I would recommend you to use `sbatch` instead of `srun` when a scaling operation is required while for quick testing you can issue `srun` commands onces the nodes are available.

See if this wiki page addresses your problem: https://github.com/aws/aws-parallelcluster/wiki/Interactive-Jobs-with-qlogin,-qrsh-(sge)-or-srun-(slurm)
