### ISSUE TITLE
centos7 and torque not working with 1.3.1

### ISSUE THREAD

**Issue by holmeso** [aws/aws-parallelcluster#135]
Hi,
I'm getting issues with the torque scheduler on centos7 using cfncluster 1.3.1.
The master and compute nodes are brought up ok, but the compute node is listed as "down" when I run pbsnodes:

```
[centos@ip-172-31-23-232 ~]$ pbsnodes
ip-172-31-23-232
     state = down
     power_state = Running
     np = 1000
     ntype = cluster
     note = MasterServer
     mom_service_port = 15002
     mom_manager_port = 15003

ip-172-31-20-16
     state = down
     power_state = Running
     np = 1
     ntype = cluster
     mom_service_port = 15002
     mom_manager_port = 15003

[centos@ip-172-31-23-232 ~]$ qstat
Job ID                    Name             User            Time Use S Queue
------------------------- ---------------- --------------- -------- - -----
0.ip-172-31-23-232.ap-southea STDIN            centos                 0 Q batch
[centos@ip-172-31-23-232 ~]$
```

The following combinations all work fine:

cfncluster 1.3.1 & centos6 & torque
cfncluster 1.3.1 & centos7 & sge
cfncluster 1.2.1 & centos7 & torque

I am not defining any pre/post install scripts or roles.
Thanks,
Ollie

**Comment by snamburi3** [comment]
@holmeso, the fix mentioned [here](http://linuxtoolkit.blogspot.com/2013/11/pbs-error-unable-to-change-status-of.html) worked for me. Check the pbs_server status - I think the hostnames are messed up. You might need to edit the IP addresses(to *.ec2.internal) in the file  /var/spool/torque/server_priv/nodes.

**Comment by lukeseawalker** [comment]
@holmeso are you still having this issue with latest release?

**Comment by holmeso** [comment]
@lukeseawalker don't know - haven't tried - closing

**Comment by dangerousdaren** [comment]
I've just spun up a Centos 7 Torque cluster with CfnCluster 1.5.4 and hit this issue with the nodes listed in /var/spool/torque/server_priv/nodes are listed with the hostname minus the domain name.

The result is a cluster where master and all nodes are in a state = down.

And the Logs on the master start with errors related to the master

LOG_ERROR::svr_is_request, bad attempt to connect from 192.168.1:187 (address not trusted - check entry in server_priv/nodes)

and then are full of entries along the lines of the below for each compute node.

LOG_ERROR::get_node_from_str, Node ip-192-168-1-59 is reporting on node ip-192-168-1-59.eu-west-1.compute.internal, which pbs_server doesn't know about

Whilst the workaround listed of editing the /var/spool/torque/server_priv/nodes should be ok for a static pool of nodes, I fear ( I have not tested yet )  that the elastic nature of the cluster will add in nodes without their fqdn and thus be perpetually in a down state.

**Comment by lukeseawalker** [comment]
Thanks @dangerousdaren, we are looking into the issue.

L

**Comment by dangerousdaren** [comment]
Interestingly on Centos6 the /var/spool/torque/server_priv/nodes file also contains just the unqualified node name,  but in this instance the compute nodes are actually accepted into the pool and show up as status=free.

There is still a single entry for each compute node in /var/log/messages though 

PBS_Server: LOG_ERROR::svr_is_request, bad attempt to connect from 10.12.3.245:358 (address not trusted - check entry in server_priv/nodes)

But these only appear once.

**Comment by vbosquier** [comment]
Hi all!

As described in this topic, on CfnCluster clusters (version 1.5.4 on my system) started with Torque as sheduler on Centos7, Torque can’t detect/configure the compute nodes because the compute nodes hostname is the “short one” without the domain name… as soon as you add the domain name to the hostnames in the /var/spool/torque/server_priv/nodes configuration file, Torque detects the new nodes.

Is there any update on this issue? (I can see it was declared as a bug on September 20th)

Best regards,
Vincent.

**Comment by demartinofra** [comment]
The fix for this has been merged into develop branch and will be released with the next version of AWS ParallelCluster. Resolving..
