### ISSUE TITLE
Include MKL alongside Intel MPI

### ISSUE THREAD

**Issue by ChrisDowning** [aws/aws-parallelcluster#1351]
Please consider including MKL alongside Intel MPI within the default AMI (for CentOS, at least); at present, the low-friction options to enabling MKL usage are:
1) Install on the head node and ensure the relevant directory is exported via NFS
2) Install MKL on every node via a post-install script

At present, option 1 would involve "overwriting" the contents of /opt/intel with a new mount point (eg EBS volume or RAID array) and [manually installing](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-yum-repo) both Intel MPI and MKL on the head node. Option 2 uses the same process but just adds to the existing /opt/intel directory on each compute node - this is time-consuming and feels wasteful.

Including MKL (and the other Intel performance libraries, if there is demand) by default would greatly simplify things.

Alternatively, it might be viable to have the whole /opt directory be set to a dedicated NFS mount rather than just /opt/slurm as is the case currently, though that would imply different AMIs for the head node and compute nodes.

**Comment by sean-smith** [comment]
Hi @ChrisDowning 

Already in progress, see https://github.com/aws/aws-parallelcluster-cookbook/pull/372

This change also exports `/opt/intel` to the compute nodes.
