### ISSUE TITLE
Compute Instance update not working - Tests have a bug

### ISSUE THREAD

**Issue by datsabk** [aws/aws-parallelcluster#1353]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.4.1] - aws-parallelcluster-2.4.1
 - OS: [e.g. alinux] - ubuntu
 - Scheduler: [e.g. SGE] - slurm
 - Master instance type: [e.g. m5.xlarge] - t2.medium
 - Compute instance type: [e.g. c5.8xlarge] - t2.medium -> t2.xlarge

**Bug description and how to reproduce:**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Additional context:**
On execution of `pcluster update -c abc.config testcluster` with a different compute type, the compute instance type does not get updated. It shows that update is completed on Cloudformation stack but in reality, there is no change on compute instances. 

Additionally, on the [tests](https://github.com/aws/aws-parallelcluster/blob/develop/tests/integration-tests/tests/update/test_update.py), the test case is checked incorrectly. It should check for instance type using `updated_config.compute_instance_type`  while it checks using `init_config.compute_instance_type` which passes because the code for update instance type doesn't work.

**Comment by demartinofra** [comment]
Hi @datsabk 

Thanks for reporting this. The test seems correct: it first checks that the existing compute nodes are still of type [init_config.compute_instance_type](https://github.com/aws/aws-parallelcluster/blob/develop/tests/integration-tests/tests/update/test_update.py#L75) and then it checks that new nodes that are launched are of type [updated_config.compute_instance_type](https://github.com/aws/aws-parallelcluster/blob/develop/tests/integration-tests/tests/update/test_update.py#L81).

Existing nodes are not automatically replaced. You can use pcluster stop and pcluster start to achieve that.

Let me know if that solves your issue.

Francesco

**Comment by datsabk** [comment]
Hey @demartinofra - In that case, I would request you to let me know if update of compute_instance_type works for you. I feel the compute instance types don't really get updates anywhere in between.

**Comment by demartinofra** [comment]
Are you referring to existing compute nodes or new ones? Existing nodes are not updated and that's an expected behaviour, however new ones should be of the new instance type. Did you try to issue a pcluster stop and then a pcluster start after changing the type?

**Comment by datsabk** [comment]
@demartinofra - Let me try that and get back. Also, would love to understand as to why can't we just update the existing ones? As long as we know jobs are not running, shouldn't they be allowed to update?

**Comment by demartinofra** [comment]
Some of the reasons why we don't want to foce compute nodes termination are:
- the user might be running jobs on them
- Some data might be stored on the instances and needs to be retrieved.

In general we want the user to perform an explicit request to replace those nodes and at the moment the only way is to perform a `pcluster stop` followed by a `pcluster start`. In the future we might want to add a flag to the `pcluster update` to force replacement of compute instances but in any case the user will have to explicitly set the flag.

Were you able to replace your instances with the expected ones?
