### ISSUE TITLE
Add a tool in module at pbs nodes

### ISSUE THREAD

**Issue by rajiv03** [aws/aws-parallelcluster#1358]
I would like to install GNU parallel which i already installed in Master node and want to install it in all the nodes I take ( via batch submission)? I guess module can do that if i set GNU parallel in module? Any suggestion is appreciated. Here is a conf file I used to create cluster. Thank you

[aws]
aws_region_name = us-east-1
[cluster default]
key_name = mykey
vpc_settings = public
base_os = alinux
initial_queue_size = 0
max_queue_size = 15
scheduler = torque
master_instance_type = c5n.xlarge
compute_instance_type = c5n.18xlarge
cluster_type = spot
scaling_settings = custom
placement_group = DYNAMIC
ebs_settings = tfs
[scaling custom]
scaledown_idletime = 10
[vpc public]
vpc_id = vpc-cxxxxxx
master_subnet_id = subnet-cxxxxx
[ebs tfs]
volume_type = st1
volume_size = 800
[global]
cluster_template = default
update_check = true
sanity_check = true
[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

**Comment by lukeseawalker** [comment]
Hi,
you can install additional software via [Custom Bootstrap Actions](https://docs.aws.amazon.com/en_pv/parallelcluster/latest/ug/pre_post_install.html).

**Comment by ole-tange** [comment]
`parallel --embed` maybe?
