### ISSUE TITLE
awsbatch function is not available in cn-northwest-1 region

### ISSUE THREAD

**Issue by liuyukoala** [aws/aws-parallelcluster#1359]
**Environment:**
 -  aws-parallelcluster-2.4.1
 - OS:  alinux
 - Scheduler: AWS Batch
 - Master instance type: t3.large
 - Compute instance type: c5.xlarge

**Bug description and how to reproduce:**
AWS batch has been released in cn-northwest-1. But aws parallel seems not support this function in cn-northwest-1, as I run command "pcluster create" an error pop up as following:
"Config sanity error on resource AWSBatch_Parameters: Region cn-northwest-1 is not supported with batch scheduler"

**Additional context:**

**Comment by ddeidda** [comment]
Thanks for reporting this. I'm marking it as enhancement. AWS batch support will be extended to cn-northwest-1 as soon as possible.
