### ISSUE TITLE
 validation error detected:-Getting error with connecting to parallel cluster

### ISSUE THREAD

**Issue by nalinbhasker** [aws/aws-parallelcluster#1365]
**Environment:**
 - "AWS ParallelCluster Template. Version: aws-parallelcluster-2.4.1"

 - OS: linux
 - Scheduler: [e.g. SGE]
 - Master instance type: t2.micro 
 

**Bug description and how to reproduce:**
Followed the steps provided in the document https://d1.awsstatic.com/Projects/P4114756/deploy-elastic-hpc-cluster_project.pdf
However it failed to connect to cluster using command " pcluster ssh HelloCluster –i ~/.ssh/mysshkey.pem" from a Windows System with below error :
" 1 validation error detected: Value 'parallelcluster-FinalKey.pem' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]* "

Stack is deployed successfully and Ec2 instances were deployed and running.

**Comment by ddeidda** [comment]
Are you sure you are using the command above? The error you reported could be received if you used FinalKey.pem as cluster name by mistake (pcluster ssh FinalKey.pem -i ~/.ssh/mysshkey.pem)
