### ISSUE TITLE
1.3.1 doesn't allow sshfs (ssh works fine)

### ISSUE THREAD

**Issue by nswanson7** [aws/aws-parallelcluster#137]
Chef makes /etc/ssh/ssh_config and /etc/ssh/sshd_config, which differs from previous versions. I copied over these files with ones from the pre-chef versions, restarted sshd, and it fixed the issue.

**Comment by dougalb** [comment]
What CfnCluster version and OS are you using?

**Comment by nswanson7** [comment]
Previously we had been using 0.0.22 on ubuntu 14.04. Problem arose when we upgraded to current cfncluster. To be clear, I'm trying to sshfs the shared volume, if that helps.

**Comment by dougalb** [comment]
This should have been fixed here https://github.com/awslabs/cfncluster-cookbook/pull/17. We'll dig into why it's not working.

**Comment by nswanson7** [comment]
Ok thanks!

**Comment by lukeseawalker** [comment]
@nswanson7 are you still having this issue with latest release?
