### ISSUE TITLE
Enabling ganglia with pcluster update

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1371]
**Environment:**
 -  aws-parallelcluster-2.4.1
 - OS: centos
 - Scheduler: slurm
 - Master instance type: t2.micro
 - Compute instance type: c5.2xlarge

**Bug description and how to reproduce:**
I tried enabling ganglia after first provisioning a ParallelCluster by adding `extra_json = { "cluster" : { "ganglia_enabled" : "yes" } }` to the config file. However, it seems that the chef recipe is not run following a pcluster update, as it is definitely ont installed now.

Is it possible to enable ganglia after first creating the MasterServer?

**Comment by sean-smith** [comment]
@joeydumont You're right that Ganglia won't get enabled upon update, to work around it you can call the recipe directly from the master server after the update. 

To do so:
```bash
sudo su
cd /etc/chef
chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist aws-parallelcluster::_ganglia_install
```

Here's where we call the recipe: https://github.com/aws/aws-parallelcluster-cookbook/blob/9f68306b86d7fbf75195c63592bbf676c94ab872/recipes/base_install.rb#L176 Which is in `base_install.rb`,  and won't get run again unless the master server is replaced (say you change master server instance type).

**Comment by joeydumont** [comment]
Thanks for this! 

This leads to another question, but this might not be the best forum: just close the issue if it isn't. 

Do you have suggestions for configuration management of the MasterServer? For the ComputeFleet it's trivial, any changes to the install scripts will be reflected when a new instance is spun up. For the MasterServer, it isn't so clear.

I think that, if the Chef recipes are idempotent, and the install scripts are written to be idempotent, the cookbooks and scripts could be run every time the update_stack is built, but that's probably a naive approach.

**Comment by sean-smith** [comment]
@joeydumont So exactly what's happening here is the UserData (which kicks off Chef) is not re-run unless a parameter is changed within the UserData. As of now the only parameter that you can change in the UserData is ProxyServer. To address this we would use cfn-hup to listen to changes in the UserData. As of now if you change the `master_instance_type` the cookbooks would be re-run but not otherwise.

From a product design standpoint what you're saying makes perfect sense. Just isn't implemented like so.

**Comment by joeydumont** [comment]
That's what I thought.

I'm already customizing the basic template a fair bit: I'll play around with cfn-hup.

**Comment by joeydumont** [comment]
Hmm, I'm having issues with the procedure above.

I had to edit `dna.json` to add `"ganglia_enabled" : "yes"` in the `cfncluster` section, not the `cluster` section. There is no `cluster` section in `dna.json`. 

Then the _ganglia_install recipe worked properly. But, this did not start the gmond service. I ran `systemctl start gmond`. It complains that it does not find a gmond.conf, but starts anyway. But I still can't connect to ganglia. What am I missing?

**Comment by sean-smith** [comment]
What instance type is this?

**Comment by joeydumont** [comment]
Master is t2.micro, compute is c5.2xlarge.

**Comment by sean-smith** [comment]
centos 7?

**Comment by joeydumont** [comment]
Yes.

**Comment by sean-smith** [comment]
@joeydumont Is it timing out? Security group could be the issue. Did you open up port 80?

**Comment by joeydumont** [comment]
I am trying to access from the machine itself. I have also tried accessing via my workstation's browser with a port forward, but in both cases the connection is refused:

```bash
[admin.joey.dumont@ip-10-16-30-207 ~]$ wget http://127.0.0.1/ganglia
--2019-10-24 11:50:48--  http://127.0.0.1/ganglia
Connecting to 127.0.0.1:80... failed: Connection refused.
```

Do I have to manually start apache? I thought that the `gmond` service took care of that, so I haven't tried that.

**Comment by joeydumont** [comment]
I could get gmond to start on the compute nodes, but they do not get registered in ganglia.

I can't see any configuration file, so I'm assuming that the ComputeFleet can't communicate properly with the MasterServer. I think I'll try to set up something like what's described [here](https://www.tecmint.com/install-configure-ganglia-monitoring-centos-linux/).

**Comment by joeydumont** [comment]
I had to also re-run the `_master_base_config` recipe to finally configure ganglia. Now it works.

**Comment by sean-smith** [comment]
@joeydumont Thanks for all the updates, glad you got it working. For future reference what were the steps you had to take?

**Comment by joeydumont** [comment]
Ok, here's the procedure when the cluster is up and you want to enable Ganglia: 
  * add this the `extra_json` parameter in the configuration file:
```
extra_json = { "cfncluster" : { "ganglia_enabled" : "yes" } }
```
  * run `pcluster update <name_of_cluster>`. This insures that `dna.json` is updated in the launch configuration of the ASG.
  * to configure the MasterServer:
    * update `/etc/chef/dna.json` with
 ```
"cfncluster": { "ganglia_enabled" : "yes" }
```
  * Install ganglia on the master node:
```
chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist aws-parallelcluster::_ganglia_install
```

  * Configure ganglia on the master node. Configuration is done in the `_master_base_config` recipe, so it has to re-run.
```
chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist aws-parallelcluster::_master_base_config
```

Note that this documentation page, which I'm aware is unmaintained, has incorrect information: https://aws-parallelcluster.readthedocs.io/en/latest/getting_started.html#moving-from-cfncluster-to-aws-parallelcluster, but it's the only reference to ganglia I could find. It would be nice if ganglia support was documented in the wiki, or elsewhere.

**Comment by enrico-usai** [comment]
@joeydumont thank you for sharing your procedure.

You can find the content of the page you shared in the new official [AWS ParallelCluster documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/moving-from-cfncluster-to-aws-parallelcluster.html).

**Comment by joeydumont** [comment]
Thanks for this, I guess I only looked at the first result in my Google search :anguished:

My point still stands though, the Chef recipe looks for `['cfncluster']['ganglia_enabled'] == yes`, not `['cluster']['ganglia_enabled']`: see [this line](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/recipes/_ganglia_install.rb#L18) of the recipe.

**Comment by enrico-usai** [comment]
We changed the parameter from "cfncluster" to "cluster" when CfnCluster has been rebranded to AWS ParallelCluster, to remove the "cfncluster" word from the configuration file.

The code still supports the old "cfncluster" syntax, to maintain retrocompatibility with old configuration file, but we adapted the code to convert the new "cluster" syntax to "cfncluster" leaving the cookbook code untouched.
See: https://github.com/aws/aws-parallelcluster/blob/v2.4.1/cli/pcluster/cfnconfig.py#L555

It means you can use "cluster" (new syntax) or "cfncluster" (old syntax) and both will be converted to "cfncluster" on the cookbook side.

**Comment by joeydumont** [comment]
Ah, I see. Then my comment is only relevant when you manually edit `/etc/chef/dna.json` to enable ganglia on the MasterServer, because then you don't go through the `pcluster` CLI.
