### ISSUE TITLE
max_queue_size greater than service quota

### ISSUE THREAD

**Issue by nolta** [aws/aws-parallelcluster#1375]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.4.1
 - OS: centos7
 - Scheduler: slurm
 - Master instance type: c5.xlarge
 - Compute instance type: c5.18xlarge

**Bug description and how to reproduce:**

I created a cluster with `initial_queue_size=0` and `max_queue_size=256`. However, due to a miscommunication with AWS support, my service quota had only been increased to 100, not 256. When i submitted a 256-node job to the queue, the cluster grew to 96 instances and then stalled, neither running the job nor freeing the instances.

I expected cluster creation to fail if `max_queue_size` is greater than the service quota.

**Comment by sean-smith** [comment]
@nolta Unfortunately we don't check aws instance limits before attempting to scale up. A good way to check these limits is to go the [EC2 Console](https://console.aws.amazon.com/ec2/v2/home) click "Limits" on the left hand side and check the instance limits for both the master and compute type.
