### ISSUE TITLE
compute node won't get added to execution host list

### ISSUE THREAD

**Issue by jprobichaud** [aws/aws-parallelcluster#1390]
**Environment:**
 - AWS ParallelCluster 2.4.0
 - OS: ubuntu1604
 - Scheduler: SGE
 - Master instance type: c5.9xlarge
 - Compute instance type: c5.4xlarge

**Bug description and how to reproduce:**
We've been running this grid configuration for ~100 days.  The cpumaster current uptime is 97 days!  This morning, without any _apparent_ modifications to the system or to the post_install script, compute nodes aren't coming available to run jobs.

I'll attach some files containing debug information.

The execd_install_$host contains:
```
Your $SGE_ROOT directory: /opt/sge

Using cell: >default<

Specified cluster name >$SGE_CLUSTER_NAME=p6444< resulted in the following conflict!
Detected old RC scripts.
/etc/init.d/sgeexecd.p6444

Remove existing component(s) of cluster > p6444 < first!
```

**Comment by jprobichaud** [comment]
[execd_install_ip-172-31-30-12_2019-10-28_17:58:16.log](https://github.com/aws/aws-parallelcluster/files/3780438/execd_install_ip-172-31-30-12_2019-10-28_17.58.16.log)
[sqswatcher.sge-debug.txt](https://github.com/aws/aws-parallelcluster/files/3780439/sqswatcher.sge-debug.txt)

[i-090097394233c255f.tar.gz](https://github.com/aws/aws-parallelcluster/files/3780440/i-090097394233c255f.tar.gz)

**Comment by jprobichaud** [comment]
[pip.freeze-compute.txt](https://github.com/aws/aws-parallelcluster/files/3780442/pip.freeze-compute.txt)

**Comment by jprobichaud** [comment]
Wow, I'm getting the same problem with a newly created SGE setup!

**Comment by enrico-usai** [comment]
Hi @jprobichaud I just tried to create a new cluster for Ubuntu1604, SGE and ParallelCluster 2.4.1 and I'm able to create the cluster and submit the jobs.

From your logs it seems you are installing some python packages within your post install script.
The script ends correctly but after that, the cfn-init fails when signaling the SUCCESS of the compute node creation, with the error:
```
+ cfn-init -s parallelcluster-RevSpeechGrid30 -v -c default -r ComputeServerLaunchTemplate --region us-west-2
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 72: ordinal not in range(128)
Logged from file util.py, line 476
Traceback (most recent call last):
```

It can be possible that some package you're installing updated their dependencies by breaking cfn-init compatibility.

Please double check your python dependencies by comparing pip environment in your running and working compute node and in a new (broken) one.
In my working environment I have:
```
aws-cfn-bootstrap==1.4
cryptography==1.2.3
enum34==1.1.2
idna==2.0
ipaddress==1.0.16
lockfile==0.12.2
pyasn1==0.1.9
pyOpenSSL==0.15.1
pyparted==3.10.7
pystache==0.5.4
python-daemon==1.6.1
scour==0.32
six==1.10.0
```

Please also double-check without the custom post-install script.
If you still have issues please attach the configuration without any personal data and the post-install script.

**Comment by jprobichaud** [comment]
Thanks.  That's really unfortunate that such upstream changes hits us like that.  Wasn't 2.4.1 supposed to work off a special venv?

Anyway, in my case, I see the following differences in a _non working_ worker node:
```
$ pip freeze
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop suppo
rt for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
aws-cfn-bootstrap==1.4
cryptography==1.2.3
enum34==1.1.2
gyp==0.1
idna==2.0
ipaddress==1.0.16
lockfile==0.12.2
pyasn1==0.1.9
pyOpenSSL==0.15.1
pyparted==3.10.7
pystache==0.5.4
Pyste==0.9.10
python-daemon==1.6.1
scour==0.32
six==1.10.0
virtualenv==15.0.1
```

So basically, everything is the same except that I have the following extra packages:
```
gyp==0.1
Pyste==0.9.10
virtualenv==15.0.1
```

Could that be it?  Is there by any change a virtualenv enabled before the post_install script runs?  My post install doesn't do much with python, except:
```
apt-get -y install  python-dev python-pip python3-pip python-virtualenv python3-virtualenv  python-dev python3-dev  python3-tk ```

I'll remove that from the compute-node part of the post install script and try again.

**Comment by enrico-usai** [comment]
In your previous [pip.freeze-compute.txt](https://github.com/aws/aws-parallelcluster/files/3780442/pip.freeze-compute.txt) file there were a lot of other packages. Why is it different from the latest `pip freeze` output?

Btw, starting from 2.4.1 ParallelCluster runs all node daemons and cookbook recipes in isolated Python virtualenvs, but it is not true for cfn-init command.

You could adapt your post install script to install the pip packages in a virtual environment and use it for your application. Is it something achievable?

P.S. you don't need to create a new cluster to test a different post install script but just update it and spin up a new compute node by submitting a job, the new compute node will use the new post-install script.

**Comment by jprobichaud** [comment]
Thanks again for your help.  The previous pip.freeze-compute.txt was when
the grid was built with pcluster 2.4.0.

I've disable the installation of any python-related stuff for compute nodes
from the post install script.  Now things move a bit forward (no more logs
in /home/logs/compute) but I still get errors in the sqswatcher logs and
the compute node doesn't get added to the execution host list.

Maybe the creation of the master node was impacted (with 2.4.0).  I'll try
to recreate a brand new grid setup so that the master node creation goes
without potential conflicts.  I remember having to "finish" the sge portion
of the master node configuration.  Perhaps that caused issues too.

**Comment by enrico-usai** [comment]
Yes, the master installation must be completed correctly to ensure ParallelCluster works correctly.
Please keep us updated.

**Comment by jprobichaud** [comment]
Ok, so it's not clear to me what really happened.  I rebuilt a completely new environment, starting with a pretty much empty post_install script and adding back everything, almost line by line.  In the end, there isn't a really big difference, except that the following lines were removed:

```
apt-get -y install python-pip python3-pip python-virtualenv python3-virtualenv  python-dev python3-dev  python3-tk

pip2 install --upgrade pip                                                                                                       
pip3 install --upgrade pip
```

Note that I'm still installing python3.6 on the compute nodes and it works...
I'm not sure what else outside my post install script changed so that it suddenly stop working.  Quite puzzling.

Anyway, thanks for your help.

**Comment by sean-smith** [comment]
Hi @jprobichaud,

Glad everything is working now - we install not only a virtualenv in 2.4.1 but also use pyenv to install a specific version of python tied to that virtualenv. Currently that's python 3.6.9. 

Please update the ticket if this continues to be a problem in pcluster 2.4.1. I'll be interested to see what's going on.

**Comment by jprobichaud** [comment]
Thanks for your help, I'm really sorry to have to reopen this ticket.  The system worked for few hours, then we went back to the same issues as before:
```
129 + cfn-init -s parallelcluster-RevSpeechGrid50 -v -c default -r ComputeServerLaunchTemplate --region us-west-2
130 Traceback (most recent call last):
131   File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
132     stream.write(fs % msg.encode("UTF-8"))   
133 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 72: ordinal not in range(128)
134 Logged from file util.py, line 476
135 Traceback (most recent call last):
136   File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
137     stream.write(fs % msg.encode("UTF-8"))
138 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 80: ordinal not in range(128)
139 Logged from file util.py, line 476  
140 Traceback (most recent call last):
141   File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
142     stream.write(fs % msg.encode("UTF-8"))
143 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 53: ordinal not in range(128)
144 Logged from file util.py, line 476
145 Traceback (most recent call last):
146   File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
147     stream.write(fs % msg.encode("UTF-8"))
148 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 53: ordinal not in range(128)
149 Logged from file util.py, line 476```

Python 2.7 has the following warning
```
#Printing to terminals sometimes fails. For example, 
#with an encoding of 'cp1251', the above write will 
#work if written to a stream opened or wrapped by 
#the codecs module, but fail when writing to a 
#terminal even when the codepage is set to cp1251. 
#An extra encoding step seems to be needed. 
stream.write((ufs % msg).encode(stream.encoding))```

Right now, with ubuntu 16.04, we can't easily go over 2.7.12.  The bug was supposedly fixed in 2.7.17 (which we need to install from source).  I'll try that and if it works, I'll go with the custom_ami image route to save on compute-node preparation time.

Is there any special reason we have a dependency on python2 in one place in the system and with python3 elsewhere?

**Comment by lukeseawalker** [comment]
Hi @jprobichaud,
python2 comes from the OS package `python` installed as a prerequisite package.
Python 3.6.9 is installed from version 2.4.1 and used by parallelcluster virtualenvs.

Were you able to solve the issue with the custom AMI?

**Comment by jprobichaud** [comment]
yes rebuilding everything with the help of a custom ami worked. So I guess
we're unblocked, but that's pretty sad resolution.  The system was working
flawlessly for months and suddenly stopped working with no way to repair
it.
