### ISSUE TITLE
Couldn't ssh to Master node -permission denied

### ISSUE THREAD

**Issue by rajiv03** [aws/aws-parallelcluster#1403]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.4.1]
 - OS: [e.g. alinux]
 - Scheduler: [e.g. torque]
 - Master instance type: [c5n.xlarge]
 - Compute instance type: [c5n.18xlarge]

I have been using awsparallelcluster successfully and suddenly not able to ssh to Master node. When I try to login it produces 

pcluster ssh HPCcompchem -i ~/.ssh/mykey_rajiv.pem 
ec2-user@34.232.214.7: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

It should be noted previously I was able to use same key "mykey_rajiv" and able to login Master.

Here is my 
[pcluster-cli.log](https://github.com/aws/aws-parallelcluster/files/3792365/pcluster-cli.log)

Config :

[aws]
aws_region_name = us-east-1

[cluster default]
key_name = mykey_rajiv
vpc_settings = public
base_os = alinux
initial_queue_size = 0
max_queue_size = 25
scheduler = torque
master_instance_type = c5n.xlarge
compute_instance_type = c5n.18xlarge
cluster_type = spot
scaling_settings = custom
s3_read_write_resource = arn:aws:s3:::xxx-xxx*
ebs_settings = tfs
placement_group = DYNAMIC
#master_root_volume_size = 500
#compute_root_volume_size = 500
#enable_efa = compute

[scaling custom]
scaledown_idletime = 10

[vpc public]
vpc_id = vpc-xxxx
master_subnet_id = subnet-xxxx

[ebs tfs]
volume_type = st1
volume_size = 800

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

**Comment by enrico-usai** [comment]
Hi @rajiv03 
from the CLI log it seems you recently updated the cluster, what configuration parameter did you change?

**Comment by lukeseawalker** [comment]
Hi @rajiv03,
are you sure that you are using the right key?
In the CLI log I see that in the past you used `/Users/raju/Downloads/mykey_rajiv.pem` instead of `~/.ssh/mykey_rajiv.pem` 

L

**Comment by rajiv03** [comment]
@lukeseawalker It's a same key. I've just moved a key "mykey_rajiv.pem" to ~/.ssh/ location. This is exactly same key which i use for other EC2 instances too!( works fine for others)

**Comment by lukeseawalker** [comment]
Hi @rajiv03,
I'm not able to reproduce. Can you please post the sequence of actions done on the cluster? Is it always reproducible on your side?
