### ISSUE TITLE
updating an existing cluster fails without trace

### ISSUE THREAD

**Issue by jprobichaud** [aws/aws-parallelcluster#1410]
**Environment:**
 - AWS ParallelCluster aws-parallelcluster-2.4.1
 - OS: ubuntu 16.04
 - Scheduler: SGE
 - Master instance type: c5.9x
 - Compute instance type: c5.4x

**Bug description and how to reproduce:**
When I try to run `pcluster update --config config.test ClusterName`, I get to the point where I see `UPDATE_ROLLBACK_IN_PROGRESS` and the script exists without any useful info as to why the rollback was necessary.

**Additional context:**
The changes in the config file are:
1) removing the use of a post_install scrcipt (removing the `post_install=...` line)
2) introducing the `custom_ami=` field with a new ami image (before, no AMI image was specified)

**Comment by lukeseawalker** [comment]
Hi @jprobichaud,
can you please go through the AWS console and check the "Events" tab of the CloudFormation stack of your cluster?

Please also notice that, at the moment, this is the behaviour of the update commands for the following parameters:
* custom_ami - master and running compute nodes will not be replaced. Only new compute nodes after a scale up events will be launched using the ami specified
* post_install - only new nodes will use the updated parameter

Thanks
L

**Comment by jprobichaud** [comment]
Thanks for the pointers.  It seems the error occurs when the update tries to update the MasterServer information.  It looks like:

|  Timestamp                   |   logical id  | status | reason |
|------------------------------|---------------|--------|--------|
| 2019-11-06 13:47:15 UTC-0500 |parallelcluster-RevSpeechGrid50 |	UPDATE_ROLLBACK_IN_PROGRESS	 |The following resource(s) failed to update: [MasterServer].|
| 2019-11-06 13:47:14 UTC-0500 |MasterServer	 |UPDATE_FAILED	 |Interface: [eni-0789f2c4b11a2e2bd] in use. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidNetworkInterface.InUse; Request ID: b61da910-4386-4cac-b9e7-d22c68c6bcd0)|
| 2019-11-06 13:46:57 UTC-0500 |MasterServer |	UPDATE_IN_PROGRESS	 |Requested update requires the creation of a new physical resource; hence creating one.|
| 2019-11-06 13:46:48 UTC-0500 |EBSCfnStack	 |UPDATE_COMPLETE |	-|
| 2019-11-06 13:46:47 UTC-0500 |EBSCfnStack	 |UPDATE_IN_PROGRESS |	-|
| 2019-11-06 13:46:08 UTC-0500 |parallelcluster-RevSpeechGrid50	 |UPDATE_IN_PROGRESS |	User Initiated|

**Comment by jprobichaud** [comment]
Note that the master node is currently running (currently serving files) but no jobs can be submitted yet.  After these steps, all the steps performed are to perform cleanup & rollback.  Is there a way to not touch the cpumaster itself and only update the compute node portion?

**Comment by lukeseawalker** [comment]
At the moment there is no way to update only the compute nodes portion and my previous sentence about the behaviour of the custom_ami parameter was wrong: its change does impact also the master instance.

I'm marking this as a bug since it shouldn't have allowed you to launch the update.

**Comment by jprobichaud** [comment]
I see.  So technically, if I modify the custom_ami line, it will attempt to
rebuild the master node as well?  This is problematic I guess because one
good reason to change the custom_ami is to make the post_install script as
minimal as possible to speed up the  creation of compute nodes without
having to wait for a bunch of custom software to get installed every time.

**Comment by lukeseawalker** [comment]
Master and compute use the same AMI, so the custom_ami parameter applies on both.
> one good reason to change the custom_ami is to make the post_install script as
minimal as possible to speed up the  creation of compute nodes 

this is still valid, you have to create a new cluster using the custom_ami parameter from the beginning

**Comment by jprobichaud** [comment]
> this is still valid, you have to create a new cluster using the custom_ami parameter from the beginning

I'd like to challenge this.  In our use case, the master node generally gets a lot of extra customization after its initial creation: users, EBS volumes attached and mounted a certain way, closed-source software compiled/install with certain specifications, etc..

To not be able to update the compute nodes AMI without having to get the master node rebuild as well is a serious hurdle.  Stacking a lot of stuff in the post-install can seriously impact the time for compute nodes to be available and represent a waste of time and money.  The custom ami approach reduces this loss greatly.  As time goes, we add to the post_install script to further control what's going on the compute nodes and at some point, it would be useful to generate a new AMI without having to touch the master node itself.

Can we have that as a feature request?  Could it be possible to update the compute nodes AMI without requiring to destroy the Master node instance?

**Comment by demartinofra** [comment]
Let me mark this as a feature request so that we can reason around a better support for such use cases.

A few additional comments that might help you improve the current experience with ParallelCluster:
- You can try to structure your post-install script so that some commands are only running on the master or compute nodes. See [this doc page](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html) for additional details. 
- You could consider installing software on external EBS drives so that if you need to create a new cluster you can attach an existing EBS
- You could share installed software over the shared file systems: EBS over NFS, EFS, FSX Lustre
- Theoretically you could replace the AMI used by compute nodes without affecting the master AMI but this is not natively supported by ParallelCluster. It requires making some AWS calls in order to replace the AMI in the ComputeServerLaunchTemplate that gets created with the cluster. I wouldn't advice going this path unless strictly necessary.

**Comment by enrico-usai** [comment]
Release [2.8.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.8.0) is out (and [2.8.1](https://github.com/aws/aws-parallelcluster/releases/tag/v2.8.1) too). One of the enhancements of the 2.8.0 is: _"Renewed user experience and robustness of cluster update functionality"_ and this failure during the update will be prevented.

I'm going to close this issue, feel free to open a new one if you encounter similar problems.
