### ISSUE TITLE
OpenMPI LD_LIBRARY_PATH not set

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#1418]
The default mpirun/mpiexec is OpenMP and should work out of the box, however, I am getting the error: `error while loading shared libraries: libmpi.so.1: cannot open shared object file: No such file or directory`. This is due to LD_LIBRARY_PATH being empty.

Enabling MPI via [module load intelmpi](https://docs.aws.amazon.com/parallelcluster/latest/ug/intelmpi.html) results in a working LD_LIBRARY_PATH:
LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2019.4.243/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2019.4.243/linux/mpi/intel64/lib:/opt/amazon/efa/lib64

**Comment by sean-smith** [comment]
can you share the output of `module load openmpi && echo $LD_LIBRARY_PATH `

**Comment by RickoLacharity** [comment]
Thanks!
