### ISSUE TITLE
BUG: Setting master_subnet_id and compute_subnet_id to the same value -> compute nodes fail to come online

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#1427]
Configuration:
```
[global]
sanity_check = true

[vpc ***]
master_subnet_id        = subnet-1234
compute_subnet_id     = subnet-1234
```
Result:
```
Beginning cluster creation for cluster: mycluster
Creating stack named: parallelcluster-mycluster
Status: parallelcluster-torque - ROLLBACK_IN_PROGRESS
Cluster creation failed.  Failed events:
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 0 SUCCESS signal(s) out of 2.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```

Note: cluster creation fails because initial_queue_size = 2. If initial_queue_size = 0 it will succeed, but when jobs get added to the queue, compute nodes will come online but fail to register with the master instance.

I thought there was nothing wrong with being explicit and expected that `master_subnet_id= compute_subnet_id  = <id>` behave the same as `master_subnet_id = <id>`. The documentation here only shows examples where the subnets are different: https://docs.aws.amazon.com/parallelcluster/latest/ug/networking.html

**Comment by lukeseawalker** [comment]
Hi @RickoLacharity,
thank you for the feedback. This has been fixed both in the [code](https://github.com/aws/aws-parallelcluster/pull/1273) and in the [docs](https://github.com/awsdocs/aws-parallelcluster-user-guide/pull/8) and will be avail in the next release
