### ISSUE TITLE
Support for multiple-instance types mapped into partitions

### ISSUE THREAD

**Issue by steveisoft** [aws/aws-parallelcluster#1448]
We are using parallelcluster w/ slurm, but have a requirement for multiple ComputeFleets that are mapped into slurm partitions, so we can distribute the various kinds of jobs.

Yes, we could use multiple clusters, but this is dissimilar to our existing non-cloud environment, and is considered unacceptable overhead.

**Comment by sean-smith** [comment]
@steveisoft Thanks for the feature request!

**Comment by sean-smith** [comment]
Duplicate of https://github.com/aws/aws-parallelcluster/issues/1066
