### ISSUE TITLE
Support for CentOS 8

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#1453]
Hello AWS-parallelcluster Team,
I'm planning a bit ahead for a couple of projects and was wondering if the 2.4.2 release or future will include a CentOS-8 flavor. Thanks.

**Comment by sean-smith** [comment]
Hi @afernandezody, The next release, `2.5.0`, doesn't include Centos 8.

**Comment by afernandezody** [comment]
Thank you for the info.

**Comment by ya7ia2017** [comment]
Hi AWS-parallelcluster Team,

Is AWS-parallelcluster going to support Centos 8 version in the next release. And if yes when can we expect that.

Thanks.

**Comment by demartinofra** [comment]
Hi @ya7ia2017 ,

I have good news! I can confirm that Centos 8 support is going to be released with the upcoming version of ParallelCluster 🚀

**Comment by WajdiH** [comment]
Thank you for the info.
 Is there any ETA  for the next release.

**Comment by demartinofra** [comment]
We do not have a definitive date set for this feature and release, but we are preparing our next version for release in the next few weeks. We will update this issue once we have completed our next release.

**Comment by WajdiH** [comment]
Thank you for the update.

**Comment by demartinofra** [comment]
Support for Centos 8 was added as part of 2.10.0 release: https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.md#2100

**Comment by afernandezody** [comment]
Hi @**demartinofra**. Thank you for the new feature and the update. Not sure how the decision by Redhat is going to affect aws-parallelcluster (and many other projects) but I guess that everyone has about a year to figure things out.
