### ISSUE TITLE
Question: FSx for Windows File Server

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#1454]
My use case is that I want to use some Windows Server over RDP to run some Windows-only-software, and then to launch jobs on the AWS ParallelCluster-cluster. So I would like a shared filesystem for all my AWS instances regardless of the OS.

Does AWS ParallelCluster work with FSx for Windows File Server? If I pass the fsx_id here: https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html#fsx-fs-id will it work?

**Comment by sean-smith** [comment]
@RickoLacharity No, that's only for FSx Lustre. You can achieve the same behaviour using FSx's data repository (export to S3) functionality. Run the windows jobs, then export to a s3 bucket which is set as the `import_path` for the FSx Lustre file system.
