### ISSUE TITLE
pcluster update does not update compute instance types or min/max size

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#1455]
With the original configuration:
```
compute_instance_type   = c5.large  
initial_queue_size      = 2
max_queue_size        = 2
maintain_initial_size   = true    
```
Changing the values to:
```
compute_instance_type   = c5.2xlarge  
initial_queue_size      = 3
max_queue_size        = 3
maintain_initial_size   = true    
```
and running:
```
pcluster stop test-cluster
pcluster update test-cluster
pcluster start test-cluster
```
Results in 2 compute nodes of type c5.large.

Are there additional steps that are necessary to update the cluster configuration? Can some values not be updated? 
Ref: https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.update.html

**Comment by sean-smith** [comment]
@RickoLacharity Add the `--reset-desired` flag.

```bash
pcluster update test-cluster -rd
```

**Comment by RickoLacharity** [comment]
@sean-smith Based on the documentation im not sure how this would help: "Resets the current capacity of an Auto Scaling Group _to the initial configuration values_."

**Comment by RickoLacharity** [comment]
I was able to get the update to work by"
```
pcluster stop test-cluster
(manually check AWS console and wait for instances to enter terminated state)
pcluster update test-cluster
pcluster start test-cluster
```
