### ISSUE TITLE
CUDA not installed at startup on Ubuntu 16.04

### ISSUE THREAD

**Issue by skoocda** [aws/aws-parallelcluster#147]
Created a cluster with (abridged) config:

>[cluster default]
>master_instance_type = m4.xlarge
>compute_instance_type = g2.2xlarge
>base_os = ubuntu1604
>post_install = s3://<PATH_TO_FILE>.sh

NVIDIA driver installed correctly, but CUDA toolkit did not. 

No entry exists in `/usr/lib`, `/usr/bin`, `/usr/local` or any other logical location

Nor was nvcc shown as installed, as listed by `nvcc -V`

However, `sudo apt install nvcc` worked correctly when run manually in the compute instance.

From issue #140 and #123 I surmise that this is not intended behaviour, as CUDA should be installed upon creation.

**Comment by skoocda** [comment]
Is there an option to specify a variable for CustomChefRunList or can I potentially add this to extraJson:
`
“nvidia” : {
        “enabled” : ‘yes’
    }
`

**Comment by skoocda** [comment]
Seems to be caused by the c++ compiler version, which is incompatible with CUDA 7.5

**Comment by mohanasudhan** [comment]
We don't plan to add native cuda support in cfncluster.

**Comment by mohanasudhan** [comment]
My bad !!! I will take a deep look at this issue tomorrow.

**Comment by mohanasudhan** [comment]
Apologies for delay in looking at this issue (was working on cfncluster new release). As part of cfncluster 1.4.0 we upgrade to cuda9 and nvidia driver. Can you confirm you still see this issue? Note : we are not installing nvcc as part of cookbook

**Comment by jprobichaud** [comment]
I'm using cfncluster 1.4.1 and I've put the following snippet in my cluster definition:

```
base_os = ubuntu1604
extra_json : { "nvidia" : { "enabled" : "yes" } }
compute_instance_type = p3.8xlarge
master_instance_type = c5.4xlarge
```
On the compute nodes, /opt has no traces of CUDA of any sort.  What am I doing wrong?

**Comment by demartinofra** [comment]
As part of ParallelCluster 2.5.0 we updated Nvidia drivers and CUDA libraries and introduced tests that verify their setup. I'm going to resolve this one.
