### ISSUE TITLE
Custom ami EFA kernel header install issue

### ISSUE THREAD

**Issue by medcelerate** [aws/aws-parallelcluster#1480]
**Environment:**
 - aws-parallelcluster-2.4.1
 - OS: alinux
 - Scheduler: Slurm
 - Master instance type: m4a.4xlarge
 - Compute instance type: m4a.4xlarge

**Bug description and how to reproduce:**
Nodes suddenly stopped passing user health checks yesterday when being spun up. After looking at the logs there appears to be an issue with the efa installer not properly installing due to missing kernel headers. This behavior just began to happen and there have been no changes to our custom AMI. The chef command prodcues this error:

```
kernel headers were not detected and are required to build the efa kernel
```

**Comment by ddeidda** [comment]
@medcelerate, we'd need some additional information to start investigating on your problem:

- which process did you follow to create it among the ones we describe here: https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html
- which base ami did you use to create your custom-ami?
- your pcluster config file
- the log file from were you extracted the error
- /var/log/cfn-init.log, /var/log/cloud-init.log and /var/log/cloud-init-output.log files from the Master node
- one of the instance-id.tar.gz files inside the /home/logs/compute dir  

In any case, please also notice that parallelcluster 2.5.0 is now available.

**Comment by demartinofra** [comment]
Resolving for a lack of response. Please feel free to re-open by providing the requested info in case the issue still persists.
