### ISSUE TITLE
Issue with Cluster Deletion CLI

### ISSUE THREAD

**Issue by stefan-maxar** [aws/aws-parallelcluster#1485]
**Environment:**
 - aws-parallelcluster-2.5.0
 - OS: ALinux
 - Scheduler: Slurm
 - Master instance type: r5.24xlarge
 - Compute instance type: c5/c5n.18xlarge

**Bug description and how to reproduce:**
When deleting a cluster from the command line, the CLI command executed doesnt return back cleanly even though the associated cloud formation stack shows successfully deleted within the AWS Console.  

**Additional context:**
I have created/deleted several clusters using pcluster 2.5.0 that successfully delete according to CloudFormation but the command line returns error. For example, I run the following command to delete my cluster:
`pcluster delete -c config-us-east-1.dev pcluster-intel-testing`

The returned status (with exit) from this command is:
`Deleting: pcluster-intel-testing
Status: ComputeSecurityGroupIngress - DELETE_COMPLETE                           ERROR: Stack with id parallelcluster-pcluster-intel-testing does not exist
`

However, when I go to the AWS console and look at the CloudFormation stack (screenshot attached), it shows that the stack (cluster) deleted successfully with no issue. Could be a race condition between the complete status not getting there before the next step of deletion taking place?
![cfn-status](https://user-images.githubusercontent.com/57150975/69348274-e73b8080-0c43-11ea-8234-d062c430544d.png)

**Comment by ddeidda** [comment]
@stefan-maxar this problem has been fixed by this commit https://github.com/aws/aws-parallelcluster/commit/83f32f7892c13144ce7895b57c424721603e6e3b; this fix will released with the next version. Thanks for the notification

**Comment by demartinofra** [comment]
Reopening this and marking with the pending release label. We'll keep this open until a new patch release containing the fix is published

**Comment by demartinofra** [comment]
Fixed in https://github.com/aws/aws-parallelcluster/releases/tag/v2.5.1
