### ISSUE TITLE
pcluster create does not exit with a error status if the CloudFormation deploy fails

### ISSUE THREAD

**Issue by isobit** [aws/aws-parallelcluster#1487]
**Environment:**
 - AWS ParallelCluster 2.5.0
 - OS: Linux

**Bug description and how to reproduce:**
Handling CloudFormation stack deploy failures in automated scripts is difficult because the `pcluster create` command does not report failures with an exit status (returns 0 instead).

PR  #1472 should fix this issue.

**Comment by ddeidda** [comment]
Thank you @isobit for reporting this and for the contribution! Your PR is now under review by the team; you will be notified in case of comments and/or merge.

**Comment by demartinofra** [comment]
PR has been merged 🚀. Thanks for the contribution 👍
