### ISSUE TITLE
Intel Run Time Environment

### ISSUE THREAD

**Issue by stefan-maxar** [aws/aws-parallelcluster#1489]
**Environment:**
 - AWS ParallelCluster 2.5.0
 - OS: alinux
 - Scheduler: Slurm
 - Master instance type: r5.24xlarge
 - Compute instance type: c5/c5n.18xlarge

**Bug description and how to reproduce:**
I am noticing that when spinning up a cluster using v2.5.0, the "/opt/intel" directory is now NFS shared to all worker nodes from the master node. In v2.4.1, this was not the circumstance. Is this intentional for all OSes? 

We were previously installing the Intel Parallel Studio XE run time environment on each worker node. Just making sure that if we update our post-install script to install Intel PSXE only on the master node, the shared "/opt/intel" directory wont go away in future releases. 

**Side note**
Looking forward to possibly utilizing "enable_intel_hpc_platform = true" for the alinux OS, as the above becomes a moot point. We currently download the Intel PSXE RPMs via yum download only, tar ball them, then host them in S3 for use during post install. We go this route so we can do local installs than having to go to the internet (Intel's repos). Going to the internet is another potential failure point, so I am curious if AWS is hosting the Intel PSXE (and MPI) RPMs locally in S3 for use with ParallelCluster.

**Comment by sean-smith** [comment]
This is intentional, `/opt/intel` will be shared out in future releases. See https://github.com/aws/aws-parallelcluster/issues/1351

The installer script we host ourselves on S3 however the RPM's are hosted by intel.

Thanks for the feedback on adding `alinux` we've taken that into account!

**Comment by demartinofra** [comment]
I'm going to resolve this since apparently all questions have been answered. Feel free to reopen if I missed anything. Thanks :)
