### ISSUE TITLE
Please add support of centos7 AMI for parallelcluster2.5 in China

### ISSUE THREAD

**Issue by taoshen-amazon** [aws/aws-parallelcluster#1505]
Issue: Currently centos7 is not supported by paralleclcluster2.5 in China. so we import centos7 AMI from global to China region as below( cn-north-1:ami-01dae255109c43579  ; cn-northwest-1:ami-0fc6ec4d2967b6e32). 

but when we create cluster by pcluster with configuration as :
      customer_ami=amiID(shown above)
      base_os=centos7

it tripped "Template error: Unable to get mapping for AWSRegionOS2AMI::cn-north-1::centos7"

so could you please add support of these two centos7 AMI for parallelcluster2.5 in China or modify the template to accept centos7 with custom AMI?

**Comment by demartinofra** [comment]
You should be able to use a custom_ami with centos7 in China.

I think you might have a typo in your config: `customer_ami` -> `custom_ami`

Also if you agree I'd go ahead and resolve this in favour of this duplicate: https://github.com/aws/aws-parallelcluster/issues/1491
