### ISSUE TITLE
Request: Secured (private) post-install scripts

### ISSUE THREAD

**Issue by briandobbins** [aws/aws-parallelcluster#1511]
Hi all,

  This is more of a feature request than a bug, and maybe there IS a way to do it, I'm just not seeing it yet?  I want to be able to provide, securely, a list of users to add during postinstall.  I've got a python script that sets up their accounts, environment, etc., but if it's uploaded to an s3 bucket without public access, the postinstall phase can't access it (access forbidden).  I also can't bake in my credentials, so this is to be used by multiple people each with their own credentials.

  At the moment, I'm thinking of getting around this by writing a wrapper around pcluster that sets it up, then once finalized, SFTP's some credentials, downloads the script, runs it, deletes the credentials, and THEN says the cluster is ready, but I have to believe some automated way of securely uploading local files without needing public access would be better?

  I'm new to parallelcluster, so again, hopefully I'm just missing a simple way of doing it, but I thought I'd ask.

  Thanks,
  - Brian

**Comment by enrico-usai** [comment]
Hi @briandobbins 

For multi-user support we created [a wiki page](https://github.com/aws/aws-parallelcluster/wiki/MultiUser-Support) that follow a path similar to the one you described.

You can manage S3 permission through the [`s3_read_resource` and `s3_read_write_resource` parameters](https://docs.aws.amazon.com/parallelcluster/latest/ug/s3_resources.html) in the AWS ParallelCluster configuration.

Let us know if it helps.

**Comment by briandobbins** [comment]
Hi Enrico,

  Well, that helps immensely - guess I should've looked around a bit more first!  It seems my issue is solved.  Just to clarify, though, does the s3_read_resource parameter change permissions of the listed files (it seems not), or simply configure read access somehow for the instance?

  Thanks again for your help, and I'll close this after your response.

  - Brian

**Comment by enrico-usai** [comment]
When specifying a bucket through the `s3_read_resource`, a new statement will be attached to the Policy used for the RootRole assigned to the ParallelCluster instances.
It doesn't change the file permissions.

**Comment by briandobbins** [comment]
Thanks again - I clearly need to learn more about policies and roles!  I'm closing this now.
