### ISSUE TITLE
Q: Setting hostname of master node?

### ISSUE THREAD

**Issue by briandobbins** [aws/aws-parallelcluster#1514]
Hi all,

  Is there a simple way to set a specific hostname for the master node when using parallel cluster?  I can override the default with a hostnamectl command, but the queuing system is configured to point to the default hostname, so I need to change things in several places, and restart services.  I was wondering if there was an easier way?

  I did try setting it in the pre_install phase, hoping the installation of the queuing software would pick up on that, but it seems to get overwritten before then.  Maybe turning the hostname setting off in the cloud-init would work, but I thought I'd ask first in case anyone has ideas or experience first.

  Thanks again,
  - Brian

**Comment by enrico-usai** [comment]
Hi @briandobbins ,

currently it is not possible to change the master hostname.
The cluster configuration relies on the private FQDNs resolved through the VPC DNS.

There is a quite similar issue https://github.com/aws/aws-parallelcluster/issues/1192 on which an user is trying to use a custom DHCPOptionSet but it is not supported out of the box by ParallelCluster.

An alternative to get rid of the master public ip could be to use a proxy instance:
* [aws-parallelcluster-in-a-single-private-subnet-connected-using-direct-connect](https://docs.aws.amazon.com/parallelcluster/latest/ug/networking.html#aws-parallelcluster-in-a-single-private-subnet-connected-using-direct-connect)
* [aws-parallelcluster-private-deployment-in-hardened-vpcs](https://bioteam.net/2019/11/aws-parallelcluster-private-deployment-in-hardened-vpcs/)


Let us know if it helps.

**Comment by briandobbins** [comment]
Hi Enrico,

  That helps, yes, thank you.  Our interest is less in getting rid of the master public IP, and more of convenience - we have some software that uses the hostname of the login node for configuration purposes, and additionally having a consistent hostname would allow for better documentation.

  If I understand this correctly, though, since we're aiming at providing a wrapper script around 'pcluster' (and thus handles the 'pcluster configure' which in 2.5.0 creates the VPC?), I could add my own VPC creation logic, and deploy parallel cluster into that VPC via the [vpc] directives, and as long as it has DNS enabled, do it that way?  I'm not _entirely_ sure yet how to do that, since I'd have to have the system identifying as MasterServer choose a specific IP in that VPC or something, but this _should_ be feasible?

  At any rate, it's not critical, it'd just be 'nice'.  We can work around it in the meantime, but I'd love any thoughts you have, and then I'll close this ticket.

  Thanks,
  - Brian

**Comment by demartinofra** [comment]
What about creating an Elastic IP and have this associated to the master node after the cluster is created? 

You could disable the automatic creation of an elastic IP for the master node by using [use-public-ips](https://docs.aws.amazon.com/parallelcluster/latest/ug/vpc-section.html#use-public-ips) config option and then have your own EIP that you can preserve after cluster deletion and reuse for a new cluster.
If you do that just make sure the subnet you use for the compute nodes has a NAT device or Auto-assign Public IP is set to true.

**Comment by briandobbins** [comment]
Hi all,

 Sorry for the delay - I'm just getting back to this after other work deadlines and the holidays.  Once again, this is non-critical, I'm just curious about ideas.  In terms of using an Elastic IP, that's not really viable in this case since we're providing software that *other* people run, with their own credentials, to create a cluster capable of running our code.  This would require us to know / create / user elastic IPs from their accounts, which seems unnecessary for ephemeral clusters.

  I think if I do pursue this, I'll just look to use our own template for VPC creation with a DNS mapping for master & compute nodes.  I'm going to close this ticket given that I think that'll work and there doesn't seem to be an 'easier' solution.  

  Thanks again,
 - Brian
