### ISSUE TITLE
Compute environment is only configured for default user

### ISSUE THREAD

**Issue by ErikLacharite** [aws/aws-parallelcluster#1520]
centos user (Centos 7) does not have permission to administer the cluster, no problem. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/10421041/70196205-da477400-16bc-11ea-84b4-a6dabd4a11ce.png)

However, the root account is not configured at all. 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/10421041/70195514-c733a480-16ba-11ea-8171-135dac9e0a80.png)

This problem was previously closed here: https://github.com/aws/aws-parallelcluster/issues/1159
but I would like to suggest a solution.

I noticed that the environment configuration is done in `/home/centos/.bashrc`
If this configuration was moved to `/etc/bashrc` then there would be no additional steps necessary to administer the cluster. Additionally, this could make it possible to add multiple user accounts to the cluster (`/home/` would need to be shared).

**Comment by sean-smith** [comment]
@RickoLacharity `/home` is already shared via NFS. This is an excellent feature request.

**Comment by lukeseawalker** [comment]
Closing this because scheduler profiles are in `/etc/profile.d`
