### ISSUE TITLE
Feature Request: Support for ARM compute nodes (Graviton2 instances)

### ISSUE THREAD

**Issue by RickoLacharity** [aws/aws-parallelcluster#1528]
Amazon recently announced these new instances: https://aws.amazon.com/ec2/graviton/
2x performance per core, 4x the number of cores, with (maybe) 40% lower $/performance.

**Comment by RickoLacharity** [comment]
Its a little early for this feature request since it was just announced and the instances are not even available yet and given that it will likely be a huge amount of work, this will probably be a longterm issue.

**Comment by nstornetta** [comment]
Thanks, @RickoLacharity for creating this feature request. Like you, we're excited about the next generation of Graviton instances and want to give ParallelCluster users access to the broadest and deepest platform of choice to suit any kind of workload they want to bring to AWS. 

Like you've said, this is still a bit far off, but you can expect that we will do our part to make these available as soon as we reasonably can. 😄

**Comment by afernandezody** [comment]
Hello,
Any news if this feature will be available for 2.6.2? Also, any comment on which OS will be supported?
Thanks.

**Comment by lukeseawalker** [comment]
Hi @afernandezody,
it's a work in progress, if you want you can keep an eye on the following PR https://github.com/aws/aws-parallelcluster/pull/1743

**Comment by afernandezody** [comment]
Hello @**lukeseawalker**,
I'm following the PR and the merging with the master branch. Most things are straightforward to follow (although it's not my area of expertise, and I'm just trying to understand the overall picture not every detail). It seems like the available OSs are going to be ALinux2 and Ubuntu (16.04 & 18.04), and the validator checks whether the OS matches with the architecture, which is what one would expect. However, I haven't been able to find the ARM AMIs. The lists at https://github.com/tilne/aws-parallelcluster/blob/support-for-arm-instances/amis.txt and at https://github.com/aws/aws-parallelcluster/blob/wip/arm-support-feature-branch/amis.txt  (after merging) include x86_64 AMIs. A potential explanation is that the OSs are the last step in the process but wouldn't they be necessary to complete the tests? It feels like I'm missing something. Thanks.

**Comment by lukeseawalker** [comment]
AWS ParallelCluster 2.8.0 with ARM support has been released https://github.com/aws/aws-parallelcluster/releases/tag/v2.8.0
