### ISSUE TITLE
Creating custom AMI in restricted environment

### ISSUE THREAD

**Issue by naveenkns** [aws/aws-parallelcluster#1529]
Hi,
We are using pcluster 2.4.1 and 2.5.0 and we work on Ubuntu1604/1804, Centos, RHEL clusters.
One issue we are facing while creating custom AMI with 'pcluster createami' is with the public IPs. In our corporate VPC/Subnets we do not have public subnets and can not attach any EIPs. How to overcome issue with packer which tries to connect to interim instance via EIPs. Can we make it to use private IPs instead.

**Comment by lukeseawalker** [comment]
Hi @naveenkns,
since 2.5.0 you can use the following `createami` flag:
```
  --no-public-ip        Do not associate public IP to the Packer instance.
                        Defaults to associate public ip
```

**Comment by naveenkns** [comment]
Thanks Lukeseawalker, will try this feature and update the thread with comments.
