### ISSUE TITLE
SGE compute nodes failing to come online because of python 2.7 deprecation  

### ISSUE THREAD

**Issue by jprobichaud** [aws/aws-parallelcluster#1551]
**Environment:**
 - AWS ParallelCluster 2.4.1
 - OS: ubuntu 16.04
 - Scheduler:  SGE
 - Master instance type: c5.4xlarge
 - Compute instance type: c5.9xlarge

Since yesterday, our compute nodes can't come online.  We see the instance starting but the sanity checks fail and the instance gets terminated before it gets added to the list of available hosts and even before failed logs gets moved to the master /home/logs/compute directory.

I managed to salvage some logs and it seems related to some chef instructions trying to pull python 2.7 (which is now deprecated)

Any advice?

```
482     Reading package lists...
483     STDERR: W: The repository 'http://ppa.launchpad.net/jonathonf/python-2.7/ubuntu xenial Release' does not have a Release file.
484     W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
485     E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-2.7/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]
486     E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]
487     E: Some index files failed to download. They have been ignored, or old ones used instead.
```

from cloud-init-output.log:
```
129 + cfn-init -s parallelcluster-Grid60 -v -c default -r ComputeServerLaunchTemplate --region us-west-2
130 Error occurred during build: Command chef failed
131 + error_exit 'Failed to run cfn-init. If --norollback was specified, check /var/log/cfn-init.log and /var/log/cloud-init-output.log.'
132 + region=us-west-2
```

**Comment by jprobichaud** [comment]
Looks like Jonathon F. put his PPA private.  

Does parallelcluster 2.5.1 still rely on python 2.7 anywhere ?

**Comment by lukeseawalker** [comment]
I don't think we are setting up that repository in our AMI. Are you using a custom one?
Can you please post `/etc/apt/sources.list` and the `/etc/apt/sources.list.d/` folder?

I wasn't able to reproduce with a default pcluster AMI.
