### ISSUE TITLE
cw-logs-substack.json access denied in ca-central-1

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1561]
**Environment:**
 - aws-parallelcluster-2.5.1
 - OS: centos7
 - Scheduler: slurm
 - Master instance type: c5.large
 - Compute instance type: c5.large

**Bug description and how to reproduce:**
When trying to create a new cluster with ParallelCluster 2.5.1 in the ca-central-1 region, I get an access denied error in cw-logs-substack. I was able to fix it by uploading the stack to my own bucket and providing a presigned URL in my custom ParallelCluster CFN stack.

On my end, it looks like the permissions on the ca-central-1 stack are wrong.

**Comment by sean-smith** [comment]
@joeydumont Are you using `develop` branch?

**Comment by joeydumont** [comment]
Oh, don't mind me. I apparently merged the CFN stack from the develop branch into my custom stack instead of the one at v2.5.1...
