### ISSUE TITLE
Please fix the console output of "pcluster createami"

### ISSUE THREAD

**Issue by rmarable** [aws/aws-parallelcluster#1562]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.4.1] 2.5.0
 - OS: [e.g. alinux] OSX-10.14.6 using iTerm 3.3.7
 - Scheduler: [e.g. SGE] SGE
 - Master instance type: [e.g. m5.xlarge] r5.large
 - Compute instance type: [e.g. c5.8xlarge] r5.large

**Bug description and how to reproduce:**
The output of "pcluster createami" does not wrap properly.  Using iTerm windows of 80 columns, only part of the output can be viewed.  Making the window bigger or smaller renders the screen completely unreadable (please see the attached screen captures for reference).

Is there anything we can do to improve this?
![Screen Shot 2019-12-17 at 2 33 51 PM](https://user-images.githubusercontent.com/13686337/71028103-a156c880-20da-11ea-8073-d2c7a8cf7031.png)
![Screen Shot 2019-12-17 at 2 33 33 PM](https://user-images.githubusercontent.com/13686337/71028104-a156c880-20da-11ea-8ce7-11efe3bb4a33.png)
![Screen Shot 2019-12-17 at 2 33 19 PM](https://user-images.githubusercontent.com/13686337/71028105-a156c880-20da-11ea-8bde-ffdd6d97b41a.png)

**Comment by sean-smith** [comment]
@RodneyMarable That's super ugly, it's supposed to be polling status of the packer status, only 1 line long. Can you try in screen / tmux and see if that changes it?

For example, here's how it looks for me:

![image](https://user-images.githubusercontent.com/5545980/71043448-7f157880-20e3-11ea-947a-791842b6ed7b.png)

**Comment by rmarable** [comment]
Same effect when using screen:

![Screen Shot 2019-12-18 at 10 44 50 AM](https://user-images.githubusercontent.com/13686337/71101005-01557980-2184-11ea-8a97-cadf24ffe664.png)
![Screen Shot 2019-12-18 at 10 44 41 AM](https://user-images.githubusercontent.com/13686337/71101006-01557980-2184-11ea-8849-a26414f7fe36.png)
![Screen Shot 2019-12-18 at 10 44 16 AM](https://user-images.githubusercontent.com/13686337/71101007-01557980-2184-11ea-9362-826734550a20.png)

I don't normally use tmux but I can see if this still happens as well.

**Comment by enrico-usai** [comment]
Hi @RodneyMarable sorry for the delay.

The [code](https://github.com/aws/aws-parallelcluster/blob/v2.5.1/cli/pcluster/commands.py#L779) should remove the previous row of the output and always print the status in the same line, but from your screenshots it seems there are some issues specific for the OSX client. 

I'm going to mark this as a bug. Thank you for reporting this.

**Comment by enrico-usai** [comment]
The issue might be still valid for ParallelCluster 2.x but as part of 3.0.0 release we totally refactored CLI output and added the possibility to [retrieve](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.get-image-log-events-v3.html) and [export](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.export-image-logs-v3.html) build image logs in a cleanest way.
