### ISSUE TITLE
"pcluster createami" uses an old version of pip

### ISSUE THREAD

**Issue by rmarable** [aws/aws-parallelcluster#1565]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.4.1] 2.5.0
 - OS: [e.g. alinux] OSX-10.14.6 (Mojave) operating on centos7 custom AMIs
 - Scheduler: [e.g. SGE] SGE
 - Master instance type: [e.g. m5.xlarge] r5.large
 - Compute instance type: [e.g. c5.8xlarge] r5.large

**Bug description and how to reproduce:**
During the end of the "pcluster createami" process, I noticed that Packer reports a dated version of pip is being used:
```
status: custom-centos7:   Running setup.py install for aws-cfn-bootstrap Packer 
status: custom-centos7: Successfully installed aws-cfn-bootstrap-1.4 lockPacker 
status: custom-centos7: You are using pip version 8.1.2, however version Packer 
status: custom-centos7: You should consider upgrading via the 'pip instalPacker 
status: ==> custom-centos7: Provisioning with shell script: /var/folders/Packer
```
Thanks,
Rodney

**Comment by rexcsn** [comment]
Hi Rodney,

We don't install pip during "pcluster createami". We are just using the pip that comes with the latest base AMI.
Would you need the latest pip for a specific package?


Best,
Rex

**Comment by rmarable** [comment]
This version of pip doesn't seem to cause problems with my custom image build.

**Comment by rmarable** [comment]
While this error is annoying, I've gone through several iterations of my custom image build process and have found no issues with this version of pip.  I'm going to close this issue - hopefully this will be addressed whenever the parent AMI is updated in the future.
