### ISSUE TITLE
`pcluster` command does not respect AWS_PCLUSTER_CONFIG_FILE

### ISSUE THREAD

**Issue by asford** [aws/aws-parallelcluster#1579]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.5.1]

**Bug description and how to reproduce:**
The `pcluster` command does not respect the target configuration file defined by the `AWS_PCLUSTER_CONFIG_FILE` environment variable. This is likely due a merge conflict in #1109 and #1298 at https://github.com/aws/aws-parallelcluster/blob/develop/cli/pcluster/config/pcluster_config.py#L94

**Comment by lukeseawalker** [comment]
AWS ParallelCluster 2.6.0 with the fix mentioned above has been released
