### ISSUE TITLE
SGE configuration MAX_DYN_EC and file descriptor limits on amazon linux

### ISSUE THREAD

**Issue by cchng** [aws/aws-parallelcluster#1592]
**Environment:**
 - AWS ParallelCluster aws-parallelcluster-2.4.1
- Amazon Linux
- SGE 
- read/write to EBS io1 1000GiB 16000 IOPS 

I am attempting to resolve https://github.com/aws/aws-parallelcluster/issues/26#issuecomment-571390632 - tried using storage optimized instance types but that did not resolve the issue.

Because we are using DRMAA to run the jobs, we are trying to increase MAX_DYN_EC to see if that resolves the issue. It follows that we had to increase file descriptor limits (S_DESCRIPTOR, H_DESCRIPTOR, ulimit).

```
qmaster_params               ENABLE_FORCED_QDEL ENABLE_FORCED_QDEL_IF_UNKNOWN \
                             ENABLE_RESCHEDULE_KILL=1 MAX_DYN_EC=5000 \
                             gdi_retries=5
execd_params                 S_DESCRIPTORS=8192,H_DESCRIPTORS=65536
```

```
$ ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 122546
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 122546
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
$ ulimit -aS
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 122546
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 122546
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

```
$ cat /proc/sys/fs/file-max
500000
``` 

I could see that the hard and soft descriptor limit has increased, but could not figure out why the max. file descriptors for communication is still 1003.
```
01/13/2020 16:45:24|  main|ip-172-31-41-73|I|starting up SGE 8.1.9 (lx-amd64)
01/13/2020 16:51:39|  main|ip-172-31-41-73|I|controlled shutdown 8.1.9
01/13/2020 16:51:40|  main|ip-172-31-41-73|I|read job database with 0 entries in 0 seconds
01/13/2020 16:51:40|  main|ip-172-31-41-73|E|error opening file "/opt/sge/default/spool/qmaster/./sharetree" for reading: No such file or directory
01/13/2020 16:51:40|  main|ip-172-31-41-73|W|nr of dynamic event clients exceeds max file descriptor limit, setting MAX_DYN_EC=978
01/13/2020 16:51:40|  main|ip-172-31-41-73|I|qmaster hard descriptor limit is set to 65536
01/13/2020 16:51:40|  main|ip-172-31-41-73|I|qmaster soft descriptor limit is set to 8192
01/13/2020 16:51:40|  main|ip-172-31-41-73|I|qmaster will use max. 1003 file descriptors for communication
01/13/2020 16:51:40|  main|ip-172-31-41-73|I|qmaster will accept max. 978 dynamic event clients
```

Any feedback or pointers appreciated.

**Comment by lukeseawalker** [comment]
Is the MAX_DYN_EC set before the demon is started? 
It seems that the file descriptor limits have increased, but I would try to restart the qmaster demon to see if something change.

**Comment by cchng** [comment]
Hi @lukeseawalker, yes, this is after restarting qmaster. Without restarting the qmaster hard/soft  descriptor limit won't change.

**Comment by demartinofra** [comment]
I tried several approaches, such as setting the ulimits for the user that runs the sge daemon (sgeadmin) and setting the limits directly in the `init.d/sgemaster.p6444`, but however the qmaster hard and soft descriptor limit is increased I'm still getting the error you reported `nr of dynamic event clients exceeds max file descriptor limit, setting MAX_DYN_EC=978`.

Have you already tried to report this on the SGE mail list: https://arc.liv.ac.uk/trac/SGE#mail?

**Comment by cchng** [comment]
@demartinofra thanks for looking into this. I have not reported it to SGE. Just wanted to make sure I did not miss anything with the OS or parallel cluster set up.

**Comment by demartinofra** [comment]
I'm going to close this for now but feel free to reopen if needed. And please in case you find a solution it would be great if you could share it with us.

**Comment by lilinji** [comment]
sge_qmaster didn't start! 
we kown be hosts error profit
resolve method change dns ：
edit：
#  vim /etc/hosts 

127.0.0.1        caleb   
#127.0.0.1      localhost.localdomain   localhost
129.67.46.255   caleb
