### ISSUE TITLE
CFNcluster compute node ssh port and MPI version

### ISSUE THREAD

**Issue by mukulagrawal78** [aws/aws-parallelcluster#1599]
Hello, 
I have been using cfncluster for sometime. I want to make 2 changes for new applications I want to run. I have a couple of questions:

1/ Does cfncluster code tries to ssh into compute nodes (not the master node)? If I steal port 22 on compute nodes for something else, would that break cfnclsuter functionality?
2/ Can you please tell me what I need to do if I want to use a different MPI library with SGE scheduler that comes pre-configured with cfncluster?
3/ Where can I find the hostname file that SGE under cfncluster automatically populates as nodes are added and deleted in the cluster?

**Comment by lukeseawalker** [comment]
Hi @mukulagrawal78,
did you consider to update to ParallelCluster, it comes with lot of new features and improvement, see [changelog](https://github.com/aws/aws-parallelcluster/releases).

> 1

The sqswatcher demon runs remote commands on compute nodes through SSH, so it's going to break if you steal that port for other purpose

>2

You can execute arbitrary code either before (pre-install) or after (post-install) the main bootstrap action during cluster creation. So you can remove/install packages or remove/add configuration with these actions, see [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html). 
If the amount of actions take a considerable amount of time to be executed, e.g installing lot of new packages, consider to prebuild an AMI with the requirements needed, see [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html).

>3

ParallelCluster doesn't modify directly the file, but uses the `qconf` command for the administrative stuff, see [here](https://github.com/aws/aws-parallelcluster-node/blob/v2.5.1/src/common/schedulers/sge_commands.py). The changes are written under the default SGE configuration file.
