### ISSUE TITLE
(not an issue) Can 'pcluster update' be used to activate ganglia post-deploy? 

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#1611]
**Environment:**
 -  aws-parallelcluster-2.5.1

Sorry for the basic question. I have a pcluster 2.5.1 grid deployed that was finnicky to set up due to external firewall controlling access to the Master ENI

However I forgot to enable ganglia when doing the last deployment, is this a setting that can be activated and used via "pcluster update ..." or am I better off just doing a clean cluster teardown and redeploy with the ganglia JSON included? Thanks!

**Comment by demartinofra** [comment]
This is not natively supported by you can follow the instructions provided here to get this working: https://github.com/aws/aws-parallelcluster/issues/1371#issuecomment-546917533

Just be aware that you also need to add the `pre_install` script described [here](https://github.com/aws/aws-parallelcluster/issues/1612) as part of the pcluster update until the issue gets fixed.

**Comment by demartinofra** [comment]
I'm going to resolve this one. Feel free to reopen if needed :)
