### ISSUE TITLE
slurmstepd: error: Unable to establish control machine address.

### ISSUE THREAD

**Issue by chandanbfx** [aws/aws-parallelcluster#1616]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [aws-parallelcluster-2.5.0]
 - OS: [ ubuntu1804]
 - Scheduler: [slurm 19.05.3-2]
 - Master instance type: [md5.xlarge]
 - Compute instance type: [md5.2xlarge]

Hi,

Most of the scheduled job failed with:
slurmstepd: error: get_exit_code task 0 died by signal: 15
slurmstepd: error: Unable to resolve "ip-172-31-95-188": Host name lookup failure
slurmstepd: error: Unable to establish control machine address. And then I need to restart all failed jobs manually. it is happening very frequently.

We are having an issue as stated above. Slurm support suggested to restart and it fixes. However, the issue persists even after restarting. Any suggestions and help very much appreciated. 

Thanks 

log and configuration file:

[sqswatcher.txt](https://github.com/aws/aws-parallelcluster/files/4111932/sqswatcher.txt)
[nodewatcher.txt](https://github.com/aws/aws-parallelcluster/files/4111933/nodewatcher.txt)
[slurm.conf.txt](https://github.com/aws/aws-parallelcluster/files/4111934/slurm.conf.txt)
[slurmd.log](https://github.com/aws/aws-parallelcluster/files/4111928/slurmd.log)
[slurmctld.log](https://github.com/aws/aws-parallelcluster/files/4111929/slurmctld.log)

**Comment by demartinofra** [comment]
Hi,

Could you please also provide the cluster configuration file and the workflow/commands used to submit the jobs?

Thanks,
Francesco

**Comment by chandanbfx** [comment]
Hi

Here is a config file: https://drive.google.com/open?id=1eGam61fD6a2tj9AEYQ8b9DT23Pl7b8v- 
And command: https://drive.google.com/open?id=10wJew5kLXUCcraO9YtVNtTMqaqXKXasS

thanks

**Comment by chandanbfx** [comment]
Hi,

Let me know if I can help you with any other log files or details.

regards
Chandan

**Comment by ddeidda** [comment]
Hi Chandan,

thanks for the additional information. We are trying to reproduce the problem. In the meanwhile, to try reducing the variables in place, could you please let us know if the problem occurs even without using canu?

**Comment by ddeidda** [comment]
Update: I could not reproduce the problem so far. 
However, I did not find the host ip-172-31-95-188 in the logs you shared. From your slurm.conf it seems it was the hostname of the master node. Was the error you reported in the output of your submitted job?

**Comment by chandanbfx** [comment]
Hi,

We don’t face these issues without canu, also we successfully ran Canu on a smaller dataset without any such issues as a test to see if it was our slurm config that was causing issues.

yes, it was the hostname of the master node. it is the same error I am facing at all 3 stages of canu. However, all of the logs files are of canu assembly stage

Here is the one of canu out file: 
[overlap.10_32.out.txt](https://github.com/aws/aws-parallelcluster/files/4132503/overlap.10_32.out.txt)

P.S: assembly command also updated in gdrive link :
https://drive.google.com/open?id=1J5gMkCAwc3Uv2TZ_IWj7JfXx1PHm-VpWuuW8bQq8cGA

Thanks 
Chandan

**Comment by ddeidda** [comment]
So, basically what is happening is that the job starts correctly and eventually you start getting the lookup failure, am I right? Could you also please share the jobwatcher log file?

**Comment by chandanbfx** [comment]
Yes, correct.

here is job watcher log file link: https://drive.google.com/open?id=1wyNA94CCN1Ybc-l1DdkIypN4J1KdHuM-

**Comment by ddeidda** [comment]
From the jobwatcher log looks like a big amount of jobs could not be run in parallel due to the reached max size of the cluster. This is normally not a problem but since you said that the problem is not occurring with smaller datasets, I am wondering if this could raise issues with Canu. 

While we'll keep investigating on our side, maybe could you try leveraging with Canu parallelization settings or increasing the max size of your Auto Scaling Group?
https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-manual-scaling.html

**Comment by chandanbfx** [comment]
Hi 

thank you so much for your suggestion. I will try auto-scaling. It will be helpful if in meanwhile you could suggest anything in addition.

**Comment by enrico-usai** [comment]
Hi @chandanbfx , 
another suggestion is to check the cloudwatch metrics of your EC2 instances (see _Monitoring_ tab after selecting the instance in the EC2 console), to understand if there are I/O or network bottleneck in the Master or in the compute instances and eventually specify another [instance type](https://aws.amazon.com/ec2/instance-types/).

In addition, if your application is writing stuff from the compute nodes into the shared EBS volume, I'd suggest to use an EFS in place of the EBS volume. See: [when to choose EFS](https://aws.amazon.com/efs/when-to-choose-efs/) and [efs section in ParallelCluster](https://docs.aws.amazon.com/parallelcluster/latest/ug/efs-section.html).

Let us know if it helps.

**Comment by chandanbfx** [comment]
Hi @enrico-usai  

we are working on this, will get back in 3-4 days.
thanks

**Comment by chandanbfx** [comment]
Hi @enrico-usai

We tried your suggestions about EFS and Auto-scaling size. We see the same issue with instances. Here is a description of our runs:

Case 1. We tried EFS performance mode general purpose along with bursting throughput mode. There were 101 jobs scheduled for processing. It worked well till 49 jobs but then it starts failing, and the job disappeared from squeue.  The specific job out file has the same error message as we previously reported.

slurmstepd: error: get_exit_code task 0 died by signal: 15
slurmstepd: error: Unable to resolve "ip-172-31-82-201": Host name lookup failure
slurmstepd: error: Unable to establish control machine address


Here are all the log and configuration files for that day run(27 Feb):
https://drive.google.com/open?id=1c0oNKsUM9PQUev-XmuR5MmuOEuNfskKM

Case 2. We tried EFS performance mode maxIO along with bursting throughput mode. This time we increased scaledown time from default 10 min to 20  min and increased the autoscaling group size from 1 to 10. All other parameters and commands remain the same.  There were again 101 jobs scheduled for processing and till 86 jobs all are finished successfully but then jobs again start failing and disappeared from squeue. specific job out file has the same error message as we above stated. 

Here are all the all and configuration files for that day ran(28 Feb):
https://drive.google.com/open?id=1Z1XJnH8QjfLtIAIlwMB5wz1LCy2jf9dX

Chandan

**Comment by chandanbfx** [comment]
Hi,

We have not heard anything from you. Could you suggest a fix to get past this issue with the parallel cluster?

regards
Chandan

**Comment by demartinofra** [comment]
Hi @chandanbfx 
sorry for the late reply. Looking into this.

**Comment by chandanbfx** [comment]
Hi @demartinofra 

Thanks! we will try as per you recommended.

**Comment by enrico-usai** [comment]
Hi @chandanbfx 
let us know if the suggestions helped you.
