### ISSUE TITLE
About Ubuntu(18.04) and schedulers 

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#1621]
Hello Aws-Parallelcluster Team,
**Environment:**
 - aws-parallelcluster-2.5.1
I was trying to use a combination of Ubuntu(18.04) and Torque, but the submitted jobs would finish and claim that there were no available slots (although that wasn't the case). I downloaded the Torque administrator guide (6.1.2) that the Aws-Parallelcluster guide cites. This document doesn't specify Ubuntu as a supported OS. I browsed around a little bit and some people mention that some Ubuntu(18.04) libraries use c++11 incompatible with some Torque components.
My questions are simply if you have any comment on this subject, and if the only schedulers compatible with Ubuntu(18.04) would be SGE and Slurm.
Thanks.

**Comment by demartinofra** [comment]
Hi,

we found an issue with Torque misbehaving when computing the number of available slots.
We pushed a patch to workaround this but it hasn't been released yet: https://github.com/aws/aws-parallelcluster-cookbook/pull/479

Could you please take a quick look at the description in the PR and see if the issue you are facing is the same?

**Comment by afernandezody** [comment]
Hi @demartinofra,
My observation from yesterday was a bit different from what your notes so I just performed further testing. My job from yesterday was marked as 'C' and the OMPI generated the following output file:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 2
slots that were requested by the application:

  /home/ubuntu/.../executable.file

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------

```
I terminated the cluster, and tried again with some minor modifications that didn't impact the outcome. Today, I submitted two jobs with the 1st one yielding the same behavior and error message as yesterday, but the 2nd stalled in the queue (see embedded picture) that sounds similar to what you reported.
![Torque_C](https://user-images.githubusercontent.com/44442767/73385852-dc344a80-429b-11ea-8707-01651a6d6fbd.png)

**Comment by demartinofra** [comment]
Could you please share cluster config and submission command/script?

**Comment by afernandezody** [comment]
The command is simply `pcluster create COGN1cluster`
_

> [aws]
> aws_region_name = us-east-1
> aws_access_key_id = 111111111111111111111
> aws_secret_access_key = 11111111111111111111111111111111
> 
> [cluster COGN1cluster]
> vpc_settings = odyvpc
> placement_group = DYNAMIC
> placement = compute
> key_name = 111111
> master_instance_type = t3.micro
> compute_instance_type = c5.large
> cluster_type = spot
> initial_queue_size = 2
> max_queue_size = 2
> maintain_initial_size = true
> scheduler = torque
> base_os = ubuntu1804
> master_root_volume_size = 25
> compute_root_volume_size = 25
> ebs_settings = custom1
> post_install = https://ody-confs.s3.amazonaws.com/11111.sh
> 
> [ebs custom1]
> shared_dir = /ODY
> volume_size = 75
> volume_type = io1
> 
> [vpc odyvpc]
> master_subnet_id = subnet-fae93cf4
> vpc_id = vpc-fd4a6587
> 
> [global]
> update_check = true
> sanity_check = true
> cluster_template = COGN1cluster
> 
> [aliases]
> ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}_

_

**Comment by enrico-usai** [comment]
Hi @afernandezody sorry for the delay and thanks for the configuration file.

Could you also please share the command you're using to submit the job in the scheduler with the list of parameters passed to the `qsub` command, in this way we can try to reproduce the issue.

Thanks

**Comment by afernandezody** [comment]
Hi @**enrico-usai**,
I was looking at my notes but it doesn't seem that I was passing along any arguments with the `qsub` command. The torque script looks like:
```
#!/bin/bash
#PBS -l nodes=2:ppn=2,walltime=100:30:00
#PBS -N JobName
#PBS -j oe
#PBS -o /home/ody/OutputFile.out
cd /home/ody
mpirun -np 4 "executable file"
```
I'm not sure how to answer your question. Most of the clusters have been configured with SGE thus far, but a more sophisticated scheduler could be beneficial moving forward. As far as Ubuntu, it has shown some benefits with some specific software (cannot go into specifics). Disclaimer: I have used RedHat and its derivatives for most of my professional life so my personal preference is not the reason here.
Thanks.

**Comment by demartinofra** [comment]
Sorry for the late reply. 

I think I have an idea on what is causing this problem:
openmpi shipped with ParallelCluster, which is the one provided by the [EFA installer](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-enable), is not built with Torque bindings/support (you could check this by running `ompi_info` and looking for `tm` as mentioned [here](https://www.open-mpi.org/faq/?category=building#build-rte-tm). 

Here are a few options:
- Build/Install your own version of OpenMPI that is built with torque support as described [here](https://www.open-mpi.org/faq/?category=building#build-rte-tm). If you need to use EFA I would discourage to build your own version of openmpi unless you know how to add the required providers.
- Use IntelMPI that gets shipped with ParallelCluster (`module load intelmpi`).
- [my personal recommendation] Switch to Slurm as scheduler, since this is being actively developed by SchedMD and it comes with a better integration with ParallelCluster scaling logic. [Here](https://slurm.schedmd.com/faq.html#torque) is some useful resources, although if your submission scripts are simple enough I would discourage using torque wrappers for Slurm and just go Slurm native.

Let me know if this helps.

**Comment by demartinofra** [comment]
you are right you just need to make sure to add `--with-ofi=/opt/amazon/efa/` when you run configure before building your version of mpi.

**Comment by afernandezody** [comment]
Yes, of course. Closing the thread (would open a new one if I ran into any issue with slurm).
