### ISSUE TITLE
Feature Request: Request for a config parameter to toggle between Compute/Cluster while disabling Hyperthreading

### ISSUE THREAD

**Issue by ganderaj** [aws/aws-parallelcluster#1627]
I  am a developer who is working with AWS Parallel Cluster specifically to run ANSYS Fluent workloads. As per ANSYS recommendations, to achieve better performance it is advised to disable hyperthreading on the Compute Nodes (where the CFD computations takes place). 

I am working with Parallel Cluster v2.5.1. It comes with a config parameter "disable_hyperthreading" which takes boolean values. Disabling hyperthreading was in-effect on the Master Node too while I was looking to disable only on the Compute Nodes. Users reported slow performance on the Master Node, since multiple users login to the Master Node simultaneously and that the number of cores were reduced to half due to disabling hyperthreading.

I request the Parallel Cluster team to come up with another config parameter which will enable the developers to choose between [Compute Nodes] or [Master & Compute Nodes] while opting to disable hyper threading. You may want to consider this requested parameter similar to existing config parameter "placement" which is used to toggle between compute/cluster when user wants to leverage "placement_groups".

**Comment by ddeidda** [comment]
Thanks for this request. It's a feature that makes perfect sense; marked as enhancement.

**Comment by enrico-usai** [comment]
We did it as part of 3.x development. See [HeadNode-DisableSimultaneousMultithreading](https://docs.aws.amazon.com/parallelcluster/latest/ug/HeadNode-v3.html#yaml-HeadNode-DisableSimultaneousMultithreading) and [ComputeResources-DisableSimultaneousMultithreading](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeResources-DisableSimultaneousMultithreading).
