### ISSUE TITLE
Add a pcluster diff command, similar to cdk diff

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1639]
This is a follow-up to a [comment](https://github.com/aws/aws-parallelcluster/pull/1583#discussion_r376062345) I made on #1583. In it, I mentioned that I would like to change the behaviour of `pcluster update` to use the `TemplateURL` provided in the configuration file rather than pass `UsePreviousTemplate=True` to the `update_stack` call.

What I would like is to be able to set that parameter through the CLI. Something like `pcluster update --use-template-url`, or whatever.

Given the risk associated with that (as far as I understand #1583, the validation extends only to changes in the parameters, not changes in the template, as it is assumed that we re-use the same template), I think it would be better if we could see the changes before actually deploying, similar to what `cdk diff` does.

The new parameter validation logic in #1583 could be reused for `pcluster diff`. If parameter validation succeeds, the command could then show:
  * a diff of the old and new parameters
  * a diff of the old and new template
  * the CFN change set associated with the update

At this point, the user could determine if running `pcluster update --use-template-url` is safe or not.

**Comment by rexcsn** [comment]
Hi,

I am labeling this as a feature request. We will take this issue into consideration during our task to improve `pcluster update`.
Thank you!

**Comment by bollig** [comment]
+1. This would be useful. Even a command to query the current config for a running cluster would help immensely. E.g., `pcluster show-config mycluster`

**Comment by enrico-usai** [comment]
I created a new issue to track the "pcluster show-config" feature: https://github.com/aws/aws-parallelcluster/issues/2700

**Comment by enrico-usai** [comment]
Pcluster update has been totally refactored for 2.x to be able to show a complete list of changes: https://docs.aws.amazon.com/parallelcluster/latest/ug/using-pcluster-update.html


The same is true for Pcluster 3.x: https://docs.aws.amazon.com/parallelcluster/latest/ug/using-pcluster-update-cluster-v3.html and we also added the `--dryrun` option to the `update-cluster` command.
