### ISSUE TITLE
Support S3 URI for custom_chef_cookbook

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1640]
**Environment:**
 - aws-parallelcluster-2.5.1

I use a `custom_chef_cookbook` to configure my nodes. However, my organization would like to disallow objects with `public-read` ACLs in S3 buckets. Would it be possible to support S3 URIs for the `custom_chef_cookbook` field?

In the past, I've used presigned URLs to fix that issue with the custom template URL and the additional stack, but the Chef cookbook must be accessible at all times, since new compute nodes are constantly being instantiated.

The only downside I can see is that validation will be a more complicated, as `pcluster` will have to make sure that the MasterServer and the ComputeFleet has read access to the S3 object.

**Comment by rexcsn** [comment]
Hi,

Thank you for opening this issue, marking this as a feature request.
