### ISSUE TITLE
Upgrade: Need parameter to attach say a 1Tb SSD to compute nodes.

### ISSUE THREAD

**Issue by eewolfe** [aws/aws-parallelcluster#1649]
Upgrade:

We have the need to say 1Tb of SSD ( or other) scratch space mounted to the compute nodes. Our tools like the fast access of local scratch disk, and it would be great to have a parameter for this, or another similar option. Ephemeral is OK.

**Comment by rexcsn** [comment]
Hi,

There are specific instance types with ephemeral scratch disk, the complete list is here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html

I created my cluster with `compute_instance_type = c5d.12xlarge` and I can see that the scratch disk is present:
```
ubuntu@ip-172-31-20-171:~$ lsblk
NAME                   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0                    7:0    0  89.1M  1 loop /snap/core/8039
loop1                    7:1    0    18M  1 loop /snap/amazon-ssm-agent/1480
loop2                    7:2    0  91.3M  1 loop /snap/core/8592
nvme0n1                259:0    0 838.2G  0 disk 
└─nvme0n1p1            259:6    0 838.2G  0 part 
  └─vg.01-lv_ephemeral 253:0    0   1.7T  0 lvm  /scratch
nvme1n1                259:1    0 838.2G  0 disk 
└─nvme1n1p1            259:5    0 838.2G  0 part 
  └─vg.01-lv_ephemeral 253:0    0   1.7T  0 lvm  /scratch
nvme2n1                259:2    0    30G  0 disk 
└─nvme2n1p1            259:3    0    30G  0 part /
```

Please let me know if this helps.
