### ISSUE TITLE
Failures in jobwatcher with SGE and parallelcluster 2.5.X

### ISSUE THREAD

**Issue by sanman-99** [aws/aws-parallelcluster#1652]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: 2.5.0 and 2.5.1
 - OS: Centos7
 - Scheduler: SGE
 - Master instance type: i3en.large
 - Compute instance type: r5.2xlarge

**Bug description and how to reproduce:**
We are seeing the following error when using SGE and 2.5.0 and 2.5.1 parallelcluster software.  This happens and continues immediately upon deployment.  This prevents new nodes from being spun up when their are jobs sitting in queue wait.  

`2020-02-17 13:43:52,157 ERROR [jobwatcher:main] An unexpected error occurred: cannot import name 'SGE_DISABLED_STATE'
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/jobwatcher/jobwatcher.py", line 154, in main
    scheduler_module = load_module("jobwatcher.plugins." + config.scheduler)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/common/utils.py", line 45, in load_module
    __import__(module)
  File "/root/.pyenv/versions/3.6.9/envs/node_virtualenv/lib/python3.6/site-packages/jobwatcher/plugins/sge.py", line 13, in <module>
    from common.schedulers.sge_commands import (
ImportError: cannot import name 'SGE_DISABLED_STATE'`

**Additional context:**
The zip file contains:
 - configuration file for deployment.
 - /var/log/jobwatcher, and /var/log/sqswatcher logs

[jobwatchererror.zip](https://github.com/aws/aws-parallelcluster/files/4215656/jobwatchererror.zip)

**Comment by enrico-usai** [comment]
Hi @sanman-99 
from the error I'd say the python virtual environment used by the parallelcluster-node is broken.

It could happen when the post-install script add some custom python packages or changes the PATH.
Can you share the content of your post-install script and/or re-try without using it?

Let us know if it helps.

**Comment by sanman-99** [comment]
Here is a copy of my postinstall script.  I will also test it without a post-install.

`#!/bin/bash
groupadd -g 33264 galaxy
efsmnt=/efs/galprod
ephmnt=/data
mnt=/nfs
mkdir -p $mnt
mkdir -p $efsmnt
mkdir -p $ephmnt
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-ffe277b6.efs.us-east-1.amazonaws.com:/ $mnt
mount -t nfs -o rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 172.32.4.222:/nfs/home /$mnt/home
mount -t nfs -o noacl,nocto,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 172.32.8.252:/data /$ephmnt
yum install -y sssd realmd pcre2
cp /nfs/sw/configs/sssd.conf /etc/sssd/sssd.conf
service sssd start
mv /etc/sysconfig/clock /etc/sysconfig/clock.orig
cp /nfs/sw/configs/clock /etc/sysconfig/.
ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
#install required R packages for lefse
Rscript -e 'install.packages("modeltools", repos="https://cran.rstudio.com")'
Rscript -e 'install.packages("coin", repos="https://cran.rstudio.com")'
Rscript -e 'install.packages("mvtnorm", repos="https://cran.rstudio.com")'
#legacy ssl required for some tools RGI and samtools
#legacy ssl required for some tools RGI and samtools
cp /usr/lib64/libssl.so.1.0.2k /usr/lib64/libssl.so.1.0.2k.backup
ln -sf /usr/lib64/libssl.so.1.0.2k /usr/lib64/libssl.so.1.0.0
cp /usr/lib64/libcrypto.so.1.0.2k /usr/lib64/libcrypto.so.1.0.2k.backup
ln -sf /usr/lib64/libcrypto.so.1.0.2k /usr/lib64/libcrypto.so.1.0.0
`

**Comment by sanman-99** [comment]
After further investigation looks like I was using another postinstall for the initial deployment that was causing the issue.

**Comment by enrico-usai** [comment]
Hi @sanman-99 
thanks for sharing and closing the issue.
