### ISSUE TITLE
Policies Required for t2.micro running Parallel Cluster

### ISSUE THREAD

**Issue by eewolfe** [aws/aws-parallelcluster#1668]
Hello APC,

I provisions a t2.micro running AWS OS, and have installed Parallel Cluster. Is there an example policy this instance requires to run pcluster to create HPCs so that I do not have to pass in credentials and run aws configure? Would this be some update to AWS docs?

-- Gene.

**Comment by lukeseawalker** [comment]
Hi @eewolfe,
you can setup a role for the instance with the ParallelCluster user policy described here https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html#parallelclusteruserpolicy

L

**Comment by eewolfe** [comment]
The docs are pretty good at explaining what is required.

**Comment by demartinofra** [comment]
Closing. Feel free to reopen if needed!
