### ISSUE TITLE
Unable to change master_root_volume_size on CentOS 6 cluster

### ISSUE THREAD

**Issue by nick-phillips** [aws/aws-parallelcluster#1688]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.6.0
 - Configuration file:

```
[cluster dev-cluster]
key_name = <REMOVED>
base_os = centos6
master_instance_type = m4.4xlarge
compute_instance_type = m4.4xlarge
vpc_settings = <REMOVED>
efs_settings = dev-pipeline-efs
extra_json = {"cluster": {"ganglia_enabled":"yes"}}
master_root_volume_size = 250
compute_root_volume_size = 50
initial_queue_size = 1
max_queue_size = 10
s3_read_write_resource = <REMOVED>
post_install = <REMOVED>
```

**Bug description and how to reproduce:**

I created a CentOS 6 cluster with master_root_volume_size = 250. Cluster creation finishes successfully, but when I connect to the master node, I see via `df` that the filesystem is only 30G. Running `lsblk` shows a 250G partition available, however, running `resize2fs <device>` results in the following error:

``` 
Filesystem at /dev/xvda1 is mounted on /; on-line resizing required
old desc_blocks = 2, new_desc_blocks = 16
Performing an on-line resize of /dev/xvda1 to 65534903 (4k) blocks.
resize2fs: Operation not permitted While trying to add group #243
```

`dmesg` shows the following: `EXT4-fs warning (device xvda1): ext4_group_add:1605: No reserved GDT blocks, can't resize`. 

I'm currently trying to figure out how to get ParallelCluster to create a file system of the desired size on startup, or resize during the post_install script. This issue is currently blocking our ability to scale up using ParallelCluster, any help resolving it would be much appreciated! Thanks

**Comment by ddeidda** [comment]
Hi Nick. This is a known issue with CentOS6 which is unfortunately is currently still open. Would switching to CentOS7 be an acceptable option for you?

**Comment by nick-phillips** [comment]
Hi @ddeidda, 

Thanks for the help. Unfortunately for my use case I can't update to Centos 7, so I will try working with an additional EBS volume.

**Comment by rexcsn** [comment]
Hi Nick, closing this issue, feel free to re-open if you still have open question. Thanks!
