### ISSUE TITLE
Q: Backwards compatibility in parallelcluster versions & custom AMIs?

### ISSUE THREAD

**Issue by briandobbins** [aws/aws-parallelcluster#1689]
Hi all,

  I could dig through the code and answer this, but thought I'd ask and save some work.  I have a custom AMI that was based off parallel cluster 2.5.0, and I'm wondering if I launch with 2.6.0 (eg, the system on which I run 'pcluster create' is at 2.6) if I should expect issues?  Or will the newer release simply overwrite the older packages from the 2.5.0 install?  I understand that could slow down node booting due to needing to update things, but are there other gotchas?

  Obviously I can just install the 2.5.0 version on the launching system to work around this, too.

  Thanks,
  - Brian

**Comment by ddeidda** [comment]
Hi.

Unfortunately a custom AMI cannot be upgraded in this way. ParallelCluster does not upgrade existing software during nodes booting.
As specified in the user guide:"After you build your own AMI, you no longer receive updates or bug fixes with future releases of AWS ParallelCluster. Also, you must repeat the steps used to create your custom AMI with each new AWS ParallelCluster release."

https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html

**Comment by rexcsn** [comment]
Hi Brian, I am closing this issue now, feel free to re-open if you still have open question. Thanks!
