### ISSUE TITLE
Stack error (PMPI_Init)

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#1695]
Hello Aws-Parallelcluster Team,
Yesterday I ran into some totally unexpected error with the stack. This is just my speculation but I might have hit a limit -in regards to the number of MPI ranks or instances- with the Intel compiler configuration triggering some unexpected reaction. Here is the story, I have been progessively increasing the number of instances and everything was working great. However, when turning the hyperthreading on for 125 instances (c5n.18xlarge), the first error appeared and the cluster became essentially useless. I thought: well maybe the problem has been caused by the hyperthreading itself. The next step was to deploy a clusters with 250 instances but the 1st job again caused a bunch of errors (and the cluster was no good for much else). The error reads:
```
/opt/intel/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpirun: 74: [: intel64: unexpected operator
Abort(1091471) on node 185 (rank 185 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(703)........: 
MPID_Init(958)...............: 
MPIDI_OFI_mpi_init_hook(1382): OFI get address vector map failed
Abort(1091471) on node 192 (rank 192 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(703)........: 
MPID_Init(958)...............: 
MPIDI_OFI_mpi_init_hook(1382): OFI get address vector map failed
Abort(1091471) on node 540 (rank 540 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(703)........: 
MPID_Init(958)...............: 
MPIDI_OFI_mpi_init_hook(1382): OFI get address vector map failed
Abort(1091471) on node 57 (rank 57 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(703)........: 
MPID_Init(958)...............: 
MPIDI_OFI_mpi_init_hook(1382): OFI get address vector map failed
Abort(1091471) on node 91 (rank 91 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
...
ABOUT 100 SIMILAR OUTPUT ERRORS (shortened for better readability)
...
MPIR_Init_thread(703)........: 
MPID_Init(958)...............: 
MPIDI_OFI_mpi_init_hook(1382): OFI get address vector map failed
Abort(1091471) on node 8526 (rank 8526 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(703)........: 
MPID_Init(958)...............: 
MPIDI_OFI_mpi_init_hook(1382): OFI get address vector map failed
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:532): downstream from host ip-172-31-6-192.ec2.internal was killed by signal 13 (Broken pipe)
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-14-245.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-12-149.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-11-61.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-7-7.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-8-41.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-4-22.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-3-113.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-6-160.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-1-226.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-4-39.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-7-145.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-6-243.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-14-191.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-15-202.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] wait_proxies_to_terminate (../../../../../src/pm/i_hydra/mpiexec/intel/i_mpiexec.c:528): downstream from host ip-172-31-11-101.ec2.internal exited with status 141
[mpiexec@ip-172-31-6-192] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:2084): assert (exitcodes != NULL) failed
```
All of this is, of course, with the Intel module loaded. I was able to find a reference to a similar error in the Intel MPI library Linux OS developer guide update 6 (not attaching the document itself but will do if requested) on page 32. My interpretation is that there is some limit here but you probably have a better idea of what went wrong or if any other customer has faced similar issues.
Thanks a lot.

**Comment by rexcsn** [comment]
Hi @afernandezody ,

Thank you for opening this issue.

To get started, could you provide the pcluster config and version that you used to launch the cluster so we can see which features are enabled for your cluster?

**Comment by afernandezody** [comment]
Hi @**rexcsn**, 
It's 2.6.0. This config file isn't particularly sophisticated:
```
[aws]
aws_region_name = us-east-1
aws_access_key_id = 
aws_secret_access_key = 

[cluster c1cluster]
vpc_settings = ******
placement_group = DYNAMIC
placement = compute
key_name = ******
master_instance_type = t3.micro
compute_instance_type = c5n.18xlarge
cluster_type = spot
enable_efa = compute
initial_queue_size = 250
max_queue_size = 250
maintain_initial_size = true
scheduler = sge
base_os = ubuntu1804
custom_ami = ***
master_root_volume_size = ***
compute_root_volume_size = ***

[vpc odyvpc]
master_subnet_id = 
vpc_id = 

[global]
update_check = true
sanity_check = true
cluster_template = c1cluster

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```
Thanks

**Comment by enrico-usai** [comment]
Hi @afernandezody 

thanks for the configuration and sorry for the delay.

Some questions: 
1. How are you disabling hyperthreading? I don't see the [disable_hyperthreading](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#disable-hyperthreading) option in your configuration file.
1. You said you're increasing the number of instances. Are you creating a new cluster for each new test or are you executing an update in the existing cluster?
1. Are the job performing high I/O or network traffic? I'm asking because I see you're using a t3.micro as master instance and the shared volume is exported by the master instance so it could be a bottleneck. You could double check the master instance usage charts.

It could be helpful to take a look at our [best practice](https://github.com/aws/aws-parallelcluster/wiki/Best-Practices) wiki page to align your cluster configuration to the characteristics of your job.

In any case this issue seems very "MPI" specific.
Could you please provide us more details on the job you're running, the steps you're doing to run  it (load module, etc) to have enough information to try reproduce it.

Thanks

**Comment by afernandezody** [comment]
Hi @**enrico-usai**,
My answers:
1 - The error happened for both situations with and without hyperthreading when running a job with 9,000 MPI ranks; this would be 4,500 cores (125 instances) when hyperthreading and 9,000 cores (250 instances) without hyperthreading.
2 - All clusters are created from scratch (after the previous one is completely terminated to avoid any issue from any remnant).
3 - For these particular clusters and the tests that I was performing, I/O was minimal.
I agree that this is related to MPI, and more specifically to the Intel MPI implemented in aws-parallelcluster. My interpretation of what happened is that the MPI wrapper was simply not able to handle so many MPI ranks (my first thought was that hyperthreading had caused the error until I decided to perform another test without hyperthreading; it cannot be a coincidence that the errors were the same once you surpass a number of ranks whether hyperthreading is active). My suggestion (which you are obviously not obliged to follow) would be to talk to your Intel technical person and ask if there is any limit associated with the Intel MPI version that they are providing.  
I cannot provide much detail about the jobs (because of IP concerns) but, in order to reproduce the error, would suggest to choose some app using intensive MPI communications, load the intel module, and increase the size of the jobs to check if they break (my breaking point was 9,000 ranks but I didn't try to pinpoint the exact figure, which might or might not fluctuate with different apps and the level of communications).
Thanks.

**Comment by enrico-usai** [comment]
Hi @afernandezody 

yes, I already pinged our internal MPI experts to analyze your issue before asking you more information. They'll follow it up.
Thanks for the additional information, they can be useful to try to replicate the job.

Thanks

**Comment by demartinofra** [comment]
We have been able to reproduce the error in Intel MPI U6. We have also confirmed that the issue is fixed when using Intel MPI U7 due to an update in the Libfabric provider distributed with it.

Next ParallelCluster version is going to be shipped with intelMPI U7 to address this issue. In the meanwhile here is how you can build a cluster with IntelMPI U7 installed:

Fastest option but probably the least efficient is to create a new cluster with the following config option:

```
extra_json = { "cluster" : { "skip_install_recipes" : "no", "intelmpi" : {"url": "https://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16546/l_mpi_2019.7.217.tgz", "version": "2019.7.217"} } }
```

This triggers the installation of intelmpi U7 at runtime on all nodes, meaning each compute node will spend additional 2 minutes to be launched.

Alternatively you could build a post install script that runs the following instructions on all nodes:
```
cat /etc/chef/dna.json | jq '.cfncluster = .cfncluster +  { "intelmpi" : {"url": "https://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16546/l_mpi_2019.7.217.tgz", "version": "2019.7.217"} }' > /tmp/dna.json && mv -f /tmp/dna.json /etc/chef/dna.json && cd /etc/chef && chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json --override-runlist aws-parallelcluster::intel_mpi
```

This installs intelmpi U7 on the MasterNode only and shares the binaries over NFS to the rest of the cluster. Compute nodes will only run instructions to create the modulefile, so boot time won't be affected.

In both cases you will be able to use intel U7 by loading its module:
```
module load intelmpi/2019.7.217
```

Please let us know if you need further guidance in creating a post_install script or patching the existing cluster.

**Comment by afernandezody** [comment]
Hi @**demartinofra**, 
Thanks. I'm swamped so it might have to wait a couple of weeks until I can try those solutions out. By the next version, I guess that you mean v2.6.2 (or maybe 2.7). 
Anyway, I'm closing the ticket for now ( would only reopen it if none of the solutions work out). 
Best.
