### ISSUE TITLE
Cannot easily use NiceDCV if only connection is via ssh on port 22

### ISSUE THREAD

**Issue by PhilipMorrisJones** [aws/aws-parallelcluster#1716]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.6.0]

dcv_settings = hpc-dcv

[dcv hpc-dcv]
enable = master

**Bug description and how to reproduce:**

We only have access via ssh so everything has to be tunnelled via port 22.

To get NiceDCV to work I have to do this:

I have a script on the cluster that runs `pcluster_dcv_connect.sh` and parses the output to form a connection string that is a URL for localhost so I can then use an ssh tunnel to connect through that.

If I run the standard connect

```
$ pcluster dcv connect -s pmjmon30-01
Please use the following one-time URL in your browser within 30 seconds:
https://52.71.41.236:8443?authToken=n2D_WcBJdEOCbS9gv737KfoZpfZMI7h1OAzrKNmtu_eouwkKDuK4UR0ApEg_xVfSN_RQebhr6ndW-hTmzQDe4s05pGnhJBhzOSv5oPhroFmT2vrC5sv_TaLo0H7ZnQs-TkHQnANgmd7StyNLI9AN08U3sLMQ-W8t9bvJPiOgadDsz_AOdFMdE6oY4Q4-hYrxMppvwLAhvJTYzoYTT51rC7z6PEujXjSl0okHKtOUs7rNm4kSm0yf53nleHwGOtCw#Hj6Avm86itfs8BaCAu0r
```

I get a URL that does not work. Instead, I have to run a script such as below 

```
#!/bin/bash
dcvstr=`/opt/parallelcluster/scripts/pcluster_dcv_connect.sh /tmp`
dcvarr=($dcvstr)
pattern=\*\=
port=${dcvarr[0]#$pattern}
sess=${dcvarr[1]#$pattern}
auth=${dcvarr[2]#$pattern}
echo "https://localhost:"$port"?authToken="$auth"#"$sess
```
which outputs
```
https://localhost:8443?authToken=UuD-XC8li-8VcYRm1TFcRwgDlAIeFNPFo5y95A1BzPzjqyr1W2YIpxqhYic2clWhMv2V1lvzDa9ahUAgSzXNW7euRGf4RjdwyluveyMVzEP4-FVqBUgELe4oIE-0VhGAkZsmxpPt2zJhn3dPhEv21Uxi_6-KCUEzRAQ7a8RBw42uofQWE0u31AKjOZMW-5s5bhpUhG33XYMeEYEYNVWb0XEORFYwUnu4_Yul4UESE70Bg2nlhlfvQdabYaWePk1T#Hj6Avm86itfs8BaCAu0r
```

It would be good to add this sort of option to the pcluster script so e.g.

`pcluser dcv connect -show-url --local-url ...`

**Comment by demartinofra** [comment]
Hi Philip,

thanks for opening this feature request.

As an alternative, instead of replacing the actual master ip with localhost you could modify the /etc/hosts file so that the public IP of the master gets resolved to localhost.

**Comment by enrico-usai** [comment]
Hi @PhilipMorrisJones, while this request remains valid, it is not a feature we are able to prioritize at this time within our roadmap. We are continuing to work closely with the DCV team within AWS so that we can evolve our integration to cover a wider variety of use cases and enhancements. Thanks
