### ISSUE TITLE
more info / Chef recipe about what is include in various AMI's (GPU drivers, etc)

### ISSUE THREAD

**Issue by habemus-papadum** [aws/aws-parallelcluster#1730]
**Bug description and how to reproduce:**
There is no easy way to know if the bundled AMI's contain cuda drivers, and which version, as well as other software.  Is there some chef recipe that I can refer to that describes how each AMI (alinux, alinux2, etc) is built

Thanks!

**Comment by enrico-usai** [comment]
Hi @habemus-papadum 
in the [aws-parallelcluster-cookbook- default.rb](https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.6.1/attributes/default.rb#L69) file you can see the version of the software associated with the released with the 2.6.1.

You can use the *Tag* selector to switch between ParallelCluster versions and verify the software installed within that specific release.

Another way to retrieve this information is by checking the [changelog](https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.rst) or the [releases](https://github.com/aws/aws-parallelcluster/releases) page.

Let us know if it helps.

**Comment by habemus-papadum** [comment]
Brilliant! Thank you.
