### ISSUE TITLE
pcluster configure failed

### ISSUE THREAD

**Issue by duanjingqi** [aws/aws-parallelcluster#1734]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: 2.6.1
 - OS: alinux
 - Scheduler: slurm
 - Master instance type: t2.micro
 - Compute instance type: t2.micro

**Bug description and how to reproduce:**
pcluster configure failed with following message: 

_Creating CloudFormation stack...
Do not leave the terminal until the process has finished
Stack Name: parallelclusternetworking-pubpriv-20200412205701
Status: parallelclusternetworking-pubpriv-20200412205701 - CREATEStatus: parallelclusternetworking-pubpriv-20200412205701 - ROLLBACK_IN_PROGRESS
Cluster creation failed.  Failed events:
  - AWS::EC2::Subnet Private Resource creation cancelled
  - AWS::EC2::Subnet Public Resource creation cancelled
  - AWS::EC2::RouteTable RouteTablePrivate Resource creation cancelled
  - AWS::EC2::EIP NatEIPPublic The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceeded; Request ID: 4eab21b1-72d3-43af-ba83-aa3a479414a4)
Could not create the network configuration_

**Comment by enrico-usai** [comment]
Hi @duanjingqi 

The `AddressLimitExceeded` means you're reaching the limit of the number of Elastic IP you can instantiate on your account (by default the limit is 5).

You can check if you have **detached**  [Elastic IPs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html) on your [EC2 console](https://console.aws.amazon.com/ec2/) and delete them or request for [a limit increase](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html).

Let us know if it helps.

**Comment by duanjingqi** [comment]
thanks. problem solved after clean up the unused EIPs. 

Jingqi
