### ISSUE TITLE
Feature request: support multiple EFS mounts

### ISSUE THREAD

**Issue by rakarnik** [aws/aws-parallelcluster#1735]
AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.6.0]

Is there a possibility that parallel cluster could mount multiple EFS instances? I am currently using a single large EFS instance (mounted at /work) and smaller EBS images (mounted at /home, /software, etc.). This arrangement works fine for the most part, unless I change a configuration file in my user directory or install new software, at which point I have to update the EBS images.

Are there design considerations that prevent the use of multiple EFS mounts?

**Comment by demartinofra** [comment]
Hi Rahul,

thanks for opening this feature request. I think your use case makes sense and there are no design considerations that prevent ParallelCluster to support multiple EFS volumes. We are going to take this into account while evolving the roadmap of the product.

If you are blocked by this the only way to have multiple EFS volumes in the current version of ParallelCluster is to implement some custom post_install script that does that for your. Let us know if you need further guidance in doing that.

**Comment by rakarnik** [comment]
Thanks @demartinofra! I will go the post-install script route for now.

**Comment by gregjohnso** [comment]
Expanding this to FSx mounts as well would also be great.

**Comment by MikeKroell** [comment]
+1 for multiple NFS in the config file.

**Comment by demartinofra** [comment]
@MikeKroell just to confirm you would like multiple EFS right? Because support for multiple NFS is already available.

**Comment by andrei-xdlab** [comment]
+ 1 for multiple EFS and FSx filesystems in the same cluster. 

We need to deploy different types of EFS + backup to support various workloads and also FSx scratch space in the same environment. Currently, pcluster create fails to deploy both, EFS and FSx in the same cluster.

[efs customefs1]
shared_dir = /home
efs_fs_id = fs-xxx

[efs customefs2]
shared_dir = /apps
efs_fs_id = fs-xxx

[fsx customfsx]
shared_dir = /scratch
fsx_fs_id = fs-xxx

**Comment by MikeKroell** [comment]
> @MikeKroell just to confirm you would like multiple EFS right? Because support for multiple NFS is already available.

Yes, we need support for multiple EFS, it seems we found mount EFS with the NFS configuration options.

**Comment by enrico-usai** [comment]
This feature is under develop: https://github.com/aws/aws-parallelcluster/pull/3947

**Comment by gmarciani** [comment]
Support for multiple EFS included in [ParallelCluster 3.2.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.2.0)
