### ISSUE TITLE
Use awssub from outside of master node (e.g. laptop)?

### ISSUE THREAD

**Issue by habemus-papadum** [aws/aws-parallelcluster#1737]
When using AWS Batch, is there a supported workflow for launch jobs from a machine other than the master node?  (Sorry if this obvious, I am new)  thanks, nehal

**Comment by demartinofra** [comment]
Yes all awsb* commands work outside of the master node. 

Just make sure you [install pcluster cli](https://docs.aws.amazon.com/parallelcluster/latest/ug/install.html), you [configure the AWS credentials](https://docs.aws.amazon.com/parallelcluster/latest/ug/getting-started-configuring-parallelcluster.html) and you use the `-c CLUSTER, --cluster CLUSTER` option when submitting any of the awsb* commands.

**Comment by AureliusTech** [comment]
thank you.  nehal

**Comment by habemus-papadum** [comment]
thanks!
