### ISSUE TITLE
Potential pagination/iterator boto3 error for sqswatcher.py  in accounts with massive dynamodb usage

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#1740]
**Environment:**
 - AWS ParallelCluster

**Bug description and how to reproduce:**

This is more of a "are we on the right track debugging this issue?" guidance request until I can get back into this AWS environment to verify but we are starting to suspect we have a Parallecluster deploy issue caused by the fact that our aws account has so many DynamoDB tables in use that the basic boto3 table query in sqswatcher.py is returning null when in fact the parallelcluster created dynamoDB table exists. 

I think I've found at least one other "boto3 needs to iterate over this query" issue in the past so this is the first thing that pops in my mind with our current problem. 

**Additional context:**

This is the relevent section of sqswatcher.py from the Github project for "aws-parallelcluster-node":

```
def _get_ddb_table(region, table_name, proxy_config):
    """
    Get DynamoDB table by name.

    :param region: AWS region
    :param table_name: Table name to search for
    :param proxy_config: proxy configuration
    :return: the Table object
    """
    log.debug("Getting DynamoDB table '%s'", table_name)
    ddb_client = boto3.client("dynamodb", region_name=region, config=proxy_config)
    try:
        # Check that table exists
        ddb_client.describe_table(TableName=table_name)

        ddb_resource = boto3.resource("dynamodb", region_name=region, config=proxy_config)
        table = ddb_resource.Table(table_name)
        log.debug("DynamoDB table found correctly.")
    except ClientError as e:
        log.critical("Unable to get the DynamoDB table '%s'. Failed with exception: %s", table_name, e)
        raise

    return table
```

My boto3 lack of experience is showing here but I think that query for the DynamoDB table name is not set up to iterate/paginate over a potentially vast number of return results? 

If this is accurate I'd be happy to chase this down further. I suspect but am not 100% sure that our current "nodes can't join cluster" problem is because the query above is returning empty despite the table actually being present.  A sysadmin at my client modified that code to print the list of table names returned and the table we wanted was NOT in the returned list despite existing. 

Thanks!

**Comment by ddeidda** [comment]
Hi Chris.
There was actually a pagination problem in that portion of code, which had been addressed by this commit in November last year:

https://github.com/aws/aws-parallelcluster-node/commit/fe677e4e162949711c49cdb9579a4f5c2b7e88e1

Is your client using a cluster created with a recent (>= 2.5) version of ParallelCluster?

**Comment by rexcsn** [comment]
Hi Chris,

Judging by the code excerpt you provided, looks like you are already using pcluster >=2.6.0, for which we already addressed an old pagination issue.

Methods in our current implementation such as `ddb_client.describe_table(TableName=table_name)` should not suffer from pagination issue, so I would suggest looking elsewhere if you are still debugging problems for your cluster.

Please let us know if you have further question, thanks!
