### ISSUE TITLE
PCluster fleet launch failure with Torque

### ISSUE THREAD

**Issue by CharlesEGrant** [aws/aws-parallelcluster#1742]
**Environment:**
aws-parallelcluster-2.4.0 and aws-parallelcluster-2.4.1  #############################################
#############################################

[global]
#cluster_template = test-meme-cluster
sanity_check = true

#############################################
#############################################
[aws]
# This is the AWS credentials section (required).
# These settings apply to all clusters
# replace these with your AWS keys
aws_region_name = us-west-2

################################
################################

[cluster test-meme-cluster]
key_name = meme-suite-uswest-2 
initial_queue_size = 1 
max_queue_size = 4
maintain_initial_size = true
scheduler = torque
cluster_type = spot
spot_price = 0.05
# Modified Ubuntu 16.04
custom_ami = ami-0572a6ec3824c764e
compute_instance_type = m5.large 
master_instance_type = m5.large
ebs_settings = testuser, testdata
vpc_settings = meme-suite
base_os = ubuntu1604
#post_install = https://meme-suite-custom-bootstrap.s3-us-west-2.amazonaws.com/meme-suite-cluster-config.sh

[cluster primary-meme-cluster]
key_name = meme-suite-uswest-2 
initial_queue_size = 1 
max_queue_size = 7
maintain_initial_size = true
scheduler = torque
cluster_type = spot
spot_price = 0.05
# Modified Ubuntu 16.04
custom_ami = ami-0572a6ec3824c764e
compute_instance_type = m5.large 
master_instance_type = m5.large
ebs_settings = primaryuser, primarydata
vpc_settings = meme-suite
base_os = ubuntu1604
#post_install = https://meme-suite-custom-bootstrap.s3-us-west-2.amazonaws.com/meme-suite-cluster-config.sh

[vpc meme-suite]
vpc_id = vpc-fdbca39f
master_subnet_id = subnet-6a44612c

[ebs testdata]
ebs_volume_id = vol-0fb32e70e5d029f59
shared_dir = /home/meme-data

[ebs primarydata]
ebs_volume_id = vol-0d21dcf853fbf4d05
shared_dir = /home/meme-data

[ebs testuser]
ebs_volume_id = vol-0cf0dc28ead15983d
shared_dir = /home/meme
volume_type = standard
volume_size = 400

[ebs primaryuser]
ebs_volume_id = vol-05812a41028831261
shared_dir = /home/meme

.

**Bug description and how to reproduce:**
We've been using pcluster 2.4.0 and 2.4.1 with Torque and this configuration file for months without problem. Yesterday (2020-04-21) we began seeing a problem where jobs were piling up in the Torque queue but never being run. Our autoscaling group had launched the maximum allowed number of compute instances. Looking at /var/spool/torque/server_log and /var/spool/torque/server_priv/nodes is look like though compute instances were being spun up, they were never being added to /var/spool/torque/server_priv/nodes

I deleted that instance of the cluster and I've repeatedly tried to relaunch a new instance, using the command

`pcluster create -c meme-web-aws-pcluster-config -t test-meme-cluster test-meme-cluster
`
This would almost always fail, with the error message

Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-test-meme-cluster The following resource(s) failed to create: [MasterServerWaitCondition, ComputeFleet].
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Resource creation cancelled
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Failed to receive 1 resource signal(s) within the specified duration

but actually worked once or twice. When I looked at the Torque logs on the master, the issue was always the same as the initial problem: the compute node was not being added to the server_priv/nodes file, so communication couldn't be established between the master and the compute node.

**Additional context:**

Any other context about the problem. E.g.:

No cloudwatcher or sqs logs found. It looks like there was a script failure in cloud-init.log

2020-04-23 03:48:56,073 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance

[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/4520381/cloud-init-output.log)

[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/4520382/cloud-init.log)

**Comment by ddeidda** [comment]
Hi Charles.

From the logs you shared seems like you are using an ami backed with ParallelCluster 2.4.0 to create a cluster with ParallelCluster 2.4.1. 

As reported in our user guide: 

"After you build your own AMI, you no longer receive updates or bug fixes with future releases of AWS ParallelCluster. Also, you must repeat the steps used to create your custom AMI with each new AWS ParallelCluster release. "

To solve the issue you could either build a new AMI with the version of ParallelCluster you want to use (latest one is currently 2.6.1) by following the steps in this tutorial: 
https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html 

or re-install parallelcluster 2.4.0 by launching the following command:

```
pip install aws-parallelcluster==2.4.0
```
If you are working with different version of ParallelCluster in the same machine you run the above command inside a virtual environment as described here:

https://docs.aws.amazon.com/parallelcluster/latest/ug/install-virtualenv.html

Hope it helps.

**Comment by CharlesEGrant** [comment]
I thought I had tried using both versions 2.4.0 and 2.4.1 with similar failures. However the situation may have been confused because we were also get failures to purchase spot instances of m5.large instances in us-west-2.  At any our configuration seems to be working now with pcluster 2.4.0 and using m5n.large instances. Thanks for your quick assistance!
