### ISSUE TITLE
pcluster createami should point out that Berks is missing

### ISSUE THREAD

**Issue by brainstorm** [aws/aws-parallelcluster#1745]
When the local ChefDK installation is not properly setup (i.e when a user installs chefdk via Homebrew `rbenv-chefdk` formula), the following happens:

```
$ pcluster createami --ami-id ami-09226b689a5d43824 --os alinux2 --config conf/config --region ap-southeast-2 --cluster-template tothill
Building AWS ParallelCluster AMI. This could take a while...
Base AMI ID: ami-09226b689a5d43824
Base AMI OS: alinux2
Instance Type: t2.xlarge
Region: ap-southeast-2
VPC ID: vpc-7d2b2e1a
Subnet ID: subnet-3ad03d5c
Template: https://s3.ap-southeast-2.amazonaws.com/ap-southeast-2-aws-parallelcluster/templates/aws-parallelcluster-2.6.1.cfn.json
Cookbook: https://s3.ap-southeast-2.amazonaws.com/ap-southeast-2-aws-parallelcluster/cookbooks/aws-parallelcluster-cookbook-2.6.1.tgz
Packer log: /var/folders/wz/__dd9trs0kl4jb3rs83704y80000gn/T/packer.log.20200427-144543.zn8dxbyo
Packer status: 	exit code 1

No custom AMI created
```

It makes it seem **as if there was some sort of packer issue**, when in reality it's **`berks`/chefdk at fault**... the error message should point (earlier?) that `Berks` is missing, not Packer.

**Environment:**
 - OSX Catalina
 - aws-parallelcluster-2.6.1
 - parallelcluster config: https://github.com/umccr/infrastructure/blob/master/parallel_cluster/conf/config

/cc @reisingerf

**Comment by ddeidda** [comment]
Thank you for reporting this. I marked it as enhancement in our backlog.

**Comment by lukeseawalker** [comment]
Closing this because Berkshelf has been removed from the client requirements since version 2.8.0.
Reference https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.rst#280

**Comment by brainstorm** [comment]
Great!
