### ISSUE TITLE
EBS volumes not removed on pcluster termination by default?

### ISSUE THREAD

**Issue by brainstorm** [aws/aws-parallelcluster#1750]
**Environment:**
 - aws-parallelcluster-2.6.1
 - https://github.com/umccr/infrastructure/blob/master/parallel_cluster/conf/config

**Bug description and how to reproduce:**

After creating a custom AMI with the following command (based on Amazon Linux2), completing successfully:

https://github.com/umccr/infrastructure/blob/master/parallel_cluster/bin/create_ami.sh

The user starts the cluster, [but on termination](https://github.com/umccr/infrastructure/blob/master/parallel_cluster/bin/stop_cluster.sh), all the volumes created seem to remain:

![Skärmavbild 2020-04-29 kl  09 38 40](https://user-images.githubusercontent.com/175587/80548393-2f827a00-89fe-11ea-9e3f-92efe7201d09.png)

Is there any directive I'm missing ([from the official parallelcluster docs](https://docs.aws.amazon.com/parallelcluster/latest/ug/aws-parallelcluster-ug.pdf)) on config or while creating the AMI via `pcluster createami`? The `[ebs]` section does not seem to allow the configuration of [deletion for EBS volumes on termination](https://aws.amazon.com/premiumsupport/knowledge-center/deleteontermination-ebs/).

I could workaround it via `bootstrap.sh`, but I guess it would make sense to have this functionality exposed under `[ebs]` config for `createami` to use?

/cc @reisingerf @AndrewPattison

**Comment by brainstorm** [comment]
I just found out that this is closely related with another user's feedback on issue #1544

**Comment by rexcsn** [comment]
Hi @brainstorm ,

Are these volume created by the cluster?

By default, all resources created by the pcluster cluster stack should be deleted when the cluster is deleted. I am unable to reproduce your issue, even when using a `custom_ami`. All the resources created by pcluster are cleaned up on cluster deletion.
