### ISSUE TITLE
Bug: Scheduler thinks there are pending jobs, but none exist

### ISSUE THREAD

**Issue by briandobbins** [aws/aws-parallelcluster#1759]
**Environment:**
 - AWS ParallelCluster 2.5.0

**Bug description and how to reproduce:**
We have apparently had a parallelcluster instance spinning up nodes endlessly for the past two months, with logs like this:
2020-05-04 11:47:18,858 INFO [slurm:get_required_nodes] Found the following pending jobs:
[]
2020-05-04 11:47:18,858 INFO [jobwatcher:_poll_scheduler_status] There are no pending jobs or the requirements on pending jobs cannot be satisfied. Noop.
2020-05-04 11:48:18,805 INFO [utils:get_asg_settings] ASG min/desired/max: 0/4/10

I'm happy to provide any additional data; I'm posting this now to get the chance to do that before shutting things down.  Instead, I've set the autoscaling group to do a max of 0 nodes, since this has run up costs around $3K/month when we weren't actually using nodes.

Previously this environment has worked without issues - has anyone seen 'ghost' launches of nodes like this before?  Is there any idea what the culprit might be?  We're currently using Slurm, with customized AMIs.

I'm happy to attach fuller logs.

Thanks!
  - Brian

**Comment by rexcsn** [comment]
Hi,

Please double check that you are not setting `maintain_initial_size = true`.
To help us diagnose the problem, please attach the following config/logs:
* config file used to launch the cluster
* `/var/log/jobwatcher` log from master node
* `/var/log/sqswatcher` log from master node
* `/var/log/nodewatcher` log from one of the compute nodes that did not terminate

Thank you.

**Comment by tarankalra-usgs** [comment]
Hi Brian, 

I have noticed this in our setup. We do have ``` maintain_initial_size=true``` in the configuration file. 

thank you,

**Comment by rexcsn** [comment]
Hi,

`maintain_initial_size=true` is used to keep the initial size of compute nodes alive and available.
For example, if you have `initial_queue_size=4` and `maintain_initial_size=true`, the cluster will keep 4 compute nodes up at all time.
Please remove `maintain_initial_size=true` from your configuration if you want all compute nodes to scale down when they are idle.

You can also use [`scaledown_idletime`](https://docs.aws.amazon.com/parallelcluster/latest/ug/scaling-section.html) to control how long the compute nodes should wait before scaling down after they are idle.

I will go ahead and close this issue now. Please let us know if you have any open question.

Thank you!
