### ISSUE TITLE
is_node_down() reports down too quickly

### ISSUE THREAD

**Issue by nathanhaigh** [aws/aws-parallelcluster#1763]
I'm having issues where `sinfo`, executed within `is_node_down()`, timesout after 60s, causing a compute node to be reported as down and then subsequently terminated.

The reason for `sinfo` timeout out is a bit unclear but might relate to network congestion. In either case, it seems too aggressive for `is_node_down()` to report a node as being down just because `sinfo` timesout once. Perhaps the use of the `@retry` decorator should be used to ensure `sinfo` doesn't just timeout?

https://github.com/aws/aws-parallelcluster-node/blob/47ef7224cf2ed0c7d27759106eb5a90d219f002f/src/nodewatcher/plugins/slurm.py#L83

```
May  7 00:55:46 ip-10-255-1-85 nodewatcher 2020-05-07 00:55:45,796 INFO [slurm:is_node_down] Node is in state: 'allocated'
May  7 00:55:56 ip-10-255-1-85 nodewatcher 2020-05-07 00:55:52,721 INFO [nodewatcher:_poll_instance_status] Instance has active jobs.
May  7 00:57:56 ip-10-255-1-85 nodewatcher 2020-05-07 00:57:52,745 ERROR [slurm:is_node_down] Failed when checking if node is down with exception Comma
May  7 00:57:56 ip-10-255-1-85 nodewatcher 2020-05-07 00:57:52,746 WARNING [nodewatcher:_poll_wait_for_node_ready] Node reported as down
May  7 00:57:56 ip-10-255-1-85 nodewatcher 2020-05-07 00:57:52,746 ERROR [nodewatcher:_terminate_if_down] Node is marked as down by scheduler or not at
May  7 00:58:47 ip-10-255-1-8 compute_sync.sh[17851]: ssh: connect to host ip-10-255-1-85 port 22: Connection refused
```

If it helps, this is a summary of the cluster load at the time of the node node terminations. During this time there was an excess of jobs in the queue so no reason for a drop in nodes/CPU count at arount 00:05-00:10 and 00:20, other than terminations due to `sinfo` timing out:

![image](https://user-images.githubusercontent.com/2037575/81244221-f1fe9c00-9050-11ea-8ef9-deb007f583e6.png)

**Comment by rexcsn** [comment]
Hi @nathanhaigh,

Thanks for reporting the issue. In recent versions of `pcluster`, there is a 5 minutes `TERMINATE_TIMEOUT`, and `nodewatcher` will only terminate a node if it's consistently been in down states for 5 minutes, see code [here](https://github.com/aws/aws-parallelcluster-node/blob/v2.6.1/src/nodewatcher/nodewatcher.py#L184).

Could you provide the version of `pcluster` that you are using and your cluster config file?

Thanks!

**Comment by nathanhaigh** [comment]
I'm running on 2.4.1. From a quick look, it seems the logic here hasn't changed in 2.6.1.

**Comment by enrico-usai** [comment]
Hi @nathanhaigh 
as highlighted by you we already extended the TERMINATE_TIMEOUT configuration parameter.

Is it ok for you to migrate to the new version of ParallelCluster and try it?
If you cannot drop the existing cluster you could create a pre_install script to change the configuration parameter in the nodewatcher code, but we don't recommend this path.

Let us know if we can close this issue.
Thanks

Let

**Comment by nathanhaigh** [comment]
Lets close it - if I come across the issue with the latest version, I'll reopen or submit a new issue.
