### ISSUE TITLE
Status: parallelcluster-hpc002 - CREATE_FAILED

### ISSUE THREAD

**Issue by shanxiong001** [aws/aws-parallelcluster#1773]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 
   aws-parallelcluster-2.6.1
 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.
[aws]
aws_region_name = cn-northwest-1

[cluster sge]
key_name = shanxiong0511
vpc_settings = xiong
scheduler = sge
master_instance_type = t3.xlarge
compute_instance_type = m5.xlarge
initial_queue_size = 1
max_queue_size = 2
maintain_initial_size = true
cluster_type = spot
extra_json = { "cluster" : { "cfn_scheduler_slots" : "cores"} }
base_os = alinux
custom_ami = ami-056169db492793d02
compute_root_volume_size = 50
master_root_volume_size = 50
ebs_settings = genomes
scaling_settings = GATK-ASG

[ebs genomes]
shared_dir = genomes
ebs_snapshot_id = snap-040c71fd2bb5d4236
volume_type = gp2
volume_size =  1024

[scaling GATK-ASG]
scaledown_idletime = 5

[global]
cluster_template = sge
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[vpc xiong]
vpc_id = vpc-335be65a
master_subnet_id = subnet-039e8ae1564970fe8

**Bug description and how to reproduce:**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

[ec2-user@ip-172-20-0-208 ~]$ pcluster create -c ~/.parallelcluster/config hpc002 --norollback
Beginning cluster creation for cluster: hpc002
Creating stack named: parallelcluster-hpc002
Status: parallelcluster-hpc002 - CREATE_FAILED
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-hpc002 The following resource(s) failed to create: [MasterServerWaitCondition, ComputeFleet].
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Resource creation cancelled
  - AWS::CloudFormation::WaitCondition MasterServerWaitCondition Failed to receive 1 resource signal(s) within the specified duration

i have try to create HPC cluster  serial times, all failure.

could you help me check my config file  or other some reason 

thanks

**Comment by shanxiong001** [comment]
attach file is the log

**Comment by shanxiong001** [comment]
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/4613417/cfn-init-cmd.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/4613418/cfn-init.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/4613419/cloud-init.log)
[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/4613420/cloud-init-output.log)

**Comment by enrico-usai** [comment]
Hi @shanxiong001 

I analyzed the logs you provided and I'm unable to find issues, so it seems the Master Server has been created correctly.
I see you set `initial_queue_size = 1` so the cluster creation is probably failing during the creation of the compute instance.

You can retrieve the logs of the failing compute node by executing the `pcluster create` with the `--norollback` option and checking in the [CloudWatch Groups](https://docs.aws.amazon.com/parallelcluster/latest/ug/cloudwatch-logs.html) created within the cluster.

In any case I see you're using a `custom_ami`. [Which process](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html) did you follow to create it?

Thanks
