### ISSUE TITLE
Cluster creation complete

### ISSUE THREAD

**Issue by mukulagrawal78** [aws/aws-parallelcluster#1778]
I am using cfncluster. On the master node, is there a way for me to check/poll that cluster creation is complete before I start submitting jobs to SGE? Is there any file or env variable available on master node that I can poll?

**Comment by lukeseawalker** [comment]
Hi,
you could check the status of the cluster e.g.
```
aws cloudformation describe-stacks --stack-name <your-stack-name> --region <your-region> --query Stacks[].StackStatus --output text
```

Side note, I would recommend to update to ParallelCluster which comes with many bug fixes and improvements respect to cfncluster, see https://github.com/aws/aws-parallelcluster/releases

**Comment by mukulagrawal78** [comment]
Thanks @lukeseawalker .
Is parallelcluster backward compatible with cfncluster? If I use my existing custom AMI, use parllelcluster's JSON template but supply it with my existing input arguments, is it expected to work as it is?

**Comment by lukeseawalker** [comment]
Hi @mukulagrawal78,
the custom AMI must be recreated matching the corresponding ParallelCluster version.
