### ISSUE TITLE
Feature Request: Ability to add existing ENI to the Master server

### ISSUE THREAD

**Issue by jeremyjpaws** [aws/aws-parallelcluster#1782]
Feature Request:
Please allow the ability to pass into the cluster config, an existing ENI to bound to the master server. This would allow defining a consistent static IP address to the master server, which would allow the IP to remain the same even if the master server and cluster had to be replaced.

**Comment by enrico-usai** [comment]
A way to achieve this result could be to use a custom template when creating the cluster: https://github.com/aws/aws-parallelcluster/issues/368#issuecomment-389556927

This solution is not applicable to reuse an Elastic IP from an already running master instance.

**Comment by enrico-usai** [comment]
As part of 3.0.0 release we added the possibility to specify an ElasticIp for the head node: https://docs.aws.amazon.com/parallelcluster/latest/ug/HeadNode-v3.html#yaml-HeadNode-Networking-ElasticIp

**Comment by francisreyes-tfs** [comment]
Would like to re-request this as ElasticIPs are one way to get static IPs but my company connects to AWS via Transit Gateway . I have a block of IP addresses assigned to my subnet that I can just allocate as I wish. Would be nice to take advantage of AWS::EC2::NetworkInterface PrivateIPAddress  from my cluster config to assign to the headnode.
