### ISSUE TITLE
Exporting Changed Data to s3 from FSx

### ISSUE THREAD

**Issue by ophir-oneview** [aws/aws-parallelcluster#1795]
**Environment:**
 - AWS ParallelCluster version 2.6.1
 - Configuration file:

```
[aws]
aws_region_name = eu-west-1

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = oXXXXXXXX
base_os = ubuntu1804
scheduler = slurm
master_instance_type = c5.xlarge
compute_instance_type = p3.2xlarge
max_queue_size = 2
maintain_initial_size = true
vpc_settings = default
compute_root_volume_size = 25
master_root_volume_size = 25
cluster_type = ondemand
fsx_settings = workspace
post_install = s3://my-bucket/install_env.sh
s3_read_resource = arn:aws:s3:::my-bucket/*

[fsx workspace]
shared_dir = /workspace
storage_capacity = 3600
imported_file_chunk_size = 1024
export_path = s3://my-bucket
import_path = s3://my-bucket
weekly_maintenance_start_time = 1:00:00

[vpc default]
vpc_id = vpc-0eXXXXXXXXXXXX
master_subnet_id = subnet-02XXXXXXXXXXXX
compute_subnet_id = subnet-06XXXXXXXXXXX
use_public_ips = false
```

**Bug description and how to reproduce:**
Hello, 
First Amazing project!

My scenario,
I am using parallelcluster for training deep learning models.
All my dataset and code are in s3 that I am connecting to FSx.
My outputs also saved in the same FSx. 
When I finish using my cluster I like to back to that s3 all the changes/ouputs were made in FSx.
I didn't find an automatic way for doing it, do you have one?

I tried to use aws CLI for this with the command:
`aws fsx --region=eu-west-1 create-data-repository-task  --file-system-id $FSX_id \
    --type EXPORT_TO_REPOSITORY \
    --report Enabled=true,Scope=FAILED_FILES_ONLY,Format=REPORT_CSV_20191124,Path=s3:///my-bucket/fsx_reports`

But I am getting:
`An error occurred (AccessDeniedException) when calling the CreateDataRepositoryTask`
There is a way to give upfront (when creating the cluster) the right access role for create data repository task?

If there is no option, I suppose that there is a better practice to save my outputs to this s3?

Thanks 
Ophir

**Comment by sean-smith** [comment]
Hi @ophir-oneview,

You can use the [additional_iam_policies](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#additional-iam-policies) section of the cluster config and give it FSx permissions like so:

```ini
[cluster default]
...
additional_iam_policies = arn:aws:iam::aws:policy/AmazonFSxFullAccess
```

Using `additional_iam_policies` instead of `ec2_iam_role` is the reccomended way to specify additional IAM permissions.

**Comment by ophir-oneview** [comment]
Thanks:)

Looks good!
