### ISSUE TITLE
SGE-Torque Deprecation Announcement Has Broken Links

### ISSUE THREAD

**Issue by rmarable** [aws/aws-parallelcluster#1798]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.5.1]
2.7.0

 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.
N/A

**Bug description and how to reproduce:**
The SGE and Torque deprecation announcement posted at https://github.com/aws/aws-parallelcluster/wiki/Deprecation-of-SGE-and-Torque-in-ParallelCluster contains what appears to be two broken links that are supposed to provide guidance on migrating to AWS Batch from SGE or Torque:

* https://integ-docs-aws.amazon.com/parallelcluster/latest/ug/awsbatchcli.html
* https://integ-docs-aws.amazon.com/parallelcluster/latest/ug/tutorials_03_batch_mpi.html

**Comment by lukeseawalker** [comment]
Thank you for reporting this,
links are fixed now.
* https://docs.aws.amazon.com/parallelcluster/latest/ug/awsbatchcli.html
* https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_03_batch_mpi.htm
