### ISSUE TITLE
Config file with a .ini extension

### ISSUE THREAD

**Issue by sean-smith** [aws/aws-parallelcluster#1799]
As a feature request, I'm suggesting reading the default config file `~/.parallelcluster/config.ini` with a `.ini` extension. 

Newly created config files, with `pcluster configure`, will be created with this suffix and this will support backwards compatibility for the no-extension `~/.parallelcluster/config`. 

### Why is this useful?

This enables syntax highlighting in your favorite editor, which leads to fewer mistakes in editing the config file. For example, a common action such as commenting out a line, can be done in an editor easily with `Command + /` if the editor knows that the file is a `.ini`.

For example, in VIM:

![image](https://user-images.githubusercontent.com/5545980/82693201-ee087780-9c15-11ea-903d-bfb28c72cd03.png)

Versus

![image](https://user-images.githubusercontent.com/5545980/82693620-b3eba580-9c16-11ea-8d42-3f2be8a9bceb.png)

**Comment by demartinofra** [comment]
Currently this can be achieved with `pcluster create --config ~/.parallelcluster/config.ini`

**Comment by sean-smith** [comment]
@demartinofra Yes that's possible and setting the environment variable is possible, however this feature request is requesting the default gets changed.

**Comment by enrico-usai** [comment]
I'm going to close this patch, since in ParallelCluster 3.0 we are changing the format of the configuration file to be a YAML file. Thanks!
