### ISSUE TITLE
qhost "command not found"

### ISSUE THREAD

**Issue by jedijamez567** [aws/aws-parallelcluster#1801]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 2.7.0
 - Configuration file 
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = XXXX
initial_queue_size = 3
max_queue_size = 3
maintain_initial_size = True
base_os = alinux2
scheduler = slurm
vpc_settings = default

[vpc default]
vpc_id = vpc-xxxxxx
master_subnet_id = subnet-xxxxxx
compute_subnet_id = subnet-xxxxxx
use_public_ips = false

**Bug description and how to reproduce:**
After following the getting started guide to the T and logging into my instance using the "pcluster ssh" command, I enter qhost and recieve the following error: 
"-bash: qhost: command not found"

**Additional context:**
qsub is also not working. I get the following error message:

"Can't locate Switch.pm in @INC (@INC contains: /opt/slurm/lib64/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /opt/slurm/bin/qsub line 51, <DATA> line 604.
BEGIN failed--compilation aborted at /opt/slurm/bin/qsub line 51, <DATA> line 604."

**PATH OUTPUT**
"/usr/lib64/qt-3.3/bin:/usr/local/pyenv/shims:/usr/local/pyenv/bin:/opt/amazon//openmpi/bin/:/opt/amazon//efa/bin/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/slurm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin"

**Comment by lukeseawalker** [comment]
Hi @jedijamez567,
`qhost` and `qsub` are commands for `scheduler = sge` but you created a cluster for `scheduler = slurm`

**Comment by bollig** [comment]
Hi @jedijamez567 , in this case, the qhost command is a shim provided with Slurm for compatibility with jobs from pbs/sge clusters. On a Slurm cluster, you will get better functionality using the native sinfo, squeue, and scontrol, etc. If you need qhost, qstat, or other compatibility commands from /opt/slurm/bin, you can “yum install perl-Switch” or “apt-get install libswitch-perl” to activate them.

**Comment by demartinofra** [comment]
Yes what's happening is exactly what @bollig is describing. I'm also going to reference an old issue that contains a reply with some useful links: https://github.com/aws/aws-parallelcluster/issues/1617#issuecomment-578699779

Resolving but feel free to re-open if you still need an input from us.
