### ISSUE TITLE
Latest AMI for testing does not allow for environments where users may be blocked from using  just any AMI

### ISSUE THREAD

**Issue by mjdellwo** [aws/aws-parallelcluster#1822]
https://github.com/aws/aws-parallelcluster/blob/c3bec0846ce370a3691dc0e00cd83530e7eccdcf/cli/pcluster/config/pcluster_config.py#L429

In corporate environments such as mine, we are frequently blocked from using AMIs that are not on an approved list.  The barrier to adding new AMIs to the list is high.

The use of the latest AMI in this function surprised me, as it was not a documented AMI required for pcluster, as given [here](https://github.com/aws/aws-parallelcluster/blob/v2.7.0/amis.txt).  I had requested a specific AMI be whitelisted to get past the initial configuration test, then less than two weeks later the "latest" was advanced, and I had to repeat my request.  Actually, I modified the code in this line to return the specific AMI I had gotten approved previously.  I had to dig into the code to understand why these unlisted AMIs were required, and found that they are only used for a 'DRYRUN' configuration test.

Wouldn't it make sense to use the AMI that pcluster will launch itself, rather than this more generic AMI, which is not otherwise used by pcluster?  This could include potentially custom AMIs specified in the cluster section's [custom_ami](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#custom-ami-section) field.  By using the AMI for testing that is also used by pcluster itself (ie the AMIs in that amis.txt), I can request approval for a specific documented list corresponding to the version of the tool I'm using; I know that the configuration check that this AMI is used for will actually exercise my ability to launch that specific AMI, not some other AMI; and I have the option to stay at that version so as not to be blocked by unexpected changes in the required AMIs.

If that change cannot be made, maybe a global config option to have a 'test_ami'....

**Comment by tilne** [comment]
Sorry for the lack of communication at the time I tagged this issue.

I agree that this is definitely a worthwhile change. The motivation for using the latest Amazon Linux AMI instead of using the AMI that will actually be used is that the AMI mappings used to get the default AMIs for a given region-OS combination is contained in the CloudFormation template unless a `custom_ami` is used (as you mentioned).

As a workaround, you can prevent the error from blocking cluster creation by setting the [sanity_check](https://docs.aws.amazon.com/parallelcluster/latest/ug/global.html#sanity-check) parameter to `false`.

**Comment by enrico-usai** [comment]
This has been addressed as part of https://github.com/aws/aws-parallelcluster/pull/2584 . The code will be released as part of 3.0.0 release and is going to use official amis for the test.

**Comment by demartinofra** [comment]
This was addressed also as part of `2.10.2` release. From changelog:
>Improve cluster config validation by using cluster target AMI when invoking RunInstances in dryrun mode.
