### ISSUE TITLE
InstanceProfile should not be created when using existing Role

### ISSUE THREAD

**Issue by mjdellwo** [aws/aws-parallelcluster#1823]
https://github.com/aws/aws-parallelcluster/blob/cc17cabfbb17fb82b5d3fa28e139e1054b71fd20/cloudformation/aws-parallelcluster.cfn.json#L1539-L1557

This block of CloudFormation template appears to attempt creating an Instance Profile even when the configuration is set to use an existing IAM Role.  In my (corporate) environment, I am not allowed to create a role or instance profile, I must request one be created for me.  Hence I configured a specific role, but see this error (Ive obscured the accountid):
`2020-06-01 15:54:31,389 - INFO - utils -   - AWS::IAM::InstanceProfile RootInstanceProfile API: iam:CreateInstanceProfile User: arn:aws:iam::123456789012::user/mjdellwo is not authorized to perform: iam:CreateInstanceProfile on resource: arn:aws:iam::123456789012:instance-profile/parallelcluster-test-cluster1-RootInstanceProfile-SM6TYRAZNTQM with an explicit deny`

The role I provided already has an instance profile, and there is no role corresponding to the instance profile in the error message.  There is no way that I can see to provide a specific instance profile.  My work-around will likely be to take the overall template that my configuration generated, to take out this block, and to hard-code the specific instance profile.  And configure it as a custom template, which may cause other issues for me (I believe it requires a public URL).

**Comment by mjdellwo** [comment]
Is there any reason this is tagged as an enhancement rather than a bug?  (I may be misinterpreting tags here.)  IMO it's a bug: a role is explicitly provided in the configuration parameter 'ec2_iam_role' in a [cluster] section, but the cloudformation does not use the role's instance profile, instead attempting to create one.

**Comment by rexcsn** [comment]
Hi @mjdellwo ,

Our current limitation is that we are always creating the `RootInstanceProfile` for the user. As such we require the users to have the permission to create the instance profile, `iam:CreateInstanceProfile`, in their user policy; please see our official documentation [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html).

When user is providing an IAM role, we will still create the `RootInstanceProfile`, but using the custom role user provided instead of the default role `pcluster` creates.
I understand that this is a limitation for you since your corporate environment prevents you from creating role or instance profile, but we currently do not support specifying a custom instance profile. Additionally, the instance profile to use cannot be determined automatically from a role user provided because a role can be associated with multiple instance profiles.

As such, we are marking the support of custom instance profile (possibly in the form of a new parameter similar to `ec2_iam_role`) as an enhancement.

Please let us know if you have any question. Thank you!

**Comment by mjdellwo** [comment]
Hi @rexcsn, I would be supportive of a new parameter ec2_iam_instanceprofile, only needed when ec2_iam_role is used.  I wasn't aware that a role cold be associated with multiple instance profiles! I'll have to follow up w/ my account  TAMs, interested to know more about that and how it might be useful... 

Which gets specified in a launch template and/or RunInstances call, the role or the instance profile?  If it's the instance profile, maybe you don't really need ec2_iam_role.  If an instance profile can be associated with only one role, this would be sufficient to tell CloudFormation to create both a (new) role and an instance profile if not specified.  I think...  And I guess it would be a breaking change to remove ec2_iam_role entirely.

**Comment by tilne** [comment]
> Which gets specified in a launch template and/or RunInstances call, the role or the instance profile?

The instance profile is specified in the ParallelCluster launch templates.

> And I guess it would be a breaking change to remove ec2_iam_role entirely.

It would be a breaking change to remove it, but I think it's possible for the two parameters to coexist.

**Comment by dan-schlecht** [comment]
is this fixed in the latest 2.10.4 verson of aws-parallelcluster?  I also have this issue with corporate env not allowing me to create Instance profiles

**Comment by yuleiwan** [comment]
@dan-schlecht
Sorry, the 2.10.4 verson of aws-parallelcluster doesn't include this feature.

**Comment by dan-schlecht** [comment]
do you know when ec2_iam_instanceprofile parameter would be added?

**Comment by datechnic** [comment]
@rexcsn @yuleiwan  Do you know if there if support for rootinstanceprofile creation has been addressed with 2.11?  I have the same issue as the gentlemen that created this post and i am unable to create roles in my corporate environment.

**Comment by yuleiwan** [comment]
@datechnic Unfortunately, 2.11 still needs `RootInstanceProfile` creation

**Comment by datechnic** [comment]
@enrico-usai I apologize as I am not familiar with the lifecycle or the process.  When do you anticipate the parameter to be available for use by the public ?

**Comment by ZeroCool2u** [comment]
Is there an ETA for v3.0.0?

**Comment by enrico-usai** [comment]
Hi @datechnic I added the milestone because this feature enhancement has been already included in the changes that will be part of the 3.0.0 release: https://github.com/aws/aws-parallelcluster/pull/2912

@ZeroCool2u there is no public ETA but we're currently working for it.

**Comment by enrico-usai** [comment]
I'm closing this issue since 3.0.0 is out (and 3.0.2 too).
