### ISSUE TITLE
EFS mount error in China region

### ISSUE THREAD

**Issue by Iwillsky** [aws/aws-parallelcluster#1839]
**Environment:**
 - AWS ParallelCluster: aws-parallelcluster-2.7.0
**Bug description and how to reproduce:**
PCluster will fail when config EFS mounting in China region(BJS & ZHY). We found EFS endpoint resolving error in EFS mounting step through log. It is hard-coded as "xxx.amazonaws.com" in efs_mount.rb recipe.

**Additional context:**

sudo sed -i "s/amazonaws.com/amazonaws.com.cn/g" /etc/chef/cookbooks/aws-parallelcluster/recipes/efs_mount.rb

Although we can point to a pre_install.sh including above code, we really hope this bug can be fixed to be adaptive to China region without region-sensitive.

Similar code is here FYR:
s3_domain = "https://s3.#{node['cfncluster']['cfn_region']}.amazonaws.com"
s3_domain = "#{s3_domain}.cn" if node['cfncluster']['cfn_region'].start_with?("cn-")

**Comment by enrico-usai** [comment]
Hi @Iwillsky thanks for pointing this out. It's definitely a bug.

**Comment by lukeseawalker** [comment]
Hi @Iwillsky,
EFS support for China is targeted for next release.

**Comment by Iwillsky** [comment]
Thanks. It will be convenient to China customers. We ❤️ aws.

**Comment by Iwillsky** [comment]
Hi @lukeseawalker ,
We also found similar hard-coded url in fsx_mount.rb. It would be better if resolved together in the next release.

**Comment by lukeseawalker** [comment]
Hi @Iwillsky,
it has been taken care by this PR https://github.com/aws/aws-parallelcluster-cookbook/pull/640
Thanks

**Comment by lukeseawalker** [comment]
AWS ParallelCluster 2.8.0 with EFS support in China has been released https://github.com/aws/aws-parallelcluster/releases/tag/v2.8.0
