### ISSUE TITLE
Invalid custom cloudformation template

### ISSUE THREAD

**Issue by ma9o** [aws/aws-parallelcluster#1848]
**Environment:**
 - aws-parallelcluster-2.7.0
 - [parallelcluster/config](https://github.com/aws/aws-parallelcluster/files/4825353/config.txt)

**Bug description and how to reproduce:**
- Edit template: `InstanceInterruptionBehavior: "hibernate"`
- Upload to [public s3 bucket](https://buckeroni.s3.amazonaws.com/aws-parallelcluster.cfn.json)
- Create cluster from template url:

![image](https://user-images.githubusercontent.com/46647883/85557818-6ead0000-b628-11ea-9d82-b9a7d2febe96.png)

**Comment by enrico-usai** [comment]
Hi @ma90,
 I think you're using a newest cloudformation template (from [develop](https://github.com/aws/aws-parallelcluster/blob/develop/cloudformation/aws-parallelcluster.cfn.json) branch) on which we removed the `CLITemplate` parameter.

Please download and edit the json for the [2.7.0](https://github.com/aws/aws-parallelcluster/blob/v2.7.0/cloudformation/aws-parallelcluster.cfn.json) version.

Let us know if it helps.

**Comment by ma9o** [comment]
Thanks, it worked :+1:
