### ISSUE TITLE
I can't disable hyperthreading with *.metal instances

### ISSUE THREAD

**Issue by vbosquier** [aws/aws-parallelcluster#1855]
**Environment:**
 - AWS ParallelCluster version : aws-parallelcluster-2.7.0
 - OS: centos7
 - Scheduler: Slurm
 - Master instance type: m5.2xlarge
 - Compute instance type: c5n.metal

**Bug description and how to reproduce:**
When trying to launch a cluster with Compute instance type set to any metal instances (we tested with c5.metal, z1d.metal and c5n.metal) and the variable disable_hyperthreading set to true, PCluster fails to start the cluster with the following error:
`2020-06-24 10:43:07,135 - INFO - commands - 2020-06-24 10:30:43.599000+00:00 CREATE_FAILED AWS::AutoScaling::AutoScalingGroup ComputeFleet You must use a valid fully-formed launch template. The c5n.metal instance type does not support specifying CpuOptions. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 48f27a53-3ff6-4f3f-99d0-1fc5ca513ded)
`
It seems that this is the default behaviour of PCluster. But as soon as I start a cluster withtout the disable_hyperthreading option set to true, the cluster starts successfully with 2 threads per core.

What is the process to work with non-hyperthreaded metal instances? What do you recommend?

Let me know if you need aditional information.

Best regards,
Vincent Bosquier, UCit.

**Comment by lukeseawalker** [comment]
Hi @vbosquier,
I'm reporting here the doc about the [disable_hyperthreading](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#disable-hyperthreading) parameter

> Not all instance types can disable hyperthreading. For a list of instance types that support disabling hyperthreading, see[ CPU Cores and Threads Per CPU Core Per Instance Type](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-optimize-cpu.html#cpu-options-supported-instances-values) in the Amazon EC2 User Guide for Linux Instances.

If you look at the list of [instance types that support specifying CPU options](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-optimize-cpu.html#cpu-options-supported-instances-values), the `metal` instances are not listed.

The error you get is reporting that:
`The c5n.metal instance type does not support specifying CpuOptions. `

Setting `sanity_check = true` in the configuration, the cluster creation should have been blocked
```
pcluster create github-1855 -t github-1855                                                                                                 
Beginning cluster creation for cluster: github-1855
ERROR: The c5n.metal instance type does not support specifying disable_hyperthreading.
```

**Comment by lukeseawalker** [comment]
Hi @vbosquier,
you can still disable hyperthreading on metal instances if you follow the guide [here](https://github.com/aws/aws-parallelcluster/wiki/How-to-disable-Intel-Hyper-Threading-Technology).

**Comment by vbosquier** [comment]
Hi,

Let me try this option :
extra_json = { "cluster" : { "cfn_scheduler_slots" : "cores" } }
... and I'll let you know how it works.

(I thought it was deprecated since the "disable_hyperthreading" variable was available...)

Best regards,
Vincent.

**Comment by rexcsn** [comment]
Hi @vbosquier,

If there is no open question or concern I will resolve the issue.

Thank you!
