### ISSUE TITLE
SGE Scheduler job stuck on qw state. Not spawning or calling spot instances

### ISSUE THREAD

**Issue by sumedhjain** [aws/aws-parallelcluster#1860]
**Environment:**
 - aws-parallelcluster-2.7.0
 - Config file 
![Screenshot from 2020-07-01 15-07-21](https://user-images.githubusercontent.com/64367379/86228905-9bbf5c80-bbac-11ea-8582-db18ba998d70.png)

**Bug description and how to reproduce:**
Upon submission of job to default queue as ec2-user, it takes the job but is stuck in 'qw' pending state forever.
Tricks tried till now.
1. Added ec2-user as manager - same result.
2. Added a new queue - Job not being accepted into the new queue at all.
 

**Additional context:**
/var/log/jobwatcher

![jobwatcher](https://user-images.githubusercontent.com/64367379/86228963-ae399600-bbac-11ea-97af-deb138ef2030.png)

/var/log/sqswatcher

![sqs](https://user-images.githubusercontent.com/64367379/86229002-bc87b200-bbac-11ea-8da2-b526abd5fb71.png)

/var/log/system-messages
![Screenshot from 2020-07-01 11-06-31](https://user-images.githubusercontent.com/64367379/86229050-cb6e6480-bbac-11ea-936b-7f3813f6ee1f.png)

**Comment by sumedhjain** [comment]
@sean-smith Please do take a look at this issue. 

*Ignore the other comment where I have tagged you.

**Comment by lukeseawalker** [comment]
Hi @sumedhjain,
from the attached logs 1 node is being added to the ASG but from the sqswatcher log no messages are coming from that node.

I would proceed with the following points:
1 - look at the activity history of the autoscaling group of your cluster, with the command:
```
aws autoscaling describe-scaling-activities --region us-east-2 --query "Activities[?contains(AutoScalingGroupName, 'parallelcluster-<your_cluster_name>-ComputeFleet')]"
 ```
What's the output of this command?

2 - if the first point is not helpful to understand the problem, check if, on the head node side, there is a file in the `/home/logs/compute` folder. The name of the file should be `<instance-id>.tar.gz`.

Please attach this file

3 - if there is no `/home/logs/compute/<instance-id>.tar.gz` you need to retrieve the cluster logs, leveraging the CloudWatch logs integration. You can follow the guide [here](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs) to retrieve the cluster logs.

Please attach the tarball or at least the /var/log/nodewatcher log files.

Thanks.

**Comment by sumedhjain** [comment]
Hi @lukeseawalker ,
Thanks for taking a look at this issue. 

1. Activity history of the autoscaling group.
An error was thrown telling that I do not have access to seek them. Although I created this cluster and I am the IAM user of this account. 
**An error occurred (AccessDenied) when calling the DescribeScalingActivities operation: User: arn:aws:sts::XXXXXXXXXX:assumed-role/parallelcluster-XXXXXX-RootRole-107KA6GMXQ6BV/i-0bb9f48831d0c1983 is not authorized to perform: autoscaling:DescribeScalingActivities**

2. There is no such file on my head node. 

3. PFA nodewatcher log from CW. 

[log-events-viewer-result.pdf](https://github.com/aws/aws-parallelcluster/files/4871153/log-events-viewer-result.pdf)

**Comment by lukeseawalker** [comment]
Hi @sumedhjain,
the point number 1. indicates that your IAM user doesn't have the right level of permissions to create all the resources to manage the cluster.
Please verify that the policy associated to your user are the one described [here in the ParallelClusterUserPolicy](https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html#parallelclusteruserpolicy).

In this policy please remember to substitute the placeholders with the appropriate values:
* `<REGION>` with `us-east-2`
* `<AWS ACCOUNT ID>` with your AWS account ID
* `<PARALLELCLUSTER EC2 ROLE NAME>` with `parallelcluster-*`

After that, please recreate your cluster and check again at the activity history of the autoscaling group of your new cluster, with the command:

`
aws autoscaling describe-scaling-activities --region us-east-2 --query "Activities[?contains(AutoScalingGroupName, 'parallelcluster-<your_cluster_name>-ComputeFleet')]"
`

If everything is OK within this step, we can start from here to investigate any other problem. Please follow again the guide [here](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs) to retrieve the cluster logs and attach to this ticket the archive log file obtained following the guide.

**Comment by sumedhjain** [comment]
Hi @lukeseawalker  I managed to add the policies to my parallelcluster role using the link you mentioned.
I was under the impression that since cloud9 is creating a cluster, it will obviously add all necessary permissions and roles required to run the cluster. Obviously this is not true. I created this cluster using pcluster module Cloud9.

Furthermore, I ran the command you have mentioned seeking scaling activitiy, to my surprise I found that my spot instance count limit has been exceeded. Although, I am requesting only 2 spot instances. Furthermore, I tried to file an limit increase. Apparently, my instance type c5n.metal that I need is not at all in the list of spot instance type. This is appaling. 

Please take a look into this issue. 
PFA the response to scaling activity command

{
        "Description": "Launching a new EC2 instance.  Status Reason: Max spot instance count exceeded. Launching EC2 instance failed.", 
        "AutoScalingGroupName": "parallelcluster-CFD1-ComputeFleet-Z7ZJ9MPCU6GV", 
        "ActivityId": "8b35cc94-93b1-640d-7f02-9eafd70677c0", 
        "Details": "{\"Subnet ID\":\"subnet-XXXXXX\",\"Availability Zone\":\"us-east-2a\"}", 
        "StartTime": "2020-07-06T17:20:43.609Z", 
        "Progress": 100, 
        "EndTime": "2020-07-06T17:20:43Z", 
        "Cause": "At 2020-07-06T17:20:41Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.", 
        "StatusMessage": "Max spot instance count exceeded. Launching EC2 instance failed.", 
        "StatusCode": "Failed"
    },

**Comment by ddeidda** [comment]
Hi @sumedhjain.

Do you have other spot instances in the same AWS region on your account? As per the [official documentation](https://docs.aws.amazon.com/whitepapers/latest/cost-optimization-leveraging-ec2-spot-instances/spot-request-limits.html):
> "By default, there is an account limit of 20 Spot Instances per AWS Region."

**Comment by sumedhjain** [comment]
> Hi @sumedhjain.
> 
> Do you have other spot instances in the same AWS region on your account? As per the [official documentation](https://docs.aws.amazon.com/whitepapers/latest/cost-optimization-leveraging-ec2-spot-instances/spot-request-limits.html):
> > "By default, there is an account limit of 20 Spot Instances per AWS Region."
> 
> 

No....

**Comment by ddeidda** [comment]
@sumedhjain, 

Could you please double check by running the following command? It should tell you which active spot instances are running in your account in us-east-2 region.

```
aws ec2 describe-spot-instance-requests --filters Name=state,Values=active --region us-east-2 | grep InstanceId
```
If the output gives you more instances than you expected we can try investigating on this.

**Comment by sumedhjain** [comment]
@ddeidda,
I had raised a ticket and they told me the limit for c5n.metal (and certain other high demand instance types) spot instances for new accounts is usually 0. 

Furthermore, they have taken my request to increase my spot instance limit. Hopefully, they approve. Let's wait and see.

**Comment by ddeidda** [comment]
Thanks @sumedhjain for reporting this back to us.
Please let us know if the issue is solved after the limit increase.

**Comment by sumedhjain** [comment]
Ok @ddeidda @lukeseawalker ,
I have some new issues,
1. After increasing my spot instance limits, it was able to get spot instances. I could see new instances running in my EC2 console but they are not seen in qhost. And the job is still stuck in qw state. This is frustrating. According to the CFD for motorsport webinar by AWS, the setup was supposed to be smooth. This is taking so much, so many hurdles.

2. My job required 1 EC2 spot instance, whereas, it constantly submits requests for 2 spot instances. No idea why!!

3. More importantly, even after scaledown_time = 10 minutes (default). The spot instances does not seem to shut themselves down. Strange!!!

Please take a look these issues.

Thanks in advance.

**Comment by ddeidda** [comment]
Hi @sumedhjain.

Sorry for the problems you are encountering.
I see from your configuration that you are using a ``custom_ami``. Since the AMI is public I was able to see that it has been baked with an older version of parallelcluster. You can check this by running this command on the master node:

```
$ cat /opt/parallelcluster/.bootstrapped 
aws-parallelcluster-2.6.1
```
As reported in our [documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html):
> After you build your own AMI, you no longer receive updates or bug fixes with future releases of AWS ParallelCluster. Also, you must repeat the steps used to create your custom AMI with each new AWS ParallelCluster release. 

To overcome this issue, you could either install ParallelCluster 2.6.1 using the following command (using a [Virtual environment](https://docs.aws.amazon.com/parallelcluster/latest/ug/install-virtualenv.html) is recommended):
```
pip install aws-paralllelcluster==2.6.1
```
or create a new AMI for ParallelCluster 2.7 following one of our [recommended methods](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html). Once you do one of these operations, please re-create your cluster.

If you keep experiencing issues after doing what suggested, please share your cluster's log files (cfn-init.log from compute nodes should be the most important one for this case) following the guide [here](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs).

**Comment by sumedhjain** [comment]
Hello @ddeidda 
Following your instructions,
Recreated my cluster using ParallelCluster 2.6.1. Unfortunately, same result. Job is still stuck in qw state.

PFA the cfn-init log file from the compute node



[cfn-init_compute_node-pdfdoctor_com.pdf](https://github.com/aws/aws-parallelcluster/files/4897640/cfn-init_compute_node-pdfdoctor_com.pdf)

**Comment by sumedhjain** [comment]
I would like to thank AWS GitHub handler for solving this issue. Ultimately, it boiled down to my EC2 vCPU limit.
