### ISSUE TITLE
Spot Instance/Rollback Behavior

### ISSUE THREAD

**Issue by mukulagrawal78** [aws/aws-parallelcluster#1898]
This is a general question about how should I expect the cfncluster to behave when spot instances are requested for compute nodes.

If I need a few initial compute nodes and if spot procurement fails then I see cluster creation failure. That is understanable.
My question is what happens if spot procurement fails during cluster scaling? I have few compute ndoes in cluster. I have few jobs waiting in queue. cfncluster tries to procure few more compute nodes but procurement fails at bidding price. Would it be reported as error and rollback triggered? Or else, its not treated as error and jobs would just keep waiting in queue waiting for hardware to be available? Would cfncluster try bidding for spot instances again after sometime? Or would it just try one time and then give up?

Thanks, appreciate any guidance.

**Comment by tilne** [comment]
Hi, Mukul.

> My question is what happens if spot procurement fails during cluster scaling?
...
> Would cfncluster try bidding for spot instances again after sometime? Or would it just try one time and then give up?

The auto-scaling group used to scale the number of compute nodes available to the cluster will continue attempting to bid for nodes based on the [spot_price](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#spot-price) configuration parameter. If you set `spot_price` to too low a value, you can safely change it on a running cluster using the `pcluster update` command.

> Would it be reported as error and rollback triggered? Or else, its not treated as error and jobs would just keep waiting in queue waiting for hardware to be available?

Jobs would keep waiting in the queue until the hardware became available. Of course, jobs would also continue to flow through the compute nodes already part of the cluster (provided the job's requirements were satisfied).

Also, here is a link to our official documentation on [working with Spot instances](https://docs.aws.amazon.com/parallelcluster/latest/ug/spot.html). It mostly contains information for dealing with spot instance interruptions, which isn't directly related to your inquiry but might come in useful as you work more with spot clusters.

**Comment by mukulagrawal78** [comment]
@tilne , thank you for your reply. This was very helpful. Is this behavior consistent between cfncluster and parallelclsuter?

Link you provided was very helpful as well. I am just a bit confused about the following section. If job continues to run then why do you necessarily revcomend user to kill the job? Is it because some MPI processes got killed? If they are non communicating then I should be fine right?

SGE
The job is not terminated and continues to run on the remaining nodes. The compute node is removed from the scheduler queue, but will appear in the hosts list as an orphaned and unavailable node.

The user must delete the job when this occurs (qdel <jobid>).
