### ISSUE TITLE
Feature request(s) -- fixed ENI for master node / tolerate LogGroups persisting after cluster is deleted

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#1900]
**Context** 
Heavy parallecluster user as a consultant across multiple orgs and aws accounts. Thanks again for all the work on this project as it is very helpful and very powerful for use in the life sciences.   I've got two potential feature requests that arose out of a few different projects. None of these are bugs or blockers but they've come up often enough that I figured I'd mention them to see if it made sense to look at them for a future roadmap ..

**Feature request 1 - support mapping an existing ENI to the master node NIC** 

Summary:  _provide an ENI-id that can be assigned to the master node during a new deploy._ 

The use case here is "heavily secured environment with lots of firewalls". It would be very useful if we could have a pre-existing ENI network interface that the firewall and inline security devices were already aware of and are already set up with policies to pass traffic. This would let us deploy a new HPC environment with a "known" network interface that would not need post-deploy work by the firewall and security teams.  

Currently I get around this by mapping an ENI in as a secondary NIC on the master node but this causes the standard "multiple NICs on the same subnet" routing issues that require some delicate scripting to get around. 

**Feature request 2 -  tolerate preservation of parallelcluster Cloudwatch LogGroups when cluster is deleted** 

Summary:  Support keeping the cloudwatch logGroups created by a cluster during "pcluster delete" 

This one hit me this week with a client that had set up IAM rules that utterly blocked any attempt to delete a cloudwatch log group or log stream. This is also a security related design decision intended to stop bad actors from deleting logs. 

However "pcluster delete" fails to run cleanly with this restriction in place. Because the stackset can't fully clean up after itself the delete process errors out.  The more I think about this the more I'm supportive of a '_we never delete logs_' type approach so if possible I'd like to see if Parallelcluster could be supportive of a scenario where the logs are preserved when the cluster is deleted or cleaned up

And just to be clear again, these are not bugs or blockers for me, just things I noticed working across a number of different client environments, Thanks!

**Comment by tilne** [comment]
Hi, Chris. Thanks for the feature requests. 

Regarding the second one, this functionality is already available starting in version 2.6.0. You can pass the `--keep-logs` flag to the `pcluster delete` command:

```
➜  pcluster delete --help
usage: pcluster delete [-h] [--keep-logs] [-c CONFIG_FILE] [-r REGION] [-nw]
                       cluster_name

....

optional arguments:

...

  --keep-logs           Keep cluster's CloudWatch log group data after
                        deleting. The log group will persist until it's
                        deleted manually, but log events will still expire
                        based on the previously configured retention time.
```

**Comment by tilne** [comment]
Related to #1782

**Comment by enrico-usai** [comment]
I'm going to close this issue because 1. is already addressed and 2. is tracked on https://github.com/aws/aws-parallelcluster/issues/1782 . Thanks
