### ISSUE TITLE
2.8.0: Error when calling DescribeInstanceTypes for instances t2.medium: You are not authorized to perform this operation.

### ISSUE THREAD

**Issue by tolid** [aws/aws-parallelcluster#1912]
**Environment:**
 - AWS ParallelCluster 2.8.0

 - Configuration file:

[aws]
aws_region_name = eu-central-1

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = xxxxx
base_os = ubuntu1804
scheduler = torque
master_instance_type = t2.medium
compute_instance_type = c3.4xlarge
maintain_initial_size = true
vpc_settings = default

[vpc default]
vpc_id = vpc-xxxx
master_subnet_id = subnet-0bxxxx
compute_subnet_id = subnet-0dxxxxx

**Bug description and how to reproduce:**
After upgrade from 2.7.0 to 2.8.0 any pcluster command reports error:
$ pcluster list
ERROR: Error when calling DescribeInstanceTypes for instances t2.medium: You are not authorized to perform this operation.

No problems on the same setup in 2.6.1 and 2.7.0

**Comment by demartinofra** [comment]
Hi @tolid,

As part of 2.8.0 we improved the validations performed in the CLI and as a result of it a new policy is required when running pcluster create: "ec2:DescribeInstanceTypes". The full set of policies required by the latest version can be found [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html#parallelclusteruserpolicy). Please let us know if you need further support.

**Comment by tolid** [comment]
Thank you @demartinofra 

It works!
