### ISSUE TITLE
SQS send message not reaching queue

### ISSUE THREAD

**Issue by efrye04** [aws/aws-parallelcluster#1924]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.5.1]
 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.

**Bug description and how to reproduce:**
SQS message not sent after compute_ready is executed by chef routine.  Manually modifying the compute_ready script to remove the ".cn" logic allows the script to execute properly.

**Comment by enrico-usai** [comment]
Hi @efrye04 ,
could you give us more context to try to reproduce your issue?

Which version of ParallelCluster you're using?
Which region?
Can you share the configuration file (i.e. `~/.parallelcluster/config`) without any credentials or personal data?

Thanks
