### ISSUE TITLE
cluster create fails with 2.8.0 (upgrading from 2.6.1)

### ISSUE THREAD

**Issue by rkarnik-kymera** [aws/aws-parallelcluster#1925]
AWS ParallelCluster 2.6.0

I get the following when I upgrade to 2.8.1 from 2.6.0.

Cluster creation failed.  Failed events:
  - AWS::EC2::SecurityGroup ComputeSecurityGroup Resource creation cancelled
  - AWS::CloudFormation::Stack EBSCfnStack Resource creation cancelled
  - AWS::SNS::Topic SNS Resource creation cancelled
  - AWS::IAM::Role RootRole Resource creation cancelled
  - AWS::EC2::PlacementGroup DynamicPlacementGroup Resource creation cancelled
  - AWS::EC2::NetworkInterface MasterENI Resource creation cancelled
  - AWS::DynamoDB::Table DynamoDBTable Resource creation cancelled
  - AWS::CloudFormation::Stack CloudWatchLogsSubstack Embedded stack arn:aws:cloudformation:us-east-1:423682823314:stack/parallelcluster-xxxxxxx-CloudWatchLogsSubstack-1OCYAGFTC23YK/9e6d7490-d78f-11ea-b793-0aac80a39b9b was not successfully created: The following resource(s) failed to create: [CloudWatchLogGroup].
Stack [parallelcluster-xxxxxxx-CloudWatchLogsSubstack-1OCYAGFTC23YK] does not exist

No changes made to config. I am not using custom AMIs.

**Comment by rkarnik-kymera** [comment]
Update: Creating a cw-log section with "enable = false" allowed me to start the cluster. Still, I would expect not to break existing configs when upgrading, and now I would really like cloudwath logging. :)

**Comment by enrico-usai** [comment]
Hi @rkarnik-kymera 
could you better explain what you mean with "upgrading from 2.6.1"? 

Is it possible to upgrade the cli with the `pip install aws-parallelcluster --upgrade` command but you cannot update an existing cluster created with a previous version of the cli.

I tried to execute the `pcluster update` command on a cluster created with 2.6.1 and I received the following message:
```
 C:\>pcluster update 2-6-1-test-cluster
Validating configuration file ...
Retrieving configuration from CloudFormation for cluster  2-6-1-test-cluster...
ERROR: The cluster  2-6-1-test-cluster was created with a different version of ParallelCluster: 2.6.1. Installed version is 2.8.1. Update operations may only be performed using the same ParallelCluster version used to create the cluster.
```
It means you cannot update (nor upgrade) a cluster created with an older version of the cli.

Could you explain the steps you did to be able to reproduce the issue?

Thanks

**Comment by rkarnik-kymera** [comment]
Sorry, I was not clear what I meant.

I had created this cluster a few months ago from an older laptop using 2.6.0. On my new laptop, I did the following:
1. Installed parallelcluster
`pip install aws-parallelcluster`
2. Tried to stop existing cluster.
`pip stop <clustername>`
Got error message about not being able to update cluster
3. Deleted existing cluster
`pip delete <clustername>`
Succeeded
4. Tried to recreate the cluster
`pip create -c <configfile> <clustername>`
Got the error message in my original report
5. Added a cw_log section to the config file
```
[cw_log <clustername>]
enable = false
retention_days = 7
```
6. Added a cw_log_settings line to the cluster section in the config file.
`cw_log_settings = <clustername>`
7. Created the cluster
`pcluster create <clustername>`

I was expecting step 4 to work to retain backwards compatibility of the config file. Now that I have things up again, how can I get Cloudwatch logging to work?

**Comment by demartinofra** [comment]
I think the problem is that you have a log group, having the same name as the new one you are trying to create, which was not properly deleted with a previous cluster.
ParallelCluster tries to create a log group which is `/aws/parallelcluster/$cluster-name` and in your case most likely it is failing because that loggroup already exists. Can you try to manually delete the loggroup from CloudWatch console and then recreate the cluster?

**Comment by rkarnik-kymera** [comment]
Yes, that was it, thanks! It was actually a log group I had set up for a pre-2.6.0 cluster.

Does the log group get deleted when I delete the cluster? How can I persist the logs between different cluster creations (same name)?

**Comment by enrico-usai** [comment]
@rkarnik-kymera thanks for the detailed explanation.

By default the log group is deleted at cluster deletion time. 
You can preserve it by passing the `--keep-logs` flag to the `pcluster delete` command (more details [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.delete.html)).

In any case we don't recommend to maintain the logs of a previous created cluster and create a new one with the same name, because the creation of the new one will fail saying that the CloudWatchLogGroup already exists.


Let us know if it helps.

**Comment by rkarnik-kymera** [comment]
Thank you @enrico-usai. Maybe in the future, creation of the CloudWatchLogGroup can be optional as well. Closing this issue for now.

**Comment by enrico-usai** [comment]
Hi @rkarnik-kymera 

Through the [enable](https://docs.aws.amazon.com/parallelcluster/latest/ug/cw-log-section.html) configuration parameter you can optionally disable the creation of the CloudWatch LogGroup.

Starting from 2.6.0 we decided to [enable CloudWatch integration by default](https://docs.aws.amazon.com/parallelcluster/latest/ug/cloudwatch-logs.html), it is the reason you had to insert `enable = false` in the configuration to prevent the CloudWatchLogGroup creation.

Let us know if it helps.
