### ISSUE TITLE
Cluster is not created 

### ISSUE THREAD

**Issue by armaneshaghi** [aws/aws-parallelcluster#1944]
Problem:

Creation step never finishes, the command line goes into "sulk mode" no compute nodes are created. (compute nodes are created if I do not use the `cluster_type = spot`) but cluster will not be ready to run jobs.

**Environment:**
 - AWS ParallelCluster / CfnCluster version [aws-parallelcluster-2.8.1]
 - OS: alinux2
 - Scheduler: SGE
 - Master instance type: c4.large
 - Compute instance type: c4.xlarg

**Bug description and how to reproduce:**
pcluster freezes on creation, in the following status:

`Status: MasterServerWaitCondition - CREATE_COMPLETE`

**Additional context:**
Config file

```
[aws]                                                                                                                                                                       
aws_region_name = eu-west-2

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
cluster_config_metadata = {"sections": {"cluster": ["default"], "scaling": ["default"], "vpc": ["default"]}}
key_name = x
base_os = alinux2
initial_queue_size = 2 
max_queue_size = 40
scheduler = sge 
vpc_settings = default
master_instance_type = c4.large
compute_instance_type = c4.xlarge

[vpc default]
.subnet removed
.VPC removed
use_public_ips = false
```

There is nothing remarkable in logs for cloud_init, sqswatcher and others. However, `/var/log/messages` shows:

```
Aug 15 16:59:59 ip-172-31-50-157 /ec2_dev_2_volid.py: Looking for dev /dev/sda1 in devmap {'/dev/xvda': {'DeviceName': '/dev/xvda', 'Ebs': {'AttachTime': datetime.datetime(2020, 8, 15, 16, 56, 5, tzinfo=tzlocal()), 'DeleteOnTermination': True, 'Status': 'attached', 'VolumeId': 'vol-09183311b40b73ccb'}}, '/dev/sdb': {'DeviceName': '/dev/sdb', 'Ebs': {'AttachTime': datetime.datetime(2020, 8, 15, 16, 58, 40, tzinfo=tzlocal()), 'DeleteOnTermination': False, 'Status': 'attached', 'VolumeId': 'vol-081ba0d10d68643bc'}}}
Aug 15 16:59:59 ip-172-31-50-157 udevd[1807]: timeout '/opt/parallelcluster/pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/python /sbin/ec2_dev_2_volid.py xvda1'
Aug 15 17:00:00 ip-172-31-50-157 udevd[1807]: timeout: killing '/opt/parallelcluster/pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/python /sbin/ec2_dev_2_volid.py xvda1' [5634]
Aug 15 17:00:00 ip-172-31-50-157 udevd[1807]: '/opt/parallelcluster/pyenv/versions/3.6.9/envs/cookbook_virtualenv/bin/python /sbin/ec2_dev_2_volid.py xvda1' [5634] terminated by signal 9 (Killed)
Aug 15 17:00:00 ip-172-31-50-157 udevd[1807]: timeout '/sbin/blkid -o udev -p /dev/xvda1'
```

See below for logs. Thanks in advance to anyone who can look into this. 

If I ssh to Master node:
```
$ qhost
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
```

**Comment by armaneshaghi** [comment]
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/5079418/cfn-init.log)
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/5079419/cfn-init-cmd.log)
[cloud-init-output.log](https://github.com/aws/aws-parallelcluster/files/5079420/cloud-init-output.log)
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/5079421/cloud-init.log)

**Comment by tilne** [comment]
Hi, Arman.

At first glance it looks like the issue was that the [spot_price](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#spot-price) set for the cluster was too low. If this is the case, the CLI isn't actually frozen, it's just that `pcluster create` waits for up to an hour for the compute fleet to finish being created. All of the other cluster resources finish creating, which means that there are no new stack events (which is what the command uses to update the status printed to stdout).

Did you set the `spot_price` parameter? I'm asking because I'm guessing the config you attached is missing some data considering `cluster_type = spot` is not present.

To confirm, you can do so via the autoscaling group section of the EC2 console or the AWS CLI. If you want to do so via the EC2 console, navigate to the 'Auto Scaling Groups' section via the side bar (it's at the very bottom). Then click on the cluster's ASG and navigate to the events tab. Here's a screenshot of what that page looks like for my cluster with failed scaling events due to too low of a spot price:
![Screen Shot 2020-08-17 at 5 14 14 PM](https://user-images.githubusercontent.com/55806862/90456191-213f9300-e0ad-11ea-818b-a0456677c33d.png)

Alternatively you can use the AWS CLI:
```
➜  aws autoscaling describe-scaling-activities --auto-scaling-group-name parallelcluster-spot-with-initial-computes-ComputeFleet-1FLT31UBWNTKE --region us-east-1
{
    "Activities": [
        {
            "ActivityId": "bde5cffb-9a94-7be2-c3c9-ff024184baf6",
            "AutoScalingGroupName": "parallelcluster-spot-with-initial-computes-ComputeFleet-1FLT31UBWNTKE",
            "Description": "Launching a new EC2 instance.  Status Reason: Your Spot request price of 0.01 is lower than the minimum required Spot request fulfillment price of 0.0727. Launching EC2 instance failed.",
            "Cause": "At 2020-08-18T00:09:53Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 1.",
            "StartTime": "2020-08-18T00:09:55.230Z",
            "EndTime": "2020-08-18T00:09:55Z",
            "StatusCode": "Failed",
            "StatusMessage": "Your Spot request price of 0.01 is lower than the minimum required Spot request fulfillment price of 0.0727. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"subnet-d43e0d88\",\"Availability Zone\":\"us-east-1b\"}"
        },
...
...
...
```

As for the ec2_dev_2_volid.py error message you pointed out from /var/log/messages, I was unable to reproduce that using a very similar configuration (albeit in us-east-1). Were there any differences between the configuration you provided above and what you used to create the cluster? In particular, did you use `custom_ami` or `template_url`?

**Comment by armaneshaghi** [comment]
Hi @tilne and thank you for looking into this. 

I thought to start from scratch and double check all my assumptions. This the config:

```
[aws]                                                                                                                                                                       
aws_region_name = eu-west-2

[global]
cluster_template = default
update_check = false
sanity_check = false

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = Removed
base_os = alinux2
scheduler = sge 
master_instance_type = c4.4xlarge
compute_instance_type = c4.4xlarge
cluster_type = spot
spot_price = 2.0 
initial_queue_size = 2 
maintain_initial_size = true
vpc_settings = default

[vpc default]
vpc_id = vpc-Removed
master_subnet_id = subnet-Removed
```
I have changed instances with the ones for which I have higher limits for number of instances, making sure I am not being held back by user-limits. 

1) spot_price: I changed this and the problem persists. In fact if I go for normal cluster (no spot_type) specified, same happens, meaning that the command line stays "Status: MasterServerWaitCondition - CREATE_COMPLETE".
2) I also tried increasing the spot_price up to 2 for instances with pricing history of 0.95 for on-demand use of c4.4xlarge. Also in the console I do not see any launched (and failed) spot requests.
3) Autoscaling group console has a status that stays in "updating capacity" for a long time. I have attached a scrennshot. 


![image](https://user-images.githubusercontent.com/4290297/90486347-b9329080-e130-11ea-81ae-91daa4c31f26.png)

Any hints would be gratefully appreciated.

**Comment by tilne** [comment]
Can you run the command `aws autoscaling describe-scaling-activities --auto-scaling-group-name ${AUTO_SCALING_GROUP_NAME} --region ${CLUSTER_REGION}` and paste the output here?

**Comment by armaneshaghi** [comment]
`aws autoscaling describe-scaling-activities --auto-scaling-group-name parallelcluster-helloworld-ComputeFleet-QYTF8Z54QK8J --region eu_west_2`

Which outputs:
```
{
    "Activities": [
        {
            "ActivityId": "9ed5d008-ff94-0b3a-bf41-a72d4f2581f0",
            "AutoScalingGroupName": "parallelcluster-helloworld-ComputeFleet-QYTF8Z54QK8J",
            "Description": "Launching a new EC2 instance.  Status Reason: There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Cause": "At 2020-08-18T15:46:11Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.",
            "StartTime": "2020-08-18T15:46:15.938Z",
            "EndTime": "2020-08-18T15:46:15Z",
            "StatusCode": "Failed",
            "StatusMessage": "There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"subnet-085761edd247da7b9\",\"Availability Zone\":\"eu-west-2c\"}"
        },
        {
            "ActivityId": "5625d008-fbbd-d50b-581c-5b8c634ab00e",
            "AutoScalingGroupName": "parallelcluster-helloworld-ComputeFleet-QYTF8Z54QK8J",
            "Description": "Launching a new EC2 instance.  Status Reason: There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Cause": "At 2020-08-18T15:45:08Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.",
            "StartTime": "2020-08-18T15:45:13.077Z",
            "EndTime": "2020-08-18T15:45:13Z",
            "StatusCode": "Failed",
            "StatusMessage": "There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"subnet-085761edd247da7b9\",\"Availability Zone\":\"eu-west-2c\"}"
        },
        {
            "ActivityId": "e6b5d008-f7e7-0c6d-ee28-e8cb02b7b2cf",
            "AutoScalingGroupName": "parallelcluster-helloworld-ComputeFleet-QYTF8Z54QK8J",
            "Description": "Launching a new EC2 instance.  Status Reason: There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Cause": "At 2020-08-18T15:44:05Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.",
            "StartTime": "2020-08-18T15:44:10.179Z",
            "EndTime": "2020-08-18T15:44:10Z",
            "StatusCode": "Failed",
            "StatusMessage": "There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"subnet-085761edd247da7b9\",\"Availability Zone\":\"eu-west-2c\"}"
        },
        {
            "ActivityId": "8315d008-f694-b127-564c-1a6c3b13f013",
            "AutoScalingGroupName": "parallelcluster-helloworld-ComputeFleet-QYTF8Z54QK8J",
            "Description": "Launching a new EC2 instance.  Status Reason: There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Cause": "At 2020-08-18T15:43:44Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.",
            "StartTime": "2020-08-18T15:43:48.524Z",
            "EndTime": "2020-08-18T15:43:48Z",
            "StatusCode": "Failed",
            "StatusMessage": "There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"subnet-085761edd247da7b9\",\"Availability Zone\":\"eu-west-2c\"}"
        },
        {
            "ActivityId": "aec5d008-f547-a04b-a362-69397dee00fc",
            "AutoScalingGroupName": "parallelcluster-helloworld-ComputeFleet-QYTF8Z54QK8J",
            "Description": "Launching a new EC2 instance.  Status Reason: There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Cause": "At 2020-08-18T15:43:22Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.",
            "StartTime": "2020-08-18T15:43:27.208Z",
            "EndTime": "2020-08-18T15:43:27Z",
            "StatusCode": "Failed",
            "StatusMessage": "There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"subnet-085761edd247da7b9\",\"Availability Zone\":\"eu-west-2c\"}"
        },
        {
            "ActivityId": "8535d008-f40e-d964-39b9-f99416426a98",
            "AutoScalingGroupName": "parallelcluster-helloworld-ComputeFleet-QYTF8Z54QK8J",
            "Description": "Launching a new EC2 instance.  Status Reason: There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Cause": "At 2020-08-18T15:43:01Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.",
            "StartTime": "2020-08-18T15:43:07.190Z",
            "EndTime": "2020-08-18T15:43:07Z",
            "StatusCode": "Failed",
            "StatusMessage": "There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"subnet-085761edd247da7b9\",\"Availability Zone\":\"eu-west-2c\"}"
        },
        {
            "ActivityId": "7465d008-f2bb-432e-cf56-6c9b3fe09380",
            "AutoScalingGroupName": "parallelcluster-helloworld-ComputeFleet-QYTF8Z54QK8J",
            "Description": "Launching a new EC2 instance.  Status Reason: There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Cause": "At 2020-08-18T15:42:37Z a user request update of AutoScalingGroup constraints to min: 2, max: 10, desired: 2 changing the desired capacity from 0 to 2.  At 2020-08-18T15:42:40Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.",
            "StartTime": "2020-08-18T15:42:45.456Z",
            "EndTime": "2020-08-18T15:42:45Z",
            "StatusCode": "Failed",
            "StatusMessage": "There is no Spot capacity available that matches your request. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"subnet-085761edd247da7b9\",\"Availability Zone\":\"eu-west-2c\"}"
        }
    ]
```

**Comment by tilne** [comment]
From [this document](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-spot-instance-insufficient-capacity/) it looks like the cause is a lack of spot capacity in the AZ that you're running in.

From internal tooling it looks like one of the three possible eu-west-2 AZs has very limited c4.4xlarge capacity. So you can first confirm whether or not the AZ you're attempting to launch compute nodes in is the one with low capacity for that instance type, and then if it is you can try launching instances in a different AZ.

### Identifying whether or not you're attempting to launch computes in the AZ with less available c4.4xlarge:
* Identify the subnet you're trying to launch compute nodes into. If it's specified in the `[vpc]` section pointed to by the cluster, it would be the value given for the `compute_subnet_id` parameter. If that parameter isn't specified it's the value of `master_subnet_id` from the same section.
* Run the following command, setting SUBNET_ID to the value obtained from the following step. If it outputs `euw2-az1` it's probably worth trying a different subnet.
```bash
aws ec2 describe-subnets --region eu-west-2 --subnet-id ${SUBNET_ID} --query 'Subnets[0].AvailabilityZoneId' --output text
```


### Identifying other AZs to try in eu-west-2
* The following command will output a list of subnets you might have better luck with, where VPC_ID is set to the value of the `vpc_id` from your configuration:
```bash
aws ec2 describe-subnets --region eu-west-2 --filters Name=availability-zone-id,Values=euw2-az2,euw2-az3 Name=vpc-id,Values=${VPC_ID} --query 'Subnets[].SubnetId'
```


By copying your config and attempting to launch compute nodes in the AZ with less capacity I was able to replicate your issue. By specifying a subnet from a different AZ in the same region I was able to resolve it and successfully launch compute nodes. Let me know if this works for you.

**Comment by armaneshaghi** [comment]
Thank you @tilne. You are spot-on in that the first command returns `euw2-z1`. The second command returns an empty string `[]` so I guess it means this AZ (or at least my VPC) strangely lacks suitable subnet-ids. I created a new VPC in another AZ (in eu-west-2) and the cluster was created successfully. 

Is there a way to request multiple alternatives for the master and compute nodes, so if one is missing another one can go ahead? Would, for example,`master_instance_type = c4.4xlarge, c5.xlarge, c5.2xlarge` work? Same question for `compute_instance_type`.

**Comment by tilne** [comment]
You can't currently specify multiple instance types for either of the parameters. We are currently working on a feature to enable the use of multiple different instance types for compute nodes.

I'll add a feature request for enabling the use of the `capacity-optimized` allocation strategy. It looks like it could be a valuable feature. Thank you for the link.

**Comment by armaneshaghi** [comment]
I think `capacity-optimized` can also reduce costs without affecting user experience. I am closing this issue but in case you would like to change it to a feature request please re-open.

**Comment by tilne** [comment]
I've recorded the feature request so we can keep this closed. Thanks again for submitting an issue.
