### ISSUE TITLE
At quota for number of parameters in main CFN stack 

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-parallelcluster#1953]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.8.1

**Bug description and how to reproduce:**
As of version 2.8.1, the main CFN stack uses 60 parameters, leaving no room for custom template to pass additional parameters. Would it be possible to reduce the number of parameters that pcluster itself uses? Do you have suggestions on how to pass additional parameters for custom templates?

I could refactor on my end, but that implies tracking changes both in pcluster and in the main CFN template, which I would prefer not to do.

**Comment by tilne** [comment]
Hi Joey.

Unfortunately I don't think getting rid any of the parameters is likely top happen in the short term. That said, the parameter limit is a pain point for us as well.

What is your use case? Can we help you find a good workaround?

**Comment by joeydumont** [comment]
I am currently deploying a preliminary CFN template to create some initial infrastructure for our cluster deployments, and pass the name of that template to the main template in order to its outputs. Say the template is called, parallelcluster-InitInfrastructure-Cluster1, then this name is passed to the main template, and I use its exports with `ImportValue: !Sub ${InitStackName}-ExportedValue1` and the like. 

I'm expanding that initial infrastructure a little now, and I'd like to pass other parameters as well.

Maybe the simplest thing is to use a standard naming scheme for the parameters, something that contains the cluster name (like the pcluster stack name derived from the cluster name), store everything in Parameter Store and pull the parameters that way.

Do you have other suggestions?

**Comment by tilne** [comment]
I think that sounds like a good solution.

It sounds like this could potentially be implemented using the [additional_cfn_template](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#additional-cfn-template) parameter along with a custom template. The issue of passing parameters to the InitInfrastructure stack (that aren't passed to the main CFN template) still remains, though. As you mentioned, the Parameter Store approach could be useful here. You can [specify parameters of type  AWS::SSM::Parameter::*](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-systems-manager-parameter/) or use [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html). (A downside of the second approach is that you have to specify a specific version for the parameters.)


Another option would be to add a lambda function resource to the main template. You could pass any extra parameters you'd like to use via the [extra_json](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#extra-json) `pcluster` configuration parameter, which could then be passed to the lambda. This solution is a bit less clean, but more flexible.

**Comment by joeydumont** [comment]
Actually, I kinda like the lambda solution. I think Landing Zone does something similar to pass parameters between its million moving parts.

Thanks for the feedback, I'll look into the best solution before upgrading to 2.8.

**Comment by demartinofra** [comment]
FYI: CloudFormation now supports up to 200 Parameters

**Comment by joeydumont** [comment]
@demartinofra Thanks for letting me know, this will make our job much easier!
