### ISSUE TITLE
Better options for spot instances 

### ISSUE THREAD

**Issue by sneimir** [aws/aws-parallelcluster#1963]
**Environment:**
all

**Bug description and how to reproduce:**
FEATURE request

**Additional context:**
Would be great to have an option (or even make that default behavior)  to switch to on demand if spot compute nodes fulfillment fails.

**Comment by sneimir** [comment]
compute fleet with a mix of on-demand/spot might be a solve..

**Comment by tilne** [comment]
Hi, sneimir.

> compute fleet with a mix of on-demand/spot might be a solve

I believe that a feature that will be part of the next release will provide this functionality.

As for the current version, you should be able to update a running cluster's config file's [cluster_type](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#cluster-type) value from `spot` to `ondemand` and then use `pcluster update` to apply the changes.

Here's what the update process looks like when I try it:
```
➜  pcluster update spot-to-ondemand
Validating configuration file ...
Retrieving configuration from CloudFormation for cluster spot-to-ondemand...
Found Configuration Changes:

#    parameter          old value    new value
---  -----------------  -----------  -----------
     [cluster default]
01   cluster_type       spot         ondemand

Validating configuration update...
Congratulations! The new configuration can be safely applied to your cluster.
Do you want to proceed with the update? - Y/N: Y
Updating: spot-to-ondemand
Calling update_stack
Status: parallelcluster-spot-to-ondemand - UPDATE_IN_PROGRESS
```

If you wanted to automate this, you could do so by periodically parsing the output from the shell command `aws autoscaling describe-scaling-activities --auto-scaling-group-name ${ASG_NAME} --region ${CLUSTER_REGION}` and, if for a certain period of time the output shows that the spot price is too low or there's too little spot capacity, you could then run `pcluster update` accordingly.

**Comment by demartinofra** [comment]
Starting from version 2.9.0, ParallelCluster introduced support for multiple queues and multiple instance types with Slurm scheduler: https://docs.aws.amazon.com/parallelcluster/latest/ug/queue-mode.html.

With this new feature you could configure an ondemand and a spot queue within the same cluster and build some custom automation in order to select the queue based on nodes availability. For the moment we do not plan to allow a single queue to contain both spot and ondemand capacity.
