### ISSUE TITLE
PFR: native docker support with SLURM

### ISSUE THREAD

**Issue by amrragab8080** [aws/aws-parallelcluster#2002]
To help facilitate running [ML]workloads compiled against various versions of libraries/SDKS with the benefit of native scheduling with SLURM it would be good to have native docker support in pcluster. I realize I could use Batch but as #1878 pointed out some of the integration is not available. 

Can also be useful to hydrate the compute nodes with a preset list of docker images so that workloads can get up and running quickly.

Currently solving this by creating a post-install script, but native integration would be beneficial

**Comment by ddeidda** [comment]
Hi. Thank you for reporting this.
We will evaluate your feature request to see if it can be added to our backlog. Please feel free also to share your post-install script as a contribution to help us checking better the changes you are proposing.
In the meanwhile, if you are having problems with bootstrap time due to the preinstall script, you may want to consider [creating a custom AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html) as a possible optimization.

**Comment by nstornetta** [comment]
@kniec: I know this is a pet topic of yours, so I wanted to make sure you had seen this.

**Comment by kniec** [comment]
Would like to get into more detail on that one. depending on which container engine you are using you can put the images on a shared filesystem, which might in turn just be hydrated by S3.

**Comment by amrragab8080** [comment]
The usecase is to bootstrap a compute and/or master node with docker image to hydrate from a registry. The parallelcluster feature would be some way to include registry credentials and docker images to pull from private registries. Or pull from Dockerhub or ECR-Public.

Having to put images on S3 would be an extra unnecessary step, if pcluster could use my auth creds to pull from the registry directly.

**Comment by amrragab8080** [comment]
The autoinstall script I built will install NVIDIA enroot/pyxis on pcluster. Pyxis is a slurm SPANK plugin which adds additional native container support (which works with docker) to srun.
```
[ec2-user@compute-dy-p4d24xlarge-2 ~]$ srun --container-image=centos grep PRETTY /etc/os-release
pyxis: importing docker image ...
PRETTY_NAME="CentOS Linux 8"
[ec2-user@compute-dy-p4d24xlarge-2 ~]$
```

**Comment by brannondorsey** [comment]
@amrragab8080 do you have a link to the autoinstall script you reference in https://github.com/aws/aws-parallelcluster/issues/2002#issuecomment-779372512? We're also trying to have docker support in a slurm-based parallelcluster via pyxis and are encountering issues installing, similar to those experienced in #3668.
