### ISSUE TITLE
 rename "master" instance => "primary" or "head" instance?

### ISSUE THREAD

**Issue by rsignell-usgs** [aws/aws-parallelcluster#2003]
Small point, but since we are all thinking about inclusivity these days... My daughter is an architect and they are now saying "primary bedroom" instead of "master bedroom" . Perhaps it would be good to follow suit and go with "primary" or "head" or something?

![2020-09-02_11-23-12](https://user-images.githubusercontent.com/1872600/92007526-107d5700-ed14-11ea-898e-ae51cdc25e95.png)

**Comment by ddeidda** [comment]
Hi Rich.

We believe your observation is absolutely relevant, so we will evaluate the technical implications of your proposal and see if it will be possible to replace the word "master" with a more neutral one. 
Thank you for your suggestion!

**Comment by elgalu** [comment]
what's the branch for the next major release? `develop`? does it contain all breaking changes already wrt this renaming?

**Comment by enrico-usai** [comment]
Hi Leo, 
the branch for the next major release is the [wip/pcluster3](https://github.com/aws/aws-parallelcluster/tree/wip/pcluster3) but it doesn't contain these changes yet.
For ParallelCluster 3.0 we're refactoring the entire CLI code so the code of the branch is still unstable.

**Comment by enrico-usai** [comment]
The task is completed, these patches will be part of the 3.0.0 release:
* https://github.com/aws/aws-parallelcluster/pull/2619
* https://github.com/aws/aws-parallelcluster-node/pull/289
* https://github.com/aws/aws-parallelcluster-cookbook/pull/918

**Comment by hanwen-pcluste** [comment]
ParallelCluster 3.0.0 has been released! Closing the issue because it has been addressed.
