### ISSUE TITLE
Cluster is not found

### ISSUE THREAD

**Issue by ameliatqy** [aws/aws-parallelcluster#2013]
**Environment:**
 - AWS ParallelCluster: aws-parallelcluster-2.8.0
 - Configuration file (i.e. ~/.parallelcluster/config) without any credentials or personal data.
```
[global]

cluster_template = ClusterToAccess-2b
update_check = true
sanity_check = true

[aws]
aws_region_name = us-west-2

[aliases]
ssh = ssh -i <pem_dir> {CFN_USER}@{MASTER_IP} {ARGS}

##
## AWS ParallelCluster templates
##

[cluster ClusterToAccess-2b]

key_name = turk1
tags = {"project" : "research"}
master_instance_type = m5.xlarge
compute_instance_type = p3.2xlarge
initial_queue_size = 0
max_queue_size = 1
maintain_initial_size = false
master_root_volume_size = 60
compute_root_volume_size = 60
base_os = ubuntu1804
custom_ami = ami-0a1eb7d7f39db3091
cluster_type = spot
# spot_price = 0.00  Defaults to spot price capped at at-demand
scheduler = slurm
extra_json = { "cluster" : { "cfn_scheduler_slots" : "1"} }

s3_read_write_resource =<dir>
post_install = <dir>
## 
## Settings References to other sections
##

ephemeral_dir = /scratch
encrypted_ephemeral = false
ebs_settings = ClusterToAccess-shared-2b
vpc_settings = public-us-west-2b

## VPC Settings (These define the set of possible settings, which are selected above in vpc_settings)
[vpc public-us-west-2b]
vpc_id = <vpc_id>
master_subnet_id = <master_subnet_id>
ssh_from = <ip>
additional_sg = <sg>

## First EBS Settings

[ebs ClusterToAccess-shared-2b]
shared_dir = shared
volume_type = gp2
ebs_volume_id = <volume_id>

```

**Bug description and how to reproduce:**
The main is that we cannot get into an existing cluster (it is clear that the cluster exists as other computers can access it/the stack is shown in CloudFormation). The command returns "ERROR: Stack with id ClusterToAccess does not exist" 

I am trying to get my colleague set up with parallel-cluster and get him to access an account I already created. Here is what we did on his new computer:

1. pip3 install awscli --upgrade --user
2. aws configure
3. pip3 install aws-parallelcluster==2.8.0 --upgrade --user

We try to update this cluster using `pcluster update ClusterToAccess` (we basically set the tags parameter above to tags={}) and it worked - the update went through.

But when we tried `pcluster list`, it was empty. We tried 'pcluster ssh ClusterToAccess' and the command returns "ERROR: Stack with id ClusterToAccess does not exist" .

Is it possible that we are missing something in setting up the parallel cluster? Why can we update the cluster but when we ssh in, we get a message that a cluster doesn't exists. We appreciate your help in advance!

**Comment by ddeidda** [comment]
Hi Amelia,

assuming that you and your colleague are using the same aws credentials, could it be that you are connecting to a different region? 

To double check you could try running:
```
pcluster list -r us-west-2
```
from your colleague's terminal.

**Comment by rexcsn** [comment]
Hi @ameliatqy 

Any update on this issue?

**Comment by ameliatqy** [comment]
> Hi @ameliatqy
> 
> Any update on this issue?

I apologize for the late reply. Yes the issue was resolved - it was the region problem as @ddeidda said. We stated the region when running `aws configure`, but that didn't work. So we changed the environment variable `AWS_DEFAULT_REGION` and it worked.
