### ISSUE TITLE
ParallelCluster v2.9.0 breaks on private subnet for master node

### ISSUE THREAD

**Issue by huffmabc** [aws/aws-parallelcluster#2040]
**Environment:**
 - AWS ParallelCluster v2.9.0

**Bug description and how to reproduce:**
The outputs for the 2.9.0 template seem to require a PublicIP.  So it breaks for a master node in a private subnet:
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack MasterServerSubstack Embedded stack arn:aws:cloudformation:us-east-1:12digitAccountID:stack/parallelcluster-abcluster-MasterServerSubstack-1AEXV65IDSB3P/5aabdfe0-f688-11ea-ba7f-0a63dd50faa5 was not successfully created: Attribute: PublicIp was not found for resource: i-07101206057f4b8c8
    - AWS::CloudFormation::Stack parallelcluster-abcluster-MasterServerSubstack-1AEXV65IDSB3P Attribute: PublicIp was not found for resource: i-07101206057f4b8c8

**Additional context:**
I am not using a proxy server, but my subnet does have access to the internet via a transit gateway and NAT gateways in another account.

**Comment by enrico-usai** [comment]
Hi @huffmabc 

You found a bug in the CloudFormation template used to create the Master Substack, on which we missed to evaluate if the MasterPublicIP exists when defining the Output. 

We are going to fix it, thanks for reporting this.

**Comment by enrico-usai** [comment]
Patch to fix the issue: https://github.com/aws/aws-parallelcluster/pull/2041

**Comment by enrico-usai** [comment]
Release 2.9.1 to fix this issue is out: https://github.com/aws/aws-parallelcluster/releases/tag/v2.9.1
