### ISSUE TITLE
instance type 'c5ad.12xlarge' not supported

### ISSUE THREAD

**Issue by rems0** [aws/aws-parallelcluster#2050]
**Environment:**
 - AWS ParallelCluster 2.9.1

**Bug description and how to reproduce:**
$ pcluster create -c /home/centos/.parallelcluster/config-2.9.1-v1 HR-11
Beginning cluster creation for cluster: HR-11
ERROR: The configuration parameter 'instance_type' generated the following errors:
The instance type 'c5ad.12xlarge' used for the 'instance_type' parameter is not supported by AWS ParallelCluster.

Why are c5ad.12xlarge instances not supported?

Kind regards,
Richard

**Comment by enrico-usai** [comment]
Hi @rems0 thanks for opening this.

The message means that we didn't tested yet ParallelCluster with this instance type.

In any case it should work, if you are using **slurm**.
You could try it by setting `sanity_check = false` in the `[global]` section.

I'm marking it as feature enhancement, to officially add support for the c5ad.* family.

**Comment by demartinofra** [comment]
This instance is going to be enabled in the upcoming release

**Comment by lukeseawalker** [comment]
Instance is now enabled on AWS ParallelCluster version 2.10.0
