### ISSUE TITLE
Default Slurmctl port range spans Slurmdb port and ExternalDbd port.

### ISSUE THREAD

**Issue by alexiswl** [aws/aws-parallelcluster#2051]
**Environment:**
 - AWS ParallelCluster / CfnCluster version:  aws-parallelcluster-2.9.1

**Bug description and how to reproduce:**

The latest SlurmConf file at `/opt/slurm/etc/slurm.conf` has the following ctld port range
```
SlurmctldPort=6817-6827
```

However the Slurmdb port and DbdPort operate on 6818 and 6819 respectively.

Both `/opt/slurm/sbin/slurmdbd` (to start the slurm database daemon) and `systemctl start slurmctld` can therefore not be run simultaneously or they'll error out. Running them with the `-D` command (foreground) shows this pretty clearly.

It is therefore not possible on the standard settings to connect to an RDS database as shown through the tutorial [here](https://aws.amazon.com/blogs/compute/enabling-job-accounting-for-hpc-with-aws-parallelcluster-and-amazon-rds/)

From [slurm.conf man page](https://slurm.schedmd.com/slurm.conf.html):
> SlurmctldPort
The port number that the Slurm controller, slurmctld, listens to for work. The default value is SLURMCTLD_PORT as established at system build time. If none is explicitly specified, it will be set to 6817. SlurmctldPort may also be configured to support a range of port numbers in order to accept larger bursts of incoming messages by specifying two numbers separated by a dash (e.g. SlurmctldPort=6817-6818). NOTE: Either slurmctld and slurmd daemons must not execute on the same nodes or the values of SlurmctldPort and SlurmdPort must be different.
Note: On Cray systems, Realm-Specific IP Addressing (RSIP) will automatically try to interact with anything opened on ports 8192-60000. Configure SlurmctldPort to use a port outside of the configured SrunPortRange and RSIP's port range.

**Comment by demartinofra** [comment]
Hi Alexis,

you are right in the fact that with 2.9 version we increased the number of ports used by Slurmctld in order to handle a bigger number of concurrent connections. And yes there is some overlapping with other default ports: the 6818 used by Slurmd can be ignored since `slurmd` does not run on the head node; regarding 6819 which is the default for slurmdbd you can simply change it by using a different port in `slurmdbd.conf` with `DbdPort`. If needed you can also change the ports used by Slurmctld without affecting the system.
In the next version we could change the ports for `SlurmctldPort` in order not to overlap with the default dbd port, but again you are free to change them in your cluster to support your custom setup.

Francesco

**Comment by alexiswl** [comment]
Thanks @demartinofra, I think it's important that those ports don't overlap.

After spinning up my instance (which starts wth slurmdb daemon on the master node  `/opt/slurm/sbin/slurmdbd` in the post-install script)

I then killed it running

```
$ ps -ef | grep slurmdbd
ec2-user  1755   863  0 16:01 pts/0    00:00:00 grep --color=auto slurmdbd
slurm     7674     1  0 11:33 ?        00:00:00 /opt/slurm/sbin/slurmdbd
$ sudo kill 7674
```

I then restarted the control service
```
$ sudo systemctl restart slurmctld
```

And then when trying to run sacct on the master node got
```
$ sacct -j2
sacct: error: slurm_persist_conn_open_without_init: failed to open persistent connection to ip-10-2-1-239:6819: Connection refused
sacct: error: slurmdbd: Sending PersistInit msg: Connection refused
sacct: error: Problem talking to the database: Connection refused
```

I can then restart the slurmdb daemon and slurm control daemon and successfully run `sacct -j2`

```
$ sudo /opt/slurm/sbin/slurmdbd
$ sudo systemctl restart slurmctld
sacct -j2
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode
------------ ---------- ---------- ---------- ---------- ---------- --------
2                  wrap    compute                     1    RUNNING      0:0
```

**Comment by demartinofra** [comment]
Hi Alexis,

sorry for the late reply. I'm not sure why you had to restart the daemons twice to make it work. What is the slurmdbd config you are setting before starting the daemon in the post-install script? Have you updated the DbdPort in the config?

**Comment by alexiswl** [comment]
I restarted it twice here to show the two scenarios, sorry if that was confusing.

The former was with running `sacct` with just the control service running on the master node.
The latter was running `sacct` with both. 

It shows that to run `sacct` on the head node, one needs both the control daemon and database daemon running simultaneously.

Yes, in the post installation script I switch the control port range to 6820 to 6830 to not conflict with the daemon.

**Comment by enrico-usai** [comment]
[2.10.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.10.0) release is out. Thanks for reporting this.
