### ISSUE TITLE
Stack not showing up with pcluster list

### ISSUE THREAD

**Issue by zadelman** [aws/aws-parallelcluster#2056]
**Environment:**
 - aws-parallelcluster-2.3.1

**Bug description and how to reproduce:**
Not sure this is a bug, but I'm looking for some insight into what may be going on.  I have one stack running in the us-west-1 region that I had started with pcluster back in February. It's up and running fine, I'm doing compute jobs on it, it shows up in the cloud formation stacks AWS console. The problem I'm having is that it's not showing up with the CLI.  When I type ``pcluster list`` all I'm seeing is another stack that I have running in us-east-2. I've tried to change regions using aws configure but I still can't get the pcluster command line to see the one running in us-west-1. 

I need to add a couple of users to this already running stack and I'm trying to follow your instructions for [Multi-user support](https://github.com/aws/aws-parallelcluster/wiki/MultiUser-Support). I can't figure out how to stop and then restart the stack if pcluster isn't listing it.

**Comment by zadelman** [comment]
I'm figuring this out, I need to use the -r flag:

``pcluster stop -c myconfig -r us-west-1 mycluster``

**Comment by enrico-usai** [comment]
Hi @zadelman 

The `pcluster` CLI uses by default the `aws_region_name` configured in the `[aws]` section of your configuraiton file.

To specify another region, as you already found, you need to pass the `--region|-r` flag or set the `AWS_DEFAULT_REGION` environment variable before executing the CLI command.

Thanks for describing how you solved your issue.
I'm going to close it.
