### ISSUE TITLE
Dead nodes still exist in SGE scheduler host list

### ISSUE THREAD

**Issue by sumedhjain** [aws/aws-parallelcluster#2057]
**Environment:**
 - AWS 2.6.1
 - OS: [alinux2]
 - Scheduler: [SGE]
 - Master instance type: [t2.micro]
 - Compute instance type: [m5.24xlarge and m5.metal] 
[jobwatcher.xlsx](https://github.com/aws/aws-parallelcluster/files/5244816/jobwatcher.xlsx)
[sqswatcher.xlsx](https://github.com/aws/aws-parallelcluster/files/5244817/sqswatcher.xlsx)

-ami used - ami-06c1b20396c5551f3

**Bug description and how to reproduce:**
A job is running, it is interrupted (although there is no such request from the user or auto-scaling group). And the job still remains in running status. The ghost/dead node does not leave even after deleting the job. 

PFA jobwatcher & sqswatcher from master node.

**Comment by lukeseawalker** [comment]
Hi @sumedhjain,
can you please post the followings:
* the pcluster configuration file used without any credentials or personal data.
* the output of the command `qstat -f -g dt -u '*'`

Thanks

**Comment by demartinofra** [comment]
Can you also provide the full content of jobwatcher and sqswatcher logs? The provided files seem to contain only the last part of the logs.

Most likely your use case corresponds to the Scenario 3 described here: https://docs.aws.amazon.com/parallelcluster/latest/ug/spot.html.
