### ISSUE TITLE
Error executing action `mount` on resource 'mount[/shared]'

### ISSUE THREAD

**Issue by soniagarden** [aws/aws-parallelcluster#206]
~10% chance of this error occurring when auto-scaling spins off new compute nodes. 
Any good way to avoid connection timed out?  Thanks!

    ================================================================================
    Error executing action `mount` on resource 'mount[/shared]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '32'
    ---- Begin output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-220-1-44.ec2.internal:/shared /shared ----
    STDOUT:
    STDERR: mount.nfs: Connection timed out
    ---- End output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-220-1-44.ec2.internal:/shared /shared ----
    Ran mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-220-1-44.ec2.internal:/shared /shared returned 32

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_compute_base_config.rb

     30: mount node['cfncluster']['cfn_shared_dir'] do
     31:   device "#{nfs_master}:#{node['cfncluster']['cfn_shared_dir']}"
     32:   fstype 'nfs'
     33:   options 'hard,intr,noatime,vers=3,_netdev'
     34:   action [:mount, :enable]
     35: end
     36:

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/cfncluster/recipes/_compute_base_config.rb:30:in `from_file'

    mount("/shared") do
      action [:mount, :enable]
      supports {:remount=>false}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      mount_point "/shared"
      device "ip-10-220-1-44.ec2.internal:/shared"
      device_type :device
      fsck_device "-"
      fstype "nfs"
      options "hard,intr,noatime,vers=3,_netdev"
      dump 0
      pass 2
      username nil
      password nil
      domain nil
      declared_type :mount
      cookbook_name "cfncluster"
      recipe_name "_compute_base_config"
    end

    Platform:
    ---------
    x86_64-linux

**Comment by mohanasudhan** [comment]
Can you elaborate the problem?

**Comment by soniagarden** [comment]
When lunching a cluster with --norollback, -nr, over time I observed about one out of 10 newly spin off compute nodes will have the above error message in /var/log/cfn-init.log, which is rather high failing rate.  Even if these instances were terminated soon after the build failure (if the cluster was launched without the --norollback option), the cost of paying for extra 1 hour per failure could become insignificant. 

My question is, why would there be "Connection timed out" when mounting the nfs drive?  Is there anything we can do to prevent this error?

**Comment by soniagarden** [comment]
The build failed instances caused by 
> mount.nfs: Connection timed out

were not terminated even when the cfncluster was launched without the "--norollback" flag.  Every week I have several "failed" instances just running for no reasons.  Any suggestions on how I could fix this?

**Comment by soniagarden** [comment]
Error in chef 

```
Generated at 2017-08-21 19:21:54 +0000
Mixlib::ShellOut::ShellCommandFailed: mount[/shared] (cfncluster::_compute_base_config line 30) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '32'
---- Begin output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-220-1-210.ec2.internal:/shared /shared ----
STDOUT:
STDERR: mount.nfs: Connection timed out
---- End output of mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-220-1-210.ec2.internal:/shared /shared ----
Ran mount -t nfs -o hard,intr,noatime,vers=3,_netdev ip-10-220-1-210.ec2.internal:/shared /shared returned 32
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/shell_out.rb:118:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/mount/mount.rb:115:in `mount_fs'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/mount.rb:47:in `block in action_mount'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/mount.rb:46:in `action_mount'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'

```

**Comment by bwbarrett** [comment]
@soniagarden, can you provide a bit more information about your setup?  Which version of CfnCluster are you using?  What instance type/size are you using for master and compute nodes?  How large is your cluster?

Your issue is that the compute nodes are not able to mount one of the filesystems exported by the master node.  Given that most of the compute nodes succeed, this does not look like an issue with NFS permissions, but is a timeout due either to the master instance itself being overloaded or the nfs server on the master being overloaded.  Without knowing more about your environment, it's hard to suggest next steps.

**Comment by soniagarden** [comment]
Thanks for the response @bwbarrett. 

I'm running a custom GPU cluster with cfncluster.  Here are some specific specs:
I use cfncluster (1.3.2) and Ubuntu 14.04.5 LTS custom AMI, which was built on top of the cfncluster Ubuntu 14.04.5 AMI with CUDA 8.0 installed.  Master instance is an m3.medium, only used to submit jobs to the grid engine, and some simple bash scripting.  The cluster contains up to 10 p2.xlarge compute nodes.  GE jobs are submitted based on the GPU slot so most of CPU on compute nodes are idle.  The filesystem failed to be mounted is the shared EBS, which is a 1GB gp2 volume (100/3000 IOPS) with post-installed script and a basic python environment (miniconda).  This /shared drive is mostly idle except when initiating new compute nodes.  

Thanks for any suggestions or tips in advance.

**Comment by mohanasudhan** [comment]
I am not sure about sporadic behaviour on nfs mount here. Can you try ebs-optimized instance type in master? Again i am not sure whats happening here, just throwing an idea to try. I look at nfs ubuntu failures I couldn't get any suggestion as it works most of the case. So try different instance type.

**Comment by mohanasudhan** [comment]
Do you still see this issue ? any updates here ?

**Comment by enrico-usai** [comment]
Hi @soniagarden 
we added [EFS](https://aws.amazon.com/efs) support with ParallelCluster 2.1.0 and the [FSx Lustre](https://aws.amazon.com/it/fsx/) support for Centos 7 with [ParallelCluster 2.2.1](https://github.com/aws/aws-parallelcluster/releases/tag/v2.2.1).

I think you could give it a try.
