### ISSUE TITLE
Problems with ParallelClusterUserPolicy in 2.9.1

### ISSUE THREAD

**Issue by mattsnell** [aws/aws-parallelcluster#2060]
Config: [config.txt](https://github.com/aws/aws-parallelcluster/files/5248975/config.txt)
Version:  ParallelCluster 2.9.1
Scheduler:  Slurm

I'm using the example "ParallelClusterUserPolicy using SGE, Slurm, or Torque" (https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html#parallelclusteruserpolicy) policy as a component in an instance role.  The instance is used to manage clusters and I've encountered some issues that prevent successful cluster deployment/destruction for slurm based clusters (SGE/Torque untested).  The problem began with 2.9.x.

To reproduce, create an IAM user or instance/profile with the policy referenced in the documentation, use the provided config (updated for your VPC/subnets/keys, etc), and attempt to create a cluster.  It should fail, the first error will explain that an S3 bucket cannot be created and as you correct each blocking error, other errors will become evident.  

Note: The cluster config file was created fresh with 'pcluster configure' to remove as many human variables as possible.

My understanding is that some new resources need to be created (a cluster resource bucket and related lambda functions) and other permissions are missing to allow for management (dynamodb:GetItem, lambda:GetFunction, route53:ListQueryLoggingConfigs, and route53:GetChange at a minimum).  I've included modified JSON objects below for review and inclusion in the documentation.  

- The NetworkingEasyConfig object adds "ec2:CreateRoute"
- The S3ResourcesBucket object replaces the S3Delete object in the ParallelClusterUserPolicy example
- The Lambda section is altogether new to the ParallelClusterUserPolicy example
- The DynamoDBModify object adds "dynamodb:GetItem", and also restricts the resource (was '*').  Somebody with more familiarity with the software should review the resource restriction, it seems reasonable but I don't have all of the context.  
- The CreateRoute53HostedZone and Route53HostedZones objects correct some errors and missing permissions I found in both the batch and slurm/sge/torque ParallelClusterUserPolicy examples.

----
        {
            "Sid": "NetworkingEasyConfig",
            "Action": [
                "ec2:CreateVpc",
                "ec2:CreateRoute",
                "ec2:ModifyVpcAttribute",
                "ec2:DescribeNatGateways",
                "ec2:CreateNatGateway",
                "ec2:DescribeInternetGateways",
                "ec2:CreateInternetGateway",
                "ec2:AttachInternetGateway",
                "ec2:DescribeRouteTables",
                "ec2:CreateRouteTable",
                "ec2:AssociateRouteTable",
                "ec2:CreateSubnet",
                "ec2:ModifySubnetAttribute"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Sid": "S3ResourcesBucket",
            "Action": [
                "s3:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::parallelcluster-*"
            ]
        },
        {
            "Sid": "Lambda",
            "Action": [
                "lambda:CreateFunction",
                "lambda:DeleteFunction",
                "lambda:GetFunction",
                "lambda:GetFunctionConfiguration",
                "lambda:InvokeFunction",
                "lambda:AddPermission",
                "lambda:RemovePermission"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:lambda:<REGION>:<AWS ACCOUNT ID>:function:parallelcluster-*",
                "arn:aws:lambda:<REGION>:<AWS ACCOUNT ID>:function:pcluster-*"
            ]
        },
        {
            "Sid": "DynamoDBModify",
            "Action": [
                "dynamodb:CreateTable",
                "dynamodb:DeleteTable",
                "dynamodb:PutItem",
                "dynamodb:Query",
                "dynamodb:GetItem",
                "dynamodb:TagResource"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:dynamodb:<REGION>:<AWS ACCOUNT ID>:table/parallelcluster-*"
        },
        {
            "Sid": "CreateRoute53HostedZone",
            "Action": [
                "route53:CreateHostedZone"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Sid": "Route53HostedZones",
            "Action": [
                "route53:ChangeResourceRecordSets",
                "route53:ChangeTagsForResource",
                "route53:DeleteHostedZone",
                "route53:GetChange",
                "route53:ListQueryLoggingConfigs",
                "route53:GetHostedZone",
                "route53:ListResourceRecordSets"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:route53:::change/*",
                "arn:aws:route53:::hostedzone/*",
                "arn:aws:route53:::healthcheck/*"
            ]
        }
----

I iterated on this a bit so a second set of eyes is more than welcome!

In other news, I'm having some problems with 'pcluster ssh <cluster>' when I deploy to the default VPC and my own custom VPC on 2.9.1 (the VPCs created by pcluster are fine, I will create a new issue if I can't figure it out).

**Comment by rexcsn** [comment]
Hi @mattsnell 

Thank you for pointing out the issue and providing your version of a new policy!

We were aware of the issue and we updated our documentations with new sets of policies here: https://docs.aws.amazon.com/parallelcluster/latest/ug/iam.html.
Please try our new policies and let us know if you have any question/concern.

Thank you!

**Comment by demartinofra** [comment]
I'm going to resolve this one since policies got updated a week ago. Feel free to reopen if you are still facing permission related issues.
