### ISSUE TITLE
Failure: Custom image creation failure with createami command

### ISSUE THREAD

**Issue by Shadabdyn** [aws/aws-parallelcluster#2062]
**Environment:**
 - AWS ParallelCluster  version - 2.8.1
 - Configuration file: (providing some basic informations)
[aws]
aws_region_name = us-west-2
[cluster default]
base_os = ubuntu1604
scheduler = sge
compute_instance_type = c5n.2xlarge
vpc_settings = default
max_queue_size = 25
master_root_volume_size = 100
compute_root_volume_size = 100

**Bug description and how to reproduce:**

When I am trying to create the custom AMI following this command `pcluster createami --ami-id ami-0dcafa3de487c128f --os ubuntu1604 --instance-type c5n.2xlarge`

Constantly I am getting the error related to Cookbook build_ami.sh command not found and this is the error output.

> Building AWS ParallelCluster AMI. This could take a while...
Base AMI ID: ami-0dcafa3de487c128f
Base AMI OS: ubuntu1604
Instance Type: c5n.2xlarge
Region: us-west-2
VPC ID: vpc-04b57061
Subnet ID: subnet-02697ed68c95d40fe
Template: https://us-west-2-aws-parallelcluster.s3.us-west-2.amazonaws.com/templates/aws-parallelcluster-2.8.1.cfn.json
Cookbook: https://us-west-2-aws-parallelcluster.s3.us-west-2.amazonaws.com/cookbooks/aws-parallelcluster-cookbook-2.8.1.tgz
Packer log: C:\Users\Shadab\AppData\Local\Temp\packer.log.20200922-153150.oy7uhobl
Failed to run C:\Users\Shadab\AppData\Local\Temp\tmppd2czz48\aws-parallelcluster-cookbook-2.8.1/amis/build_ami.sh --os ubuntu1604 --partition region --region us-west-2 --custom --arch x86_64
Command not found
No custom AMI 

Any ideas? Please let me know how to resolve this?
Thanks in advance!

Regards,
Shadab

**Comment by lukeseawalker** [comment]
Hi @Shadabdyn,
the `createami` command doesn't currently work on Windows. I'm going to open a ticket to improve the documentation.
To solve this, you can spin up a Linux EC2 instance and use the command from there.

**Comment by lukeseawalker** [comment]
I have to correct myself, cause It's already documented
https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.createami.html

**Comment by Shadabdyn** [comment]
Hi,

Thank you for response and valuable suggestions.

So, as you suggested, i have tried this command on EC2 instance, but it was not successful and recieved the error with exit status: 69.

Could you please look into it and help me to resolve it.

> pcluster createami --ami-id ami-0dcafa3******* --os ubuntu1604
Building AWS ParallelCluster AMI. This could take a while...
Base AMI ID: 0dcafa3*******
Base AMI OS: ubuntu1604
Instance Type: t2.xlarge
Region: us-west-2
VPC ID: vpc-010b33c6b87401697
Subnet ID: subnet-0725bf6e3a77c4929
Template: https://us-west-2-aws-parallelcluster.s3.us-west-2.amazonaws.com/templates/aws-parallelcluster-2.9.1.cfn.json 
Cookbook: https://us-west-2-aws-parallelcluster.s3.us-west-2.amazonaws.com/cookbooks/aws-parallelcluster-cookbook-2.9.1.tgz 
Packer log: /tmp/packer.log.20200924-164234.e6jjrzl1
Packer status: + main --os ubuntu1604 --partition region --region us-west-2 --custom --arcPacker status: + parse_options --os ubuntu1604 --partition region --region us-west-2 --cusPacker status: ++ dirname /tmp/tmpiaqlz07j/aws-parallelcluster-cookbook-2.9.1/amis/build_aPacker status: + cp -R /tmp/tmpiaqlz07j/aws-parallelcluster-cookbook-2.9.1/amis/../BerksfiPacker status: + packer build -color=false -var-file=/tmp/tmpiaqlz07j/aws-parallelcluster-Packer status: ==> custom-ubuntu1604: Prevalidating AMI Name: custom-ami-aws-parallelclustPacker status: ==> custom-ubuntu1604: Creating temporary keypair: packer_5f6ccc7c-bae3-a89Packer status: ==> custom-ubuntu1604: Creating temporary security group for this instance:Packer status: ==> custom-ubuntu1604: Authorizing access to port 22 from [0.0.0.0/0] in thPacker status: custom-ubuntu1604: Adding tag: "Name": "Packer Builder ami-0dcafa3de487c128Packer status: custom-ubuntu1604: Adding tag: "parallelcluster_version": "aws-parallelclusPacker Instance ID: i-0264e2c2da9456690
Packer status: ==> custom-ubuntu1604: Waiting for instance (i-0264e2c2da9456690) to becomePacker status: ==> custom-ubuntu1604: Provisioning with shell script: /tmp/packer-shell012Packer status: ==> custom-ubuntu1604: Provisioning with shell script: /tmp/packer-shell663Packer status: ==> custom-ubuntu1604: Provisioning step had errors: Running the cleanup prPacker status: Build 'custom-ubuntu1604' errored after 1 minute 6 seconds: Script exited wPacker status: --> custom-ubuntu1604: Script exited with non-zero exit status: 69.Allowed Packer status:  exit code 1
No custom AMI created

Thanks in advance!

Regards,
Shadab

**Comment by lukeseawalker** [comment]
Hi @lukeseawalker,
the error says `systemctl: No such file or directory`, meaning that it's not able to find the `systemctl` command which comes from [systemd](https://wiki.ubuntu.com/systemd) package. `systemd` is the default system and service manager in Ubuntu16.

My hypothesis here are:
* your starting AMI is not Ubuntu16, but an older version (`systemd` wasn't installed by default in older version)
* your starting AMI is Ubuntu16 but you have upgraded from an older version (`systemd` wasn't installed during the upgrade)
* your starting AMI is Ubuntu16 and you have uninstalled  `systemd` because you are using another system and service manager

Can you please double check your OS version and why `systemd` package is missing?

**Comment by Shadabdyn** [comment]
Hi,

As you mentioned, firstly I have verified the ubuntu version and found that it is Ubuntu1404 and that's why it doesn't have `systemd `package.

 I think it is not possible to create the cluster ami by taking the reference image AMI of ubuntu14 and base OS ubuntu16.

Let me know your views on it. I think I should create the fresh cluster custom AMI by taking the base parallel cluster AMI and compiling the required software and then using this image with custom_ami input in the config file.

Thanks & Regards,
Shadab

**Comment by lukeseawalker** [comment]
Hi @Shadabdyn,
I agree that what you described is the cleanest way to move forward.

Thanks,
L
