### ISSUE TITLE
Master server info is not available

### ISSUE THREAD

**Issue by acastanedam** [aws/aws-parallelcluster#2067]
- AWS ParallelCluster v2.9.1
 - Config. file:
 `[global]
cluster_template = default
sanity_check = true
update_check = true

[aws]
aws_region_name = eu-west-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
base_os = centos7
compute_root_volume_size = 150
custom_ami = ami-0d0d1718156ed1488
enable_intel_hpc_platform = false
key_name = my_key
master_instance_type = z1d.2xlarge
master_root_volume_size = 150
queue_settings = compute
scheduler = slurm
shared_dir = /shared
vpc_settings = public

[queue compute]
compute_resource_settings = default
compute_type = ondemand
disable_hyperthreading = true
enable_efa = false
placement_group = DYNAMIC

[compute_resource default]
initial_count = 1
instance_type = z1d.2xlarge
max_count = 1
min_count = 1

[vpc public]
vpc_id = vpc-1d72a978
master_subnet_id = subnet-b7cc5dd2
`
 - OS: centos7
 - Scheduler: slurm
 - Master instance type: z1d.2xlarge
 - Compute instance type: z1d.2xlarge

**Bug description and how to reproduce:**

After stopping the created cluster (master and compute node), it is
not possible to get information of the master, `pcluster instances`
prints a blank line and `pcluster status` prints:
`Status: CREATE_COMPLETE
Cannot retrieve master node status. Exiting...`

Thanks in advance,
Arcesio Castaneda

**Comment by lukeseawalker** [comment]
Hi @acastanedam,
thank you for reporting this.

**Comment by acastanedam** [comment]
Thanks @lukeseawlaker, now it is working (in the `develop`
branch). Unfortunately, I have another problem, when I try to start
the cluster, the master server does not pass the `Instance status
checks` and it is not reachable. If I create, just a single instance
(without `pcluster`), then after stopping, the restarting proceeds
without any problem. What could be the problem?, (should I report this
as a new issue?).
