### ISSUE TITLE
Slurm Perl API

### ISSUE THREAD

**Issue by rkarnik-kymera** [aws/aws-parallelcluster#2073]
**Environment:**
 - aws-parallelcluster-2.9.1

I am trying to install the slurmtop tool for monitoring job status. It requires the SLURM Perl API. Is this installed by default on aws-parallelcluster? It seems to built by default in Slurm installs.

**Comment by demartinofra** [comment]
Hi @rkarnik-kymera 

yes we should be installing perlapi as part of the `make install-contrib` step we perform when building Slurm. Are you facing specific issues?

For reference here is the script used to build and install Slurm: https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/recipes/slurm_install.rb#L56-L68

**Comment by rkarnik-kymera** [comment]
Thanks @demartinofra, I now see the built Perl modules at /opt/slurm/lib64/perl5. I was trying to build a Perl script that uses these, so just need to adjust @INCLUDE, I think.
