### ISSUE TITLE
Why S3 needed?

### ISSUE THREAD

**Issue by JeffNing** [aws/aws-parallelcluster#2077]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.9.1
 - OS: [e.g. alinux] CentOS 7
 - Scheduler: [e.g. SGE] SLURM
 - Master instance type: [e.g. m5.xlarge] t2.micro
 - Compute instance type: [e.g. c5.8xlarge] r4.8xlarge

**Bug description and how to reproduce:**
My configuration does NOT define any S3 bucket use, but the error shows this:
_Unable to create S3 bucket parallelcluster-jnsa236su0cc22n6.
Access Denied__

Here is my config file content:

[cluster datcluster]
vpc_settings = veracyte
base_os = centos7
cluster_type = ondemand
key_name = dat_user
ec2_iam_role = dat_ec2
master_instance_type = t2.micro
compute_instance_type = r4.8xlarge
initial_queue_size = 2
max_queue_size = 5
maintain_initial_size = false
scheduler = slurm
custom_ami = ami-0b37b8636efa15100
tags = {"Name" : "test-pcluster291", "owner" : "dat_user"}

**Additional context:**
Any other context about the problem. E.g.:
 - configuration file without any credentials or personal data.
 - pre/post-install scripts, if any
 - screenshots, if useful
 - if the cluster fails creation, please re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node
 - if you encounter scaling problems please attach `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node

**Comment by demartinofra** [comment]
Hi @JeffNing 

Starting from version 2.9, ParallelCluster automatically creates an S3 bucket as part of the cluster resources. The S3 bucket is needed to support the newly introduced features.
