### ISSUE TITLE
pcluster configure should allow the user to specify the zone

### ISSUE THREAD

**Issue by mark-cresset** [aws/aws-parallelcluster#2090]
When configuring parallelcluster and asking it to set up the VPC, would it be possible to specify the availability zone to use? For my use case I have an existing EBS volume I'd like to attach, so I need the VPC to be in that zone.

**Comment by demartinofra** [comment]
Hi Mark,

unfortunately this is not possible at the moment. I'm going to mark this as a feature request.

What you could do as a workaround is to reuse the same CloudFormation template used by ParallelCluster to create the subnets to create a new CloudFormation stack. That template accepts as input the AZ where to create the subnets.
You can find the template in the CloudFormation console after you let the pcluster configure create the networking for you or simply get it from https://us-east-1-aws-parallelcluster.s3.us-east-1.amazonaws.com/templates/networking/public-private-2.9.1.cfn.json

**Comment by briandobbins** [comment]
Just a minor comment to second this as a feature request.  We've worked around this by hand, but it's a lot less straightforward when providing tools to deploy clusters for non-technical end-users.  

For our application, we keep finding certain AZs are more limited than others in terms of the node availability we desire, so we have to 'fish' for other AZs.  Doing this via the launch options in a pcluster config would make things much simpler! 

If I understand things correctly, even better would be options for specifying an AZ ID, vs an AZ name, per the link below:
https://aws.amazon.com/premiumsupport/knowledge-center/vpc-map-cross-account-availability-zones/

(This would allow us to tell other users, "Oh, you're having problems in use1-az1?  Try use1-az3, that worked for us with an 80-node config just last week.)

**Comment by hanwen-pcluste** [comment]
This issue has been addressed by this [commit](https://github.com/aws/aws-parallelcluster/commit/b5e88d9123265eaa3cfce28596ed8f31f3804014)
It will be part of the 3.0.0 release.

**Comment by hanwen-pcluste** [comment]
ParallelCluster 3.0.0 has been released. Please try out the new `pcluster configure`. Cheers!
