### ISSUE TITLE
awsbatch not perfoming the multinode job on the spot compute instances

### ISSUE THREAD

**Issue by Shadabdyn** [aws/aws-parallelcluster#2098]
**Required Info:**
 - AWS ParallelCluster version -2.9.1

**Problem description and how to reproduce:**

I have created the **AWS Parallel cluster** with **AWS batch scheduler** and completed the tutorial multi-node job tutorial successfully as given the user guide. But when I tried to run the same tutorial with **cluster_type = spot** and **spot_bid_percentage = 85**, the job stays in the RUNNABLE state for the last four hours.

![image](https://user-images.githubusercontent.com/32924473/94708644-7506f280-0362-11eb-9b80-6a23d8b50c1f.png)

I have tried to figure out the reason why it is not running and found out that this statement from [aws batch user guide](https://docs.aws.amazon.com/batch/latest/userguide/multi-node-parallel-jobs.html).

![image](https://user-images.githubusercontent.com/32924473/94709234-23ab3300-0363-11eb-9658-be5ea005b2d1.png)

So, I just want to know is this the reason because of which my job is not running?

Please let me know how to form the spot cluster and perform successful jobs with the aws-batch scheduler.

Thanks & Regards,
Shadab

**Comment by demartinofra** [comment]
Hi @Shadabdyn 

Yes that's the reason why your job remains in a `RUNNABLE` state and is never executed. AWS Batch Multinode jobs cannot be executed in a Spot cluster which means you cannot specify a number of nodes greater than 1 (with the `-n` option) when `cluster_type = spot`.

If you need to run multinode jobs please use `cluster_type = ondemand`. While if you don't need to run MPI jobs spanning across multiple jobs than you can use single node or array jobs in a spot cluster.

**Comment by demartinofra** [comment]
We also updated the docs to call this out explicitly: https://docs.aws.amazon.com/parallelcluster/latest/ug/awsbatchcli.awsbsub.html

I'm going to resolve this one since the limitation you are facing is expected and is not something controlled by ParallelCluster. Feel free to reopen this one or a new one if you need further support.
