### ISSUE TITLE
ParallelCluster 2.9.x: compute nodes provisioning fails when using pre/post_install_args with double quotes

### ISSUE THREAD

**Issue by demartinofra** [aws/aws-parallelcluster#2101]
Affected versions: 2.9.0, 2.9.1

When using pre/post_install scripts, ParallelCluster offers the possibility to pass script arguments via post/pre_install_args options. While in previous versions you were allowed to use double quotes `"` to pass multiple script arguments as reported below, this functionality is currently broken and will cause a failure when launching the compute nodes

Example of a broken config:
```
post_install = https://mybucket.s3.amazonaws.com/myscript.sh
post_install_args = "R curl wget"
```

**Comment by demartinofra** [comment]
While we are working on a permanent fix that will be included in the next version of the product, as a workaround you can use single quotes `'`. 

```
post_install = https://mybucket.s3.amazonaws.com/myscript.sh
post_install_args = 'R curl wget'
```

Note that if you were relying on variables resolution (e.g. you were passing `"$PATH arg2"` as script args and expect $PATH to be resolved) this will not work with the proposed workaround and you'll need to handle this in the custom script.

**Comment by rexcsn** [comment]
Fix has been merged into develop and go out in the next pcluster release: https://github.com/aws/aws-parallelcluster/pull/2124

**Comment by enrico-usai** [comment]
[2.10.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.10.0) release is out.
