### ISSUE TITLE
ParallelCluster 2.9.x: cannot use capital letters in queue names

### ISSUE THREAD

**Issue by demartinofra** [aws/aws-parallelcluster#2102]
Affected versions: 2.9.0, 2.9.1

When creating a Slurm cluster and selecting a queue name that has capital letters in it the created cluster will not be able to provision compute nodes.
Capital letters are not allowed in queue names but, due to a bug in the CLI validation logic, they are not correctly rejected when creating a cluster.

As correctly reported in ParallelCluster [docs](https://docs.aws.amazon.com/parallelcluster/latest/ug/queue-section.html):
> queue-name must start with a lowercase letter, contain no more than 30 characters, and only contain lowercase letters, numbers, and hyphens (-).

**Comment by demartinofra** [comment]
Issue has been addressed as part of https://github.com/aws/aws-parallelcluster/pull/2096

**Comment by enrico-usai** [comment]
[2.10.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.10.0) release is out.
