### ISSUE TITLE
`pcluster createami` breaks in regions without t2.micro instances

### ISSUE THREAD

**Issue by tilne** [aws/aws-parallelcluster#2120]
**Bug description**
Running the command `pcluster createami -r ${REGION}` using a region that does not have t2.micro instances will result in the following error:
```
(develop) ❯ pcluster createami -r eu-north-1 -os centos7 -ai ami-0245ac58f1f766d43
Building AWS ParallelCluster AMI. This could take a while...
ERROR: Error when calling DescribeInstanceTypes for instances t2.xlarge: The following supplied instance types do not exist: [t2.xlarge]
```

**How to reproduce the bug**
Run `pcluster createami -r ${REGION}` using a region that does not have t2.micro instances.

Thus far, the issue is known to affect eu-north-1 and us-gov-east-1.

**Affected Versions**
This bug affects versions 2.8.0 and later.

**Workarounds**
* Set `master_instance_type` in the default config file's default `[cluster]` section to an instance type that's available in the region.
* Build AMIs in a different region and copy them to the desired region afterwards.

**Comment by rexcsn** [comment]
#2132 addresses this bug, and will be included in the next release

**Comment by enrico-usai** [comment]
[2.10.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.10.0) release is out.
