### ISSUE TITLE
Enabling slurm sview and smap 

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#213]
Hi,

I am trying to get slurm sview and smap working. I have a custom centos6 AMI with all the libraries that are needed for my application. I am using slurm tools that come as default using cfncluster. Could you provide help on adding sview/smap?

Thanks
Santi

**Comment by demartinofra** [comment]
I'm resolving this since it appears to be a very old issue we missed for some reason. If this request is still valid feel free to re-open so that we can take a look
