### ISSUE TITLE
[Feature Request] Expose AutoImportPolicy for fsx filesystems

### ISSUE THREAD

**Issue by cread** [aws/aws-parallelcluster#2157]
Please can you expose the `AutoImportPolicy` parameter of [CreateFilesystemLustreConfiguration](https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystemLustreConfiguration.html) as an option in the `[fsx ]` section?

**Comment by enrico-usai** [comment]
Hi Chris, we already implemented it, see https://github.com/aws/aws-parallelcluster/pull/2086

It is already merged in develop. It will be part of the next release.

**Comment by enrico-usai** [comment]
[2.10.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.10.0) release is out.
