### ISSUE TITLE
Unable to start P3.8xlarge as compute instance

### ISSUE THREAD

**Issue by ybc1991** [aws/aws-parallelcluster#2164]
- AWS ParallelCluster version [e.g. 2.9.0]: 2.9.0
 - Cluster configuration:
   [compute_resource default]
    instance_type = p3.8xlarge
    initial_count = 2
    min_count = 0
    max_count = 4

    [ebs default]
    shared_dir = shared
    volume_type = st1
    volume_size = 500

    [cluster default]
    base_os = ubuntu1804
    scheduler = slurm
    master_instance_type = p3.2xlarge
    vpc_settings = default
    ebs_settings = default
    queue_settings = compute
    compute_root_volume_size = 64
    master_root_volume_size = 64

 - Cluster name: BluefogGPU
 - [Optional] Arn of the cluster CloudFormation main stack:

**Bug description and how to reproduce:**
The compute nodes of P3.8xlarge are never been able to be allocated. 
If set initial_count =0, the creation is able to finish. But after ssh, `scalloc -N 2` first shows ok. But after 1-2 seconds, 
it will report node fail and revoke the job.

Interestingly, if I switch to p3.2xlarge as compute node. Everything works

**If you are reporting issues about cluster creation failure or node failure:**

Attached:
* From Head node: 
[ip-172-31-48-87.i-02ea8319b36b507c5.cloud-init.txt](https://github.com/aws/aws-parallelcluster/files/5420878/ip-172-31-48-87.i-02ea8319b36b507c5.cloud-init.txt)
[ip-172-31-48-87.i-02ea8319b36b507c5.chef-client.txt](https://github.com/aws/aws-parallelcluster/files/5420879/ip-172-31-48-87.i-02ea8319b36b507c5.chef-client.txt)

Since compute node is never up, so nothing to attach.

**Comment by demartinofra** [comment]
Hi @ybc1991 

at first sight it looks like the nodes cannot be launched due to either capacity issues or account limits. Can you look at the error messages from `/var/log/parallelcluster/slurm_resume.log` and `/var/log/parallelcluster/clustermgtd`? Feel free to attache them to the issue so we can take a look as well.

Thanks,
Francesco

**Comment by ybc1991** [comment]
Thank you for replying. Yeah, I found the reason, VcpuLimitExceeded.

ERROR - Encountered exception when launching instances for nodes (x2) ['compute-dy-p38xlarge-1', 'compute-dy-p38xlarge-2']: An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 32 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.

So because P3.8xlarge/16xlarge has 32/64 vCPU. If I understand correct, this limitation should be aws account setting and nothing related with aws-parallelcluster, right?

**Comment by enrico-usai** [comment]
Hi YBC,
yes, that's correct. 

It doesn't depend by ParallelCluster, you can request an increase of the limits by following the [provided link](http://aws.amazon.com/contact-us/ec2-request).
This [guide](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-on-demand-instance-vcpu-increase/) can help you for the calculation.

I'm going to close this issue feel free to answer or open a new one if you have more questions.
