### ISSUE TITLE
Feature Request: Spot Block Duration

### ISSUE THREAD

**Issue by dhawalkp** [aws/aws-parallelcluster#2171]
If you are reporting an issue with AWS Parallelcluster / CfnCluster please make sure to add the following data in order to facilitate the root cause detection:

**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 2.9.0

```ini
[aws]
aws_region_name = us-west-2

[cluster default]
key_name = <redacted>
vpc_settings = cfncluster
base_os = alinux
scheduler = sge

initial_queue_size = 0
max_queue_size = 10


maintain_initial_size = false

placement = cluster
placement_group = DYNAMIC

master_instance_type = c4.xlarge
compute_instance_type = c4.8xlarge

#master_instance_type = t2.micro
#compute_instance_type = t2.micro
cluster_type = spot
#cluster_type = ondemand
ebs_settings = custom 


post_install = <redacted>
extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }
[ebs custom]
shared_dir = shared
volume_type = st1
volume_size = 500
#ebs_snapshot_id = <redacted>
#ebs_snapshot_id = <redacted>
ebs_snapshot_id = <redacted>
[vpc cfncluster]
use_public_ips = false
#vpc_id = <redacted>
#master_subnet_id = <redacted>
vpc_security_group_id = <redacted>
vpc_id = <redacted>
master_subnet_id = <redacted>
#master_subnet_id = <redacted>
[global]
cluster_template = default
update_check = true
sanity_check = true
```

## Feature Request
I am trying to change the ASG Settings for ParallelCluster via pcluster config and add spot block duration (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#fixed-duration-spot-instances) which basically allows the cluster to request spot instances for fixed duration w/o interruptions. I do not see any pcluster config for that where I can set the value of this parameter. Since ASG is managed by ParallelCluster in this case, how can we provide this addnl parameter to ASG? The scheduler is sge.

**Comment by lukeseawalker** [comment]
Hi @dhawalkp,
setting Spot block duration is currently unsupported.
Before accepting this as feature enhancement, we would like to understand how to support this feature in ParallelCluster. 
Reporting what was already written [here](https://github.com/aws/aws-parallelcluster/pull/1496#issuecomment-559428225) reusing or sharing a spot node among different jobs with a given block duration might be somehow misleading and result in unexpected termination of nodes.

**Comment by dhawalkp** [comment]
Thanks @lukeseawalker ! I read the concern and I understand that! So what are our next steps?

**Comment by tilne** [comment]
Hey, @dhawalkp .

We are taking the feature into consideration and evaluating it against other committed projects. Unfortunately, this means that we're unlikely to implement this feature in the immediate future.

If you'd like to use this functionality immediately, it will require using a customized version of ParallelCluster. Is that an option you'd be interested in?

**Comment by enrico-usai** [comment]
From https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#fixed-duration-spot-instances
Spot Instances with a defined duration (also known as Spot blocks) are no longer available to new customers from July 1, 2021. For customers who have previously used the feature, we will continue to support Spot Instances with a defined duration until December 31, 2022.
