### ISSUE TITLE
ParallelCluster >2.8 ARM Alinux2: sqswatcher not starting when using AMI created using `createami` command

### ISSUE THREAD

**Issue by lukeseawalker** [aws/aws-parallelcluster#2187]
Affected version: >2.8.0
Affected architecture: ARM
Affected OS: Alinux2

When creating cluster with AMI created using `createami` command, sqswatcher is not able to start.
Root cause is that `cryptography` package, installed as dependency of python package `paramiko`, dropped support for OpenSSL 1.0.2, see [here](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#32---2020-10-25)

Workaround is, in case custom AMI is needed, to modify an AWS ParallelCluster AMI instead of using `createami` command, see [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html).

**Comment by demartinofra** [comment]
Issue fixed by https://github.com/aws/aws-parallelcluster-cookbook/pull/791.

**Comment by enrico-usai** [comment]
[2.10.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.10.0) release is out.
