### ISSUE TITLE
Using ParallelCluster from Lambda

### ISSUE THREAD

**Issue by calebwin** [aws/aws-parallelcluster#2237]
Has anyone used ParallelCluster from Lambda?

It would be great to hear anyone's input on experience with this or thoughts on how feasible this would be.

**Comment by nstornetta** [comment]
@calebwin: Could you share any more details about what it is that you have in mind? 

My first reaction is to think that what you're describing could be similar to what's described by this series of blog posts demonstrating how to use ParallelCluster with a serverless API: 
1. https://aws.amazon.com/blogs/compute/using-aws-parallelcluster-with-a-serverless-api/
2. https://aws.amazon.com/blogs/opensource/aws-api-gateway-hpc-job-submission/
3. https://aws.amazon.com/blogs/compute/using-aws-parallelcluster-serverless-api-for-aws-batch/

This is an approach that we have seen several customers take towards how they run ParallelCluster in their environments.

**Comment by calebwin** [comment]
Thank you for the response. We want to be able to do the following from an AWS Lambda function:

- Create and delete clusters
- Programmatically SSH into the cluster to launch jobs (using `subprocess.run` from Python)
- Use ParallelCluster commands to do the above using cluster resources in a _different_ AWS account

The blog posts you shared definitely look promising. If I'm understanding correctly, we can use SAM to do the deployment of the ParallelCluster Python scripts/binary to the Lambda functions. Is that correct? Would SAM also allow us to more easily install something large like the interpreter for Julia [1] (the Julia runtime is fairly large) on deployed Lambda functions?

[1] https://discourse.julialang.org/t/creating-a-custom-julia-aws-layer-runtime/18166/17

**Comment by nstornetta** [comment]
As far as your first 2 bullet points go, yes, both of those use cases are covered and detailed as part of the series above. Your third bullet point, while not covered explicitly, is something that I believe would also be possible to do using the same or similar setup.

In response to your last question I am not sure. I am not familiar enough with SAM to say whether it makes it possible to architect around the limitations described on file size upload at the link you've shared. I did some researching myself to try and understand how others may have addressed the same problem and was unable to find clear answers. I've also passed this information along to the AWS Lambda team.

**Comment by calebwin** [comment]
Thanks, Nathan. Appreciate your help and it would be great to get clarity from the team on whether SAM can help get around the size restrictions.

**Comment by enrico-usai** [comment]
Hi @Caleb 

to get around the size restrictions you should have different ways:
* [S3 for the zip archive](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html)
* [Lambda Layer](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html)
* [Use EFS with Lambda](https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/)
* [Lambda Container Image](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html)

I looked ad the provided link for Julia and it seems they are using the Layer approach. In this case the total unzipped size of the function and all layers can't exceed the unzipped deployment package size limit of 250 MB. See [Lambda quotas](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html) for all the details.

Worth to share also "[Choosing between AWS Lambda data storage options in web apps](https://aws.amazon.com/blogs/compute/choosing-between-aws-lambda-data-storage-options-in-web-apps/)" blog post.

Let us know if it helps.

**Comment by calebwin** [comment]
Thanks, @enrico-usai! Those look very useful and it looks like with a container image, I might be able to get around the 250 MB restriction with up to 10 GB of total space for the image?

**Comment by enrico-usai** [comment]
Hi Caleb,
I personally never tested it but yes, according with the documentation, Lambda supports images up to 10 GB in size.
