### ISSUE TITLE
--tags not inherited to compute nodes, just master nodes (Feature Request)

### ISSUE THREAD

**Issue by alexiswl** [aws/aws-parallelcluster#2247]
We use the `--tags` parameter when running `pcluster create` to ensure that all of our instances have an identifiable owner or service user associated with them.  

While the master instance id inherits the tags set by the `pcluster create` cli, the compute nodes do not.  

Although this would be technically possible to add through the pre-install/post-install with some messy `jq` logic, 
can we request that `--tags` is inherited by both the master and any compute nodes that are launched throughout the duration of the cluster?

**Comment by brainstorm** [comment]
Indeed, for billing purposes (among others) this can help a lot.

**Comment by ddeidda** [comment]
@alexiswl 

Your feature request should already be satisfied by [this patch](https://github.com/aws/aws-parallelcluster/pull/2113/files). The new behavior will be supported by the next version of ParallelCluster. Thanks for your contribution!

**Comment by demartinofra** [comment]
Duplicate of https://github.com/aws/aws-parallelcluster/issues/2100. The linked issue also contains a temporary workaround while this gets addressed in the upcoming release
