### ISSUE TITLE
disable_cluster_dns not working for ParallelCluster 2.10.0

### ISSUE THREAD

**Issue by huffmabc** [aws/aws-parallelcluster#2263]
Trying to create a new cluster with ParallelCluster 2.10.0 fails with:
`
(pcluster-2.10.0) [user@server ~]$ pcluster version
2.10.0
(pcluster-2.10.0) [user@server ~]$ pcluster create bchtest
Beginning cluster creation for cluster: bchtest
ERROR: The configuration parameter 'disable_cluster_dns' is not allowed in the [cluster default] section
`

According to the documentation that parameter is supposed to go in the cluster section, so this appears to be a bug.

[config_sanitized.txt](https://github.com/aws/aws-parallelcluster/files/5591714/config_sanitized.txt)

Regards,
Brian

**Comment by lukeseawalker** [comment]
Hi @huffmabc,
while I look into this, please move the `compute_instance_type` value under a [compute_resource](https://docs.aws.amazon.com/parallelcluster/latest/ug/compute-resource-section.html) section, linked to the cluster section through a [queue](https://docs.aws.amazon.com/parallelcluster/latest/ug/queue-section.html) section, e.g.

```
[cluster default]
queue_setting = q1
...

[queue q1]
compute_resource_settings = cr1

[compute_resource cr1]
instance_type = t3.small
```

**Comment by huffmabc** [comment]
Done.  I'm in the process of upgrading from 2.8.1...

The error still occurs for the disable_cluster_dns parameter.

**Comment by lukeseawalker** [comment]
can you please post the modified configuration?

Alternatively, do the following steps:
* remove the `disable_cluster_dns` parameter from the original configuration
* convert the configuration into the new format using the command `pcluster-config convert -c original_config -o new_config`
* add back the `disable_cluster_dns` parameter into the `new_config`

**Comment by huffmabc** [comment]
I guess I must have still had something wrong in my config.  I did the convert, added the disable_cluster_dns back in and now it's working.

Thank you.
