### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by mk4-eyen** [aws/aws-parallelcluster#2267]
Are there any plans or is there a timeline for Ubuntu 20.04 support as base_os for ParallelCluster? We have a software designed and tested on Ubuntu 20.04 which we would like to run in a cluster, so we would like to know if we would be wasting our time backporting it to Ubuntu 18.04.

Best regards
Karel Maděra

**Comment by lukeseawalker** [comment]
Hi @mk4-eyen,
thank you for your interest.
At the moment we do not have a timeline for Ubuntu 20 support.
I'll keep the issue open as feature request.

Thanks,
L

**Comment by asford** [comment]
This appears to be addressed in https://github.com/aws/aws-parallelcluster/pull/2607 and https://github.com/aws/aws-parallelcluster/pull/2620

@lukeseawalker Is there a rough timeline for a release of this on the 2.x series?

**Comment by hanwen-pcluste** [comment]
Ubuntu 20.04 has been supported by ParallelCluster.

Thank you,
Hanwen

**Comment by rexcsn** [comment]
pcluster v2.11.0 is released, which adds support for Ubuntu 20.04.
Please let us know if you have any question, thanks!
