### ISSUE TITLE
Providing a S3 bucket as a default bucket while creating the Cluster with SLURM scheduler

### ISSUE THREAD

**Issue by Shadabdyn** [aws/aws-parallelcluster#2279]
**Required Info:**
 - AWS ParallelCluster version [2.9.1]
 - Scheduler: SLURM

**Bug description and how to reproduce:**
Actually Its not a bug. While creating the Cluster with SLURM scheduler, it creates a S3 bucket every time and automatically get deleted if we delete the cluster. But it is observed that if we exceed the limit of the buckets in s3 account it wont create the cluster.

So, we are thinking to provide the a fixed S3 bucket as a default s3 bucket that can be used by the SLURM scheduler to create the cluster. Because we already have a limit of 1000 buckets in our account.

Can you please help me with this and provide your valuable suggestions or comments to handle this issue very effectively.

Thanks in advance !!

Regards,
Shadab

**Comment by lukeseawalker** [comment]
Hi @Shadabdyn,
this has been added in [version 2.10.0](https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.md#2100):
```
Add cluster_resource_bucket parameter under cluster section to allow the user to specify an existing S3 bucket.
```
Official doc [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#cluster-resource-bucket-section)
