### ISSUE TITLE
Slower NFS connection to compute nodes?

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#229]
I am using cfncluster to create a cluster, create a shared EBS volume and attach it to compute nodes. I have tried gp2 (100GB and 500GB disk sizes) and st1 (500GB). I am seeing significant deterioration in performance of data access. On master node, I am able to read files 30x faster than on compute nodes. This wasn't the case before. Could you give any pointers in resolving this problem?

```
master_instance_type = m4.xlarge
compute_instance_type = m4.xlarge
initial_queue_size = 4
max_queue_size = 10
maintain_initial_size = true
placement_group = DYNAMIC
master_root_volume_size = 100
compute_root_volume_size = 100
base_os = ubuntu1604
ebs_settings = custom
scheduler = slurm
```

Thanks!

**Comment by mohanasudhan** [comment]
I have couple of questions 
1. Can you share your custom ebs_settings ? are you using volume_iops in your ebs setting?
2. Are you using custom ami? what's the nfs version in your ami?
3. use tools like dd or fio to test i/o performance metrics
4. finally can you share your master instance id ? we like to pull in few extra information from their

**Comment by adavanisanti** [comment]
1. custom_ebs settings

```
[ebs custom]
volume_type = st1
volume_size = 500
```
I have also tried with gp2 and volume_size 100 and 500. 
I am not settings volume_iops assuming that is relevant only for volume_type io1

2. Yes, I am using custom ami created from ubuntu1604 cfncluster ami (ami-c4b1b8bd). I have not made any changes to nfs version.

3. I will try those tools.
4. Master instance id: i-0293cdad3228c5814

**Comment by adavanisanti** [comment]
I ran a few experiments using dd with different file sizes and I see that the compute node takes longer compared to the master node.

Master
```
time dd if=/dev/zero of=/shared/ddtxt/log bs=32k count=128k
131072+0 records in
131072+0 records out
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 14.9454 s, 287 MB/s

real	0m14.946s
user	0m0.024s
sys	0m2.636s
```

Compute
```
time dd if=/dev/zero of=/shared/ddtxt/log bs=32k count=128k
131072+0 records in
131072+0 records out
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 65.9755 s, 65.1 MB/s

real	1m5.977s
user	0m0.012s
sys	0m2.532s
```

Compute
```
ubuntu@ip-172-31-22-8:~$ time dd if=/dev/zero of=/shared/ddtxt/log bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 32.3941 s, 66.3 MB/s

real	0m32.396s
user	0m0.024s
sys	0m1.560s
ubuntu@ip-172-31-22-8:~$ rm /shared/ddtxt/log
ubuntu@ip-172-31-22-8:~$ exit
logout
```
Master
```
Connection to ip-172-31-22-8 closed.
ubuntu@ip-172-31-21-135:~$ time dd if=/dev/zero of=/shared/ddtxt/log bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 1.30013 s, 1.7 GB/s

real	0m1.301s
user	0m0.016s
sys	0m1.280s
ubuntu@ip-172-31-21-135:~$
```

Sometimes I see that the rate on compute node is higher but it is not consistent. Let me know if this is expected. Is EFS the storage to use instead of EBS if I want the compute nodes to have similar read rate as the master node?

**Comment by adavanisanti** [comment]
@mohanasudhan I ran a few more experiments with different compute EC2 types.

Command run 
```
time dd if=/dev/zero of=/shared/ddtxt/log bs=16k count=128k
131072+0 records in
131072+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied,
```
On Master nodes, it takes ~ 1.2 seconds and at a rate of 1.6-1.8GB/s

I am reporting the total time and rate in 

| m4.xlarge | m4.2xlarge  | m4.10xlarge | c4.2xlarge |
| ---------- | ----------- | ------------- | ---------- |
| 32.28 (66.3MB/s) | 27.06 (79.04 MB/s) | 14.98 (143MB/s) | 17.225 (126 MB/s) | 

Is this difference in rate expected? Also, will an upgrade to nfs version 4 help in getting comparable read times between master & compute?

Thanks
Santi

**Comment by adavanisanti** [comment]
@mohanasudhan I tried using nfs4 on one of the compute nodes and I see the same rate. 

Is this a typical speed you see while running HPC loads? Is there a range of speeds that I should expect? These speeds are way slower than what I saw a month or two back.

Appreciate your help!

Santi

**Comment by dougalb** [comment]
Santi, the MasterNode has a directly attached EBS volume which is mounted
as /shared. This is then *exported* to all the ComputeFleet over NFS and
mounted as /shared. You cannot get the same performance from as they are
two different configurations.

**Comment by adavanisanti** [comment]
@dougalb I understand that they don't get the same performance :). What are the expected performance and the range of performance I can expect? I am noticing slowness that I did not experience before. In your experiments, do you see similar behavior? 

My impression is that for HPC workloads, these speeds can become a huge bottleneck.

Thanks
Santi

**Comment by mohanasudhan** [comment]
Thanks @adavanisanti for data. 

When you started this thread, you mentioned "This wasn't the case before". Can you elaborate on that? What was your original behavior and what's changed now? I understand you seeing slow rate in compute node because you are sharing ebs volume of master via nfs.

Is 30x slow speed expected here ? I donno, I will update you on that today. I like to replicate it and run similar test. I heard we can tune nfs to increase performance but i don't have it handy, need to diggin.

**Comment by adavanisanti** [comment]
@mohanasudhan Unfortunately, I did not measure I/O performance with dd before. I had run my parallel experiments and did not notice a problem with I/O. I will try to infer I/O numbers from my previous runs and get back to you.

From AWS [documentation,](https://aws.amazon.com/ec2/instance-types/) I see the following:

When launched in a placement group, select EC2 instances can utilize up to 10 Gbps for single-flow and 25 Gbps for multi-flow traffic in each direction (full duplex). 

I am not sure what that translates into for I/O and if the overall performance varies with the number of nodes. I will get back with my findings.

**Comment by lukeseawalker** [comment]
Hi @extremoburo,
to improve network performance, placement group could help. You can find more information on what is a placement group [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html).

You can configure the cluster to use your own placement group with
`placement_group = <your_placement_group_name>`
or let CfnCluster create a placement group with the "cluster" strategy with
`placement_group = DYNAMIC`

More configuration info [here](https://cfncluster.readthedocs.io/en/latest/configuration.html#placement-group).

Please also consider to choose an instance type that supports enhanced networking. For more information, see [Enhanced Networking](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html).

Also note that bandwidth scales with instance size, see [here](https://aws.amazon.com/it/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/) 

These three hints should cover the whole range of possibilities to improve network communication.

**Comment by extremoburo** [comment]
thank you very much @lukeseawalker  I'll give it definitely a try soon

**Comment by extremoburo** [comment]
@lukeseawalker one last little question , do you think using st1 volume type to read/write input and outputs could also affect performance as well in this case? thks

**Comment by lukeseawalker** [comment]
@extremoburo it really depends on the use cases. You can find more info [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html)

**Comment by gjparker9** [comment]
for optimal settings for NFS and/or EFS, 
https://d1.awsstatic.com/whitepapers/optimizing-electronic-design-automation-eda-workflows-on-aws.pdf

in particular page 37 and Appendix A
