### ISSUE TITLE
Unable to delete FSx filesystem

### ISSUE THREAD

**Issue by sumedhjain** [aws/aws-parallelcluster#2303]
Recently, I have had attached a FSx partition to a head node of a cluster I created using PC 2.6.1 After completion of my sims, I tried to back up data from FSx partition back to S3. Unfortunately, the partition started to misbehave and I was not able to back up data. Finally, I decided to let go of the data and delete the whole partition to save money. By this time, last data backup task was still on "cancelling" stage. This task did not allow me to delete the partion manually. 

Please look into this asap 

I will give more info about the FSx partion directly in message to the ticket handler.

Thank you for your time

**Comment by ddeidda** [comment]
@sumedhjain 

when you say 
> I have had attached a FSx partition to a head node of a cluster I created using PC 2.6.1

are you meaning that you attached it manually or by adding a [[fsx]](https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html) section in your ParallelCluster configuration file?

**Comment by sumedhjain** [comment]
Sorry for the late reply @ddeidda. Added Fsx section in PC config file.
Anyhow, I had raised an internal ticket with AWS. They fixed the issue. The FSx filesystem has been deleted.
