### ISSUE TITLE
ORTE communications issue on c6gn.16xalrge using EFA

### ISSUE THREAD

**Issue by SiHubb** [aws/aws-parallelcluster#2346]
There seems to be some network problems when using EFA on the c6gn instances. 

AWS ParallelCluster version: 2.10.0
Pcluster config:

> [aws]
> aws_region_name = eu-west-1
> [global]
> cluster_template = default
> update_check = true
> sanity_check = true
> [aliases]
> ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
> [ebs myebs]
> shared_dir = /work
> volume_size = 1000
> [vpc default]
> vpc_id = 
> master_subnet_id = 
> [cluster default]
> key_name = 
> base_os = ubuntu1804
> custom_ami = ami-07b73abb892002aba
> scheduler = slurm
> master_instance_type = c6g.xlarge
> vpc_settings = default
> ebs_settings = myebs
> queue_settings = compute
> [queue compute]
> compute_type = spot
> enable_efa = true
> enable_efa_gdr = false
> placement_group = DYNAMIC
> compute_resource_settings = default
> [compute_resource default]
> instance_type = c6gn.16xlarge
> max_count = 100
> spot_price = 1.2

Error is:

> ORTE has lost communication with a remote daemon.
> 
>   HNP daemon   : [[45674,0],0] on node compute-dy-c6gn16xlarge-1
>   Remote daemon: [[45674,0],2] on node compute-dy-c6gn16xlarge-3
> 
> This is usually due to either a failure of the TCP network
> connection to the node, or possibly an internal failure of
> the daemon itself. We cannot recover from this failure, and
> therefore will terminate the job.

The cluster runs jobs fine with c6g non-EFA instances.
All logs in /var/log/parallelcluster look normal, no related errors or issues.

**Comment by tilne** [comment]
Hi @SiHubb,

The description says that you're using v2.10.0. We added support for EFA on c6gn instances starting with v2.10.1. From the [changelog](https://github.com/aws/aws-parallelcluster/blob/v2.10.1/CHANGELOG.md):
```
Install EFA kernel module on ARM instances with alinux2 and ubuntu1804. This enables support for c6gn instances.
```

Would you be willing to trying with the new version?

**Comment by SiHubb** [comment]
Hi,

Thanks. Yes upgrading no problem - I upgraded to 2.10.0 on hearing the release of c6gn instances assuming it would be EFA ready - I'll make sure I check in future.

Simon.

**Comment by SiHubb** [comment]
Running c6gn's with EFA fine under pcluster 2.10.1 so closing this - thanks for your help.
