### ISSUE TITLE
Inconsistent documentation with Slurm and auto scaling groups pcluster 2.9.0 and newer

### ISSUE THREAD

**Issue by PhilipMorrisJones** [aws/aws-parallelcluster#2353]
If you are reporting an issue with AWS Parallelcluster / CfnCluster please make sure to add the following data in order to facilitate the root cause detection:

**Required Info:**
 - AWS ParallelCluster version 2.9.0

**Bug description and how to reproduce:**

I created a new cluster with cluster 2.10.0 and slurm workload manager and looked for the auto-scaling group and could not see one.

In the docs it says it uses an auto-scalign group

https://docs.aws.amazon.com/parallelcluster/latest/ug/autoscaling.html

```
The auto scaling strategy described here applies to HPC clusters that are deployed with 
one of the supported traditional job schedulers, either Son of Grid Engine (SGE), Slurm 
Workload Manager (Slurm), or Torque Resource Manager (Torque). When deployed with 
one of these schedulers, AWS ParallelCluster implements the scaling capabilities by 
managing the Auto Scaling group of the compute nodes, and then changing 
the scheduler configuration as needed. 
```

but also it says it use sa new architecture

https://docs.aws.amazon.com/parallelcluster/latest/ug/multiple-queue-mode-slurm-user-guide.html

```
The new scaling architecture is based on Slurm’s Cloud Scheduling Guide and power saving 
plugin. For more information about the power saving plugin, see Slurm Power Saving Guide.
In the new architecture, resources that can potentially be made available for a cluster are
typically predefined in the Slurm configuration as cloud nodes.
```

**Comment by chenwany** [comment]
Hi,
Thanks for your feedback! We will update the documentation to be more clear on this.

For pcluster < v2.9.0, our traditional schedulers, including SGE, Slurm and Torque, rely on auto-scaling group for scaling.
For pcluster >= v2.9.0 && scheduler == slurm, we use newly introduced scaling architecture instead of auto-scaling group.

**Comment by chenwany** [comment]
Hi, @PhilipMorrisJones 

Official document has been update: https://docs.aws.amazon.com/parallelcluster/latest/ug/autoscaling.html

Thank you!

**Comment by PhilipMorrisJones** [comment]
Thank you. Feel free to close.
