### ISSUE TITLE
How to identify the queue of a compute node during initialization?

### ISSUE THREAD

**Issue by vbosquier** [aws/aws-parallelcluster#2366]
Hi ParallelCluster Dev Team!

We need to know which queue (Slurm partition) a new Compute node is belonging to during its initialization phase.

How can we find this information so that we can put it in a variable and use it in our custom pre/post-installation scripts?

Note: at this step, we can not request Slurm (with "sinfo" or "scontrol show node") because we need the information BEFORE it is actually setup in Slurm.

Best regards,
Vincent.

**Comment by demartinofra** [comment]
Hi Vincent,
After sourcing `/etc/parallelcluster/cfnconfig` in a compute node you'll have access to the `cfn_scheduler_queue_name`  variable containing the queue name the node belongs to.

Francesco

**Comment by vbosquier** [comment]
Thank you Francesco!
Closing this issue!
