### ISSUE TITLE
Secure access to a bucket and its contents (RO + RW)

### ISSUE THREAD

**Issue by vbosquier** [aws/aws-parallelcluster#2378]
Hi ParallelCluster Dev Team!

In order to use a s3 bucket (either Read-only or Read-Write), the documentation says now we need to set the value of the corresponding variables in .parallelcluster/config file to "bucketname*".

In order to access securely to the bucket, we used to build policies to allow "bucketname" + "bucketname/* ". Using "bucketname*" means that we would allow acces to ANY bucket or URL which would start with "bucketname" and this is not what we want for security reasons.

Can you help me determine how to achieve our goal?

Best regards,
Vincent.

**Comment by demartinofra** [comment]
Hi Vincent,

if you want to have full control over the policy you add to the nodes you can create your own policy and use the [additional-iam-policies](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#additional-iam-policies) configuration option. 

Using `s3_read_resource` and `s3_read_write_resource` only allows you to choose between giving access to bucket objects only (bucketname/*) vs giving access to a bucket + its objects with the downside of using a prefix.

I'd recommend you to go with `additional-iam-policies` unless you are ok with only giving object resource level access.
