### ISSUE TITLE
Initiating cluster creation without blocking

### ISSUE THREAD

**Issue by calebwin** [aws/aws-parallelcluster#2388]
Is it possible to start the process of cluster creation/deletion/updating (by calling one of the `pcluster` CLI commands) without waiting for it to finish.

To give context, we're trying to use `pcluster` from Lambda but are concerned that cluster-related commands may take longer than the 15 minute limit on Lambda execution time. So we're wondering - can we start cluster creation, end the Lambda function, and then submit new Lambda functions that poll for the cluster-related command to complete using `pcluster status`? If yes, how long should we wait after issuing a `pcluster create` or `pcluster delete` before exiting?

**Comment by demartinofra** [comment]
Hi Caleb,

you can use the `-nw, --nowait` option when running `create/delete/update` and then poll the status with a `pcluster status --nowait` when needed.

**Comment by enrico-usai** [comment]
Caleb, in addition to Francesco's comment, if you're using pcluster from Lambda [this blog post](https://aws.amazon.com/blogs/compute/using-aws-parallelcluster-with-a-serverless-api/) might be interesting for you.

**Comment by calebwin** [comment]
Hi @enrico-usai,

Sorry for the late response. This is great to know and should work perfectly for our use-case! Thank you.
