### ISSUE TITLE
Impact of using auto_import_policy in [fsx] section on the clusters' initialization duration

### ISSUE THREAD

**Issue by vbosquier** [aws/aws-parallelcluster#2393]
Hi PC Dev Team!

I use FSx for Lustre linked to a s3 bucket to import files automatically. By default only the metadata are imported.

In case the s3 bucket contains a large volume and amount of file (over 50k objects), the first read operation of the contents of the filesystem is VERY long (hours), whereas the duration of the second read operation is (only) 2 minutes.

How does the "auto import" works? Is it a foreground or a background operation? If I set the "auto_import_policy" to NEW or NEW_CHANGED, how does it impact the initialization duration of the cluster?

Best regards,
Vincent.

**Comment by lukeseawalker** [comment]
Hi Vincent,
the `auto_import_policy` exposed by ParallelCluster corresponds to the [AutoImportPolicy property of the FSx filesystem](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fsx-filesystem-lustreconfiguration.html#cfn-fsx-filesystem-lustreconfiguration-autoimportpolicy).

From the official [FSx doc](https://docs.aws.amazon.com/fsx/latest/LustreGuide/importing-files.html):
> Amazon FSx transparently copies the content of a file from your repository and loads it into the ﬁle system when your application first accesses the file in FSx.

So it's a lazy-load behavior that doesn't affect the cluster creation.

Another reference for the auto import feature is in [this blog post](https://aws.amazon.com/blogs/storage/automatically-import-amazon-s3-object-updates-into-amazon-fsx-for-lustre/).

One possibility to reduce the latency you are facing is to preload the contents of individual files or directories, as suggested by [the following doc](https://docs.aws.amazon.com/fsx/latest/LustreGuide/preload-file-contents-hsm.html).

L

**Comment by vbosquier** [comment]
Hi Luke!

Thanks for the references. I already checked the references and I understand that there in no impact on the duration of the cluster's creation phase IF you keep the default behaviour copying only metadata to the FSx for Lustre filesystem.

My question is: what is the impact on the cluster creation if we force the copy of the data (not only the metadata) using the auto_import_policy?
Is the CloudFormation FSx substack stuck in CREATE_IN_PROGRESS status until the data are actually fully copied?

Best regards,
Vincent.

**Comment by rexcsn** [comment]
Hi @vbosquier,

Unfortunately I am 100% sure of the behavior here, as is problem is perhaps more specific to FSx.

From my understanding of the [FSx AutoImportPolicy documentation here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fsx-filesystem-lustreconfiguration.html#cfn-fsx-filesystem-lustreconfiguration-autoimportpolicy), I don't think changing `AutoImportPolicy` to `NEW` or `NEW_CHANGED` will actually load the files onto the filesystem.
It simply configures the filesystem to add reference of a new objects or changed objects to the filesystem, not copying the actual files.
As such I think it will have small effect on the creation time of the filesystem, as the filesystem is still not actually loading files, but only adding file and directories references to the filesystem.

As Luca mentioned previously, if you want to preload and copy files before first accessing them, you will probably need to follow [this preloading guide](https://docs.aws.amazon.com/fsx/latest/LustreGuide/preload-file-contents-hsm.html) and execute these commands once the filesystem is mounted.
In the past we have seen other customers do this in the post-install script, but note that the setup and creation of cluster nodes is time-capped at 30 mins, so if you are preloading a lot of data it would probably be best to do this manually, after cluster creation is completed.

Hope that helps! Please let us know if you have any question.
