### ISSUE TITLE
Does `pcluster stop` terminates all jobs?

### ISSUE THREAD

**Issue by elgalu** [aws/aws-parallelcluster#2440]
We're planning to use https://github.com/aws/aws-parallelcluster/wiki/MultiUser-Support however the guide shows pcluster stop,update,start steps after adding each user.

What are the implications of https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.stop.html ? will it terminate all running jobs or kill all compute nodes?

**Comment by tilne** [comment]
Before getting to the implications of `pcluster stop`, I believe the purpose of stopping, updating, and restarting the cluster is only necessary if the cluster was created without a pre- or post-install script that adds the desired users. In this case, updating the cluster ensures that compute nodes run the desired script when they are initialized. It would be possible to update the users added by the script when a compute node comes up by having the script read the user information from an external source (like S3) or updating the script in-place. A notable downside of this approach is that newly added users are not added to existing compute nodes, which have already run the post-install script during the bootstrapping process.

As for the implications of `pcluster stop`: it will terminate all compute nodes. Depending on which scheduler is used and how it's configured I would expect this to either terminate running jobs or suspend them until new compute nodes are available.

**Comment by elgalu** [comment]
Thanks, yes, post-install script are not "dynamic" enough for this use case. I suppose one must consider incorporating another technology like AWS SSM or Ansible or Saltstack or Chef. Is https://github.com/aws/aws-parallelcluster-cookbook something that could add this feature or what's the purpose of that project?

**Comment by tilne** [comment]
The cookbook contains the chef cookbook used to provision a cluster's instances, as well as the scripts and packer configuration files used to build AMIs.
