### ISSUE TITLE
Configure cluster users home directories on the shared storage (FSx, EFS, EBS)

### ISSUE THREAD

**Issue by elgalu** [aws/aws-parallelcluster#2441]
There's a [fsx-shared-dir](https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html#fsx-shared-dir) fsx option but couldn't find a home_dir

As of now the way to provide private home directories to each users is to write a custom [post_install](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html) setup?

**Comment by tilne** [comment]
Correct. It's not possible to specify via the ParallelCluster configuration file that an FSx directory should be used as the default user's home directory. The post-install script would be the recommended way to do so.

**Comment by zbarr** [comment]
+1 here. Although it is probably trivial to undo the NFS export from the controller to the compute nodes, unravelling something built in feels like a hack. This would be a great feature as almost everyone has to use some type of other shared storage better than the NFS share for their work. This also would allow users to keep configs and such in their home dir through cluster rebuilds.

**Comment by chenwany** [comment]
Hi, this feature request is tracked in ParallelCluster roadmap
Thanks!

**Comment by enrico-usai** [comment]
We released this feature as part of [3.8.0 release](https://github.com/aws/aws-parallelcluster/releases/tag/v3.8.0):

> Allow for mounting home as an EFS or FSx external shared storage via the SharedStorage section of the config file.

and [3.9.0 release](https://github.com/aws/aws-parallelcluster/releases/tag/v3.9.0):
> Add the configuration parameter `DeploymentSettings/DefaultUserHome` to allow users to move the default user's home directory to `/local/home` instead of `/home` (default).

**Comment by elgalu** [comment]
thanks @enrico-usai very much appreciated
