### ISSUE TITLE
Specifying the keypair in the aws-parallelcluster script

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#2446]
Hello,
I'm almost sure of the answer to this question but I'm asking it just in case that I'm missing something. Can you use a custom AMI without the keypair on it? By this, I mean where the 'authorized keys' files have been erased. In other words, is there any mechanism to provide the aws-parallelcluster script with a (AWS-stored) keypair manually?
Thanks.

**Comment by hanwen-pcluste** [comment]
Hello afernandezody,
If I understood the issue, you are trying to create a cluster without specifying a keypair:
It is currently impossible to run [`pcluster create`](https://docs.aws.amazon.com/parallelcluster/latest/ug/pluster.create.html) without specifying the [`key_name`](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#key-name) in the configuration file. However, we are aware of the need to create a cluster without any key pair. And a [patch](https://github.com/aws/aws-parallelcluster/pull/2364) has been merged and will be included in the next release.
You can also [use pre/post-install script to customize bootstrap actions](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html)
Please let us know if your question is answered. Thank you.

**Comment by afernandezody** [comment]
Hi @hanwen-pcluste,
This was probably an unnecessary question and my own misconception. I had assumed that, if you're using a custom AMI, you would need to use the same keypair in the AMI and pcluster script. However, that is not necessary (probably discussed in some part of the documentation that I skipped reading) and you can log in into the master instance with either key. I haven't tested it yet but using a custom AMI without keys should work fine as long as AWS ParalleCluster adds the key in the script to the master instance. This should solve my issue.      
I'm not sure what you meant by creating a cluster without any key pair. How would you ssh to the master instance?
Thanks.

**Comment by hanwen-pcluste** [comment]
Seems I misunderstood the question.
If I understand it now, you are trying to create a cluster with a custom AMI, where the `authorized keys` file is empty. But you would like the cluster to have an AWS stored keypair attached to enable SSH access:
The answer is yes. You just need to specify the [`custom_ami`](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#custom-ami-section), [`key_name`](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#key-name), and other required fields in the configuration file and run `pcluster create`.

I will provide another reply on how to create a cluster without a keypair (This scenario is not common at all)

**Comment by hanwen-pcluste** [comment]
There are multiple options to [connect to your instance](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html). I thought you were trying to stop managing SSH keys, therefore gave you the first answer. 
Regarding your use case, I'd say the common SSH connection is enough. I hope the second answer could solve you question.

**Comment by afernandezody** [comment]
Thanks!
