### ISSUE TITLE
Cannot connect to NICE-DCV (from Windows)

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#2457]
Hello,
I'm having issues trying to connect to NIVE-DCV. The aws-parallecluster version is 2.10.1. I downsized the cluster size and boiled down the configuration script to its skeleton:
```
[global]
update_check = true
sanity_check = true
cluster_template = g1cluster

[aws]
aws_region_name = us-east-1
aws_access_key_id = ********...
aws_secret_access_key = ********...

[cluster g1cluster]
vpc_settings = odyvpc
placement_group = DYNAMIC
placement = compute
key_name = ********
master_instance_type = t3.medium
compute_instance_type = c5.large
cluster_type = spot
disable_hyperthreading = true
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
scheduler = slurm
base_os = centos8
dcv_settings = wdcv

[vpc odyvpc]
master_subnet_id = subnet-********
vpc_id = vpc-********

[dcv wdcv]
enable = master
access_from = 0.0.0.0/0

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

```
Everything is working fine and the dcvserver is up and running:
```
 sudo systemctl status dcvserver
? dcvserver.service - NICE DCV server daemon
   Loaded: loaded (/usr/lib/systemd/system/dcvserver.service; enabled; vendor p>
   Active: active (running) since Mon 2021-02-22 18:35:10 UTC; 5min ago
 Main PID: 6162 (dcvserver)
    Tasks: 4 (limit: 23063)
   Memory: 26.5M
   CGroup: /system.slice/dcvserver.service
           ??6162 /bin/bash /usr/bin/dcvserver -d --service
           ??6173 /usr/libexec/dcv/dcvserver --service

Feb 22 18:35:06 ip-172-31-47-117 systemd[1]: Starting NICE DCV server daemon...
Feb 22 18:35:10 ip-172-31-47-117 systemd[1]: Started NICE DCV server daemon.


```
with no running dcv sessions as expected. The issue happens when I try to connect (from Windows) with:
```
C:\Users\Arturo\.parallelcluster>pcluster dcv connect -k ~/.ssh/id_rsa g1cluster
The authenticity of host '54.163.137.65 (54.163.137.65)' can't be established.
ECDSA key fingerprint is SHA256:u2tUM52iIzq56r18rUdv0R3Oi7fQMJ23qwGE0RbgY9A.
Are you sure you want to continue connecting (yes/no)?
ERROR: Something went wrong during DCV connection.
centos@54.163.137.65: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Please check the logs in the /var/log/parallelcluster/ folder of the head node and submit an issue https://github.com/aws/aws-parallelcluster/issues
```
Thanks,
Arturo
[pcluster_dcv_authenticator.log](https://github.com/aws/aws-parallelcluster/files/6024485/pcluster_dcv_authenticator.log)

**Comment by ddeidda** [comment]
Hi Arturo,

I wonder the key path `~/.ssh/id_rsa g1cluster` might not work in Windows. You could try using backslashes, like `c:\path\to\key`. The rest of your configuration seems OK to me.

**Comment by afernandezody** [comment]
Hi @**ddeidda**, 
Not sure if I'm following you. Why would the id_rsa key be in my Windows system? Isn't the pcluster command supposed to grab that key from the master instance and open the dcv connection? 
Thanks.

**Comment by ddeidda** [comment]
@afernandezody 

With the `-k` argument you specify the local path to the private ssh key that should be hosted on your system.
More information here: https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.dcv.html

**Comment by afernandezody** [comment]
Hi @**ddeidda**,
You're right, I had not paid attention to the NICE DCV HTTPS certificate section. It's not exactly how I assumed it would work. Let me close the ticket because I need to think about about going about this via a different route, and your proposed solution should work.
Thanks.
