### ISSUE TITLE
Automatic node adding via scontrol update state=power_up error

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2467]
**Bug description and how to reproduce:**

I followed the [Multiple queue mode slurm user guide](https://docs.aws.amazon.com/parallelcluster/latest/ug/multiple-queue-mode-slurm-user-guide.html) and tried to add a node manually in order to find a workaround to [issue-2454](https://github.com/aws/aws-parallelcluster/issues/2454).

```
$ sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST
t2-medium*    up   infinite     10  idle~ t2-medium-dy-t2medium-[1-10]

$ scontrol update nodename=t2-medium-dy-t2medium-1 state=power_up   # master node
slurm_update error: Invalid user id
```

Can you please tell me what I am doing wrong? How to debug it further?

**Required Info:**
 - AWS ParallelCluster version 2.10.1:
 - Cluster name: `test-cluster20-scaleup`
 - Cluster configuration
```
[aws]
aws_region_name = ca-central-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
base_os = alinux2
key_name = parallel-cluster-master-node
vpc_settings = default
efs_settings = awselasticfs

scheduler = slurm
master_instance_type = t2.small
master_root_volume_size = 25   # GB
compute_root_volume_size = 25  # GB
queue_settings = t2-small

s3_read_resource = *
s3_read_write_resource = *


[vpc default]
vpc_id = vpc-MASKED
master_subnet_id = subnet-ID1_MASKED   # PCI_Subnet4
compute_subnet_id = subnet-ID1_MASKED   # PCI_Subnet4


[scaling custom]
scaledown_idletime = 5

[queue t2-small]
compute_resource_settings = t2-medium
compute_type = spot

[compute_resource t2-medium]
instance_type = t2.medium
initial_count = 0
max_count = 10

[efs awselasticfs]
shared_dir = /efs
encrypted = true
efs_fs_id = fs-MASKED-ID
performance_mode = generalPurpose
```

Note that right now, I am not able to use [the guide for collecting logs to S3](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs)  due to insufficient permissions but I  can send you any logs from master / compute nodes.

**Comment by oplatek** [comment]
Hi @lukeseawalker !
Should I provide more logs/information to receive help? Any suggestions?

**Comment by demartinofra** [comment]
The error you reported
```
$ scontrol update nodename=t2-medium-dy-t2medium-1 state=power_up   # master node
slurm_update error: Invalid user id
```

is due to the fact that scontrol update commands can only be executed as root or slurm user. try the following:
```
$ sudo su -
$ scontrol update nodename=t2-medium-dy-t2medium-1 state=power_up   # master node
```

**Comment by oplatek** [comment]
Thank you @demartinofra . Your suggestion worked like a charm.

```
$ sudo su -

# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST 
t2-medium*    up   infinite     10  idle~ t2-medium-dy-t2medium-[1-10] 

# scontrol update nodename=t2-medium-dy-t2medium-1 state=power_up   # works now

# sinfo
PARTITION  AVAIL  TIMELIMIT  NODES  STATE NODELIST 
t2-medium*    up   infinite      1  idle# t2-medium-dy-t2medium-1 
t2-medium*    up   infinite      9  idle~ t2-medium-dy-t2medium-[2-10] 
```

**Comment by oplatek** [comment]
@demartinofra do you think it would easy to make the command to work with just sudo without the signed as root user first?

Re-opening the issue because:

```
$ sudo su -
# scontrol update nodename=t2-medium-dy-t2medium-1 state=power_up   # works now
```

But simply running the command with sudo is not possible

```
sudo scontrol update nodename=t2-medium-dy-t2medium-1 state=power_up   # fails now
```

For multiuser support is obviously using `sudo` is a much better solution.

**Comment by demartinofra** [comment]
You can solve this in several different ways. The problem here is that the path to Slurm binaries is defined in `/etc/profile.d/slurm.sh` which only gets sources with a login shell. 

All the following alternatives work:
```
sudo /opt/slurm/bin/scontrol ...  # absolute path to binaries
sudo -i scontrol ... # login shell
sudo env "PATH=$PATH" scontrol ...  # set the PATH to the one in use by the current user
```

**Comment by oplatek** [comment]
Makes sense, thank you for the clarification!
