### ISSUE TITLE
ARM clusters creation failing

### ISSUE THREAD

**Issue by mserkov** [aws/aws-parallelcluster#2470]
Version: 2.10.1
configuration
`
[aws]
aws_region_name = us-east-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
key_name = test
base_os = alinux2
scheduler = slurm
master_instance_type = c6g.medium
vpc_settings = default
queue_settings = compute
ephemeral_dir = /scratch

[vpc default]
vpc_id = vpc-***
master_subnet_id = subnet-***
use_public_ips = false
additional_sg = sg-***

[queue compute]
enable_efa = false
compute_resource_settings = compute
compute_type = spot

[compute_resource compute]
instance_type = c6g.16xlarge
max_count = 1
`

>pcluster create -c config.conf test-cluster
ERROR: Unable to validate configuration parameters for instance type 'c6g.medium'. Please double check your cluster configuration.
The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.

Started couple of hours ago with no changes in configuration file. I dig a little into the code, and found that it is happening in test_configuration routine of sit_cluster_model and hit_cluster_model when it tries to test master/compute nodes configuration

```
            # Test head node configuration
            self._ec2_run_instance(
                pcluster_config,
                InstanceType=head_node_instance_type,
                MinCount=1,
                MaxCount=1,
                ImageId=latest_alinux_ami_id,
                CpuOptions=head_node_cpu_options,
                NetworkInterfaces=head_node_network_interfaces,
                Placement=head_node_placement_group,
                DryRun=True,
            )

```

Seems like latest_alinux_ami_id is returning x86 AMI instead of ARM. Interestingly, even if I define custom_ami in the config - the creation fails. Looks like this test doesn't really look into custom_ami parameter. I don't know why it is started happening just now, maybe something is changed on AWS side, as this latest_alinux_ami_id is coming from boto interface and I assume requesting some standard resource which might have changed.

Can someone please take a look? Maybe it is not the code, but I do something wrong. However, yesterday this exact configuration was working, and I have it in SCM, so really no changes.  Right now it isn't really possible to create ARM clusters, at least in my case. Tried to switch to different region ( us-east-2 ), same thing.

**Comment by mserkov** [comment]
Checked a bit deeper. So latest_alinux_ami_id eventually comes from the following source:
```
            alinux_ami_id = (
                boto3.client("ssm")
                .get_parameters_by_path(Path="/aws/service/ami-amazon-linux-latest")
                .get("Parameters")[0]
                .get("Value")
            )
```

The problem is that it returns list of AMI-s, but we get only first one [0] from the list. The whole list is like:
```
/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-ebs ami-0724396c26f1b7dae
/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-gp2 ami-0d08a21fc010da680
/aws/service/ami-amazon-linux-latest/amzn-ami-hvm-x86_64-s3 ami-0b2b61b9a591a7cc5
/aws/service/ami-amazon-linux-latest/amzn-ami-minimal-hvm-x86_64-s3 ami-05c84ec05c7706b2a
/aws/service/ami-amazon-linux-latest/amzn-ami-pv-x86_64-s3 ami-0fc45f1c0e819fc61
/aws/service/ami-amazon-linux-latest/amzn2-ami-graphics-hvm-x86_64-gp2 ami-0d939f4f49b41d202
/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2 ami-0c3dda3deab25a563
/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs ami-088378c6de091c70c
/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2 ami-0915bcb5fa77e4892
/aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-arm64-ebs ami-0aaf2d8fefcde5893 
```

I have no idea why it was working before. Maybe dry-run actually did accept wrongly assigned AMI but was fixed, that is the only theory I have. 

I just commented those dry-run tests for master/computation nodes, and cluster was created with no issues. I think it is better to address this issue by identifying architecture and getting proper AMI from the list ( not the first one ), and also add custom_ami handler so the code will be checking AMI that used has defined.

**Comment by ddeidda** [comment]
Thanks @mserkov for reporting this.

We are working on a fix to address this issue; in the meanwhile the suggested workaround is to disable sanity checks by setting `sanity_check = false` in your configuration file.

**Comment by mserkov** [comment]
@ddeidda Thank you for working on that! Please let me know if any additional information required.

**Comment by rexcsn** [comment]
Hi, [AWS ParallelCluster v2.10.2](https://github.com/aws/aws-parallelcluster/releases/tag/v2.10.2) is released and contains fix for this issue.
Closing the issue now, please feel free to reopen if there is any question. Thank you!

**Comment by ukirandumkara** [comment]
Hi @rexcsn 
We got hit with similar bug from the AWS on our customized Parallel Cluster image version 2.9.1 on Nov 23, 2021.  Our custom AMI based on x86_64 was running normal last 6 months and no changes were made to the platform, last week hit with this bug.

Error: Unable to validate configuration parameters. Please double check your cluster configuration.
The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that have matching architecture, and try again. You can use 'describe-instance-types' or ...

We set the sanity_check=false and able to start a cluster. But it throws out error messages and cluster start time increased by 20%.

**Comment by gwolski** [comment]
Hi all, including @rexcsn and @ddeidda,

I'm hit with the same problem as @ukirandumkara but I'm running 2.10.1.  I successfully launched a set of new clusters last week on Nov 20, so something happened between Nov 20 and Nov 23 when @ukirandumkara reported a problem.  My first set of messages:

Retrieving configuration from CloudFormation for cluster sim...
Validating configuration file simcluster_config-2.10.1...
ERROR: Unable to validate configuration parameters for instance type 't3a.medium'. Please double check your cluster configuration.
The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.
ERROR: Unable to validate configuration parameters for instance type 'm5.large'. Please double check your cluster configuration.
The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.

And it repeats for every instance type I have in my compute_resource descriptions.

Looking for some guidance -- going to try moving to 2.11.3 tomorrow.

**Comment by enrico-usai** [comment]
Hi @ukirandumkara and @gwolski,

when starting a cluster the CLI performs a dry-run check to try to launch an instance with the specified configuration and verify if it's correct. 

The bug in ParallelCluster <=2.10.1 was that the code wasn't using the custom image configured through the `custom_ami` parameter but the first image available in `amazon-linux-latest` repo that sometimes is not aligned with the configured one.

As mentioned by Rex the fix for this patch has been already merged and included in ParallelCluster 2.10.2+ releases, both the versions you're using (2.9.1 @ukirandumkara and 2.10.1 @gwolski) don't contain the fix. See: https://github.com/aws/aws-parallelcluster/pull/2474

The solution is to move to ParallelCluster >=2.10.2. We suggest the latest available version. Thanks!

**Comment by gwolski** [comment]
Hi @enrico-usai,
Thank you for your response.  I should never file a "ticket" after 5PM -- I wasn't thinking clearly.  I saw Rex's note about 2.10.2+ and I thought I was on 2.10.4.  But then went back to my clusters to get all the details and just blindly copied my .2.10.1 and submitted my note.  I was on 2.10.1...  Just didn't think...

That said, I spun up 2.11.3 yesterday and I'm not seeing the issue.
Thank you all.

**Comment by bifxcore** [comment]
I'm on pcluster 2.11.3 and I still get an error:
ERROR: Error when resolving cluster ami id: No official image id found for base_os='alinux2' and architecture='x86_64'

Disabling sanity_check throws:
Invalid type for parameter ImageId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>

I guess this means we are forced to upgrade to pcluster 3+ ?

**Comment by enrico-usai** [comment]
Hi @bifxcore
the only alternative I can see is to pass the AMI id at cluster creation time, by searching for it [here](https://github.com/aws/aws-parallelcluster/blob/v2.11.3/amis.txt).
Anyway, we strongly suggest to move to ParallelCluster 3.x. ParallelCluster 2.x is EOL by long time, see https://docs.aws.amazon.com/parallelcluster/latest/ug/support-policy.html
