### ISSUE TITLE
[Feature request] more than 3 instance types in queue

### ISSUE THREAD

**Issue by mserkov** [aws/aws-parallelcluster#2502]
Hello,

Just wondering if more than 3 instance types ( compute resources ) can be defined for one queue?

While I agree that removing the limit completely may increase the complexity of scaling mechanism, but 3 types seems a bit small. It is possible to use different queues, but in some cases it creates a lot of pain for configuring apps.

Best regards,
Mikhail Serkov

**Comment by rexcsn** [comment]
Hi @mserkov,

Thank you for opening this feature request, first, we want to understand a bit more about your use case.
In general, how many instance types per queue would you be looking to configure for your applications?

The current limit of 3 instance types per queue is configured as part of the `sanity_check` functionality.
If you want to experiment with using > 3 instance types per queue, you can try to disable `sanity_check` by specifying `sanity_check = false` in your configuration file.
After disabling `sanity_check`, you should be able to create a cluster with > 3 instance types per queue.

Of course, this is not an officially supported path, so you might encounter some issues.
It would be great if you could inform us of the limitations and issues you see when working with > 3 instance types per queue, so we can take those into account when evaluating this feature.

Thank you!

**Comment by hanwen-pcluste** [comment]
Hi @mserkov,

Starting with ParallelCLuster 3, we raise the limit to 10 queues and 5 compute resources per queue.

Thank you!
