### ISSUE TITLE
using aws sso credentials with pcluster fails

### ISSUE THREAD

**Issue by FenryrMKIII** [aws/aws-parallelcluster#2515]
# Issue 
I have the following aws-cli & pcluster versions installed on my Windows computer 👍 

```bash
aws-cli/2.1.29 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
pcluster 2.10.2
```

I have to authenticate through SSO (Okta) because my company forbids any other way of accessing AWS ressources. It works with standard aws cli commands e.g. :

```bash
aws s3 ls --profile my_profile
```
lists the s3 buckets. But using pcluster command while logged on with sso provides an error : 

```bash
pcluster status cluster
AWS Credentials not found.
```

how can I use pcluster with sso credentials ?

# Workaround 
You can access pcluster command with temporary credentials by following [this ](https://aws.amazon.com/blogs/security/aws-single-sign-on-now-enables-command-line-interface-access-for-aws-accounts-using-corporate-credentials/)tutorial and by setting environment variables.

However, I would like to know if there is a way of achieving this by using the named profile ?

**Comment by demartinofra** [comment]
Hi @FenryrMKIII 

please check if this reply addresses your question: https://github.com/aws/aws-parallelcluster/issues/2482#issuecomment-788990323

**Comment by FenryrMKIII** [comment]
> Hi @FenryrMKIII
> 
> please check if this reply addresses your question: [#2482 (comment)](https://github.com/aws/aws-parallelcluster/issues/2482#issuecomment-788990323)

I found that solution yesterday. And indeed it works.
On windows you have to use `setx` and open a new shell. Indeed, `set` command that is active in the current shell does not seem to work properly on my side.
