### ISSUE TITLE
Compute instances running but not showing up in qhost, on Amazon Linux with SGE

### ISSUE THREAD

**Issue by yuankunzhu** [aws/aws-parallelcluster#252]
Dear all,

What I experienced is very similar to #86 and #159, but I don't think it was caused by the same reason, as I didn't use `custom_ami` nor `post_install` in the configs. 

So my CloudWatch/CloudFormation/CloudTrail are all working successfully. Computer instance was also launched successfully, in running status, but not added to qhost. Meanwhile, as the SBG job stays in `qw` state, new compute nodes were continued to be launched, but still, none of them shows up in qhost. Have to stop the cluster after it reached too many nodes. 

Have worked with cfncluster for a while, worked well within other environment. 

Below is my config:
```
[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = us-east-1
aws_access_key_id =
aws_secret_access_key = 

[cluster default]
key_name =
master_instance_type = m4.2xlarge
compute_instance_type = d2.4xlarge
initial_queue_size = 0
max_queue_size = 10
maintain_initial_size = false
scheduler = sge
cluster_type = spot
spot_price = 1.5
s3_read_write_resource = *
proxy_server = NONE
ephemeral_dir = /scratch
master_root_volume_size = 100
compute_root_volume_size = 15
vpc_settings = default
scaling_settings = default

[vpc default]
vpc_id = vpc-xxxxxxxx
master_subnet_id = subnet-xxxxxxxx
ssh_from = 0.0.0.0/0

[scaling default]
scaling_threshold = 1
scaling_adjustment = 1
scaling_threshold2 = 80
scaling_adjustment2 = 5
scaling_period = 60
scaling_evaluation_periods = 2
scaling_cooldown = 120
```

and when qsub, i got warning as:
```
$ qsub run.sh
Unable to run job: warning: ec2-user's job is not allowed to run in any queue
Your job 7 ("run.sh") has been submitted
```

qstat is always `qw`, qhost gives nothing.

**Comment by jocherry** [comment]
I think this forum post is the same issue you are experiencing: https://forums.aws.amazon.com/thread.jspa?messageID=676978

Which has to do with your setting the initial queue size to 0, and how SGE handles this.

Please let me know if this does not answer your question.

**Comment by lukeseawalker** [comment]
@yuankunzhu are you still having this issue with latest release? I was not able to reproduce
