### ISSUE TITLE
How to assign different tags between the compute and master nodes? 

### ISSUE THREAD

**Issue by eewolfe** [aws/aws-parallelcluster#2521]
Hello Folks,

We have a requirement for the master node to have one tag_Role_<property> and the compute nodes to have a different tag_Role_<property>. I see in the pcluster config there is a tags option, but I am not sure how to use this to set different tags between master and compute . . . any ideas?

-- Gene.

**Comment by hanwen-pcluste** [comment]
Hello Gene,

Unfortunately, `pcluster` currently doesn't support assigning different tags between the compute and master nodes. I am going to mark this as a feature request for us to take it into account in the future.

At the moment, you can use the [tags parameter](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#tags) to assign them to all nodes. If you want to assign different tags to different nodes, you can use [custom bootstrap scripts](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html). In the scripts, you can [retrieve instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html) to get instance id and call [EC2 API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html) to assign more tags.

Thank you!
Hanwen

**Comment by eewolfe** [comment]
OK, thank you very much for your research and comments on this.

-- Gene.
