### ISSUE TITLE
Docker causing unexpected behavior

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#2538]
Hello,
Installing and starting docker is causing me every type of problem when running jobs. The cluster is running on CentOS8 and with v2.10.2. The jobs keep running (not doing anything productive) but I can see messages such as:
```
taskid: 3 hostname: compute-st-r52xlarge-1
[compute-st-r52xlarge-1][[11331,1],3][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[11331,1],1]
```
which reflect that something is just not right. Should I expect this behavior even without doing anything with a container? 
Thanks.

**Comment by yuleiwan** [comment]
Hi @afernandezody,

From the messages you provided, it's not clear to understand the problem and root cause, could you provide more information like:
* How and when is you installing and running docker?
* Are there any other logs you can provide that might help us to investigate the problem?

**Comment by afernandezody** [comment]
Hi @**yuleiwan**, 
Firstly, let me clarify that there is no error message per se (beyond the previously mentioned message) so let me try to explain the issue in greater detail. It has been causing me trouble since Saturday so I have tried several things. 
**Method A** - I created a custom AMI where Docker is installed. For CentOS8, the installation reads:
```
sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install docker-ce --nobest -y
sudo systemctl enable --now docker
sudo usermod -a -G docker centos
```
These commands are slightly different than for Alinux2. Anyhow, checking docker status return enabled as expected. This was my original configuration on Saturday when I launched the 1st cluster. It actually kept running for almost 2 hours until I realized that the ranks were running (checked the compute instances) but there was no progress at all. After several attempts, it was evident that the cluster runs the jobs without any issue when no Docker is active but, when this is active, the jobs don't make any progress even if the cores are apparently crunching numbers.
**Method B** - Docker is installed as a postscript. The logs report this installation and chef completes as usually. Then, it's the same story (cores are running but there is no progress and I can see the "unexpected process identifier message").
Please let me know if this is now clear enough.
Thanks.

[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/6160584/cfn-init-cmd.log)

**Comment by yuleiwan** [comment]
Hi @afernandezody,

Thanks for your details. I tried to reproduce the issue on centos8 pcluster 2.10.2, but I can't. I just installed and enbaled the docker on cluster as the commands you provide and submit a simple job, it succeeded.

Are you using slurm as scheduler? Could you check slurmctld log to see you job status and use command `scontrol show jobs -o {job_id} to see the job status?

Thank you

**Comment by afernandezody** [comment]
Hi @**yuleiwan**, 
scontrol is returning
```
JobId=2 JobName=EXE_2
   UserId=centos(1000) GroupId=centos(1000) MCS_label=N/A
   Priority=4294901759 Nice=0 Account=(null) QOS=(null)
   JobState=RUNNING Reason=None Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:00:32 TimeLimit=UNLIMITED TimeMin=N/A
   SubmitTime=2021-03-18T23:01:34 EligibleTime=2021-03-18T23:01:34
   AccrueTime=2021-03-18T23:01:34
   StartTime=2021-03-18T23:01:34 EndTime=Unknown Deadline=N/A
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2021-03-18T23:01:34
   Partition=compute AllocNode:Sid=ip-172-31-35-136:5650
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=compute-st-c6gmedium-[1-2]
   BatchHost=compute-st-c6gmedium-1
   NumNodes=2 NumCPUs=2 NumTasks=2 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=2,node=2,billing=2
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=1 MinMemoryNode=0 MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/home/centos/EXEBench_2.sbatch
   WorkDir=/home/centos
   StdErr=/home/centos/output.txt
   StdIn=/dev/null
   StdOut=/home/centos/output.txt
   Power=
   MailUser=(null) MailType=NONE

```
I'm not that familiar with slurm internals so any help is welcomed. Thanks.

[slurmctld.log](https://github.com/aws/aws-parallelcluster/files/6167641/slurmctld.log)

**Comment by yuleiwan** [comment]
From slurmctld log, I saw it was the first job you submitted to scheduler, there may get stuck when you spin up the compute instances, but I am not sure about the root cause right now. Could you scancel {job_id} to cancel the job and resubmit it? If it still doesn't work, we need your job script without confidential and personal data to reproduce your issue for further investigation.

**Comment by afernandezody** [comment]
I terminated the cluster so I'd need to launch it again. However, I only submitted one single job and I never log in before the whole cluster launch is complete. 
I was trying to decipher why the log is claiming that it cannot open the node_state or trigger_state files, but I can tell you that. based on the time stamps, these warnings/errors happened during the spin up (before I logged in). Something else is that my jobs are always numbered starting with 2 (not that this matters per se but makes me wonder if something else might have gone during launch).
```
[global]
update_check = true
sanity_check = true
cluster_template = w1cluster

[aws]
aws_region_name = us-east-1
aws_access_key_id = ***
aws_secret_access_key = ***

[cluster w1cluster]
vpc_settings = odyvpc
placement_group = DYNAMIC
placement = compute
key_name = llave_i3
master_instance_type = c6g.medium
compute_instance_type = c6g.medium
cluster_type = spot
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
scheduler = slurm
base_os = centos8
custom_ami = ami-***
master_root_volume_size = 50
compute_root_volume_size = 50
post_install = ***
post_install_args = ***
additional_iam_policies = ***
tags = ***

[vpc odyvpc]
master_subnet_id = subnet-***
vpc_id = vpc-***

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```

**Comment by afernandezody** [comment]
Hi @**yuleiwan**, 
I have finished some further testing and my observations are pretty much the same as yesterday. Let me begin with a very vanilla config without any custom AMI:
```
[global]
update_check = true
sanity_check = true
cluster_template = w1cluster

[aws]
aws_region_name = us-east-1
aws_access_key_id = ***
aws_secret_access_key = ***

[cluster w1cluster]
vpc_settings = odyvpc
placement_group = DYNAMIC
placement = compute
key_name = llave_i3
master_instance_type = t3.micro
compute_instance_type = c5.large
cluster_type = spot
disable_hyperthreading = true
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
scheduler = slurm
base_os = centos8

[vpc odyvpc]
master_subnet_id = subnet-***
vpc_id = vpc-***

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
```
This doesn't do much but the slurmctld log (attached) still claims some missing files during the spin up period. After it, I launched a larger cluster (2xr5.2xlarge) with a custom AMI. This one doesn't have any Docker stuff and the app runs without any issue. Once the job is running, the slurmctl.log has added the lines describing the job
```
[2021-03-19T11:12:08.964] _slurm_rpc_submit_batch_job: JobId=2 InitPrio=4294901759 usec=282
[2021-03-19T11:12:09.220] backfill: Started JobId=2 in compute on compute-st-r52xlarge-[1-2]
[2021-03-19T11:12:09.220] prolog_running_decr: Configuration for JobId=2 is complete
```  
and scontrol return is very similar to yesterday's (when the cores are running but with no progress). I really don't know why the presence of Docker is causing these issues.
Thanks.  

[slurmctld.log](https://github.com/aws/aws-parallelcluster/files/6170853/slurmctld.log)

**Comment by yuleiwan** [comment]
Hi @afernandezody,

Your case is very similar to this [github issue](https://github.com/aws/aws-parallelcluster/issues/2147) about extra docker network interface in cluster. Could you confirm if it helps your issue. Meanwhile I will use your config files to try to reproduce the issue and do investigation.

**Comment by afernandezody** [comment]
Hi @**yuleiwan**, 
I missed that thread in my initial search for related issues and didn't cross my mind that Docker was creating the network interface and messing with the MPI wrapper. It seems to be working now so I'm closing the ticket.
Thanks.
