### ISSUE TITLE
Will pcluster status show failed creating or deletion?

### ISSUE THREAD

**Issue by calebwin** [aws/aws-parallelcluster#2557]
I want to use `--nowait` on `pcluster create` and `pcluster delete`. But I want to later be able to poll/check if the cluster creation or deleting failed or not.

Would I be able to do that with `pcluster status`?

**Comment by yuleiwan** [comment]
Hi @calebwin,

Yes, you are able to retrieve cluster creation or deletion status by `pcluster status` command. `--nowait` option is specified to skip displaying the status of cloudformation stack events like `MasterSeverSubstack` or `CloudWatchDashBoardSubstack` etc., but `pcluster status` will still return the cluster stack(main stack) status, even if you use `--nowait` in commands.
