### ISSUE TITLE
Clarifying question about pcluster update and post_install

### ISSUE THREAD

**Issue by calebwin** [aws/aws-parallelcluster#2562]
Hi,

Just want to clarify behavior of `pcluster update` with a `post_install`. If the path to the post-install script in S3 stays the same but the contents get changed, will later nodes launched in the cluster pull from that S3 location?

**Comment by lukeseawalker** [comment]
Hi @calebwin, 
this has been answered in https://github.com/aws/aws-parallelcluster/issues/2558#issuecomment-803722953.
The post installation script will be download and executed in the bootstrap phase of new launched nodes, regardless if the location or the content stay the same.

Behind the scenes, the [`fetch_and_run` script](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/templates/default/fetch_and_run.erb) is called during the [execution of the user data](https://github.com/aws/aws-parallelcluster/blob/develop/cloudformation/compute-fleet-hit-substack.cfn.yaml#L455)

**Comment by calebwin** [comment]
Thank you :+1:
