### ISSUE TITLE
Question: Running postinstall script at ec2-user permission

### ISSUE THREAD

**Issue by cailinw** [aws/aws-parallelcluster#2586]
The postinstall script runs at root user level permission. Is it possible to run this script at ec2-user permission level? For example, I want to install Julia packages in the postinstall script, however since they are install at root level permission, they are not accessible by ec2-user later. I tried using `sudo su - ec2-user -c` in the postinstall script, but that gives permission denied.
Thank you!

**Comment by enrico-usai** [comment]
Hi Cailin

it is not possible to run the post-install script as ec2-user but the `sudo su - ec2-user -c` should work.

I tried to login in an EC2 instance, created a bash script with the following content:
```
#!/bin/bash
wget https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.0-linux-x86_64.tar.gz
tar -xvzf /julia-1.6.0-linux-x86_64.tar.gz
```
and executed it as root:
```
[root /]# sudo su - ec2-user -c "sh /julia-install.sh"

[root /]# ls -lart /home/ec2-user/
...
drwxr-xr-x 8 ec2-user ec2-user       100 Mar 25 02:41 julia-1.6.0
-rw-rw-r-- 1 ec2-user ec2-user 112838927 Mar 25 03:50 julia-1.6.0-linux-x86_64.tar.gz
```

Can you share the details of the permission denied error and the post-install script you're executing?
