### ISSUE TITLE
EFA with centos8 & arm

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#2588]
Hello,
I was trying to launch a cluster with c6gn.16xlarge instances and got the error message:
```
ERROR: The configuration parameter 'enable_efa' generated the following errors:
EFA currently not supported on centos8 for arm64 architecture
```
I saw another ticket #2360 but I'm using v2.10.3.
Thanks.

**Comment by enrico-usai** [comment]
Hi @afernandezody 
You can try the workaround suggested in the #2360, to set `sanity_check = false` in the `global` section.

But anyway we want to understand the root cause of the issue.
Could you please share your configuration file (by removing sensitive data)?

We'd like to replicate the issue.
Thanks

**Comment by afernandezody** [comment]
```
[global]
update_check = true
sanity_check = true
cluster_template = w1cluster

[aws]
aws_region_name = us-east-1
aws_access_key_id = 
aws_secret_access_key = 

[cluster w1cluster]
vpc_settings = odyvpc
placement_group = DYNAMIC
placement = compute
key_name = 
master_instance_type = t4g.small
compute_instance_type = c6gn.16xlarge
cluster_type = spot
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
enable_efa = compute
scheduler = slurm
base_os = centos8

[vpc odyvpc]
master_subnet_id = 
vpc_id = 

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

```

**Comment by enrico-usai** [comment]
Hi,
thanks for sharing the configuration. I've been replicate the behaviour.
I was wrong suggesting you to set `sanity_check` to false because it is not a supported combination.

> The following AMIs support EFA with Arm-based (Graviton 2) instance types:
Amazon Linux 2
Ubuntu 18.04 and 20.04
openSUSE Leap 15.2

Source: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types

**Comment by afernandezody** [comment]
Hi @**enrico-usai**, 
I guess that for a technical explanation (or even for requesting it as a potential feature) I'd need to contact the EFA team. Even if that were feasible, that would still have to wait until future versions of parallelcluster. Thanks.

**Comment by enrico-usai** [comment]
Yes @afernandezody 
When EFA support will be available for Centos8 ARM for sure we'll add in ParallelCluster.
Thanks

**Comment by afernandezody** [comment]
Hello,
I have been using the suggested workaround (#2360) for the last few months (and was working fine for what I tested -up to 320 cores or so, maybe a bit more-): 
```
[global]
update_check = true
sanity_check = false
cluster_template = armcluster 
...
```
and this has worked for the last few weeks. However, today's attempt is resulting in the error:
```
Beginning cluster creation for cluster: armcluster
ERROR: The configuration parameter 'enable_efa' generated the following errors:
EFA currently not supported on centos8 for arm64 architecture
Info: There is a newer version 2.11.1 of AWS ParallelCluster available.
Creating stack named: parallelcluster-wrfarmcluster
Status: parallelcluster-wrfarmcluster - ROLLBACK_IN_PROGRESS
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack MasterServerSubstack Embedded stack arn:aws:cloudformation:us-east-1:815706811166:stack/parallelcluster-wrfarmcluster-MasterServerSubstack-2LMEJG6DU17G/b554b3e0-fef2-11eb-bcdf-127f049a8fed was not successfully created: The following resource(s) failed to create: [MasterServer].
    - AWS::CloudFormation::Stack parallelcluster-wrfarmcluster-MasterServerSubstack-2LMEJG6DU17G The following resource(s) failed to create: [MasterServer].
    - AWS::EC2::Instance MasterServer Received FAILURE signal with UniqueId i-0eb5995b299a6f8b4 

```
I'm not sure why this was working 2 or 3 weeks ago but not anymore.
Thanks.
