### ISSUE TITLE
Question: How does the node selection for job for multiple instance types in queues work?

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2591]
Hi!

I would like to understand how the node selection process works in multiple queue setting once I have selected queue which has more instance types.

My questions are about the multi-queue setup defined by the config at the very end below.

**1. The `sinfo` command does not display the instance types as they will be selected. Why and how to know which instance type will be selected? Is it somehow based on the CPU count?**
```
$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST 
ko*           up   infinite     32  idle~ ko-dy-c5a8xlarge-[1-9],ko-dy-c5a24xlarge-[1-3],ko-dy-c5axlarge-[1-20] 
ok          up   infinite     30  idle~ ok-dy-m4large-[1-10],ok-dy-m4xlarge-[1-10],ok-dy-m42xlarge-[1-10]

$ srun -p ko /bin/hostname
ko-dy-c5axlarge-1

$srun -p ok /bin/hostname
ok-dy-m4large-1
```

**2.  Can a user define the preference of nodes for partition in the parallel cluster config file?**
The closest thing I found is the [weight setting for slurm](https://stackoverflow.com/questions/28035631/how-do-i-set-the-order-of-nodes-for-a-slurm-job).

Is there a way how to influence e.g. this config file
```
 cat /opt/slurm/etc/pcluster/slurm_parallelcluster_ko_partition.conf 
# This file is automatically generated by pcluster

NodeName=ko-dy-c5a24xlarge-[1-3] CPUs=96 State=CLOUD Feature=dynamic,c5a.24xlarge,c5a-24xlarge
NodeName=ko-dy-c5a8xlarge-[1-9] CPUs=32 State=CLOUD Feature=dynamic,c5a.8xlarge,c5a-8xlarge
NodeName=ko-dy-c5axlarge-[1-20] CPUs=4 State=CLOUD Feature=dynamic,c5a.xlarge,c5a-xlarge

NodeSet=ko_nodes Nodes=ko-dy-c5a24xlarge-[1-3],ko-dy-c5a8xlarge-[1-9],ko-dy-c5axlarge-[1-20]
PartitionName=ko Nodes=ko_nodes MaxTime=INFINITE State=UP
```

**3. If many jobs are submitted at once e.g. in a job array: is the logic modified or is the situation handled as if the job were submitted "sequentially"?**

The config file used for experimenting with submissions:
```
[aws]
aws_region_name = ca-central-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
base_os = alinux2
key_name = parallel-cluster-master-node
vpc_settings = default

scheduler = slurm
master_instance_type = t2.small
queue_settings = ko, ok

[vpc default]
vpc_id = vpc-MASKED
master_subnet_id = subnet-MASKED

[scaling custom]
scaledown_idletime = 2

[queue ok]
compute_resource_settings = m4-large, m4-xlarge, m4-2xlarge
compute_type = spot

[queue ko]
compute_resource_settings = c5a-xlarge, c5a-8xlarge, c5a-24xlarge
compute_type = spot

[compute_resource m4-large]
instance_type = m4.large
initial_count = 0

[compute_resource m4-xlarge]
instance_type = m4.xlarge
initial_count = 0

[compute_resource m4-2xlarge]
instance_type = m4.2xlarge
initial_count = 0


[compute_resource c5a-xlarge]
instance_type = c5a.xlarge
initial_count = 0
max_count = 20

[compute_resource c5a-8xlarge]
instance_type = c5a.8xlarge
initial_count = 0

[compute_resource c5a-24xlarge]
instance_type = c5a.24xlarge
initial_count = 0
```

**Comment by enrico-usai** [comment]
Hi Ondrej,

ParallelCluster doesn't interfer with Slurm scheduling logic so you can refer to official [`srun`](https://slurm.schedmd.com/srun.html) and [job array](https://slurm.schedmd.com/job_array.html) Slurm documentation.

I can anyway share this [Multiple queue mode tutorial](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorial-mqm.html) specific for ParallelCluster.

In the tutorial you can see that: 
1. You can specify a constraint during job submission to select the instance type to be used for your job:
> `-C "[c5.2xlarge*1&t2.micro*2]"` – specifies the specific node constraints for this job. This requests one (1) c5.2xlarge node and two (2) t2.micro nodes to be used for this job.
2. The first queue you specified in the `queue_settings` parameter is configured as the default one and it will be used if you don't specify a partition during job submission.
> Note that, because you didn't specify a specific queue, the default queue (spot) is used.

Let us know if it helps.

Enrico

**Comment by oplatek** [comment]
Hi @enrico-usai,

> ParallelCluster doesn't interfer with Slurm scheduling logic so you can refer to official srun and job array Slurm documentation.

Good to know

I know about the possibilities of using the `--constraint` option and I also know about preference among queues - thank you for mentioning them.

FYI: I found more reasonable documentation from slurm for node selection
- https://slurm.schedmd.com/cpu_management.html#Step1
- https://slurm.schedmd.com/slurm.conf.html

From the documentation of slurm.conf it seems that the following resources can be specified: `The resources checked at node registration time are: CPUs, RealMemory and TmpDisk.`
From the example I mentioned above `NodeName=ko-dy-c5a24xlarge-[1-3] CPUs=96 State=CLOUD Feature=dynamic,c5a.24xlarge,c5a-24xlarge` pcluster specify only `CPUs` 
**it seems that the memory, gpus (and disc space)  are not taken into account, am I right?**

**Comment by oplatek** [comment]
@enrico-usai another question is how would you recommend introducing `weight` settings from the [slurm.conf](https://slurm.schedmd.com/slurm.conf.html) documentation into parallel cluster setup?
Should I use[ post_installation boostrap actions](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html)?

Copy paste from the documentation:
```
Weight
The priority of the node for scheduling purposes. All things being equal, jobs will be allocated the nodes with the lowest weight which satisfies their requirements. For example, a heterogeneous collection of nodes might be placed into a single partition for greater system utilization, responsiveness and capability. It would be preferable to allocate smaller memory nodes rather than larger memory nodes if either will satisfy a job's requirements. The units of weight are arbitrary, but larger weights should be assigned to nodes with more processors, memory, disk space, higher processor speed, etc. Note that if a job allocation request can not be satisfied using the nodes with the lowest weight, the set of nodes with the next lowest weight is added to the set of nodes under consideration for use (repeat as needed for higher weight values). If you absolutely want to minimize the number of higher weight nodes allocated to a job (at a cost of higher scheduling overhead), give each node a distinct Weight value and they will be added to the pool of nodes being considered for scheduling individually. The default value is 1.
```

**Comment by oplatek** [comment]
Found the details in `/opt/slurm/etc/slurm.conf`, so parallel cluster setups **SLURM so it allocates the nodes in fact based on CPU count.**

```
# TRES AND GPU CONFIG OPTIONS                                                                                                                                                                                                                                                                                                                                                                  
GresTypes=gpu                                                                                                                                                                                                                                                                                                                                                                                  
SelectType=select/cons_tres                                                                                                                                                                                                                                                                                                                                                                    
SelectTypeParameters=CR_CPU  
```

Explanation copied from the slurm cpu_management documentation
```
EXAMPLE 4: CONSUMABLE RESOURCES WITH MINIMIZATION OF RESOURCE FRAGMENTATION
A job requires 12 CPUs (12 tasks and 1 CPU per task with no overcommitment).
Allocate CPUs using the minimum number of nodes and the minimum number of sockets
required for the job in order to minimize fragmentation of allocated/unallocated CPUs in the cluster.

slurm.conf options:

SelectType=select/cons_res
SelectTypeParameters=CR_Core,CR_CORE_DEFAULT_DIST_BLOCK
```

**Comment by enrico-usai** [comment]
Hi @oplatek thanks for all the detailed comments.

> **it seems that the memory, gpus (and disc space) are not taken into account, am I right?**

* Memory: you can find a discussion here: https://github.com/aws/aws-parallelcluster/issues/2198
* Gpus: ParallelCluster sets gpu information in the `/opt/slurm/etc/pcluster/slurm_parallelcluster_compute_gres.conf` file.

> **another question is how would you recommend introducing weight settings from the slurm.conf documentation into parallel cluster setup?**

You can modify Slurm config under `/opt/slurm/etc/pcluster/` and configure a `Weight` for each node with a post install action. ParallelCluster will not override configs under `/opt/slurm/etc/pcluster/` until you perform a cluster update.  See similar request here: https://github.com/aws/aws-parallelcluster/issues/2054#issuecomment-698478278

> **so parallel cluster setups SLURM so it allocates the nodes in fact based on CPU count.**

Yes, CPUs is the basic information we are using as a consumable resource. We're using `select/cons_tres` plugin that is an efficient way to permit multiple jobs to be co-scheduled on nodes when resources permit it (you can anyway use the `--exclusive` srun option if needed).

`cons_tres` plugin provides all the same functionality provided by `cons_res` plugin plus additional functionality specifically related to GPUs: https://slurm.schedmd.com/cons_res.html 

Enrico

**Comment by oplatek** [comment]
Thank you @enrico-usai very helpful comments! -- closing the issue - I learned what I needed.
