### ISSUE TITLE
Compatibility with higher Python

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#2594]
Hello,
I was wondering if future versions will be compatible with Python 3.9 and higher. Or in other words, is there any timeline for upgrading Python in the base AMIs for the different OSs? I am using mostly CentOS8 with some AL2 & Ubuntu and the most recent Python version in any of them seems to be 3.6.
Thanks.

**Comment by enrico-usai** [comment]
Hi @afernandezody,
actually we're installing python [from official repo](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/attributes/default.rb#L285), but you are free to upgrade/change it with a [custom post install script](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html).

**Comment by afernandezody** [comment]
Hi @**enrico-usai** ,
The thing is that using a custom AMI with python upgraded to 3.9 led chef to crash during cluster launch. Using a postscript to upgrade Python is certainly feasible but then you need to also install any app or dependency based on Python, which can range from a few second to several hours. I'm not sure if there is a some workaround to it but, otherwise, maybe it could be a requested feature (compatibility between Python 3.9 and newer ones with aws-parallelcluster/chef launcher). Thanks.

**Comment by enrico-usai** [comment]
Thanks for explaining your use case. 

I think you can leave in the custom AMI both the packages (python and python3) to avoid the crash. Can you share the log of the chef crash? It can be interesting to see if there is something we can fix there or a workaround to share.

An alternative to achieve the result is to create [a custom cookbook](https://docs.aws.amazon.com/parallelcluster/latest/ug/custom_cookbook.html) (by removing python and python-pip dependencies) and then [create a custom ami](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.createami.html) by passing the custom cookbook, but it's an advanced task that can lead in unexpected behaviours.

In any case I think it's an interesting feature request. I'm adding the label to this ticket.
