### ISSUE TITLE
/home vs /shared for sharing files?

### ISSUE THREAD

**Issue by calebwin** [aws/aws-parallelcluster#2609]
I want files to be shared between the master and compute nodes. My understanding is that by default, a single 20 GiB EBS volume is mounted at `/shared` on the head node and shared among all nodes. But it seems like files in `/home` are also shared. Is my understanding correct and if so where should I expect the EBS volume to be mounted by default?

**Comment by enrico-usai** [comment]
Hi Caleb,
it's correct. ParallelCluster automatically exports from the head node:
* `/home` --> root volume of the head node
* all the mount dirs for shared EBS volumes (1 additional EBS volume is attached by default to the head node and exported by using `/shared` mount point),
* all the mount dirs for shared RAID volumes (if configured).

You can find the details in the [head_node_base_config.rb cookbook recipe](https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.10.3/recipes/head_node_base_config.rb#L122).

**Comment by calebwin** [comment]
Thank you! And so is the default storage 20 GiB? Would upgrading it be done by creating an EBS volumes in AWS console and then specifying it in the cluster configuration?

**Comment by enrico-usai** [comment]
Yes, default size is 20 GB. The following links should clarify ParallelCluster behaviour:
* https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#cluster-shared-dir
* https://docs.aws.amazon.com/parallelcluster/latest/ug/ebs-section.html
