### ISSUE TITLE
FSX Luster FileSystem for Ubuntu 18.04 is mounted with root permissions

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2635]
**Bug description**
The `fsx` file system is mounted as `root`.
Expected behaviour: it would be much better if the file system was mounted under the owner `ubuntu` permissions (ubuntu is the default user on Ubuntu 18.04). 
Workaround: `chown -R ubuntu:ubuntu /fsx` will be time-consuming on several TB of storage in FSX.

```
$ ls -al /fsx
total 37
drwxrwxrwt  3 root root 33280 Jan  1  1970 .
drwxr-xr-x 26 root root  4096 Apr 12 20:13 ..

ubuntu@ip-10-0-9-119:~$ df -h
Filesystem                Size  Used Avail Use% Mounted on
udev                      7.9G     0  7.9G   0% /dev
tmpfs                     1.6G  936K  1.6G   1% /run
/dev/xvda1                 25G   16G  9.0G  63% /
...
10.0.2.243@tcp:/jxqj7bmv  1.1T  4.5M  1.1T   1% /fsx
```

To reproduce the behavior run `pcluster create -c test.conf test` with the configuration below and the commands which created the output above.

**Required Info:**
 - AWS ParallelCluster version 2.10.3
 - Cluster name: test
 - Cluster config
```
# test.conf
[aws]
aws_region_name = us-east-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
base_os = ubuntu1804
key_name = pcluster-key
fsx_settings = lustrefs


scheduler = slurm
master_instance_type = m4.xlarge  # consider m5a instances for larger clusters
compute_instance_type = m4.xlarge

vpc_settings = default

[vpc default]
vpc_id = vpc-08f04318f9ae8c7b0
master_subnet_id = subnet-0521a5bd52465f5a6


[fsx lustrefs]
shared_dir = /fsx
storage_capacity = 1200
deployment_type = SCRATCH_2
```

**Comment by lukeseawalker** [comment]
Hello @oplatek,
I'm not sure I get your question correctly.

Even if the fsx file system is mounted as root, I'm able to write data into it as the user I'm using, i.e.
```
ubuntu@ip-172-31-30-150:~$ ls -la /fsx
total 33
drwxrwxrwt 3 root root 33280 Jan  1  1970 .

ubuntu@ip-172-31-30-150:~$ touch /fsx/myFile

ubuntu@ip-172-31-30-150:~$ ls -la /fsx
total 37
drwxrwxrwt  3 root   root   33280 Apr 15 11:24 .
drwxr-xr-x 26 root   root    4096 Apr 15 11:23 ..
-rw-rw-r--  1 ubuntu ubuntu     0 Apr 15 11:24 myFile
```

Can you better explain what is your use case?

Thanks
L

**Comment by oplatek** [comment]
Hi @lukeseawalker, that's interesting.

I thought the problem was that the disc is mounted as root.

Maybe I tested the problem with a configuration where I also used `import_path` and `export_path`.
```
[fsx mylustresettings]
shared_dir = /fsx
import_path = s3://mybucket
export_path = s3://mybucket
```

Closing the issue right now, I will reopen it and update it once I know more.

**Comment by oplatek** [comment]
Hi @lukeseawalker, I just want to confirm that there is no issue.
Sorry for the confusion, I have no idea how I got the permissions error.

Even if the fsx file system is mounted as root, I'm able to write data into it as the user I'm using as well. :)

**Comment by lukeseawalker** [comment]
Hi @oplatek,
glad to hear that and thank you for the update.
