### ISSUE TITLE
Question: Update Slurm partition node count live

### ISSUE THREAD

**Issue by keien** [aws/aws-parallelcluster#2653]
Just a question - do you have any suggestions for how we might update the node count of a given instance in a Slurm partition live, without having to recreate the cluster? For example, if I have a partition like the following:
```
$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
cpu*         up   infinite     41  idle~ cpu-dy-m54xlarge-[1-19],cpu-dy-m512xlarge-[1-12],cpu-dy-m524xlarge-[1-10]
```
and I wanted to change this so it has `cpu-dy-m54xlarge-[1-50]`, bumping up the 4xl count to 50 - before with ASGs I could edit the corresponding ASG live to increase the max instance count and that would do it. I can tell it would be a lot harder to do with how these Slurm partitions are set up, but is there any way to do this?

**Comment by hanwen-pcluste** [comment]
Hello Keien,

You could use [pcluster update](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.update.html) to update your cluster with an updated configuration file.
To bump up the 4xl count to 50, you could change the [max_count in the compute_resource](https://docs.aws.amazon.com/parallelcluster/latest/ug/compute-resource-section.html) and run `pcluster update`

Hanwen

**Comment by keien** [comment]
ah, I didn't realize this was one of the things that `pcluster update` could do live - thanks
