### ISSUE TITLE
Random failure in compute node during chef installation

### ISSUE THREAD

**Issue by mohanasudhan** [aws/aws-parallelcluster#266]
I have seen this couple of time (auto scaling instance is provisioned but it fails during cfn init), when i retry same configuration cfncluster creation is successful. 

Here is my configuration

[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = us-east-1
aws_access_key_id = <>
aws_secret_access_key = <>

## cfncluster templates
[cluster default]
base_os = ubuntu1404
key_name = mohgan
compute_instance_type = c4.4xlarge
master_instance_type = c4.4xlarge
initial_queue_size = 1
max_queue_size = 1
maintain_initial_size = true
scheduler = torque
cluster_type = ondemand
ec2_iam_role = Ec2Role
vpc_settings = public

## VPC Settings
[vpc public]
vpc_id = vpc-38ad7541
master_subnet_id = subnet-22de0078

Compute instance fails in cfn-init. Here is the logs. 

2017-12-01 18:45:36,029 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2017-12-01 18:45:36,029 [DEBUG] Describing resource ComputeServerLaunchConfig in stack cfncluster-tester-c4-5
2017-12-01 18:45:36,152 [INFO] -----------------------Starting build-----------------------
2017-12-01 18:45:36,153 [DEBUG] Not setting a reboot trigger as scheduling support is not available
2017-12-01 18:45:36,153 [INFO] Running configSets: default
2017-12-01 18:45:36,154 [INFO] Running configSet default
2017-12-01 18:45:36,156 [INFO] Running config deployConfigFiles
2017-12-01 18:45:36,156 [DEBUG] No packages specified
2017-12-01 18:45:36,156 [DEBUG] No groups specified
2017-12-01 18:45:36,156 [DEBUG] No users specified
2017-12-01 18:45:36,156 [DEBUG] No sources specified
2017-12-01 18:45:36,156 [DEBUG] Writing content to /etc/chef/client.rb
2017-12-01 18:45:36,156 [DEBUG] Setting mode for /etc/chef/client.rb to 000644
2017-12-01 18:45:36,156 [DEBUG] Setting owner 0 and group 0 for /etc/chef/client.rb
2017-12-01 18:45:36,157 [DEBUG] Writing content to /tmp/dna.json
2017-12-01 18:45:36,157 [DEBUG] Content will be serialized as a JSON structure
2017-12-01 18:45:36,157 [DEBUG] Setting mode for /tmp/dna.json to 000644
2017-12-01 18:45:36,157 [DEBUG] Setting owner 0 and group 0 for /tmp/dna.json
2017-12-01 18:45:36,157 [DEBUG] Writing content to /tmp/extra.json
2017-12-01 18:45:36,157 [DEBUG] Setting mode for /tmp/extra.json to 000644
2017-12-01 18:45:36,157 [DEBUG] Setting owner 0 and group 0 for /tmp/extra.json
2017-12-01 18:45:36,157 [DEBUG] Running command jq
2017-12-01 18:45:36,157 [DEBUG] No test for command jq
2017-12-01 18:45:36,245 [INFO] Command jq succeeded
2017-12-01 18:45:36,245 [DEBUG] Command jq output:
2017-12-01 18:45:36,246 [DEBUG] Running command mkdir
2017-12-01 18:45:36,246 [DEBUG] No test for command mkdir
2017-12-01 18:45:36,248 [INFO] Command mkdir succeeded
2017-12-01 18:45:36,248 [DEBUG] Command mkdir output:
2017-12-01 18:45:36,248 [DEBUG] Running command touch
2017-12-01 18:45:36,248 [DEBUG] No test for command touch
2017-12-01 18:45:36,250 [INFO] Command touch succeeded
2017-12-01 18:45:36,250 [DEBUG] Command touch output:
2017-12-01 18:45:36,250 [DEBUG] No services specified
2017-12-01 18:45:36,252 [INFO] Running config getCookbooks
2017-12-01 18:45:36,252 [DEBUG] No packages specified
2017-12-01 18:45:36,252 [DEBUG] No groups specified
2017-12-01 18:45:36,252 [DEBUG] No users specified
2017-12-01 18:45:36,252 [DEBUG] No sources specified
2017-12-01 18:45:36,252 [DEBUG] No files specified
2017-12-01 18:45:36,252 [DEBUG] Running command berk
2017-12-01 18:45:36,252 [DEBUG] No test for command berk
2017-12-01 18:47:16,869 [ERROR] Command berk (. /tmp/proxy.sh; for d in `ls /tmp/cookbooks`; do cd /tmp/cookbooks/$d;LANG=en_US.UTF-8 /opt/chef/embedded/bin/berks vendor /etc/chef/cookbooks; done ) failed
2017-12-01 18:47:16,869 [DEBUG] Command berk output: Resolving cookbook dependencies...
Fetching 'cfncluster' from source at .
Fetching cookbook index from https://supermarket.getchef.com...
Installing apt (6.1.4) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing compat_resource (12.19.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing hostname (0.4.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing hostsfile (3.0.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing iptables (4.3.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing line (0.6.3) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing mingw (2.0.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing build-essential (8.0.4) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Using cfncluster (1.4.0) from source at .
Installing openssh (2.4.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing poise (2.8.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing poise-archive (1.5.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing poise-languages (2.1.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing poise-python (1.6.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing ohai (5.2.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing seven_zip (2.0.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing sysctl (0.10.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing tar (2.0.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing windows (3.4.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing yum (5.0.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing yum-epel (2.1.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader/entry.rb:74:in `rescue in full_name': tar is corrupt, name contains null byte (Gem::Package::TarInvalidError)
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader/entry.rb:67:in `full_name'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:28:in `block (2 levels) in extract'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader.rb:65:in `each'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:27:in `block in extract'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader.rb:29:in `new'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:118:in `reader'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:25:in `extract'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive.rb:33:in `extract'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/community_rest.rb:16:in `unpack'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/community_rest.rb:102:in `download'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/downloader.rb:66:in `try_download'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/downloader.rb:40:in `block in download'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/downloader.rb:39:in `each'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/downloader.rb:39:in `download'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/installer.rb:106:in `install'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'

        from (celluloid):0:in `remote procedure call'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/future.rb:104:in `value'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/future.rb:68:in `value'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/installer.rb:176:in `map'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/installer.rb:176:in `install_from_universe'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/installer.rb:40:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/berksfile.rb:422:in `install'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/berksfile.rb:631:in `block in vendor'
        from /opt/chef/embedded/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/berksfile.rb:629:in `vendor'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/cli.rb:399:in `vendor'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/cli.rb:52:in `dispatch'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/cli.rb:27:in `execute!'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/bin/berks:5:in `<top (required)>'
        from /opt/chef/embedded/bin/berks:22:in `load'
        from /opt/chef/embedded/bin/berks:22:in `<main>'
E, [2017-12-01T18:47:16.786061 #1763] ERROR -- : Actor crashed!
Gem::Package::TarInvalidError: tar is corrupt, name contains null byte
        /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader/entry.rb:74:in `rescue in full_name'
        /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader/entry.rb:67:in `full_name'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:28:in `block (2 levels) in extract'
        /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader.rb:65:in `each'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:27:in `block in extract'
        /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/package/tar_reader.rb:29:in `new'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:118:in `reader'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:25:in `extract'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive.rb:33:in `extract'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/community_rest.rb:16:in `unpack'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/community_rest.rb:102:in `download'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/downloader.rb:66:in `try_download'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/downloader.rb:40:in `block in download'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/downloader.rb:39:in `each'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/downloader.rb:39:in `download'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/berkshelf-5.6.4/lib/berkshelf/installer.rb:106:in `install'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
        (celluloid):0:in `remote procedure call'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:41:in `_send_'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/pool_manager.rb:140:in `method_missing'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'

2017-12-01 18:47:16,869 [ERROR] Error encountered during build of getCookbooks: Command berk failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command berk failed
2017-12-01 18:47:16,993 [ERROR] -----------------------BUILD FAILED!------------------------
2017-12-01 18:47:16,993 [ERROR] Unhandled exception during build: Command berk failed
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command berk failed

**Comment by soniagarden** [comment]
I'm having the same issue. Happens about 10% of time when spinning off a new compute node. The first error is in command berk. Any thoughts?


...
2018-08-08 13:00:53,532 [DEBUG] Running command berk
2018-08-08 13:00:53,532 [DEBUG] No test for command berk
2018-08-08 13:01:46,595 [ERROR] **Command berk (. /tmp/proxy.sh; for d in `ls /tmp/cookbooks`; do cd /tmp/cookbooks/$d;LANG=en_US.UTF-8 /opt/chef/embedded/bin/berks vendor /etc/chef/cookbooks; done ) failed**
2018-08-08 13:01:46,595 [DEBUG] Command berk output: Resolving cookbook dependencies...
Fetching 'cfncluster' from source at .
Fetching cookbook index from https://supermarket.getchef.com...
Installing apt (6.1.4) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing build-essential (8.0.4) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Using cfncluster (1.4.1) from source at .
Installing compat_resource (12.19.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing hostname (0.4.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing hostsfile (3.0.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing iptables (4.3.4) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing line (0.6.3) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing mingw (2.1.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing ohai (5.2.3) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing openssh (2.4.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing poise (2.8.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing poise-archive (1.5.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing poise-languages (2.1.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing poise-python (1.6.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing seven_zip (3.0.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing sysctl (0.10.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing tar (2.0.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing windows (5.0.0) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing yum (5.0.1) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
Installing yum-epel (2.1.2) from https://supermarket.getchef.com/ ([opscode] https://supermarket.chef.io:443/api/v1)
/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (OpenSSL::SSL::SSLError)
        from /opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from /opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from /opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:852:in `start'

**Comment by mauri-melato** [comment]
I see `Using cfncluster (1.4.1) from source at .` in your `cfn-init.log`. 
Could you try to create a new cluster with the latest version of CfnCluster 1.5.2 ? 
Please run `pip install --upgrade cfncluster` for upgrading.

**Comment by soniagarden** [comment]
Thanks for replying.  Would this upgrade automatically apply to existing clusters or just to new clusters?

**Comment by mauri-melato** [comment]
New clusters will use updated AMIs, cookbooks, sw packages
