### ISSUE TITLE
Use "pcluster configure" to create a subnet in preferred availibility zone

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2660]
Hi there!

I recently hit a workflow where I use `pcluster configure`, especially the part for subnet creation automation to create a subnet under VPC.
However, AFAIK I cannot specify the (preferred) Availability Zone in the process.

**Why is the ability to specify Availability Zone important?**
Some spot instances e.g c5n, g4dn or p3 instances are not supported in all availability zones,
so if your parallel cluster configuration uses such instances and the "randomly" assigned availability zone does not support the instances, your configuration is not usable.

I think it would be a great new feature, hopefully quite easy to implement.

Thank you for a really cool work on pcluster!

Ondra

**Comment by hanwen-pcluste** [comment]
Hi Ondra,

Thank you for the suggestion. We've received [similar requests](https://github.com/aws/aws-parallelcluster/issues/2090). We would mark this issue as a feature request and take it into account in our development.

Hanwen

**Comment by enrico-usai** [comment]
I'm going to close this in favour of https://github.com/aws/aws-parallelcluster/issues/2090  to avoid having two issues related to the same feature enhancement. Thanks
