### ISSUE TITLE
FSX slows down instance startup times when import_path from S3 is used and post_install script uses FSX

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2661]
**Why the [lazy loading from S3](https://www.hpcworkshops.com/04-amazon-fsx-for-lustre/03-lazy-loading.html) influences the startup time of new nodes?**
Please, see below documented three cases documenting that a startup time of node is greatly increased (~30min vs 3min) if FSX with `import_path` is used.
- The `case A` documents the problem. See the startup time at the very end and it uses the whole configuration below
- In the `case B` I wanted to see what is the influence of just removing the `import_path` from the configuration. The lines with the comment `# COMMENTED OUT IN CASE B` were commented out in this case. See the much improved times below.
- In the `case C` I wanted to see what is the influence if the FSX is not used at all. The difference between `C` and `B` is minimal. I include it just as a baseline and for reference.

**Required Info:**
- `$ pcluster version   # outputs 2.10.3`
- This configuration has three variants A, B, C see lines with `COMMENTED OUT IN CASE B/C` for the variants
``` 
[aws]
aws_region_name = us-east-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
base_os = ubuntu1804
key_name = MASKED
fsx_settings = lustrefs             # COMMENTED OUT IN CASE C
additional_iam_policies = arn:aws:iam::aws:policy/AmazonFSxFullAccess  # See https://github.com/aws/aws-parallelcluster/issues/1795 and post_install.sh
post_install = s3://MASKED/post-install/post_install.sh


scheduler = slurm
master_instance_type = c5n.xlarge
queue_settings = g4dn-nxlarge, p3-nxlarge, c5n-nxlarge

s3_read_resource = *
s3_read_write_resource = *

vpc_settings = default

[vpc default]
vpc_id = vpc-MASKED
master_subnet_id = subnet-MASKED # us-east-1a
additional_sg = sg-MASKED  # allow mosh-udp-range group

[queue c5n-nxlarge]
compute_resource_settings = c5n-xlarge, c5n-2xlarge, c5n-9xlarge
disable_hyperthreading = true
compute_type = spot

[queue g4dn-nxlarge]
compute_resource_settings = g4dn-xlarge, g4dn-2xlarge, g4dn-12xlarge
disable_hyperthreading = true
compute_type = spot

[queue p3-nxlarge]
compute_resource_settings = p3-2xlarge, p3-8xlarge, p3-16xlarge
disable_hyperthreading = true
compute_type = spot

[compute_resource c5n-xlarge]
instance_type = c5n.xlarge
initial_count = 0
max_count = 5

[compute_resource c5n-2xlarge]
instance_type = c5n.2xlarge
initial_count = 0
max_count = 5

[compute_resource c5n-9xlarge]
instance_type = c5n.9xlarge
initial_count = 0
max_count = 2

[compute_resource g4dn-xlarge]
instance_type = g4dn.xlarge
initial_count = 0
max_count = 10

[compute_resource g4dn-2xlarge]
instance_type = g4dn.2xlarge
initial_count = 0
max_count = 10

[compute_resource g4dn-12xlarge]
instance_type = g4dn.12xlarge
initial_count = 0
max_count = 1

[compute_resource p3-2xlarge]
instance_type = p3.2xlarge
initial_count = 0
max_count = 5

[compute_resource p3-8xlarge]
instance_type = p3.8xlarge
initial_count = 0
max_count = 2

[compute_resource p3-16xlarge]
instance_type = p3.16xlarge
initial_count = 0
max_count = 2


[fsx lustrefs]
shared_dir = /fsx
storage_capacity = 1200
auto_import_policy = NEW_CHANGED                  # COMMENTED OUT IN CASE B
import_path =  s3://pcluster-fsx-import-export    # COMMENTED OUT IN CASE B
export_path =  s3://pcluster-fsx-import-export    # COMMENTED OUT IN CASE B
deployment_type = SCRATCH_2

```

## The speed of getting a node without FSX - a baseline - `case C`
```
$ time srun -p c5n-nxlarge /bin/hostname     # first time usage
c5n-nxlarge-dy-c5nxlarge-1
real	2m34.792s
user	0m0.005s
sys	0m0.029s

$ time srun /bin/hostname      # first time usage
g4dn-nxlarge-dy-g4dnxlarge-1
real	2m51.224s
user	0m0.014s
sys	0m0.017s
```
## The speed of getting a node wit a FXX without import from S3 - `case B`

```
$ time srun -p c5n-nxlarge /bin/hostname   # first time usage
c5n-nxlarge-dy-c5nxlarge-1
real    2m57.735s
user    0m0.015s
sys     0m0.016s

$ time srun -p p3-nxlarge /bin/hostname   # first time usage
p3-nxlarge-dy-p32xlarge-1
real    3m21.756s
user    0m0.019s
sys     0m0.012s
```
## The speed of getting a node with a FSX with import from S3 used - `case A`
```
$ time srun -p c5n-nxlarge /bin/hostname   # first time usage
c5n-nxlarge-dy-c5nxlarge-1
real    22m33.253s
user    0m0.023s
sys     0m0.043s

$ time srun -p p3-nxlarge /bin/hostname   # first time usage
p3-nxlarge-dy-p32xlarge-1
real    28m3.841s
user    0m0.028s
sys     0m0.045s
```

**Comment by oplatek** [comment]
Note: that I have not [preloaded any data](https://docs.aws.amazon.com/fsx/latest/LustreGuide/preload-file-contents-hsm.html) there was ~100GB in /fsx filesystem.

**Comment by hanwen-pcluste** [comment]
Hi Ondra,

I tried to use the following configuration file to create clusters, and used a S3 bucket with 20GB content.
```
[aws]
aws_region_name = us-east-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
key_name = rampup
scheduler = slurm
master_instance_type = t2.micro
base_os = alinux2
vpc_settings = default
queue_settings = compute
fsx_settings = lusterfsx    # COMMENTED OUT IN CASE C

[vpc default]
vpc_id = vpc-xxx
master_subnet_id = subnet-xxx
compute_subnet_id = subnet-yyy

[queue compute]
compute_resource_settings = default

[compute_resource default]
instance_type = t2.micro

[fsx lusterfsx]
shared_dir = /fsx
storage_capacity = 1200
auto_import_policy = NEW_CHANGED                  # COMMENTED OUT IN CASE B
import_path =  s3://pcluster-fsx-import-export    # COMMENTED OUT IN CASE B
export_path =  s3://pcluster-fsx-import-export    # COMMENTED OUT IN CASE B
deployment_type = SCRATCH_2
```
I couldn't reproduce the slowdown when launching compute nodes. According to our [official document](https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html#fsx-import-path), lazy loading is on by default.
I noticed you used a post_install script for the cluster creation. Could you check if the script is trying to access some files in the FSx?
I was also wondering if you run `time srun -p c5n-nxlarge /bin/hostname` and `time srun -p p3-nxlarge /bin/hostname` in the same cluster? If it was the FSx file loading issue, the first command should've already loaded the data from S3 to FSx and the second command wouldn't take so long, right?
I will try to use a more similar configuration file to yours to try to reproduce it again.

Thank you!
Hanwen

**Comment by oplatek** [comment]
Hi @hanwen-pcluste !

I have run 
```
time srun -p c5n-nxlarge /bin/hostname 
# and
time srun -p p3-nxlarge /bin/hostname
```
in the same cluster.

However, it is a good point that I should try to eliminate using the `post_install` script for FSX operations.
The script used `aws s3 sync` command to synchronize one git repository.

I will try it out and get back to you.
Thank you for the tip!

**Comment by oplatek** [comment]
Hi @hanwen-pcluste,

you were right. Once I simplified the post_install script to be used only on the master node
the times improved to the expected ranges

```
time srun -p c5n-nxlarge /bin/hostname
c5n-nxlarge-dy-c5nxlarge-1

real	2m51.876s
user	0m0.011s
sys	0m0.017s

time srun -p p3-nxlarge /bin/hostname
p3-nxlarge-dy-p32xlarge-1

real	2m51.204s
user	0m0.007s
sys	0m0.021s
```
