### ISSUE TITLE
Multiple queue setup: ERROR: Multiple reference to section ...

### ISSUE THREAD

**Issue by rems0** [aws/aws-parallelcluster#2665]
Hi all,

I am trying to create a multiqueue cluster with 5 queues and 3 compute_resources per queue using AWS ParallelCluster version 2.10.3 .
Some queues use the same instance_types, because one queue is for spot and the other is ondemand:

A simplified example:
```
[cluster default]
queue_settings = queue_spot, queue_ondemand

[queue queue_spot]
compute_type = spot
compute_resource_settings = cr_1, cr_2, cr_3

[queue queue_ondemandl]
compute_type = ondemand
compute_resource_settings = cr_1, cr_2, cr_3

[compute_resource cr_1]
instance_type = ...

[compute_resource cr_2]
instance_type = ...

[compute_resource cr_3]
instance_type = ...

```

But when I run `pcluster create my_cluster` I get the following error message:
`ERROR: Multiple reference to section '[cr_1]'. Only one reference to each section is allowed from the same configuration file.`

Do I have to duplicate all `compute_resource` settings even if they are the same?
Should this possibility be added as a new feature?

Kind regards,
Richard

**Comment by hanwen-pcluste** [comment]
Hi Richard,

Unfortunately you have to duplicate all the `compute_resource`. We would mark it as a feature request and consider it during our development.

Thank you!
Hanwen

**Comment by enrico-usai** [comment]
I'm going to close this issue because we implemented a new configuration format for ParallelCluster 3.x.
It is YAML and it is possible to use [anchors and aliases](https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases).
We're not going to extend current 2.11 behaviour.
