### ISSUE TITLE
Question: What is the default AMI build workflow for pcluster and what version of software to expect?

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2671]
Hi there!

I am trying to figure out if the default version of AMI is enough for us in long-term or we should switch to building custom AMIs.

In particular, I am interested in Nvidia GPU card Driver and optionally also for pre-installed CUDA support.
Note that the Nvidia GPU card driver determines [Compute Capability](https://en.wikipedia.org/wiki/CUDA#GPUs_supported) which influences supported CUDA version even if installed manually.

I figured out that:
- Here is the list of currently supported list of [AMIs](https://github.com/aws/aws-parallelcluster/blob/develop/amis.txt)
- The pcluster AMIs are based on [deep learning AMIs](https://github.com/aws/aws-parallelcluster/blob/f7d53fb6a99fdc0dd0aa59a80efff80b5fb27a26/tests/integration-tests/tests/common/utils.py#L41)
- The [ubuntu 18.04 release notes states that the latest CUDA supported is 11.0](https://aws.amazon.com/releasenotes/aws-deep-learning-ami-ubuntu-18-04/)
- [There should be multiple CUDA versions available ](https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-base.html)

My questions:
- Are the pcluster AMIs.txt updated with every release of the deep learning AMIs?
- Are the deep learning AMIs.txt stripped? I do not see so many versions of CUDA?

**Comment by pzelasko** [comment]
Cool. I think for the short-mid term this setup is sufficient. Having CI that auto builds our own AMI in some regular time intervals might be good in the long term but I don’t want us to spend effort on this yet.

**Comment by hanwen-pcluste** [comment]
Hi Ondra

Thank you for the clear question. ParallelCluster use vanilla ubuntu AMI to build parallelcuster cluster. You can see how we are filtering the base AMI at [here](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/amis/packer_ubuntu1804.json#L31). And we are [installing CUDA in our cookbook recipes](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/attributes/default.rb#L133)
The code that you pointed out using deep learning AMIs is the integration test code where we are testing creatami command.
The AMIs.txt is only updated for each release of ParallelCluster

What do you mean by asking if the AMIs.txt is stripped?

Thanks
Hanwen

**Comment by oplatek** [comment]
Hi @hanwen-pcluste,

really appreciated the links to the code! All clear now :)

> What do you mean by asking if the AMIs.txt is stripped?

This is actually an irrelevant question because as you explained you install [cuda in the cookbook recipes](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/attributes/default.rb#L133), and you use the deep learnings AMIs only for integration testing.

I see that in [cookbook recipes](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/attributes/default.rb#L133) you plan to use driver version `460.73.01` and the preinstalled cuda with `11.3`.
Any ETA of this be part of an aws-parallelcluster release? Really just an estimate is enough.

**Comment by rexcsn** [comment]
Hi @oplatek,

Upgrade for NVIDIA packages is planned as part of our next release.
Unfortunately we cannot give an ETA.

Thank you.
