### ISSUE TITLE
[ Enhancement request ] add optional slurmdbd support

### ISSUE THREAD

**Issue by rems0** [aws/aws-parallelcluster#2681]
Hi all, 

first, thanks for AWS ParallelCluster, works great!

In my use case it would be good to have slurmdbd running.
I see the executable is there, but I've found no systemd unit script under /opt/slurm or /etc/systemd/system.
I think having the option to enable automatically slurmdbd on the config script would be a niche to have feature.

Many thanks again for ParallelCluster!

Kind regards,
Richard

**Comment by yuleiwan** [comment]
Hi Richard,

Thanks for your acknowledgement! Do you want to enable slurmdbd for slurm accounting or other propose? There is a post about how to setup slurm accounting in parallelcluster https://github.com/aws/aws-parallelcluster/issues/1494, but currently we don't have a plan to officially support accounting.

Best,
Yulei

**Comment by rems0** [comment]
Hi Yulei,

yes, job accounting. Being able to check data for jobs that ran a few hours or minutes ago but already disappeared from the output of `scontrol show jobs` is often very useful.
I will check that post, thanks.

Best,
Richard
