### ISSUE TITLE
Create a command to query the current config for a running cluster

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-parallelcluster#2700]
A command to query the current config for a running cluster would help immensely. E.g., `pcluster show-config mycluster`

_Originally posted by @bollig in https://github.com/aws/aws-parallelcluster/issues/1639#issuecomment-638365973_

**Comment by demartinofra** [comment]
This is available in ParallelCluster 3 where you can get the cluster config as part of the `pcluster describe-cluster` response.
