### ISSUE TITLE
MPI with EFA support for GPUDirect RDMA

### ISSUE THREAD

**Issue by tbrandvik** [aws/aws-parallelcluster#2703]
I am trying to take advantage of EFA support for GPUDirect RDMA. 

I am running with Parallel Cluster 2.10.1 using a p4d.24xlarge compute node running CentOS 8 with both "enable_efa" and "enable_efa_gdr" set to true in the config file.

I am wondering if there is any guidance on which options to give to mpirun when launching MPI applications to take advantage of this feature (I am using the Open-MPI that comes pre-installed in /opt/amazon/openmpi/)? Is GPUDirect RDMA supported through MPI or is it only for applications that use NCCL directly?

Thanks in advance for any help!

**Comment by yuleiwan** [comment]
Hi @tbrandvik,
GPUDirect RDMA is supported in OpenMPI and this feature is released since Open MPI v1.7.4, you can find details in this document https://www.open-mpi.org/faq/?category=runcuda. It also includes how to use this feature with which option.

**Comment by tbrandvik** [comment]
Hi @yuleiwan,

Many thanks for the quick reply! It sounds like the best approach is to build a separate version of Open-MPI to that which is already installed - is that what you would recommend as well?

**Comment by rexcsn** [comment]
Hi @tbrandvik ,

Latest pcluster release v2.10.3 comes with OpenMPI 4.1.0, which would support GPUDirect RDMA, since all OpenMPI versions >= v1.7.4(ancient) should support the feature.
I don't think you would need to build a separate version of OpenMPI.

Thanks.

**Comment by tbrandvik** [comment]
Hi @rexcsn,

The problem is that the default Open-MPI version does not come with CUDA support: https://github.com/aws/aws-parallelcluster/issues/1162 

It would be great to have it included, but I will try to compile a separate version of Open-MPI with support for GPUDirect RDMA for EFA.

**Comment by demartinofra** [comment]
If there are no pending action items on our side I'm going to resolve this. Feel free to reopen if I missed anything
