### ISSUE TITLE
[Feature Request] Support GP3 and custom volume size on Master node boot volume

### ISSUE THREAD

**Issue by MikeKroell** [aws/aws-parallelcluster#2759]
With GP3 out, we would like to take advantage of GP3 on the head node. By allowing GP3 we can get the full 3000 IOPS from the EBS volume, lower cost, and lower the size of the volume if a deployment warrants a smaller volume. It appears that GP3 and Custom sizes are already supported on the additional EBS volumes as shared NFS.

**Version:** 2.10.4
**Workaround:** No workaround available
**Proposed Fix:** Create a parameter in the config file for size and type and associated parameters in the Cloudformation. GP3 could reasonably become the default type.

**Comment by zeekus** [comment]
It appears you can only use this currently if the volume_type is defined in the EBS section. I attempted to setup gp3 in my cluster configuration area and got the following errors: 

ERROR: The configuration parameter 'volume_type' is not allowed in the [compute_resource default] section
ERROR: The configuration parameters 'volume_type' are not allowed in the [cluster slurmworker] section

It would be a nice feature to a future release. Currently, the OS drives all mount as gp2 by default on the compute and controller nodes. AWS customers could benefit from the a 20% savings on OS drive storage in addition to the performance increase.

**Comment by lukeseawalker** [comment]
Hi @MikeKroell and @zeekus,
thank you for your interest.
Your request make sense, I'm marking this as feature enh.
For the volume size, you can already choose size for both root volume of head node and compute node, using
[master-root-volume-size](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#master-root-volume-size) and [compute-root-volume-size](https://docs.aws.amazon.com/parallelcluster/latest/ug/cluster-definition.html#compute-root-volume-size).

Thanks,
Luca

**Comment by hanwen-pcluste** [comment]
Hi Mike and Teddy,

Starting with ParallelCluster 3.x, specifying root volume type is supported on [head node](https://docs.aws.amazon.com/parallelcluster/latest/ug/HeadNode-v3.html#HeadNode-v3-LocalStorage) and [Slurm compute nodes](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#Scheduling-v3-SlurmQueues-ComputeSettings)

Thank you,
Hanwen
