### ISSUE TITLE
cfncluster node update fails due to missing EC2 IAM policy actions

### ISSUE THREAD

**Issue by jmenbo** [aws/aws-parallelcluster#276]
cfncluster version 1.4.1 requires the following **additional** EC2 IAM policy actions in order to perform EC2 instance updates that require restarting the instance, i.e. changing instance type

> "ec2:StopInstances",
> "ec2:ModifyInstanceAttribute",
> "ec2:StartInstances"

This should be added to the **CfnClusterUserPolicy** under the Ec2Modify section

**Comment by mohanasudhan** [comment]
Starting version 1.4.0, we changed stop/start behaviour of cfncluster. We no longer stop master instance as part cfncluster-stop (we only set compute-node Auto-scaling property to 0 to shrink it down). Hence I feel following permission doesn't make sense now. If I am wrong, @jmenbo can you confirm which API of cfncluster is affected by those permission ?

**Comment by jmenbo** [comment]
That's odd, I'm using version 1.4.1
> cfncluster --config .cfncluster/clusterx_prod_env version 
> 2017-12-11T14:35:02.945 - INFO - cfncluster.cli - CfnCluster cli starting
> 1.4.1

Each time I tried to update the cloudformation stack it failed, each time reporting the account I was using didn't have permissions to perform the ec2 actions listed. After adding all those 3 actions I'm now able to update the master node with no errors.
BTW, I didn't have this problem with `version 1.3.2`. So it appears to be something specifically related to `version 1.4.1`

**Comment by jmenbo** [comment]
Hey @mohanasudhan I just had some time to circle back to this issue. Based on your statement 

> we only set compute-node Auto-scaling property to 0 to shrink it down

the changes you made would only affect compute nodes. The problem I reported was specific to the Master node, which is not managed by the auto-scaling policy. Users will only come across this issue when they reboot the Master node, i.e. want to change the instance type. In those cases, the policies listed on my initial post **are** required.

**Comment by tom-dyar** [comment]
Is there any way this could be related to this behavior: After idle time, and all compute nodes have been terminated, I submit a job, which "cannot be run on any queue" until a Compute node gets spun up. HOWEVER, at that point, I cannot ssh into my Master node anymore with permission denied, and in my ssh session on Master, I get permission denied when I try to "cd ~". Rebooting Master brings everything back to normal, though...

Where should I look to see what might be happening?

Thanks!
Tom

**Comment by mauri-melato** [comment]
@tom-dyar I think you're reporting a different issue that should be followed in a new thread. It's a peculiar situation since scaling up new nodes should not impact at all your ssh session and the possibility to log into the master. 
If you file a new issue for it please share your cfncluster version / scheduler / os, better your full cfncluster configuration (removing aws account id and credentials) and if you are doing some further custom configuration on the nodes.

Thanks

**Comment by enrico-usai** [comment]
This issue has been addressed as part of the #1583

With this patch, the `pcluster update` command will check for the updatablity of each detected change and will prevent the update from being run if any change is marked as not safe or not possible.

We also added unit tests and integration tests to verify the update of the "updatable" parameters.

**Comment by enrico-usai** [comment]
Release [2.8.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.8.0) is out (and [2.8.1](https://github.com/aws/aws-parallelcluster/releases/tag/v2.8.1) too). One of the enhancements of the 2.8.0 is: _"Renewed user experience and robustness of cluster update functionality"_ and this failure during the update will be prevented.

I'm going to close this issue, feel free to open a new one if you encounter similar problems.
