### ISSUE TITLE
mpirun across multiple nodes, cfncluster shutting down active nodes

### ISSUE THREAD

**Issue by jbzambon** [aws/aws-parallelcluster#280]
I'm currently having problems with cfncluster.  On one end, I tried to use SGE to manage a cluster and submit jobs.  When I did, SGE failed to allocate the job across the appropriate number of hosts.  Instead, it would assign all of the nodes to one host.  I tried setting different parallel environments, including configuring my own to have 36 slots.  This ended up trying to fire up 36 hosts instead.

My next step was to create and populate hostfiles to the master node and then use mpirun -np [total processes] -ppn [processes/host] --hostfile /home/ec2-user/hostfile ./stuff.exe.  This properly allocated the job across several hosts, however the job was killed after the cfncluster nodewatch decided to delete some of the nodes from the execute list.  I screenshot the load monitor showing the grid load vs availability.  I don't know why nodewatch is deleting nodes that are running 100% CPU (although the memory and network usage is fairly small).  I know nodewatch uses CPU and network to determine if the nodes are being utilized, so I took a screenshot.

I'm trying to run a simulation now with "maintain_initial_size = true" to fix the compute fleet at the initial_queue_size.  However, I feel like this shouldn't be happening and I might be missing something.

I would prefer to utilize the first method, so that I don't have to keep adjusting the hostfile every time a blade is added/dropped.  If there is something to adjust in the parallel environment, I would appreciate to know how.  Thanks!

-Joe

<img width="1133" alt="screen shot 2017-12-19 at 1 40 25 am" src="https://user-images.githubusercontent.com/12818350/34146219-2167e994-e467-11e7-8807-bbb772e5612a.png">

**Comment by jbzambon** [comment]
Quick update: setting "maintain_initial_size = true" prevented the run from dying after about 5 hours now.  Something is happening with nodewatch killing the jobs prematurely.  Also, I forgot to mention that this testing was done using on-demand nodes, so they weren't being out-bid on the on-demand market.

**Comment by jbzambon** [comment]
Also my node setup is to use one c4.large as the master node, and push jobs to 2+ c4.8xlarge nodes.  I was wondering if nodewatch would kill jobs seeing that the master node is mostly idle?

**Comment by jocherry** [comment]
Hi jbzambon, 
Looking at this issue it appears the primary issue with with SGE's distribution of work across nodes.  This is not coordinated by cfncluster, but done by SGE, so can you send your SGE config / commands you ran to get your job running?  

For the second part of your question (using mpirun), we base the allocating / reaping of nodes on how many jobs are queued according to cfncluster.  If you bypass it, and use the nodes yourself, cfncluster cannot see this and therefore you run a risk of having your nodes reaped while running a job.  This is not recommended.

Overall this appears to be an issue with how your interacting with SGE, so if you can include some data on how your using SGE (scripts, jobs, commands etc) we can assist in debugging.

**Comment by jbzambon** [comment]
Thanks for the quick reply, jocherry!

Here's some output to help, please let me know if I'm missing anything.  Thanks again!

SBE configuration...
>[ec2-user@ip-172-31-65-197 ~]$ qconf -sq all.q
qname                 all.q
hostlist              @allhosts
seq_no                0
load_thresholds       np_load_avg=1.75
suspend_thresholds    NONE
nsuspend              1
suspend_interval      00:05:00
priority              0
min_cpu_interval      00:05:00
processors            UNDEFINED
qtype                 BATCH INTERACTIVE
ckpt_list             NONE
pe_list               make smp mpi
rerun                 FALSE
slots                 1,[ip-172-31-73-113.ec2.internal=36], \
                      [ip-172-31-66-160.ec2.internal=36]
tmpdir                /tmp
shell                 /bin/sh
prolog                NONE
epilog                NONE
shell_start_mode      posix_compliant
starter_method        NONE
suspend_method        NONE
resume_method         NONE
terminate_method      NONE
notify                00:00:60
owner_list            NONE
user_lists            NONE
xuser_lists           NONE
subordinate_list      NONE
complex_values        NONE
projects              NONE
xprojects             NONE
calendar              NONE
initial_state         default
s_rt                  INFINITY
h_rt                  INFINITY
s_cpu                 INFINITY
h_cpu                 INFINITY
s_fsize               INFINITY
h_fsize               INFINITY
s_data                INFINITY
h_data                INFINITY
s_stack               INFINITY
h_stack               INFINITY
s_core                INFINITY
h_core                INFINITY
s_rss                 INFINITY
h_rss                 INFINITY
s_vmem                INFINITY
h_vmem                INFINITY

Make configuration...
> qconf -sp make
pe_name            make
slots              999
user_lists         NONE
xuser_lists        NONE
start_proc_args    NONE
stop_proc_args     NONE
allocation_rule    $round_robin
control_slaves     TRUE
job_is_first_task  FALSE
urgency_slots      min
accounting_summary TRUE
qsort_args         NONE

SMP configuration...
>qconf -sp smp
pe_name            smp
slots              999
user_lists         NONE
xuser_lists        NONE
start_proc_args    NONE
stop_proc_args     NONE
allocation_rule    $pe_slots
control_slaves     TRUE
job_is_first_task  TRUE
urgency_slots      min
accounting_summary TRUE
qsort_args         NONE

MPI configuration...
>qconf -sp mpi
pe_name            mpi
slots              99999
user_lists         NONE
xuser_lists        NONE
start_proc_args    NONE
stop_proc_args     NONE
allocation_rule    $fill_up
control_slaves     TRUE
job_is_first_task  TRUE
urgency_slots      min
accounting_summary FALSE
qsort_args         NONE

Submit script...
>more qsub_wrf
#!/bin/bash
#$ -cwd
#$ -V
#$ -N wrf1
#$ -o wrf.out
#$ -e wrf.err
#$ -m ea
#$ -M [email]
mpirun -np 76 --hostfile /home/ec2-user/hostfile ./wrf.exe

Submit script command...
> qsub < qsub_wrf

**Comment by jocherry** [comment]
A couple of things to look at:
when you say: 'SGE failed to allocate the job across the appropriate number of hosts' What does that mean precisely?  And how are you assigning slots to the nodes SGE controls?

Also you have your allocation rules set up differently from SGE to MPI:
In SGE you have it set up to Round Robin (which it sounds like what you want)
VS in MPI you have fill up (which will fill up the slots available on one host)

But you need to look at how precisely you're assigning slots in your SGE environment, can you provide details here?
