### ISSUE TITLE
Question: location of post-install script on Slurm nodes

### ISSUE THREAD

**Issue by keien** [aws/aws-parallelcluster#2822]
We're on 2.10.1 with Slurm and occasionally we have a need to rerun our post-install scripts - for example, we use it to make modifications to Slurm conf files, which get overwritten during some `pcluster update` commands and we need to redo our changes.

Is there something I can do to make post-install scripts rerun on master/compute nodes, and/or a location where the script is downloaded that I can invoke it from?

**Comment by demartinofra** [comment]
You can do the following:
```
sudo /opt/parallelcluster/scripts/fetch_and_run -preinstall
sudo /opt/parallelcluster/scripts/fetch_and_run -postinstall
```

**Comment by keien** [comment]
thank you
