### ISSUE TITLE
PythonDeprecationWarning

### ISSUE THREAD

**Issue by andrei-xdlab** [aws/aws-parallelcluster#2836]
Environment:  2.10.4
scheduler = awsbatch

Is there a new Python 3.6  pcluster AMI for 2.10.4 in US-EAST-1 ?

$ awsbstat
/usr/lib/python2.7/site-packages/boto3/compat.py:86: PythonDeprecationWarning: Boto3 will no longer support Python 2.7 starting July 15, 2021. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.6 or later. More information can be found here: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/
  warnings.warn(warning, PythonDeprecationWarning)
jobId    jobName    status    startedAt    stoppedAt    exitCode
-------  ---------  --------  -----------  -----------  ----------

[cluster default]
key_name = xxx
scheduler = awsbatch
master_instance_type = t2.micro
base_os = alinux2
vpc_settings = default
compute_instance_type = optimal
desired_vcpus = 0
max_vcpus = 80

**Comment by demartinofra** [comment]
This will be fixed as part of the upcoming release 2.11.0. We will be installing the batch cli commands as part of a virtualenv using Python 3.

See https://github.com/aws/aws-parallelcluster-cookbook/pull/885 for additional details

**Comment by rexcsn** [comment]
pcluster v2.11.0 is released, which contains the fix for this issue.
Resolving the issue now, please let us know if you have any question, thanks!
