### ISSUE TITLE
awsbatch parallel cluster environment with LDAP

### ISSUE THREAD

**Issue by andrei-xdlab** [aws/aws-parallelcluster#2837]
Environment:  2.10.4
scheduler = awsbatch

Can custom_ami be used along with scheduler = awsbatch? We have to create a multi-user LDAP'based parallel cluster batch node and have to enable LDAP authentication on the aws batch head node and all worker nodes.

Reference: https://aws.amazon.com/blogs/opensource/managing-aws-parallelcluster-ssh-users-with-openldap/

[cluster default]
key_name = xxx
scheduler = awsbatch
master_instance_type = t2.micro
base_os = alinux2
vpc_settings = default
compute_instance_type = optimal
desired_vcpus = 0
max_vcpus = 80

**Comment by demartinofra** [comment]
`custom_ami` with `scheduler = awsbatch` only controls the AMI for the head node. It is currently not possible to customize the ECS AMI or the Batch Dockerfile with native features.

Available custom options (not officially supported):
* To use a custom ami for the Batch compute environment you'll have to customize the CloudFormation stack used for batch and set the ImageId in the ComputeEnvironment: https://github.com/aws/aws-parallelcluster/blob/develop/cloudformation/batch-substack.cfn.json#L419
* To customize the docker environment you can follow: https://github.com/aws/aws-parallelcluster/wiki/AWS-Batch-with-a-custom-Dockerfile
