### ISSUE TITLE
[question] Why run_instances instead of create_fleet?

### ISSUE THREAD

**Issue by elgalu** [aws/aws-parallelcluster#2849]
Hi, first of all thanks for this project.

I'm trying to understand how the plugin for Slurm works and I notice that this project uses `run_instances` https://github.com/aws/aws-parallelcluster-node/blob/31e346ed5e17d9afaf3d306bce7974bd173b5b19/src/slurm_plugin/common.py#L285

While in aws-plugin-for-slurm https://github.com/aws-samples/aws-plugin-for-slurm/blob/6b39f6ea399db05de012d620918b9e8516611c2b/resume.py#L94) `create_fleet` is used.

Is it because create_fleet is slower than simply launching EC2 instances?

**Comment by hanwen-pcluste** [comment]
Hi Leo,

The `run_instances` call meets the requirements of  current ParallelCluster scaling logic. Although I am not aware of if `create_fleet` is slower than `run_instances`, I'd use the simplest API call that can accommodate our need.

Thank you for this good question!
Hanwen
