### ISSUE TITLE
SSL Verification Error during cluster creation

### ISSUE THREAD

**Issue by dan-schlecht** [aws/aws-parallelcluster#2851]
If you are reporting an issue with AWS Parallelcluster / CfnCluster please make sure to add the following data in order to facilitate the root cause detection:

**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]:2.10.4
 - Full cluster configuration without any credentials or personal data
[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = us-gov-east-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = xxxxxxxxxxxxxx
scheduler = slurm
master_instance_type = c5n.large
base_os = alinux2
vpc_settings = default
queue_settings = compute
custom_ami = ami-xxxxxxxxxxxxxxxxx
ec2_iam_role = Proj_EC2SysAdmin
additional_iam_policies = arn:aws:iam::aws:policy/AdministratorAccess
cluster_resource_bucket = gs-hpc-pcluster
s3_read_write_resource = arn:aws:s3:::xxxxxxxxxxxxx/*
ebs_settings = volume1
pre_install = s3://xxxxxxxxxxxxx/pclusterPreinstall.sh

[compute_resource default]
instance_type = c5n.18xlarge
min_count = 1
max_count = 9

[ebs volume1]
ebs_kms_key_id = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
ebs_volume_id = vol-xxxxxxxxxxxxxxxxx
encrypted = true
volume_iops = 100
volume_type = gp2

[queue compute]
compute_resource_settings = default
enable_efa = true
enable_efa_gdr = false

[scaling default]
scaledown_idletime = 10

[vpc default]
vpc_id = vpc-xxxxxxxxxxxxxxxxx
master_subnet_id = subnet-xxxxxxxxxxxxxxxxx

use_public_ips = false
vpc_security_group_id = sg-xxxxxxxxxxxxxxxxx

 - Cluster name: pcluster-hpc
 - [Optional] Arn of the cluster CloudFormation main stack:

**Bug description and how to reproduce:**
I'm new to AWS ParallelCluster.
Cluster creation fails during Master Server Instance creation.
I got into the Master VM and looked at the /var/log/clound-init-output.log file
It appears to download and install cinc-15.11.8-1.el7.x86_64.rpm
Then, it fails to install berkshelf because our corporate Root CA is not trusted
  /opt/cinc/embedded/bin/gem install --no-document berkshelf:7.0.10
  ERROR:  SSL verification error 

Because of -nr option, I used the failed Master Instance and manually installed cinc and berkshelf
Then, created a custom AMI, but the same failure keeps happening

I've tried the following to get gem to trust our corporate CA to install berkshlef:
1. add our corporate CA file to /opt/cinc/embedded/ssl/certs/cacert.pem.  However, cloud-init always installs cinc even though it is already installed.  The installation appears to reset the whole /opt/cinc/... folder path
2. I tried to set an environment variable SSL_CERT_FILE to the RHEL location of our corporate CA pem file, but the environment variable is not being used during cluster creation.  But, when I log in as ec2-user or root, the environment variable is set and I can do the gem install of berkshelf.  I'm thinking cloud-init and python has something to do with this.  I've tried placing the env variable in .bashrc files, /etc/bashrc, /etc/environment, /etc/bashrc, /etc/profile.d/<bash and csh scripts>
3. I also tried a pre-install script to set environment variables, but I don't my pre-install script is being executed at this point of cluster creation since I don't see any log statements and I also tried to touch a file for confirmation.

I don't know what else to try...
[UPDATE]
I figure more details on the problem would help.

When the Master instance is getting started for the first time, it 
1. downloads and installs:
https://us-gov-east-1-aws-parallelcluster.s3.us-gov-east-1.amazonaws.com/archives/cinc/el/7/cinc-15.11.8-1.el7.x86_64.rpm
2. Then, executes /opt/cinc/embedded/bin/gem install --no-document berkshelf:7.0.10
The gem install fails will SSL verification error.
I was puzzled by the unable to download from https://rubygens.org because of our corporate Root CA isn’t trusted..
I’m guessing rubygems.org is being spoofed by a GD server with a GD certificate.
Since the /opt/cinc/embedded/ssl/certs/cacert.pem file is a GlobalSign CA cert and not our corporate Root CA cert, the corporate “rubygems.org” server isn’t trusted.
Since cinc is installed every time and resetting the cacert.pem file every time, I can't get the gem install to trust our corporate Root CA.

**If you are reporting issues about scaling or job failure:**
We cannot work on issues without proper logs. We **STRONGLY** recommend following [this guide](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs) and attach the complete cluster log archive with the ticket.

For issues with AWS ParallelCluster >= v2.9.0 and scheduler == slurm, please attach the following logs:
* From Head node: `/var/log/parallelcluster/clustermgtd.log`, `/var/log/parallelcluster/slurm_resume.log`, `/var/log/parallelcluster/slurm_suspend.log`, and `/var/log/slurmctld.log`
* From Compute node:  `/var/log/parallelcluster/computemgtd.log`, and `/var/log/slurmd.log`

Otherwise, please attach the following logs:
* From Head node: `/var/log/jobwatcher`, `/var/log/sqswatcher`, and `/var/log/slurmctld.log` if scheduler == slurm.
* From Compute node:`/var/log/nodewatcher`, and `/var/log/slurmd.log` if scheduler == slurm

**If you are reporting issues about cluster creation failure or node failure:**

If the cluster fails creation, please re-execute `create` action using `--norollback` option.

We cannot work on issues without proper logs. We **STRONGLY** recommend following [this guide](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs) and attach the complete cluster log archive with the ticket.

* From Head node: `/var/log/cloud-init.log`, `/var/log/cfn-init.log`, and `/var/log/chef-client.log`
* From Compute node:  `/var/log/cloud-init-output.log`

**Additional context:**
Any other context about the problem. E.g.:
 - pre/post-install scripts, if any
 - screenshots, if useful

**Comment by hanwen-pcluste** [comment]
Hello Dan,

Thank you for the detailed information. It is really helpful!

Could you try [pcluster createami](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.createami.html) to create a AMI with ParallelCluster software installed. In the command, the `--ai` flag should be set to your custom AMI. Using the outcome AMI to create a cluster will not download cinc. Using `pcluster createami` to bake the custom AMI can reduce the time of cluster creation and compute nodes launch time.

I would like to answer the 3 points you asked:
1. cinc is downloaded and installed as long as the AMI is not baked by pcluster
2. I will look into if CloudFormation UserData uses environment variable
3. You are right. Both pre-install and post-install scripts are executed by cinc

If you see the SSL error in `pcluster createami`, please contact us again and we would like to help!

Thank you!
Hanwen

**Comment by dan-schlecht** [comment]
ok, if I use pcluster createami with --ai set to my first custom ami.  The output will be my second ami to use in my pcluster config file custom_ami proptery?  Do I need to do anything else to the output second ami?  launch the ami and install software manually and then create a third ami?

**Comment by hanwen-pcluste** [comment]
Second AMI is good to be put in the custom_ami property. No need for a third one

**Comment by dan-schlecht** [comment]
cool, but I am having problems with createami.  I tried it out on my Windows box and t3.small VM, and failed Master instance.
I keep getting the same error.

(pcluster) [ssm-user@ip-10-149-11-115 pcluster]$ **pcluster createami -i c5n.large -ai ami-0121a090f548cd6ea -os alinux2**
Building AWS ParallelCluster AMI. This could take a while...
/home/ssm-user/pcluster/lib/python2.7/site-packages/boto3/compat.py:86: PythonDeprecationWarning: Boto3 will no longer support Python 2.7 starting July 15, 2021. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.6 or later. More information can be foundhere: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/
  warnings.warn(warning, PythonDeprecationWarning)
Base AMI ID: ami-0121a090f548cd6ea
Base AMI OS: alinux2
Instance Type: c5n.large
Region: us-gov-east-1
VPC ID: vpc-0afdd125a4ded1ff0
Subnet ID: subnet-036d4fdb7439c3672
Template: https://us-gov-east-1-aws-parallelcluster.s3.us-gov-east-1.amazonaws.com/templates/aws-parallelcluster-2.10.4.cfn.json
Cookbook: https://us-gov-east-1-aws-parallelcluster.s3.us-gov-east-1.amazonaws.com/cookbooks/aws-parallelcluster-cookbook-2.10.4.tgz
Post install script dir not specified.
Packer log: /tmp/packer.log.20210618-200041.ndW0q1
Failed to run /tmp/tmp6bekm7/aws-parallelcluster-cookbook-2.10.4/amis/build_ami.sh --os alinux2 --partition region --region us-gov-east-1 --custom --arch x86_64
Command not found

No custom AMI created

**Comment by hanwen-pcluste** [comment]
This failure appeared seconds after you run the command, right?

**Comment by dan-schlecht** [comment]
yep

**Comment by hanwen-pcluste** [comment]
I am still looking into it. But my guess is the failure is related to Python2. Could you try running the command with Python3?

**Comment by dan-schlecht** [comment]
Ok, I used pip3 to install virtualenv and aws-parallelcluster
I get a very similar error:

(pcluster3) [ssm-user@ip-10-149-11-102 pcluster3]$ pcluster createami -i c5n.large -ai ami-xxxxxxxxxxxx -os alinux2
Building AWS ParallelCluster AMI. This could take a while...
Base AMI ID: ami-xxxxxxxxxxxx
Base AMI OS: alinux2
Instance Type: c5n.large
Region: us-gov-east-1
VPC ID: vpc-xxxxxxxxxxxx
Subnet ID: subnet-xxxxxxxxxxxxx
Template: https://us-gov-east-1-aws-parallelcluster.s3.us-gov-east-1.amazonaws.com/templates/aws-parallelcluster-2.10.4.cfn.json
Cookbook: https://us-gov-east-1-aws-parallelcluster.s3.us-gov-east-1.amazonaws.com/cookbooks/aws-parallelcluster-cookbook-2.10.4.tgz
Post install script dir not specified.
Packer log: /tmp/packer.log.20210621-050514.2qxb4kib
**Failed to run /tmp/tmpddw4m0kq/aws-parallelcluster-cookbook-2.10.4/amis/build_ami.sh --os alinux2 --partition region --region us-gov-east-1 --custom --arch x86_64**
Command not found

No custom AMI created

**Comment by chenwany** [comment]
Hi Dan,
Parallelcluster CreateAMI command is for Linux and MacOs, see https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.createami.html. The problem might cause by using windows VM to run the command, could you try with using linux VM? 

Thanks

**Comment by dan-schlecht** [comment]
yes, I have tried both Windows and linux vm.  I mainly have been debugging on linux VM.  Looking at the createami.py file in the _run_packer method.  Looks like there is IOError with doing the line:
process = sub.Popen(
            _command, env=packer_env, stdout=sub.PIPE, stderr=sub.STDOUT, stdin=dev_null, universal_newlines=True
        )

I added to the exceptions list to differentiate between IOError and OSError
Any idea why there would be an IOError with trying to run the packer command?

**Comment by chenwany** [comment]
Hi, do you have the latest packer install? Download the latest version from https://www.packer.io/downloads.html. 
Parallelcluster is using pakcer 1.7.2

**Comment by dan-schlecht** [comment]
I think I found out the problem.  My AWS VM doesn't allow scripts to be executed out of /tmp.  I modified createami.py to create a temp dir in my home directory and it executed.  However, the ami build failed for lack of permissions.  Looks like ec2:CreateSecurityGroup was denied.  But, I defined a specific security group in my config file.  Does createami command ignore the vpc_security_group_id = sg-xxxxxxx parameter?

**Comment by dan-schlecht** [comment]
BTW, I have packer version 1.7.3

**Comment by chenwany** [comment]
Happy to see you figure it out! 👍 

You are right, vpc_security_group_id = sg-xxxxxxx paramete will be ignored, only `master_subnet_id` and `vpc_id` will be used for createami command.

For lacing of permissions, I think it is because the IAM role attach to your AWS VM lack of the permissions. By adding lacking permissions, you can go to the EC2 console, find the Instance, -->IAM Role-->Attach policies--->Create policy, then paste the following to the json, or you can just add it in an existing policy. See here for example https://docs.amazonaws.cn/en_us/AWSEC2/latest/UserGuide/iam-policies-ec2-console.html
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateSecurityGroup",
            ],
            "Resource": "*"
        },
    ]
}
```

**Comment by dan-schlecht** [comment]
I'm sorry, but my corporate account will not allow me to create Security groups.  I need to use already existing security groups created specifically for the project I am on.  Shouldn't createami support the security group parameter?

Also for /tmp not allowing script execution, I think this is becoming a common security concern.  I found that cluster creation also tries to execute scripts from /tmp.  Seems like another parameter is needed to specify a temp directory where script can execute from.  Right now, my workaround is to update the UserData section of the MasterServer and ComputeFleet templates to remount /tmp with execute permissions.  This requires me to upload the main and 2 substacks to S3 and specify the main stack via template_url

**Comment by chenwany** [comment]
Dan, thank you for your feedbacks! 
createami doesn't support the security group parameter currently. I will follow up with the team on this.
As for execute scripts from /tmp, it seems we have many scripts run from /tmp. I will also raise the concern to the team.
Let me know if your workaround solve the problem
I will get back to you after following up with the team

**Comment by enrico-usai** [comment]
Hi @dan-schlecht 
I just want to mention that the patch to add the possibility to specify a security group when creating a custom ami is already merged and will be part of the next release: https://github.com/aws/aws-parallelcluster-cookbook/pull/984

**Comment by enrico-usai** [comment]
I'm adding the "pending-release" label to the ticket, regarding the security group feature, let us know if there are additional questions.

**Comment by rexcsn** [comment]
pcluster v2.11.0 is released, which contains the fix for this issue.
Resolving the issue now, please let us know if you have any question, thanks!
