### ISSUE TITLE
Question: Spot Instance Termination Notice handling inside SLURM job

### ISSUE THREAD

**Issue by oplatek** [aws/aws-parallelcluster#2887]
Hi there!

I am working heavily with spot instances, I use python to successfully capture SIGTERM signal which is sent when the spot instance is reclaimed by AWS.
However, the SIGTERM signal does not give the job enough time to save the work and upload it to S3.

I hoped that there is another operating signal sent in advance to all applications on the node which are going to be terminated because the node is going to be shut down, but I was not able to find it. 
I found few tutorials about 2 minutes in advance notice e.g. announcement[1] and a guide on how to handle them[2]:
[1] https://aws.amazon.com/about-aws/whats-new/2015/01/05/announcing-amazon-ec2-spot-instance-termination-notices/
[2] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#using-spot-instances-managing-interruptions

My questions are:
1. Is there an operating signal received by all applications for terminating spot instances when used with AWS Parallel Cluster default config for Slurm?
 
2. If no operating signal is issued automatically, what is the recommended approach to notify the job / the running process that its node going to be terminated? Can the SLURM scheduler be used to notify the jobs that a node is going to be terminated?

The last thing I want to do is to bake polling of spot instance state into the code which runs as a job on SLURM as described in [2]

I can imagine I can start a separate process on each node which checks the spot instance node state and if it detects that the node is going to be terminated it sends the OS signal to the instances.

Thank you for any tips!

**Comment by enrico-usai** [comment]
Hi Ondrej,
ParallelCluster doesn't have any mechanism to signal the applications when spot instances are reclaimed.

In addition to the link you already shared, there is a new mechanism (since 2018) that permits to monitor Spot Notification alerts in CloudWatch LogEvents and automatically route these events to different targets: https://aws.amazon.com/about-aws/whats-new/2018/01/amazon-ec2-spot-two-minute-warning-is-now-available-via-amazon-cloudwatch-events/

In the following blog post there is an example of association with a Lambda Function or a SNS topic:
https://aws.amazon.com/blogs/compute/taking-advantage-of-amazon-ec2-spot-instance-interruption-notices/

An alternative is to use SSM Run Command as a target of the CloudWatch Event rule, to automatically run commands into the instances. If you're going to use the [2.11 release](https://github.com/aws/aws-parallelcluster/releases/tag/v2.11.0), SSM agent are installed by default in the AMIs. 

Let us know if it helps.

**Comment by oplatek** [comment]
@enrico-usai thanks a lot! 

It seems that even for version 2.10.3 of the cluster the SSM agent is running.

If you think that the version of our cluster 2.10.3 is enough I will try to make it work during next month.

```
sudo systemctl status snap.amazon-ssm-agent.amazon-ssm-agent.service
● snap.amazon-ssm-agent.amazon-ssm-agent.service - Service for snap application amazon-ssm-agent.amazon-ssm-agent
   Loaded: loaded (/etc/systemd/system/snap.amazon-ssm-agent.amazon-ssm-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-30 17:39:05 UTC; 2 months 1 days ago
 Main PID: 1260 (amazon-ssm-agen)
    Tasks: 35 (limit: 4915)
   CGroup: /system.slice/snap.amazon-ssm-agent.amazon-ssm-agent.service
           ├─1260 /snap/amazon-ssm-agent/3552/amazon-ssm-agent
           └─1828 /snap/amazon-ssm-agent/3552/ssm-agent-worker

Apr 30 17:39:05 ip-10-0-35-251 systemd[1]: Started Service for snap application amazon-ssm-agent.amazon-ssm-agent.
Apr 30 17:39:06 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: Error occurred fetching the seelog config file path:  open /etc/amazon/ssm/seelog.xml: no such file or directory
Apr 30 17:39:06 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: Initializing new seelog logger
Apr 30 17:39:06 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: New Seelog Logger Creation Complete
Apr 30 17:39:06 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: 2021-04-30 17:39:06 WARN Error adding the directory '/etc/amazon/ssm' to watcher: no such file or directory
Apr 30 17:39:06 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: 2021-04-30 17:39:06 INFO [amazon-ssm-agent] amazon-ssm-agent - v3.0.529.0
Apr 30 17:39:06 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: 2021-04-30 17:39:06 INFO [amazon-ssm-agent] OS: linux, Arch: amd64
Apr 30 17:39:07 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: 2021-04-30 17:39:07 INFO [amazon-ssm-agent] [LongRunningWorkerContainer] [WorkerProvider] Worker ssm-agent-worker is not running, starting worker process
Apr 30 17:39:07 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: 2021-04-30 17:39:07 INFO [amazon-ssm-agent] [LongRunningWorkerContainer] [WorkerProvider] Worker ssm-agent-worker (pid:1828) started
Apr 30 17:39:07 ip-10-0-35-251 amazon-ssm-agent.amazon-ssm-agent[1260]: 2021-04-30 17:39:07 INFO [amazon-ssm-agent] [LongRunningWorkerContainer] Monitor long running worker health every 60 seconds
```

**Comment by enrico-usai** [comment]
Yes Ondrej, in 2.10.3 SSM agent was ready to use in some OSes but it was missing in other (i.e. CentOS7 and CentOS8), we aligned all the OSes, by installing SSM agent on them, as part of 2.11.0, but 2.10.3 might be enough according to the OS you're using.
