### ISSUE TITLE
Cluster creation fails with AWS::EC2::EIP MasterEIP The maximum number of addresses has been reached

### ISSUE THREAD

**Issue by fgv2104** [aws/aws-parallelcluster#2905]
pcluster fails to create cluster because of insufficient elastic IP address availability but when I check on elastic IPs on aws, four out of five of them are not associated to any resource. Any help is appreciated, thank you.

 - AWS ParallelCluster version 2.11.0
 - Cluster name: fgvCluster
- Cluster config file:
[aws]
aws_region_name = us-east-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = fgvCluster
update_check = true
sanity_check = true

[cluster fgvCluster]
key_name = fgv_mac
scheduler = sge
master_instance_type = c5.large
base_os = alinux2
cluster_type = spot
vpc_settings = public
spot_price = 1.5
master_root_volume_size = 500
compute_root_volume_size = 50
compute_instance_type = c5.4xlarge

[vpc public]
vpc_id = vpc-319c9555
master_subnet_id = subnet-003bd010dd990e304

$ pcluster create fgvCluster --norollback
Beginning cluster creation for cluster: fgvCluster
WARNING: The configuration parameter 'scheduler' generated the following warnings:
The job scheduler you are using (sge) is scheduled to be deprecated in future releases of ParallelCluster. More information is available here: https://github.com/aws/aws-parallelcluster/wiki/Deprecation-of-SGE-and-Torque-in-ParallelCluster
Creating stack named: parallelcluster-fgvCluster
Status: parallelcluster-fgvCluster - CREATE_FAILED                              
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-fgvCluster The following resource(s) failed to create: [MasterEIP, MasterSecurityGroup, RootRole, DynamoDBTable, SNS, CleanupResourcesFunctionExecutionRole, EBSCfnStack, CloudWatchLogsSubstack]. 
  - AWS::EC2::SecurityGroup MasterSecurityGroup Resource creation cancelled
  - AWS::DynamoDB::Table DynamoDBTable Resource creation cancelled
  - AWS::CloudFormation::Stack EBSCfnStack Resource creation cancelled
  - AWS::CloudFormation::Stack CloudWatchLogsSubstack Resource creation cancelled
  - AWS::IAM::Role RootRole Resource creation cancelled
  - AWS::IAM::Role CleanupResourcesFunctionExecutionRole Resource creation cancelled
  - AWS::SNS::Topic SNS Resource creation cancelled
  - AWS::EC2::EIP MasterEIP The maximum number of addresses has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: AddressLimitExceeded; Request ID: 7d6deba1-fdff-43ac-944a-cc118ead12d5; Proxy: null)

**Comment by enrico-usai** [comment]
Hi @fgv2104 

ParallelCluster tries to create a new ElasticIP, to avoid this issue you should delete one of the unused ElasticIPs, ParallelCluster will create a new one as part of the CloudFormation Stack created within the cluster.

Let us know if it helps.
