### ISSUE TITLE
Createami fails when trying to createSecurityGroup

### ISSUE THREAD

**Issue by dan-schlecht** [aws/aws-parallelcluster#2917]
If you are reporting an issue with AWS Parallelcluster / CfnCluster please make sure to add the following data in order to facilitate the root cause detection:

**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 2.11.0
 - Full cluster configuration without any credentials or personal data
 - Cluster name:
 - [Optional] Arn of the cluster CloudFormation main stack:
```
[global]
cluster_template = default
update_check = true
sanity_check = true
[aws]
aws_region_name = us-gov-east-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = xxxxxxxxxxxxxx
scheduler = slurm
master_instance_type = c5n.large
base_os = alinux2
vpc_settings = default
queue_settings = compute
custom_ami = ami-xxxxxxxxxxxxxxxxx
ec2_iam_role = Proj_EC2SysAdmin
additional_iam_policies = arn:aws:iam::aws:policy/AdministratorAccess
cluster_resource_bucket = gs-hpc-pcluster
s3_read_write_resource = arn:aws:s3:::xxxxxxxxxxxxx/*
ebs_settings = volume1
pre_install = s3://xxxxxxxxxxxxx/pclusterPreinstall.sh

[compute_resource default]
instance_type = c5n.18xlarge
min_count = 1
max_count = 9

[ebs volume1]
ebs_kms_key_id = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
ebs_volume_id = vol-xxxxxxxxxxxxxxxxx
encrypted = true
volume_iops = 100
volume_type = gp2

[queue compute]
compute_resource_settings = default
enable_efa = true
enable_efa_gdr = false

[scaling default]
scaledown_idletime = 10

[vpc default]
vpc_id = vpc-xxxxxxxxxxxxxxxxx
master_subnet_id = subnet-xxxxxxxxxxxxxxxxx
use_public_ips = false
vpc_security_group_id = sg-xxxxxxxxxxxxxxxxx
```

**Bug description and how to reproduce:**
https://github.com/aws/aws-parallelcluster/issues/2851
I was told that version 2.11.0 was able to support the vpc_security_group_id parameter in the config file
however, the createami command still fails:
pcluster createami -i c5n.large -ai ami-xxxxxxxx -os alinux2 -c <config_file>

Looking at the createami.py file, it doesn't appear to be getting the vpc_security_group_id parmeter and populating the packer_env with it.
I tried add this code to the createami.py file and it got further:
```
        **security_group_id = vpc_section.get_param_value("vpc_security_group_id")**

        packer_env = {
            "CUSTOM_AMI_ID": args.base_ami_id,
            "AWS_FLAVOR_ID": instance_type,
            "AMI_NAME_PREFIX": args.custom_ami_name_prefix,
            "AWS_VPC_ID": vpc_id,
            "AWS_SUBNET_ID": subnet_id,
            **"AWS_SECURITY_GROUP_ID": security_group_id,**
            "ASSOCIATE_PUBLIC_IP": "true" if args.associate_public_ip else "false",
        }
```
Then, it timesout waiting for SSH
Here is the packer.log file:
```
+ main --os alinux2 --partition region --region us-gov-east-1 --custom --arch x86_64
+ requirements_check
++ packer --version
+ currentver=1.7.3
+ requiredver=1.4.0
+ packer build --help
+ '[' 0 -ne 0 ']'
++ printf '%s\n' 1.4.0 1.7.3
++ head -n1
++ sort -V
+ '[' 1.4.0 = 1.4.0 ']'
+ parse_options --os alinux2 --partition region --region us-gov-east-1 --custom --arch x86_64
+ _os=
+ _partition=
+ _region=
+ _custom=false
+ _public=false
+ _build_date=
+ _arch=
+ '[' 9 -eq 0 ']'
+ '[' 9 -gt 0 ']'
+ case "$1" in
+ _os=alinux2
+ shift
+ shift
+ '[' 7 -gt 0 ']'
+ case "$1" in
+ _partition=region
+ shift
+ shift
+ '[' 5 -gt 0 ']'
+ case "$1" in
+ _region=us-gov-east-1
+ shift
+ shift
+ '[' 3 -gt 0 ']'
+ case "$1" in
+ _custom=true
+ shift
+ '[' 2 -gt 0 ']'
+ case "$1" in
+ _arch=x86_64
+ shift
+ shift
+ '[' 0 -gt 0 ']'
+ check_options
+ set -e
+ available_arm_os='ubuntu1804 ubuntu2004 alinux2 centos7 centos8'
+ available_os='centos7 ubuntu1804 ubuntu2004 alinux2 centos7 centos8'
++ dirname /tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0/amis/build_ami.sh
+ cwd=/tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0/amis
++ cd /tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0/amis/..
++ pwd
+ export COOKBOOK_PATH=/tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0
+ COOKBOOK_PATH=/tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0
+ export SCRIPT_PATH=/tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0/amis/../../script
+ SCRIPT_PATH=/tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0/amis/../../script
+ '[' true == true ']'
+ only=custom-alinux2
+ '[' xalinux2 == x ']'
+ '[' xus-gov-east-1 == x ']'
+ '[' false == true ']'
+ '[' region == commercial ']'
+ '[' region == govcloud ']'
+ '[' region == china ']'
+ '[' region == region ']'
+ export AWS_REGION=us-gov-east-1
+ AWS_REGION=us-gov-east-1
+ '[' us-gov-east-1 == all ']'
+ export BUILD_FOR=us-gov-east-1
+ BUILD_FOR=us-gov-east-1
+ '[' -z x86_64 ']'
+ '[' -z x86_64 ']'
+ available_archs='x86_64 arm64'
+ case ${_arch} in
+ export AMI_ARCH=x86_64
+ AMI_ARCH=x86_64
+ '[' x86_64 == arm64 ']'
+ do_command
+ RC=0
+ mkdir -p /tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0/amis/../../script
+ '[' x == x ']'
++ date +%Y%m%d%H%M
+ export BUILD_DATE=202107062132
+ BUILD_DATE=202107062132
+ export AWS_TIMEOUT_SECONDS=3600
+ AWS_TIMEOUT_SECONDS=3600
+ case ${_os} in
+ packer build -color=false -var-file=/tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0/amis/packer_variables.json -only=custom-alinux2 /tmp/tmp4wl02ieu/aws-parallelcluster-cookbook-2.11.0/amis/packer_alinux2.json
==> custom-alinux2: Prevalidating any provided VPC information
==> custom-alinux2: Prevalidating AMI Name: custom-ami-aws-parallelcluster-2.11.0-amzn2-hvm-x86_64-202107062132
custom-alinux2: Found Image ID: ami-xxxxxxxxxx
==> custom-alinux2: Creating temporary keypair: packer_60e4cbf7-d5b5-d164-16fb-477e6b55b071
==> custom-alinux2: Launching a source AWS instance...
==> custom-alinux2: Adding tags to source instance
custom-alinux2: Instance ID: i-06bc03846a7b0e225
==> custom-alinux2: Waiting for instance (i-06bc03846a7b0e225) to become ready...
custom-alinux2: Adding tag: "Name": "Packer Builder ami-xxxxxxxxxxx"
custom-alinux2: Adding tag: "parallelcluster_version": "aws-parallelcluster-2.11.0"
custom-alinux2: Adding tag: "build_date": "202107062132"
==> custom-alinux2: Using SSH communicator to connect: 18.253.131.66
==> custom-alinux2: Waiting for SSH to become available...
==> custom-alinux2: Timeout waiting for SSH.
==> custom-alinux2: Terminating the source AWS instance...
==> custom-alinux2: Cleaning up any extra volumes...
==> custom-alinux2: No volumes to clean up, skipping
==> custom-alinux2: Deleting temporary keypair...
Build 'custom-alinux2' errored after 6 minutes 10 seconds: Timeout waiting for SSH.

==> Wait completed after 6 minutes 10 seconds

==> Some builds didn't complete successfully and had errors:
--> custom-alinux2: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.
```

**Comment by tilne** [comment]
To first address why you had to modify the createami source: the prior issue you mentioned references [this cookbook PR](https://github.com/aws/aws-parallelcluster-cookbook/pull/984), which enables the packer config files that are used by createami to utilize the value of the `AWS_SECURITY_GROUP_ID` environment variable. If you set that environment variable to the security group ID you want to use I would think createami would work as you expect without having to modify the source. I believe we elected not to use the `[vpc]` section's `vpc_security_group_id` parameter for this purpose because we feared it wasn't intuitive to customers that that parameter would be used for that purpose. I'll see if that's the case.

As for why the AMI build failed after specifying the desired security group: my first guess is that the security group doesn't permit incoming SSH connections from where you were running createami. Did you double-check this?

**Comment by lukeseawalker** [comment]
Hello @dan-schlecht,
were you able to set desired SG setting the env var `AWS_SECURITY_GROUP_ID` before calling the `createami` command?

**Comment by dan-schlecht** [comment]
Sorry, I didn't know I had to set an environment variable before trying to create the ami.  I will try this.
When I try again, I will see if I still get SSH problems.  I'm executing the createami from an EC2 instance with the same region, VPC, security group, and placement group

**Comment by dan-schlecht** [comment]
I was able to get further with setting env var AWS_SECURITY_GROUP_ID without modifying the createami.py file.
However, I still have the SSH timeout issue.
I tried to connect to the Packer instance myself via AWS Connect button and I couldn't.
The error I got was some client wasn't installed or the wrong IAM Instance profile is applied to the instance.
I looked at the Packer instance details and saw an Instance Profile that I don't use.
How does the instance profile get set for the Packer instance?
My pcluster config file parameter ec2_iam_role is not being used.
The instance profile of the VM I'm using to execute createami is not being used.
The iam role assigned to my logged in user is not being used.

Is there some other config parameter or env variable that I need to set?

**Comment by lukeseawalker** [comment]
Hello @dan-schlecht, 
an instance profile is autogenerated by Packer and attached to the instance by default.
You can override it by exporting the env var [AWS_IAM_PROFILE](https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.11.0/amis/packer_alinux2.json#L28).
For the SSH connection, Packer generate a key pair on the fly and keeps it in memory, so you'll not see unless you set the `-debug` flag when calling the `packer` command [here](https://github.com/aws/aws-parallelcluster-cookbook/blob/v2.11.0/amis/build_ami.sh#L211-L216). Doing this, the key will be written on disk and can be used to SSH into the packer instance.

**Comment by dan-schlecht** [comment]
I set AWS_IAM_PROFILE and was able to connect to the packer instance via the AWS GUI Console's connect button, but I still get an SSH Timeout failure.  Looks like it is trying to connect to a public IP address set to the Packer Instance.  I'm not sure my corporate environment is allowing this.  Is there an env variable to force ssh connection via the private ip address?

BTW, is there a list of documented environment variables I can reference?

**Comment by lukeseawalker** [comment]
That one is a CLI flag `--no-public-ip`

```
pcluster createami -h
usage: pcluster createami [-h] -ai BASE_AMI_ID -os BASE_AMI_OS
                          [-i INSTANCE_TYPE] [-ap CUSTOM_AMI_NAME_PREFIX]
                          [-cc CUSTOM_AMI_COOKBOOK]
                          [--post-install POST_INSTALL_SCRIPT]
                          [--no-public-ip] [-c CONFIG_FILE]
                          [-t CLUSTER_TEMPLATE] [--vpc-id VPC_ID]
                          [--subnet-id SUBNET_ID] [-r REGION]

optional arguments:
  -h, --help            show this help message and exit
  -ai BASE_AMI_ID, --ami-id BASE_AMI_ID
                        Specifies the base AMI to use for building the AWS
                        ParallelCluster AMI.
  -os BASE_AMI_OS, --os BASE_AMI_OS
                        Specifies the OS of the base AMI. Valid options are:
                        alinux2, ubuntu1804, ubuntu2004, centos7, centos8.
  -i INSTANCE_TYPE, --instance-type INSTANCE_TYPE
                        Sets instance type to build the ami on. Defaults to
                        t2.xlarge.
  -ap CUSTOM_AMI_NAME_PREFIX, --ami-name-prefix CUSTOM_AMI_NAME_PREFIX
                        Specifies the prefix name of the resulting AWS
                        ParallelCluster AMI.
  -cc CUSTOM_AMI_COOKBOOK, --custom-cookbook CUSTOM_AMI_COOKBOOK
                        Specifies the cookbook to use to build the AWS
                        ParallelCluster AMI.
  --post-install POST_INSTALL_SCRIPT
                        Specifies the post install script to use to build the
                        AWS ParallelCluster AMI.
  --no-public-ip        Do not associate public IP to the Packer instance.
                        Defaults to associate public ip
  -c CONFIG_FILE, --config CONFIG_FILE
                        Defines an alternative config file.
  -r REGION, --region REGION
                        Indicates which region to connect to.

Build AMI by using VPC settings from configuration file:
  -t CLUSTER_TEMPLATE, --cluster-template CLUSTER_TEMPLATE
                        Specifies the 'cluster' section of the configuration
                        file to retrieve VPC settings.

Build AMI in a custom VPC and Subnet:
  --vpc-id VPC_ID       Specifies the VPC to use to build the AWS
                        ParallelCluster AMI.
  --subnet-id SUBNET_ID
                        Specifies the Subnet to use to build the AWS
                        ParallelCluster AMI.
```

**Comment by dan-schlecht** [comment]
cool thx.  That got me further, but now createami fails when trying to execute a script out of /tmp
_custom-alinux2: bash: /tmp/script_3393.sh: Permission denied_
https://github.com/aws/aws-parallelcluster/issues/2914
#https://github.com/aws/aws-parallelcluster/issues/2914

BTW, I think I may be referencing old AWS ParallelCluster documentation.
These env variables and CLI options for createami aren't listed:
https://github.com/awsdocs/aws-parallelcluster-user-guide/blob/main/doc_source/pcluster.createami.md
https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.createami.html

Seems like there should be a separate configuration section for createami to say which config parameters are supported
Seems like the CLI options should be updated.

**Comment by yuleiwan** [comment]
@dan-schlecht,
yes, there are some CLI options for createami aren't listed, we will update the user guide.

For the question that createami fails when trying to execute a script out of /tmp. The custom way is to remount the `/tmp` during createami process, this command can be added in packer json file, but we are not clear how did you remount /tmp in cluster create process, did you use an additional ebs volume? If so, when remounting `/tmp` in packer process, we need to define an extra volume as well. Could you provide you custom userdata to create cluster?

Thanks
Yulei

**Comment by dan-schlecht** [comment]
My current workaround for the pcluster create command is this

in the master-server-substack-2.11.0.cfn.yaml file after line 533 and in the compute-fleet-hit-substack-2.11.0.cfn.yaml file after line 461, I added commands to the userdata section:
# remount /tmp to allow execution
mount -o remount,exec /tmp
# fix SSL issues, needed for pip/pip3 installs
export PIP_CERT=/etc/ssl/certs/ca-bundle.crt
# fix SSL issues, needed for curl/openssl failures
export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt

I also had to update my aws-parallelcluster-2.11.0.cfn.json template file to reference my master-server-substack file that I uploaded to my S3 bucket.

I also had to update my pcluster config file to use the template_url and hit_template_url parameters.  The template_url config parameter points to my S3 bucket where I uploaded the aws-parallelcluster-2.11.0.cfn.json and master-server-substack files.  The hit_template_url points to a local file for my compute-fleet-hit file

**Comment by enrico-usai** [comment]
Hi @dan-schlecht 

It seems to me there are no pending action items in this ticket, the execution of scripts in the /tmp folder is tracked in another Issue.

I just want to share that in the package there is [an uploadTemplate.sh utility script](https://github.com/aws/aws-parallelcluster/blob/release-2.11/util/uploadTemplate.sh) that automatically performs the replacement of the substack url according to the bucket on which you're uploading the template.

Thanks

**Comment by dan-schlecht** [comment]
I agree it is the same but, I don't know if the solution will be the same.  It seems like createami and create a very different features.  For createami, it seems like packer may need to be involved in the solution.

For the uploadTemplate.sh script, how/when would I use this script?  Would I use it to help with my workaround for create cluster or create ami?
