### ISSUE TITLE
Question: Use slurm client from outside parallelcluster

### ISSUE THREAD

**Issue by kim0** [aws/aws-parallelcluster#2976]
I'm running parallelcluster and I'm also running workstation ec2 servers beside it. It would be very convenient to allow users to (sbatch, srun, sinfo, scancel ...etc) from their workstations directly without having to ssh into parallelcluster first. The workstation OS is centos7. I could install the slurm package on it, but it wasn't clear what it takes to get this client config running.

**Comment by yuleiwan** [comment]
@kim0,
Parallelcluster doesn't support such feature now, because slurm is installed and configured on cluster headnode and some RunInstance, EC2Terminate policies are attached to headnode. So you aren't able to submit job from your ec2 workstation without ssh into parallelcluster headnode.

**Comment by demartinofra** [comment]
while this setup is not supported out of the box by ParallelCluster, if I'm not missing something you should be able to run Slurm commands from a separate host as long as the client host shares the same Slurm config, binaries and the Munge realm (ParallelCluster generates a munge key for each cluster and you can find it under `/home/$default_os_user/.munge/.munge.key`). Probably you'll have to run Munge daemon from the client host with the same key present in the cluster.

For a more complete setup that allows you to control multiple clusters, you could look at [Slurm federation](https://slurm.schedmd.com/federation.html). In this case you'll have to configure slurm daemons on the client machine and also have accounting enabled. Also ,the same Munge key needs to be shared across all clusters.
