### ISSUE TITLE
Question: adding a second network interface to Slurm nodes

### ISSUE THREAD

**Issue by keien** [aws/aws-parallelcluster#3009]
What's the best way to configure ParallelCluster to create and attach a second network interface to its nodes (both master and compute)? Is it through the `additional_cfn_template` param, and if so is there any guidance on how we could use this?

**Comment by demartinofra** [comment]
Especially if you want to dynamically create and attach additional network interfaces to compute nodes it might be better to handle this in a pre/post installation script. However you'll need to build some custom logic to periodically clean-up unused network interfaces. At the moment we do not offer any hook to run actions on instance termination. You could register a Lambda function on EC2 events for instance state transition and filter instance types by tag to determine whether the instances belong to a given cluster.

Can I ask what is the use case for this?
