### ISSUE TITLE
v2.10.4 pcluster createami doesn't take AWS_SECURITY_GROUP_ID environment variable

### ISSUE THREAD

**Issue by zedgvgrzsrz** [aws/aws-parallelcluster#3106]
**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 2.10.4
 - Full cluster configuration without any credentials or personal data 
 - Cluster name:
 - [Optional] Arn of the cluster CloudFormation main stack:

Full cluster configuration file

> [aws]
> aws_region_name = eu-west-1
> 
> [aliases]
> ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
> 
> [global]
> cluster_template = default
> update_check = true
> sanity_check = true
> 
> [cluster default]
> key_name = pcluster_test
> scheduler = slurm
> master_instance_type = t2.small
> base_os = centos7
> vpc_settings = private-proxy
> queue_settings = compute
> custom_ami = ami-xxxxxxxxxxx
> master_root_volume_size = 32
> additional_iam_policies = arn:aws:iam::xxxxxxxxxxx
> ebs_settings = monvolume2 
> proxy_server = http://proxy-xxxxxxxxxxx
> s3_read_resource = arn:aws:s3:::xxxxxxxxxxx/*
> template_url = http://0.0.0.0:8000/aws-parallelcluster-2.10.4.cfn.json
> #custom_chef_cookbook = https://xxxxxxxxxxx.s3.xxxxxxxxxxx.amazonaws.com/custom-cookbook/aws-parallelcluster-custom-cookbook-2.10.tgz 
> #custom_chef_cookbook = http://0.0.0.0:8000/aws-parallelcluster-cookbook-2.10.4.tgz
> extra_json = { "cluster" : { "skip_install_recipes" : "no" } }
> 
> [ebs monvolume2]
> #shared_dir = vol2
> volume_type = io1
> volume_iops = 200
> encrypted = true
> ebs_kms_key_id = arn:aws:kms:xxxxxxxxxxx
> 
> [vpc private-proxy]
> vpc_id = vpc-xxxxxxxxxxx
> master_subnet_id = subnet-xxxxxxxxxxx
> compute_subnet_id = subnet-xxxxxxxxxxx
> use_public_ips = false
> vpc_security_group_id = sg-xxxxxxxxxxx
> additional_sg = sg-xxxxxxxxxxx
>  
> 
> [queue compute]
> enable_efa = false
> enable_efa_gdr = false
> compute_resource_settings = default
> 
> [compute_resource default]
> instance_type = t2.micro
> 
> 
> #[cw_log logger]
> #enable = false

**Bug description and how to reproduce:**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

Hello, we are trying to use pcluster createami, but the command fails on ssh timeout. That is because we have to give the instance our security-groups. And there is the problem. Packer doesn't use the security group id set with `export AWS_SECURITY_GROUP_ID=sg-xxxxxxx` and instead goes on creating its temporary security groups.

Here is our pcluster createami command : `pcluster createami -os centos7 -ap "createami" -ai ami-xxxxxxxx--no-public-ip -cc http://0.0.0.0:8000/aws-parallelcluster-cookbook-2.10.tgz
`

the export command is run just before the pcluster createami command. Here is the output of `$ printenv | grep AWS_SECURITY`
> AWS_SECURITY_GROUP_ID=sg-xxxxxxxxxx

Packer build part of packer log file : 

> + packer build -color=false -var-file=/tmp/tmpn33bawmm/aws-parallelcluster-cookbook-2.10.4/amis/packer_variables.json -only=custom-centos7 /tmp/tmpn33bawmm/aws-parallelcluster-cookbook-2.10.4/amis/packer_centos7.json
> ==> custom-centos7: Prevalidating any provided VPC information
> ==> custom-centos7: Prevalidating AMI Name: pclustercreateami-aws-parallelcluster-2.10.4-centos7-hvm-x86_64-202108090757
> custom-centos7: Found Image ID: ami-xxxxxxxxxxxxx
> ==> custom-centos7: Creating temporary keypair: packer_6110dff7-1a83-d069-7255-70d62dcbb466
> ==> custom-centos7: Creating temporary security group for this instance: packer_6110dff8-8b46-8560-21ed-ab8e0005a5dd
> ==> custom-centos7: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
> ==> custom-centos7: Launching a source AWS instance...
> ==> custom-centos7: Adding tags to source instance
> custom-centos7: Adding tag: "Name": "Packer Builder ami-xxxxxxxxxxxxxx"
> custom-centos7: Adding tag: "parallelcluster_version": "aws-parallelcluster-2.10.4"
> custom-centos7: Adding tag: "build_date": "202108090757"
> custom-centos7: Instance ID: i-xxxxxxxxxxxxx
> ==> custom-centos7: Waiting for instance (xxxxxxxxxxxxxx) to become ready...
> ==> custom-centos7: Using SSH communicator to connect: x.x.x.x
> ==> custom-centos7: Waiting for SSH to become available...
> 

Any ideas why Packer wouldn't use the given security group id ?

Thanks

**Comment by enrico-usai** [comment]
Hi @zedgvgrzsrz 

the support for AWS_SECURITY_GROUP_ID override has been added as part of [2.11.0 release](https://github.com/aws/aws-parallelcluster/blob/release-2.11/CHANGELOG.md#2110) so it is not included in 2.10.4.

Patch: https://github.com/aws/aws-parallelcluster-cookbook/pull/984

**Comment by zedgvgrzsrz** [comment]
Hi @enrico-usai 

Thanks for the quick answer. We have applied the same modifications you did in [aws/aws-parallelcluster-cookbook#984](https://github.com/aws/aws-parallelcluster-cookbook/pull/984), (updated our packer_centos7.json in our custom-cookbook) while not upgrading to v2.11, with no results. Can you think of anything else that could make Packer not look for the environment variable ?
Thanks

**Comment by enrico-usai** [comment]
@zedgvgrzsrz 

The cookbook used by the `createami` command is [the official one](https://github.com/aws/aws-parallelcluster/blob/release-2.10/cli/src/pcluster/createami.py#L56) and not the one you're setting in the config.

You can double check the CLI logs: `~/.parallelcluster/pcluster-cli.log` and search for [this message](https://github.com/aws/aws-parallelcluster/blob/release-2.10/cli/src/pcluster/createami.py#L87) explaining which is the cookbook used for the ami creation.

The are no ways to override this behaviour other than using the 2.11.0 package or modify the CLI code of the 2.10.4.

**Comment by zedgvgrzsrz** [comment]
@enrico-usai 

We are setting our custom cookbook through the -cc parameter to the pcluster createami command.
Output of ~/.parallelcluster/pcluster-cli.log : 

> 2021-08-11 08:54:47,337 - INFO - createami - Cookbook: http://0.0.0.0:8000/aws-parallelcluster-cookbook-2.10.tgz

**Comment by zedgvgrzsrz** [comment]
since the cookbook contains private information about our organization, we are serving it to ParallelCluster through a web server running locally on the machine, hence the http://0.0.0.0:8000/aws-parallelcluster-cookbook-2.10.tgz url

**Comment by enrico-usai** [comment]
I just tried the following:
```
$ pcluster version
2.11.1

$ export AWS_SECURITY_GROUP_ID=sg-test
$ pcluster createami --os alinux2 -ai ami-02b4e72b17337d6c1 --region eu-west-1
Building AWS ParallelCluster AMI. This could take a while...
Base AMI ID: ami-02b4e72b17337d6c1
Base AMI OS: alinux2
Instance Type: t2.xlarge
Region: eu-west-1
VPC ID: vpc-xxx
Subnet ID: subnet-yyy
Template: https://eu-west-1-aws-parallelcluster.s3.eu-west-1.amazonaws.com/templates/aws-parallelcluster-2.11.1.cfn.json
Cookbook: https://eu-west-1-aws-parallelcluster.s3.eu-west-1.amazonaws.com/cookbooks/aws-parallelcluster-cookbook-2.11.1.tgz
Post install script dir not specified.
Packer log: /var/folders/3n/pvwhfrgx48l1jldm777526c80000gr/T/packer.log.20210816-153653.5hk0d0sn
Packer status: 	exit code 1

No custom AMI created


$ cat /var/folders/3n/pvwhfrgx48l1jldm777526c80000gr/T/packer.log.20210816-153653.5hk0d0sn
[...]
+ packer build -color=false -var-file=/var/folders/3n/pvwhfrgx48l1jldm777526c80000gr/T/tmpm5h7l2m1/aws-parallelcluster-cookbook-2.11.1/amis/packer_variables.json -only=custom-alinux2 /var/folders/3n/pvwhfrgx48l1jldm777526c80000gr/T/tmpm5h7l2m1/aws-parallelcluster-cookbook-2.11.1/amis/packer_alinux2.json
==> custom-alinux2: Prevalidating any provided VPC information
==> custom-alinux2: Prevalidating AMI Name: custom-ami-aws-parallelcluster-2.11.1-amzn2-hvm-x86_64-202108161536
custom-alinux2: Found Image ID: ami-02b4e72b17337d6c1
==> custom-alinux2: Creating temporary keypair: packer_611a69f9-...-4cea4b1cc382
==> custom-alinux2: Deleting temporary keypair...
Build 'custom-alinux2' errored after 9 seconds 402 milliseconds: Couldn't find specified security group: InvalidGroupId.Malformed: Invalid id: "sg-test"
status code: 400, request id: b72ee2b2-d9df-46dd-b73e-71b55223da01

==> Wait completed after 9 seconds 405 milliseconds

==> Some builds didn't complete successfully and had errors:
--> custom-alinux2: Couldn't find specified security group: InvalidGroupId.Malformed: Invalid id: "sg-test"
status code: 400, request id: b72ee2b2-d9df-46dd-b73e-71b55223da01
```

This confirms that the Security Group exported in the environment is passed ahead to the packer.


Your timeout issue:
```
==> custom-centos7: Waiting for instance (xxxxxxxxxxxxxx) to become ready...
==> custom-centos7: Using SSH communicator to connect: x.x.x.x
==> custom-centos7: Waiting for SSH to become available...
```
is probably due to the fact that the security group you're passing doesn't permit SSH communication from the node in which `pcluster createami` command is executed and the instance used to create the custom image.

Let us know if it helps
