### ISSUE TITLE
How to specify queue of cluster cross Multi-AZ？

### ISSUE THREAD

**Issue by hy714335634** [aws/aws-parallelcluster#3114]
Hi~
Is there any native methods or configuration can help to build cluster cross Multi-AZ when the Version of Parallelcluster > 2.8.0？

**Comment by enrico-usai** [comment]
Hi @hy714335634 it is not possible. I'm going to mark this as feature request.

**Comment by tanantharaman** [comment]
In the meantime you can use the aws cli to expand the AutoScalingGroup used by parallelcluster to all possible AZs. I use a csh script to create my parallelcluster as shown below. Be warned that you will be charged $0.01/GB of NFS traffic from the compute nodes that are NOT in the same AZ as the head node.
```csh
----------------------------------------Start of csh script --------------
#!/bin/csh -f

set REGION = "us-east-2"
set INSTANCE = "c5n.18xlarge" # compute instance
set CLUSTER = "mycluster" # name of cluster
set CONFIG = "~/.parallelcluster/config" 

pcluster create -c $CONFIG $CLUSTER # add additional pcluster options here

# Find list of AZs that currently have the compute instance
set NOW = `date -Iseconds`
set AZ_LIST = `/usr/bin/aws --region $REGION ec2 describe-spot-price-history --instance-types $INSTANCE --product-description Linux/UNIX --start-time $NOW | sort -n -k5 | awk '{print $2}' | sort | uniq | awk -vORS=\| '{print $1}' | sed 's/|$/\n/'`
set SUBNET_IDS = `/usr/bin/aws --region $REGION ec2 describe-subnets --filters "Name=defaultForAz,Values=true" | egrep $AZ_LIST |  awk -vORS=, '{print $(NF-1)}' | sed 's/,$/\n/'`

# Expand to multiple availability zones with vpc subnets in SUBNET_IDS
set ASG = `/usr/bin/aws --region $REGION autoscaling describe-auto-scaling-groups | egrep autoScalingGroupName | egrep ${CLUSTER}-ComputeFleet | awk '{print $3}'`
aws --region $REGION autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG --vpc-zone-identifier $SUBNET_IDS

# Avoid spot terminations due to rebalancing across availability zones, if using multiple availability zones
aws --region $REGION autoscaling suspend-processes --auto-scaling-group-name $ASG --scaling-processes AZRebalance
```

**Comment by hy714335634** [comment]
> Hi @hy714335634 it is not possible. I'm going to mark this as feature request.

Great, It will be very helpful for us expand scale up cluster

**Comment by hy714335634** [comment]
@tanantharaman 
Thanks for your detail answer. 
I have some confusion about the operation,  It seem we cannot control multi-az by Autoscaling Group with the new version (>2.8.0), I am not sure if we can use. Some new features like **Multi-queue,Multi-type** compute instances  also are good in our scenario, so we decide use the latest version (**>2.10.0) of Parallelcluster** with Slurm, I remember that in versions after 2.8.0, **the queue is not managed by ASG, the registration and DNS resolver of nodes also has changed**.

**Comment by hy714335634** [comment]
@tanantharaman 
Thanks for your detail answer. 
I have some confusion about the operation,  It seem we cannot control multi-az by Autoscaling Group with the new version (>2.8.0), I am not sure if we can use. Some new features like **Multi-queue,Multi-type** compute instances  also are good in our scenario, so we decide use the latest version (**>2.10.0) of Parallelcluster** with Slurm, I remember that in versions after 2.8.0, **the queue is not managed by ASG, the registration and DNS resolver of nodes also has changed**.

**Comment by tanantharaman** [comment]
It still works for me with 2.10.3, but I use SGE so cannot use Multi-queue,Multi-type features : I have another workaround script to enable multiple equivalent compute instance types (eg c5.18xlarge, c5n.18xlarge, c5d.18xlarge) with SGE, provided they are all equivalent to the original compute instance, by directly updating the ASG.  However multiple SGE queues, are not supported, so I can only use one instance type at a time, but am able to switch between types (eg c5.18xlarge to m5.24xlarge) by using "pcluster update ...", as long as the update is done after all compute instances are idle and deallocated (by lowering the desired value to 0).

**Comment by hy714335634** [comment]
@tanantharaman 
Got it, you are right, SGE and PBS is still managed by ASG, in order to prevent the EC2 being shut down by asg, it is also necessary to turn off the stop behavior of az-balance.

**Comment by enrico-usai** [comment]
Closing this in favour of: https://github.com/aws/aws-parallelcluster/issues/3576
Feel free to add your use cases there. Thanks!
