### ISSUE TITLE
(UnauthorizedOperation) when calling the DescribeRegions operation: You are not authorized to perform this operation. ERROR: No options found for AWS Region ID

### ISSUE THREAD

**Issue by ritwik7** [aws/aws-parallelcluster#3140]
**The ParallelCluster team uses this template to report known issues on github. If you are reporting an issue, please use the 'Bug report' template instead.**

## Bug description
I am trying to run pcluster configure but it keeps giving me the error "Failed with error: An error occurred (UnauthorizedOperation) when calling the DescribeRegions operation: You are not authorized to perform this operation.
ERROR: No options found for AWS Region ID "

I've followed the instructions in https://github.com/aws/aws-parallelcluster/issues/1609 and attached a policy with ec2:DescribeRegions and additionally the permissions listed ; but the problem still persists. 

Please help
thanks

**Comment by chenwany** [comment]
Hi 
Sorry for reply late, 
It seems like a problem of lacking some IAM policy, we need `DescribeRegions` permission to list all the regions for pcluster configure.
Could you check the following:
- `aws configure` is run before parallelcluster configure: see doc here: https://docs.aws.amazon.com/parallelcluster/latest/ug/getting-started-configuring-parallelcluster.html
- Make sure the policy is attach to the correct role: You can run `aws sts get-caller-identity` to see which role you are using, and see if the policy is correctly attach to the specified role
Could you also give us some other information, for example, the parallelcluster version, where do you run parallelcluster configure  to help us better understand the problem?
For example, do you run parallelcluster configure on a virtual machine or locally? Which operating system you are using? If it is running on the instance, does the instance attach DescribeRegions policy?

Thanks!
