### ISSUE TITLE
Running qsub with post-install

### ISSUE THREAD

**Issue by awacs** [aws/aws-parallelcluster#316]
I want to start a workflow with qsub as soon as the cfncluster creation is successful. However when I put the command into the post install script specifically for the master node, it returns qsub command not found. What is going on?

**Comment by mohanasudhan** [comment]
**post-install actions are called after cluster bootstrap is complete, as the last action before an instance is considered complete. Typical post-install actions may include changing scheduler settings, modifying storage or packages.**

Ref: http://cfncluster.readthedocs.io/en/latest/pre_post_install.html?highlight=post_install#custom-bootstrap-actions

Workflow has to be initiated outside of cfncluster, cfncluster post_install as mentioned above is part of cluster bootstrapping. Poll for cluster creation completion & execute qsub command via [Ec2 Run command](https://docs.aws.amazon.com/systems-manager/latest/userguide/execute-remote-commands.html) or via ssh.

**Comment by awacs** [comment]
Is there a way to run command as ec2-user automatically when the cfncluster creation is successful, without ssh or ec2 run?

**Comment by jocherry** [comment]
Yes we believe so, but it will take a but of work based on your environment.
Since you are running as root, you will need to su to your user (ec2-user it sounds like), then create your script, then add your needed PATH env variables, then you should be able to run qsub.

As a trivial example:
su - ubuntu; echo "#!/bin/bash echo Hello World" > script.sh; PATH=$PATH:/opt/sge/bin/lx-amd64/ (+ more variables); qsub script.sh

For an ubuntu and SGE example (NOTE this does not fully work, but it does find qsub).
You should be able to work out a post install script that allows you to run qsub.

Overall this sounds like it could be a useful feature, and will add it as an enhancement.

**Comment by jprobichaud** [comment]
I'm wonder how true is this statement from @mohanasudhan  

> Typical post-install actions may include changing scheduler settings, modifying storage or packages.

I'm trying to add a complex variable when the compute node runs the post_install script and I'm getting the error below.

command:
``` 
su -c "SGE_ROOT=/opt/sge /opt/sge/bin/lx-amd64/qconf -mattr exechost complex_values ram_free=30G `hostname`" sgeadmin
```

Error:
```
denied: host "ip-172-31-31-210.us-west-2.compute.internal" is neither submit nor admin host
```
If I run the exact same command from the compute node after it gets visible in qhost, then the command works without problem.

**Comment by jw-feng** [comment]
Hi, I am trying to do the same thing as jprobichaud by calling qconf to modify settings for a compute node.  I am also getting the same denied message:
`denied: host <hostname> is neither submit nor admin host`

**Comment by demartinofra** [comment]
post-install script is meant to allow the configuration of a node before this gets added to the scheduler and that is why you are not able to run any scheduler specific config command on compute nodes at that stage. 

What you could do is to execute scheduler configuration commands on the master node only, by adding a conditional statement to your post-install script as described in the [official docs](https://docs.aws.amazon.com/parallelcluster/latest/ug/pre_post_install.html). Of course at that point in time the scheduler won't have the compute nodes available in its configuration.

An idea for a potential enhancement is to expose a hook to execute a custom script after a node gets added to the scheduler.

**Comment by demartinofra** [comment]
There is no plan for now to support job submission in post-install scripts because such scripts are meant to provide hooks for software installation and are executed when the scheduler daemons haven't been initialized.
