### ISSUE TITLE
AMI not recognizing user when expanding tar file

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#3217]
Hello,
I'm beginning to work with v2.11.2 (CentOS8-AArch64) but a completely unexpected problem has cropped up. I have moved a tar file to the /opt directory. However, and when I untar it, the new subdirectory is assigned an ownership of "1006" (rather than root), which suggests that the OS is not recognizing the user. 
```
$ ls -la
total 56388
drwxr-xr-x   3 root   root        152 Aug 31 14:45 .
drwxr-xr-x. 12 root   root        145 Aug 31 14:36 ..
drwxrwxr-x  15   1006   1006     4096 Nov 14  2020 gmp-6.2.1
```
Thanks

**Comment by tilne** [comment]
Hi @afernandezody, some questions for you:

* Were you using one of the default ParallelCluster AMIs, or one that you created yourself?
* Can you provide a script that reproduces the problem?
* Are you running the commands to move and/or expand the archive as root, or as a different user?

**Comment by afernandezody** [comment]
Hi @**tilne**,
I'm using ami-02b0ba5d6493cc6d1 and there isn't much of a script other than untarring the file:
`$sudo tar -xvf gmp-6.2.1.tar
`
This is from the /opt/my_directory subdirectory so sudo is necessary. It's a pretty weird error and completely unexpected.

**Comment by tilne** [comment]
Even though the script isn't complicated it helps to be able reproduce the problem. I tested this by attempting to unpack what I think is a similar tarball in subdirectories of /opt owned by root and the default user.

Downloading the source:
```
[centos@ip-172-31-15-120 ~]$ wget https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz
--2021-08-31 20:14:07--  https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz
Resolving gmplib.org (gmplib.org)... 130.242.124.102
Connecting to gmplib.org (gmplib.org)|130.242.124.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2027316 (1.9M) [application/octet-stream]
Saving to: ‘gmp-6.2.1.tar.xz’

gmp-6.2.1.tar.xz                                                    100%[=================================================================================================================================================================>]   1.93M   453KB/s    in 4.4s

2021-08-31 20:14:12 (453 KB/s) - ‘gmp-6.2.1.tar.xz’ saved [2027316/2027316]
```

Creating directories owned by root and copying the archive into it:

```
[centos@ip-172-31-15-120 ~]$ sudo mkdir /opt/dir-owned-by-root
[centos@ip-172-31-15-120 ~]$ sudo cp ./gmp-6.2.1.tar.xz /opt/dir-owned-by-root
```

Unpacking as root the file owned by the default user within in the subdirectory owned by root looks to reproduce your situation:

```
[centos@ip-172-31-15-120 dir-owned-by-root]$ cd /opt/dir-owned-by-root
[centos@ip-172-31-15-120 dir-owned-by-root]$ ll
total 1980
-rw-r--r-- 1 root root 2027316 Aug 31 20:35 gmp-6.2.1.tar.xz
[centos@ip-172-31-15-120 dir-owned-by-root]$ sudo tar xf gmp-6.2.1.tar.xz
[centos@ip-172-31-15-120 dir-owned-by-root]$ ll
total 1984
drwxrwxr-x 15 1006 1006    4096 Nov 14  2020 gmp-6.2.1
-rw-r--r--  1 root root 2027316 Aug 31 20:35 gmp-6.2.1.tar.xz
[centos@ip-172-31-15-120 dir-owned-by-root]$ ll ./gmp-6.2.1 | head
total 4128
-rw-rw-r--  1 1006 1006  124127 Nov 14  2020 acinclude.m4
-rw-rw-r--  1 1006 1006  363087 Nov 14  2020 aclocal.m4
-rw-rw-r--  1 1006 1006    3681 Nov 14  2020 asl.h
-rw-rw-r--  1 1006 1006    1718 Nov 14  2020 assert.c
-rw-rw-r--  1 1006 1006    3945 Nov 14  2020 AUTHORS
-rw-rw-r--  1 1006 1006    3073 Nov 14  2020 bootstrap.c
-rw-rw-r--  1 1006 1006 1182652 Nov 14  2020 ChangeLog
-rw-rw-r--  1 1006 1006    1846 Nov 14  2020 compat.c
-rwxr-xr-x  1 1006 1006    7333 Sep  5  2015 compile
```

This seems like expected behavior. In the `tar` man page that ships on that AMI I see the following:

```man
       --same-owner
              Try extracting files with the same ownership as exists in the archive (default for superuser).
```

I see the same thing in the [GNU manual](https://www.gnu.org/software/tar/manual/tar.html#Attributes).

**Comment by afernandezody** [comment]
@**tilne**,
I transferred the file directly but that's not important. My expectation (as it has been the case in dozens of previous occasions) is that the owner and group would be root, not 1006. This "1006" thing is new to me but reading some posts suggests that the OS is not recognizing the users properly.

**Comment by tilne** [comment]
The 1006 is probably displayed because those were the owner IDs associated with the file wherever the archive was created and they don't exist on the local system. Would using the `--no-same-owner`/`-o` fix the problem?

**Comment by afernandezody** [comment]
The `--no-same-owner` flag seems to help. Thanks.
