### ISSUE TITLE
Add option to append the cluster name to the node name

### ISSUE THREAD

**Issue by mark-cresset** [aws/aws-parallelcluster#3238]
For a number of reasons we often have multiple independent clusters running in the same AZ. It sometimes gets a little confusing having lots of machines called "master" and other called "compute", without knowing which cluster they belong to. A useful option in StarCluster was to append the cluster name to the default machine name, so for cluster "mycluster" the machines would be called "Master_mycluster" and "Compute_mycluster". Could this (or something similar) be added? I know I can add tags to the different clusters and filter on that, but being able to differentiate quickly on machine name would be useful.

**Comment by tilne** [comment]
Thanks for the request, Mark. I'll note it in our backlog and discuss it with the team.

**Comment by tilne** [comment]
> being able to differentiate quickly on machine name would be useful

when you say you want to differentiate quickly, do you mean visually when looking at the EC2 console?

**Comment by mark-cresset** [comment]
Yes - it's just easier when looking at the console to be able to see what multiple clusters are doing without having to filter on tags or keys or something.

**Comment by enrico-usai** [comment]
Hi @mark-cresset 
I just want to suggest that you can add new columns to the console, by clicking in the "gear" icon in the top right of the console and then adding the column related to the tag you want to monitor. 

You can also reorder the columns to move the interesting ones on the left. This should give you an experience similar on having the cluster name in the instance name without the need to "filtering" by using tags.

Let us know if it helps.

**Comment by enrico-usai** [comment]
The `Name` is a particular tag that can be easily modified by the user to identify a specific instance. 

ParallelCluster sets `parallelcluster:cluster-name` (V3) and `ClusterName` (V2) tags to all the instances.
We documented existing tags in official documentation:
* 2.x https://docs.aws.amazon.com/parallelcluster/latest/ug/resources-tags.html
* 3.x https://docs.aws.amazon.com/parallelcluster/latest/ug/resources-tags-v3.html

The usage of these tags with the possibility to add a new column in the AWS Console to show the tag values should solve this issue.

Thanks for your inputs.
