### ISSUE TITLE
Excessive ubuntu1804 OS update activity on compute nodes

### ISSUE THREAD

**Issue by eshpc** [aws/aws-parallelcluster#3269]
**Required Info:**
 - AWS ParallelCluster version: 2.11.0
 - Full cluster configuration without any credentials or personal data:
 
[global]
cluster_template = default
update_check = true
sanity_check = true

[aws]
aws_region_name = us-east-2

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[cluster default]
key_name = <key_name>
base_os = ubuntu1804
scheduler = slurm
vpc_settings = default
scaling_settings = custom
ebs_settings = fs_ebs
efs_settings = fs_efs
master_instance_type = c5.xlarge
queue_settings = intel-spot,intel-noefa-spot
enable_intel_hpc_platform = false
disable_hyperthreading = true
s3_read_resource = <s3_info>

[vpc default]
vpc_id = <vpc_id>
master_subnet_id = <subnet_id>
vpc_security_group_id = <sg_id>

[scaling custom]
scaledown_idletime = 4

[ebs fs_ebs]
shared_dir = data
encrypted = true
volume_type = gp3
volume_size = 60
volume_iops = 3000
volume_throughput = 125

[efs fs_efs]
efs_fs_id = <efs_name>
shared_dir = shared

[queue intel-spot]
compute_resource_settings = c5n-18xlarge
compute_type = spot
enable_efa = true
placement_group = DYNAMIC

[queue intel-noefa-spot]
compute_resource_settings = c5n-18xlarge-noefa
compute_type = spot
enable_efa = false
placement_group = DYNAMIC

[compute_resource c5n-18xlarge]
instance_type = c5n.18xlarge
min_count = 0
initial_count = 0
max_count = 16

[compute_resource c5n-18xlarge-noefa]
instance_type = c5n.18xlarge
min_count = 0
initial_count = 0
max_count = 16

**Bug description and how to reproduce:**
When running a job on a compute node (via SLURM), ubuntu1804 OS update tasks are taking an excessive amount of time and CPU resource, even after the node (c5n.18xlarge) has been running for 15 mins. This makes it very difficult to do accurate benchmarking of short running jobs. Is it possible to disable the automatic updating of the OS and just use the version in the AMI you provide as is? I know it is good in general to get the fixes in the OS updates, but it would be nice to be able to control this with an option in ParallelCluster (e.g. on the queue or compute_resource settings), or doing the updates manually via adding commands in a post_install script.

Examples of the OS update processes running (from ps -ef on the compute node):

root      1773     1  0 09:10 ?        00:00:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
root      6935  6889 76 09:14 ?        00:02:50 /usr/bin/python3 /usr/bin/unattended-upgrade
root      7684  6935 10 09:18 ?        00:00:00 /usr/bin/python3 /usr/bin/unattended-upgrade
root      7832  7684  0 09:18 ?        00:00:00 /usr/bin/python3 /usr/bin/unattended-upgrade

(after about 10 mins):

root     25026  6935  0 09:22 ?        00:00:00 /usr/bin/python3 /usr/bin/unattended-upgrade
root     25148 25026  0 09:23 pts/1    00:00:00 /usr/bin/dpkg --status-fd 12 --configure --pending
root     25153 25148  0 09:23 pts/1    00:00:00 /bin/sh /var/lib/dpkg/info/linux-headers-5.4.0-1056-aws.postinst configu
root     25154 25153  0 09:23 pts/1    00:00:00 run-parts --report --exit-on-error --arg=5.4.0-1056-aws /etc/kernel/head
root     25155 25154  0 09:23 pts/1    00:00:00 /bin/sh /usr/lib/dkms/dkms_autoinstaller start 5.4.0-1056-aws
root     25161 25155  0 09:23 pts/1    00:00:00 /bin/bash /usr/sbin/dkms autoinstall --kernelver 5.4.0-1056-aws
root     29999 25161  0 09:23 pts/1    00:00:00 /bin/bash /usr/sbin/dkms autoinstall --kernelver 5.4.0-1056-aws
root     30474 29999  0 09:23 pts/1    00:00:00 /bin/bash /usr/sbin/dkms autoinstall --kernelver 5.4.0-1056-aws
root     30475 29999  0 09:23 pts/1    00:00:00 /bin/bash /usr/sbin/dkms autoinstall --kernelver 5.4.0-1056-aws
root     30476 30474  0 09:23 pts/1    00:00:00 make -j4 NV_EXCLUDE_BUILD_MODULES= KERNEL_UNAME=5.4.0-1056-aws IGNORE_CC
root     30482 30476  0 09:23 pts/1    00:00:00 /bin/sh -c make "CC=cc"  -C /lib/modules/5.4.0-1056-aws/build M=/var/lib
root     30483 30482  0 09:23 pts/1    00:00:00 make CC=cc -C /lib/modules/5.4.0-1056-aws/build M=/var/lib/dkms/nvidia/4
root     30913 30483  3 09:23 pts/1    00:00:00 make -f ./scripts/Makefile.build obj=/var/lib/dkms/nvidia/460.73.01/buil
root     36119 30475  0 09:23 pts/1    00:00:00 sleep 3
root     36322 30913  0 09:24 pts/1    00:00:00 /bin/sh -c set -e;  echo '  CC [M]  /var/lib/dkms/nvidia/460.73.01/build
root     36323 36322  0 09:24 pts/1    00:00:00 cc -Wp,-MD,/var/lib/dkms/nvidia/460.73.01/build/nvidia-uvm/.uvm_va_block
root     36324 36323  0 09:24 pts/1    00:00:00 /usr/lib/gcc/x86_64-linux-gnu/7/cc1 -quiet -nostdinc -I ./arch/x86/inclu
root     36339 30913  0 09:24 pts/1    00:00:00 /bin/sh -c set -e;  echo '  CC [M]  /var/lib/dkms/nvidia/460.73.01/build
root     36340 36339  0 09:24 pts/1    00:00:00 cc -Wp,-MD,/var/lib/dkms/nvidia/460.73.01/build/nvidia-uvm/.uvm_range_gr
root     36341 36340  0 09:24 pts/1    00:00:00 /usr/lib/gcc/x86_64-linux-gnu/7/cc1 -quiet -nostdinc -I ./arch/x86/inclu
root     36356 30913  0 09:24 pts/1    00:00:00 /bin/sh -c set -e;  echo '  CC [M]  /var/lib/dkms/nvidia/460.73.01/build
root     36357 36356  0 09:24 pts/1    00:00:00 cc -Wp,-MD,/var/lib/dkms/nvidia/460.73.01/build/nvidia-uvm/.uvm_thread_c
root     36358 36357  0 09:24 pts/1    00:00:00 /usr/lib/gcc/x86_64-linux-gnu/7/cc1 -quiet -nostdinc -I ./arch/x86/inclu

**Additional context:**
I haven't tested other OS versions.

**Comment by lukeseawalker** [comment]
Hello @eshpc,
thank you for your feedback.
We are aware of the problematic of unattended upgrades and we are going to improve the situation in the future, starting from next version, see https://github.com/aws/aws-parallelcluster/pull/2915 for example.

**Comment by eshpc** [comment]
Hi @lukeseawalker, thanks for the information. Good to know that it will be improved in the next version. In the meantime, I tried making those changes to /etc/apt/apt.conf.d/20auto-upgrades in my SLURM script, and it helped a lot. (Doing it in a pre-install script would be better of course).

**Comment by lukeseawalker** [comment]
Hello @eshpc,
PCluster version 3.0.0 is out and Ubuntu unattended upgrades are disabled by default
