### ISSUE TITLE
awsbatch cluster with 2 FSx Lustre and ephemeral SSD storage

### ISSUE THREAD

**Issue by andrei-xdlab** [aws/aws-parallelcluster#3278]
*Required Info:**
 - AWS ParallelCluster version  2.11.0
 - Cluster name:cpf-sdt

1. Trying to mount 2 FSx Lustre filesystem is generating syntax error. What is appropriate way to mount 2 Lustre filesystems -  /share and /home. Do you support mounting FSx Luster /home?

[cluster awsbatch]
fsx_settings = fs1, fs2
scheduler = awsbatch

[fsx fs1]
shared_dir = /shared
fsx_fs_id = fs-xxxx

[fsx fs2]
shared_dir = /home
fsx_fs_id = fs-xxxxx

2. Is ephemeral_dir option supported on aws batchworker nodes? We have a requirement to mount SSD ephemeral on worker node and map to a AWS batch container. What is a best way to accomplish that? How to modify AWS Batch job definition file to map /scratch from worker node to a container?

[cluster awsbatch]
ephemeral_dir=scratch

3. How does authentication work when using awsbatch cluster option? We need to create local users on batch head node and worker node, and essentially in the docker file. I believe by default awsbsub jobs running as root.

Template

[global]
cluster_template = awsbatch
update_check = true
sanity_check = true

[cluster awsbatch]
key_name = cpf-sdt
scheduler = awsbatch
master_instance_type = c5.4xlarge
base_os = alinux2
cluster_type = spot
spot_bid_percentage = 85
vpc_settings = default
compute_instance_type = c5d.4xlarge
min_vcpus = 0
desired_vcpus = 0
max_vcpus = 3200
dcv_settings = custom-dcv
dashboard_settings = custom-dashboard
#ebs_settings = custom1
fsx_settings = fs1, fs2
s3_read_write_resource = arn:aws:s3:::dev-xxx/*

[dashboard custom-dashboard]
enable = true

[dcv custom-dcv]
enable = master
port = 443
access_from = 0.0.0.0/0

[fsx fs1]
shared_dir = /shared
fsx_fs_id = fs-xxxx

[fsx fs2]
shared_dir = /home
fsx_fs_id = fs-xxxxx

#[ebs custom1]
#shared_dir = /home
#volume_type = gp2
#volume_size = 500

**Comment by yuleiwan** [comment]
Hi @andrei-xdlab 
> 1. Trying to mount 2 FSx Lustre filesystem is generating syntax error. What is appropriate way to mount 2 Lustre filesystems - /share and /home. Do you support mounting FSx Luster /home?

we don't support to mount multiple Lustre filesystems.

> 2. Is ephemeral_dir option supported on aws batchworker nodes? We have a requirement to mount SSD ephemeral on worker node and map to a AWS batch container. What is a best way to accomplish that? How to modify AWS Batch job definition file to map /scratch from worker node to a container?

yes, ephemeral_dir option is supported on batch, you can specify it under cluster section `ephemeral_dir = /scratch`. You can use customized job definition by specifying in awsbatch_cli.cfg.

> 3. How does authentication work when using awsbatch cluster option? We need to create local users on batch head node and worker node, and essentially in the docker file. I believe by default awsbsub jobs running as root.

We don't support multi-user environment in pcluster 2.11

**Comment by enrico-usai** [comment]
Hi @andrei-xdlab 

> Do you support mounting FSx Luster /home?

This is tracked here: https://github.com/aws/aws-parallelcluster/issues/2441

> What is a best way to accomplish that? How to modify AWS Batch job definition file to map /scratch from worker node to a container?

This question is similar to the one in https://github.com/aws/aws-parallelcluster/issues/3279 on which I suggested this wiki page: https://github.com/aws/aws-parallelcluster/wiki/AWS-Batch-with-a-custom-Dockerfile . This is the only official way to customize the docker container for now.

> How does authentication work when using awsbatch cluster option? We need to create local users on batch head node and worker node, and essentially in the docker file

I don't have an official suggestion for it. ParallelCluster is considered a single-user environment. 
You might take a look at this wiki page: https://github.com/aws/aws-parallelcluster/wiki/MultiUser-Support and with Docker customization wiki page you might put something together but I'd avoid this kind of customization, because hard of debug in case of issues. We're working to add multi-user feature for 3.1.0 release (for Slurm only).
