### ISSUE TITLE
ability to customize JobDefinition files created by ParallelCluster

### ISSUE THREAD

**Issue by andrei-xdlab** [aws/aws-parallelcluster#3279]
If you are reporting an issue with AWS Parallelcluster / CfnCluster please make sure to add the following data in order to facilitate the root cause detection:

**Required Info:**
 - AWS ParallelCluster version 2.11.0
 - Full cluster configuration without any credentials or personal data
 - Cluster name: awsbatch

Do we have ability to customize JobDefinition files created by ParallelCluster to mount ephemeral SSH /scratch to a container. I can create a new custom JobDef but how to use it with awsbsub command?

BatchJobDefinitionMnpArn: arn:aws:batch:us-east-1:544818234190:job-definition/JobDefinitionMNP-5f042afd90c627d:1

**Comment by yuleiwan** [comment]
Hi @andrei-xdlab, you can specify customize JobDefinition in ~/.parallelcluster/awsbatch-cli.cfg
```
[main]
cluster_name = batch
region = us-east-2
job_definition_mnp = ...
```

**Comment by enrico-usai** [comment]
Hi @andrei-xdlab 
I think this might help: https://github.com/aws/aws-parallelcluster/wiki/AWS-Batch-with-a-custom-Dockerfile

Enrico
