### ISSUE TITLE
Custom AMI creation (pcluster createami/pcluster build-image) fails with ARM architecture 

### ISSUE THREAD

**Issue by chenwany** [aws/aws-parallelcluster#3323]
**Bug description**
When provisioning AMIs via either the `pcluster createami` command (on pcluster 2.x) or `pcluster build-image` command (on pcluster 3.0.0), the `arm_pl_install` recipe in the ParallelCluster cookbook will fail with the following error message:
```
FATAL: OpenSSL::SSL::SSLError: remote_file[/opt/parallelcluster/sources/gcc-9.3.0.tar.gz] (aws-parallelcluster::arm_pl_install line 75) had an error: OpenSSL::SSL::SSLError: SSL Error connecting to https://ftp.gnu.org/gnu/gcc/gcc-9.3.0/gcc-9.3.0.tar.gz - SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
```

**Causes of the problem**
This error is the result of the [Letsencrypt Root CA X3 expiration](https://community.letsencrypt.org/t/help-thread-for-dst-root-ca-x3-expiration-september-2021/149190) on 30 September 2021. The certificate embedded in CINC version used is outdated. See Github issue on Chef for more details: https://github.com/chef/chef/issues/12126.

**How to reproduce the bug**
It happens when creating custom ARM architecture AMI using the following command.
For pcluster2:
```
pcluster createami --region $Region --ami-id $your_base_ami \
  --instance $arm_instance_type --os $selected_OS --config $your_config
```
For pcluster3:
```
pcluster build-image --region $Region--image-id $your_image_id \
  —image-configuration your_image_config.yaml
```

**Affected Versions**
This issue affects ParallelCluster from 2.10.1 to 3.0.0 when using `createami/build-image` with ARM architecture base AMI.

**Workaround**
You can find the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/Custom-AMI-creation-(pcluster-createami-or-build-image)-fails-with-ARM-architecture).

**Comment by enrico-usai** [comment]
Fixed as part of 2.11.3: https://github.com/aws/aws-parallelcluster/releases/tag/v2.11.3
