### ISSUE TITLE
Patching nodewatcher for more aggressive shutdown

### ISSUE THREAD

**Issue by rmilne** [aws/aws-parallelcluster#336]
It's been acknowledged that cfncluster's  nodewatcher design was intended for per-hour billing of ec2 and spot instances.  

> Since that time, EC2 has switched to per-second billing, which changes the equation slightly. However, with CfnCluster's current poor scaling up performance, the team has decided not to change the scale down behavior until we can fix the scale up behavior has well.

From #321 

What would be good way to configure a more aggressive nodewatcher?    I have a very predictable jobs and would like to shut down the computer node right after they are finished instead of waiting for 95% of the hour to be finished.  I would likely remove this bit of code from the main() loop:

```
if hour_percentile < 95:
            continue
```

And perhaps have a minimum uptime of 10 minutes to let the job start properly.  I'm considering monkey patching nodewatcher.py with the post script option, but that seems excessively dirty.  Are there better interim solutions?

Could I call something in the job script at the end to signal a shutdown for the node?
 - I suppose I could write some python that imports nodewatcher and runs the selfTerminate().

-russ

PS:  Sorry for the rubber ducky debugging here.

**Comment by andrew80k** [comment]
I'm in a situation where this would  be very useful to me.

**Comment by sean-smith** [comment]
See https://github.com/awslabs/cfncluster-node/pull/36
