### ISSUE TITLE
ParallelCluster cloudformation deployment fails with a timeout

### ISSUE THREAD

**Issue by hsimran13** [aws/aws-parallelcluster#3373]
Hello,

I am trying to deploy ParallelCluster and the cloudformation template fails with the following error:

WaitCondition timed out. Received 0 conditions when expecting 1
The following resource(s) failed to create: [HeadNodeWaitCondition20211021154453].

It does work when I scale the compute resources down to 0.  I also switched from spot to ondemand instance type thinking it might be an issue with getting spot resources but that did not help and it fails with the same error message.  In the chef-client.log file I see these messsages:

[2021-10-21T16:27:43+00:00] INFO: Waiting for static fleet capacity provisioning
[2021-10-21T16:27:58+00:00] INFO: Waiting for static fleet capacity provisioning
[2021-10-21T16:28:13+00:00] INFO: Waiting for static fleet capacity provisioning
[2021-10-21T16:28:28+00:00] INFO: Waiting for static fleet capacity provisioning
[2021-10-21T16:28:43+00:00] INFO: Waiting for static fleet capacity provisioning

I am using v3.0 for parallel cluster:

$ pcluster version
{
  "version": "3.0.0"
}

Here is my cluster config:
$ cat cluster-config.yaml| grep -v '#'
Region: us-west-2
Image:
  Os: ubuntu2004
  CustomAmi: ami-xxx
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-xxx
  DisableSimultaneousMultithreading: false
  Ssh:
    KeyName: testkeypair
    AllowedIps: 10.0.0.0/8
  LocalStorage:
    RootVolume:
      Size: 50
      Encrypted: true
      VolumeType: gp2
      DeleteOnTermination: true
    EphemeralVolume:
      MountDir: /test
  Dcv:
    Enabled: true
    Port: 8443
    AllowedIps: 10.0.0.0/8
  CustomActions:
    OnNodeConfigured:
      Script: s3://xxx/master-onnodeconfig.sh
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::xxxx:policy/ParallelCluster-S3KMS-script-policy
  Imds:
    Secured: True
  Image:
    CustomAmi: ami-xxxx
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    Dns:
      DisableManagedDns: false
  SlurmQueues:
    - Name: queue1
      CapacityType: ONDEMAND
      Networking:
        SubnetIds:
          - subnet-xxxx
        AssignPublicIp: false
      ComputeResources:
        - Name: compute-resource-1
          InstanceType: c5.xlarge
          MinCount: 1
          MaxCount: 5
      CustomActions:
        OnNodeConfigured:
          Script: s3://xxxx/compute-onnodeconfig.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::xxxx:policy/ParallelCluster-S3KMS-script-policy
      Image:
        CustomAmi: ami-xxxx
SharedStorage:
  - MountDir: /home
    Name: pcluster-home
    StorageType: Efs
    EfsSettings:
      ProvisionedThroughput: 1024
      Encrypted: true
      KmsKeyId: xxxx
Monitoring:
  Logs:
    CloudWatch:
      DeletionPolicy: Retain
  Dashboards:
    CloudWatch:
AdditionalPackages:
  IntelSoftware:
    IntelHpcPlatform: false
Tags:
  - Key: Name
    Value: Parallelcluster-sim

Any help would be greatly appreciated.

Thanks,
-Simran

**Comment by yuleiwan** [comment]
Hi @hsimran13,

The HeadNodeWaitCondition timeout is due to compute node failed to launch during bootstrapping. The potential error cloud be post install script execution failure or something else. Could you check /var/log/cloud-init-output.log on compute node? To retrieve logs you can follow the instruction in [troubleshooting page](https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3.html#troubleshooting-v3-scaling-issues).

Thanks,
Yulei

**Comment by jsmedmar** [comment]
In case people land here. I had a similar error and was due to the size of the volume. Fixed with increasing the root volume size:

```yaml
HeadNode:
  LocalStorage:
    RootVolume:
      Size: 70

Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: spot
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 70
```
