### ISSUE TITLE
Feature request: put compute node under scale down protection when there are jobs running

### ISSUE THREAD

**Issue by awacs** [aws/aws-parallelcluster#338]
To prevent autoscaling accidentally scaling down these nodes

**Comment by bwbarrett** [comment]
Do you have examples of this actually happening?  There's a (small) race today between when a node decides it can scale down and when it tells the batch scheduler that it is going to scale down, but in general, scale down is driven by the compute nodes based on whether they have jobs running.  So scale down protection wouldn't actually change any behaviors in the system, unless there's a bug we should fix...

**Comment by bwbarrett** [comment]
CfnCluster does not use CPU or network for scale up / scale down decisions.  It *only* uses the state of the job scheduler in determining node status.  Which scheduler are you using and did you have active jobs in the scheduler on those nodes when scale-down occurred?

**Comment by awacs** [comment]
Yes, I had multiple jobs running on the compute node when it scaled down, leaving the jobs on "auo" state. I was under the impression that scale up and scale down was independent of the cfncluster infrastructure, with scale up happening via a pending job alarm on cloudwatch and scale down happening via a similar cloudwatch that monitors node usage/idleness.

**Comment by ashuc** [comment]
I'm having the same issue as @awacs, using SGE. The way I fixed this was manually enabling instance protection for my CfnCluster Auto Scaling group:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-termination.html#instance-protection-group

Is there a way to enable this automatically using the CfnCluster config file when the cluster is created?

**Comment by enrico-usai** [comment]
The scaling down logic has been strongly refactored since CfnCluster 1.6.0.
In the nodewatcher code [we have a check](https://github.com/aws/aws-parallelcluster-node/blob/v2.2.1/nodewatcher/nodewatcher.py#L204) to verify if there are running jobs on the node and avoid to terminate it.

This feature enhancement is no longer required.
