### ISSUE TITLE
Using Parallelcluster in cluster name does not seem to work

### ISSUE THREAD

**Issue by hsimran13** [aws/aws-parallelcluster#3409]
Hello,

We are using pcluster v3.0:
```
$ pcluster version
{
  "version": "3.0.0"
}
```

Our cluster deployment fails with the following error message:
```
The following resource(s) failed to create: [HeadNodeWaitCondition20211028001921].
WaitCondition timed out. Received 0 conditions when expecting 1
```

When I looked at the logs, I see an issue with it finding the correct launch template:
```
 "eventTime": "2021-10-28T16:21:18Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "RunInstances",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "x.x.x.x",
    "userAgent": "Boto3/1.18.36 Python/3.7.10 Linux/5.11.0-1016-aws Botocore/1.21.36",
    "errorCode": "Client.InvalidLaunchTemplateName.NotFound",
    **"errorMessage": "The specified launch template, with template name xxx-queue1-c5.xlarge, does not exist.",**
    "requestParameters": {
        "instancesSet": {
            "items": [
                {
                    "minCount": 1,
                    "maxCount": 1
                }
            ]
        },
        "blockDeviceMappin
```

The launch template is actually called:
```
"LaunchTemplateName": "parallelcluster-xxx-queue1-c5.xlarge"
```

This is built using the cluster name we provided during our deployment:
```
pcluster create-cluster --cluster-name parallelcluster-xxx --cluster-configuration cluster-config-RSCimage-EKSsubnet.yaml --rollback-on-failure false
```

However, when I using the same cluster-config-RSCimage-EKSsubnet.yaml config file and change the cluster name by removing the parallelcluster bit and just use the remaining name it works just fine.  This tells me that somewhere in the code it does not allow or like the use of the name parallelcluster in the cluster name.  Reporting this as a bug.  Please let me know if I can provide any further information.

Thanks,
-Simran

**Comment by hanwen-pcluste** [comment]
ParallelCluster 3.0.2 has released, including the fix.
[Release Note](∫)
