### ISSUE TITLE
CfnCluster on Windows client hangs when deleting cluster

### ISSUE THREAD

**Issue by hellmersjl3ds** [aws/aws-parallelcluster#346]
When I delete a Cluster in Windows it hangs on the step

Deleting: pp-grid02
`Status: MasterEIP - DELETE_COMPLETE`

I'm not seeing anything running when I go into the CloudFormation in the AWS console, so I think it is finishing correctly.

**Comment by jocherry** [comment]
Can I ask what version of cfncluster you are using? We used to have an issue with delete in an older version and want to confirm it is not the same issue.

Otherwise I will label this a bug to look into to.

**Comment by hellmersjl3ds** [comment]
cfncluster version command reports 1.4.2.

**Comment by bwbarrett** [comment]
Thanks for the update; we don't test on Windows, so it's possible we did something platform non-portable.  It will take a couple of days to do some digging.

**Comment by bwbarrett** [comment]
@hellmersjl3ds is this repeatable?  I've run a couple of cycles of creating and deleting clusters with Python 3.6.5 on Windows 10 and don't see a hang during the delete phase.  The delete code is pretty straight-forward; it's basically a loop of sleep and getting the CloudFormation stack status.  If the stack successfully deleted, I would have expected at least an error was thrown on the next call to get the stack status.

**Comment by hellmersjl3ds** [comment]
It doesn't happen consistently for me.  A slight wrinkle on this is that I'm using the Anaconda 3 command prompt.  This command sets up the Anaconda environment.  Perhaps it has something to do with that.

**Comment by sean-smith** [comment]
Is this still an issue?
