### ISSUE TITLE
Ability to select FSX's Lustre version (2.10 vs 2.12)?

### ISSUE THREAD

**Issue by briandobbins** [aws/aws-parallelcluster#3461]
Hi all,

  Not an issue, just a question - it seems that FSX, when deployed via parallelcluster, defaults to Lustre 2.10, presumably because the API (CreateFileSystem) has a 'FileSystemTypeVersion' key which defaults to 2.10.  However, setting up FSX manually in the web console, it recommends 2.12 for all new deployments.  

  Is there an easy way to get 2.12 via parallelcluster?  I scanned through the FSX documentation in parallelcluster, but didn't see an option for it.  This isn't urgent; I'm just trying to solve an odd, infrequent data issue by ruling things out.

  Thanks,
  - Brian

**Comment by tilne** [comment]
Hey Brian,

ParallelCluster creates FSx file systems on behalf of customers through CloudFormation. This means we're limited to the configuration that can be done via the corresponding resource. Looking through the [documentation for that resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html#cfn-fsx-filesystem-lustreconfiguration) I don't see anything that would let us specify that version, but I'll look more into this.

> Is there an easy way to get 2.12 via parallelcluster?

One thing you might try is creating an FSx for Lustre file system and then specifying this existing file system in the cluster configuration file ([LTS](https://docs.aws.amazon.com/parallelcluster/latest/ug/fsx-section.html#fsx-fs-id), [3.0.X](https://docs.aws.amazon.com/parallelcluster/latest/ug/SharedStorage-v3.html#yaml-SharedStorage-FsxLustreSettings-FileSystemId)). That said, the default ParallelCluster AMIs have a 2.10 version of the Lustre client installed. I believe if you wanted to go this route you would want to install the corresponding client as well.

**Comment by tilne** [comment]
Marking this as an enhancement for now, since we'd need to expose configuration for it in the event we could specify a Lustre version via CFN.

**Comment by briandobbins** [comment]
Thanks for the suggestions; I think the fact that the instances are running the older client might require I make a custom AMI to test this, and it isn't urgent since we've found a way to work around this at the moment (disabling parallel I/O, which at this scale is not a big deal).  That said, when I do get around to this, I'll update the ticket with more information, especially if it solves it.    It seems this is likely due to some combination of PNetCDF, MPI-IO and/or Lustre.

**Comment by enrico-usai** [comment]
We're working on the upgrade to 2.12 version: https://github.com/aws/aws-parallelcluster/pull/3977

**Comment by lukeseawalker** [comment]
Lustre server version 2.12 was released with ParallelCluster 3.2.0, see release notes https://github.com/aws/aws-parallelcluster/releases/tag/v3.2.0
