### ISSUE TITLE
Use a newer version of UGE or PBS Pro

### ISSUE THREAD

**Issue by hellmersjl3ds** [aws/aws-parallelcluster#347]
I'd like to use a newer version of UGE, or use PBS Pro.

Any recommendations on how to do this using a pre/post install script?  Or modification to Chef scripts/recipes?

**Comment by bwbarrett** [comment]
We don't currently provide a way to bring your own scheduler with CfnCluster.  There are a couple of packages (nodewatcher, sqswatcher, publish_pending, as a minimum).

We have previously discussed adding the ability to bring your own scheduler.  It looks like we don't have a GitHub issue tracking the bring your own scheduler work, so I'm going to mark this issue as an enhancement and leave it open.  We obviously don't have a timeline we can share at this time.

**Comment by hellmersjl3ds** [comment]
I'm willing to work on it if you'd like.

**Comment by enrico-usai** [comment]
Closing this FE, since SGE and PBS are no longer available in ParallelCluster.
