### ISSUE TITLE
Reduce the amount of typing in the ParallelCluster 3 CLI?

### ISSUE THREAD

**Issue by mark-mackey-cresset** [aws/aws-parallelcluster#3495]
Starting a new cluster:

Parallelcluster 2:

pcluster create -c /path/to/config clustername

Parallelcluster 3:

pcluster create-cluster --cluster-configuration /path/to/config --cluster-name clustername

Can we have some short option letters back, please? The new CLI is significantly more verbose and unwieldy to use.

**Comment by chenwany** [comment]
Hi! Thanks's for reaching us! 

We would like to mark this as a feature request and take it into consideration.

Thank you!

**Comment by enrico-usai** [comment]
We addressed this as part of 3.1.1 release.
https://github.com/aws/aws-parallelcluster/releases
