### ISSUE TITLE
Q: Ability to auto delete Nat Gateway/VPC when deleting cluster tied to it?

### ISSUE THREAD

**Issue by briandobbins** [aws/aws-parallelcluster#3499]
Hi all,

  I realize that NAT Gateways are used by parallelcluster, but not exclusively so, but I was wondering if there's a way to 'tag' them upon creation by parallelcluster so that they get deleted when an ephemeral cluster is deleted?  Right now, a common workflow is:

 1) Identify a region & AZ with the node types I want
 2) Do a 'pcluster configure' to set up a VPC in that AZ
 3) Create a cluster
 4) Do some work
 5) Delete the cluster

 ... But that doesn't delete the VPC, obviously.  It'd be nice if there was a simple way to automate that, perhaps by 'tagging' the VPC / Gateway that gets created during 'pcluster create', so it can be tied to a cluster and removed when that cluster is gone.  The cost, obviously, is relatively minor ($0.045 / hr), but for people who may spin up ephemeral clusters for a few hours every few months, it's an additional hassle.

  Any thoughts on how best to do this?  I think we can do it ourselves, but I gotta imagine the functionality would be useful to others, too.

  Thanks,
  - Brian

**Comment by chenwany** [comment]
Hi Brain, thanks for reaching us!

You mentioned you used `pcluster configure` to set up a VPC in that AZ. There's a step asking whether to use existing VPC or creating a new VPC. If customers choose to create a new VPC, the output of the subnet ids will be put in the cluster configuration to used for creating the clusters.

The creation of VPC and creation of cluster are done by two steps. VPC is not created during cluster creation, and it can also be reused by other clusters so they don't need to be recreated again.

To delete the VPC, you don't need to manually delete the NAT Gateway. There's a cloudformation stack for the VPC stack with name starts with "parallelclusternetworking". By deleting the stacks, all resources used by the VPC will be cleaned up.

Thank you!

**Comment by xuanus** [comment]
Even delete the cloudformation stack with name starts with "parallelclusternetworking", not all resources used by the VPC will be cleaned up. The VPC is still active.
