### ISSUE TITLE
Encoded authorization failure message truncated

### ISSUE THREAD

**Issue by vladaeloaiei** [aws/aws-parallelcluster#3505]
When starting a cluster using `EmrCreateCluster` I encounter the following error: `Service role EmrServiceRole-X has insufficient EC2 permissions` so I tried to debug this using CloudTrail.

The problematic event is `CreateFleet`, but unfortunately the CloudTrail truncated the error message and I can not further debug my issue.
e.g.:

```JSON
"eventSource": "ec2.amazonaws.com",
    "eventName": "CreateFleet",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "elasticmapreduce.amazonaws.com",
    "userAgent": "elasticmapreduce.amazonaws.com",
    "errorCode": "Client.UnauthorizedOperation",
    "errorMessage": "You are not authorized to perform this operation. Encoded authorization failure message: F02XfWhIkobgoHSYY8QAcqgb8Gwd-FYjBvgvF5NsDrmJKiWepv8bSsYSsey-GVbdSzLlim8UF4Ndq1pmIw5VJzM9nyNMJyBcmiaWljpTNh_A3HjUxz-diNDmvPYOC-tDOBBvbuooD5bekbumvFbW1h24d--Zh17TZoy-basSWhCqqSRqIt1h66F1ny0Z2lBHSp0rExb035eTgHXWG2gHuLaWM0Lt2WXuyTxiOYvXG86XatRJY-734oNbUA5oO_fdBFGBM3NnfWFZ3EU5YPUWWKzXin5CDXJQoSCn3_lldnkXlyTWB-OMd3yChX5t4lcnQGEikTPb2vq8RrKSAHOTDdGcWS_sAXp30lHjMAryA--OTSQ5wq5IhvNb89kvoLGP8GgKdz857O8yOJ7TE1e1yrZVeOYs_bZwyU_BsYIayrFTpXsaxO1yJYSQKBGGVgwxfLXEOIsKuGlZFR5ABGfRdN2SL6G53-uBjN-OrECfUy-8sE8n2vSzVHcodt6cVOBouNvqc9ws-6c3VaWswLa8pMS8I11Z214v_ErJdUMrk_92o1uFFe-_WMuLa32nC1pbSCT-YtDY3jejU1lOgAB7MZuQ_SiB6JV8AwG9kuGE_cQCfnkl0PXR2s6kli1WjehbpDXrpxNGnuonhHOxseaEX1RuUi3xIZhlOX1zk9fZsdn-erhSSFM0O3PVFM2LpEfEoCck9FMSFLvPYdqzReuZY0xX8Ln-DC-OQmOq8iOYH7EuUGkSrVIzqzgG8xVJ77kjKv_m9acO79PoTu_Kebq98bZiidOlTLy-7eVLkB9nLKf8HRzK_g4uCr7biNvo4v7pbBHL35gqjWCMi_kx5B3Q7PtIKIEgUhgBakZYQDlUuN3jAC0gp6RMUy3r52xcXaJgF6YlyDKZyweb9H7G0IaTJmK0P2aiAHdZjav-..."
```

It is the exact same issue as [this](https://github.com/aws/aws-parallelcluster/issues/372#issuecomment-713308432) one.

**Comment by chenwany** [comment]
Hi! Could you share with us the way using `EmrCreateCluster` to create a cluster? where and when the error message appear? Thank you!

**Comment by demartinofra** [comment]
If I understand correctly you are trying to create an EMR Cluster not a cluster with [AWS ParallelCluster](https://docs.aws.amazon.com/parallelcluster/). Please refer to the available support options offered with EMR service.

**Comment by vladaeloaiei** [comment]
Hi,

Came back with an update. My issue was related to lack of permissions on `EmrServiceRole-X`.

      If I understand correctly you are trying to create an EMR Cluster not a cluster with AWS ParallelCluster.

Indeed. I tried to create an EMR cluster using `EmrCreateCluster` step from `StepFunctions`.

Going back to the original issue:
According to CloudTrail's [documentation](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html), the `errorMessage` has a maximum size of 1 KB; content exceeding that limit is truncated. Which means that this works as designed.

Although this is working as designed it is not the best experience to get a truncated error message when you are debugging your code.

Anyway, you can close this issue.

Thanks!

**Comment by demartinofra** [comment]
I share your concerns on the issue. Unfortunately AWS ParallelCluster doesn't have anything to do with AWS EMR and there isn't much we can do to help you with this.
