### ISSUE TITLE
Upgrading an existing 3.0 cluster

### ISSUE THREAD

**Issue by hsimran13** [aws/aws-parallelcluster#3514]
Hello,

Is there a way to upgrade an existing 3.0 deployment of parallelcluster to the latest 3.0.2 version?  Or would I need to delete the existing cluster and redeploy using the new version?  Also, do we know when the latest slurm 21.08.4 will be available in pcluster?

Thanks,
-Simran

**Comment by chenwany** [comment]
Hi, thank you for reaching us!

To upgrade to a newer version, you will need to redeploy the new version. To make softwares installed in the headnode reusable and reproducible, it is recommended to install them in external volumes such as EBS, EFS, EFS so they can be attached to new cluster. It is also recommenced to use post-install script for installation to make it reproducible.

We are working on upgrade to the newer version of slurm.

Thanks!
