### ISSUE TITLE
Slurm Continous retry 

### ISSUE THREAD

**Issue by kpenn88** [aws/aws-parallelcluster#3521]
I am submitting a job via slurm and I get this funny error and the job seems to keep restarting over and over, any help would be great:
```
27db5741996b: Pull complete
Digest: sha256:8d66b487edee745e37a1c4bbc62101338ff9c2f2df0b3da0aa56ce8a63334f18
Status: Downloaded newer image for ncbi/pgap:2021-07-01.build5508
PGAP version 2021-07-01.build5508 is up to date.
Output will be placed in: /home/ec2-user/Staphylococcus.Epidermidis.dir/t43832403.PGAP/t43832403.7
TAXCHECK completed successfully.
PGAP failed, docker exited with rc = 125
Unable to find error in log file.
slurmstepd: error: If munged is up, restart with --num-threads=10
slurmstepd: error: Munge encode failed: Failed to access "/var/run/munge/munge.socket.2": No such file or directory


```
Here is the sbatch script:
```
#!/usr/bin/bash
#SBATCH --job-name=t43832403
#SBATCH --output=%j.out
#SBATCH --ntasks=1

python3 ~/bin/PGAP.dir/V2.dir/pgap.py -r -o t43832403 t43832403.input.yaml   --taxcheck 

```

######squeue
 JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
               675   compute t4383240 ec2-user  R       1:50      1 compute-dy-m5xlarge-11

######scontrol show job

JobId=675 JobName=t43832403
   UserId=ec2-user(1000) GroupId=ec2-user(1000) MCS_label=N/A
   Priority=4294901086 Nice=0 Account=(null) QOS=(null)
   JobState=CONFIGURING Reason=None Dependency=(null)
   Requeue=1 Restarts=11 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:01:33 TimeLimit=UNLIMITED TimeMin=N/A
   SubmitTime=2021-11-22T15:04:30 EligibleTime=2021-11-22T15:06:31
   AccrueTime=2021-11-22T15:06:31
   StartTime=2021-11-22T15:06:38 EndTime=Unknown Deadline=N/A
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2021-11-22T15:06:38
   Partition=compute AllocNode:Sid=ip-172-21-2-214:3336
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=compute-dy-m5xlarge-11
   BatchHost=compute-dy-m5xlarge-11
   NumNodes=1 NumCPUs=1 NumTasks=1 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=1,node=1,billing=1
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=1 MinMemoryNode=0 MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/home/ec2-user/Staphylococcus.Epidermidis.dir/t43832403.PGAP/t43832403.PGAP.run.sh
   WorkDir=/home/ec2-user/Staphylococcus.Epidermidis.dir/t43832403.PGAP
   StdErr=/home/ec2-user/Staphylococcus.Epidermidis.dir/t43832403.PGAP/675.out
   StdIn=/dev/null
   StdOut=/home/ec2-user/Staphylococcus.Epidermidis.dir/t43832403.PGAP/675.out
   Power=
   NtasksPerTRES:0

**Comment by demartinofra** [comment]
How are you submitting this job to Slurm? Also from the logs it looks like you are using docker as part of your job, which makes me wondering if the submission workflow is compatible with Slurm.
