### ISSUE TITLE
AWS Parallel Cluster as Service Catalog Product?

### ISSUE THREAD

**Issue by rsignell-usgs** [aws/aws-parallelcluster#3527]
We would like to enable AWS Parallel Cluster for USGS researchers, but folks in general don't have the permissions required on our AWS account, so we are looking to create a Service Catalog Product.    

Has anyone done this?   

 I realize we would have to customize the CloudFormation stuff, but it would be useful to have a starting point to work with.

**Comment by enrico-usai** [comment]
Hi @rsignell-usgs sorry for the delay.

I'm not sure if it is possible to add ParallelCluster in a Service Catalog. 
AWS ParallelCluster is not a Service, it is an Open Source product that uses [different AWS Services](https://docs.aws.amazon.com/parallelcluster/latest/ug/aws-services-v3.html) to build an HPC cluster, so I'm not sure how it can fit into the Service Product definition.

To add ParallelCluster into a Portfolio you probably have to add all the services used by ParallelCluster (e.g. EC2 instances, Route53, DynamoDB, etc) into your Product definition.

I can share some resources related to Service Catalog customization:
* https://docs.aws.amazon.com/servicecatalog/latest/adminguide/getstarted-template.html
* https://aws.amazon.com/blogs/mt/use-aws-service-catalog-to-build-a-custom-catalog-of-products-from-aws-marketplace/
* https://www.youtube.com/watch?v=lVfXkWHAtR8

An alternative is to try to send a message to the Service Catalog team through the re:Post forum: https://repost.aws/tags/TAG08wb2QBSaGcgC5rDmZgyA/aws-service-catalog

Enrico

**Comment by rsignell-usgs** [comment]
Thanks @enrico-usai.  I think we are trying to use the service catalog approach to simply gather some of the key parameters for the cluster config, then use elevated permissions not available to the user to launch pcluster.  

 Is that about right @scongdon?

**Comment by enrico-usai** [comment]
Interesting solution, do you have something to share with the community? e.g. the CloudFormation Product definition?
