### ISSUE TITLE
Possibility of login node for slurm

### ISSUE THREAD

**Issue by hsimran13** [aws/aws-parallelcluster#3564]
Hello,

I am using parallel cluster 3.0 and would like to have my users log into a login node for job submission instead of the master node directly due to misuse of resources on the slurm master that could be impactful to the cluster.  Is there a way for parallelcluster to support such a setup?  If not, is this a feature that can be added?  

Thanks,
-Simran

**Comment by hanwen-pcluste** [comment]
Hello Simran,

My apologies for the late reply. ParallelCluster does not support a login node. I will mark this as a feature request and discuss it with our team.

Thank you,
Hanwen

**Comment by rvencu** [comment]
I could do it actually in the form of an interactive session in slurm
https://hpc-uit.readthedocs.io/en/latest/jobs/interactive.html

**Comment by cvmeq** [comment]
Commenting to support the request. We have recently deployed a login node along with ParallelCluster and even though it was possible, integrating the resources deployed by the CDK stacks with those deployed by ParallelCluster required a bit of elbow grease. A login node built-in ParallelCluster would be a great addition.

Or a ParallelCluster L3 construct in CDK :-)

**Comment by dreambeyondorange** [comment]
Login nodes are now supported with 3.7.0!

https://github.com/aws/aws-parallelcluster/releases/tag/v3.7.0
