### ISSUE TITLE
Unable to build AMI for CentOS 7 and Ubuntu 18, using version 3.0.1/2.11.3 and older

### ISSUE THREAD

**Issue by lukeseawalker** [aws/aws-parallelcluster#3584]
### Bug description
Custom AMI creation with command `pcluster build-image` (3.x) or `pcluster createami` (2.x) are failing with the following error:

```
$ curl --retry 3 -L -o /tmp/aws-cfn-bootstrap-latest.tar.gz https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
$ pip install /tmp/aws-cfn-bootstrap-latest.tar.gz

File "/tmp/pip-build-im3UcQ/pystache/setup.py", line 183
command = f"pandoc -f markdown-smart --write=rst --output={rst_temp_path} {md_path}"
SyntaxError: invalid syntax
```

### Causes of the problem
A dependency of the `aws-cfn-bootstrap-latest.tar.gz` helper package removed the support for Python2.
The dependency is `pystache` version 0.6.0, see changelog [here](https://github.com/sarnold/pystache/releases/tag/0.6.0)

### How to reproduce the bug
Create custom AMI with command `pcluster  build-image` or `pcluster createami` using centos7 or ubuntu1804 as base os

### Workarounds
Reported in the [wiki](https://github.com/aws/aws-parallelcluster/wiki/(3.0.2,-2.11.3-and-earlier)-Custom-AMI-creation-(pcluster-build-image-or-createami)-fails-for-centos7-and-ubuntu1804)

**Comment by lukeseawalker** [comment]
This has been fixed in 2.11.4, see [changelog](https://github.com/aws/aws-parallelcluster/releases/tag/v2.11.4). Removing 2.x label.

**Comment by enrico-usai** [comment]
Fix for 3.x merged: https://github.com/aws/aws-parallelcluster/pull/3582

**Comment by enrico-usai** [comment]
ParallelCluster 3.1.1, including this fix, has been released: https://github.com/aws/aws-parallelcluster/releases/tag/v3.1.1
