### ISSUE TITLE
Encryption in Transit

### ISSUE THREAD

**Issue by c200chromebook** [aws/aws-parallelcluster#3603]
I know it's a bit ridiculous for MPI, but how would I actually enable encryption in transit between nodes? The docs 
 mention this as being possible but don't explain how to do it.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/data-protection.html#encryption-transit

**Comment by chenwany** [comment]
Hi!
For transit between nodes, I think they are automatically encrypted for the instance types as mentioned in the link your shared: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/data-protection.html#encryption-transit
Running the command show if encryption in transit is supported:
```
aws ec2 describe-instance-types \
--filters Name=network-info.encryption-in-transit-supported,Values=true \ 
--query "InstanceTypes[*].[InstanceType]" --output text
```
ParallelCluster doesn't modify the default encryption in transit between instances.

Thanks
