### ISSUE TITLE
Does each Slurm task have a 4 GB limit?

### ISSUE THREAD

**Issue by calebwin** [aws/aws-parallelcluster#3612]
This article [1] says that some clusters might have a 4 GB limit per task and that you need to specify `--mem=` or `--mem-per-cpu=` to get around that limit. Unfortunately, https://github.com/aws/aws-parallelcluster/issues/1517 seems to indicate that `--mem=` or `--mem-per-cpu=` are not supported by Slurm ParallelCluster instances. So is there a 4 GB limit per task that I should be worried about?

[1] https://researchcomputing.princeton.edu/support/knowledge-base/memory

**Comment by chenwany** [comment]
Hi Caleb!

From my understanding, I think the out-of-memory issue for more than 4 GB per task may still be a limit, although I haven't seen this case before. As you mentioned in the github issue, `--mem=` is not supported by Slurm ParallelCluster instances, number of nodes are launched based on cpus needed. If you meet the issue with 4 GB limit memory issue and need to specify `-men` when submitting job, here's a post you may interested in: https://github.com/aws/aws-parallelcluster/issues/2198, it talks about how to specify memory when running jobs

Thank you!
