### ISSUE TITLE
Add support for FSx for ONTAP

### ISSUE THREAD

**Issue by triggan** [aws/aws-parallelcluster#3616]
Currently have needs for leveraging FSx for ONTAP storage with Parallel Cluster to ease data movement from on-prem into AWS or across regions (using built in replication of ONTAP).

**Comment by chenwany** [comment]
Hi Taylor, thank you for suggesting it!
I forward the request to our PM @nstornetta and we will get back to you later.

**Comment by enrico-usai** [comment]
Hi @triggan, we're working on adding support for existing FSx for ONTAP file systems: https://github.com/aws/aws-parallelcluster/pull/4048

**Comment by lukeseawalker** [comment]
Hello @triggan,
ParallelCluster 3.2.0 now supports existing FSx for ONTAP and FSx for OpenZFS file systems.
See changelog https://github.com/aws/aws-parallelcluster/releases/tag/v3.2.0
