### ISSUE TITLE
Slurm stopped by srun error :Bus error, how can I modify the slurm.conf ? 

### ISSUE THREAD

**Issue by Iterator-Taken** [aws/aws-parallelcluster#3629]
**Required Info:**
 - AWS ParallelCluster version : 2.10.0
 - Cluster name:Dev

**Bug description and how to reproduce:**
I run the cluster by slurm on Lustre file system.The bug "srun errror:bus error"  happened three times in four months. Fortunately ,I found a simular question on Slurm official site (https://slurm.schedmd.com/faq.html#cray_sigbus) . The solution is quite simple, i.e., add a  "LaunchParameters=lustre_no_flush" in slurm.conf. Now the question is how can I modify slurm.conf.
I have found ther slurm.conf in "/opt/slurm/etc/slurm.conf",then I tried to modify the .conf file by parallelcluster  **post-install** and **pre-install** script ,but it doesn't work.  So how should I do?

**Comment by enrico-usai** [comment]
Hi @Iterator-Taken,
`/opt/slurm/etc/slurm.conf` is the right file to customize and post-install the right hook to use. 

Can you clarify what you mean with "it doesn't work"? Do you mean you're not able to modify the configuration file or that the `LaunchParameters=lustre_no_flush` doesn't work as expected?

Can you see the changes applied in the `slurm.conf` file?
Did you restart `slurmctld` daemon after applying the changes? 
Can you share your configuration file and post-install script content?

Thanks

**Comment by Iterator-Taken** [comment]
Woo... I'm sorry , it's worked now.  I was failed to restart `slurmctld`  yesterday, because I have changed the hostname of master node before,  then restart slurm failed.... Now I fixes it and the slurm restart successfully.

Now I wrote the command in `post_install` script as follows :
```
#!/bin/bash
API_PLATFORM=api_poseidon_release_a

#module load anaconda/3-python3.7.3 
source /software/data/${API_PLATFORM}/env/env.sh
# cd /software/data/${API_PLATFORM}/pyslurm_build
#python setup.py build --slurm=/opt/slurm
#python setup.py install

# slurm
echo "post_install test slurm now"
sudo systemctl status slurmctld && echo
sudo ls /opt/slurm/
sudo ls /opt/slurm/etc
sudo cat /opt/slurm/etc/slurm.conf
sudo echo "LaunchParameters=lustre_no_flush" >> /opt/slurm/etc/slurm.conf
sudo cat /opt/slurm/etc/slurm.conf

sudo mkdir /etc/supervisord.d
sudo cp /etc/parallelcluster/parallelcluster_supervisord.conf /etc/supervisord.d
sudo cp /software/data/${API_PLATFORM}/supervisor/supervisord.d/* /etc/supervisord.d
sudo cp /software/data/${API_PLATFORM}/supervisor/supervisord.conf /etc/
sudo service supervisord start

# Install nginx
# sudo yum -y install nginx
sudo cp -f /software/data/${API_PLATFORM}/conf/nginx_${ENV}.conf /etc/nginx/nginx.conf
sudo mkdir /software/data/${API_PLATFORM}/logs/nginx
sudo chown nginx:nginx /software/data/${API_PLATFORM}/logs/nginx
sudo nginx
sudo nginx -s reload
```

While, I'm not sure if this command can fix the "Bus error" yet , it needs maybe several month to validate.
