### ISSUE TITLE
UpdateWaiterCustomResource fails with timeout error during update 

### ISSUE THREAD

**Issue by adamcowan** [aws/aws-parallelcluster#3646]
Hello, 

I am trying to update a running cluster but am running in to some sort of execution timed out error which causes the stack to rollback the changes. The only config changes is the max number of compute nodes (25 -> 150). Please see the attached sanitized [config](https://github.com/aws/aws-parallelcluster/files/7836249/config.txt) file. 

Under the CloudFormation stack details I see the event: 
- Embedded stack <stack> was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [UpdateWaiterCustomResource].

Under the MasterServerSubstack I see the following:
- The following resource(s) failed to update: [UpdateWaiterCustomResource].
- Received response status [FAILED] from custom resource. Message returned: Execution timed out 

The logstream for UpdateWaiter shows a timeout after 900 seconds: 

START RequestId: 5572518c-9910-4a95-b3d3-3d9dc1631135 Version: $LATEST
[INFO]	2022-01-09T21:25:23.097Z	5572518c-9910-4a95-b3d3-3d9dc1631135	Updated config version: dZyofz.8uzUzIE4zbD4HybDHePJwEHct
[INFO]	2022-01-09T21:25:23.455Z	5572518c-9910-4a95-b3d3-3d9dc1631135	Waiting for config version to be updated
... 
[INFO]	2022-01-09T21:39:54.827Z	5572518c-9910-4a95-b3d3-3d9dc1631135	Waiting for config version to be updated
[INFO]	2022-01-09T21:39:54.837Z	5572518c-9910-4a95-b3d3-3d9dc1631135	Current config version: 9lzjWMvFLOKZFxDSE2IMqNnnAgsi_Pxy
[ERROR]	2022-01-09T21:40:22.596Z	5572518c-9910-4a95-b3d3-3d9dc1631135	Execution is about to time out, sending failure message
[INFO]	2022-01-09T21:40:22.597Z	5572518c-9910-4a95-b3d3-3d9dc1631135	PhysicalResourceId present in event, Using that for response
[INFO]	2022-01-09T21:40:22.790Z	5572518c-9910-4a95-b3d3-3d9dc1631135	CloudFormation returned status code: OK
END RequestId: 5572518c-9910-4a95-b3d3-3d9dc1631135
REPORT RequestId: 5572518c-9910-4a95-b3d3-3d9dc1631135	Duration: 900100.59 ms	Billed Duration: 900000 ms	Memory Size: 128 MB	Max Memory Used: 29 MB	
2022-01-09T21:40:23.197Z 5572518c-9910-4a95-b3d3-3d9dc1631135 Task timed out after 900.10 seconds

I have not attempted to execute the update command with the '--norollback' option. 

**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 2.10.3
 - Cluster name: cluster
 - Arn of the cluster CloudFormation main stack: arn:aws:cloudformation:us-west-2:758433239158:stack/parallelcluster-cluster/4c644ba0-99af-11eb-b525-0ac403330061

Thank you in advance,
Adam

**Comment by hanwen-pcluste** [comment]
Hello Adam,

Sorry for the late reply.

When running `pcluster update` command, what are the changes displayed? Is it only the `max_count` change?

If there is no change other than the `max_count`, can you share with us the following logs to help us further investigate the issue?
* From Head node: `/var/log/cloud-init.log`, `/var/log/cfn-init.log`, and `/var/log/chef-client.log`
* From Compute node:  `/var/log/cloud-init-output.log`

You can follow [this guide](https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs) to retrieve logs.

Thank you,
Hanwen
