### ISSUE TITLE
Reducing configuring time?

### ISSUE THREAD

**Issue by c200chromebook** [aws/aws-parallelcluster#3654]
Hey, it seems to take us about 3 minutes for configuring. What's happening during this time, and is it possible to bring it down?

**Comment by demartinofra** [comment]
You can look at cloud-init and cloud-init-output log files to check what happens during the bootstrap logic. 
What version are you on and what os are you using?

**Comment by c200chromebook** [comment]
3.0.2 alinux2 using p3.2xlarge

**Comment by chenwany** [comment]
Hi, when configuring, we run [user_data](https://github.com/aws/aws-parallelcluster/blob/develop/cli/src/pcluster/resources/head_node/user_data.sh) in headnode and  [user_data.sh](https://github.com/aws/aws-parallelcluster/blob/develop/cli/src/pcluster/resources/compute_node/user_data.sh) in compute node. During configuring time, the instance mount volumes, configure softwares, run pre_install and post_install scripts... For details, you can check the timeline in cloud-init and cloud-init-output log files to see which process is taking long. 
Thanks
