### ISSUE TITLE
Compatibility with hpc6a.48xlarge

### ISSUE THREAD

**Issue by coderodyhpc** [aws/aws-parallelcluster#3656]
Hello,
This is a quick question, not a bug report. I was wondering which versions of aws-parallelcluster are compatible with the new hpc6a.48xlarge instances (and obviously EFA). 
Thanks.

**Comment by demartinofra** [comment]
We recommend you to use the latest 2.x (2.11.4) or 3.x (3.0.2) release. If you are interested in the compatibility of a specific older version please let me know and I can verify that for you

**Comment by coderodyhpc** [comment]
Hi @**demartinofra**, 
I'm running most stuff with 2.11.2 and waiting on the next version 3 release (not sure if I read that it was going to be 3.1.0 rather than 3.0.3) to begin upgrading to version 3. Hopefully this will happen within the next few days so that no extra verifications are necessary (what I'm trying to avoid is upgrading to 3.0.2 and realize the following day that there's a newer version).
Thanks.

**Comment by demartinofra** [comment]
2.11.2 should work just fine with hpc6a.48xlarge. 3.0.3 is being released to address the issue described in https://github.com/aws/aws-parallelcluster/issues/3659. 3.1.0 will also be released in January and will contain a series of new features (you can get a preview of them from the changelog)

**Comment by coderodyhpc** [comment]
Thanks!

**Comment by coderodyhpc** [comment]
Hello @**demartinofra**,
I'm reopening this thread but could open a new one if needed. You mentioned that 3.1.0 would be released in January, which it was, but there's no info about it in the Github site or the UG (I understand that updating it is time consuming). However, what I find a bit odd is that the parallelcluster team is working on 3.2.0 rather in 3.1.1. The kernels are pretty much the same (between 3.1.0 and 3.2.0) so I cannot figure out the differences between 3.0.3, 3.1.0, and 3.2.0. I need to pick one and run with it for the next few months (cannot upgrade every time there's a new release) so it's an important decision, and I'd like to have as much info as possible.
Thanks.

**Comment by enrico-usai** [comment]
Hi @coderodyhpc 

* 3.1.0 will be the next official release, it's expected to be released soon and you can see changes in the changelog from develop: https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.md.
* 3.2.0 is still in development and its release hasn't been scheduled yet. 

Therefore we suggest to use 3.1.0 as it becomes available.

**Comment by coderodyhpc** [comment]
Hi @**enrico-usai**,
Thanks, I'm going with 3.1.0 as I switched from 3.1.0.b1 to 3.1.0 a few days ago when it became available at the console (not sure what makes it an official release but that is probably a minor detail).

**Comment by enrico-usai** [comment]
> when it became available at the console

Are you talking about the new AMIs for 3.1.0 in the console? 
They have been released as pre-release steps but they cannot be used until the new CLI for 3.1.0 is available on PyPI.

**Comment by coderodyhpc** [comment]
Hi @**enrico-usai**, 
OK. I have tested the 3.1.0 AMI with single instances including hpc6a.48xlarge (with no problem at all) but launching a cluster is supposed to happen on Thursday (still have to complete a few more preliminary tasks). Is there going to be any change in the AMIs at all or is it simply a matter of updating PyPI?
Thanks.

**Comment by enrico-usai** [comment]
@coderodyhpc please don't rely on the already available AMIs.
A new version of updated AMIs will be released along with the 3.1.0 CLI.

**Comment by coderodyhpc** [comment]
Thanks.
