### ISSUE TITLE
pyxis

### ISSUE THREAD

**Issue by maziarraissi** [aws/aws-parallelcluster#3668]
How can I install nvidia pyxis on a cluster created by parallelcluster 3.0?

ParallelCluster installs slurm on /opt/slurm. So I added "CPPFLAGS = -I/opt/slurm/include" and "LDFLAGS = -L/opt/slurm/lib" to the pyxis Makefile. In the Makefile, I also modified "prefix ?= /user/local" to "prefix ?= /opt/slurm". Now, the command "sudo make install" seems to work. I also created a folder called "/etc/slurm-llnl/plugstack.conf.d" and then ran the following modified command: "sudo ln -s /opt/slurm/share/pyxis/pyxis.conf /etc/slurm-llnl/plugstack.conf.d/pyxis.conf". I also copied the file "/etc/chef/cookbooks/aws-parallelcluster/files/default/slurmd.service" to "/etc/systemd/system". This will let us run the following command without errors: "sudo systemctl restart slurmd"

However, when I type "srun --help | grep container" nothing shows. This means that the pyxis plugin is not installed.

What am I doing wrong?

**Comment by hanwen-pcluste** [comment]
Hello maziarraissi,

Unfortunately, we are not experienced about the [SPANK](https://slurm.schedmd.com/spank.html) plugin [pyxis](https://github.com/NVIDIA/pyxis). 

The process should be compiling the plugin with the proper Slurm linking, making the plugin available to Slurm and restating Slurm daemons both on head and compute nodes.
Setting Slurm debug logs and restarting the slurmd and slurmctld should give hints on whether Slurm is loading or not the plugin.

The required headers should be available under `/opt/slurm/include/slurm`.

If you can’t get unblocked, we will try to reproduce on our side.

Thank you,
Hanwen

**Comment by sean-smith** [comment]
We have a managed postinstall script that does this for you (Pyxis + Enroot) install FYI. 

See https://github.com/aws-samples/aws-parallelcluster-post-install-scripts/tree/main/pyxis
