### ISSUE TITLE
Question: Is there a configuration parameter to change the instance name

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#367]
Is there a way to change the names "Master" and "Compute" to something else from the script? Could you help with this?

Thanks
Santi

**Comment by lukeseawalker** [comment]
This is not currently possible through cfncluster. The names "Master" and "Compute" are set into the cloudformation template [here](https://github.com/awslabs/cfncluster/blob/13c44e7df42c6b452375f3e09072402c8f518f20/cloudformation/cfncluster.cfn.json#L2346) and [here](https://github.com/awslabs/cfncluster/blob/13c44e7df42c6b452375f3e09072402c8f518f20/cloudformation/cfncluster.cfn.json#L2867). Changing them requires changing the template.

**Comment by rmarable** [comment]
Determining the cluster membership of individual instances can get messy when multiple clusters are being run from a single AWS account.  Would you consider an optional configuration option that appends the cluster_name to "Master" or "Compute" like this:

Master-curvefitter 
Compute-curvefitter
Compute-curvefitter
Compute-curvefitter

**Comment by sean-smith** [comment]
We have this, there's a tag `ClusterName` which you can show in the EC2 console like so:

![image](https://user-images.githubusercontent.com/5545980/71199762-7d66c480-224b-11ea-904e-8a7aa4e9bc7b.png)

To set this up, go to EC2 > Instances > Settings (gear icon in upper right) > check `ClusterName`

![image](https://user-images.githubusercontent.com/5545980/71199837-a71feb80-224b-11ea-8928-53f02fea0506.png)

**Comment by rmarable** [comment]
Hi @sean-smith, 

Thanks, this is perfect.
