### ISSUE TITLE
(2.11.4) DCV Connection Through Web Browsers Does Not Work

### ISSUE THREAD

**Issue by hanwen-pcluste** [aws/aws-parallelcluster#3683]
With ParallelCluster 2.11.4, when running pcluster dcv connect <cluster-name>, the web page opened will be blank.

See [Wiki page](https://github.com/aws/aws-parallelcluster/wiki/DCV-Connection-Through-Web-Browsers-Does-Not-Work) for workarounds.

**Comment by enrico-usai** [comment]
[2.11.5](https://github.com/aws/aws-parallelcluster/releases/tag/v2.11.5) version is available on PyPI.
