### ISSUE TITLE
ReadMe links are wrong

### ISSUE THREAD

**Issue by xuanus** [aws/aws-parallelcluster#3700]
ReadMe links are pointing to the wrong pages

**Comment by chenwany** [comment]
Thanks for reporting the issue, can you share which ReadMe link is pointing to the wrong pages?

**Comment by lukeseawalker** [comment]
I suppose it was about the link to the forum, that is fixed by https://github.com/aws/aws-parallelcluster/pull/3731

**Comment by xuanus** [comment]
Link in this line is wrong:


IMPORTANT: you will need an Amazon EC2 Key Pair to be able to complete the following steps. Please see the [Official AWS Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html).

**Comment by lukeseawalker** [comment]
Hello @xuanus,
link points to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html which explains how to create an Amazon EC2 Key Pair. Why do you think that line is wrong?

Thanks,
L
