### ISSUE TITLE
(2.10.0 - 2.11.4) Tags in number interpreted as integer instead of string possible cause value error in Compute resource launch template

### ISSUE THREAD

**Issue by chenwany** [aws/aws-parallelcluster#3711]
**Bug description**

When creating cluster with tags set in the cluster configuration, if the tag’s key or value are in number,  they are interpreted as integer instead of string, possibly causing unexpected value conversion when tagging compute resources.
For example, cluster section with value tags = {"key" : "00000122"} is interpreted as “Key: key, Value: 82” for compute resources launched from launch template, because "00000122" is considered an octal and its string representation is converted to decimal.

This issue affects versions >=2.10.0, <=2.11.4 when creating cluster with number as tags.

**Causes of the problem**
ParallelCluster create compute fleet launch templates and pass the tags specified in the cluster configuration through cfn yaml template. The problem is that when yaml passing number without quote, it interprets it as integer instead of string. 
```
- Key: {{ tag.Key }}  
  Value: {{ tag.Value }}
```
Quotes is needed if the passing value are numbers in case we want to interpret them as string.
```
- Key: "{{ tag.Key }}"  
  Value: "{{ tag.Value }}"
```

**Workaround**
You can find the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(2.10.0---2.11.4)-Tags-in-number-interpreted-as-integer-instead-of-string-possible-cause-value-error-in-Compute-resource-launch-template).

**Comment by enrico-usai** [comment]
[2.11.5](https://github.com/aws/aws-parallelcluster/releases/tag/v2.11.5) version is available on PyPI.
