### ISSUE TITLE
Why using API to create VPC, but using CloudFormation to create Network. Any other resources created by ParallelCluster are not managed by CloudFormation?

### ISSUE THREAD

**Issue by xuanus** [aws/aws-parallelcluster#3712]
- using API to create VPC https://github.com/aws/aws-parallelcluster/blob/develop/cli/src/pcluster/networking/vpc_factory.py#L53
- using CloudFormation to create other network (Subnet, RouteTable, InternetGateway) https://github.com/aws/aws-parallelcluster/blob/develop/cli/src/pcluster/cli/commands/configure/networking.py#L104

1. It is not easy to manage the VPC without CloudFormation. Is it possible to unify them (VPC, Subnet and other network) by using CloudFormation?
2. Any other resources created by ParallelCluster are not managed by CloudFormation?
3. How ParallelCluster manage the Auto Scaling? I cannot find any EC2 Auto Scaling in CloudFormation or Console. No related info found in https://docs.aws.amazon.com/parallelcluster/latest/ug/autoscaling.html

**Comment by chenwany** [comment]
Hi! 
1. When using pcluster configure, ParallelCluster has a template to crate a Vpc stack, which contains the subnets and other resources. If you want to delete to Subnet, RouteTable, InternetGateway, you can go to cloudformation to delete the stack. For deleting the VPC, you need to manually delete it. The cloudformation template used by pcluster configure doesn’t include VPC creation to avoid issues with deleting VPCs that have dependencies outside of the cluster.

2. All other resources are managed by Cloudformation. Run pcluster delete will delete resources created by ParallelCluster. The CloudFormation pcluster-CleanupResources Lambda Function is created to delete cluster resources when you run the delete-cluster command.

3. Which scheduler and which version of ParallelCluster are you using? After version 2.9.0, only SGE and Torque scheduler use auto scaling group

Thanks

**Comment by xuanus** [comment]
Thanks for your response.

For # 2, if "All other resources are managed by Cloudformation", can I delete resources using CloudFormation console/API?

For # 3, I am using latest ParallelCluster and Slurm as scheduler. How ParallelCluster+Slurm manage the Auto Scaling cluster? Do you have any document to explain how it works? Such as: how to init/manage nodes and connect to DynamoDB?

**Comment by chenwany** [comment]
Hi @xuanus , sorry for reply late
For # 2, Yes, you can. we improve the documentation [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/install-v3-configuring.html#:~:text=After%20the%20cluster%20is%20deleted%2C%20you%20can%20delete%20the%20network%20resources%20in%20the%20VPC%20by%20deleting%20the), check the documentation for details for deleting resources.
For # 3, see documentation [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/multiple-queue-mode-slurm-user-guide-v3.html), ParallelCluster rely on slurm resume program to scale the cluster, instance is added to dynamoDB when the instance is launched.

Thanks
