### ISSUE TITLE
Add option to run pcluster CLI commands to show debug/verbose log/output

### ISSUE THREAD

**Issue by cparik** [aws/aws-parallelcluster#3723]
**The ParallelCluster team uses this template to report known issues on github. If you are reporting an issue, please use the 'Bug report' template instead.**

## Bug description
pcluster CLI doesn't have an option to print debug/verbose output for a command vis-a-vis `aws -d`. 
Not having such an option makes it difficult to troubleshoot issues. 

Provide the following information:
pcluster CLI doesn't have any option to show debug/verbose output. Sometimes, due to lack of this option, troubleshooting issues with the CLI itself becomes difficult and cumbersome.

It would help a lot if a debug/verbose logging flag/option could be added to the command that would emit the verbose output for the command that was run. 

pcluster CLI version 2.10

Example issue:
Change the value of the "Application" tag on the head node instance. 
Then try to run basic command like `pcluster status` or `pcluster ssh`. The output is a simple error 

```
ERROR: Head node not running. 
```
There is no workaround, we had to look into the code to figure out the workflow and then debug the issue.

**Comment by chenwany** [comment]
Hi, did you manually change the tag? It is possible that the cli are not able to find the corresponding headnode instance after tags changed. Are you able to see more details in `~/.parallelcluster/pcluster-cli.log`?

**Comment by demartinofra** [comment]
In ParallelCluster 3 you have the `--debug` flag that enables more verbose logging and the possibility to set PCLUSTER_LOG_TO_STDOUT environment variable to redirect the log to stdout rather than to file.

**Comment by cparik** [comment]
>>Hi, did you manually change the tag? It is possible that the cli are not able to find the corresponding headnode instance after tags changed. Are you able to see more details in ~/.parallelcluster/pcluster-cli.log?

@chenwany -- 
  Yes - I was working for a client and the client had changed the tag which caused the issue. Unfortunately, the `pcluster-cli.log` did not have any information regarding the tags. I had to manually debug this to find that it was caused due to a missing tag. Had this information been captured in the `pcluster-cli.log` file then debugging would be faster. 

@demartinofra  -- 
Thank you for sharing this information. I just have a follow up question, if we enable the `--debug` flag, does it show the tags that are required on the node instances?

**Comment by chenwany** [comment]
Hi @cparik, sorry for reply late.
>if we enable the --debug flag, does it show the tags that are required on the node instances?

Unfortunately, with --debug it doesn't show up that tags are required on the node instances. 
When using `pcluster ssh`, we try to filter the instance id with expected tags. But the filter result doesn't return anything. In pcluster3, we improve the error message to be `Unable to retrieve head node information`. 
I will pass your request on improving debug log in `pcluster ssh` to our team, thanks

**Comment by enrico-usai** [comment]
Hi @cparik let me list here the tags required by the head node for ParallelCluster 2.x, in this way you can manually re-add them to restore ssh command.

For ParallelCluster 2.x please double check the following ones:
* `Application`
* `aws-parallelcluster-node-type`
* `Name` (this is not really required if the `aws-parallelcluster-node-type` is configured)

## 2.x Master node tags

```
Key | Value
-- | --
Name | Master
aws-parallelcluster-node-type | Master
Version | 2.11.5
Application | parallelcluster-clustername
ClusterName | clustername
```


## 3.x Head node tags

For completenes I'm adding 3.x tags too.

```
Key | Value
-- | --
Name | HeadNode
parallelcluster:node-type | HeadNode
parallelcluster:cluster-name | clustername
parallelcluster:version | 3.1.0
```

**Comment by lukeseawalker** [comment]
hello @cparik,
were you able to move forward?

Thanks

**Comment by cparik** [comment]
Hello @lukeseawalker, @enrico-usai  - Thank you for sharing this information! 
I had fixed the issue after adding the necessary tags, however it took some time and manual effort of comparing it with another environment to figure out the tag. If the command had an option to detect and report the necessary tags, that would make it every easy. 

All good for now.
