### ISSUE TITLE
Get [WARNING] @aws-cdk/aws-cloudwatch.CommonMetricOptions#dimensions is deprecated

### ISSUE THREAD

**Issue by xuanus** [aws/aws-parallelcluster#3756]
repro steps:

1. python3 -m pip install --upgrade "aws-parallelcluster"
2. pcluster configure --config cluster-config.yaml
3. pcluster create-cluster --cluster-name my-cluster --cluster-configuration cluster-config.yaml

```
[WARNING] @aws-cdk/aws-cloudwatch.CommonMetricOptions#dimensions is deprecated.
  Use 'dimensionsMap' instead.
  This API will be removed in the next major release.
```

**Comment by lukeseawalker** [comment]
Hello @xuanus,
this is solved by https://github.com/aws/aws-parallelcluster/pull/3412 and will be included in next version.
