### ISSUE TITLE
Configure /efs mount on compute nodes

### ISSUE THREAD

**Issue by hellmersjl3ds** [aws/aws-parallelcluster#376]
I'd like to give the /efs mount some specific configuration options on the compute nodes that are created through cfncluster.  Is a post install script the best way do do this?

**Comment by lukeseawalker** [comment]
Yes it is, as there is no out-of-the-box CfnCluster integration.

L

**Comment by hellmersjl3ds** [comment]
Couple of questions
1. Does the post install script run as root?
2. What are the "boot_as*" scripts in the documentation pages refer to?

**Comment by mauri-melato** [comment]
Hello,
1. Yes, pre/post install scripts run as root
2. The "boot_as_*" refers to all the operations to setup a node to "boot as" master or compute node. They are the cookbook recipes performing all the software installation and machine configurations. For example scheduler setup is done in this phase.
3. Pre/post install scripts are downloaded from S3 and execution flag applied before being launched

**Comment by hellmersjl3ds** [comment]
I was able to use a post install script to do this.  Should we close this issue, or do you see a potential enhancement to do this in a more standard way?

**Comment by enricou** [comment]
Let's keep opened as feature enhancement.

**Comment by enrico-usai** [comment]
I'm going to close this issue since we added the EFS support with [ParallelCluster 2.1.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.1.0).
I'm also pleased to mention we added the FSx Lustre support for Centos 7 with [ParallelCluster 2.2.1](https://github.com/aws/aws-parallelcluster/releases/tag/v2.2.1).
