### ISSUE TITLE
CLI error when running 3.1.1 in Lambda

### ISSUE THREAD

**Issue by ccassidy-vaisala** [aws/aws-parallelcluster#3770]
**Required Info:**
 - AWS ParallelCluster version 3.1.1

**Bug description and how to reproduce:**
When running pcluster cli within a Lambda function it fails with a read-only file system error.  It appears the default directory of the log file is set for the home directory which is not writable in Lambda.  I was able to get around this by setting an environment variable for PCLUSTER_LOG_FILE: /tmp/pcluster.cli.log.

Found the reference in this code: https://github.com/aws/aws-parallelcluster/blob/33b3f045bf1008b380f337299c1856e8582c1010/cli/src/pcluster/utils.py#L273

Works fine with the workaround but wanted to provide awareness in case this was an unexpected change.

**Log output**
```
File "/opt/bin/pcluster", line 11, in <module>
sys.exit(main())
File "/opt/python/pcluster/cli/entrypoint.py", line 232, in main
pcluster_logging.config_logger()
File "/opt/python/pcluster/cli/logger.py", line 60, in config_logger
os.makedirs(os.path.dirname(logfile), exist_ok=True)
File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/var/lang/lib/python3.8/os.py", line 223, in makedirs
mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
```

**Comment by demartinofra** [comment]
Hi @ccassidy-maxar 

Thanks for reporting this. The CLI entrypoint is not meant to be used in Lambda. When deploying ParallelCluster in a Lambda function (see https://docs.aws.amazon.com/parallelcluster/latest/ug/api-reference-v3.html) we use a different entrypoint that will skip the initialization of the log file: https://github.com/aws/aws-parallelcluster/blob/develop/cli/src/pcluster/api/awslambda/entrypoint.py.

In case you want to run the CLI as is in Lambda then the right approach is to set the PCLUSTER_LOG_TO_STDOUT env variable or change the log file with PCLUSTER_LOG_FILE

**Comment by ccassidy-vaisala** [comment]
Hi @demartinofra

Thank you for the confirmation on this.  Will use the PCLUSTER_LOG_FILE env variable going forward for our use case.
