### ISSUE TITLE
Compute instances not launching with the API (v3.1.1)

### ISSUE THREAD

**Issue by coderodyhpc** [aws/aws-parallelcluster#3808]
Hello,
I've been trying to figure out this problem for the last 3 days but it's always the same result. Using the API (v3.1.1) launches a fresh cluster w/o much issue OS: Ubuntu 20.04). The problem is when I select custom AMI. Firstly, it warns me as the screenshot shows:

![problems_with_clusters001edited](https://user-images.githubusercontent.com/79646720/155214988-087a03a4-5734-45fc-8148-89cca28bc29e.png)

Then, the head node launches w/o any problem (everything is there, and putty can connect to it). However, the compute nodes never launch (it's like an endless loop where nothing happens). The logs don't tell me much; I'm posting one of them but let me know if you need any other. Earlier today, I went back to square one to make sure that I wasn't missing anything and followed the instructions to create the custom AMI step-by-step. Here, I have to acknowledge that I had not run ami_cleanup.sh previously or stopped the instance to create the image. However, the issue persists even with this new fresh AMI.
Thanks.         
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/8120008/cloud-init.log)

**Comment by hanwen-pcluste** [comment]
Hi there!

The warnings are expected when using custom AMI.

We recommend following this [guide to retrieve logs](https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3.html#troubleshooting-v3-get-logs). 
Specifically, we are interested in the following logs:
1. `/var/log/parallelcluster/slurm_resume.log` on the head node
2. `/var/log/cloud-init-output.log` on the compute nodes

Thank you,
Hanwen

**Comment by coderodyhpc** [comment]
Hi @**hanwen-pcluste**, 
The compute nodes never spin up so there're no logs from them. The file `/var/log/parallelcluster/slurm_resume.log` is empty and Slurm doesn't work (something is definitely not clicking in the deployment). Instead, I'm attaching slurmctld that is complaining about `/var/spool/slurm.state/node_state` but not sure why (maybe this is a common error but it's the first time that I run into it).
Thanks.
[slurmctld.log](https://github.com/aws/aws-parallelcluster/files/8132808/slurmctld.log)

**Comment by hanwen-pcluste** [comment]
The errors in the slurmctld.log are expected.
Can you provide the output of `scontrol show nodes`?
What will happen if you submit a simple job (e.g. `sbatch --wrap="sleep 1"`)?

Thank you!

**Comment by coderodyhpc** [comment]
```
$ scontrol show nodes
NodeName=queue0-dy-queue0-t2-micro-1 CoresPerSocket=1
   CPUAlloc=0 CPUTot=1 CPULoad=N/A
   AvailableFeatures=dynamic,t2.micro,queue0-t2-micro
   ActiveFeatures=dynamic,t2.micro,queue0-t2-micro
   Gres=(null)
   NodeAddr=queue0-dy-queue0-t2-micro-1 NodeHostName=queue0-dy-queue0-t2-micro-1
   RealMemory=1 AllocMem=0 FreeMem=N/A Sockets=1 Boards=1
   State=IDLE+CLOUD+POWERED_DOWN ThreadsPerCore=1 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Partitions=queue0
   BootTime=None SlurmdStartTime=None
   LastBusyTime=Unknown
   CfgTRES=cpu=1,mem=1M,billing=1
   AllocTRES=
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s

NodeName=queue0-dy-queue0-t2-micro-2 CoresPerSocket=1
   CPUAlloc=0 CPUTot=1 CPULoad=N/A
   AvailableFeatures=dynamic,t2.micro,queue0-t2-micro
   ActiveFeatures=dynamic,t2.micro,queue0-t2-micro
   Gres=(null)
   NodeAddr=queue0-dy-queue0-t2-micro-2 NodeHostName=queue0-dy-queue0-t2-micro-2
   RealMemory=1 AllocMem=0 FreeMem=N/A Sockets=1 Boards=1
   State=IDLE+CLOUD+POWERED_DOWN ThreadsPerCore=1 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Partitions=queue0
   BootTime=None SlurmdStartTime=None
   LastBusyTime=Unknown
   CfgTRES=cpu=1,mem=1M,billing=1
   AllocTRES=
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s

NodeName=queue0-dy-queue0-t2-micro-3 CoresPerSocket=1
   CPUAlloc=0 CPUTot=1 CPULoad=N/A
   AvailableFeatures=dynamic,t2.micro,queue0-t2-micro
   ActiveFeatures=dynamic,t2.micro,queue0-t2-micro
   Gres=(null)
   NodeAddr=queue0-dy-queue0-t2-micro-3 NodeHostName=queue0-dy-queue0-t2-micro-3
   RealMemory=1 AllocMem=0 FreeMem=N/A Sockets=1 Boards=1
   State=IDLE+CLOUD+POWERED_DOWN ThreadsPerCore=1 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Partitions=queue0
   BootTime=None SlurmdStartTime=None
   LastBusyTime=Unknown
   CfgTRES=cpu=1,mem=1M,billing=1
   AllocTRES=
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s

NodeName=queue0-dy-queue0-t2-micro-4 CoresPerSocket=1
   CPUAlloc=0 CPUTot=1 CPULoad=N/A
   AvailableFeatures=dynamic,t2.micro,queue0-t2-micro
   ActiveFeatures=dynamic,t2.micro,queue0-t2-micro
   Gres=(null)
   NodeAddr=queue0-dy-queue0-t2-micro-4 NodeHostName=queue0-dy-queue0-t2-micro-4
   RealMemory=1 AllocMem=0 FreeMem=N/A Sockets=1 Boards=1
   State=IDLE+CLOUD+POWERED_DOWN ThreadsPerCore=1 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Partitions=queue0
   BootTime=None SlurmdStartTime=None
   LastBusyTime=Unknown
   CfgTRES=cpu=1,mem=1M,billing=1
   AllocTRES=
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s

```

**Comment by coderodyhpc** [comment]
```
$ sbatch --wrap="sleep 1"
Submitted batch job 1
ubuntu@ip-xxx-xx-xx-xxx:~$ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
                 1    queue0     wrap   ubuntu CF       0:05      1 queue0-dy-queue0-t2-micro-1

```

**Comment by hanwen-pcluste** [comment]
Did the job finish?
Can you provide `slurmctld.log` and `slurm_resume.log` after the job finishs/fails?
Moreover, could you describe what changes did you make in the AMI?

Thank you!

**Comment by coderodyhpc** [comment]
Earlier this morning I forgot to post that the job never ran:
```
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
                 1    queue0     wrap   ubuntu PD       0:00      1 (BeginTime)

``` 
I waited for about 45' this morning and 30' this evening but it never got going. This evening I also copied the output of some of the logs that the system is outputting while trying (unsuccessfully) to start the job.
[NOTE: The AMI has over 20 apps plus dependencies. However, I didn't touch anything related to the OS - I have done this dozens of times with awspc v2 w/o any issue of this kind]

 
[auth.log](https://github.com/aws/aws-parallelcluster/files/8137705/auth.log)
[cfn-wire.log](https://github.com/aws/aws-parallelcluster/files/8137706/cfn-wire.log)
[slurmctld.log](https://github.com/aws/aws-parallelcluster/files/8137707/slurmctld.log)

**Comment by coderodyhpc** [comment]
Hello @**hanwen-pcluste**, 
I have tried over 2 dozen different combinations (in order to isolate the problem) but it is almost always the same result. If I simply load stuff in the custom AMI, the cluster launches. However, installing software leads to failure when spinning up the compute nodes. I've checked the OS files and noticed that the only changes are at the `/run` directory and, more specifically, the subdirectories `systemd` and `motd.d`:
```
...
drwxr-xr-x 23 root              root     540 Feb 27 18:01 systemd
drwxr-xr-x  3 root              root      60 Feb 27 18:01 motd.d
-rw-r--r--  1 root              root     646 Feb 27 19:58 motd.dynamic
drwxr-xr-x 38 root              root    1240 Feb 27 19:58 .
-rw-rw-r--  1 root              utmp    2304 Feb 27 19:58 utmp

```
Looking inside these subdirectories, the modified files seem to be:
```
...
drwxr-xr-x  2 root            root              40 Feb 27 18:01 dynamic-uid
drwxr-xr-x  2 systemd-resolve systemd-resolve   80 Feb 27 19:44 resolve
drwxr-xr-x  5 systemd-network systemd-network  120 Feb 27 19:44 netif
drwxr-xr-x  2 root            root              80 Feb 27 19:58 transient
drwxr-xr-x  2 root            root              60 Feb 27 19:58 users
drwxr-xr-x  2 root            root             120 Feb 27 19:58 sessions
drwxr-xr-x 38 root            root            1240 Feb 27 19:58 ..
drwxr-xr-x  2 root            root            1940 Feb 27 20:01 units
```
and the file `85-fwupd`. I'm not that familiar with several of these files but my question is whether an alteration in these files could cause compute instances launch to fail as I'm seeing.
Thanks.

**Comment by chenwany** [comment]
Hi! After submitting the job, are you able to find something in /var/log/parallelcluster/slurm_resume.log and /var/log/parallelcluster/clustermgtd log?

From slurmctld.log:
```
[2022-02-25T01:18:02.304] update_node: node queue0-dy-queue0-t2-micro-2 state set to DOWN
[2022-02-25T01:18:02.314] error: get_addr_info: getaddrinfo() failed: Temporary failure in name resolution
[2022-02-25T01:18:02.314] error: slurm_set_addr: Unable to resolve "queue0-dy-queue0-t2-micro-2"
[2022-02-25T01:18:02.314] error: fwd_tree_thread: can't find address for host queue0-dy-queue0-t2-micro-2, check slurm.conf
[2022-02-25T01:18:27.748] update_node: node queue0-dy-queue0-t2-micro-2 reason set to: Scheduler health check failed
[2022-02-25T01:18:27.748] powering down node queue0-dy-queue0-t2-micro-2
```
There's some error with name resolution: `getaddrinfo() failed: Temporary failure in name resolution, slurm_set_addr: Unable to resolve "queue0-dy-queue0-t2-micro-2"`
The job stay at PD because all nodes are unhealthy and failed to launch. It seems that some slurm setting is broken and unable to resolve the node name. 
Have you been trying with running 
`sudo systemctl restart slurmctld`
`scontrol reconfigure` to see if they recover?
Can I ask which way you go forward to create the custom ami? Do you use pcluster create-image to create the ami or modify an existing parallelcluster ami to install the softwares?
Does the problem happen if you remove custom ami?
Thanks

**Comment by coderodyhpc** [comment]
Hello @**hanwen-pcluste**,
When I submit `(sbatch) --wrap="sleep 1"` ---> The subdirectory `/var/log/parallelcluster` looks like:
```
drwxrwxrwt  2 root           root           4096 Mar  1 12:47 .
drwxrwxr-x 21 root           syslog         4096 Mar  1 12:47 ..
-rw-r--r--  1 root           root           6057 Mar  1 12:49 clustermgtd
-rw-r--r--  1 pcluster-admin pcluster-admin 3865 Mar  1 12:49 slurm_resume.log
-rw-r--r--  1 pcluster-admin pcluster-admin  674 Mar  1 12:49 slurm_suspend.log
```
with the files `slurm_resume.log` and `clustermgtd.log` attached to this message. 
The command `sudo systemctl restart slurmctld` does not make any difference and `scontrol reconfigure` returns an error (`slurm_reconfigure error: Invalid user id`).
I create custom AMIs by modifying a parallelcluster AMI (in this case the software is installed on an ami-04ff11c1098fb90e0). There's no problem using standard AMIs, as a matter of fact there is no problem with a custom AMI loaded with extras as long as the AMI does not increase in size. I checked to make sure that it was not the AMI creation process itself the one causing the issue.
Thanks.   
[slurm_resume.log](https://github.com/aws/aws-parallelcluster/files/8161752/slurm_resume.log)
[slurm_suspend.log](https://github.com/aws/aws-parallelcluster/files/8161753/slurm_suspend.log)

**Comment by coderodyhpc** [comment]
Previously I had not gone over the `slurm_resume` log and just noticed the message:
`2022-03-01 12:49:09,766 - [slurm_plugin.instance_manager:add_instances_for_nodes] - ERROR - Encountered exception when launching instances for nodes (x1) ['queue0-dy-queue0-t2-micro-1']: An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Volume of size 35GB is smaller than  snapshot 'snap-05f39e79cb93118a6', expect size >= 102GB`
When I tried launching the cluster, I selected 150 GiB as the root volume (>102 GiB that is the AMI size) but it seems like the API is applying this parameter to the head instance but not to the compute instances. 
P.S. I checked again, and the problem seems to be the size of the disk space attached to the compute instances.

**Comment by chenwany** [comment]
Hi! 
The volume size should also be specified under compute nodes. See documentation here: https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeSettings-LocalStorage
```
ComputeSettings:
  LocalStorage:
    RootVolume:
      Size: integer
```
If it is not specify, it will use the default volume size 35GB.
Let us know if it works after adding compute volume size to the configuration.

Thanks

**Comment by coderodyhpc** [comment]
Hi  @hanwen-pcluste , 
I've always declared the volume size for the compute nodes for awspc v2 in the scripts. However, the problem has occurred while transitioning to version 3 and learning the API. I don't see how you can specify any of the characteristics for the EBS attached to the compute nodes including volume size; even expanding advanced options doesn't offer you how to achieve this (although it technically allows you to use different custom AMIs for head and compute nodes). Anyway, going back to the problem itself, my presumption was that, because the API doesn't allow you to customize the EBS associated with the compute nodes, it'd use the inputs from the root volume (for the head node). This sounds pretty reasonable to me even though other people might disagree and assume some default values. 
I was finally able to work around this problem and launch some compute nodes by taking the yaml file generated by the API and manually modifying it. Although I can work with this temporally, it's not a particular great solution (kind of beats the purpose of having an API if you still have to learn how to edit the yaml files). I have a couple of suggestions:
1 - Unless you are very familiar with everything, it's hard to figure out that the key to understanding the issue is reading `slurm_resume.log` at `/var/log/parallelcluster` (maybe the error specifics should also be shown at some more general log).
2 - The API needs some expansion so that the size and type of storage associated with the compute nodes can be specified without having to modify the yaml files.
Thanks.

**Comment by chenwany** [comment]
Thank you for your suggestions! They make lots of sense and I already passed your suggestions to the team. 
We also plan to improve the volume size but setting the default volume size to be the snapshot size instead of hard code it as 35 GB, which may be more reasonable.

Thanks

**Comment by coderodyhpc** [comment]
Hi @**chenwany**, 
I'm reopening the thread very briefly to let you know that the yaml output generated by the API did not include the parameter for spot prices. No problem when I added it to the template, but the original did not have it.
