### ISSUE TITLE
What is the proper way to shutdown a slurm compute node so the job running on it gets requeued & restarted?

### ISSUE THREAD

**Issue by gwolski** [aws/aws-parallelcluster#3809]
I'm using parallel cluster 2.11.4.  The issue is related to spot instances, using fsx lustre file systems and shutting down a spot instance when you get the termination notice. The high level question is how can I best down the slurm spot based compute node when I get the "spot instance is being terminated" notification so my job gets requeued and restarted?

According to the FSX for Lustre docs, you should unmount any fsx disks you have mounted rather than do an ungraceful shutdown (i.e. AWS terminating you).  Documented here:

https://docs.aws.amazon.com/fsx/latest/LustreGuide/working-with-ec2-spot-instances.html

I use a variant of this script.

The problem is that I kill my running job, it exits.  Slurm recognizes my job has finished (albeit with a kill -TERM signal) and all is happy, i.e. slurm thinks my job has finished and doesn't have to requeue it.  The node then goes away, slurm ultimately recognizes and marks the node down.

As I killed the job, it isn't being requeued.  I want to have it requeued.  So what is the right way, on a running node, to take the node down so the job gets requeued and restarted?

Is it as simple as:

sudo /opt/slurm/bin/scontrol update node=$(hostname) state=DOWN

I can then sleep for 30 seconds, kill my jobs, then umount the fsx disks.
I'm expecting the job to be requeued, with a BeginTime which I believe is about one minute in the future, so my 30 second wait should be good enough?

Also Is the node always equal to the hostname? 

Appreciate any advice on this.

**Comment by hanwen-pcluste** [comment]
Hello Guntram

Sorry for the late reply. Recent weeks have been busy. We will get back to you as soon as possible.

Thank you,
Hanwen

**Comment by chenwany** [comment]
Hi Guntram,
If you run `scontrol update nodename=your_node_name state=down reason=test_reason`, the node will be set to down, and I think the job will be requeue automatically.
After the node is set to down, the clustermgtd will treat the instance behind the node as unhealthy, then the instance will be terminate. 
Currently we don't have a mechanism to automatically run some script before instance terminated. We are tracking it as a feature request here: https://github.com/aws/aws-parallelcluster/issues/2491
Can we ask how do you run the script to unmount the volumw before spot instance get terminated on the compute node? Did you unmount fsx by submitting a job?

Thanks

**Comment by chenwany** [comment]
This is a previous github issue use spot instance that you might interested in: https://github.com/aws/aws-parallelcluster/issues/2887
It suggest that you can use SSM Run Command as a target of the CloudWatch Event rule, to automatically run commands into the instances.

**Comment by gwolski** [comment]
spot will give you a two minute warning that you can poll.  I have a systemd service running a version of the shell script shown here (along with the details about the polling):

https://docs.aws.amazon.com/fsx/latest/LustreGuide/working-with-ec2-spot-instances.html

This gives me two minute warning (which I only check for every 30 seconds as shown in the code on the above page).  I have created a service in the file /etc/systemd/system/umount_disks_spot.service with the following content:
```
[Unit]
Description = Umounting all FSX disks cleanly on instance termination
After=network-online.target

[Service]
User=root
ExecStart=/opt/bin/umount_disks_script.sh
Restart=always

[Install]
WantedBy=default.target
```
I also have modified my code to perform the kill differently before trying the umount.  Instead of the shown
```
fuser -kMm -TERM "${FSXPATH}"; sleep 2
```
in the AWS page, I use this command:
```
kill -TERM $(lsof -t ${fs});sleep 2
kill -KILL $(lsof -t ${fs});sleep 2
```
fuser won't identify processes that have dynamic libraries open... lsof will identify them so I make sure I kill everything.  

This service starts on all my parallelcluster compute nodes at boot time with the post-install script I run that does a bunch of stuff.

**Comment by digout** [comment]
Have a look at this blog https://aws.amazon.com/it/blogs/hpc/using-spot-instances-with-aws-parallelcluster-and-amazon-fsx-for-lustre/

-- dp

**Comment by enrico-usai** [comment]
Thanks @gwolski for sharing the details of your solution and thanks @digout for the suggestion.

**Comment by gwolski** [comment]
Thank you to @digout -- the blog is exactly what I was looking for.  They took the FSX example I pointed to and made it production worthy for parallel cluster.  Thanks!

**Comment by gwolski** [comment]
I have implemented the suggestion in the blog and it works.  One nuance though.  The blog shows:

#!/bin/bash
trap "exit 200" TERM
\<YOUR CODE HERE...\>

Be careful, you need to have your #SBATCH directives first before any code..  Example:

#!/bin/bash
#SBATCH --job-name="sleep 36000"
#SBATCH --partition=simc2m16-spot
#SBATCH --constraint=
#SBATCH --nice=
#SBATCH --licenses=none

trap "exit 200" TERM
\<YOUR CODE HERE...\>

From the slurm documentation:

The batch script may contain options preceded with "#SBATCH" before any executable commands in the script. sbatch will stop processing further #SBATCH directives once the first non-comment non-whitespace line has been reached in the script.

**Comment by hanwen-pcluste** [comment]
Thank you for the information.

I am going to close this issue. Please feel free to reopen it if you have further conversion

Hanwen
