### ISSUE TITLE
Slurm fails to utilize the full service quota

### ISSUE THREAD

**Issue by swaroop-nath** [aws/aws-parallelcluster#3863]
I have increased my service quota from 32 to 96 after starting a AWS Parallel Cluster and queuing jobs. The compute nodes are r5axlarge (vCPU=4 per node). However, slurm resume program fails to utilize the full quota potential, and still shows that the limit is 32. A snapshot from the slurm_resume log - 

    2022-03-06 04:53:05,459 - [slurm_plugin.instance_manager:add_instances_for_nodes] - ERROR - Encountered exception when launching instances for nodes (x13) ['queue1-dy-r5axlarge-8', 'queue1-dy-r5axlarge-9', 'queue1-dy-r5axlarge-10', 'queue1-dy-r5axlarge-11', 'queue1-dy-r5axlarge-12', 'queue1-dy-r5axlarge-13', 'queue1-dy-r5axlarge-14', 'queue1-dy-r5axlarge-15', 'queue1-dy-r5axlarge-16', 'queue1-dy-r5axlarge-17', 'queue1-dy-r5axlarge-18', 'queue1-dy-r5axlarge-19', 'queue1-dy-r5axlarge-20']: 
    An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: 
    You have requested more vCPU capacity than your current vCPU limit of 32 allows for the instance 
    bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.

I have tried to cancel pending jobs and requeue them. However the issue still persists.

**Comment by enrico-usai** [comment]
Hi @swaroop-nath sorry for the delay,

Which specific limit did you increase? Did you check [these instructions](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-on-demand-instance-vcpu-increase/) and [these](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-on-demand-instances.html#vcpu-limits-request-increase)?

Thanks

**Comment by lukeseawalker** [comment]
Hello @swaroop-nath,
were you able to move forward?

Thanks

**Comment by swaroop-nath** [comment]
Hi guys, @lukeseawalker and @enrico-usai, sorry for the delay. Turns out that the service quota had shown an increase in my console but wasn't actually increased. I contacted AWS support and they informed me the same.

**Comment by sniperyyc** [comment]
Same issue here, @swaroop-nath was your case resolved after contacting AWS support?
