### ISSUE TITLE
(3.0.0-3.1.2) build-image stack deletion failed after image successfully created

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-parallelcluster#3867]
## Bug description

Starting from 2021-03-03 the `build-image` command may fail during stack deletion after image created successfully. 
From the result of `pcluster describe-image --image-id <your-image-id>` , `imageBuildStatus` is in `BUILD_COMPLETE`  state and image `state` is `AVAILABLE`, but the CloudFormation stack deletion failed with the following error messages: 
```
Resource handler returned message: 
"User: arn:aws:sts::1234567:assumed-role/ParallelClusterImageCleanup-xxxx-xxxx-xxxx/ParallelClusterImage-xxxxx is not authorized to perform: 
imagebuilder:GetImage on resource: arn:aws:imagebuilder:us-east-1:1234567:image/parallelclusterimage-build-image/3.1.2/1 
(Service: Imagebuilder, Status Code: 403, Request ID: xxx)" 
(RequestToken: xxxxx, HandlerErrorCode: GeneralServiceException)

Resource handler returned message: 
"User: arn:aws:sts::1234567:xxxx is not authorized to perform: 
imagebuilder:CancelImageCreation on resource: arn:aws:imagebuilder:sa-east-1:1234567:image/parallelclusterimage-integ-tests-build-image-xxx/3.1.2/1 
(Service: Imagebuilder, Status Code: 403, Request ID: xxx)" 
(RequestToken: xxxx, HandlerErrorCode: GeneralServiceException)
 ```

You can verify whether you are impacted by the issue by executing the following command:
```
pcluster get-image-stack-events --image-id <your-image-id> --region <image-build-region> --query "events[0]"
```
Then you can check from the output if the `resourceStatus` and `resourceStatusReason` match the following:
```
"resourceStatusReason": "The following resource(s) failed to delete: [ParallelClusterImage]. "
"resourceStatus": "DELETE_FAILED",
```
If you are not impacted by the issue, the following output is expected:
```
{
  "message": "CloudFormation Stack for Image build-image does not exist."
}
```

The root cause of the problem is that the new version of EC2 Image Builder service, which is used by ParallelCluster `build-image` command, requires two new additional IAM policies `imagebuilder:GetImage` and `imagebuilder:CancelImageCreation`.

## Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.1.2)-build-image-stack-deletion-failed-after-image-successfully-created).

**Comment by chenwany** [comment]
Close the issue since image-builder rollback the changes that require additional IAM policies.
