### ISSUE TITLE
cron jobs for mlocate and man-db should be disabled

### ISSUE THREAD

**Issue by mrgum** [aws/aws-parallelcluster#3869]
If you are reporting an issue with AWS Parallelcluster / CfnCluster please make sure to add the following data in order to facilitate the root cause detection:

**Required Info:**
 - AWS ParallelCluster version [e.g. 2.9.0]: 3.1.2
 - Full cluster configuration without any credentials or personal data n/a
 - Cluster name: n/a
 - [Optional] Arn of the cluster CloudFormation main stack: n/a
 - Full cluster configuration without any credentials or personal data
 - Cluster name:
 - [Optional] Arn of the cluster CloudFormation main stack: ami-09b149c7278ece284

**Bug description and how to reproduce:**
Out of the box parallel cluster has mlocate installed and runs daily cron jobs
- updatedb
- update man-db
Install parallelcluster and see that locate works :)
man-db is probably not worth having on a system with modules installed as these add to MANPATH

**Additional context:**
Any other context about the problem. E.g.:

like any cron based system activity. running updatedb/man-db can impact the performance of running jobs, and affects benchmarking results

I think it would be better if the default were to disable things like this

**Comment by enrico-usai** [comment]
Hi @mrgum thanks for this suggestion.

`mlocate`, `man-db` updates are executed by Anacron, so a suggestion might be to add an `OnNodeConfigured` [custom bootstrap action](https://docs.aws.amazon.com/parallelcluster/latest/ug/custom-bootstrap-actions-v3.html) to disable Anacron in the compute nodes, with a script like the following:

```bash
#!/bin/bash
sed 's/^/#/' /etc/anacrontab | sudo tee /etc/anacrontab.tmp
mv -f --backup /etc/anacrontab.tmp /etc/anacrontab
```

Let me know if it helps, anyway I'm marking it as feature enhancement.
Thanks

**Comment by francesco-giordano** [comment]
[AWS-ParallelCluster 3.2.1](https://github.com/aws/aws-parallelcluster/releases/tag/v3.2.1) Disable cron job tasks man-db and mlocate, which may have a negative impact on node performance.
