### ISSUE TITLE
Allow multiple subnets

### ISSUE THREAD

**Issue by lletourn** [aws/aws-parallelcluster#3873]
Issue #307 was closed but the issue it refers to #1066 never solved the mutiple subnet feature.

The Yaml allows for multiplt subnets per queue, but at creation it is refused.
Create multiple queues in different subnets is also refused.

I understand the need for low latency when different jobs communicate to each other, but if the use case is just many compute jobs with or without dependencies, access to more instances accorss AZs is more important and is at the moment impossible.

**Comment by enrico-usai** [comment]
I'm going to close this one in favour of: https://github.com/aws/aws-parallelcluster/issues/3576 (that I just renamed).
