### ISSUE TITLE
Slurm configuration

### ISSUE THREAD

**Issue by coderodyhpc** [aws/aws-parallelcluster#3880]
Hello,
[Using v 3.1.1]
I was trying to run the command slurmd but both head and compute nodes tell me it's not there. I also checked slurm.conf and, at the bottom, it states:
```
#
# WARNING!!! The slurm_parallelcluster.conf file included
# get updated by pcluster process, be careful
# when manually editing!
include slurm_parallelcluster.conf
```
I'm not sure but my guess is that slurm.conf seems to be copied from the head to the compute nodes regardless of the type of instances. Is there any procedure or advice on how to manually edit the conf file? Thanks.

**Comment by lukeseawalker** [comment]
hello @coderodyhpc,
`/opt/slurm` is shared from the head node and mounted by all the computes.
If you modify `/opt/slurm/etc/slurm.conf` from head, the changes are saw by the computes: just remember that you may want to restart the demons everywhere.

**Comment by coderodyhpc** [comment]
Hi @**lukeseawalker**,
That was my guess. However, when I try to call the slurm daemon, it's still producing the error message:
```
$slurmd

Command 'slurmd' not found, but can be installed with:

sudo apt install slurm-wlm-emulator  # version 19.05.5-1, or
sudo apt install slurmd              # version 19.05.5-1
```
This happens on both head and compute nodes. Thanks.

**Comment by lukeseawalker** [comment]
because slurmd is in `/opt/slurm/sbin` while in the PATH there is `/opt/slurm/bin`. You can verify it with
```
echo $PATH
```

You can call slurmd specifying the full path, i.e. `/opt/slurm/sbin/slurmd`.

Can you please share your use case to have the slurm demon binaries in the path?
Thanks

**Comment by lukeseawalker** [comment]
for the records, PCluster links `/opt/slurm/etc/slurm.sh` into the profile, see [here](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/cookbooks/aws-parallelcluster-slurm/recipes/config.rb#L27-L33)

```
$ cat /opt/slurm/etc/slurm.sh

#
# slurm.sh:
#   Setup slurm environment variables
#

PATH=$PATH:/opt/slurm/bin
MANPATH=$MANPATH:/opt/slurm/share/man

export PATH MANPATH
```

**Comment by coderodyhpc** [comment]
Hi @**lukeseawalker**, 
I was able to run slurmd using the full path w/o any problem. I was trying to understand the binding when submitting a hybrid job (OpenMP+MPI) via slurm to a cluster with c6a instances.

**Comment by demartinofra** [comment]
Thanks @coderodyhpc for the update. If there are no open questions I'm going to resolve the issue.
