### ISSUE TITLE
EBS with only required settings do not deploy a new cluster

### ISSUE THREAD

**Issue by jlanzarotti** [aws/aws-parallelcluster#3951]
According to the docs https://docs.aws.amazon.com/parallelcluster/latest/ug/SharedStorage-v3.html#SharedStorage-v3-EbsSettings, when using EBS shared storage you need to provide Throughput and DeletionPolicy. Using the VolumeType with the current default `gp2` seems to be incompatible with `Throughput`.

```
The throughput parameter is not supported for gp2 volumes. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterCombination;
```

**Comment by chenwany** [comment]
Thank you for reporting the problem! `Throughput` and `DeletionPolicy` are not required parameters when using EBS shared storage. We will fix the documentation. The throughput parameter is not supported for gp2 volumes.

**Comment by enrico-usai** [comment]
Documentation is fixed.

We marked `Throughput` and `DeletionPolicy` as **Optional**, and documented that `Throughput` setting is valid only when `VolumeType` is `gp3`.

Thanks!
