### ISSUE TITLE
(3.0.0-3.1.3) build-image creates invalid images when using aws-cdk.aws-imagebuilder==1.153.0

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-parallelcluster#3988]
### Bug description

ParallelCluster depends on the `aws-cdk` Python library. It is installed automatically when installing the `aws-parallelcluster` package from PyPI. 

The latest version of `aws-cdk` (1.153.0) changed its internal behaviour in the `aws-cdk.aws-imagebuilder` library, causing the build image process, executed by the `pcluster build-image` command, to create invalid images.

You can verify if you are affected by this issue by checking the installed version of the `aws-imagebuilder` library in the environment on which you have the ParallelCluster CLI installed using the following command:

```
$ pip freeze | grep imagebuilder
aws-cdk.aws-imagebuilder==1.153.0
```

When using the `1.153.0` version of the library, the `pcluster build-image` execution doesn’t return any error, the AMI is created but the image won’t be available in the list of ParallelCluster images, because internal information is missing (e.g. tags for ParallelCluster version, image id, etc).

This means you won’t see the image in the output of the `pcluster describe-image` and `pcluster list-images` commands and you cannot delete it with `pcluster-delete` command.

### Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.1.3)-build-image-creates-invalid-images-when-using-aws-cdk.aws-imagebuilder-1.153.0).

**Comment by lukeseawalker** [comment]
New release 3.1.4 is out
