### ISSUE TITLE
pcluster build-image fails in one of the cookbook component in 3.1.3

### ISSUE THREAD

**Issue by bacharzin** [aws/aws-parallelcluster#3995]
Status reason:

Resource handler returned message: "Error occurred during operation 'SSM execution 'f9fada4e-849a-4bb6-a444-32b6a9571782' failed for image arn: 'arn:aws:imagebuilder:us-east-1:xxxxxxxxxxxx:image/parallelclusterimage-xxxxxxxxxxxxxxxxxxxxxxxx/3.1.3/1' with status = 'Failed' in state = 'BUILDING' and failure message = 'Document arn:aws:imagebuilder:us-east-1:xxxxxxxxxxxx:component/parallelclusterimage-c7374890-c574-11ec-9f03-12507a6b4b03/3.1.3/1 failed!''." (RequestToken: 7227e835-5fea-c3bd-cdfb-b27f4c1392d7, HandlerErrorCode: GeneralServiceException)

**Comment by demartinofra** [comment]
Can you please share the config used to build the image and the image build logs that can be retrieved with the commands reported in https://docs.aws.amazon.com/parallelcluster/latest/ug/custom-ami-v3.html?

**Comment by joehellmersNOAA** [comment]
I'm having a similar problem and I tracked it down to having an AMI with an old version of Amazon Linux (2018.03) which isn't apparently supported.

Is there any sort of work around I could try?

**Comment by bacharzin** [comment]
I was using an old AMI, I replaced it with this  ami-0eee15b8096c92ba5 (amz linux2).
This change fixed the issue.

**Comment by demartinofra** [comment]
You could use a more recent base AMI or set the following in the image config:
```
Build:
  UpdateOsPackages:
    Enabled: true
```

Also if you still face issues can you please report the full image config and full logs? Additionlly the full arn of the failing image builder error, without the obfuscated account id, also helps.

**Comment by bacharzin** [comment]
sure, thanks
