### ISSUE TITLE
(3.0.0-3.1.3) AWSBatch - Multi-node Parallel jobs fail if no EBS defined in cluster

### ISSUE THREAD

**Issue by francesco-giordano** [aws/aws-parallelcluster#4011]
### Bug description

When the scheduler of the cluster is awsbatch and a [Multi-node Parallel (MNP)](https://docs.aws.amazon.com/batch/latest/userguide/multi-node-parallel-jobs.html) job is submitted, in case there is no EBS shared volume defined in the cluster, the job will fail. The failure is caused by the requirement of a shared volume to exchange information regarding the nodes involved in the multi node execution.

The MNP job fails with error:
```
Error executing script: Shared directory /NONE does not exist
```
## Affected versions (OSes, schedulers)

* All versions of ParallelCluster >= 3.0.0 are affected when run a multi node parallel job and there is not a EBS defined in the cluster

## Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.1.3)-AWSBatch---Multi-node-Parallel-jobs-fail-if-no-EBS-defined-in-cluster)

**Comment by chenwany** [comment]
[3.1.4](https://github.com/aws/aws-parallelcluster/releases/tag/v3.1.4) version is available on PyPI.
