### ISSUE TITLE
Retry submission on no resource left.

### ISSUE THREAD

**Issue by lletourn** [aws/aws-parallelcluster#4030]
Until https://github.com/aws/aws-parallelcluster/issues/3576 get's resolved, is there a config that can make slurm/parallelcluster retry to create instances until one is available instead of terminating it?

This is problematic especially if that task also has dependencies, then the whole chain of jobs are rejected.

(Example failure message:
Retries
2022-05-09 18:01:44,275 - [slurm_plugin.instance_manager:add_instances_for_nodes] - ERROR - Encountered exception when launching instances for nodes (x1) ['gpu-dy-g4dnxlarge-1']: An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 1): We currently do not have sufficient g4dn.xlarge capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get g4dn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1c, us-east-1d, us-east-1f.

**Comment by hanwen-pcluste** [comment]
Hi lletorn,

The current behavior has retries. When there is an insufficient capacity error, the cluster will keep trying to relaunch compute nodes. 
With ParallelCluster<3.2.0, it keeps retrying. 
With ParallelCluster >=3.2.0, each compute resource is disabled for 10 minutes if insufficient capacity event occurs.
During these retries, the job is re-queued as long as `--no-requeue` option is not used.

According to my understanding, your job failed. Did the job get requeued?

Hanwen,
Thank you!

**Comment by lletourn** [comment]
My job never got requeued. Just to be clear this is not from hitting the limit in my account, this is lack of AWS capacity in us-east1a. I even tried to launch an instance in that region manually from another account and got the error message.

Ran srun on the command line of the head node, got terminating job message, submission failed and right back to command line.

**Comment by lletourn** [comment]
I saw the documentation that says it requeues on NODE_FAIL if no-requeue is set, but this was when using SPOT instances. I haven't found any documentation that talks about ON-DEMAND nodes hitting InsufficientInstanceCapacity.

**Comment by lletourn** [comment]
Forgot to mention I'm running pcluster 3.1.2

**Comment by hanwen-pcluste** [comment]
By default, we allow requeue regardless of SPOT or ON-DEMAND.

Could you provide the command you used for `srun` or `sbatch` and your `/opt/slurm/etc/slurm.conf`?

Thank you!

**Comment by lletourn** [comment]
There you do:
`srun -p gpu --time=04:00:00 -c 4 --pty bash -i`

**Comment by enrico-usai** [comment]
Hi @lletourn 
to have the job requeued, you should use the `sbatch` command. In fact, the `--no-requeue` option is not supported by `srun` command.

> The `srun` command is designed for interactive use, with someone monitoring the output. The output of the application is seen as output of the srun command, typically at the user's terminal. The `sbatch` command is designed to submit a script for later execution and its output is written to a file. [...] Another significant difference is in fault tolerance. Failures involving sbatch jobs typically result in the job being requeued and executed again, while failures involving srun typically result in an error message being generated with the expectation that the user will respond in an appropriate fashion.

Source: [Slurm documentation](https://slurm.schedmd.com/faq.html#sbatch_srun)

Let us know if it helps.
Enrico

**Comment by lletourn** [comment]
Yeah I was trying to get an interactive job to test some things. I didn't try sbatch at that time. I guess that might be it. Thanks for the link @enrico-usai
