### ISSUE TITLE
Build Image command returning an error

### ISSUE THREAD

**Issue by cnvsureshg** [aws/aws-parallelcluster#4032]
Hi Guys,

Trying to launch a cluster with OS called Rocky Linux. For that, trying to create a build-image (in Pcluster) with the custom AMI. For that created a customizable AMI from the Rocky Linux server. 
But while trying to generate a cluster image by using the command build-image facing an issue as below. Along with my error providing the inputs as well. Can someone help here to chase this?

**config file**
Build:
  InstanceType: t2.large
  ParentImage: ami-047ecc1561da9806f

 **Command:** 
With Dry test
```
pcluster build-image -c buildImageConfig.yaml -i ami-g3nm0t --dryrun true
{
  "message": "Request would have succeeded, but DryRun flag is set."
}
```
Without dry test
`
pcluster build-image -c buildImageConfig.yaml -i ami-g3nm0t --dryrun false
`

**Error:**

```

Resource handler returned message: "Error occurred during operation 'SSM execution '81cd3cd0-ef1e-4f94-83fe-fbc6ff477637' failed for image arn: 'arn:aws:imagebuilder:us-west-1:XXXXXX:image/parallelclusterimage-ami-g3nm0t/3.1.3/1' with status = 'Failed' in state = 'BUILDING' and failure message = 'Document arn:aws:imagebuilder:us-west-1:XXXXXXX:component/parallelclusterimage-c5073330-d02a-11ec-9e24-062ddb3f9f15/3.1.3/1 failed!''." (RequestToken: XXXXXXX, HandlerErrorCode: GeneralServiceException)
--

The following resource(s) failed to create: [ParallelClusterImage].

```

**Comment by hanwen-pcluste** [comment]
Hi Venkat,

Unfortunately, ParallelCluster does not support Rocky Linux. ParallelCluster only supports Amazon Linux 2, CentOS7, Ubuntu 18.04 and Ubuntu 20.04.

You can follow the [Troubleshooting and monitoring AMI creation process](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html) to retrieve the logs. We are pretty sure that you have to customize some of the code to make it work.

Thank you,
Hanwen

**Comment by rvencu** [comment]
I am getting the same problem with Ubuntu 18.04

It is true, I am picking up a deep learning AMI used by some colleagues for manual deployments as base AMI.

Will try with the official Ubuntu 18.04 AMI and rebuild the stack if it works

**Comment by cnvsuresh** [comment]
Hi @hanwen-pcluste 
I've tried those steps. Yes it's not supportive. 

When I'm trying the build image with the existing VM getting different Errors. 
Because of this reason unable to create a cluster from a predefined one. When every I want need to set up once the cluster has been created.
