### ISSUE TITLE
Error when pip install pcluster>=3

### ISSUE THREAD

**Issue by ChristianKniep** [aws/aws-parallelcluster#4042]
**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.1.4
 - CloudShell regions: ap-southeast-2, us-east-1

When installing PCluster in CloudShell, I get an error - even though PCluster is installed... 🤷‍♂️ 

```bash
Preparing your terminal...
[cloudshell-user@ip-10-0-131-26 ~]$ Try these commands to get started:
aws help  or  aws <command> help  or  aws <command> --cli-auto-prompt
[cloudshell-user@ip-10-0-131-26 ~]$ sudo pip3 install aws-parallelcluster>=3 --use-feature=2020-resolver -U --no-warn-script-location
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
ERROR: awsebcli 3.20.3 requires botocore<1.24.0,>1.23.41, but you'll have botocore 1.24.46 which is incompatible.
aws-sam-cli 1.46.0 requires Flask~=1.1.2, but you'll have flask 2.0.3 which is incompatible.
[cloudshell-user@ip-10-0-131-26 ~]$ pcluster version
{
  "version": "3.1.4"
}
[cloudshell-user@ip-10-0-131-26 ~]$ 
```

What is the best course of action to install pcluster on CloudShell?

**Comment by lukeseawalker** [comment]
Hello @ChristianKniep,
the package for which you are getting an error (awsebcli) is not a ParallelCluster dependency.
I believe it's something preinstalled by default in the CloudShell Python environment.

I suggest you to follow the [recommended guide](https://docs.aws.amazon.com/parallelcluster/latest/ug/install-v3-virtual-environment.html) to install ParallelCluster in a virtual environment to avoid requirement version conflicts with other pip packages.
