### ISSUE TITLE
Multiple SLURM jobs are being submitted to the same Compute node.

### ISSUE THREAD

**Issue by mohammedmsk** [aws/aws-parallelcluster#4049]
Hello Team,

I am trying to use AWS parallel cluster 3 with nextflow.

I have been able to successfully set it up and get it to work.

But there seems to be an issue with how compute EC2 instances are assigned to slurm jobs.

I have been assuming that every single slurm job submitted runs on a different compute node (EC2 instance), but that does not seem to be the case.

Below you can see a snippet of 8 slurm jobs running but all on the same EC2 instance (This is htop output on that instance):
![image](https://user-images.githubusercontent.com/16212913/169358879-c7fa8bde-080b-4480-970b-1ad29164d9a6.png)

This obviously causes memory issues and all the jobs die.

**Comment by ChrisDowning** [comment]
Hi @mohammedmsk ,

> I have been assuming that every single slurm job submitted runs on a different compute node (EC2 instance), but that does not seem to be the case.

That is possible, but not the default; to give each job its own node, add `--exclusive` to the `sbatch` command/script you use - you can read more about this and other related settings [here](https://slurm.schedmd.com/sbatch.html#OPT_exclusive).

**Comment by mohammedmsk** [comment]
Ok. That should resolve the issue. Where is the slurm config file located if I want to add this option as a default to my cluster?

**Comment by mohammedmsk** [comment]
I figured it out. Thanks a lot for help.

**Comment by joehellmersNOAA** [comment]
@mohammedmsk, Out of curiosity, how did you change the configuration to make it work?

**Comment by mohammedmsk** [comment]
@joehellmersNOAA , So I did not change the slurm configuration as such. I simple updated my nextflow config to include the key word "--exclusive" for all slurm jobs. Hope that helps.

Here is the snipped of nextflow config:

```
process {
  executor = 'slurm'
  withName: '.*' {
    clusterOptions = {"--exclusive"}
  }
}

```
