### ISSUE TITLE
(3.0.0 3.1.3) Unable to create cluster or custom image when using API or CLI with documented user policies

### ISSUE THREAD

**Issue by lukeseawalker** [aws/aws-parallelcluster#4052]
### Bug description

Cluster creation or custom image creation using the ParallelCluster API or CLI fails with the cluster stack in `CREATE_FAILED` status and reason 

```
User: arn:aws:sts::xxx:assumed-role/yyy is not authorized to perform: lambda:TagResource on resource: zzz
```

This happens when creating a cluster or a custom image using the ParallelCluster API from version 3.0.0 to 3.1.3 or any CLI version when the user has an IAM role with the user policies previously documented in the [official doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/iam-roles-in-parallelcluster-v3.html#iam-roles-in-parallelcluster-v3-base-user-policy) before May 17, 2022.

### Root Cause

Starting from Jun 2022, AWS Lambda is enforcing the requirement of the `lambda:TagResource` action policy to perform the creation of a Lambda function deployed through CloudFormation.

### Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.1.3)-Unable-to-create-cluster-or-custom-image-when-using-API-or-CLI-with-documented-user-policies).

**Comment by enrico-usai** [comment]
It has been fixed in 3.1.4 release.
