### ISSUE TITLE
(3.0.0 3.1.4) Unable to perform cluster update when using API or CLI with documented user policies

### ISSUE THREAD

**Issue by lukeseawalker** [aws/aws-parallelcluster#4053]
### Bug description

Cluster updates after changing the LambdaFunctionsRole using the ParallelCluster API or CLI fails with the cluster stack in `UPDATE_FAILED` status and reason

```
User: arn:aws:sts::xxx:assumed-role/yyy is not authorized to perform: lambda:ListTags on resource: zzz
```

This happens when updating the property `LambdaFunctionsRole` during a cluster update using the ParallelCluster API from version 3.0.0 to 3.1.4 or any CLI version when the user has an IAM role with the user policies documented in the [official doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/iam-roles-in-parallelcluster-v3.html#iam-roles-in-parallelcluster-v3-base-user-policy).

### Root Cause

Starting from May 2022, AWS Lambda is enforcing the usage of `lambda:ListTags`, `lambda:TagResource`, and `lambda:UntagResource` actions policy to be able to perform the update of a Lambda function deployed through CloudFormation.

### Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.1.4)-Unable-to-perform-cluster-update-when-using-API-or-documented-user-policies).

**Comment by gmarciani** [comment]
Fix included in [ParallelCluster 3.2.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.2.0)
