### ISSUE TITLE
FSx for Lustre mount failure on cluster creation if UpdateOsPackages:Enabled:true in imagebuilder

### ISSUE THREAD

**Issue by zbarr** [aws/aws-parallelcluster#4057]
ParallelCluster version: 3.1.4

I personally do not have time to fill out this full bug report right now as this feature isn't really even necessary to our build but what happened is exactly what was in the title. The only time this happened was if UpdateOsPackages:Enabled was set to true in imagebuilder. Everything worked totally fine outside outside of that. Sorry for being so brief! Do not hesitate to just close this out if you don't feel like hunting it down yourself.

Happened twice. Output from CloudWatch:
`---- Begin output of ["mount", "-t", "lustre", "-o", "defaults,_netdev,flock,user_xattr,noatime,noauto,x-systemd.automount", "fs-<redacted>.fsx.us-east-2.amazonaws.com@tcp:/oczhpbmv", "/mnt/fsx"] ----
STDERR: mount.lustre: mount fs-043c863f083c90c07.fsx.us-east-2.amazonaws.com@tcp:/oczhpbmv at /mnt/fsx failed: No such device`

**Comment by lukeseawalker** [comment]
Hello @zbarr,
please provide the build image log. You can find information on how to retrieve it in
https://docs.aws.amazon.com/parallelcluster/latest/ug/cloudwatch-logs-v3.html#cloudwatch-logs-build-images
and 
https://docs.aws.amazon.com/parallelcluster/latest/ug/custom-ami-v3.html doc sections.
The log will help us to understand if the fsx client was installed during the custom image build process.
