### ISSUE TITLE
Adding support for Ubuntu 22.04 images

### ISSUE THREAD

**Issue by JoshOBrien** [aws/aws-parallelcluster#4060]
Are there any immediate plans to add the option of using Ubuntu 22.04 instances by setting `Os: ubuntu2204` in the `Image:` section of a cluster configuration file?

Alternatively, is there some currently existing recommended approach to getting Ubuntu 22.04 on the nodes of a cluster set up using AWS ParallelCluster version 3?

**Comment by lukeseawalker** [comment]
Hello @JoshOBrien,
we are tracking this as feature enhancement.

**Comment by coderodyhpc** [comment]
Hello @**lukeseawalker**,
Is there any timeline or information such as target availability 3.1.5 or 3.2 that you can share with us? Thanks.

**Comment by skoloCFD** [comment]
A timeline for this would be really helpful for planning purposes. Nice to sync awspc ubuntu with our other OS switchovers.

**Comment by gns-build-server** [comment]
This is of interest to us as well.

**Comment by ghost** [comment]
Just ran into the incompatibility for ubuntu 22.04.x on a current project.  Is there a plan for when this support will be added?  In the meantime is there a workaround?

**Comment by lletourn** [comment]
This is of interest to us as well.
Related: #4341

**Comment by kmb5482** [comment]
We need this too.

**Comment by tamuanand** [comment]
Would you know if there are plans for Ubuntu 22.04 support?

**Comment by gns-build-server** [comment]
We would be very interested to know this, too!

**Comment by enrico-usai** [comment]
Hi! 
This feature cannot be developed yet due to a [lack of EC2 Image Builder support for this OS](https://docs.aws.amazon.com/imagebuilder/latest/userguide/what-is-image-builder.html#image-builder-os).

Image Builder is a requirement to build official images and to permit the users to build custom images with the `build-image` command.

**Comment by lletourn** [comment]
If that's what it takes, everyone that needs this feature please vote for it:
https://github.com/aws/ec2-image-builder-roadmap/issues/81

**Comment by gns-build-server** [comment]
Thanks @lletourn .  Only 24 "thumbs up" votes on https://github.com/aws/ec2-image-builder-roadmap/issues/81 doesn't feel like a lot.  I worry that without enough support, the Parallelcluster team will not prioritize this.

Everyone reading this, please go and thumbs-up on issue 81, and put a comment to tell AWS why you need 22.04.  We managed to get multi-AZ by showing them how many of their customers needed it -- let's get 22.04 now.

**Comment by lletourn** [comment]
I just received the EOL 18.04 email.

Any chance 22.04 will be ready before May 31st? (ideally a week before to setup and test)
Or are we forced to use 20.04/AmazonLinux and wait until 22.04 comes out and change again?

We were hoping to skip having to setup our cluster twice.

Thanks

"Your account has been identified as having started an instance or continuing to run Ubuntu 18.04 LTS (Long Term Support) instance(s) over the last 6 months. Canonical, publisher of Ubuntu, announced that the Ubuntu 18.04 LTS will reach end of standard support on May 31, 2023 [1].

Ubuntu 18.04 LTS will not receive any security updates from Canonical after May 31, 2023, and it is important to take action either by migrating the Ubuntu 18.04 version to one of the supported LTS versions (for example, Ubuntu 22.04 LTS or Ubuntu 20.04 LTS) [...]"

**Comment by francesco-giordano** [comment]
Hi lletourn, 
Thanks for your heads up. Support for Ubuntu 22.04 is on our roadmap and being actively worked on, however we have not committed to a specific release yet.

**Comment by dreambeyondorange** [comment]
Ubuntu 22 support is now available with 3.7.0!

https://github.com/aws/aws-parallelcluster/releases/tag/v3.7.0
