### ISSUE TITLE
Shared Storage does not use the EFS mount option tls on existing EFS filesystem

### ISSUE THREAD

**Issue by mrgum** [aws/aws-parallelcluster#4073]
Before submitting a new issue, please search through open [GitHub Issues](https://github.com/aws/aws-parallelcluster/issues) and check out the [troubleshooting documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3.html).

Please make sure to add the following data in order to facilitate the root cause detection.

**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.1.4

**Bug description and how to reproduce:**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

When I use an existing EFS filesystem with the configuration

``` yaml
SharedStorage:
  - Name: efs
    StorageType: Efs
    MountDir: /efs
    EfsSettings:
      FileSystemId: "fs-0c6b3373bc86ec3dd"
```

The cluster nodes mount the filesystem directly using NFS4 rather than having the traffic encrypted with stunnel (using the -o tls option)

Adding the "Encrypted: True" option does nothing as that is for creating an encrypted efs

I think either an Option SecureTransport should be added and it should be the default or the default should be to use the tls mount option

**Additional context:**

```
mount | grep nfs4
fs-1234.efs.region.amazonaws.com:/ on /efs type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,timeo=30,retrans=2,sec=sys,clientaddr=10.1.42.187,local_lock=none,addr=10.1.44.38,_netdev)
```

(AWS doc describing how it should be}[https://docs.aws.amazon.com/efs/latest/ug/encryption-in-transit.html]

**Comment by francesco-giordano** [comment]
Hi @mrgum,
thank you for reporting, I'm marking this with the "enhancement" label and forwarding the request to the manager.

Francesco

**Comment by mrgum** [comment]
I think 3.4.0 fixed this. I'll check and close to f it did

**Comment by francesco-giordano** [comment]
Hi mrgum,
Yes has been added from 3.4.0 - 
https://docs.aws.amazon.com/parallelcluster/latest/ug/SharedStorage-v3.html#yaml-SharedStorage-EfsSettings-EncryptionInTransit

Closing the issue.
Thank you.
