### ISSUE TITLE
Add jobID and jobName to dynamo table

### ISSUE THREAD

**Issue by skoloCFD** [aws/aws-parallelcluster#4101]
I noticed the dynamo table created by awspc has the nodeID and instanceID.

Would be convenient if it also had the slurm jobID and jobName as well. Then dynamo could be called to essentially view job information rather than getting it from the head node.

**Comment by chenwany** [comment]
Hi, 
The DynamoDB is used to saving assigned hostnames with instances ids and node name.
These items will be never removed, but will be replaced if there's new instance ids associated with old hostnames.

For getting slurminfo without logging into the cluster, you can use PclusterManager: https://github.com/aws-samples/pcluster-manager, which shows job info via ssm from head node

Thanks
