### ISSUE TITLE
Support for RHEL 8/9

### ISSUE THREAD

**Issue by libhe** [aws/aws-parallelcluster#4120]
Hello AWS-parallelcluster Team,

I am wondering if the AWS-parallelcluster release or future will include a RHEL 8/9 flavor. 

For the current release, the base_os doesn't include RHEL flavor. Since the CML command pcluster build-image  can build a AWS parallelCluster AMI with custom option, is it possible to specify a RHEL ami in custom option to build a custom parallelCluster AMI?

Thanks.

**Comment by hanwen-pcluste** [comment]
Hi Libhe,

Currently, RHEL 8/9 is not supported by ParallelCluster. Neither does the `build-image` command.

I will mark this as a feature request to be considered by our team.

Thank you!
Hanwen

**Comment by libhe** [comment]
Thanks for the information.  Hope ParallelCluster will support RHEL in the future.

**Comment by StefanA1309** [comment]
100% agree ! In order to support a free distro I would suggest Rocky Linux.

As of today (ParallelCluster 3.4.1) you support 7 distros, 4 on x86_64 and 3 on arm64, all of them older than 2.5 years ! This age makes it difficult to integrate PC in an existing environment (esp if you also have to support it, not only 'get the applications to run somehow')

**Comment by pmekhedjian** [comment]
Respectfully, there is a great need for modern Linux OSs that can be provisioned with AWS ParallelCluster for HPC use with up-to-date package sets. 

Oracle Linux 8, Rocky Linux 8, and AlmaLinux 8 are all great candidates for the next generation of ParallelCluster AMIs with EOLs in 2029 and beyond. Aside from the Ubuntu options, we only have Amazon Linux 2 and CentOS 7 for RPM compatibility. Both are EOL next year and the HPC community requires other RHEL-compatible options. 

If RHEL 8/9 are complicated by subscription snags, please consider support for Oracle 8, Rocky 8, or Alma 8. Thank you!

**Comment by enrico-usai** [comment]
RHEL 8 is now supported! https://github.com/aws/aws-parallelcluster/releases/tag/v3.6.0
