### ISSUE TITLE
How did slurm perform cpu/mem settings?

### ISSUE THREAD

**Issue by wttat** [aws/aws-parallelcluster#4123]
- AWS ParallelCluster version [e.g. 3.1.1]:3.1.3
 - Cluster name: ngs-ubuntu1804
 

```
{
  "creationTime": "",
  "headNode": {
    "launchTime": "",
    "instanceId": "i-0b4654743d7caabd5",
    "publicIpAddress": "",
    "instanceType": "m5.xlarge",
    "state": "running",
    "privateIpAddress": "10.0.6.78"
  },
  "version": "3.1.3",
  "clusterConfiguration": {
    "url": ""
  },
  "tags": [
    {
      "value": "3.1.3",
      "key": "parallelcluster:version"
    }
  ],
  "cloudFormationStackStatus": "UPDATE_COMPLETE",
  "clusterName": "ngs-ubuntu1804",
  "computeFleetStatus": "RUNNING",
  "cloudformationStackArn": "arn:aws-cn:cloudformation:cn-northwest-1:405621504724:stack/ngs-ubuntu1804/bbb0b4e0-dcc9-11ec-8350-02b6daf3d0a4",
  "lastUpdatedTime": "2022-06-19T05:49:55.822Z",
  "region": "cn-northwest-1",
  "clusterStatus": "UPDATE_COMPLETE"
}
```

I have read this issue to set slurm mem limit:https://github.com/aws/aws-parallelcluster/issues/2198

However, I am curious about the logic in my test of compute node r5.2x(8c64g):
If SelectTypeParameters=CR_CPU by default：
We can saw that:

1. We cannot allocate job by mem.
2. First slurm could allocate job 83,84(cores=1)  to same node2.
3. Then slurm allocate job 85,86(cores=4)  to different node 11,15.
4. Then slurm allocate job 87,88(cores not set), to the same node2 as job 83 and 84.
5. Finally slurm allocate job 89,90(cores=3) to the same node2 as job 85 and 86

Question :
- Max multiplex is （8-1=7）cores, is that true?
- if cores not set,default core=1,mem max 4g, is that true?

![Image](https://user-images.githubusercontent.com/29791466/174610531-3ae2ce7d-9458-4db2-ae62-5c30b2ffbafe.jpg)

If I changed SelectTypeParameters to CR_CPU_Memory and slurm_parallelcluster_<PARTITION_NAME>_partition.conf as the issus describe
We can saw that:

1. First slurm could allocate job 76,77(mem=2G)  to same node2.
2. Then slurm could allocate job 78,79(cpu=1,mem=2G)  to same node2.
3. Finally slurm allocate job 80,81(cpu=1) to total different node11.15 ???

![Image (1)](https://user-images.githubusercontent.com/29791466/174612565-05a8c9c9-08c0-4e6c-a956-076ff34dea06.jpg)

Question :

- Why would 3. happened? I understand this may because of SelectTypeParameters=CR_CPU_Memory, but it should allow me to allocate job by cpu?

**Comment by demartinofra** [comment]
Hi believe the reason is that when you enable `CR_CPU_Memory` and you don't specify memory requirements (e.g. with `--mem`) at job submission time, Slurm defaults to all the memory of the node. You can control this default with other config settings such as [DefMemPerCPU](https://slurm.schedmd.com/slurm.conf.html#OPT_DefMemPerCPU)

**Comment by wttat** [comment]
> Hi believe the reason is that when you enable `CR_CPU_Memory` and you don't specify memory requirements (e.g. with `--mem`) at job submission time, Slurm defaults to all the memory of the node. You can control this default with other config settings such as [DefMemPerCPU](https://slurm.schedmd.com/slurm.conf.html#OPT_DefMemPerCPU)

After I set SelectTypeParameters=CR_CPU_Memory and DefMemPerCPU=8000 at the same time, 
I could set cpu/mem/(cpu+mem) for the job.

Thanks.
