### ISSUE TITLE
Nvidia driver issues on compute nodes

### ISSUE THREAD

**Issue by jlanzarotti** [aws/aws-parallelcluster#4127]
Hi, I'm getting issues with the NVIDIA driver using compute instances `g4dn.2xlarge` with  `Os: ubuntu2004` on pcluster 3.1.4 

```
ubuntu@ip-10-0-2-5:~$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  470.103.01  Thu Jan  6 12:10:04 UTC 2022
GCC version:  gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
ubuntu@ip-10-0-2-5:~$ sudo dmesg | tail -4
[  263.729759] NVRM: API mismatch: the client has the version 470.129.06, but
               NVRM: this kernel module has the version 470.103.01.  Please
               NVRM: make sure that this kernel module and all NVIDIA driver
               NVRM: components have the same version.
ubuntu@ip-10-0-2-5:~$ nvtop
Impossible to initialize nvidia nvml : Driver/library version mismatch

```
 
Any ideas what it can be? Seems some packages are being updated and breaks the driver setup.

**Comment by jlanzarotti** [comment]
Running `sudo apt-get install nvidia-driver-470` I get the drivers back, updating the kernel module to 470.129.06

**Comment by lukeseawalker** [comment]
Hello @jlanzarotti,
can you please provide the AMI id?

I tried with official PCluster 3.1.4 AMI `aws-parallelcluster-3.1.4-ubuntu-2004-lts-hvm-x86_64-202205121006` and I'm not able to reproduce

```
ubuntu@ip-172-31-5-96:~$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  470.103.01  Thu Jan  6 12:10:04 UTC 2022
GCC version:  gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

ubuntu@ip-172-31-5-96:~$ sudo dmesg | grep NVRM
[   18.481814] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  470.103.01  Thu Jan  6 12:10:04 UTC 2022
```

I suspect that the installation of `nvtop` package, which is not provided by default, breaks the driver installed in the official PCluster AMI.

Thanks,
L

**Comment by lukeseawalker** [comment]
I confirm that the installation of the `nvtop` package breaks the installation of the `470.103.01` driver because some of its dependencies override the files under

```
/usr/lib/x86_64-linux-gnu/libnvidia*
```

so you should either
* install nvtop which is compatible with `470.103.01`
* update the driver to `470.129.06`

**Comment by jlanzarotti** [comment]
Thanks for the investigation! 
I had a hunch that could be that, but I though “how a monitor tool can break your drivers”… oh Murphy
