### ISSUE TITLE
Running 'sacctmgr' slurm command in headnode throws an error

### ISSUE THREAD

**Issue by ipraveen3** [aws/aws-parallelcluster#4159]
**Description:**
Running `sacctmgr` slurm commands like `sacctmgr list cluster`  in headnode gives the following error:
You are not running a supported accounting_storage plugin
Only 'accounting_storage/slurmdbd' is supported.

**Screenshot:**
![error_msg](https://user-images.githubusercontent.com/58859046/176966857-1657f96e-f842-4c6a-b32e-a5304251133c.png)

Please let me know if I have to do any setup before I run this command or how I can resolve this.
Do I need to setup mysql with the slurm in order to do this? or the Dynamodb can handle it.

**How to reproduce:**
1. Create a cluster using the below mentioned configuration file.
[hello-world.txt](https://github.com/aws/aws-parallelcluster/files/9031478/hello-world.txt)
VPC uses the 'Head node in a public subnet and compute fleet in a private subnet' configuration
`pcluster create-cluster --cluster-name hello-world --cluster-configuration hello-world.yaml`
2. Log in to the head-node
`pcluster ssh --cluster-name hello-world -i /path/to/keyfile.pem`
3. Run the following command
`sacctmgr`

I also tried running `/opt/slurm/bin/sacctmgr list cluster` which gave the same error
![err_woith_opt_path](https://user-images.githubusercontent.com/58859046/176969545-f982635f-cc98-47b4-908c-9ff220134696.png)

Running other sacctmgr commands like `sacctmgr show clusters` ,  `sacctmgr add resource ....` also gives the same error.

**Required Info:**

 - AWS ParallelCluster version : 3.1.4
 - Full cluster configuration without any credentials or personal data:
[hello-world.yaml](https://github.com/aws/aws-parallelcluster/files/9031393/hello-world.txt)
 - Cluster name: hello-world
 - Output of `pcluster describe-cluster` command :
[describe-cluster-output.txt](https://github.com/aws/aws-parallelcluster/files/9031512/describe-cluster-output.txt)
 - [Optional] Arn of the cluster CloudFormation main stack: arn:aws:cloudformation:us-east-1:383598844771:stack/hello-world/db4c7280-f96b-11ec-9894-0aeac1e7b445

**Logs:**
`/var/log/parallelcluster/clustermgtd`:
[clustermgtd.log](https://github.com/aws/aws-parallelcluster/files/9031439/clustermgtd.log)

`/var/log/cloud-init.log`:
[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/9031459/cloud-init.log)

`/var/log/chef-client.log`:
[chef-client.log](https://github.com/aws/aws-parallelcluster/files/9031468/chef-client.log)

Let me know if you need any other information

**Comment by enrico-usai** [comment]
Hi @ipraveen3 

the Slurm accounting feature is not present on ParallelCluster. This is something "optional" you have to configure manually.

You can follow [this Blog Post](https://aws.amazon.com/blogs/compute/enabling-job-accounting-for-hpc-with-aws-parallelcluster-and-amazon-rds/) with detailed instructions.

Let me know if it helps.

**Comment by ipraveen3** [comment]
Thanks it helped. I was able to setup and run sacctmgr and other commands.
