### ISSUE TITLE
 clustermgtd closes spot node after 6 hours (no corresponding instance in EC2)

### ISSUE THREAD

**Issue by drleo93** [aws/aws-parallelcluster#4172]
Dear aws-parallelcluster developers, 

I am facing an issue that I hope you can help me with, I apologize in advance in case I am mistaken or I have not provided all required information (this is my first Issue on github).

**Required Info:**
 - AWS ParallelCluster version: "3.1.4"
 - Full cluster configuration without any credentials or personal data.
[cluster-config.txt](https://github.com/aws/aws-parallelcluster/files/9053347/cluster-config.txt)

The custom actions refer to those provided in: https://aws.amazon.com/it/blogs/hpc/using-spot-instances-with-aws-parallelcluster-and-amazon-fsx-for-lustre/ for more controlled unmounting of the fsx in case of spot instance interruption.

 - Cluster name: "clus4c"

**Bug description**
The cluster is configured for using spot instances as compute nodes that need to run a job for several hours (only on one node). 
For the first 6 hours (exact and repeated value) the job runs seamlessy, then the job is interrupted and re-submitted. 
Initially, I believed the instance was reclaimed by aws, but after checking in the logs, it seems that clustermgtd health checks are failed and the node is powered down.

For issues with Slurm scheduler, please attach the following logs:
*  `/var/log/parallelcluster/clustermgtd`
[clustermgtd.txt](https://github.com/aws/aws-parallelcluster/files/9053815/clustermgtd.txt)

(this is the log section pertaining the first run of the job, that is repeated every time the job gets requeued)

Thank you in advance for your support.

**Comment by enrico-usai** [comment]
Hi @drleo93 

from the `/var/log/parallelcluster/slurm_resume.log` in the head node you should be able to retrieve the instance id of the instance associated to the ip 10.0.1.171, that is the one listed in the clustermgtd as unhealthy : `IDLE+CLOUD+NOT_RESPONDING`.

Could you please share the instance id of this instance and then try to retrieve the logs of this instance from CloudWatch?
See https://docs.aws.amazon.com/parallelcluster/latest/ug/cloudwatch-logs-v3.html for instructions where to find the Logs.

Thanks

**Comment by drleo93** [comment]
Hi @enrico-usai  

I have followed your instructions and this is the file containing the logs from CloudWatch, related to that instance:
[log-events-viewer-result.csv](https://github.com/aws/aws-parallelcluster/files/9065224/log-events-viewer-result.csv)

Thanks,
Leo

**Comment by enrico-usai** [comment]
Can you share the instance id too?
Anyway from your log I can see the message:
```
Instance is getting terminated. Clean and unmount '/fsx' ...
```

This is coming from the [`spot-daemon.sh`](https://github.com/aws-samples/parallelcluster-spot-fsxlustre/blob/main/spot-daemon.sh) script that is checking for the existence of the `http://169.254.169.254/latest/meta-data/spot/instance-action` metadata to understand if the instance is retired by AWS and according to the log, this is the case.


As you can read in [Spot documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html):
> If your Spot Instance is marked to be stopped or terminated by Amazon EC2, the instance-action item is present in your [instance metadata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html). Otherwise, it is not present.


Then, the clustermgtd is just discovering that the instance is no longer available and reporting it in the logs:
``` 
no corresponding instance in EC2 for node queue1-dy-compute-1(10.0.1.171)
```

So I'd say you're just facing a spot interruption.
Let me know if it helps.

**Comment by drleo93** [comment]
I'm sorry, of course: i-06c8b322bdf5befa4.

The spot interruption by aws was the same assumption that I initially made, but I could not find any connection between this and the exact frequency of the event. 
Additionally, the spot requests connected with the instances were in the state: 'instance-terminated-by-user'.

**Comment by enrico-usai** [comment]
Hi @drleo93 by looking at the details of the spot-daemon.sh script we found there is an issue in the logic:

```
    if [[ "$HTTP_CODE" -eq 401 ]] ; then
        # Refreshing Authentication Token
        TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 30")
    elif [[ "$HTTP_CODE" -ne 200 ]] ; then
```
source: https://github.com/aws-samples/parallelcluster-spot-fsxlustre/blob/main/spot-daemon.sh


should be instead:
```
    if [[ "$HTTP_CODE" -eq 401 ]] ; then
        # Refreshing Authentication Token
        TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 30")
        continue
    elif [[ "$HTTP_CODE" -ne 200 ]] ; then
```
Source: https://docs.aws.amazon.com/fsx/latest/LustreGuide/working-with-ec2-spot-instances.html

We created a GitHub issue in aws-samples to fix the script: https://github.com/aws-samples/parallelcluster-spot-fsxlustre/issues/1

So to fix your issue you just need to add the `continue` keyword in the refreshing authentication token branch.

Enrico

**Comment by drleo93** [comment]
Hi @enrico-usai 
thank you very much for your support, I am going to update the spot-daemon.sh script and close this issue.

Best regards,
Leonardo
