### ISSUE TITLE
At pcluster installation on AL2 there is a missing dependency

### ISSUE THREAD

**Issue by rvencu** [aws/aws-parallelcluster#4180]
**Required Info:**
 - AWS ParallelCluster version 3.1.4:

**Bug description and how to reproduce:**
Trying to install on AL2
```
python3 -m pip install aws-parallelcluster --upgrade --user --quiet
ERROR: Could not find a version that satisfies the requirement aws-cdk.aws-globalaccelerator==1.163.0 (from aws-cdk.aws-route53-targets==1.163.0->aws-cdk.aws-ecs==1.163.0->aws-cdk.aws-batch!=1.153.0,~=1.137->aws-parallelcluster) (from versions: 1.42.0, 1.42.1, 1.43.0, 1.44.0, 1.45.0, 1.46.0, 1.47.0, 1.47.1, 1.48.0, 1.49.0, 1.49.1, 1.50.0, 1.51.0, 1.52.0, 1.53.0, 1.54.0, 1.55.0, 1.56.0, 1.57.0, 1.58.0, 1.59.0, 1.60.0, 1.61.0, 1.61.1, 1.62.0, 1.63.0, 1.64.0, 1.64.1, 1.65.0, 1.66.0, 1.67.0, 1.68.0, 1.69.0, 1.70.0, 1.71.0, 1.72.0, 1.73.0, 1.74.0, 1.75.0, 1.76.0, 1.77.0, 1.78.0, 1.79.0, 1.80.0, 1.81.0, 1.82.0, 1.83.0, 1.84.0, 1.85.0, 1.86.0, 1.87.0, 1.87.1, 1.88.0, 1.89.0, 1.90.0, 1.90.1, 1.91.0, 1.92.0, 1.93.0, 1.94.0, 1.94.1, 1.95.0, 1.95.1, 1.95.2, 1.96.0, 1.97.0, 1.98.0, 1.99.0, 1.100.0, 1.101.0, 1.102.0, 1.103.0, 1.104.0, 1.105.0, 1.106.0, 1.106.1, 1.107.0, 1.108.0, 1.108.1, 1.109.0, 1.110.0, 1.110.1, 1.111.0, 1.112.0, 1.113.0, 1.114.0, 1.115.0, 1.116.0, 1.117.0, 1.118.0, 1.119.0, 1.120.0, 1.121.0, 1.122.0, 1.123.0, 1.124.0, 1.125.0, 1.126.0, 1.127.0, 1.128.0, 1.129.0, 1.130.0, 1.131.0, 1.132.0, 1.133.0, 1.134.0, 1.135.0, 1.136.0, 1.137.0, 1.138.0, 1.138.1, 1.138.2, 1.139.0, 1.140.0, 1.141.0, 1.142.0, 1.143.0, 1.144.0, 1.145.0, 1.146.0, 1.147.0, 1.148.0, 1.149.0, 1.150.0, 1.151.0, 1.152.0, 1.153.0, 1.153.1, 1.154.0, 1.155.0, 1.156.0, 1.156.1, 1.157.0, 1.158.0, 1.159.0, 1.160.0, 1.161.0, 1.162.0)
ERROR: No matching distribution found for aws-cdk.aws-globalaccelerator==1.163.0 (from aws-cdk.aws-route53-targets==1.163.0->aws-cdk.aws-ecs==1.163.0->aws-cdk.aws-batch!=1.153.0,~=1.137->aws-parallelcluster)
```

**Comment by rvencu** [comment]
/home/ec2-user/.local/bin/pcluster create-cluster --cluster-name hpc-1click-prod-v2 --cluster-configuration config.us-east-1.yaml --rollback-on-failure false --wait
bash: /home/ec2-user/.local/bin/pcluster: No such file or directory

**Comment by enrico-usai** [comment]
Hi @rvencu ,

I'm able to reproduce the issue. We'll check into this. 

Anyway I was able to go ahead by installing ParallelCluster cli in a virtual environment as recommended in [our documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/install-v3-virtual-environment.html).

Could you please follow these steps to see if they unblock you?

I saw that the version 1.163.0 of [aws-cdk.aws-globalaccelerator](https://pypi.org/project/aws-cdk.aws-globalaccelerator/#history) has been released today.
Maybe there is something conflicting with the packages installed by default in the Amazon Linux instances and installing the CLI in a virtual environment will avoid the issue.

Let me know if it helps.

**Comment by enrico-usai** [comment]
An alternative to unblock the installation is to execute the following steps:

``` 
python3 -m pip install aws-cdk.aws-ecs==1.155.0
python3 -m pip install aws-cdk.aws-route53-targets==1.155.0
python3 -m pip install aws-cdk.aws-batch==1.155.0
python3 -m pip install aws-parallelcluster --upgrade --user --quiet
```

Enrico

**Comment by rvencu** [comment]
Great. I'll try the workarounds, thank you_

**Comment by rvencu** [comment]
I tried second workaround with v 1.155 but not lucky when I tried to create a cluster

{
  "message": "module 'aws_cdk.aws_ecr_assets' has no attribute 'Platform'"
}

**Comment by EddyMM** [comment]
Hey @rvencu,
Could you retry running the installation again?
`python3 -m pip install aws-parallelcluster --upgrade --user --quiet`
We were able to reproduce the issue last week but after a patch release of CDK late a few days ago, the issue is no longer reproducible.

**Comment by rvencu** [comment]
Yes, it is fixed. thank you
