### ISSUE TITLE
Placement group usage

### ISSUE THREAD

**Issue by rvencu** [aws/aws-parallelcluster#4215]
Hi, regarding Placement Groups inside the pcluster config file, I want to understand more about the relationship with the

1. instances placed on the same spline and available via targeted capacity reservations. are they in the same placement group already, or does enabling this in the config still make sense?
2. Will the majority of compute nodes being set as static (spin them up permanently since the capacity reservation is paid for anyway) allow placement groups to be used at the job level?
3. is there any strategy at job definition to max out the EFA bandwidth for that specific job?

**Comment by chenwany** [comment]
Hi @rvencu 
1. As far as I understood, ODCR placed on the same spline are Configurable ODCR. They target a spine. Since instances are already in the same network spines, it will be similar to PlacementGroup. `PlacementGroup` option can not be specified in cluster configuration, or there will be insufficient capacity error. It doesn't make sense and we shouldn't use placement group in this case
2. Do you mean to change the placement group of instances when job are running? Since static nodes are already spun up, they are already launched from some droplets and their location can not be changed when running job, unless they are replaced.
3. Let me ask the EFA team before get back to you on this question

**Comment by wzamazon** [comment]
> Is there any strategy at job definition to max out the EFA bandwidth for that specific job?

Sorry, I do not quite understand the question. By "job", do you mean slurm job?

**Comment by rvencu** [comment]
Thank you, yes I mean a slurm batch with distributed computing in the workload.

What worries me is that while I have five different targeted ODCR, all in the same az, it is unclear to me if I should create a single giant cluster with all of them added to the ODCR Group or if it would be better to create five different clusters, one for each ODCR, so that the above placement happens for sure.

In other words, five targeted ODCR in the same az/datacenter belong to a single spine, or it might happen for them to belong to different spines?

Making a single or multiple clusters account for a strategy in my mind. As we observe EFA speed decay with the increasing number of nodes, picking instances from different spines in the mixed scenario could be a reason.

**Comment by rvencu** [comment]
> 2\. Do you mean to change the placement group of instances when job are running? Since static nodes are already spun up, they are already launched from some droplets and their location can not be changed when running job, unless they are replaced.

Having a giant cluster maybe by choosing nodes from a specific ODCR at job time once we know the requested number. Of course, in case there are multiple spines instead of only one.

**Comment by wzamazon** [comment]
> five targeted ODCR in the same az/datacenter belong to a single spine, or it might happen for them to belong to different spines?

I see. I think you questions are two folded:

1. whether you nodes in 5 different ODCRs are on multiple spines.

I believe your account manager who help you setup ODCR will be able to get the information for you.

2. If the nodes are indeed on different spines, is there a way to make a slurm job configuration that it  will use nodes on same spine.

@chenwany please correct me if I am wrong, but I do not think aws-parallelcluster has this information (whether two nodes are on same spine), therefore slurm will not have this information either.

**Comment by chenwany** [comment]
Thanks @wzamazon!
>1. whether you nodes in 5 different ODCRs are on multiple spines.

Yeah I agree with @wzamazon on this. You will need to check with the account manager to confirm or request to change the spines of the ODCR
> 2.If the nodes are indeed on different spines, is there a way to make a slurm job configuration that it will use nodes on same spine.

If you are using run-instances override, you can create multiple resource groups for multiple ODCRs. Run-instances override is on compute resources level. So you can either specify different ODCRs for different compute resources within the same queue or use multiple queues.
When submitting slurm sbatch jobs, you can add `-C` constrain to specify the compute resource name to always use nodes from the specified compute resource. If you put them in different queues, you can specify the queue when submitting jobs.

Thanks

**Comment by rvencu** [comment]
Great. This answer my question and I know now what to do. 

Thank you

**Comment by chenwany** [comment]
Cool! I am going to close the issue if you don't have further questions.
Thank you!
