### ISSUE TITLE
slurm.conf cluster name should be populated with the cluster name from pcluster create command

### ISSUE THREAD

**Issue by rvencu** [aws/aws-parallelcluster#4218]
At this time it seems it is hardcoded as `parallelcluster`. Since multiple clusters may coexist in the same AWS account it would make sense to diferentiate them in `slurm.conf` as well.

this is helpful while using various prolog/epilog scripts where there is env variable `SLURM_CLUSTER_NAME` which matches the value from `slurm.conf`

Maybe you wonder what the use case would be: we can keep things in attached fsx for each cluster and supposedly we use the same fsx for more than one, we would need separate folders to keep assets in, hence using cluster name dependent folders it helps for isolation. Since it is hard to submit custom variables into prolog/epilog scripts using this one makes a lot of sense

**Comment by chenwany** [comment]
Thank you for the feature request! I marked it as a feature request and shared it with our PM.

**Comment by lukeseawalker** [comment]
Slurm ClusterName is now set in [PCluster version 3.3.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.3.0). The change was done to support Slurm accounting feature
