### ISSUE TITLE
(3.0.0-3.1.4) ParallelCluster API Stack Upgrade Fails for ECR resources

### ISSUE THREAD

**Issue by EddyMM** [aws/aws-parallelcluster#4220]
### Bug description

Upgrading the CloudFormation stack for the ParallelCluster API from one version to another (within the versions in reported range) is going to fail with the following error messages for these reported resource IDs:

* *EcrImagesRemover:*
```
UPDATE_FAILED:
Received response status [FAILED] from custom resource. 
Message returned: See the details in CloudWatch Log Stream: ...
```
* *EcrImage:*
```
UPDATE_FAILED:  Resource creation cancelled
```
This is preventing customers from upgrading their ParallelCluster API stacks from one version to another.

### Root Cause

The *EcrImageDeletionLambda* IAM Role also has a policy that only matches an ImagePipeline resource found in the current API Stack. This makes it unable to use the ImagePipeline resource of the new API stack.

### Mitigation:

For more details and the mitigation strategy, use this wiki: [(3.0.0 3.1.4) ParallelCluster API Stack Upgrade Fails for ECR resources
](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.1.4)-ParallelCluster-API-Stack-Upgrade-Fails-for-ECR-resources)

**Comment by gmarciani** [comment]
Issue fixed in [ParallelCluster 3.2.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.2.0)
