### ISSUE TITLE
[sqswatcher:_process_sqs_messages] Failed when processing event EventType.ADD for instance Host

### ISSUE THREAD

**Issue by gauravgupta26091987** [aws/aws-parallelcluster#4222]
Hi Team,

Details given below for set up and config -
 - AWS ParallelCluster version [e.g. 2.11.0]: 2.11.4
 - Full cluster configuration without any credentials or personal data.
 - master instance type : t3.xlarge
 - compute instance type : t3.xlarge
 - OS of the machine where parallel cluster in installed and created : Red Hat Enterprise Linux 8.5 (Ootpa).
 - OS for master and compute nodes : Alinux2 AMI.
 - Cluster name: mycluster
 - min count of compute node - 0 
 - max count of compute node - 3 

While executing job in AWS parallel cluster using SGE scheduler , we get below error in sqswatcher log and job remains in qw state. It doesnt move to 'r' state(using qstat). so seems like sqswatcher is not able to add the new compute instance created to host queue. No errors in jobwatcher.

In AWS parallel cluster UG (https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting.html#troubleshooting-failed-launch-and-join-operations) , it says as below but doesnt give further info for troubleshooting this.
"If compute nodes failed to join the scheduler configuration despite successful setup, check the /var/log/sqswatcher log to see whether sqswatcher processed the event. These issues in most cases are because sqswatcher didn’t process the event."

One of issues here in GIT (https://github.com/aws/aws-parallelcluster/issues/4120) says about base OS not supported for RHEL. so is this OS mismatch causing this because Cluster is installed in RHEL8 linux machine whereas master/compute node are on alinux2 ? or any other issue ?

As mentioned in AWS parallel user guide that no further support will be provided for AWS parallel cluster <= 2.11.4 with SGE/Torque schedulers. so Bit clueless now how to proceed further.

Please let me know if any further information required on the same .

**Comment by gauravgupta26091987** [comment]
Quick update , tried with Cluster machine as alinux2 ami without redhat to make sure no platform mismatch between cluster and head/compute nodes and its the same error in sqswatcher logs.
Also I tried running qconf separately as "/opt/sge/bin/lx-amd64/qconf -ah ip-10-78-14-77" and it says hostname not found. 
When run as "/opt/sge/bin/lx-amd64/qconf -ah 10.78.14.77" then it says permission denied for ec2-user and it needs to have manager to execute this command which means it recognizes the IP. 
so is it something to do with EC2 hostname getting used in qconf command which it is not able identify or again something else ?

**Comment by gauravgupta26091987** [comment]
This Issue was fixed by changing the hostname type to Resource name instead of IP name while launching the aws ec2 instance for installing parallel cluster. Probably was due to DNS name was not getting resolved.

**Comment by gauravgupta26091987** [comment]
Unfortunately , That change did not fix , not sure how it worked before and now getting the same error in sqswatcher logs.

2022-07-26 11:13:28,901 INFO [sge_commands:add_hosts_to_group] Adding  to @allhosts group
2022-07-26 11:13:28,901 INFO [sge_commands:add_host_slots] Adding  to all.q queue
2022-07-26 11:13:28,901 ERROR [sqswatcher:_process_sqs_messages] Failed when processing event EventType.ADD for instance Host(instance_id='i-05c494d2944e74ee2', hostname='ip-10-78-14-114', slots='1', gpus=0)
2022-07-26 11:13:28,902 ERROR [sqswatcher:_process_sqs_messages] Deleting failed event EventType.ADD from queue: {"Type" : "Notification", "Message" : "{\"StatusCode\":\"Complete\",\"Description\":\"Succesfully launched i-05c494d2944e74ee2\",\"Event\":\"parallelcluster:COMPUTE_READY\",\"EC2InstanceId\":\"i-05c494d2944e74ee2\",\"Slots\":\"1\",\"LocalHostname\":\"ip-10-78-14-114.corp.novocorp.net\",\"EC2InstanceType\":\"t2.micro\"}"}

due to above error, since it doesnt find any compute node in allhosts group and all.q queue , it continues to terminate current compute node and start a new instances , so seems like a loop of terminating and starting instances due to above error. please guide on this.

**Comment by chenwany** [comment]
Hi @gauravgupta26091987 ,
If I understand correctly, since you are able to install ParallelCluster on Red Hat Enterprise Linux 8.5, create a cluster successfully and log into the cluster to submit jobs, I believe it is not the issue with cluster installation on your OS.
The OS specified in the cluster configuration is Alinux2 doesn't need to be aligned with the OS where you install ParallelCluster. 
Are you using `custom_ami` in cluster configuration?
Could you share your cluster configuration without any credentials or personal data and logs of the cluster?
See here for how to retrieve logs: https://github.com/aws/aws-parallelcluster/wiki/Creating-an-Archive-of-a-Cluster's-Logs
Could you check if there's failure in the logs of the failure instances `i-05c494d2944e74ee2` and i-0832a669cdeb067c4' in cloudwatch log? 
Thanks

**Comment by gauravgupta26091987** [comment]
Hi @chenwany ,

No, I'm not using cluster_ami option and just using the below tutorial to get started with SGE scheduler.
https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_01_hello_world.html

Here is cluster configuration and attached logs which I directly pulled from cloud watch logs and not using the script you provided as I dont have bucket for logs.

[aws]
aws_region_name = eu-central-1

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[global]
cluster_template = default
update_check = true
sanity_check = true

[cluster default]
key_name = <Key name>
scheduler = sge
master_instance_type = t2.micro
base_os = alinux2
vpc_settings = default
compute_instance_type = t2.micro
max_queue_size = 3

[vpc default]
vpc_id = <VPC ID>
master_subnet_id = <SUBNET ID>
use_public_ips = false
vpc_security_group_id = <Security Group Id>

[cloud-init.csv](https://github.com/aws/aws-parallelcluster/files/9195188/cloud-init.csv)
[cloud-init-output.csv](https://github.com/aws/aws-parallelcluster/files/9195189/cloud-init-output.csv)
[jobwatcherlogs.csv](https://github.com/aws/aws-parallelcluster/files/9195190/jobwatcherlogs.csv)
[Nodewatcherlogs.csv](https://github.com/aws/aws-parallelcluster/files/9195191/Nodewatcherlogs.csv)
[sqswatcherlogs.csv](https://github.com/aws/aws-parallelcluster/files/9195192/sqswatcherlogs.csv)
[system-messages.csv](https://github.com/aws/aws-parallelcluster/files/9195195/system-messages.csv)

I still see the same error in sqswatcher :-
ERROR [sqswatcher:_process_sqs_messages] Failed when processing event EventType.ADD for instance Host(instance_id='i-0eb82b76c31718fda', hostname='ip-10-78-14-104', slots='1', gpus=0)

Error from Nodewatcher :-
2022-07-27   04:17:05,425 ERROR [utils:_run_command] Command   '['/opt/sge/bin/lx-amd64/qstat', '-xml', '-g', 'dt', '-u', '*', '-f', '-l',   'hostname=ip-10-78-14-104']' returned non-zero exit status 1.
--
2022-07-27 04:17:05,425 ERROR   [sge:is_node_down] Failed when checking if node is down with exception   Command '['/opt/sge/bin/lx-amd64/qstat', '-xml', '-g', 'dt', '-u', '*', '-f',   '-l', 'hostname=ip-10-78-14-104']' returned non-zero exit status 1.. Reporting   node as down.

Not sure if this would cause above errors but I use use_elastic_ip as false since I dont have public IP's for the instances as our subnet seems to be the private one and not public one. And as suggested in https://docs.aws.amazon.com/parallelcluster/latest/ug/networking.html VPC needs to have proxy set up for all traffic in case of private subnets and also DHCP options with the correct domain-name for the Region.
please suggest would else could be done to investigate this further.

**Comment by chenwany** [comment]
Thanks for sharing the cluster configuration and logs.
You are right, the error starts from this command: `/opt/sge/bin/lx-amd64/qconf -ah ip-10-78-14-77`. After the compute node launch, it try to add the hostname of the host to SGE trust host lost but failed. 
Just notice `LocalHostname":"ip-10-78-14-114.corp.novocorp.net`. Are you using custom DHCPOptionSet on VPC configuration?
See similar issues here https://github.com/aws/aws-parallelcluster/issues/1192 and https://github.com/aws/aws-parallelcluster/issues/1514

**Comment by chenwany** [comment]
Also, if the subnet specified in the cluster configuration `master_subnet_id =` is a private subnet, it is also require to add `proxy_server` in the config. You can follow the instruction [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/networking.html#:~:text=AWS%20ParallelCluster%20in%20a%20single%20private%20subnet%20connected%20using%20AWS%20Direct%20Connect)

**Comment by gauravgupta26091987** [comment]
Hi @chenwany : I tried to run parallel cluster via my personal account and it works which means that problem is with our VPC set up(DHCP/proxy) to resolve DNS names. I m now checking with our internal AWS core team to make some changes and then will see if this works in our env.
So as of now , i can close this issue and will re-open if required later. thanks for your help and guidance !
