### ISSUE TITLE
Anacrontab and MPI performance degradation

### ISSUE THREAD

**Issue by stefan-vaisala** [aws/aws-parallelcluster#4237]
AWS ParallelCluster version: 3.1.4

**Bug description and how to reproduce:**
On the AmazonLinux 2 PCluster AMI by default, anacrontab runs (`/etc/cron.hourly/0anacron`) to submit and run system-level jobs found in `/etc/anacrontab` . These maintenance jobs run on every cluster head instance or worker instance configured. The hourly cron (`0anacron` script) kicks off at the top of every hour and detects if the required system maintenance jobs have been run yet by some date logic found in `/var/spool/anacron/cron.daily`. If these jobs havent been run today (which is the circumstance for any new cluster instance spun up and the time crosses top of the hour), the jobs are scheduled to run sometime within the next hour with a random delay (see `/etc/anacrontab`).

We have identified that these scheduled jobs, especially those found in `/etc/cron.daily/`, cause significant performance degradation in cluster submitted (SLURM) MPI jobs that are running. On average, the MPI job slowdown is 15-20%. Most of this performance degradation can be attributed to the man-db.cron daily job that is run. Since these scheduled jobs run at random times within the first hour on each worker instance, the degradation is prolonged until each randomly delayed anacron is completed on each worker instance. 

So far, our work around has been to completely comment out the anacrontab file within our post-install procedures to block the anacrontab from running anything:
```
sed 's/^/#/' /etc/anacrontab > /etc/anacrontab.tmp
mv -f --backup /etc/anacrontab.tmp /etc/anacrontab
```

The above works if the cluster instances come up and are configured any time **after** the top of the hour. However, if the cluster instances come up and the top of the hour is crossed before they are completely configured, the above doesnt work as anacron starts before the disabling is complete (e.g., it reads in the original anacrontab file and caches it for use). The anacron will trigger and schedule as soon as the instance is considered up and active and the time crosses the top of the hour, so even running the above as a pre-install procedure likely wouldn't work (perhaps putting something in user-data could possibly work?).

Since we provision and delete clusters daily, we don't need to have these services run, especially if they degrade the performance of our MPI applications. Is it possible for anacrontab to be completely disabled from the PCluster AMI level? The commands run (man-db, logrotate, mlocate) don't seem to be essential, especially for short-lived cluster instances. Also open to alternatives for disabling these processes. We've tried other methods (jobs.deny files, etc.) and the only method that ensures none of the jobs are run is the above post-install solution. Thanks!

**Comment by lukeseawalker** [comment]
Thanks @stefan-maxar,
this was already tracked in https://github.com/aws/aws-parallelcluster/issues/3869.
I will make sure to report this again so it can be better prioritized.

The workaround I would suggest to you is to customize a PCluster AMI with the anacrontab disabled (or even uninstalled).

To customize a PCluster AMI you can follow the [official doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html#how-to-customize-the-aws-parallelcluster-ami-v3).
There are two ways, depending on the needs to be able to automatize the process you can select one over the other:
* first one is to build a PCluster AMI, [see doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html#build-a-custom-aws-parallelcluster-ami-v3). At high level, it requires you to create a build image config where you will have to specify an AMI from where to start the customization process (you can even start from a PCluster AMI of the same version) and then add a [Component](https://docs.aws.amazon.com/parallelcluster/latest/ug/Build-v3.html#Build-v3-Components) to disable or uninstall the service. Then create the AMI with the [pcluster build-image command](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.build-image-v3.html) 
* second method is to modify a PCluster AMI, [see doc](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html#modify-an-aws-parallelcluster-ami-v3). At high level, it requires you to start an instance (outside of a cluster creation) from the AMI you are using for your cluster, modify it and then create a new AMI that you will use as custom AMI for your cluster creation.

Hope this helps,
Luca

**Comment by stefan-vaisala** [comment]
Thanks @lukeseawalker - I couldn't find the ticket but knew this has been brought up before. Ideally, we'd like to stay away from customized PCluster AMIs (would rather not have one more thing to manage/deploy when new versions drop) - but if that is the current workaround, so be it. Regardless, I think reviving the discussion of this and how it might be configured/changed in the official PCluster AMI would be great.

**Comment by francesco-giordano** [comment]
[AWS-ParallelCluster 3.2.1](https://github.com/aws/aws-parallelcluster/releases/tag/v3.2.1) Disable cron job tasks man-db and mlocate, which may have a negative impact on node performance.
