### ISSUE TITLE
parallelCluster Manager 3.2.0 failed on PERSISTENT_2 Lustre creation

### ISSUE THREAD

**Issue by cyberchip-wang** [aws/aws-parallelcluster#4288]
parallelCluster Manager 3.2.0  created with https://www.hpcworkshops.com/03-deploy-pcm/01-deploy-pcm.html does not propagate PerUnitStorageThroughput to the final Cluster Configuration. This caused the "Dry Run" failed. The workaround is  adding a line manually to the Cluster Configuration template file: PerUnitStorageThroughput: 125

Screenshots:
![Storage Properties](https://user-images.githubusercontent.com/111794603/186048178-a6f9514c-d13e-496f-beb3-6a94433f318c.png)
![Dry run error](https://user-images.githubusercontent.com/111794603/186048224-e387d621-b79f-404b-b8cc-7322bcc5eaec.png)

URL for AWS ParallelCluster Manager:
https://k0fymmi0ei.execute-api.us-east-2.amazonaws.com/home

The Lustre section in the Cluster Configuration:
SharedStorage:
  - Name: FsxLustre0
    StorageType: FsxLustre
    MountDir: /shared
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: PERSISTENT_2
      DataCompressionType: LZ4

Dry Run error:

Invalid cluster configuration.
ValidationErrors:
FsxPersistentOptionsValidator: Per unit storage throughput must be specified when deployment type is PERSISTENT_2.

The issue can be reproduced by following the instructions from hpcworkshops:
1) Deploy the Pcluster Manager stack:
https://www.hpcworkshops.com/03-deploy-pcm/01-deploy-pcm.html
2) Create HPC Cluster:
https://www.hpcworkshops.com/06-fsx-for-lustre/01-create-cluster.html
3) Create FSx Lustre:
https://www.hpcworkshops.com/06-fsx-for-lustre/02-create-cluster-fsx.html

**Comment by demartinofra** [comment]
Hi @cyberchip-wang, thanks for the report. Would you mind opening this issue to the pcluster-manager repo https://github.com/aws-samples/pcluster-manager/issues?

Thanks,
Francesco

**Comment by cyberchip-wang** [comment]
Francesco,

I have opened the issue at 
https://github.com/aws-samples/pcluster-manager/issues/274

This ticket will be closed.

Thanks,

Yusong
