### ISSUE TITLE
Image building fails when installing cookbook dependency behind MITM proxy

### ISSUE THREAD

**Issue by cvmeq** [aws/aws-parallelcluster#4316]
Hello ParallelCluster developers,

In our corporate cloud environment we have a MITM proxy monitoring traffic to/from Internet via SSL inspection. This means we need to have the CA of the proxy provider in the CA trust store of the instance in order to reach the Internet, or have tools specifically configured to point to the required certificates.

I'm using `build-image`  with ParallelCluster 3.2.0 and the following configuration file
~~~yaml
Region: eu-central-1
Build:
  InstanceType: c5.xlarge
  SubnetId: subnet-YYY
  ParentImage: ami-ZZZ
  UpdateOsPackages:
    Enabled: true
  SecurityGroupIds:
    - sg-XXX
Image:
  Name: xxx-ami
~~~
where `ami-ZZZ` is an Amazon Linux 2 AMI provided by our corporate IT which has all the require certificates already installed.

The command `build-image` fails when cinc tries to install the [berkshelf ](https://rubygems.org/gems/berkshelf) gem, which is the very first dependence that is needed to manage all following cookbooks:

~~~
2022-09-05T13:52:56.595+02:00
CmdExecution: Stderr: curl --retry 3 -L https://eu-central-1-aws-parallelcluster.s3.eu-central-1.amazonaws.com/archives/cinc/cinc-install-1.1.0.sh | bash -s -- -v 17.2.29
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 25086  100 25086    0     0   268k      0 --:--:-- --:--:-- --:--:--  269k
/opt/cinc/embedded/bin/gem install --no-document berkshelf:7.2.0
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /C=DE/ST=XXX/L=XXX/O=XXX/OU=XXX to your local trusted store
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /C=DE/ST=XXX/L=XXX/O=XXX/OU=XXX to your local trusted store
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /C=DE/ST=XXX/L=XXX/O=XXX/OU=XXX to your local trusted store
ERROR:  Could not find a valid gem 'berkshelf' (= 7.2.0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (https://rubygems.org/specs.4.8.gz)
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /C=DE/ST=XXX/L=XXX/O=XXX/OU=XXX to your local trusted store
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /C=DE/ST=XXX/L=XXX/O=XXX/OU=XXX to your local trusted store

2022-09-05T13:52:56.595+02:00
CmdExecution: ExitCode 2
~~~

The problem here is that cinc is shipped with its own CA certificate bundle installed n `/opt/cinc/embedded/ssl/certs/cacert.pem` which of course do not contain any third-party CA that might be needed. This issue has been addressed by [this PR](https://github.com/aws/aws-parallelcluster-cookbook/pull/1144) in the [aws-parallelcluster-cookbook](https://github.com/aws/aws-parallelcluster-cookbook) project. However that recipe is only applied after berkshelf is installed and in the step described here the certificates being used are still those embedded in cinc.

An obvious solution in the same spirit of the recipe above is to link cinc certificates to the instance certificate bundle before trying to install the gem. Is there any drawback to this? I will sent a PR implementing this, not sure if it's the right approach.

FYI this is somewhat related to [!2916 ](https://github.com/aws/aws-parallelcluster/issues/2916) but not really the same thing.

**Comment by hanwen-pcluste** [comment]
Hi cvmeq,

Are you unblocked?

Thank you,
Hanwen

**Comment by cvmeq** [comment]
Hi @hanwen-pcluste, yes. Closing this. Thank you!
