### ISSUE TITLE
Nvidia drivers and libraries version bump up (like cuda 11.6)

### ISSUE THREAD

**Issue by rvencu** [aws/aws-parallelcluster#4324]
Hi we would like you to bump up the version of nvidia drivers and libraries in pcluster default AMIs if possible, also add the corresponding cudnn version as well.

Is this on the roadmap already? if not what can we do to upgrade these things on our end?

**Comment by hanwen-pcluste** [comment]
Hi Richard,

We are working on upgrading CUDA to 11.7.  For Nvidia driver, we would stay on version 470 because it is the latest long term support version according to https://docs.nvidia.com/datacenter/tesla/drivers/#lifecycle. We will keep up with the latest patch version in the Nvidia driver 470. Does it satisfy your use case?

Thank you,
Hanwen

**Comment by rvencu** [comment]
Yes, it is fine. Currently nvidia-smi claims to support up to 11.4, if the patch can support 11.7 then ok.

When should we expect this to be available?

**Comment by hanwen-pcluste** [comment]
CUDA 11.7 will be included in `pcluster` 3.3.0. However, we don't have a date of the release. Please note that`pcluster` 3.2.0 includes CUDA 11.4.
I marked this issue as a feature request. We will discuss the possibility to include cudnn in the future

Thank you

**Comment by jdeamicis** [comment]
Dear @rvencu, a way to move forward before we release the new version of ParallelCluster would be also to use an AMI with an updated version of CUDA as a base AMI for the `pcluster build-image` functionality. Would this be suitable to you?

**Comment by rvencu** [comment]
Yes, this is also an option can you suggest a good AMI for that? I was refraining to try because I do not want to jeopardize the support for the parallelcluster. If the support is impaired, I would at least want to learn how to install cudnn on the currently supported, official pcluster image of AL2

**Comment by rvencu** [comment]
Hi, because of PyTorch, we would prefer to get cuda 11.6 instead of 11.7, so we can match the PyTorch version.

**Comment by enrico-usai** [comment]
Hi @rvencu,

one alternative simpler than building a custom image with `pcluster build-image` command is to modify an existing ParallelCluster AMI, using the [Modify an AWS ParallelCluster AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html#modify-an-aws-parallelcluster-ami-v3) approach.

You can start from a ParallelCluster base AMI, create an instance, modify the NVIDIA/CUDA packages installed on it and then create a new ami to be used as `CustomAmi` in the cluster config. Details in the provided link.

Please let us know if this solution fits your needs.
Enrico

**Comment by rvencu** [comment]
Yes, this means redeploying the cluster. I will look into it. In the meanwhile, any idea how to install cuDNN 8 for cuda 11.4 without rebooting the compute nodes?

**Comment by enrico-usai** [comment]
According to [official doc](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html) the restart after the cuDNN installation shouldn't be required. It is required only after NVIDIA installation. 

Did you have the possibility to try the installation without the restart? Did you got any issue?

**Comment by rvencu** [comment]
The Amazon Linux 2 has the package most probably available for `yum install`, but I just cannot find it. Need some heads-up for that. I try to avoid the convoluted setup from sources

**Comment by lukeseawalker** [comment]
> Yes, this means redeploying the cluster. 

No need to redeploy the cluster if you need the update only on the compute nodes.

The [CustomAmi](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-Image-CustomAmi) parameters for the compute nodes can be updated through a cluster-update.
Furthermore, in 3.2.0 we improved the flexibility on cluster configuration updates to avoid the stop and start of the entire cluster, by setting the parameter Scheduling/SlurmSettings/QueueUpdateStrategy to select the preferred strategy to adopt for compute nodes.

**Comment by rvencu** [comment]
FYI Amr is using yum install for this 
https://github.com/aws-samples/aws-efa-nccl-baseami-pipeline/blob/master/nvidia-efa-ami_base/nvidia-efa-ml-al2.yml

**Comment by enrico-usai** [comment]
Hi Richard,

to install the packages with yum you have first to register the repository:
```
sudo yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
```
then you can install them with:
``` 
sudo yum -y install cuda-toolkit-11-6 libcudnn8 libcudnn8-devel
```

I'd suggest to test this command in a single instance and verify everything works as expected, before performing the same action in all the nodes.

I tried the following steps:
``` 
# Checked Nvidia SMI output to see installed version
[ec2-user@queue1-dy-queue1-g34xlarge-1 ~]$ nvidia-smi
Fri Sep 23 12:27:50 2022
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |

# listed existing versions
[ec2-user@queue1-dy-queue1-g34xlarge-1 ~]$ ls /usr/local/ | grep cuda
cuda
cuda-11.4

# checked nvcc command execution
[ec2-user@queue1-dy-queue1-g34xlarge-1 ~]$ /usr/local/cuda-11.4/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0

# Configured repo and installed the drivers
[ec2-user@queue1-dy-queue1-t2medium-1 ~]$ sudo yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
[ec2-user@queue1-dy-queue1-t2medium-1 ~]$ sudo yum -y install cuda-toolkit-11-6 libcudnn8 libcudnn8-devel

# Verified there is the new version installed --> note: there are now other versions installed in `/usr/local`
[ec2-user@queue1-dy-queue1-g34xlarge-1 ~]$ ls /usr/local/ | grep cuda
cuda
cuda-11
cuda-11.2
cuda-11.4
cuda-11.6

# Tried to use both nvcc commands and both of them are working
[ec2-user@queue1-dy-queue1-g34xlarge-1 ~]$ /usr/local/cuda-11.6/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
[ec2-user@queue1-dy-queue1-g34xlarge-1 ~]$ /usr/local/cuda-11.4/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0

# Anyway Nvidia-smi output is still pointing to 11.4 
[ec2-user@queue1-dy-queue1-g34xlarge-1 ~]$ nvidia-smi
Fri Sep 23 12:38:31 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
```

It seems that the two versions can co-exists but please double check with PyTorch application.

Let us know if it helps.

Enrico

**Comment by rvencu** [comment]
Install done on the small sandbox cluster. I will have colleagues run their scripts and test

**Comment by rvencu** [comment]
Partial checks: the cuda and cuda-11 folders are symlinks of the cuda-11.6 folder. Some basic jobs work. Still pending more sophisticated tests

**Comment by chenwany** [comment]
thank you for the update!

**Comment by rvencu** [comment]
More tests passed succesfully. While it seems some libraries require updated drivers for cuda11.6 we found ways to circumvent these issues

Here is a gist of installing JAX and run a successful test employing cuda and cudnn installed with the method above:
https://gist.github.com/rom1504/fb3bcafe91effef71b84a9da97cf824c

Also this test worked:
```
import jax
import jax.numpy as jnp
jax.lax.conv(jnp.eye(4)[None, None], jnp.eye(4)[None, None], (1, 1), 'SAME')
```
