### ISSUE TITLE
Slurm is not installed properly in latest ParallelCluster ubuntu2004 image

### ISSUE THREAD

**Issue by xuanus** [aws/aws-parallelcluster#4325]
Create a new ubuntu2004 ParallelCluster with default settings

in the head node

```
ubuntu@ip-:~$ sbatch -v

Command 'sbatch' not found, but can be installed with:

sudo apt install slurm-client



ubuntu@ip-:~$ sinfo

Command 'sinfo' not found, but can be installed with:

sudo apt install slurm-client
```

1. May I know what is the root cause?
2. How to prevent it from happening? Hard code CustomAmi pointing to a ParallelCluster aws official image? Will the aws official ParallelCluster image be deleted in the future?

**Comment by hanwen-pcluste** [comment]
Hi xuanus
> Create a new ubuntu2004 ParallelCluster with default settings

What exact ParallelCluster version are you using? Can you attach the cluster configuration file (without sensitive information)?

> Hard code CustomAmi pointing to a ParallelCluster aws official image?

If you want to use a ParallelCluster official image, `CustomAmi` shouldn't appear in the cluster configuration file. ParallelCluster will automatically pick the official image

> Will the aws official ParallelCluster image be deleted in the future?

The official images won't be deleted

Thank you,
Hanwen

**Comment by hanwen-pcluste** [comment]
I created an ubuntu2004 cluster with ParallelCluster 3.2, and the Slurm was installed properly:
```
$ sbatch --version
slurm 21.08.8-2
```
The Slurm is installed in `/opt/slurm`:
```
$ which sbatch
/opt/slurm/bin/sbatch

$ echo $PATH
/opt/amazon/openmpi/bin/:/opt/amazon/efa/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/aws/bin:/opt/parallelcluster/pyenv/versions/3.7.10/envs/cfn_bootstrap_virtualenv/bin:/opt/parallelcluster/pyenv/versions/3.7.10/envs/awsbatch_virtualenv/bin:/opt/slurm/bin
```
Did you remove the Slurm folder from `PATH`?

**Comment by xuanus** [comment]
After trying to create more pclusters, I found it was due to the head node was not being fully ready yet.
If ssh to the head node after the head node running but before the CF completed, the slurm has not been set in the PATH yet.
The fix is to exit and re-ssh.

Thank you.

**Comment by hanwen-pcluste** [comment]
Sounds good! You can use [desribe-cluster](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.describe-cluster-v3.html) command to see the status of the cluster

Thank you!
