### ISSUE TITLE
Support for Amazon Linux 2022

### ISSUE THREAD

**Issue by PhilipMorrisJones** [aws/aws-parallelcluster#4341]
Hi, 

Do you have a plan to add Amazon Linux 2022 as a base OS? We like Amazon Linux 2 which had an EOL of June 2023. I see that has been pushed back to June 2024 but we'd very much like to be able to use Amazon Linux 2022 sooner than later.

**Comment by jdeamicis** [comment]
Thank you for your message, we will consider this as a feature request.

**Comment by lletourn** [comment]
Related: #4060

**Comment by mrgum** [comment]
Close and concentrate on al2023 #5214 ?

**Comment by PhilipMorrisJones** [comment]
I'm happy with al2023
