### ISSUE TITLE
Support for Ondemand Capacity Reservation to avoid ICE

### ISSUE THREAD

**Issue by tkasuz** [aws/aws-parallelcluster#4342]
I'd like to propose a feature request that will help avoid insufficient capacity error (ICE) when trying to launch dozens of large size instances. Parallel cluster waits a job to start until the given size of the nodes are ready, but it would be wasted if ICE happens. I think that it would better to run ODCR (On-demand Capacity Reservation) when a job get submitted, so that a job causing ICE doesn't need to even provision any instance.

we can call create_capacity_reservation API to check if there is enough capacity in a region to run the give size of the nodes before provisioning On-demand instances. 

> https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_capacity_reservation

**Comment by lukeseawalker** [comment]
Hello @kopkunka55,
thanks for your feedback, I'm marking this as feature request so to be discussed by our team.

**Comment by enrico-usai** [comment]
Added as part of [3.3.0 release](https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.md#330)

> Add support for On-Demand Capacity Reservations and Capacity Reservations Resource Groups.
