### ISSUE TITLE
Which EBS path is shared and private by default

### ISSUE THREAD

**Issue by xuanus** [aws/aws-parallelcluster#4348]
Which EBS path is shared and private by default? I cannot find the related info in the official doc. 

After creating a pcluster with basic config (NO any config for shared storage EBS/EFS...), I found:

**To access the default shared EBS, we need to `cd ~`**
1. ~/* is shared by the head node and compute nodes, right?
2. should we install shared software in ~/ ?
3. I found after installing software in head node, I don't need to export PATH in compute node. May I know how head node and compute nodes shared the PATH env?

**To access the default private EBS, we need to `cd /`**
1. /* is the default private EBS, right?
2. to run each Sbatch job, in the job script we need to cd to / first to download data and process data independently, right?

**What is the best practice in pcluster to**
1. store shared data  / install shared software in shared EBS and shared EFS?
2. store private data / install private software in private EBS?

**Comment by enrico-usai** [comment]
Hi @xuanus let me give a first answer.

The following directories are shared between the nodes by default:
* `/home` - This includes the default user home folder (`/home/ec2_user` on Amazon Linux, `/home/centos` on CentOS, and `/home/ubuntu` on Ubuntu).
* `/opt/intel` - This includes Intel MPI, Intel Parallel Studio, and related files.
* `/opt/slurm` - This includes Slurm Workload Manager and related files. (Conditional, only if `Scheduler: slurm`.)
From: https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3.html#troubleshooting-v3-dirs-must-keep

all the other folders are kept as private.

As suggested in the [Best Practices](https://docs.aws.amazon.com/parallelcluster/latest/ug/best-practices-v3.html#best-practices-cluster-upgrades-v3), if you want to share something, it's better to add an additional EBS volume (or EFS or FSx according to your needs) and install the application/software you want to share there:
- https://aws.amazon.com/efs/when-to-choose-efs/
- https://aws.amazon.com/fsx/when-to-choose-fsx/

Let us know if this answers to your questions.
Enrico
