### ISSUE TITLE
Question about scaling down cluster

### ISSUE THREAD

**Issue by rahul003** [aws/aws-parallelcluster#4366]
The MaxSize for compute fleet is an option that requires to stop the compute fleet for updating. Pcluster shows an option to override that and force update it. I never saw any issue with that. I wanted to understand the reason for requiring stopping the update fleet. What potential issues can that cause? It's very inconvenient to take down the whole cluster when all we want is to take down a few nodes.

**Comment by enrico-usai** [comment]
Hi @rahul003 are you talking about [`MaxCount`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeResources-MaxCount)?

If so, you can easily increase the size of `MaxCount` without the need to stop the cluster but if you want to reduce the size of the queue below the current size, the compute fleet must be stopped, in this way we're sure there are no running or pending jobs on the nodes we're terminating.

This also permits to avoid situation on which the user submits a job while ParallelCluster logic is shutting down some of the nodes to reduce the capacity.

Let me know if it helps to understand the reasoning behind this choice.
Enrico
