### ISSUE TITLE
pcluster 3.2.0: Missing dynamodb:UpdateItem policy in Base user policy required to invoke AWS ParallelCluster features

### ISSUE THREAD

**Issue by gwolski** [aws/aws-parallelcluster#4367]
I'm working on deploying/testing pcluster 3.2.0. I have the dynamodb policies in place as specified in https://docs.aws.amazon.com/parallelcluster/latest/ug/iam-roles-in-parallelcluster-v3.html#iam-roles-in-parallelcluster-v3-base-user-policy

However when I went to run an update-compute-fleet command, I received a policy missing error:

% pcluster update-compute-fleet -n <clustername> --status STOP_REQUESTED
{
  "message": "Failed when stopping compute fleet with error: User: arn:aws:sts::ACCOUNT:assumed-role/usw2-prod-cluster-mgmt/i-0a9b8e428e6922f96 is not authorized to perform: dynamodb:UpdateItem on resource: arn:aws:dynamodb:us-west-2:<NUMBERSDELETED>:table/parallelcluster-tim because no identity-based policy allows the dynamodb:UpdateItem action"

I updated the policy entry for dynamodb to include:

                "dynamodb:UpdateItem",

And then the pcluster update-compute-fleet command worked.  Is this missing from the documentation or did I miss something?

I am using my pcluster2 policies, slightly enhanced, with my pcluster3 trials but I don't think that is the problem as I just don't see this             "dynamodb:UpdateItem" policy anywhere.

**Comment by lukeseawalker** [comment]
Hello @gwolski,
thank you for reporting this.
PR with the doc fix https://github.com/awsdocs/aws-parallelcluster-user-guide/pull/103
