### ISSUE TITLE
pcluster 3.2 not available in pip

### ISSUE THREAD

**Issue by zeekus** [aws/aws-parallelcluster#4394]
aws-parallelcluster cli seems to be stuck at 3.2.0b1 in pip on Centos7.

How can we get 3.2 ? 

pip --version
pip 21.3.1 from /home/myuser/hpc-ve/lib/python3.6/site-packages/pip (python 3.6)

pip install aws-parallelcluster==3.2
ERROR: Could not find a version that satisfies the requirement aws-parallelcluster==3.2 (from versions: 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.2.1, 2.3.1, 2.3.2a1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.10.4, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.11.4, 2.11.5, 2.11.6, 2.11.7, 3.0.0b1, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0b1, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.2.0b1)
ERROR: No matching distribution found for aws-parallelcluster==3.2

pcluster version
{
  "version": "3.2.0b1"
}

**Comment by EddyMM** [comment]
Hello @zeekus ,

`aws-parallelcluster==3.2.0` dropped support for Python 3.6 since it reached end-of-life support (See [ChangeLog](https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.md)).

We recommend upgrading your environment's Python version to 3.7+ in order to use `aws-parallelcluster==3.2.0`.

**Comment by zeekus** [comment]
Thanks for the response. I added spack to my centos7 box and setup python3.9 in a virtual enviornment.  

It is working now. 
 
```
   spack install python@3.9.14
   ln -s $(spack location -i python)/bin/python /usr/bin/python3.9
   python3.9 -m venv python3.9
   source ~/python3.9/bin/activate
   (python3.9) [myuser@myhost ~]$ /usr/bin/python3.9 -m pip install aws-parallelcluster==3.2
```

https://spack-tutorial.readthedocs.io/en/latest/tutorial_basics.html
