### ISSUE TITLE
ParallelCluster API 3.2.1 timeouts during POST on /v3/clusters

### ISSUE THREAD

**Issue by zbarr** [aws/aws-parallelcluster#4491]
Hello,

I am going to try to get the info out for this one without having to paste massive configuration files at the moment, but if you need them I will try to get them up right away.

I have been heavily utilizing the AWS ParalllelCluster API, deployed via cloudformation and utilized with an OpenAPI generated Python client. It has been going great up until this point.

Since I moved up to 3.2.1, I have been getting Gateway Timeouts when creating a cluster (POST @ /v3/clusters):

    HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 31 Oct 2022 18:40:51 GMT', 'Content-Type': 'application/json', 'Content-Length': '41', 'Connection': 'keep-alive', 'x-amzn-RequestId': 'e612fc28-7285-4817-bce6-f9c311ba327a', 'x-amzn-ErrorType': 'InternalServerErrorException', 'x-amz-apigw-id': 'a4h3iEsjiYcFfLA=', 'X-Amzn-Trace-Id': 'Root=1-63601696-48243ec703d77c590631676f'})
    HTTP response body: {"message": "Endpoint request timed out"}

I was able to confirm that the lambda function was timing out via cloudwatch logs:
    2022-10-31T17:59:33.477Z a87479ec-47bc-4eb5-ae7f-bcc0c858c8f2 Task timed out after 30.05 seconds

I noticed that the parallelcluster-api.yaml file indicates a 30 second timeout for the lambda functions so I bumped that up to 60 seconds. This allowed the lambda function to complete and kick off the cluster creation but then the API gateway was still returning the timeout. I suspect that this is because, despite the fact that the lambda function can run for over 30 seconds now, the API gateway does not allow a request to exceed 30 seconds: https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html. Not to mention, requests of this length are essentially an anti-pattern in the world of HTTP.

My question is as such... am I doing something wrong to be bumping up against that 30 second limit or are create-cluster calls hitting that endpoint in testing also coming near that limit? If it is the former, then I will start to dig into what is taking so long in that function. I have a massive cluster definition so my first guess would have something to do with that.

Thanks.

**Comment by enrico-usai** [comment]
Hi @zbarr

You could try to use X-Ray to analyze the time spent by the different phases https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html 
This is already enabled for Pcluster Lambda so you can go in the AWS Lambda console and search for X-Ray logs in the Monitoring section.

Another thing you can try is to suppress the validators with `--suppress-validators ALL` just to see if in this way you're able to fit the 30secs timeout - Source: https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.create-cluster-v3.html

Let us know if it helps.
Enrico

**Comment by enrico-usai** [comment]
Another thing to mention is that sometimes the first invocation of the API (the "cold start" of the Lambda Function) can reach the timeout because of the time required to load the modules and initialize the environment, but subsequent invocations should not, because the Lambda service reuses warmed environments for subsequent invocations. 

Can you confirm you're facing the timeout issue at the first invocation only? 
If you're facing it at every `create-cluster` invocation, can you share your cluster config, we'd like to see if your config is routing some time expensive path.

Thanks

**Comment by zbarr** [comment]
I can kind of tell where the slowdown is by the lambda logging in cloudwatch, except I can't tell if they are logging before the action or after:
`{
    "level": "INFO",
    "location": "common.py:134:_log_boto3_calls()",
    "message": "Executing boto3 call: region=us-east-2, service=s3, operation=PutObject, params={'Bucket': 'parallelcluster-1f40ad08d655707c-v1-do-not-delete', 'Body': \"<body>", 'Key': 'parallelcluster/3.3.0/clusters/cpcv-cluster-4fyev3a2mg72h311/configs/cluster-config.yaml'}",
    "timestamp": "2022-11-03 21:16:48,839+0000",
    "service": "pcluster",
    "cold_start": false,
    "function_name": "parallelcluster-api-3300-ParallelClusterFunction-3XaZYOKQd24l",
    "function_memory_size": "1024",
    "function_arn": "arn:aws:lambda:us-east-2:159458012829:function:parallelcluster-api-3300-ParallelClusterFunction-3XaZYOKQd24l",
    "function_request_id": "7e61c659-5fc0-4cf9-8dac-754575ff315c",
    "xray_trace_id": "1-63642fb5-5fbcee901f976d6d373fd6ff"
}
`


And 18 seconds later:
`{
    "level": "INFO",
    "location": "common.py:134:_log_boto3_calls()",
    "message": "Executing boto3 call: region=us-east-2, service=s3, operation=PutObject, params={'Bucket': 'parallelcluster-1f40ad08d655707c-v1-do-not-delete', 'Key': 'parallelcluster/3.3.0/clusters/cpcv-cluster-4fyev3a2mg72h311/custom_resources/artifacts.zip', 'Body': <s3transfer.utils.ReadFileChunk object at 0x7fa54bd42df0>}",
    "timestamp": "2022-11-03 21:17:06,785+0000",
    "service": "pcluster",
    "cold_start": false,
    "function_name": "parallelcluster-api-3300-ParallelClusterFunction-3XaZYOKQd24l",
    "function_memory_size": "1024",
    "function_arn": "arn:aws:lambda:us-east-2:159458012829:function:parallelcluster-api-3300-ParallelClusterFunction-3XaZYOKQd24l",
    "function_request_id": "7e61c659-5fc0-4cf9-8dac-754575ff315c",
    "xray_trace_id": "1-63642fb5-5fbcee901f976d6d373fd6ff"
}
`

**Comment by enrico-usai** [comment]
Hi @zbarr thanks.

I'd say the time here is spent after the latest `PutObject` call, that by looking at our code means during the generation of the CloudFormation template for the cluster, by using CDK.

I'd suggest to try to pass `suppressValidators=True` in the query string, this will permit you to save some time. Let us know if it helps.

We'd like to replicate the issue, can you share the cluster configuration you're using?

**Comment by lukeseawalker** [comment]
Hello @zbarr,
we released [version 3.3.1](https://github.com/aws/aws-parallelcluster/releases/tag/v3.3.1) with the following change
> Increase memory size of ParallelCluster API Lambda to 2048 in order to reduce cold start penalty and avoid timeouts.

Can you please check if the above is able to solve your issue?
