### ISSUE TITLE
Feature Request: Support S3 data import for FSx Persistent 2 File Systems

### ISSUE THREAD

**Issue by stefan-vaisala** [aws/aws-parallelcluster#4499]
**Background:** 
We currently spin-up clusters using PCluster v3.2.1 once a day in an automated fashion. During this process, we spin up a Scratch 2 FSx file system that is connected to a S3 bucket and the data is imported from S3 using the lfs hsm_restore CLI. These clusters and all related resources are only up for ~2 hours; the entire stacks, including the created FSx volume are deleted. Currently, PCluster handles the creation of the Scratch 2 FSx file system and imports the data from S3 to the FSx via the "ImportPath" YAML option. Our post install procedures then run the lfs hsm_restore commands to load the data.

**Feature:**
With the new Persistent 2 FSx file system, the process of connecting the FSx file system to S3 and importing the data from S3 is way more complicated and time intensive than it should be. There are two additional tasks that need to be run to associate S3 to a Persistent 2 FSx file system: i) create a data repository association, and ii) running a data repository task to do a bulk import of the S3 metadata to the FSx volume.

We have added (i) and (ii) to our PCluster post-install bash scripts by using the recommended aws CLI calls (aws fsx create-data-repository-association and aws fsx create-data-repository-task). However, we quickly realized that creating the data repository association takes several minutes, but the aws CLI call returns immediately rather than waiting for the association to transition from "Creating" to "Available". As a result, any subsequent post install procedures that require the association, such as the required data repository task and lfs hsm_restore calls, will not succeed without waiting on this association. Overall, it is not ideal to have our post install script waiting on these AWS resources and tasks to complete/become available as these sort of tasks are "upstream" of anything post install procedures should handle. It seems like this could be handled directly after the FSx is created to save valuable time in cluster spin-up given how long the association takes to become available.

So, it would be great if PCluster could handle the steps described above for Persistent 2 FSx file systems - the creation of the data repository association and the initial data repository task to import the metadata from S3 to the FSx. This functionality already exists for the other FSx file system types supported by PCluster and would save us valuable time if was available for the Persistent 2 FSx as well. Thanks!

**Comment by hanwen-pcluste** [comment]
Hi Stefan,

Thank you for the detailed description. I am going to mark this as a feature request and will discuss within our team.

Hanwen,

**Comment by enrico-usai** [comment]
Released as part of release 3.8.0 

> Add support for Data Repository Associations when using PERSISTENT_2 as DeploymentType for a managed FSx for Lustre.
