### ISSUE TITLE
update-cluster fails because of EfsIdValidator when existing Efs is used in config file

### ISSUE THREAD

**Issue by matteoacrossi** [aws/aws-parallelcluster#4578]
**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.3.0
**Bug description and how to reproduce:**

I created a cluster successfully with an existing EFS mount point. The configuration looks like this:

```yaml
SharedStorage:
  - MountDir: /workspace
    Name: EFSworkspace
    StorageType: Efs
    EfsSettings:
      FileSystemId: fs-xxxxxxxxxxxxxxx
```

I modified the configuration in other parts (namely the LDAP authentication part), where it was possible to run `update-cluster` without needing to recreate it. But when I run `pcluster update-cluster` I get the following validation error:

```json
{
  "configurationValidationErrors": [
    {
      "level": "ERROR",
      "type": "EfsIdValidator",
      "message": "There is an existing Mount Target fsmt-xxxxxxxxxxxxxxx in the Availability Zone eu-west-1a for EFS fs-xxxxxxxxxxxxxxx, but it does not have a security group that allows inbound and outbound rules to support NFS. Please modify the Mount Target's security group, to allow traffic on port 2049."
    },
    {
      "level": "WARNING",
      "type": "EfsIdValidator",
      "message": "There is an existing Mount Target fsmt-xxxxxxxxxxxxxxx in the Availability Zone eu-west-1a for EFS fs-xxxxxxxxxxxxxxx, but it does not have a security group that allows inbound and outbound rules to allow traffic of subnet subnet-xxxxxxxxxxxxxxx. Please modify the Mount Target's security group, to allow traffic on subnet."
    }
  ],
  "message": "Invalid cluster configuration."
}
```

**Comment by chenwany** [comment]
Hi @matteoacrossi 
Thanks for reporting the issue!
Could you share what is in the changeset?
is the security group of the EFS deleted or modify? Could you check the security group associated with the EFS?

**Comment by lukeseawalker** [comment]
Hello @matteoacrossi,
we would like to repro the issue. Can you please report the following:
* Full cluster configuration without any credentials or personal data
* Describe of the fs-xxxxxxxxxxxxxxx you are using
* Arn of the cluster CloudFormation main stack:

**Comment by matteoacrossi** [comment]
I'm not able to reproduce the problem with ParallelCluster 3.4.0.
