### ISSUE TITLE
In previous 3.x releases, Getting Started links to the 2.x documentation and not the 3.x docs

### ISSUE THREAD

**Issue by devbioinfoguy** [aws/aws-parallelcluster#4647]
I have imposed a temp freeze on my work with 3.2.0, and so have been working with the repo at this commit tag. 

When checking through the [ReadMe.md](https://github.com/aws/aws-parallelcluster/tree/v3.2.0#readme), I've noticed that "Getting Started" links takes me to the [v2 Setting Up...](https://docs.aws.amazon.com/parallelcluster/latest/ug/getting_started.html), not the [v3 Setting Up...](https://docs.aws.amazon.com/parallelcluster/latest/ug/install-v3.html).

**Comment by chenwany** [comment]
Good catch! We already updated "Getting Started" links to points to ParallelCLuster3 documentation for 3.3.0 and later versions. Unfortunately we are not able to update the `readme.md` for the released version.

**Comment by devbioinfoguy** [comment]
Hmmm. I guess rewriting commit history to fix past problems, esp. on a tagged commit, is (politely) discouraged, huh?  ;-) 

Thanks for mentioning this. I did happen to see the correction in 3.3.x which gave me pause to think how I might fix the past release. Alas..

Thanks for all the hard effort on this. Really enjoy using it!!

**Comment by chenwany** [comment]
Yeah it is discouraged, a tag points to an exact commit, we can not put a new commit into an existing tag. 
>Thanks for all the hard effort on this. Really enjoy using it!!

Thank you for the feedback! Happy to hear that! :)
