### ISSUE TITLE
cfncluster master Node backup and recovery

### ISSUE THREAD

**Issue by srknk8990** [aws/aws-parallelcluster#466]
Hi,
I created one cfncluster by creating a custom Ami.
* Started with Aws provided ami(https://github.com/awslabs/cfncluster/blob/master/amis.txt)
* ran my custom scripts and finally ran the ami cleanup script(/usr/local/sbin/ami_cleanup.sh) 
* The cfncluster is currently running with sge scheduler

Now I want to achieve backup and restore option for the Master node in case of disaster(I am not worried about Compute nodes, since they are ephemeral). 

Just to try ,  I created the Ami of the existing cfncluster Master Node .
Launched an instance from this Ami to run the aws provided ami cleanup Script(/usr/local/sbin/ami_cleanup.sh) . Finally created the Ami of this instance. 

This Ami I entered into the cfncluster config file's custom_ami section. I tried creating a new cluster but the cluster is not getting created.
In the cfn-init.log I see that the cleanup is not happening and i see many configurations and files having the same entries as in  the previous cfncluster master node. 

I know that there is a separate section to provide snapshotid or volumeid in the cfncluster config file where i could keep the files that i need the backup of and attach it to new cluster that i am creating. But because of this I would not be able to keep the backup of files and application/softwares  that my user created in their personal /home/user directory. With this restriction  i would always need to keep a track of  all steps that my user performed (ex : install application in /home/user dir) in the existing cluster and perform them in bootstrap during new cluster creation.

Can I know of some solution to deal with this problem ??
Thanks in advance.

**Comment by srknk8990** [comment]
@sean-smith  Any Recommendations or guidance for us to start on and achieve this ? 

Thanks

**Comment by enrico-usai** [comment]
I'm going to close this ticket in favour of: [#2441 - Configure cluster users home directories on the shared storage (FSx, EFS, EBS)](https://github.com/aws/aws-parallelcluster/issues/2441)
