### ISSUE TITLE
Feature Request: CloudWatch log group cleanup

### ISSUE THREAD

**Issue by stefan-vaisala** [aws/aws-parallelcluster#4711]
In PCluster 3.X.X, Lambdas are created to clean up resources and route53. These lambdas stream their logs to log groups like: `/aws/lambda/pcluster-CleanupResources-[random hash]` and `/aws/lambda/pcluster-CleanupRoute53-[random hash]`. 

Since we spin-up/down new clusters daily (if not multiple times a day), we have a constantly growing number of these log groups. Currently, we need to delete these manually every so often so we can more efficiently navigate to the log groups we are looking for or to just keep the number of log groups we have a more manageable number.

It would be great if PCluster could either i) use a constant log group name for each cleanup routine so that all the log streams are held within that log group, or ii) delete the log groups of clusters upon cluster deletion (since the cleanup log groups are no longer relevant for a deleted cluster).

Thanks! - Stefan

**Comment by enrico-usai** [comment]
Hi @stefan-maxar, if your clusters are stable and you don't need them at cluster deletion time you can use [DeletionPolicy](https://docs.aws.amazon.com/parallelcluster/latest/ug/Monitoring-v3.html#yaml-Monitoring-Logs-CloudWatch-DeletionPolicy) or reduce [RetentionInDays](https://docs.aws.amazon.com/parallelcluster/latest/ug/Monitoring-v3.html#yaml-Monitoring-Logs-CloudWatch-RetentionInDays).

Let us know if it helps.

**Comment by stefan-vaisala** [comment]
@enrico-usai Thanks for the tip! I was unsure if that section actually "worked" on those log groups since we already have CloudWatch logs disabled in our cluster YAML:

```
Monitoring:
  Logs:
    CloudWatch:
      Enabled: false
      RetentionInDays: 14
  Dashboards:
    CloudWatch:
      Enabled: false
```

I will try adding in a DeletionPolicy there and see if that works. Thanks!

**Comment by enrico-usai** [comment]
Yes, we're using the same `DeletionPolicy` for all the Log Groups. 
Anyway can you confirm that the Lambda Log Groups are deleted after 14 days?

Thanks!

**Comment by stefan-vaisala** [comment]
Doesn't seem like it - see the attached example of a log group created a month ago with a 2 week retention policy. The log events within each log stream is deleted, but the log streams and log group remains. Though, that seems like the intended behavior based on the description of a retention policy (https://docs.aws.amazon.com/managedservices/latest/userguide/log-customize-retention.html)?

![Screenshot 2022-12-15 121322](https://user-images.githubusercontent.com/57150975/207926340-25eb31f2-46c7-42d1-95b7-dbb8c83a7e21.png)

**Comment by stefan-vaisala** [comment]
Just confirmed that using `DeletionPolicy` works as expected with those log groups. Thanks!

**Comment by enrico-usai** [comment]
> that seems like the intended behavior based on the description of a retention policy

Correct, you found the right documentation confirming that the log streams are deleted but Log Groups are not.

> Just confirmed that using DeletionPolicy works as expected with those log groups. Thanks!

Thanks for the confirmation, perfect, resolving the issue, feel free to comment or create a new one if you need additional help.

Thanks
Enrico
