### ISSUE TITLE
(3.2.0-3.4.1) Rebooting nodes through Slurm might cause an instance replacement if EC2 health checks fail

### ISSUE THREAD

**Issue by demartinofra** [aws/aws-parallelcluster#4751]
### Bug description

Starting from version 3.2.0, ParallelCluster supports the reboot of compute nodes through Slurm commands. Such a mechanism allows cluster users to leverage the Slurm `scontrol reboot` command to reboot a compute node and instructs the ParallelCluster fleet management daemon (clustermgtd) to disregard health check failures for the duration of the reboot.

Due to a lag between the time a rebooted instance becomes ready and the time the status of the EC2 health checks is updated, in case the node becomes available to the Slurm scheduler before the EC2 health check failure is cleared, ParallelCluster marks the node as unhealthy and replaces the instance. In such cases a reboot will result in a replacement of the underlying EC2 instance. No additional functionalities are impacted.

### Mitigation

As a mitigation you can temporarily disable the handling of EC2 health checks when rebooting instances so that nodes are not replaced when the condition described above is met. Here are the steps to follow:

1. Disable health checks management in clustermgtd by setting `disable_ec2_health_check = true` in `/etc/parallelcluster/slurm_plugin/parallelcluster_clustermgtd.conf`
2. Check that there are no errors in `/var/log/parallelcluster/clustermgtd` and that the new config is applied (log message: `Applying new clustermgtd config...`)
3. Perform node reboots by running the `scontrol reboot` command and wait for the nodes to complete. You can check its status with an `scontrol show nodes`.
4. Revert the changes in clustermgtd config by removing `disable_ec2_health_check = true` or setting it to `false`.
5. Check there are no errors in `/var/log/parallelcluster/clustermgtd` log file and that the config is applied.

**Comment by lukeseawalker** [comment]
[PCluster version 3.5.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.5.0) released with the fix 
> Fix an issue in clustermgtd that caused compute nodes rebooted via Slurm to be replaced if the EC2 instance status checks fail.
