### ISSUE TITLE
Unable to create pcluster using version 3.3.1

### ISSUE THREAD

**Issue by ehimgoy** [aws/aws-parallelcluster#4755]
Facing Issues while creating cluster using pcluster version 3.3.1 . Normally, I create cluster through this version but today(22-Dec-2022) I faced this issue

Error:-
HeadNodeWaitCondition2  CREATE FAILED
WaitCondition timed out. Received 0 conditions when expecting 1
-------------------------------------------------------------------------------------------
After the release of 3.4.0, not able to create cluster with earlier versions. Although able to create cluster with pcluster version 3.4.0. Any update like we have to update older versions to 3.4.0 or we can create cluster with the earlier version also.

**Comment by pmjlearninggit** [comment]
try using package sudo yum install nice-dcv-gl-2022.2.983-1.el7.x86_64.rpm

**Comment by EddyMM** [comment]
Hello @ehimgoy,

The error appears to be a networking issue. Is the problem still reproducible?
If so, could you kindly share the cluster configuration and `chef-client` logs (`/var/log/chef-client.log`)? Ensure to remove any sensitive information.

It could be that you're using a Custom AMI that doesn't have `xorg-x11-utils`

**Comment by ehimgoy** [comment]
Hello @EddyMM 

I think it's not an issue with the custom ami because I have one running cluster with the same configuration. The real issue occurs after the release of pcluster version 3.4.0 . After 22nd Dec I am not able to create a very simple cluster. I used versions 3.1.1 and 3.3.1. Both are unable to create cluster and cluster creation failed on the HeadNode wait condition. Although this is not case before the release of 3.4.0. 

On my request can you just create a cluster with any of the pcluster version like 3.1.1 or 3.3.1. If you get any success then let me know

**Comment by hanwen-pcluste** [comment]
Hi ehimgoy,

We have tests running daily and are able to create clusters. There are two possible causes:
1. mirror.centos.org might have temporarily down.
2. The subnet(s) for your cluster does not have Internet connection.

To verify this:
1. Can you create a cluster and see if the problem persists?
2. Can you make sure the subnet(s) have Internet access? To verify this, you can create an instance(s) in the subnet(s), and run `ping mirror.centos.org -c 5`

**Comment by ehimgoy** [comment]
Hi hanwen-pcluste.

I tried to create cluster not just with centos but also with the alinux2 and it failed on the same Head Node wait condition.
And also checked the subnet and it have the internet connection.

One more thing I would like to add that I am able to create cluster with pcluster version 3.4.0 but not with the earlier versions like 3.1.1 and 3.3.1 

So, my concern related to the version. After the release of 3.4.0, not able to create cluster with earlier versions.

**Comment by hanwen-pcluste** [comment]
I manually created clusters with Alinux2 and CentOS7. The creations were successful.
Could you provide the cluster configuration file (without sensitive information) and /var/log/chef-client.log to help us further the investigation?
Alternatively, could you describe in details of what customization are there:
1. Is a custom AMI used? If yes, how was the AMI created?
2. Is a custom action script used?
3. What instance type is used for head node?
4. Are the head node and compute nodes in the same subnet?
5. Are there any other customizations in the cluster configuration file?

Thank you!
