### ISSUE TITLE
sinfo is showing incorrect cores and sockets

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#477]
I have spun up a 8-node c5.4xlarge cluster. It has 16 vCPUs. However, sinfo shows 16 sockets.

```
sinfo -o '%9P %4c %8z %8X %8Y %8Z'
PARTITION CPUS S:C:T    SOCKETS  CORES    THREADS
compute*  16   16:1:1   16       1        1
```

Has something changed in slurm setup?

I have used the [template](https://raw.githubusercontent.com/awslabs/cfncluster/develop/cloudformation/cfncluster.cfn.json) directly.

Thanks
Santi

**Comment by sean-smith** [comment]
In 1.5.2 we added slot count to slurm: https://github.com/awslabs/cfncluster/releases/tag/v1.5.2

**Comment by adavanisanti** [comment]
Thanks. Is there a plan to enable `[sacct](https://slurm.schedmd.com/sacct.html)` in any of the future releases?

**Comment by sean-smith** [comment]
Here's a [blogpost](https://aws.amazon.com/blogs/compute/enabling-job-accounting-for-hpc-with-aws-parallelcluster-and-amazon-rds/) on how to setup sacct.

**Comment by rexcsn** [comment]
Thanks Sean, seems like there is no open question here, I will go ahead and close this issue.

Feel free to re-open if there is any question!
