### ISSUE TITLE
(3.3.0-3.4.0) Slurm cluster NodeName and NodeAddr mismatch after cluster scaling

### ISSUE THREAD

**Issue by chenwany** [aws/aws-parallelcluster#4781]
## Bug description

There is an issue present in the Slurm 22.05.5-22.05.7 `scontrol update NodeName=A,B,... NodeAddr=A,B,...` command that mismatches pairs of NodeName and NodeAddr depending on the order of the node list. ParallelCluster uses this functionality during scaling operations and can therefore potentially reach an inconsistent state, resulting in nodes not being accessible or being backed by the incorrect EC2 instance type.

The problem can be identified by checking `clustermgtd` logs for the text “`Resetting powering down nodes:`” where the NodeName (beginning of the identifier) does not match the NodeAddr (in parenthesis in the identifier). For example, in the following log:

`[slurm_plugin.clustermgtd:_handle_powering_down_nodes] - INFO - Resetting powering down nodes: (x2) ['t2medium-dy-t2medium-1(t2small-dy-t2small-1)', 't2small-dy-t2small-1(t2medium-dy-t2medium-1)']`
the NodeName `t2medium-dy-t2medium-1` should be matched with the NodeAddr `t2medium-dy-t2medium-1`, but it is instead matched with `t2small-dy-t2small-1`.

## Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.3.0-3.4.0)-Slurm-cluster-NodeName-and-NodeAddr-mismatch-after-cluster-scaling).

**Comment by truatpasteurdotfr** [comment]
thx for the heads-up!
Has this been reported upstream?

**Comment by hanwen-pcluste** [comment]
Yes. Slurm is notified. They are working on a fix.

**Comment by lukeseawalker** [comment]
ParallelCluster 3.4.1 has been released, it contains the fix for this issue, ref https://github.com/aws/aws-parallelcluster/releases/tag/v3.4.1
