### ISSUE TITLE
Support for persistent_2 FSx for Lustre

### ISSUE THREAD

**Issue by wtempel** [aws/aws-parallelcluster#4799]
Do I understand correctly that currently
1. PERSISTENT_1 type filesystems can be fully managed (created, deleted) and configured (import from, export to an S3 bucket) via a parallelcluster configuration file
2. PERSISTENT_2 type filesystems must be managed and configured outside the parallelcluster configuration?

If the answer to both questions is yes:
1. Will PERSISTENT_1 filesystems remain available for the foreseeable?
2. Is there a plan and timeframe for integration of PERSISTENT_2 filesystem management in the parallelcluster configuration?

**Comment by davprat** [comment]
Hi,

Support for fully managed PERSISTENT_2 type file systems was added in ParallelCluster v3.2.0 - see the [documentation here](https://docs.aws.amazon.com/parallelcluster/latest/ug/SharedStorage-v3.html#yaml-SharedStorage-FsxLustreSettings-DeploymentType) on how to configure it.

However, import from and export to an S3 bucket is not supported for PERSISTENT_2 - see the note in the [documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/SharedStorage-v3.html#SharedStorage-v3-FsxLustreSettings) for the `ImportPath` property.

**Comment by wtempel** [comment]
Thanks @davprat.

> import from and export to an S3 bucket is not supported for PERSISTENT_2

Support for import and export in the parallelcluster configuration on-the-fly, as seems to be available for PERSISTENT_1, would, imo, be a welcome enhancement. I wonder
- what is the recommended method of configuring import-export for PERSISTENT_2 within ephemeral clusters right now? Should `pcluster create-cluster` be embedded in a wrapper in which also the filesystem is created is created, its id recorded and DRAs are configured? Or could the DRA be configured as a post-install task? Or...
- whether support for PERSISTENT_2 `ImportPath` and `ExportPath`, or their equivalents, is forthcoming.

**Comment by jdeamicis** [comment]
Hi @wtempel,

currently AWS CloudFormation does not support those parameters for PERSISTENT_2 types of Lustre deployments: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html#cfn-fsx-filesystem-lustreconfiguration

The recommended solution is to configure it from the console and then use it in ParallelCluster as an external file system.

We will consider supporting `ImportPath` and `ExportPath` for PERSISTENT_2 as soon as CloudFormation will support them.

**Comment by stefan-vaisala** [comment]
FYI - I have a long standing ticket related to this: https://github.com/aws/aws-parallelcluster/issues/4499

That being said - its news to me that CF doesnt fully support PERSISTENT_2 yet akin to how it is supported for other types - which makes sense why PCluster can't do the same workflow as other FSX for Lustre types. Perhaps there's an opportunity to put in a feature request (if not already created) with the Cloud Formation team? Curious if its on their roadmap, and if so, when.

**Comment by wtempel** [comment]
> Perhaps there's an opportunity to put in a feature request (if not already created) with the Cloud Formation team? Curious if its on their roadmap, and if so, when.

@jdeamicis Would this be the place to either see the status or request the feature? https://github.com/aws-cloudformation/cloudformation-coverage-roadmap

**Comment by jdeamicis** [comment]
Actually I have to correct myself on this topic. It looks like FSx for Lustre now supports [data repository associations (DRAs) between S3 buckets and Lustre file systems](https://docs.aws.amazon.com/fsx/latest/LustreGuide/create-dra-linked-data-repo.html): this functionality is available for PERSISTENT_2 deployments.

We have an internal ticket to track this feature request. I will reopen this issue.

**Comment by jsmedmar** [comment]
@jdeamicis, kind follow up on this topic. Has the pcluster team consider addressing this issue and #4499?

**Comment by enrico-usai** [comment]
Added as part of 3.8.0 release

> Add support for Data Repository Associations when using PERSISTENT_2 as DeploymentType for a managed FSx for Lustre.
