### ISSUE TITLE
(3.3.0-3.4.1) Custom AMI creation fails on Ubuntu 20.04 during MySQL packages installation

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-parallelcluster#4835]
## Bug description

The process of creating a custom AMI, by using the the `pcluster build-image` command, fails in ParallelCluster 3.3.0 - 3.4.1, when using an Ubuntu 20.04 x86_64 as `ParentImage` in the image build configuration file.

The `pcluster build-image` command will fail after about 1 hour, due to a failure with the installation of the MySQL client packages during the ParallelCluster AMI building process.

The custom AMI creation process started to fail on January 25th, because an updated version of MySQL packages ([8.0.32](https://dev.mysql.com/downloads/mysql/)) has been released in the Ubuntu OS repository. This package is installed in the system by the initial phases of the build AMI process and then the `install_mysql_client` code tries to install the old 8.0.31 version on top of the updated version, causing the installation steps to fail.

## Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.3.0-3.4.1)-Custom-AMI-creation-fails-on-Ubuntu-20.04-during-MySQL-packages-installation).

**Comment by flowinh2o** [comment]
Any idea on how frequently the releases are made or when this change will be included?  Looks like the fix was merged to dev 3 weeks ago and would like to start using 3.4.1 as well.  Thank you.

**Comment by maurizp** [comment]
Parallel Cluster 3.5.0 has been released and includes this patch.
