### ISSUE TITLE
GENERAL QUESTION - Parallelcluster 3.1.1 AMI to ParallelCluster 3.4.1 AMI upgrade Possible ?

### ISSUE THREAD

**Issue by datechnic** [aws/aws-parallelcluster#4836]
We are trying to move our pcluster environment to version 3.4.1 from 3.1.1.  We have a hardened 3.1.1 AMI which we took from the AWS AMI marketplace that contains all of our tools that we we would like to use with 3.4.1.  Is there an option available to update this AMI to version 3.4.1.  I am talking about the AMI not the CLI.  Any help you can provide would be appreciated.

**Comment by enrico-usai** [comment]
Hi @datechnic,
you cannot reuse the existing 3.1.1 AMI. Anyway the 3.1.1 AMI has been created starting from your parent AMI.

You should restart the AMI creation process starting from your [ParentImage](https://docs.aws.amazon.com/parallelcluster/latest/ug/Build-v3.html#yaml-build-image-Build-ParentImage), not from the 3.1.1 AMI. 
[Here](https://docs.aws.amazon.com/parallelcluster/latest/ug/building-custom-ami-v3.html) you can find the steps to create a new ParallelCluster AMI for 3.4.1.
