### ISSUE TITLE
Wrong instance type after update_compute

### ISSUE THREAD

**Issue by lletourn** [aws/aws-parallelcluster#4865]
`` - AWS ParallelCluster version: 3.2.1
 
I created my cluster with a compute node of type c5.4xlarge

Later I ran 
`pcluster update-compute-fleet --region us-east-1 --cluster-name XXXX --status STOP_REQUESTED`
Then updated the instance type to c5.18xlarge and ran
`pcluster update-cluster --cluster-name XXXX --cluster-configuration configs/cluster-config.prod.us-east1a.yaml`

Once updated, I restarted the fleet.
In the AWS console I see c5.18x instances.

but sinfo still shows
`
$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
cpu*         up   infinite    999  idle~ cpu-dy-c54xlarge-[2-1000]
cpu*         up   infinite      1    mix cpu-dy-c54xlarge-1
`
Also `scontrol show job` shows node names as being c54large

Shouldn't the update also update the node names?

**Comment by francesco-giordano** [comment]
Hi,
that is the name of the `ComputeResources`. In your updated configuration do you have changed the name of the `ComputeResources` too?

**Comment by lletourn** [comment]
Changed nothing but the instance type. Then I ran pcluster update-cluster

**Comment by hanwen-pcluste** [comment]
That explains why the name of the nodes are not changed. The instance type should have been changed successfully.
In other words, the name displayed by `sinfo` is the same as the `ComputeResource` `Name`, independent from what `InstanceType` you choose.

**Comment by lletourn** [comment]
Man I'm so dumb. I forgot about that field. I thought It was dynamically set.
So sorry to have wasted your time, please destroy this whole thread.

Geez now I feel bad :-)
