### ISSUE TITLE
(3.0.0-3.2.1) Running nodes might be mistakenly replaced when new jobs are scheduled

### ISSUE THREAD

**Issue by francesco-giordano** [aws/aws-parallelcluster#4874]
## Bug description

Due to an issue present in the Slurm scheduler module (bug [14073](https://bugs.schedmd.com/show_bug.cgi?id=14073)), which is responsible to initiate the provisioning of dynamic cloud nodes, running nodes might be mistakenly replaced with new instances. As a consequence of this operation, jobs that were potentially running on the affected nodes are re-queued and the cluster undergoes a temporary over-scaling that is automatically recovered.

## Mitigation

You can find a detailed explanation and the mitigation of the problem in the [wiki page](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.2.1)-Running-nodes-might-be-mistakenly-replaced-when-new-jobs-are-scheduled).

**Comment by lukeseawalker** [comment]
Starting from [PCluster version 3.3.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.3.0), a Slurm version with the fix is distributed.

> Upgrade Slurm to version 22.05.5.
