### ISSUE TITLE
fixing code on (3.0.0-3.5.0) DCV virtual session on Ubuntu 20.04 might show a black screen

### ISSUE THREAD

**Issue by santhanrvs** [aws/aws-parallelcluster#4949]
There are a few errors in the script. Here are the corrections:

The URL in the wget command is not properly formatted. Replace [https://d1uj6qtbmh3dt5.cloudfront.net/2022.2/Servers/${DCV_FILE}.tgz](https://d1uj6qtbmh3dt5.cloudfront.net/2022.2/Servers/$%7BDCV_FILE%7D.tgz) with https://d1uj6qtbmh3dt5.cloudfront.net/2022.2/Servers/${DCV_FILE}.tgz.
The popd command is missing an argument. Change popd to popd ...

`#!/bin/bash -ex

WORK_DIR=`mktemp -d`
DCV_VERSION=2022.2-14521
DCV_FILE=nice-dcv-${DCV_VERSION}-ubuntu2004-x86_64

function cleanup {
  rm -rf ${WORK_DIR}
}

trap cleanup EXIT

chmod go+rx ${WORK_DIR}
pushd ${WORK_DIR}
wget https://d1uj6qtbmh3dt5.cloudfront.net/NICE-GPG-KEY
gpg --import NICE-GPG-KEY
wget https://d1uj6qtbmh3dt5.cloudfront.net/2022.2/Servers/${DCV_FILE}.tgz
tar -xvzf ${DCV_FILE}.tgz
pushd ${DCV_FILE}

sudo mv /etc/dcv/dcv.conf /etc/dcv/dcv.conf.bak
sudo systemctl stop dcvserver
sudo systemctl disable dcvserver
/usr/bin/yes | sudo apt install -y ./nice-dcv-server_2022.2.14521-1_amd64.ubuntu2004.deb
sudo apt install -y ./nice-dcv-web-viewer_2022.2.14521-1_amd64.ubuntu2004.deb
sudo usermod -aG video dcv
sudo apt install -y ./nice-xdcv_2022.2.519-1_amd64.ubuntu2004.deb
sudo apt install -y ./nice-dcv-gl_2022.2.1012-1_amd64.ubuntu2004.deb
sudo mv /etc/dcv/dcv.conf.bak /etc/dcv/dcv.conf
sudo systemctl restart dcvserver
sudo systemctl enable dcvserver

popd ..
popd
`

**Comment by chenwany** [comment]
Thank you for the feedbacks! 
We fixed the formatting issue of [https://d1uj6qtbmh3dt5.cloudfront.net/2022.2/Servers/${DCV_FILE}.tgz](https://d1uj6qtbmh3dt5.cloudfront.net/2022.2/Servers/$%7BDCV_FILE%7D.tgz) 
For popd, I think it can be used alone without adding argument.
for example:
```
pushd /tmp
popd
```
Thank you!
