### ISSUE TITLE
PC UI deployment fails

### ISSUE THREAD

**Issue by cartalla** [aws/aws-parallelcluster#4955]
**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.5.0

**Bug description and how to reproduce:**

Tried to deploy PC UI:

https://docs.aws.amazon.com/parallelcluster/latest/ug/install-pcui-v3.html

The cloudformation stack failed. 

substack:

arn:aws:cloudformation:us-east-1:415233562408:stack/parallelcluster-ui-ParallelClusterApi-8D1ERSMFBH4Z/a2d079d0-b3a9-11ed-bdcf-0e0bf000f0ab

EcrImage resource failed with:

Resource handler returned message: "Error occurred during operation 'SSM execution '89b8eb74-5708-4b3d-877e-707d26208a07' failed for image arn: 'arn:aws:imagebuilder:us-east-1:415233562408:image/importpublicecrimage-3-5-0-a2d079d0-b3a9-11ed-bdcf-0e0bf000f0ab/3.5.0/1' with status = 'TimedOut' in state = 'BUILDING' and failure message = 'SSM Agent verification failed''." (RequestToken: 7fd0a507-3bbc-d3d6-ca30-4decdc901913, HandlerErrorCode: GeneralServiceException)

I was able to see the ImageBuilder instance in the default VPC, but I wasn't able to connect to it with SSM so not sure how image build is supposed to execute commands.

**Comment by chenwany** [comment]
Hi 
For issue related to PC UI, could you post the issue in https://github.com/aws-samples/pcluster-manager?

Thank you!

**Comment by cartalla** [comment]
Created new issue at:

https://github.com/aws-samples/pcluster-manager/issues/551
