### ISSUE TITLE
Allow prefix list for DCV/AllowsIps

### ISSUE THREAD

**Issue by cartalla** [aws/aws-parallelcluster#4956]
**Required Info:**
 - AWS ParallelCluster version: 3.5.0

**Bug description and how to reproduce:**
When configuring DCV, AllowedIps only allows a single CIDR.
My IP address can change daily because I'm accessing from corporate VPN.
We have a managed prefix list that gives the egress CIDRs for our corporate network and that is what should go into the
security group, not a single CIDR block.

**Comment by chenwany** [comment]
Hi,
thank you for you feedback!
If you want to access DCV from a prefix list, one way you can do is to configure additional security group for HeadNode. See https://docs.aws.amazon.com/parallelcluster/latest/ug/HeadNode-v3.html#yaml-HeadNode-Networking-AdditionalSecurityGroups, you can create an additional security group to have inbound rules with port 8443 (the default port for DCV), then you can update or create the cluster with the AdditionalSecurityGroup.
Let us know if that works for you.

Thanks,
Wanyi
