### ISSUE TITLE
(3.3.0-3.5.0) Update cluster to remove shared EBS volumes can potentially cause node launching failures

### ISSUE THREAD

**Issue by chenwany** [aws/aws-parallelcluster#5018]
## Bug description

The cluster may hit issues during scale-up operations with new nodes joining after a cluster update where shared EBS volumes have been removed from the SharedStorages section of the configuration.

In particular, the error occurs if the removed EBS had a MountDir path that's a sub-path of other volumes shared in the cluster. For example, removing a custom shared storage with a mount directory as `/shared`, `/slurm`, `/parallelcuster/shared` or `/intel` would corrupt the ParallelCluster NFS export paths from the head node, causing the mount operations on the compute nodes to fail.

More in general, the issue happens whenever you remove a shared EBS with mount path `/path_1` and another system or custom EBS volume has an export path as `/path_2/path_1`.

This is caused by an issue in our code to unmount shared EBS volumes, which deletes lines from `/etc/exports` that match the regular expression of the `/<MountDir> ` without checking if it starts with `^/<MountDir> `. For example, if you have multiple SharedEBS volumes with MountDir that are contains the path name of each other: `path_1` and `path_2/path_1`. Both paths ( `/path_1` and `/path_2/path_1)`are written in `/etc/exports`. If you update the cluster to remove shared EBS with `path_1`, the regular expression with match lines that have `/path_1` and also unintentionally removed `/path_2/path_1`, further cluster operations like launching nodes or submitting jobs may fail due to required softwares or paths no longer exported over NFS. 

## Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.3.0-3.5.0)-Update-cluster-to-remove-shared-EBS-volumes-can-potentially-cause-node-launching-failures).

**Comment by enrico-usai** [comment]
Fixed as part of: https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.md#351
