### ISSUE TITLE
EFS shared storage, String does not match expected pattern

### ISSUE THREAD

**Issue by blakemertz** [aws/aws-parallelcluster#5027]
I'm attempting to create a cluster that connects to our shared EFS storage. My Shared storage section in my configuration file is as follows:
```
SharedStorage:
  - MountDir: /data/modstore1
    Name: modstore1
    StorageType: Efs
    EfsSettings:
      FileSystemId: fsmt-xxxxxxxx
```

My FileSystemId was pulled from our EFS mount target ID.

However, when I go to create the cluster, I get the following error:
```
pcluster create-cluster -n modbind-noAD-modstore1 -c modbind-noAD-modstore1                                                                                                  
{
  "configurationValidationErrors": [
    {
      "level": "ERROR",
      "type": "ConfigSchemaValidator",
      "message": "[('SharedStorage', {0: {'EfsSettings': {'FileSystemId': ['String does not match expected pattern.']}}})]"
    }
  ],
  "message": "Invalid cluster configuration."
}

```
I believe that I am using the correct string syntax, since our EFS was created before 2019 which should mean our targetID has 8 alphanumeric characters. I didn't find anything in the log file that would provide additional detail, and a search through the git issues was unfruitful as well. Any help would be much appreciated.

**Comment by enrico-usai** [comment]
Hi @blakemertz you should not use the File System Mount Point id id but the EFS File System id.
You should replace `fsmt-xxxxxx` with something like `fs-xxxx`.

The pattern is: `^fs-[0-9a-z]{8}$|^fs-[0-9a-z]{17}$`.

Let us know if solves your issue.

**Comment by blakemertz** [comment]
@enrico-usai thanks for the quick response! I had originally used the fs-xxxx name for our EFS mount point but I must have had an input/copy error in setting up the configuration script. Parallelcluster configure now accepts the mount point ID as you have instructed.

I have other issues related to network configuration of my EFS, but that is unrelated to this issue. Again, thank you for the help -- I'll mark this closed.
