### ISSUE TITLE
pcluster v3.5.0 CLI as well as parallelClusterUI don't allow creation of compute instance type hpc6a.48xlarge

### ISSUE THREAD

**Issue by adayaru** [aws/aws-parallelcluster#5056]
Actual issue explained in the next comment.

**Comment by adayaru** [comment]
ParallelCluster UI and CLI - doesn't allow creation of a cluster with hpc6a.48xlarge

This is the message I see:

(apc-ve) gromacs-clusters 10Mar2023 15:59 $ pcluster create-cluster --cluster-name hpc --cluster-configuration gromacs-actual-config-multi-queue-modified.yaml
{
  "message": "Invalid cluster configuration: The following supplied instance types do not exist: [hpc6a.48xlarge]"
}
(apc-ve) gromacs-clusters 10Mar2023 16:00 $ 

Same is seen in the UI too - Image below
 
 <img width="952" alt="Screenshot 2023-03-10 at 3 58 03 PM" src="https://user-images.githubusercontent.com/111283900/224638558-ddd46253-c515-43f4-a85c-de0c177f2227.png">
 
 
This instance type doesn't appear in the dropdown too (in fact, no instance starting with 'hpc' is there in the dropdown).

I would like to create aws parallel cluster with compute nodes of type hpc6id as well as hpc6a .
There is a aws workshop example showing hpc6a.48xlarge compute node at:
https://catalog.workshops.aws/gromacs-on-aws-parallelcluster/en-US/01-hpc-cluster/02-create-cluster

But when I tried using the same config file as in the workshop above, it showed the failure as in the screenshot.

I am trying these in us-east-1 region.

**Comment by adayaru** [comment]
Currently this instance type (and instances of type hpc6id.32xlarge) are available only in 
the region: us-east-2

I was trying in us-east-1.

Hope the documentation for these types makes it easier to check which region it is available. in.

I used this aws CLI to look for the same:

heck for hpc6id.32xlarge:


Check in us-east-1:
```
aws ec2 describe-instance-type-offerings     --location-type availability-zone     --filters Name=instance-type,Values=hpc6id.32xlarge    --region us-east-1
```
```
  ------------------------------------------
  (apc-ve) code 14Mar2023 16:08 $ 
  (apc-ve) code 14Mar2023 16:08 $ aws ec2 describe-instance-type-offerings     --location-type availability-zone     --filters Name=instance-type,Values=hpc6id.32xlarge    --region us-east-1
  {
      "InstanceTypeOfferings": []
  }
  (apc-ve) code 14Mar2023 16:08 $ 
  ------------------------------------------
```
Check in us-east-2:
```
aws ec2 describe-instance-type-offerings     --location-type availability-zone     --filters Name=instance-type,Values=hpc6a.48xlarge     --region us-east-2
```
```
  ------------------------------------------
  (apc-ve) code 14Mar2023 16:08 $ aws ec2 describe-instance-type-offerings     --location-type availability-zone     --filters Name=instance-type,Values=hpc6id.32xlarge    --region us-east-2
  {
      "InstanceTypeOfferings": [
          {
              "InstanceType": "hpc6id.32xlarge",
              "LocationType": "availability-zone",
              "Location": "us-east-2b"
          }
      ]
  }
  (apc-ve) code 14Mar2023 16:09 $ 
  ------------------------------------------
```

**Comment by enrico-usai** [comment]
Thanks @adayaru for closing it with an explanation!
