### ISSUE TITLE
(3.0.0-3.5.0) ParallelCluster build-image command does not tag resources created by Image Builder during the AMI building process

### ISSUE THREAD

**Issue by jdeamicis** [aws/aws-parallelcluster#5089]
## Bug description

When creating an AMI with ParallelCluster via the `pcluster build-image` command, users may provide the [﻿Tags﻿](https://docs.aws.amazon.com/parallelcluster/latest/ug/Build-v3.html#Build-v3-Tags) parameter in the Build section of the image build configuration file to tag the resources used to build the AMI. 

Due to a missing parameter in the Image Builder infrastructure configuration created by ParallelCluster, only the Image Builder configuration itself is tagged with the tags provided by the user, while the resources created by Image Builder during the AMI creation (e.g. EC2 instances to build and test the AMI) are not tagged.

## Mitigation

We are working on this, a fix will be shipped in the next major release.

**Comment by enrico-usai** [comment]
Issue fixed with: https://github.com/aws/aws-parallelcluster/pull/5045

**Comment by enrico-usai** [comment]
Issue fixed on 3.6.0 release: https://github.com/aws/aws-parallelcluster/releases/tag/v3.6.0
