### ISSUE TITLE
Feature request: AmazonLinux 2023 (al2023) support

### ISSUE THREAD

**Issue by nyetsche** [aws/aws-parallelcluster#5214]
Amazon Linux 2023 was released in 2023 and has support from AWS until at least 2027: https://docs.aws.amazon.com/linux/al2023/ug/release-cadence.html

Please consider adding `al2023` to supported AMIs/OSes. 

The `alinux2` AMI was EOL in Dec, 2020 - https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/

While RHEL8 is in `develop` and possibly released soon - https://github.com/aws/aws-parallelcluster/pull/5211 - the other operating system choices, `ubuntu1804`, `centos7` are at/near EOL. The `ubuntu2004` OS has a few more years, but we'd prefer to stay with an RPM distribution. RHEL8 requires an additional licensing cost.

https://github.com/aws/aws-parallelcluster/issues/4120 suggested adding Oracle, Rocky, or AlmaLinux 8 as the next step after `centos7` but there are no recent updates.

**Comment by joehellmersNOAA** [comment]
I will second this.  It would be very helpful to have AL 2023 supported. 

Perhaps it is possible to use EC2 Image Builder to do this prior to it being officially added?

**Comment by lukeseawalker** [comment]
Hello @nyetsche,
RHEL 8 is coming with next release (3.6), while alinux2 EOL is 2025-06-30, see https://aws.amazon.com/it/amazon-linux-2/faqs/. Support for alinux2023 is being considered, thanks for the feedback.

**Comment by mflevine** [comment]
Any update on this?

**Comment by enrico-usai** [comment]
Active development on this:
* https://github.com/aws/aws-parallelcluster-cookbook/pull/2343
* https://github.com/aws/aws-parallelcluster-cookbook/pull/2692

**Comment by mrgum** [comment]
I think this can be closed as per https://aws.amazon.com/about-aws/whats-new/2024/06/aws-parallelcluster-3-10-amazon-linux-2023-terraform/

**Comment by hanwen-pcluste** [comment]
Since ParallelCluster 3.10.0, Amazon Linux 2023 is supported.

Thank you
