### ISSUE TITLE
Inquiry on using Parallel Cluster 3 with Torque scheduler

### ISSUE THREAD

**Issue by cezfer** [aws/aws-parallelcluster#5225]
Dear Maintainers of Parallel Cluster,

I hope this message finds you well. I am reaching out to inquire about the usage of Parallel Cluster 3 with the Torque scheduler, and I would appreciate any guidance or information you can provide.

Specifically, I am interested in using Parallel Cluster 3 for a project, but I have a specific need to use the Torque scheduler. I have reviewed the documentation available online, but I have not found a clear answer to my question.

I would be grateful if you could provide any information or resources you have available regarding the compatibility of Parallel Cluster 3 with Torque, as well as any additional steps that may be necessary to use these systems together.

Thank you for your time and assistance, and I look forward to hearing back from you.

Best regards,

Cezar

**Comment by lukeseawalker** [comment]
Hello @cezfer,
ParallelCluster version 3 only supports Slurm and AWSBatch as schedulers.

Please notice that the Slurm installation shipped with ParallelCluster, comes with wrappers for Torque commands, see [official doc](https://slurm.schedmd.com/faq.html#torque) for more details.

**Comment by nyetsche** [comment]
@cezfer I haven't personally used Torque, but I believe it's derived from PBS. There's an "AWS Labs" tool with a similar spirit to ParallelCluster, `Scale-Out-Computing-on-AWS` or `SOCA`. https://github.com/awslabs/scale-out-computing-on-aws

The scheduler with SOCA is OpenPBS - https://github.com/awslabs/scale-out-computing-on-aws/blob/main/THIRD_PARTY_LICENSES.txt#L15 - there is no well defined way for a different scheduler, but you might be able to re-use significant parts of the software if Torque is "close enough".

Do note that SOCA isn't under active development and it's unclear what support, if any, AWS will give it going forward.
