### ISSUE TITLE
Confusing line/link in README.md

### ISSUE THREAD

**Issue by mrgum** [aws/aws-parallelcluster#5280]
The README.md has the line
```
Please reference installation instructions [in the AWS CDK documentaton](https://docs.aws.amazon.com/parallelcluster/latest/ug/install-v3.html).
```
Either the text of the link should be `in the AWS ParallelCluster documentation` or the link should be to CDK.

I'm not sure which is intended

**Comment by francesco-giordano** [comment]
Thank you for the heads up. Fixed in the PR above


Francesco
