### ISSUE TITLE
(3.2.0-3.5.1) GPU nodes not coming back online after `scontrol reboot`

### ISSUE THREAD

**Issue by francesco-giordano** [aws/aws-parallelcluster#5295]
## Bug description

After rebooting a GPU compute node via the `scontrol reboot` command available in the Slurm scheduler, the compute node may not come back online in the Slurm cluster because the slurmd daemon fails to start due to unavailability of GPU device files, causing the compute node to be unavailable to jobs.

This will lead to waste of instance time: the instance backing the compute node remains running until hitting the timeout defined as `ResumeTimeout` (by default 30 minutes), but it is not usable by Slurm jobs. After this timeout the compute node will be placed in DOWN state, causing ParallelCluster to reprovision it.

Support for Slurm-aware rebooting was introduced in ParallelCluster version 3.2.0: prior to this version this bug was already present, but there was no supported way to reboot compute nodes without the risk of ParallelCluster replacing the instance backing the node.

Please also be aware that versions between 3.2.0 and 3.4.1 were already affected by [a bug in the slurm reboot functionality](https://github.com/aws/aws-parallelcluster/issues/4751), therefore doing Slurm-aware rebooting of the compute nodes is not advisable in those versions.

### Affected versions (OSes, schedulers)

* ParallelCluster versions between 3.2.0 and 3.5.1 on all OSs.
* Only the Slurm scheduler is affected.
* Only compute nodes with NVIDIA GPUs are affected.

## Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.2.0-3.5.1)-GPU-nodes-not-coming-back-online-after-scontrol-reboot).

**Comment by enrico-usai** [comment]
Issue fixed on 3.6.0 release: https://github.com/aws/aws-parallelcluster/releases/tag/v3.6.0
