### ISSUE TITLE
NatGateway cost $2.40 every day

### ISSUE THREAD

**Issue by vwxyzjn** [aws/aws-parallelcluster#5359]
Hello, this is a cool project. I recently noticed the cluster costs $2.40 every day. This is quite surprising. What is `NatGateway` doing? I have deleted all the clusters and only left the parallelcluster UI running, but its [docs](https://docs.aws.amazon.com/parallelcluster/latest/ug/install-pcui-v3.html#install-pcui-costs-v3) suggests it should cost no more than a dollar per month. This NatGateway, however, costs $72 per month. 

<img width="771" alt="image" src="https://github.com/aws/aws-parallelcluster/assets/5555347/8a952f4d-a7d9-4ade-8f7a-b099a4186b17">

**Comment by enrico-usai** [comment]
Hi @vwxyzjn the Nat Gateway is required to permit the instances in the "private" subnet (i.e. compute nodes) to reach internet.

You can avoid it if you opt for a network configuration with [a single public subnet](https://docs.aws.amazon.com/parallelcluster/latest/ug/network-configuration-v3.html#network-configuration-v3-single-subnet).

If you're talking about a networking infrastructure part of Pcluster UI I'd suggest you to ask here: https://github.com/aws/aws-parallelcluster-ui

Thanks.
