### ISSUE TITLE
Resilliency

### ISSUE THREAD

**Issue by srknk8990** [aws/aws-parallelcluster#536]
We have SGE scheduler for our cfncluster. I have few questions regarding resiliency.

1.) If we submitted a job and somehow the compute node fails due to service 500 error, or gets terminated , what would happen to my jobs? DO i need to resubmit them?

2.) What if the same happens with the Master node ?

Is there any way the jobs could continue execution form the point where it got terminated, or can we keep an extra Master node in stand by to gain resiliency.  Something like having Shadow master which could take up the Master when it fails.(http://gridscheduler.sourceforge.net/howto/shadow.html)

Please guide on this. Is this achievable. 
If you could give some guiding directions on this, i could go ahead and try to achieve this.

**Comment by enrico-usai** [comment]
Hi @srknk8990 ,
CfnCluster permits to deploy and mantain HPC clusters but it does not deal with job management. 
This task is made by the Job Scheduler without any interference.

This means that if a compute node fails, CfnCluster doesn't resubmit the jobs, you need to resubmit them and as far as I know there are no ways to continue terminated jobs. 

In a CfnCluster environment the Compute Nodes are in an Auto Scaling Group so the terminated instance will be replaced by a new one and added to the cluster. 
The Master node is not part of an Auto Scaling Group, so it will not replaced if terminated. More details [here](https://cfncluster.readthedocs.io/en/latest/autoscaling.html).  

Currently there are no ways to configure a Shadow Master or something similar through CfnCluster.

**Comment by enrico-usai** [comment]
Hi @srknk8990, with SGE is possible to submit a job with the `-r yes` option (to have a re-runnable job).
http://gridscheduler.sourceforge.net/htmlman/htmlman1/qsub.html

**Comment by srknk8990** [comment]
@enrico-usai  Extreme thanks for the guiding directions on those, I just have one quick question for you.
 This is a generic HPC question. If we execute a job with the -r option then, the job would start from the beginning . is my assumption correct ?

I am trying to know if there is anyway,  a scheduler (for example - SGE) does the checkpointing for a job running on it? again I know that it also depends on the application if it does the self checkpointing, and then if it resubmits the job may be it can start from the point where it left after the compute node died abruptly.

but in case if the application does not do the checkpointing, is there any way possible to continue the job from the point where it left?



At this point I am very much concerned about the high availability for our cluster. covering 2 cases,

i) make system resilient when master dies, to continue the jobs even if master dies, either through Shadow master or anything that you may recommend me,
ii.) make system highly available, if compute node dies resubmit job from the point where it left on other Compute nodes.

I would request your views on above, also if you please recommend me some link or documentation for a read to me so that I can understand them, would be a great help. 

Again thanks in advance    @enrico-usai

**Comment by sean-smith** [comment]
@srknk8990 that's correct, `-r` re-runs the job. For checkpointing you can checkout sge's checkpointing interface: http://gridscheduler.sourceforge.net/howto/checkpointing.html

**Comment by enrico-usai** [comment]
Hi @srknk8990 , 

unfortunately we don't have many information to share about it. 
In ParallelCluster we have Torque, Slurm and SGE, so you can try to search in the appropriate websites or ask to the relative forums.

You could also think to use [AWS Batch](https://aws.amazon.com/batch/?nc1=h_ls), a fully managed batch processing service, with no Master and without the need to manage the compute nodes.

You could try it [with ParallelCluster](https://aws.amazon.com/it/blogs/opensource/aws-parallelcluster/) itself.
