### ISSUE TITLE
Slurm 23.02.2 sshare command core dumps

### ISSUE THREAD

**Issue by oyarzun** [aws/aws-parallelcluster#5372]
Parallel Cluster 3.6.0
Slurm 23.02.2

`sshare` command core dumps with the following error:

```
ubuntu@ip-10-0-0-133:/opt/slurm/bin$ sshare
sshare: error: plugin_load_from_file: dlopen(/opt/slurm/lib/slurm/priority_basic.so): /opt/slurm/lib/slurm/priority_basic.so: undefined symbol: job_list
sshare: error: Couldn't load specified plugin name for priority/basic: Dlopen of plugin file failed
sshare: error: cannot create priority context for priority/basic
sshare: fatal: failed to initialize priority plugin
```

Looks like this is fixed in Slurm 23.02.3 https://github.com/SchedMD/slurm/commit/b968136d8e762ca143fe8f7a020ffb17e1a2b4d1

**Comment by chenwany** [comment]
Thank you for reporting the issue! 
I will discuss with the team to understand when we plan to include the slurm version with the bug fix in our product

**Comment by enrico-usai** [comment]
Tracked internally, we're going to update it for the next release.

**Comment by enrico-usai** [comment]
Slurm upgraded to 23.11 as part of: https://github.com/aws/aws-parallelcluster/releases/tag/v3.9.0
