### ISSUE TITLE
Looking for some clarification as to what the HIT stacks are for

### ISSUE THREAD

**Issue by shairozan** [aws/aws-parallelcluster#5388]
**Required Info:**
 - 2.11.4

**Bug description and how to reproduce:**
There's no real bug, I just can't find a reference to it in the documentation from AWS, and the source code isn't exactly very clear on it. We utilize Parallel cluster but _not_ via `pcluster`. We have our own orchestration for it, but was uncertain as to what the HIT template was for in the repo. What differentiates it from the typical compute fleet?

**Comment by enrico-usai** [comment]
Hi @shairozan HIT was an internal acronym for Heterogeneous Instance Type (as opposed to SIT: Single Instance Type).

This was a way to distinguish between the two user flow. We introduced heterogeneous instance type support as part of [2.9.0](https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.md#290)

**Comment by shairozan** [comment]
Thanks! That's what I was looking for
