### ISSUE TITLE
Logs of onNodeStart

### ISSUE THREAD

**Issue by nobodyme** [aws/aws-parallelcluster#5394]
**Required Info:**
 - AWS ParallelCluster version: 3.6.0

I have attached onNodeStart script to a compute node,
the cluster is failing before the headnode itself is launched,

Where/How do I see the logs for what's causing this failure?
`cfn-init` from Cloudwatch doesn't seem to have the logs.

**Comment by davprat** [comment]
Hi @nobodyme - if the cluster is failing before the HeadNode instance is launched, then check the events for the cluster stack in the CloudFormation console.

**Comment by enrico-usai** [comment]
HI @nobodyme where you able to find the root cause of the issue?
