### ISSUE TITLE
(3.0.0-3.6.0) Ptrace_scope not disabled for Ubuntu compute nodes

### ISSUE THREAD

**Issue by dreambeyondorange** [aws/aws-parallelcluster#5410]
## (3.0.0-3.6.0) Ptrace_scope not disabled for Ubuntu compute nodes

Bug description

Libfabric and EFA require that classic ptrace permissions are set on any AMI that uses them for maximum performance. The default setting in Ubuntu for the ptrace_scope kernel parameter is to [restrict ptrace by default](https://www.kernel.org/doc/Documentation/security/Yama.txt).  This means EFA will operate with reduced bandwidth since the cross memory attach feature is not available. Only versions of PC 3.0 or greater running on Ubuntu are affected.  Starting with PC version 3.0, PC AMIs are configured with these default settings which prevented ptrace permissions from being set correctly. Because of this, customers using PC v3.0 and later will experience much lower EFA bandwith than expected on Ubuntu AMIs.

Affected versions (OSes, schedulers)

All currently release versions of ParallelCluster 3 (3.0.0-3.6.0) at time of writing are affected.  This only affects Ubuntu AMIs.

Mitigation

You can find a detailed explanation and the mitigation of the problem https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-3.6.0)-Ptrace_scope-not-disabled-for-Ubuntu-compute-nodes

**Comment by gmarciani** [comment]
The fix for this issue has been included in release 3.6.1.
