### ISSUE TITLE
DCV packages, amazon-ssm-agent using RPM SHA1 signature in RHEL8

### ISSUE THREAD

**Issue by nyetsche** [aws/aws-parallelcluster#5420]
In a RHEL8 instance, custom created with `ImageBuilder`, the following packages are flagged by Redhat as using a deprecated SHA1 signature:

```
# rpm -qa  --qf '%{NAME}-%{VERSION}-%{RELEASE} %{RSAHEADER:pgpsig}\n' | grep SHA1
nice-dcv-server-2023.0.15022-1.el7            RSA/SHA1, Fri 21 Apr 2023 09:15:56 AM UTC, Key ID 11b5c70a170c6114
nice-dcv-web-viewer-2023.0.15022-1.el7   RSA/SHA1, Fri 21 Apr 2023 09:16:17 AM UTC, Key ID 11b5c70a170c6114
nice-xdcv-2023.0.547-1.el7                          RSA/SHA1, Thu 06 Apr 2023 09:21:31 AM UTC, Key ID 11b5c70a170c6114
amazon-ssm-agent-3.2.985.0-1                   RSA/SHA1, Thu 11 May 2023 06:01:30 PM UTC, Key ID dd81a61756baa549
```

The operation of a RHEL8 pcluster continues, but it's considered deprecated, will be removed in RHEL9, and might be picked up by our other compliance scans (including `fips` mode, if we ever try and turn it on).

I also see that the release is `el7`, not `el8`, although I don't think that's make a functional difference.

( The code for these is in another repo, is the Issue best reported there? https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/cookbooks/aws-parallelcluster-platform/resources/dcv/partial/_rhel_common.rb#L33 )

**Comment by chenwany** [comment]
Hi, thanks for raising the concerns!

Nice DCV is a package that ParallelCluster installed on the headnode that enables users to securely connect to graphic-intensive 3D applications that are hosted on a remote high-performance server. 
It appears that both the `amazon-ssm-agent` and `Nice DCV` packages are signed using the SHA1 algorithm. Unfortunately, ParallelCluster does not have control in the signature algorithms used by these packages. But I will reach out to the package providers to let them know the concerns about their signing algorithms.

Thanks

**Comment by chenwany** [comment]
It looks like DCV have sha256 signing for both RHEL8 and RHEL9
See response from the DCV team:
>We have both. Getting the latest packages at https://download.nice-dcv.com/ and setting sudo update-crypto-policies --set FUTURE still allows the packages to be installed. This is both in RHEL8 and RHEL9
I did the same check in RHEL8 and RHEL9. In both of them SHA256 is shown:
RHEL8
rpm -qa  --qf '%{NAME}-%{VERSION}-%{RELEASE} %{RSAHEADER:pgpsig}\n' | grep nice
nice-dcv-gl-2023.0.1039-1.el8 RSA/SHA256, Thu 29 Jun 2023 10:50:54 AM UTC, Key ID 11b5c70a170c6114
nice-dcv-server-2023.0.15487-1.el8 RSA/SHA256, Fri 30 Jun 2023 01:05:36 PM UTC, Key ID 11b5c70a170c6114
nice-dcv-web-viewer-2023.0.15487-1.el8 RSA/SHA256, Fri 30 Jun 2023 01:06:43 PM UTC, Key ID 11b5c70a170c6114
nice-xdcv-2023.0.551-1.el8 RSA/SHA256, Tue 27 Jun 2023 10:12:40 AM UTC, Key ID 11b5c70a170c6114
nice-dcv-gltest-2023.0.318-1.el8 RSA/SHA256, Mon 27 Mar 2023 08:09:51 AM UTC, Key ID 11b5c70a170c6114
nice-dcv-simple-external-authenticator-2023.0.208-1.el8 RSA/SHA256, Thu 04 May 2023 12:45:46 PM UTC, Key ID 11b5c70a170c6114
RHEL9
$ rpm -qa  --qf '%{NAME}-%{VERSION}-%{RELEASE} %{RSAHEADER:pgpsig}\n' | grep nice
nice-dcv-server-2023.0.15487-1.el9 RSA/SHA256, Fri Jun 30 13:08:01 2023, Key ID 11b5c70a170c6114
nice-dcv-gltest-2023.0.318-1.el9 RSA/SHA256, Mon Mar 27 08:09:23 2023, Key ID 11b5c70a170c6114
nice-dcv-gl-2023.0.1039-1.el9 RSA/SHA256, Thu Jun 29 10:49:47 2023, Key ID 11b5c70a170c6114
nice-xdcv-2023.0.551-1.el9 RSA/SHA256, Tue Jun 27 10:13:00 2023, Key ID 11b5c70a170c6114
nice-dcv-web-viewer-2023.0.15487-1.el9 RSA/SHA256, Fri Jun 30 13:08:00 2023, Key ID 11b5c70a170c6114
nice-dcv-simple-external-authenticator-2023.0.208-1.el9 RSA/SHA256, Thu May  4 12:45:01 2023, Key ID 11b5c70a170c6114
Only RHEL7 we use SHA1
rpm -qa  --qf '%{NAME}-%{VERSION}-%{RELEASE} %{RSAHEADER:pgpsig}\n' | grep nice
nice-dcv-gltest-2023.0.320-1.el7 RSA/SHA1, Fri 12 May 2023 11:43:01 AM UTC, Key ID 11b5c70a170c6114
nice-dcv-web-viewer-2023.0.15477-1.el7 RSA/SHA1, Thu 29 Jun 2023 09:10:06 AM UTC, Key ID 11b5c70a170c6114
nice-xdcv-2023.0.550-1.el7 RSA/SHA1, Tue 27 Jun 2023 10:10:10 AM UTC, Key ID 11b5c70a170c6114
libnice-0.1.3-4.el7 RSA/SHA256, Fri 04 Jul 2014 03:02:13 AM UTC, Key ID 24c6a8a7f4a80eb5
nice-dcv-server-2023.0.15477-1.el7 RSA/SHA1, Thu 29 Jun 2023 09:10:03 AM UTC, Key ID 11b5c70a170c6114


Thanks
