### ISSUE TITLE
ParallelCluster UI GET /cost-monitoring fails in UIs deployed in non-payer accounts

### ISSUE THREAD

**Issue by christianversloot** [aws/aws-parallelcluster#5479]
If you have an active AWS support contract, please open a case with AWS Premium Support team using the below documentation to report the issue:
https://docs.aws.amazon.com/awssupport/latest/user/case-management.html

Before submitting a new issue, please search through open [GitHub Issues](https://github.com/aws/aws-parallelcluster/issues) and check out the [troubleshooting documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3.html).

Please make sure to add the following data in order to facilitate the root cause detection.

**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.6.0
 - Full cluster configuration without any credentials or personal data. `nonrelevant`
 - Cluster name: `infoplaza-hpc-cluster`
 - Output of `pcluster describe-cluster` command. `nonrelevant`
 - [Optional] Arn of the cluster CloudFormation main stack: `nonrelevant`

**Bug description and how to reproduce:**
I've recently deployed the newest version of ParallelCluster UI using the templates in AWS documentation. It all works nicely, except for one thing, being that I'm being bombarded with error messages whenever I try doing something:

![image](https://github.com/aws/aws-parallelcluster/assets/6450612/30b44a33-94e2-43e6-aa75-8c8e55ef6585)

I investigated - and the browser console suggests that these come from `GET /cost-monitoring` in the UI-deployed API:

```
Failed to load resource: the server responded with a status of 400 ()
GET /cost-monitoring
```

Further investigation leads to this in CloudWatch:

```
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the ListCostAllocationTags operation: Failed to list Cost Allocation Tags: Linked account doesn't have access to cost allocation tags.
```

From our SA's advice, we've deployed everything into a sub account (with a payer account being present), so enabling them / accessing them is impossible from this sub account:

![image](https://github.com/aws/aws-parallelcluster/assets/6450612/9638169b-3a11-459c-9c45-24d5543c9a4b)

Hence, it makes sense that the Lambda fails, but this is an issue for us - as it makes using the UI very annoying (think 5 such messages every few seconds when you try doing something).

I've Googled but I haven't found anything related to enabling it at sub account level.

Please let me know if you need more info :)

**Comment by EddyMM** [comment]
Hello @christianversloot,
I recommend opening the issue in the [aws-parallelcluster-ui](https://github.com/aws/aws-parallelcluster-ui) repository.
Could you also confirm the region where the UI is running from as well as if you're using the most recent version of ParallelCluster UI?
We recently released a bugfix related to Cost Monitoring being unsupported in GovCloud (June 7, 2023 [See Release notes and document history](https://docs.aws.amazon.com/parallelcluster/latest/ug/document_history.html)).
