### ISSUE TITLE
(3.0.0 - 3.8) Interactive job submission through srun can fail after increasing the number of compute nodes in the cluster

### ISSUE THREAD

**Issue by NSsirena** [aws/aws-parallelcluster#5538]
## Bug description

ParallelCluster allows to extend the size of a cluster without imposing the requirement to stop the compute fleet. Extending the size of a cluster includes adding new queues to the scheduler, new compute resources within a queue, or increasing  [MaxCount](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeResources-MaxCount) of a compute resource.

According to the documentation of Slurm reported below, adding or removing nodes from a cluster requires to restart both the `slurmctld` on the head node and the `slurmd` on all the compute nodes.

From https://slurm.schedmd.com/slurm.conf.html#SECTION_NODE-CONFIGURATION:

> The configuration of nodes (or machines) to be managed by Slurm is also specified in /etc/slurm.conf. Changes in node configuration (e.g. adding nodes, changing their processor count, etc.) require restarting both the slurmctld daemon and the slurmd daemons. All slurmd daemons must know each node in the system to forward messages in support of hierarchical communications.

The  `slurmctld` on the head node is restarted during a cluster update operation, but the `slurmd` daemons running on the compute nodes are not.
While there is no impact on the job submission through `sbatch` (neither in calls to `srun` within a batch job submitted via `sbatch`), missing to restart `slurmd` on the compute fleet when adding new nodes to the cluster may have an impact on direct `srun` interactive job submissions: 

* `srun` jobs involving both new and old nodes, with communications from old to new nodes, are affected: if at any time an old node must propagate a Slurm RPC to a new node, this propagation will fail, leading the whole `srun` to fail;
* `srun` jobs ending only on new nodes are not impacted because the nodes have just started all together so they know about others;
* `srun` jobs ending only on old nodes are not impacted because all nodes already know each other;
* single-node `srun` are not affected.

## The error message

The error message shown when facing this issue is

`run: error: fwd_tree_thread: can't find address for host <hostname>, check slurm.conf`

## Affected versions (OSes, schedulers)

* ParallelCluster 3.0.0 - latest
* Slurm scheduler

## Mitigation
See Wiki page
* [(3.0.0 ‐ latest) Interactive job submission through srun can fail after increasing the number of compute nodes in the cluster](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-%E2%80%90-latest)-Interactive-job-submission-through-srun-can-fail-after-increasing-the-number-of-compute-nodes-in-the-cluster)

**Comment by joehellmersNOAA** [comment]
Hello.  I've tried these instructions to not avail.  Is there a time frame when this problem might be addressed?

https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-%E2%80%90-latest)-Interactive-job-submission-through-srun-can-fail-after-increasing-the-number-of-compute-nodes-in-the-cluster

https://github.com/aws/aws-parallelcluster/issues/5538

https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-fc-v3-run-job.html

**Comment by lukeseawalker** [comment]
This is going to be resolved in 3.9.0

**Comment by himani2411** [comment]
Released as part of [v3.9.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.9.0)
