### ISSUE TITLE
(3.0.0-3.7.2) Cluster update rollback can fail when modifying the list of instance types declared in the Compute Resources

### ISSUE THREAD

**Issue by chenwany** [aws/aws-parallelcluster#5598]
## Bug description

During a cluster update it is possible to change the list of instance types declared in a compute resource (`Scheduling/SlurmQueues/`[`ComputeResources`](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#Scheduling-v3-SlurmQueues-ComputeResources)), by modifying the `InstanceTypes` or `InstanceType` configuration parameter.

This change alone does not cause any issue, but if there is a problem during the cluster update (e.g. connection to Slurm Accounting Database goes wrong) and the whole operation fails, the cluster update rollback will also fail and the stack will go in the `UPDATE_ROLLBACK_FAILED` state.

By looking at the `/var/log/chef-client.log` file from the head node instance it’s possible to find an error like: `ERROR - Failed to generate slurm configurations, exception: '<old-instance-type>'`.

## Affected versions (OSes, schedulers)

* ParallelCluster 3.0.0 - 3.7.2
* Slurm scheduler

## Mitigation

See Wiki page [(3.0.0-3.7.2) Cluster update rollback can fail when modifying the list of instance types declared in the Compute Resources](https://github.com/aws/aws-parallelcluster/wiki/(3.0.0%E2%80%903.7.2)-Cluster-update-rollback-can-fail-when-modifying-the-list-of-instance-types-declared-in-the-Compute-Resources)

**Comment by enrico-usai** [comment]
Fix released as part of [3.8.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.8.0)
