### ISSUE TITLE
Amazon Linux 2

### ISSUE THREAD

**Issue by karlvirgil** [aws/aws-parallelcluster#567]
It seems that when
`base_os = alinux
`is selected that Amazon Linux gets used as the OS to create the cluster
However, I'd like to use [Amazon Linux 2](https://aws.amazon.com/amazon-linux-2/) to create the cluster.  Is this option available, and if not, can it be added?

Karl

**Comment by sean-smith** [comment]
Unfortunately it's not an option yet. Stay tuned, we'll update this issue when we add support.

**Comment by andyjones1982** [comment]
I would also like to be able to use Amazon Linux 2

**Comment by kdyb** [comment]
Here is one way to use Amazon Linux 2
https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fdev.classmethod.jp%2Fcloud%2Faws%2Fal2-cfncluster-and-pyenv%2F

**Comment by ronlaren** [comment]
Seems like this is still true a year later (using parallel cluster 2.5.0)... Unfortunately Amazon Linux 1 is really out of date by know, seems like amazon linux 2 should be the default...

**Comment by rmarable** [comment]
Has there been any update on this?

**Comment by lukeseawalker** [comment]
No updates yet on this

**Comment by rmarable** [comment]
Thanks @lukeseawalker, I appreciate the feedback.

**Comment by lukeseawalker** [comment]
AWS ParallelCluster 2.6.0 with Amazon Linux 2 support has been released
