### ISSUE TITLE
How to stop compute fleet when parallelcluster is setup via CloudFormation? 

### ISSUE THREAD

**Issue by francisreyes-tfs** [aws/aws-parallelcluster#5675]
I have made changes to my CloudFormation template with regards to [parallelcluster via Cloudformation. ](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_09_cfn-custom-resource-v3.html) and it requires me to stop the compute fleet. How can this be done by CF? or do I need to stop it via command line?

**Comment by EddyMM** [comment]
Hello @francisreyes-tfs ,

It's likely that the updates you made to the cluster require stopping the compute fleet. You can update the cluster's [QueueUpdateStrategy](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmSettings-QueueUpdateStrategy) to define the behaviour you want for the changes you've made to the queue.

The alternative would be to use the CLI: [pcluster update-compute-fleet ](https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.update-compute-fleet-v3.html)

You can refer to the documentation for further info: [AWS CloudFormation custom resource / Cluster operations](https://docs.aws.amazon.com/parallelcluster/latest/ug/cloudformation-v3.html#cfn-cluster-ops)

> If you update the cluster configuration defined in the stack, according to configuration update policies, CloudFormation updates the cluster. The AWS ParallelCluster custom resource provider doesn't stop the compute fleet before updating the cluster. We recommend that you use the [QueueUpdateStrategy](https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmSettings-QueueUpdateStrategy) setting for cluster updates. This way, you can avoid making explicit pcluster update-compute-fleet calls before and after updates when using the AWS ParallelCluster custom resource.

**Comment by francisreyes-tfs** [comment]
Thanks for the reply. I think this will be the way to go.
