### ISSUE TITLE
cluster update with ebs_volume_id

### ISSUE THREAD

**Issue by wjaskowski** [aws/aws-parallelcluster#570]
I have an existing volume, so in the config of cfncluster I specify `ebs_volume_id`. Works without problems, it is mounted on `/home/ubuntu/shared` as I specified in the config. But then when I want to `cfncluster update` I get: 
```
Updating: cluster
Volume vol-xxxxxxxx is in state 'in-use' not 'available'
```
Is that a bug or a feature? How should I get around that?

**Comment by sean-smith** [comment]
it's a bug, it checks the attachment state of the volume when you do an update. You can try turning off config sanity `config_sanity = false` in the cfncluster config.

**Comment by wjaskowski** [comment]
Thx. The workaround works.

**Comment by enrico-usai** [comment]
This code has been totally refactored as part of  the #1298 

The update instead has been improved as part of the #1583
With this patch, the `pcluster update` command will check for the updatablity of each detected change and will prevent the update from being run if any change is marked as not safe or not possible.

Currently the update of the `ebs_volume_id` is not supported.

**Comment by enrico-usai** [comment]
Release [2.8.0](https://github.com/aws/aws-parallelcluster/releases/tag/v2.8.0) is out (and [2.8.1](https://github.com/aws/aws-parallelcluster/releases/tag/v2.8.1) too). One of the enhancements of the 2.8.0 is: _"Renewed user experience and robustness of cluster update functionality"_ and this failure during the update will be prevented.

I'm going to close this issue, feel free to open a new one if you encounter similar problems.
