### ISSUE TITLE
Login Nodes with support for  `OnNodeStart`, `OnNodeConfigured` (and possibly `OnNodeUpdated`) ?

### ISSUE THREAD

**Issue by michaelmayer2** [aws/aws-parallelcluster#5723]
I am really grateful for all the new features that are being released with each new ParallelCluster Release. 

I am particularly excited about the ability to add Login Nodes to the Cluster which simplifies the otherwise [rather complex workflow](https://github.com/aws/aws-parallelcluster/wiki/ParallelCluster:-Launching-a-Login-Node) considerably. 

Wondering if it would be possible to allow `OnNodeStart`, `OnNodeConfigured` (and possibly `OnNodeUpdated`) for the [Login Nodes type](https://docs.aws.amazon.com/parallelcluster/latest/ug/LoginNodes-v3.html) as well ? It would simplify setup and reduce the need for different AMI's for HeadNode, LoginNode and ComputeNode types.

**Comment by joehellmersNOAA** [comment]
Yes, I love the new login nodes feature as well, but it would be the cat's meow if I could configure it like I do the other nodes without having to make an AMI.

**Comment by enrico-usai** [comment]
Hi @michaelmayer2

this is a known gap that we missed to introduce in the first version of login nodes feature.
I'll mark it as feature enhancement, thanks!

Enrico

**Comment by snemir2** [comment]
Any eta on rolling this out?
Having OnNodeStart, OnNodeConfigured would really make the solution so much better.

**Comment by samcofer** [comment]
Just wanted to check and see if there was a status update on this feature?

**Comment by jagga13** [comment]
Any update on this feature?  We would also be interested in this feature and if it is not available will have to use terraform code to spin up our own LoginNode and LB infrastructure to support.  Would prefer not to do this if it is close to being released.

Thanks.

**Comment by ssyed85** [comment]
in case if anyone's interested, here's an ugly hack (that worked in version 3.9.1) !
- get the launch template data of your login node and append commands at the end of UserData section
- then create a new version of the template, something like aws ec2 create-launch-template-version --launch-template-name "$template_name" --launch-template-data "$updated_template_data" --region "$AWS_REGION"
- then modify existing template with new default version, something like aws ec2 modify-launch-template --launch-template-name "$template_name" --default-version "$newVersion" --region "$AWS_REGION"

**Comment by michaelmayer2** [comment]
Seems like finally good news are coming with AWS ParallelCluster 3.11.0  according to https://github.com/aws/aws-parallelcluster/commit/2a13ae6eee7382b1137c9af9d6c884215444d8bc and https://github.com/aws/aws-parallelcluster/blob/develop/CHANGELOG.md. 

Can't wait to get a beta version of 3.11.0 going.

**Comment by michaelmayer2** [comment]
Seems like this is now available in 3.11.0, however https://github.com/aws/aws-parallelcluster/issues/6507 remains to be addressed.

**Comment by hanwen-pcluste** [comment]
You are right. This feature has been included since 3.11.0. I am closing this issue
