### ISSUE TITLE
Feature Request: Munge key from AWS Secrets Manager

### ISSUE THREAD

**Issue by mrgum** [aws/aws-parallelcluster#5729]
I'd like Parallel Cluster to have an option to get the munge key from AWS Secrets Manager.

I run mulitple slurm PC clusters in a federation and use A/B clusters for upgrades and maintenance. At present each cluster gets its own munge key so I cannot, for example, look at jobs on one cluster from the other.

I can copy the munge key from one cluster and restart munge and slurmctld on another clusters headnode.  This lets one cluster's headnode talk to the other however then when new compute nodes come up in that cluster the jobs fail as the compute nodes no longer have the same munge key as their head node (they keep the one that was created as part of the cluster)

**Comment by enrico-usai** [comment]
Hi @mrgum

this feature enh is under development: https://github.com/aws/aws-parallelcluster/pull/5681

Enrico

**Comment by mrgum** [comment]
Thank you @enrico-usai

**Comment by enrico-usai** [comment]
Released as part of [3.8.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.8.0)
