### ISSUE TITLE
spot hourly increments

### ISSUE THREAD

**Issue by karlvirgil** [aws/aws-parallelcluster#582]
I noticed on the description of spot instances that they can now be reserved for predefined durations:

https://aws.amazon.com/ec2/spot/pricing/

> Spot instances are also available to run for a predefined duration – in hourly increments up to six hours in length – at a discount of up to 30-50% compared to On-Demand pricing.

Is cnfcluster equipped to specify a request for a specific hourly increment?

Karl

**Comment by fnubalaj** [comment]
Unfortunately, no. We use autoscaling group to launch spot instances and neither that nor the cloudformation template support this feature.

**Comment by isobit** [comment]
It looks like CloudFormation now supports [specifying `BlockDurationMinutes` on EC2 launch templates](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-instancemarketoptions-spotoptions.html#cfn-ec2-launchtemplate-launchtemplatedata-instancemarketoptions-spotoptions-blockdurationminutes). Could this be reopened until PR #1496 is merged?

**Comment by demartinofra** [comment]
From https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#fixed-duration-spot-instances

Spot Instances with a defined duration (also known as Spot blocks) are no longer available to new customers from July 1, 2021. For customers who have previously used the feature, we will continue to support Spot Instances with a defined duration until December 31, 2022.
