### ISSUE TITLE
nodes autostart issues 

### ISSUE THREAD

**Issue by extremoburo** [aws/aws-parallelcluster#583]
Hi all, 

I'm using version 1.5.4 and I'm having issues with nodes autostart , neither default nor my own scaling up config is doing well. 

how to reproduce:

1 - start a cluster using the below pasted configuration.
2 - ssh to the master node
3 - run a simple mpi test script asking for 8 slots 

script:
`
#! /bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -N mpi_pe_test 
#$ -pe mpi 8

/usr/lib64/openmpi/bin/mpirun -np 8 hostname
`
I was expecting from my scale up policy to see 4 nodes of type t2.medium ( 2 slots each ) to attach SGE but so the job would start, instead I had 13 nodes in the ASG settings and only 4 out of 13 attached and the job could finish, otherwise it would have triggered more and more I guess. Maybe I need to increase the scaling_cooldown ? or maybe I'm hitting some bug ? I don't understand why if I set the desired_capacity from console nodes attach to SGE easly and quickly while with autostart sometimes they don't attach. 

BTW: I'm using te.medium for testing but I've faced similar problems with c4.xlarge and c5.xlarge, c5.2xlarge 

Any tip would be rellay appreciated. thks 

`[cluster biogps_c5]
 key_name = key
 vpc_settings = clusterVPCextended
 base_os = centos6
 cwl_region = us-east-1
 master_instance_type = t2.medium
 compute_instance_type = t2.medium
 tags = {"App" : "test" }
 scheduler = sge
 ec2_iam_role = CfnclusterEC2RoleCustom
 post_install = urltomyscript/myscript.sh
 initial_queue_size = 1
 max_queue_size = 32
 maintain_initial_size = true
 cluster_type = spot
 spot_price = 0.05
 scaling_settings = medium

 [scaling medium]
 scaling_period = 60
 scaling_cooldown = 300
 scaling_threshold = 8
 scaling_adjustment = 4

 [vpc clusterVPCextended]
 vpc_id = vpc-12345678910
 master_subnet_id = subnet-12345678910
`

**Comment by fnubalaj** [comment]
Can you try the same with our latest release candidate. 1.6.0rc2?

Thanks

**Comment by extremoburo** [comment]
Before I report my results I'd like to inform that I had to add 2 this in my custom IAM Instance Policy:

`                
"autoscaling:DescribeTags",
"autoScaling:UpdateAutoScalingGroup"
`
Then I was able to start the cluster , and I've realized 2 things: 

1)
nodeswatcher in the nodes is failing with:

`An error occurred (AccessDenied) when calling the DescribeStacks operation: User: arn:aws:sts::USERID:assumed-role/CfnclusterEC2RoleCustom/blabla is not authorized to perform: cloudformation:DescribeStacks on resource: ....`

which is quite explicit I need to give more privileges to my User. could you tell me where to add this one ? 

2) 
I'm having some issues with the post_init script cause in 2 out of 4 nodes its failing, but why I wonder... 

It looks like this version is scaling well, I mean the ASG desired_capacity was correct but only one new node attached ( 1 was started and attached from the beginning as from my config ) , the other two didn't attach to SGE , I guess because my post_init script failed in 2 of them. I will check my script and restart the cluster.

**Comment by sean-smith** [comment]
The `CfnclusterEC2RoleCustom` that you specify in your config files needs those permissions. It sounds like the pre-validation of your iam role didn't catch the missing `DescribeStacks` permission. 

Can you confirm that you have `config_sanity = true` set in your config?

**Comment by sean-smith** [comment]
We've updated the code so that you'll get warned about the missing `DescribeStacks` permission before cluster creation. This code will be included in the 1.6.0 release https://github.com/awslabs/cfncluster/pull/586

For now just add `cloudformation:DescribeStacks` permissions in your iam role, the change is documented here: 

https://cfncluster.readthedocs.io/en/develop/iam.html (just change the version to develop in the lower right hand corner)

**Comment by extremoburo** [comment]
hi Sean, 

yes I have config_sanity = true 

but my User IAM policy is correct , could it be that I have to add `cloudformation:DescribeStacks` somewhere in the Istance IAM policy instead ?

**Comment by sean-smith** [comment]
You'll need to add it to the instance policy`CfnclusterEC2RoleCustom` that you specify in the config.

**Comment by extremoburo** [comment]
hello, 

fixed by adding to the Instance policy this: 

`        {
            "Sid": "CloudFormationDescribe",
            "Action": [
                "cloudformation:DescribeStacks"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
`

and it is actually working fine, it's really responsive on triggering new nodes but maybe too fast terminating nodes. It's so fast that sometimes I couldn't take 10 min to modify a job and re-run. maybe scaling_cooldown is not anymore considered ? 

in anyway 1.6 is the right way to go :+1:

**Comment by lukeseawalker** [comment]
Hi @extremoburo,
thank you for the feedback.
The configuration "scaling_cooldown" is not valid anymore in 1.6.
You can configure the amount of time in minutes without a job after which the compute node will terminate see https://cfncluster.readthedocs.io/en/develop/configuration.html#scaledown-idletime

L
