### ISSUE TITLE
Accessing ParallelCluster cluster name in boostrap scripts

### ISSUE THREAD

**Issue by joehellmersNOAA** [aws/aws-parallelcluster#5879]
Is there a way to access the cluster name inside a boostrap script?  I can find it from the /etc/parallelcluster/cfnconfig file, but I was hoping for a more seemless method, like and environment variable or something.

**Comment by hanwen-pcluste** [comment]
Hello Joe,

Unfortunately, getting the cluster name from `/etc/parallelcluster/cfnconfig` or `/etc/chef/dna.json` is the only method.
If you would like to make this as a feature request, can you tell us more about your use case?

Thank you,
Hanwen

**Comment by joehellmersNOAA** [comment]
OK.  I was able to simply source the cfnconfig file and simply use the variables defined there in my script.

Thanks.
