### ISSUE TITLE
Feature request:  price-capacity-optimized

### ISSUE THREAD

**Issue by gns-build-server** [aws/aws-parallelcluster#6058]
We have been using Parallelcluster 2.x with SGE for quite some time, manually editing the autoscaling groups, and using the "price-capacity-optimized" spot allocation strategy introduced to ASGs in late 2022:  https://aws.amazon.com/blogs/compute/introducing-price-capacity-optimized-allocation-strategy-for-ec2-spot-instances/

We've more recently switched to Parallelcluster 3 with Slurm, and find that our only AllocationStrategy options are "lowest-price" or "capacity-optimized".  We'd like to be able to use price-capacity-optimized, but it's not an option:  
https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-AllocationStrategy

I suspect many here may be very interested in having this AllocationStrategy available.

Thanks,
Dan

**Comment by hgreebe** [comment]
I have added this feature request to our backlog.

**Comment by mflevine** [comment]
I have made a pull request for this feature. It would be great for someone from AWS team to review.
