### ISSUE TITLE
Packages used to build base ubuntu 16.04 AMI

### ISSUE THREAD

**Issue by adavanisanti** [aws/aws-parallelcluster#606]
Is there a list of packages that are installed on the base `cfncluster` AMI for ubuntu 16.04? I am looking for all the `apt-get ` or `apt` steps done. 

Appreciate your help!

**Comment by sean-smith** [comment]
See https://github.com/awslabs/cfncluster-cookbook/blob/develop/attributes/default.rb#L105

All the distro's are in there.

**Comment by adavanisanti** [comment]
Thanks, @sean-smith!
