### ISSUE TITLE
install NFS daemon

### ISSUE THREAD

**Issue by maestro7879** [aws/aws-parallelcluster#6065]
Attempting to build an image using a hardened AWS AL2 AMI and receiving the below errors.

Error executing action `setup` on resource 'nfs[install NFS daemon]'.

FATAL: Mixlib::ShellOut::ShellCommandFailed: nfs[install NFS daemon] (aws-parallelcluster-environment::install line 16) had an error: Mixlib::ShellOut::ShellCommandFailed: service[statd] (nfs::_common line 56) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'

**Comment by judysng** [comment]
Hi, what version of pcluster are you using, and could you provide your build image config file? Can you also run `pcluster export-image-logs` and upload the logs: https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.export-image-logs-v3.html ?

**Comment by maestro7879** [comment]
> Hi, what version of pcluster are you using, and could you provide your build image config file? Can you also run `pcluster export-image-logs` and upload the logs: https://docs.aws.amazon.com/parallelcluster/latest/ug/pcluster.export-image-logs-v3.html ?
pcluster version
{
  "version": "3.8.0"
}

IMAGE_CONFIG
Build:
 InstanceType: t3.xlarge
 ParentImage: ami-0ea65a9hwsdhh34
 SubnetId: subnet-04b8cf582355b45
 SecurityGroupIds: 
   - sg-0f39076344bfd9da
 Imds:
   ImdsSupport: v2.0
 Iam:
   InstanceProfile: arn:aws:iam::45333550383:instance-profile/asdf-asdf-imagebuild-instancerole
   PermissionsBoundary: arn:aws:iam::45333550383:policy/asdf-asdf-asdf-permissions-boundary
   CleanupLambdaRole: arn:aws:iam::45333550383:role/system/asdf-lambda-execution-role
Image:
  RootVolume:
    Size: 80

I'd have to work on getting the logs exports.

**Comment by maestro7879** [comment]
I have not been able to export the logs.

Is there any information on what is trying to be done related to NFS ? 
I assume just install and start the service ?

**Comment by enrico-usai** [comment]
Hi @maestro7879 sorry for the delay, I hope you've been able to solve your issue in the meantime.

Anyway, I'll try to add here some context.

1. [these](https://github.com/aws/aws-parallelcluster-cookbook/blob/955ad4c8ccf6c868e66ee4336a1271fe99386eae/cookbooks/aws-parallelcluster-environment/recipes/install.rb#L16) are the steps executed at AMI creation time. 
2. The [nfs resource](https://github.com/aws/aws-parallelcluster-cookbook/blob/955ad4c8ccf6c868e66ee4336a1271fe99386eae/cookbooks/aws-parallelcluster-environment/resources/nfs/partial/_install_nfs4_and_disable.rb) behind the scenes tries to install [nfs official cookbooks](https://github.com/sous-chefs/nfs)
3. In your case nfs installation is failing in the [line 56 of _common.rb](https://github.com/sous-chefs/nfs/blob/main/recipes/_common.rb#L56) from nfs third party cookbook, while trying to start the [statd service](https://github.com/sous-chefs/nfs/blob/e4f0f4eb463e51271fa02dc29c9a3f8b223bfa30/attributes/default.rb#L115)

This is out of ParallelCluster control. To try to debug why `statd` is not starting you can try to manually start it in your AMI and check the logs.
