### ISSUE TITLE
Integrate parallelcluster deployment with Terraform

### ISSUE THREAD

**Issue by jagga13** [aws/aws-parallelcluster#6092]
Hello,

I am currently using ParallelCluster 3.8.0 and we would like to see if there is a way for us to trigger the ParallelCluster deployment via Terraform.  Is there a way for me to get access to the CloudFormation stack that can be deployed via Terraform using the cluster config that we typically pass to via the pcluster api?  We are trying to automate as much of the deployment as possible and we are a terraform shop.  Any insight or help would be greatly appreciated!

Thanks.

**Comment by gmarciani** [comment]
Hi @jagga13 thanks for your interest in using ParallelCluster with Terraform.
We are actively working on adding support for ParallelCluster with Terraform.
We do not have a precise delivery date for of this project, but it should be within Q2 2024.

**Comment by hongbo-miao** [comment]
Came from https://stackoverflow.com/questions/76104786/does-terraform-aws-provider-allow-to-create-aws-parallel-cluster-instances
We're also interested in utilizing Terraform to automate the provisioning of AWS ParallelCluster instances.
This automation will greatly facilitate the use of high-performance computing (HPC) in the cloud. Thanks! ☺️

**Comment by alemairebe** [comment]
Hi @jagga13 ,
Did you saw this module : https://github.com/aws-tf/terraform-aws-parallelcluster ?

**Comment by gmarciani** [comment]
Hi all,

the first alpha version has been released! 
Stay tuned for the first official release coming soon.

You can find the AWS ParallelCluster Provider at https://registry.terraform.io/providers/aws-tf/aws-parallelcluster/latest
You can find the AWS ParallelCluster Module at https://registry.terraform.io/modules/aws-tf/parallelcluster/aws/latest

**Comment by hanwen-pcluste** [comment]
Hi all,

ParallelCluster Terraform integration is officially released!

You can find the AWS ParallelCluster Provider at https://registry.terraform.io/providers/aws-tf/aws-parallelcluster/latest
You can find the AWS ParallelCluster Module at https://registry.terraform.io/modules/aws-tf/parallelcluster/aws/latest
