### ISSUE TITLE
Accelerate creating cfncluster

### ISSUE THREAD

**Issue by SunPj** [aws/aws-parallelcluster#612]
Is there a way to accelerate creating cfncluster? I am new at that. I just use default cfn cluster template.

**Comment by mauri-melato** [comment]
If you are not doing anything custom (e.g. a long post_install script) a plain cluster creation should take around 10 minutes.
We know there is room for improvement on the cluster creation time but at the moment there is not so much you can do to accelerate.

**Comment by mukulagrawal78** [comment]
Would switching off library download and making them part of a custom AMI help?
I am not sure which step takes so long in the process?

**Comment by lukeseawalker** [comment]
Cluster creation time has been reduced since AWS ParallelCluster 2.4.1, see changelog https://github.com/aws/aws-parallelcluster/releases/tag/v2.4.1
