### ISSUE TITLE
Installation error about botocore version

### ISSUE THREAD

**Issue by guorongxu** [aws/aws-parallelcluster#613]
Hi cfncluster team,

I tried to install the latest version of cfncluster on a new amazon linux box. But I got the error as the attached screenshot.
![screen shot 2018-11-01 at 12 28 25 pm](https://user-images.githubusercontent.com/19211919/47874762-dec29e80-ddd1-11e8-8c0e-581e7c44ef75.png)

The python version is default: Python 2.7.14
I searched the related posts but I did not find any helpful posts to solve this issue. I can easily reproduce this issue, but I don't have this issue with my old version cfncluster (v1.4.2).

Thanks,
Guorong

**Comment by mauri-melato** [comment]
Hi Guorong, 

you need an updated version of botocore. The tool [easy_install](https://setuptools.readthedocs.io/en/latest/easy_install.html) is deprecated and as we can see here https://packaging.python.org/discussions/pip-vs-easy-install it doesn't update dependencies as `pip` does instead.

You may want to install cfncluster via `sudo pip install cfncluster`

Thanks

**Comment by guorongxu** [comment]
Hi mauri-melato,

Thanks for your response!
After I ran the pip to install cfncluster, I still got another issue that awscli requires botocore==1.10.79. Please see the attached screenshot. 
![screen shot 2018-11-02 at 10 05 23 am](https://user-images.githubusercontent.com/19211919/47929746-425ad380-de87-11e8-89be-9c458cee39e8.png)

If I installed the awscli with pip, the pip will automatically uninstalled botocore-1.12.36 and installed botocore-1.10.79. then the cfncluster cannot ran anymore. Looks like the cfncluster has conflict with awscli. 
![screen shot 2018-11-02 at 10 05 40 am](https://user-images.githubusercontent.com/19211919/47929874-8f3eaa00-de87-11e8-9e57-4cf83bf222ed.png)

Do you have any solution?

Thanks,
Guorong

**Comment by guorongxu** [comment]
After I ran the below commands, I solved the issue.
sudo yum install python-pip python-wheel
sudo pip install awscli==1.14.39 botocore==1.8.42

Thanks!
