### ISSUE TITLE
unknown filesystem type 'gpt' when mounting an EBS specified in the .cfncluster/config

### ISSUE THREAD

**Issue by gridley** [aws/aws-parallelcluster#614]
Hi,

First off, thanks for putting together this nice tool. Second, I'm trying to start a cluster with a c5.large master node and c5.4xlarge compute nodes on govcloud. I'm also trying to have a gp2 EBS drive mounted on /shared. I double-checked and the EBS volume and the master node are both ending up in the same availability zones. Unfortunately, the configuration ends up failing. After using --norollback to check my /var/cfn-init.log, I find:

> ---- Begin output of mount -t gpt -o _netdev /dev/disk/by-ebs-volumeid/vol-<myvolume> /shared ----
> STDOUT:
> STDERR: mount: unknown filesystem type 'gpt'
> ---- End output of mount -t gpt -o _netdev /dev/disk/by-ebs-volumeid/vol-<myvolume> /shared ----

What would cause this? I thought GPT was pretty standard.

**Comment by gridley** [comment]
I assume you mean the OS on the amazon machine. uname -r gives:

```
[ec2-user@ip-<num> ~]$ uname -r
4.14.72-68.55.amzn1.x86_64
```

And as for ebs_volume_id, I have everything that should be needed:
```
[global]
...
cluster_template=mycluster
...
[cluster mycluster]
...
ebs_settings=test-ebs
...
[ebs test-ebs]
ebs_snapshot_id=snap-<number>
volume_type=gp2
ebs_volume_id=vol-<number>
```

I'm unsure if it's related, but OpenMP programs also won't compile on this with -fopenmp, even though libgomp is installed. The behavior is summarized by this:

```
[ec2-user@ip- ~]$ locate /omp.h
/usr/lib/gcc/x86_64-amazon-linux/4.8.5/include/omp.h
[ec2-user@ip-1 ~]$ gcc testo.c -fopenmp
testo.c:13:10: fatal error: omp.h: No such file or directory
 #include <omp.h>
          ^~~~~~~
compilation terminated.
[ec2-user@ip- ~]$ gcc48 testo.c -fopenmp
[ec2-user@ip ~]$ ./a.out 
Hello World from thread = 0
Number of threads = 2
Hello World from thread = 1
```

Oh, and of course, my cfncluster version:

```
[gavin@gpad ~]$ cfncluster version
1.6.0
```

**Comment by gridley** [comment]
Looks to me like this kernel for this AMI was compiled without support for GPT. From [here](https://wiki.archlinux.org/index.php/Partitioning):

> The CONFIG_EFI_PARTITION option in the kernel config enables GPT support in the kernel (despite the name, EFI PARTITION). This option must be built in the kernel and not compiled as a loadable module. This option is required even if GPT disks are used only for data storage and not for booting. This option is enabled by default in all Arch's officially supported kernels. In case of a custom kernel, enable this option by doing CONFIG_EFI_PARTITION=y.

**Comment by rexcsn** [comment]
Yes, so it looks like that you are trying to use an existing volume, which has GPT partition, with Cfncluster. As you have noted, the AMI does not have support for GPT, if you are determined to use that GPT partitioned volume with Cfncluster, it would require a custom AMI. However, if you only care about using the data on your volume, a workaround could be to just use the snapshot of the volume to create a new volume to use with Cfncluster. Try to create a snapshot of your GPT partitioned volume, specify the `ebs_snapshot_id=snap-<...>` option under the `[ebs]` section and any other option you would like, but DO NOT specify the `ebs_volume_id`. If you provide an `ebs_volume_id` the program will not create a new volume, and will try to mount the volume you have provided. Please try and see if that will solve your issue. The OpenMP issue is most probably unrelated to the volume issue.

**Comment by gridley** [comment]
Well, thank you for that. I just expected the amazon linux instances to work with EBS's created in the web-based console, but I guess not. Instead I'll just keep running an ubuntu-based cluster. Do you think there should be a cfncluster-specific error message for this? I feel like this is functionality many people would try to get. It took a few hours to figure out what was going on.

**Comment by rexcsn** [comment]
Thank you for pointing this issue out. We understand that this is an issue that is difficult to debug. We will look into ways to make this easier in the future.

**Comment by notestaff** [comment]
Just to note, I'm running into the same issue, and it would be great to have it fixed.

**Comment by lukeseawalker** [comment]
fix coming in the next release
