### ISSUE TITLE
DCV on Ubuntu 22.04 ARM not possible w/ v3.8.0-v3.11 despite availability of compatble DCV binaries

### ISSUE THREAD

**Issue by eugeneswalker** [aws/aws-parallelcluster#6158]
DCV cannot be turned on for Ubuntu 22.04 ARM64 using AWS Parallel Cluster v3.8.0-v3.10.1, despite upstream DCV binaries being available.

There are instructions here for installing DCV for Ubuntu 22.04 ARM:
https://docs.aws.amazon.com/dcv/latest/adminguide/setting-up-installing-linux-server.html

But if you try to launch a parallel cluster using official Ubuntu 22.04 ARM64 image with DCV turned on, validation fails with the following error:
```
  "configurationValidationErrors": [
    {
      "level": "ERROR",
      "type": "DcvValidator",
      "message": "NICE DCV can be used with one of the following operating systems when using arm64 architecture: ['alinux2', 'centos7', 'rhel8', 'rocky8']. Please double check the os configuration."
    },
```

See this file:
https://github.com/gmarciani/aws-parallelcluster/blob/develop/cli/src/pcluster/cli/commands/dcv_util.py

Would it be possible to enable this going forward?

**Comment by enrico-usai** [comment]
Thanks @eugeneswalker , tracked internally as enhancement.

**Comment by eugeneswalker** [comment]
> Thanks @eugeneswalker , tracked internally as enhancement.

Any chance this might be available in next release?

**Comment by enrico-usai** [comment]
Hi @eugeneswalker unfortunately there have not been yet active development on this area.

**Comment by nchaimov** [comment]
The latest release (v.3.10.0) appears to support DCV on alinux2, rhel8, rocky8, rhel9, and rocky9, but not any Ubuntu releases. Are there any updates on when support for Ubuntu might be available?

**Comment by sameershende** [comment]
We are interested in this capability and upgrade to ParallelCluster 3.10.0.

**Comment by kwryankrattiger** [comment]
It would be cool to see ParaView demoed on the newer ParallelCluster, let me know when you get this working!

**Comment by eugeneswalker** [comment]
Any update on this @hgreebe @enrico-usai ?

**Comment by hanwen-pcluste** [comment]
Hi everyone,

This task is under discussion with high priority.

Thank you for the feature request!
Hanwen

**Comment by eugeneswalker** [comment]
> Hi everyone,
> 
> This task is under discussion with high priority.
> 
> Thank you for the feature request! Hanwen

What do you think? Do you think it may come soon? We are eager to use this!

**Comment by hanwen-cluster** [comment]
Hello everyone,

https://github.com/aws/aws-parallelcluster-cookbook/pull/2843 has been merged. This improvement will be included in the upcoming 3.12.0 release

Thank you,
Hanwen

**Comment by hanwen-cluster** [comment]
ParallelCluster 3.12.0 has been released!
https://pypi.org/project/aws-parallelcluster/#history

Thank you all for the feature request!

**Comment by eugeneswalker** [comment]
> ParallelCluster 3.12.0 has been released! https://pypi.org/project/aws-parallelcluster/#history

Thank you for this!
