### ISSUE TITLE
cfncluster 1.6.1 fails launching new instances

### ISSUE THREAD

**Issue by karlvirgil** [aws/aws-parallelcluster#618]
I am trying to use cfncluster 1.6.1.  I created a new cluster, using the attached config file.  When I submit a qsub job, I get the following in the Auto Scaling Group Activity History:

> Failed | Launching a new EC2 instance | 2018 November 8 15:02:17 UTC-5 | 2018 November 8 15:02:17 UTC-5
> -- | -- | -- | --
> Description:DescriptionLaunching a new EC2 instance. Status Reason: Insufficient capacity. Launching EC2 instance failed.Cause:CauseAt 2018-11-08T20:02:14Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 4. | Description:DescriptionLaunching a new EC2 instance. Status Reason: Insufficient capacity. Launching EC2 instance failed. | Cause:CauseAt 2018-11-08T20:02:14Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 4.
> Description:DescriptionLaunching a new EC2 instance. Status Reason: Insufficient capacity. Launching EC2 instance failed.
> Cause:CauseAt 2018-11-08T20:02:14Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 4.

It never successfully launches compute nodes.  However, I am requesting c4.8xlarge instances, and there are plenty available according to the aws spot pricing history
![screen shot 2018-11-08 at 3 09 13 pm](https://user-images.githubusercontent.com/6791257/48224608-4e9fce80-e368-11e8-8249-0ef8ba4387e7.png)

I've attached my config file:
[config.txt](https://github.com/awslabs/cfncluster/files/2563391/config.txt)

Here's my qsub script:
`
#!/bin/sh

#$ -V
#$ -cwd
#$ -N class2_6x2_target_ceiling_20ft_tyco7226-k17_10psi_amongFour
#$ -pe mpi 72
#$ -j y
date
set -x

module load mpi/openmpi3-x86_64
. /efs/tmp/OpenFOAM/OpenFOAM-v1806/etc/bashrc

cd ${SGE_O_WORKDIR}

mpirun -np 72 fireFoam -parallel
`

**Comment by 91bsjun** [comment]
You may have to request to increase your instance capacity. As a default, AWS deny the large-size EC2 instance because of preventing misuse. I also had similar issue before.

**Comment by karlvirgil** [comment]
For my limits, I have

> Running On-Demand c4.8xlarge instances | 270
> Spot instance requests   | 90

**Comment by enrico-usai** [comment]
Hi @karlvirgil ,
your issue could be related to placement group setting.

You have different instance types for the master and the compute, you set the `placement_group = DYNAMIC` and the default value for the `compute` parameter was `cluster` for CfnCluster 1.6.1.
It means that ParallelCluster tried to launch both master and Compute instances in the same placement group and this might be the cause of the insufficient capacity error.

With ParallelCluster 2.1.1 [we changed](https://github.com/aws/aws-parallelcluster/commit/7ce6bf58937faf8d758c84a2ea0ab59f767ea993) the default value for the compute parameter to `compute`.

To solve your issue you can try to use the same instance type for both master and compute instances or set `placement = compute`.

We also added it to the [best practices](https://github.com/aws/aws-parallelcluster/wiki/Best-Practices#network-performance).
