### ISSUE TITLE
ganglia not being disabled

### ISSUE THREAD

**Issue by karlvirgil** [aws/aws-parallelcluster#619]
I am using the line 
`extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores", "ganglia_enabled" : "no" } }`
when creating a new cfncluster with version 1.6.1
I still get this message in the creation, even though I've asked for ganglia to be disabled:
```
$ )cfncluster create test
Beginning cluster creation for cluster: test
Creating stack named: test
Status: test - CREATE_COMPLETE
ClusterUser: centos
MasterPrivateIP: 10.15.20.62
GangliaPrivateURL: http://10.15.20.62/ganglia/
```
Seems to be a bug.

**Comment by sean-smith** [comment]
Thanks for reporting this.

**Comment by sean-smith** [comment]
Ganglia has been disabled by default in AWS ParallelCluster.
