### ISSUE TITLE
Static MAC addresses on the master and compute nodes

### ISSUE THREAD

**Issue by dennisthegitmenace** [aws/aws-parallelcluster#622]
I am trying to use `cfncluster` for running scientific computations. The software I use is licensed to specific MAC addresses.

 How can I give my master node and compute nodes static MAC addresses every time I relaunch the cluster? I know I could use ENI with set MAC address but then it could only be attached to a master node?

Regarding the compute nodes. Here is an extract from the documentation.  

> In the case of very large clusters, it is often sufficient if you send us the output of the $ADFBIN/dirac info command from the head node and 2 or 3 compute nodes. As most compute node names have the same beginning, we can then add them with a wild card (for example Linuxchem*). 

Can we somehow program names and MAC addresses of compute nodes to start with a pre-set string?

P.S. I might be speaking a good deal of nonsense. Please excuse me. I am not knowledgeable withe the subject of networking.

I would greatly appreciate you help. Thank you.

**Comment by enrico-usai** [comment]
Hi @dennisthegitmenace ,
you could change the name by using [custom bootstrap actions](https://cfncluster.readthedocs.io/en/latest/pre_post_install.html) but I cannot confirm that everything will work correctly (it should be verified). 

One idea could be to launch the cluster with [maintain-initial-size = true](https://cfncluster.readthedocs.io/en/latest/configuration.html#maintain-initial-size) and use the same _public_ subnet for both master and compute nodes. In this way the nodes will have a "static" Public IPs and you can get the ENIs .

If you stop the Compute nodes the Public IPs and the ENI will be released, whereas the Elastic IP of the Master will be retained.

Another idea is to allocate some [Elastic IPs](https://docs.aws.amazon.com/en_us/vpc/latest/userguide/vpc-eips.html) and attach them to the nodes when they are running.

**Comment by dennisthegitmenace** [comment]
Thank you so much Enrico. That added few things on my "to try" list. Currently I am waiting for some bureaucracy to be over with and hopefully I will get to try all of the above very soon.

**Comment by enrico-usai** [comment]
Ok @dennisthegitmenace , I'm going to close the issue, feel free to re-open it if you have other problems or to let us know what the final solution will be. 

We suggest to use the latest version of AWS ParallelCluster (`pip install aws-parallelcluster`) that is the AWS supported tool built on the CfnCluster project.
