### ISSUE TITLE
Doc issue: Setting cookbook node attribute for Closed Source Nvidia drivers in version 3.9.1?

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#6230]
For version 3.9.1 we are hitting the validation enforcement on p3 series node types with this error:
```
    {
      "level": "ERROR",
      "type": "InstanceTypeBaseAMICompatibleValidator",
      "message": "The instance type 'p3.2xlarge' is not supported by NVIDIA OpenRM drivers. OpenRM can only be used on any Turing or later GPU architectures. Please consider using a different instance type or building a custom AMI with closed source NVIDIA drivers."
    },
```

We still have an occasional need for the V100 GPU to support some older legacy scientific computing workflows so I'd like to enable p3.2xlarge support in pcluster version 3.9.1 on occasion.

The change in enforcement/validation is documented and the release notes say this:
```Add possibility to choose between Open and Closed Source Nvidia Drivers when building an AMI, through the ['cluster']['nvidia']['kernel_open'] cookbook node attribute.```

We do build custom AMIs so this is not an issue, however I can't find the documentation that says where and how to make the config change to flip between the Open and Closed Source Nvidia Drivers.  

Is there a link or more info on how to pass in the proper "cookbook node attribute" to flip this config setting when building a custom AMI?    The only docs I can find that reference "Cookbook node attributes" is the Chef repo over at https://github.com/aws/aws-parallelcluster-cookbook

**Comment by enrico-usai** [comment]
Hi @chrisdag you can find detailed instructions here: https://github.com/aws/aws-parallelcluster/wiki/Newer-Linux-kernels-are-no-longer-compatible-with-EFA-and-closed-Source-Nvidia-drivers-in-instances-with-GPU-Direct-RDMA-support#mitigation-for-parallelcluster--380---how-to-build-a-custom-ami-with-closed-source-nvidia-drivers-for-p3-p2-g3-and-g2-1
