### ISSUE TITLE
(3.8.0 - 3.9.1) SharedStorageType: Efs not working on arm instances

### ISSUE THREAD

**Issue by dreambeyondorange** [aws/aws-parallelcluster#6237]
### Bug description

When using the `SharedStorageType` config option `Efs` on arm instance types, the cookbook attempts to backup and mount the `/opt/intel` dir which doesn't exist for those instance types.

### Affected versions (OSes, schedulers)

Affects all clusters using arm instance types, regardless of OS or scheduler in pcluster versions 3.8.0 - 3.9.1

### Mitigation

You can find a detailed explanation and the mitigation of the problem [here](https://github.com/aws/aws-parallelcluster/wiki/(3.8.0%E2%80%903.9.1)-SharedStorageType:-Efs-not-working-on-arm-instances)

**Comment by skoloCFD** [comment]
Does anyone have an idea as to when this might be fixed in a standard release? I don't see it in 3.9.2, for example.

**Comment by enrico-usai** [comment]
Hi @skoloCFD, this is fixed in 3.9.2: https://github.com/aws/aws-parallelcluster-cookbook/pull/2722

We missed to list it in the changelog.

**Comment by dreambeyondorange** [comment]
Updated the CHANGELOG!
