### ISSUE TITLE
Timeout::Error: execution expired

### ISSUE THREAD

**Issue by mangesh1983** [aws/aws-parallelcluster#634]
Hi Team,

After attaching volume _master_base_config script failed with below error.
Please help me to resolve this issue as soon as possible.

[chef-stacktrace.out.txt](https://github.com/aws/aws-parallelcluster/files/2576394/chef-stacktrace.out.txt)

```
ruby_block("sleeping_for_volume") do
             action [:nothing]
             default_guard_interpreter :default
             declared_type :ruby_block
             cookbook_name "cfncluster"
             recipe_name "_master_base_config"
             block #<Proc:0x0000000002fbed00@/tmp/kitchen/cache/cookbooks/cfncluster/recipes/_master_base_config.rb:38>
             block_name "sleeping_for_volume"
           end


Running handlers:
       [2018-11-12T12:00:45+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-11-12T12:00:45+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 01 minutes 39 seconds
       [2018-11-12T12:00:45+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-11-12T12:00:45+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-11-12T12:00:45+00:00] FATAL: Timeout::Error: execution expired
```

**Comment by enrico-usai** [comment]
Hi @mangesh1983 could you please share your configuration file and let us know what version of the product are you using? Thank you

**Comment by mangesh1983** [comment]
Hi Team,

Thanks for the response on this!!!

I am using Version 2.0.0.
I have two issue after running this aws-parallelcluster-cookbook.
  1. botocore.exceptions.NoCredentialsError: Unable to locate credentials
-- for this I find the workaround- I login to the Master node and manually
create AWS credentials file. but I would like to know how I will do that
automatically while running cookbook itself.
  2.FATAL: Timeout::Error: execution expired


Below are the variable deatils. please let me know if you need more
information.

export AWS_KEYPAIR_NAME=mangesh

export EC2_SSH_KEY_PATH=/home/ubuntu/mangesh.pem

export AWS_FLAVOR_ID=t2.micro

export AWS_AVAILABILITY_ZONE=us-east-1a

export AWS_DEFAULT_REGION=us-east-1

export AWS_VPC_ID=vpc-b3d573c9

export AWS_SUBNET_ID=subnet-2256c70c

export AWS_SECURITY_GROUP_ID=sg-0cd479b053090d051

export AWS_IAM_PROFILE=CfnClusterEC2IAMRole

export AWS_IAM_PROFILE=

export
KITCHEN_LOCAL_YAML=/home/ubuntu/aws-parallelcluster-cookbook/.kitchen.cloud.yml

export CFN_VOLUME=vol-0e5d9613702c717d2

export AWS_STACK_NAME=cfncluster-test-kitchen

export CFN_SQS_QUEUE=cfncluster-chef

export CFN_DDB_TABLE=cfncluster-chef

**Comment by lukeseawalker** [comment]
Hi @mangesh1983 what's the background of this problem? What's the command that you are executing?

**Comment by mangesh1983** [comment]
Hi Team,

I am trying to create cfn-cluster environment using chef cookbook.
https://cfncluster.readthedocs.io/en/latest/ami_development.html

I ran below command.
1. kitchen create base-config-MasterServer-ubuntu-16-04-lts -- it ran
successfully able to create the Master node.
2. kitchen converge base-config-MasterServer-ubuntu-16-04-lts -- it failed
with below two error.
                   1. botocore.exceptions.NoCredentialsError: Unable to
locate credentials
                        -- for this I find the workaround- I login to the
Master node and manually create AWS credentials file. but I would like to
know how I will do that automatically while running cookbook itself.
                  2.FATAL: Timeout::Error: execution expired

Please let me know how to resolve this issue.

**Comment by lukeseawalker** [comment]
The instruction reported in https://cfncluster.readthedocs.io/en/latest/ami_development.html
are meant for building a custom AMI. 

Now the process of creating a custom AMI is integrated within the AWS ParallelCluster CLI, see https://aws-parallelcluster.readthedocs.io/en/latest/commands.html#createami

Please make sure you are using the latest version aws-parallelcluster == 2.0.1

**Comment by mangesh1983** [comment]
Hi Luca,
Thanks for helping on this!!!

If I do manually pcluster or cfncluster command everything works fine.
but I would like to run that through chef cookbook
https://github.com/aws/aws-parallelcluster-cookbook
when I ran below command.
1. kitchen create base-config-MasterServer-ubuntu-16-04-lts -- it ran
successfully able to create the Master node.
2. kitchen converge base-config-MasterServer-ubuntu-16-04-lts -- it failed
with below two error.
                   1. botocore.exceptions.NoCredentialsError: Unable to
locate credentials
                        -- for this I find the workaround- I login to the
Master node and manually create AWS credentials file. but I would like to
know how I will do that automatically while running cookbook itself.
                  2.FATAL: Timeout::Error: execution expired

Please let me know how to resolve this issue.

**Comment by lukeseawalker** [comment]
The `kitchen` command is not a supported path to create a cluster.

By the way, from your previous post, you are unsetting the value of AWS_IAM_PROFILE variable, which it is used by kitchen.
```
export AWS_IAM_PROFILE=CfnClusterEC2IAMRole
export AWS_IAM_PROFILE=
```

**Comment by mangesh1983** [comment]
Hi Luca,

Yes you are right, I corrected that now kitchen command went successfully.

I will try some more scenario tomorrow.

If kitchen command will not help me to create cluster can you please guide
me what this cookbook do.
also just me how i can do automation of cluster or what I will do using
this chef cookbook.

Thanks
Mangesh kharade

**Comment by lukeseawalker** [comment]
The cookbook is used by ParallelCluster in order to build and bootstrap the AMI used to create a cluster.

Please read https://aws-parallelcluster.readthedocs.io/en/latest/getting_started.html to get familiar with ParallelCluster and its usage.
