### ISSUE TITLE
Feature Request: Limiting Scope of SharedStorage Updates

### ISSUE THREAD

**Issue by vcoralic** [aws/aws-parallelcluster#6357]
Hi,

Right now, updating the SharedStorage cluster configuration detaches and recreates _all_ of the shared storage volumes specified in the updated configuration. A more desirable behavior, however, might be to simply update the storage volumes that _differ_ from the original configuration.

My current use case is that I would like to attach an FSx Lustre volume when running HPC workloads, and detach it when I am done (to be frugal). However, when detaching the Lustre volume, I would like keep my other volumes, where I store less ephemeral data, intact.

**Comment by dreambeyondorange** [comment]
This should be possible now with 3.9.0

**Comment by vcoralic** [comment]
@dreambeyondorange , this behavior was observed with 3.9.0 and confirmed with AWS support. If you believe there's a mistake, would you please provide a configuration YAML that I can use to test that the feature works as intended?
