### ISSUE TITLE
 OnNodeConfigured section for LoginNode

### ISSUE THREAD

**Issue by jagga13** [aws/aws-parallelcluster#6360]
Hello,

I am building the latest 3.10.1 based ParallelCluster instance and trying to use the LoginNode feature for the first time.  I don't see a OnNodeConfigured section for the LoginNodes and I use this to do post deployment customization of the nodes.  Is there a different way to handle post scripts for LoginNodes?  How am I supposed to add changes to the LoginNode when they are deployed using a base AMI which does not have all customization.  Any insight would be greatly appreciated!

Thanks.

**Comment by hanwen-pcluste** [comment]
Hi!

Apologies for the late reply. 
OnNodeConfigured scripts are not supported on login nodes. We have merged a PR https://github.com/aws/aws-parallelcluster/pull/6319 to add the support. It will be supported in ParallelCluster 3.11.0

Thank you!
