### ISSUE TITLE
Unable to create a valid Base64 encoded Munge key

### ISSUE THREAD

**Issue by rmarable-flaretx** [aws/aws-parallelcluster#6378]
I followed the guidance outlined here to generate a custom Munge key: https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmSettings-MungeKeySecretArn

I tried using the `mungekey` utility and Base64-encoding the resulting file.
```
$ mungekey -c -k munge-custom.key -b 1024 -f
$ base64 -w 0 munge-custom.key
```
However, pasting this text into the configured Secrets ARN fails to pass the validator:
```
{
  "configurationValidationErrors": [
    {
      "level": "ERROR",f
      "type": "MungeKeySecretSizeAndBase64Validator",
      "message": "The content of the secret arn:aws:secretsmanager:us-east-2:[redacted]:secret:pcluster-default-munge-key-YYYYYY is not a valid Base64 encoded string. Please refer to the ParallelCluster official documentation for more information."
    }
  ],
  "message": "Invalid cluster configuration."
}
```
I got the same results using `dd` and the suggested Python code.  Any suggestions would be welcomed with open arms.

**Required Info:**
 - AWS ParallelCluster version [e.g. 3.1.1]: 3.10.1

**Comment by hanwen-pcluste** [comment]
Sorry for the late reply.
Please make sure the key is stored as "Plaintext" (instead of "Key/value") in secret manager.

**Comment by rmarable-flaretx** [comment]
Hi @hanwen-pcluste - thanks for getting back to me.

The "Plaintext" field was explicitly used to save the key.
<img width="306" alt="Screenshot 2024-08-10 at 12 10 05 AM" src="https://github.com/user-attachments/assets/dc55aa3b-57be-4ee2-8b95-bd05dfcb657b">

**Comment by hanwen-pcluste** [comment]
So in the plaintext, please use the value directly (e.g. W0p...), instead of using the dictionary (e.g. {"xxx":"xxx"})

**Comment by rmarable-flaretx** [comment]
Thank you, that did the trick.
