### ISSUE TITLE
Enhancement Request: Custom Slurm GRES Types

### ISSUE THREAD

**Issue by joehellmersNOAA** [aws/aws-parallelcluster#6388]
Hello,

I see at https://docs.aws.amazon.com/parallelcluster/latest/ug/slurm-configuration-settings-v3.html#slurm-configuration-denylists-v3
that we cannot configure GresTypes on the Cluster or Gres on the compute nodes.

This would be a great feature.  I get that it would be rather tricky to implement, but there are some resources on the compute node that I'd like to be have to schedule jobs based on.

In particular, I'd like configure the amount of space on local instance storage.  So if I have the local instance storage mapped to a location on the computer node such as 
```
# df -hT
Filesystem                               Type      Size  Used Avail Use% Mounted on
/dev/mapper/vg.01-lv_ephemeral           ext4      218G   24K  207G   1% /mnt/ephemeral

```
I'd like to have a resource defined on the cluster called something like localssd, or localscratch which could have a Gres entry on the compute nodes, and then jobs could be scheduled based on limitations of that resource.

Thanks

**Comment by himani2411** [comment]
Hi @joehellmersNOAA 

I am not sure I understand the feature request.

Even if we do not support Gres and GresTypes in CustomSlurmSettings as  you have already read in documentation.
We do support GRES Scheduling by creating the required `/opt/slurm/etc/slurm_parallelcluster_*_gres.conf` files.

Also we have settings in cluster-config to provide Local Storage to Compute resource
Here is the Settings you can look at  https://docs.aws.amazon.com/parallelcluster/latest/ug/Scheduling-v3.html#yaml-Scheduling-SlurmQueues-ComputeSettings-LocalStorage

Please let us know if there is anything we can help.

Thank you.

**Comment by joehellmersNOAA** [comment]
Thanks for responding Himani.

My concern is that the configuration of GresType and Gres (on the compute nodes) is not supported hence there might be some sort of issue with configuring them manually or via a script, which I could certainly do.

Based on what you are saying it sounds like I could configure those settings in my post configuration script for the head node and compute nodes.  If that is the case I can give that a try.

BTW I've been using the LocalStorage setting on the compute nodes and it works great.  Thanks for adding that!

Joe Hellmers
