### ISSUE TITLE
porting cfncluster config file to parallelcluster

### ISSUE THREAD

**Issue by karlvirgil** [aws/aws-parallelcluster#639]
I am trying out parallelcluster, trying to port my config file settings from cfncluster.  I get an error message about "Volume1" failing to create:

```
$ )pcluster create myfirstcluster
Beginning cluster creation for cluster: myfirstcluster
Creating stack named: parallelcluster-myfirstcluster
Status: parallelcluster-myfirstcluster - ROLLBACK_IN_PROGRESS
Cluster creation failed.  Failed events:
  - AWS::EC2::SecurityGroup ComputeSecurityGroup Resource creation cancelled
  - AWS::DynamoDB::Table DynamoDBTable Resource creation cancelled
  - AWS::EC2::NetworkInterface MasterENI Resource creation cancelled
  - AWS::SNS::Topic SNS Resource creation cancelled
  - AWS::EC2::EIP MasterEIP Resource creation cancelled
  - AWS::CloudFormation::Stack EBSCfnStack Embedded stack arn:aws:cloudformation:us-east-1:684353139040:stack/parallelcluster-myfirstcluster-EBSCfnStack-1LTBR9JJBE6CS/b3204e50-e757-11e8-8b5e-500c2854b699 was not successfully created: The following resource(s) failed to create: [Volume1].


```

I've attached my old cfncluster config file and my newly created pcluster config file for comparison.  I am using pcluster version 2.0.0
[pcluster_config.txt](https://github.com/aws/aws-parallelcluster/files/2576903/pcluster_config.txt)
[cfncluster_config.txt](https://github.com/aws/aws-parallelcluster/files/2577074/cfncluster_config.txt)

**Comment by rexcsn** [comment]
Hi, unfortunately I was not able to reproduce your error with a similar config file. If you have not deleted this failed stack, could you log into the CloudFormation Console, look at the `Events` tab for the `parallelcluster-myfirstcluster-EBSCfnStack-...` nested stack, and send a screenshot of the error when `Volume1` failed to create? If the failed stack is deleted, please try creating it again with the `--norollback` option, do the same procedure, and send a screenshot of the error when `Volume1` failed to create.

**Comment by karlvirgil** [comment]
![screen shot 2018-11-13 at 1 06 38 pm](https://user-images.githubusercontent.com/6791257/48433408-02c49f00-e745-11e8-9903-a0f0ff9daca4.png)

Looks like my snapshot is still "pending"

**Comment by karlvirgil** [comment]
Once the snapshot finished being created then the cluster was created with no problem.  Thanks for your help!
