### ISSUE TITLE
Question: Slurm MinCount is this min nodes running or min nodes available to take jobs?

### ISSUE THREAD

**Issue by francisreyes-tfs** [aws/aws-parallelcluster#6417]
I'm looking for an option similar to MinCount, but instead of specifying the minimum number of nodes that are always running, I'd like to specify that there is at least X nodes running and those nodes are able to take jobs.

**Comment by dreambeyondorange** [comment]
I'm not sure I understand the difference you are specifying?  `minimum number of nodes that are always running` vs `at least X nodes running`. They seem to be the same thing.

MinCount is indeed the number of static nodes that are always available to take jobs
