### ISSUE TITLE
parallelcluster 3.9.x failing to build with custom image, even though it worked before and it works with 3.11.0.

### ISSUE THREAD

**Issue by gwolski** [aws/aws-parallelcluster#6477]
Using parallelcluster 3.9.1, .2, or .3.
I have a custom ami that I was able to overlay parallelcluster with build_image with 3.9.1 on May 27, 2024. 
The custom ami has been in existence since May 16, 2024.  Custom AMI is Rocky 8.9.

Today, I'm trying to move to 3.9.3 and I am encountering a build problem. In addition, I have reproduced the build problem with 3.9.1 and 3.9.2 as well. (and the fact I fail with 3.9.1 is odd as I did build and am running since May).

I am unable to build a parallel cluster AMI overlayed on my customized AMI with 3.9.x.  I was able to build with 3.11.0.

My build command for 3.9.3 is:

pcluster build-image --image-id pcluster-3-9-3-Rocky-8-x86-64-ami-XXXXXXXXXXXXXX--image-configuration pcluster-3-9-3-Rocky-8-x86-64-ami-XXXXXXXXXXXXXX--region us-west-2

Contents of my pcluster-3-9-3-Rocky-8-x86-64-ami-XXXXXXXXXXXXXX.yml file is:

Image:
  Name: pcluster-3-9-3-Rocky-8-x86-64-ami-XXXXXXXXXXXXXX
  RootVolume:
    Size: 32

Build:
  Imds:
    ImdsSupport: v2.0
  InstanceType: m6a.large # 2 vcpus/8GB
  SubnetId: subnet-0redacted
  SecurityGroupIds:
    - sg-04f9redacted
  ParentImage: ami-XXXXXXXXXXXXXX
  UpdateOsPackages:
    Enabled: false

DevSettings:
  TerminateInstanceOnFailure: false

Complete log from the command:
$ pcluster get-image-log-events --image-id pcluster-3-9-3-Rocky-8-x86-64-ami-XXXXXXXXXXX --log-stream-name "3.9.3/1" 
is attached.

[pcluster_build_3.9.3.log](https://github.com/user-attachments/files/17422887/pcluster_build_3.9.3.log)

Here is the relevant section from the log where I see the first error.

      "message": "CmdExecution: Stderr: PLATFORM='RHEL'\n\nif [[ ${PLATFORM} == RHEL ]]; then\n  CA_CERTS_FILE=/etc/ssl/certs/ca-bundle.crt\n  yum -y upgrade ca-certificates\nelif [[ ${PLATFORM} == DEBIAN ]]; then\n  CA_CERT
S_FILE=/etc/ssl/certs/ca-certificates.crt\n  apt-get -y --only-upgrade install ca-certificates\nfi\n\ncurl --retry 3 -L https://us-west-2-aws-parallelcluster.s3.us-west-2.amazonaws.com/archives/cinc/cinc-install-1.2.0.sh | b
ash -s -- -v 18.2.7\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0   
   0 --:--:-- --:--:-- --:--:--     0\r100 26698  100 26698    0     0   206k      0 --:--:-- --:--:-- --:--:--  206k\n\nif [[ -e ${CA_CERTS_FILE} ]]; then\n  ln -sf ${CA_CERTS_FILE} /opt/cinc/embedded/ssl/certs/cacert.pem\n
fi\n\n/opt/cinc/embedded/bin/gem install --no-document berkshelf:8.0.7\n\n",
      "timestamp": "2024-10-16T18:54:53.954Z"
    },
    {
      "message": "CmdExecution: ExitCode 0",
      "timestamp": "2024-10-16T18:54:53.954Z"
    },
    {
      "message": "ExecuteBash: FINISHED EXECUTION",
      "timestamp": "2024-10-16T18:54:53.954Z"
    },
    {
      "message": "Step DownloadCookbook",
      "timestamp": "2024-10-16T18:54:53.974Z"
    },
    {
      "message": "ExecuteBash: STARTED EXECUTION",
      "timestamp": "2024-10-16T18:54:53.976Z"
    },
    {
      "message": "Stdout: Vendoring cookbook failed.",
      "timestamp": "2024-10-16T18:54:55.202Z"
    },
    {
      "message": "CmdExecution: Command execution has been completed",
      "timestamp": "2024-10-16T18:54:55.203Z"
    },
    {
      "message": "CmdExecution: [ ERROR ] Command execution has resulted in an error",
      "timestamp": "2024-10-16T18:54:55.203Z"
    },

Looking for a clue please...???

**Comment by hanwen-pcluste** [comment]
Hi Guntram,

This is a known issue. Please see details here https://github.com/aws/aws-parallelcluster/wiki/(3.8.0-%E2%80%90-3.9.3)-ParallelCluster-Build-Image-Failing-during-Installation-of-Minitar-Ruby-Gem-Dependency

Thank you,
Hanwen

**Comment by gwolski** [comment]
Thank you for the pointer to the wiki. I have chosen to move on to 3.11.0 now that you have explained https://github.com/aws/aws-parallelcluster/issues/6478. Much appreciated.
