### ISSUE TITLE
v 3.11.0 cloudformation cannot delete the stack for a custom pcluster build_image run.

### ISSUE THREAD

**Issue by gwolski** [aws/aws-parallelcluster#6478]
Using 3.11.0.  Have virtual environment for 3.11.0.
Using pcluster build-image command:

$ pcluster build-image --image-id pcluster-3-9-3-Rocky-8-x86-64-ami-XXXXXXXXXXXX --image-configuration pcluster-3-9-3-Rocky-8-x86-64-ami-XXXXXXXXXXXXX.yml --region us-west-2

Contents of yml file:

Image:
  Name: pcluster-3-9-3-Rocky-8-x86-64-ami-XXXXXXXXXXXXXX
  RootVolume:
    Size: 32

Build:
  Imds:
    ImdsSupport: v2.0
  InstanceType: m6a.large # 2 vcpus/8GB
  SubnetId: subnet-0d4eYYYYYYYYYY
  SecurityGroupIds:
    - sg-04f9903XXXXXXXXX # can be any security group that allows outbound connections. Don't need inbound.
  ParentImage: ami-XXXXXXXXXXXXXX
  UpdateOsPackages:
    Enabled: false

DevSettings:
  TerminateInstanceOnFailure: false

This custom image was successfully used to build a parallelcluster image back in May 2024 with 3.9.1 (though I can't reproduce that today - different issue).

Parallelcluster builds the AMI just fine.  I've deployed it into a cluster and it is working.  However the cloudformation stack fails deletion:

![image](https://github.com/user-attachments/assets/186e1693-abb3-4ed5-8cd0-fafcf26a3f09)

Resources tab shows DELETE_FAILED:

![image](https://github.com/user-attachments/assets/79f46443-940d-4c11-ae04-988e42cc462a)

though if I click through to the IAM Roles, it is gone:

![image](https://github.com/user-attachments/assets/f06fa82f-6ef2-47ef-aecb-393afc86c73e)

Stack arn: arn:aws:cloudformation:us-west-2:326469498578:stack/pcluster-3-11-0-Rocky-8-x86-64-ami-02b57508ab520f631/0050c0d0-8c96-11ef-8112-0aa5e2830695

I've tried twice, same error.

**Comment by hanwen-pcluste** [comment]
Hi Guntram,

This is a known issue. Please see details here https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-and-later)-Build-image-CloudFormation-stacks-fail-to-delete-after-images-are-successfully-built

Thank you,
Hanwen

**Comment by gwolski** [comment]
Thank you for the pointer.  Maybe you could update the "New issue" template that you populate when one opens a new issue to include references to this wiki.  I only searched the issues section as suggested:

"Before submitting a new issue, please search through open [GitHub Issues](https://github.com/aws/aws-parallelcluster/issues) and check out the [troubleshooting documentation](https://docs.aws.amazon.com/parallelcluster/latest/ug/troubleshooting-v3.html)."

I did not even think of looking at the wiki.
Thanks again!

**Comment by gwolski** [comment]
@hanwen-pcluste  I just built a custom image with 3.11.1 and the Cloudformation stack deleted.  Maybe it's fixed and you could update the wiki?

**Comment by mfontana-elem** [comment]
> [@hanwen-pcluste](https://github.com/hanwen-pcluste) I just built a custom image with 3.11.1 and the Cloudformation stack deleted. Maybe it's fixed and you could update the wiki?

I am running with 3.13.0 and still have the same _The security token included in the request is invalid_ error.  Which still blocks the delete. Runs fun if I delete it manually.

This is problematic though, as I am running via Terraform and due to this failure my image resource is marked as tainted and cannot do further applies of my module without deleting this image. Is it still the case that the only way around this is creating a custom cleanup role with the suggested policies?

**Comment by gmarciani** [comment]
Hi @mfontana-elem as of today (latest version today is PC 3.13.1), this is still the only mitigation: https://github.com/aws/aws-parallelcluster/wiki/(3.0.0-and-later)-Build-image-CloudFormation-stacks-fail-to-delete-after-images-are-successfully-built

We have a backlog item to address this problem in future releases.
