### ISSUE TITLE
3.11.1 pcluster list-official-images shows two images for all OSes and architectures.

### ISSUE THREAD

**Issue by gwolski** [aws/aws-parallelcluster#6564]
Built virtual env as shown in docs for parallelcluster 3.11.1

Run pcluster list-official-images and you get two images listed for all the supported OSes. Both for x86_64 and arm64.
ami Names are the same, only the ami-id is different.

Looking at just the rhel8 version, only difference I can see on the AWS console dashboard is that the deprecation time is three days later.

Just calling this out in case there is something odd with your build process that makes two images available for each OS.
If you specify the os and version, you only get one listed.  The one with the later deprecation date.  At least for rhel8....

**Comment by hanwen-pcluste** [comment]
Hi Guntram,

Thank you for noticing this. There were some hiccups during our release, which caused two AMIs for all OSes. The two AMIs are identical. So you can use either AMI. By default, ParallelCluster uses the latest AMI

Thank you,
Hanwen
