### ISSUE TITLE
1.6.0 slurm won't scale past 10 nodes

### ISSUE THREAD

**Issue by gridley** [aws/aws-parallelcluster#659]
Hello,

The title describes the situation. Despite having set max_queue_size=30, it seems slurm won't scale past 10 nodes. I'm definitely using the cluster definition which contains that specification of max_queue_size. What more information can I provide to help with this? It's on c5.4xlarge nodes.

**Comment by tgjohnst** [comment]
It's likely that this isn't a slurm issue but rather a hard limit on your account - unless you've specifically requested an instance limit increase for that instance type on your AWS account, it appears that the default limit is 10 concurrent c5.4xlarge instances per account. You can view your limits and request a limit increase by going to https://console.aws.amazon.com/ec2/ and selecting "Limits" from the sidebar.

**Comment by gridley** [comment]
Ah, yes, this is the case. Sorry about the trouble.
