### ISSUE TITLE
Adding nodes manually

### ISSUE THREAD

**Issue by mukulagrawal78** [aws/aws-parallelcluster#692]
Two questions:

1/ can I manually start a new node either from AWS console or AWS CLI and add it to an existing running cfn cluster?

2/ If a node crashes for some reason killing job running on that node, can I configure SGE (or otger scheduler) under cfn to resubmit job (maybe a modified version) and restart that on a new node ? I would like the scheduler to properly start accounting for that new job as the old crashed job.

**Comment by sean-smith** [comment]
1. Yes, you can go to the aws autoscaling console, look for the ASG named `cfncluster-[cluster_name]` or `parallelcluster-[cluster_name]` and bump up desired. This will cause a new node to launch and join the scheduler.
https://console.aws.amazon.com/ec2/autoscaling/home?region=us-east-1#AutoScalingGroups:

2. See `man sge`, there's a helpful `-r` option:

```
-r y[es]|n[o]
              Available for qsub and qalter only.

              Specifies whether a job can be rerun or not.  If the value of -r is 'yes', the job will  be  rerun
              if  it  gets  aborted without leaving a consistent exit state.  (This is typically the case if the
              node on which the job is running crashes).  If -r is 'no' (the default), the job will not be rerun
              under  such  circumstances.   It  will still be rerun if it finishes with exit code 99 unless FOR‐
              BID_RESCHEDULE is set in qmaster_params in sge_conf(5).

              Interactive jobs submitted with qsh, qrsh, or qlogin are not rerunnable.
```

**Comment by sean-smith** [comment]
No, the ASG uses uses either a launch template or launch configuration which specifies the instance type. You need this launch template for the node to join the cluster. 

I suppose theoretically you could copy the launch template, remove the instance type and then update the ASG to use the new diversified ASG. I haven’t tried this so I can’t give you the pitfalls. See https://aws.amazon.com/blogs/aws/new-ec2-auto-scaling-groups-with-multiple-instance-types-purchase-options/

If you want multiple instance types, checkout the new aws batch integration we launched as part of ParallelCluster. Batch allows you to specify an instance family, such as c4 or c5. This will scale up the best instance to meet your job’s requirements. See https://aws-parallelcluster.readthedocs.io/en/latest/hello_world.html#running-your-first-job-using-aws-batch

**Comment by JiaweiZhuang** [comment]
> Am I allowed to add a node in ASG which is of different type (e.g. rest of nodes in cluster are c.xlarge but I add c.4xlarge)

You should be able to do so with https://github.com/aws/aws-parallelcluster/issues/307#issuecomment-462215214

**Comment by steveisoft** [comment]
I am using batch with compute_instance_type = m5.xlarge,m5.2xlarge with max_vcpus = 128
How will it know what limits to apply to each of the ASGs?

**Comment by enrico-usai** [comment]
Hi @steveisoft 
as a general suggestion please always open a new issue instead of answering to a closed one.

For clusters that are based on AWS Batch, AWS ParallelCluster relies on the elastic scaling capabilities provided by the AWS-managed job scheduler.
ParallelCluster doesn't use ASG in that case. 

Virtually there are no limits in the compute instances with AWS Batch.
See https://docs.aws.amazon.com/en_us/batch/latest/userguide/service_limits.html
