### ISSUE TITLE
1.6.1 only starting 5 instances, when limit is set to 12

### ISSUE THREAD

**Issue by sentient-kshaffer** [aws/aws-parallelcluster#711]
I initialized my cfncluster 1.6.1 with an `initial_queue_size` of 0, and a `max_queue_size` of 12, but my SLURM job scheduler shows that only 5 of my 7 submitted jobs are actually being worked on.
I checked in AWS, and only see 5 instances running. I expected that more instances (up to 12) would be spun up as needed. 

Note: I am using gov cloud for this job. 

```
JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
   27   compute    JOB15   ubuntu PD       0:00      1 (Resources)
   28   compute    JOB16   ubuntu PD       0:00      1 (Priority)
   22   compute    JOB10   ubuntu  R 1-23:35:38      1 ip-10-0-0-216
   23   compute    JOB11   ubuntu  R   11:35:34      1 ip-10-0-0-9
   24   compute    JOB12   ubuntu  R    8:52:38      1 ip-10-0-0-169
   25   compute    JOB13   ubuntu  R    6:21:01      1 ip-10-0-0-211
   26   compute    JOB14   ubuntu  R    2:40:52      1 ip-10-0-0-229
```

Here is my config file (with my vpcs and such just blindly named, since the 5 running jobs work just fine)
```
[aws]
aws_region_name = us-gov-west-1

[cluster default]
key_name = myHpc
vpc_settings = my-vpc
ebs_settings = custom

initial_queue_size = 0
max_queue_size = 12

scheduler = slurm
base_os = ubuntu1604
master_instance_type = t2.micro
compute_instance_type = c5.18xlarge

compute_root_volume_size = 15
master_root_volume_size = 15

[vpc my-vpc]
vpc_id = vpc-abc123
master_subnet_id = subnet-abc123

[global]
cluster_template = default
update_check = true
sanity_check = true

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

[ebs custom]
volume_size = 1000
volume_type = gp2
ebs_snapshot_id = snap-abc123
```

**Comment by sean-smith** [comment]
How many slots and nodes did you request for each job? 

Can you please post the contents of `/var/log/jobwatcher`? That script decides how many nodes to launch. 

It's also possible you're hitting ec2 limits, you can go to aws console > ec2 > autoscaling and look at the Activity History tab.

**Comment by sentient-kshaffer** [comment]
Thank you! The old version of cfncluster I was using didn't use autoscaling groups, so I didn't think to look there. And then I also used the aws CLI to check my instance limit, but it gave me an answer of 20 instances, but didn't seem to break it down by instance type.

Turns out that I only had 5 available for the instance size I was using (c5.18xlarge).

Thanks!
