### ISSUE TITLE
SGE compute nodes do not show up on qhost, seems connected to `ebs_volume_id`

### ISSUE THREAD

**Issue by ewengillies** [aws/aws-parallelcluster#712]
Let me start by saying I love the concept of `cfncluster`.  I am from an academic background, where I used `qsub` and `slurm` a lot, and I am glad to see this interface in AWS.  Thank you for the effort!

This seems similar to #252, for reference.  

I'm having a little trouble getting what a cluster to successfully attach a shared volume denoted via `ebs_volume_id` to the compute nodes.  I've provided the config below.  There are three scenarios:
 * If I set `ebs_volume_id`  and `initial_queue_size = 0`, then it all boots fine and I can see my volume mounted on the `Master` node.  However, if I submit some "hello world" jobs, the compute instances initialize and get to "running" state, but they never appear on `qhost`.  The jobs are left on `qw` indefinitely.
 * If I set `ebs_volume_id`  and `initial_queue_size = 2`, then it does not create the cluster successfully.  I get an error that says:
```
 - AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 1 FAILURE signal(s) out of 2.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```
 * If I do not use `ebs_volume_id`, everything works fine for both `initial_queue_size = 0` and `initial_queue_size = 2`.

What I would like to achieve is a shared volume across the master and compute nodes that can also persist across several cluster creations/deletions. I'd like to use this node to store config files (bashrc, vimrc, etc.), a copy of our software's git repo, some `qsub` wrappers i've developed, and job run scripts and log files.  I'd prefer to not have to set up this shared space every time I spin up a new cluster. I'd love to know if there's a better way to achieve this.  Thanks again!

```
# Global settings                                                                                                                                                                    [aws]   
aws_access_key_id = 
aws_secret_access_key = 
aws_region_name = us-east-1

## Custom cluster ids       
[cluster util-cluster]
# Name of the key to use               
key_name =          
# Name the network settings to read
vpc_settings = production
# Master instance type, should usually be micro
master_instance_type = t2.micro
compute_instance_type = t2.medium
# Read/write access to document cache
s3_read_write_resource = 
# Inital number of EC2 instances to launch as compute nodes in the cluster.
initial_queue_size = 0 # if a non-zero value is used, the ComputeFleet fails to build
# Maximum number of EC2 instances that can be launched in the cluster.
max_queue_size = 10
# Boolean flag to set autoscaling group to maintain initial size and scale back
maintain_initial_size = false
# Type of cluster to launch i.e. ondemand or spot
cluster_type = ondemand

# Name of the custom settings we will be using
ebs_settings = home
# Mount the directory as home
shared_dir = new_home

## EBS (Volume) Settings
[ebs home]
# Existing EBS volume to be attached to the MasterServer
ebs_volume_id = vol-<id>

## Networking settings
[vpc production]
vpc_id = vpc-<id>
master_subnet_id = subnet-<id>
```

**Comment by enrico-usai** [comment]
Hi @ewengillies, we are glad you like CfnCluster.

Your way is the right one, another one could be to use a [post-install action](https://cfncluster.readthedocs.io/en/latest/pre_post_install.html) to install your stuff.

What version of CfnCluster are you using?

To verify the error you could re-execute `cfncluster create` action using `--norollback` option and check for errors in the `/var/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node or Compute Nodes not attached to the cluster.

**Comment by ewengillies** [comment]
> Your way is the right one, another one could be to use a post-install action to install your stuff.

Thanks!  Some of the repos are private though, and it seems a new `ssh` key is generated for each new `cfncluster configure` update.  I couldn't think of a safe way to give the new Master instance clearance to pull the private code.  If there is a way, that could be another work around.

> What version of CfnCluster are you using?

Right, its version 1.6.1.  

> To verify the error you could re-execute cfncluster create action using --norollback option and check for errors in the /var/cfn-init.log, /var/log/cloud-init.log and /var/log/cloud-init-output.log files from the Master node or Compute Nodes not attached to the cluster.

I couldn't find any errors in the logs, but also I did not see anything mounted on "/new_home", which I selected for the volume.  Is there a specific error string I should grep for?

**Comment by enrico-usai** [comment]
The creation with `initial_queue_size != 0` fails because the compute nodes are not able to execute some actions (probably related to the mount).

I'd try in this way: set `initial_queue_size = 1` in your configuration and use `--norollback` at creation time. Then connect by ssh to the Compute instance not attached to the cluster and check the logs, by searching for `new_home`, `shared_dir` or `mount` string.
