### ISSUE TITLE
pcluster 2.0.2 fails to create master in proxy-required private VPC (issue is in part-002 script) 

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#726]
**Environment:**
 - AWS ParallelCluster 2.0.2
 - OS: CentOs7
 - Scheduler: SGE

**Bug description and how to reproduce:**

1) Try to launch with proxy_server defined in config within a VPC that blocks all internet access except via proxy 

2) Result:  cloudformation stack timeout for master server complete is hit and the cluster fails and performs a rollback. The deployment process hangs forever during the execution of /var/lib/cloud/instance/scripts/part-002 

**Additional context:**

This issue as filed I think will not be useful for the developers -- I'm seeking more tips on debugging in this particular context as I've got the perfect hardened VPC in which to test, debug and find more detailed info. 

This is what I've noticed:

- cfncluster|parallelcluster in general is excellent at proxy support for it's actions. It fetches files from s3 and does all the other stuff it needs to do just fine

 - Something is off about the interaction between the part-002 script and how it handles setting up the OS package repository (I think ...) 

- Because when I launch with a MINIMAL pre_install bootstrap script that deletes all the .repo files and replaces them with .repo files that do not need proxy access because they point to internal CentOS and EPEL mirror hosts then parallecluster-2.0.2 deploys perfectly

- The funny thing is that when I do "fix" the local repo files to point to private mirrors and the cluster deploys successfully you actually DO see the proxy_server info appended to the bottom of /etc/yum.conf config file --- however on a system where the repo files point to the internet and deployment fails you DO NOT see proxy info appended to the bottom of yum.conf -- so the failure or hang is occurring before the /var/lib/cloud/instance/scripts/runcmd command can execute as that seems to be the file that makes apt or yum "proxy aware" 

- So something gets hung/wedged when proxy is required, part-002 script starts to run and the wedge/hang occurs *before* the code can append proxy_server info to yum.conf

I'm happy to keep testing and digging but I'm looking for debug/pointers on where I should look for the root cause. The standard log files where I'd normally look (cfn*.log etc.) do not show any useful errors and when I run /var/lib/cloud/instance/scripts/part-002 by hand it also just hangs forever without giving me an error  -- and it is the "hanging forever" issue that trips the timout and causes the rollback

**Comment by enrico-usai** [comment]
Hi @chrisdag,
thank you for the detailed report.

The proxy is added to the yum configuration [as first action](https://github.com/aws/aws-parallelcluster/blob/v2.0.2/cloudformation/aws-parallelcluster.cfn.json#L3102-L3112) in the user-data.sh script executed in the EC2 instance, so you should always find the proxy or the `_none_` word in the _yum.conf_ file.

The access to the CentOS repository is not enough, the instances also require access to:
- pypi.python.org
- bootstrap.pypa.io
- supermarket.chef.io
- and to some AWS Endpoints (i.e. cloudformation, ec2, dynamodb, autoscaling, queue, s3)

Could you please double-check the `cfn-init.log` or the `cloud-init.log` files to understand what is the code executed by the "part-002" script? Then we can help you to understand why it is failing.
Thank you

**Comment by chrisdag** [comment]
Thanks for the reply!

I was able to launch again and reproduce the fatal error. The only change in this "non working" version vs the "working" version is that this "non working" config did not use the pre_install bootstrap script to fix the local repo files by replacing CentOS and EPEL repos with files that pointed to a private local mirror

I still think this is yum specific. The python stuff clearly goes through the proxy to hit the Pypi server etc.

I also included /etc/yum.conf from this failed cluster. The most interesting data point relative to your reply is confirming that proxy host info **_is not_** appended to yum.conf at all! 

The files from the failed launch are attached here. This is a VPC that uses private mirrors for CentOS and EPEL yum repos but also supports outbound HTTP and HTTPS via proxy.  The "failure" in this case is  that the master fails to build and we hit the cloudformation timeout that triggers a rollback. I got these files by forcing the failure in "--norollback" mode

I did a quick sanity check of the attached files to remove corporate hostnames but other than that the files are untouched 


[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/2640840/cloud-init.log)
[yum.conf.txt](https://github.com/aws/aws-parallelcluster/files/2640841/yum.conf.txt)
[dna.json.txt](https://github.com/aws/aws-parallelcluster/files/2640842/dna.json.txt)
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/2640843/cfn-init-cmd.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/2640844/cfn-init.log)
[cfn-wire.log](https://github.com/aws/aws-parallelcluster/files/2640845/cfn-wire.log)

**Comment by enrico-usai** [comment]
Hi @chrisdag sorry for the delay.

I reproduced your behaviour when some rules are missing in the proxy configuration.

For Centos instances it is required to enable the `.centos.org` domain in the Proxy.
If you look at the access log of your proxy (e.g. `/var/log/squid/access.log` for Squid) you should see the websites the instance is trying to connect to.

To confirm that the problem is in the proxy configuration you could also try to configure the proxy to let pass the requests for all the websites.

Please let us know if it helps.

**Comment by chrisdag** [comment]
My proxy server has unrestricted internet access to all the sites listed above including .centos.org so I don't think we are reproducing the same error

However I've upgraded to parallecluster 2.1.1 and now I have a new proxy related error (see #832 ) 
Thanks!

**Comment by enrico-usai** [comment]
Hi @chrisdag,
thank you for the clarification.

Please make sure you have the _.amazonaws.com_ domain added to the enabled list.

1. What proxy are you using?
2. Could you check the access log of your proxy to detect what is the failing domain?
3. Did you try to configure the proxy to let pass the requests for all the websites?

Then I see in your _cloud-init.log_ a lot of messages concerning mount failures:
```
2018-11-16 15:01:37,311 - util.py[DEBUG]: Failed mount of '/dev/xvda' as 'iso9660': Unexpected error while running command.
Command: ['mount', '-o', 'ro,sync', '-t', 'iso9660', '/dev/xvda', '/tmp/tmpXuFN5F']
Exit code: 32
Reason: -
Stdout: -

...
2018-12-03 18:15:18,806 - util.py[DEBUG]: Failed mount of '/dev/xvdba' as 'iso9660': Unexpected error while running command.
Command: ['mount', '-o', 'ro,sync', '-t', 'iso9660', '/dev/xvdba', '/tmp/tmpdTgmZT']
Exit code: 32
Reason: -
Stdout: -
Stderr: mount: wrong fs type, bad option, bad superblock on /dev/xvdba,
               missing codepage or helper program, or other error
        
               In some cases useful info is found in syslog - try
               dmesg | tail or so.

...
2018-12-03 18:15:18,950 - util.py[DEBUG]: Failed mount of '/dev/xvdbb' as 'iso9660': Unexpected error while running command.
Command: ['mount', '-o', 'ro,sync', '-t', 'iso9660', '/dev/xvdbb', '/tmp/tmpmZcRHk']
Exit code: 32
Reason: -
Stdout: -
Stderr: mount: wrong fs type, bad option, bad superblock on /dev/xvdbb,
               missing codepage or helper program, or other error
        
               In some cases useful info is found in syslog - try
               dmesg | tail or so.
```

4. Could you try without your post-install.sh script? (and share it, if possible)
5. Could you share the config file without any credentials or personal data?

Thanks

**Comment by enrico-usai** [comment]
Any update?

**Comment by enrico-usai** [comment]
I'm going to close the issue, feel free to re-open or open a new one in case of other specific problems.
