### ISSUE TITLE
"Desired Instances" not being correctly calculated

### ISSUE THREAD

**Issue by karlvirgil** [aws/aws-parallelcluster#743]
**Environment:**
 - AWS ParallelCluster / CfnCluster version aws-parallelcluster-2.0.2
 - OS: centos7
 - Scheduler: SGE

**Bug description and how to reproduce:**

Using the new parallelcluster, I submit a series of jobs.  The "desired instances" value is incorrectly calculated.  The AWS console lists 26 desired jobs, but I am only requesting 8 nodes.

```
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------

0 nodes

job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
     45 0.55500 test       centos       qw    12/05/2018 16:45:21                                  144
     46 0.55500 test       centos       qw    12/05/2018 16:45:33                                  144

45 /shared/scaling/poolFire/1M/smallPoolFire3D-144
46 /shared/scaling/poolFire/1M/smallPoolFire3D-128
```

**Additional context:**
A screenshot of the aws console is provided
![screen shot 2018-12-05 at 4 49 18 pm](https://user-images.githubusercontent.com/6791257/49546213-bbe24900-f8ad-11e8-8a3a-2690507a65bd.png)
The config file with credentials removed is also provided.
[config.txt](https://github.com/aws/aws-parallelcluster/files/2650780/config.txt)

These files are attached too: `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node
[sqswatcher.txt](https://github.com/aws/aws-parallelcluster/files/2650787/sqswatcher.txt)
[jobwatcher.txt](https://github.com/aws/aws-parallelcluster/files/2650788/jobwatcher.txt)

**Comment by karlvirgil** [comment]
Here's an example of the qsub command:

```
#!/bin/sh

#$ -V
#$ -cwd
#$ -N test
#$ -pe mpi 144
#$ -j y
set -x

export PATH=/efs/opt/openmpi-2.1.1/bin/:$PATH
export LD_LIBRARY_PATH=/efs/opt/openmpi-2.1.1/lib/:$PATH
. /efs/clang/OpenFOAM/OpenFOAM-v1806/etc/bashrc
cd ${SGE_O_WORKDIR}

mpirun -np 128 --bind-to core fireFoamVanilla -parallel
```

I am requesting 144 cores.  

I am submitting many jobs at once, all using this similar qsub script.  I submit similar jobs consisting of  1, 2, 4, 16, 32, 36, 64, 72, 128, 144, 224, 288 cores at the same time.  Most of the jobs run fine, but a few of the jobs end up in the "t" state.  

The scaledown_idletime is just the default.   I can't get to the nodewatcher log, because the compute nodes aren't showing up in the parallelcluster, even though in the console it says that there are 17 active compute nodes associated with this cluster.

**Comment by karlvirgil** [comment]
In fact, now, in the console, it shows that there are 15 running instances, 22 desired.  However, there are no nodes that show up under qhost, and I haven't had any jobs in the queue for hours.
<img width="1744" alt="screen shot 2018-12-05 at 10 05 55 pm" src="https://user-images.githubusercontent.com/6791257/49558731-1a252100-f8da-11e8-959d-434df72a2151.png">

**Comment by karlvirgil** [comment]
The "activity history" tab shows this:
<img width="1744" alt="screen shot 2018-12-05 at 10 08 19 pm" src="https://user-images.githubusercontent.com/6791257/49558791-55bfeb00-f8da-11e8-98d1-c10046e286b5.png">

**Comment by enrico-usai** [comment]
Hi @karlvirgil ,
we've analyzed your logs and we've found the problem.

For an unknown and rare reason the sqswatcher was unable to get the hostname of the instance 
`i-04f6614745c4985ee` and to add it to the cluster.
```
2018-12-05 16:13:16,047 INFO [sqswatcher:pollQueue] eventType=parallelcluster:COMPUTE_READY
2018-12-05 16:13:16,047 INFO [sqswatcher:pollQueue] instanceId=i-04f6614745c4985ee
2018-12-05 16:13:16,262 INFO [sqswatcher:pollQueue] Adding Hostname: 
2018-12-05 16:13:16,263 INFO [sge:addHost] Adding  with 36 slots
error: no option argument provided to "-ah"
...
2018-12-05 16:13:49,330 CRITICAL [sge:addHost] Unable to provison host
Traceback (most recent call last):
  File "/usr/bin/sqswatcher", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/sqswatcher/sqswatcher.py", line 219, in main
    pollQueue(scheduler, q, t, proxy_config)
  File "/usr/lib/python2.7/site-packages/sqswatcher/sqswatcher.py", line 170, in pollQueue
    raise e
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutItem operation: One or more parameter values were invalid: An AttributeValue may not contain an empty string
```

From that moment the sqswatcher and the scaling-up process started working bad. 
It was unable to process this message from the queue and crashed raising an exception.

At some moments when the failing message was locked due to [sqs visibility timeout](https://docs.aws.amazon.com/en_us/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) the restarted sqswatcher process was able to process some other messages and add new hosts to the cluster but when the failing message was re-analyzed the sqswatcher failed again.

We are currently working to create a patch for the sqswatcher code, to make it more robust and avoid to process multiple times a wrong host or a wrong sqs message.
Thank you for your useful logs.

That should not be a common issue and you shouldn't have the same issue again, 
in any case we'll update this issue when we've done.

**Comment by enrico-usai** [comment]
I'm going to close this case since the patch has been merged in the develop branch. 
It will be available in the next version of AWS ParallelCluster.
Please let us know if you have any questions.
