### ISSUE TITLE
cfncluster-1.6.1: Template format error: Unresolved resource dependencies [RootRole] in the Resources block of the template

### ISSUE THREAD

**Issue by JeffNing** [aws/aws-parallelcluster#746]
My AWS account has limited privileges but a specific ec2 role (spec_ec2) is created with full privileges. When the specific role is used for ec2 creation:
ec2_iam_role = spec_ec2
When trying to create the cluster, I encountered this error:
Template format error: Unresolved resource dependencies [RootRole] in the Resources block of the template
The template is validated without any error by cloudformation validate-template.
Any suggestion and/or advice would be highly appreciated.

P.S.
Here is the portion of RootRole resouce block:
**"RootRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [{
						"Effect": "Allow",
						"Principal": { "Service": ["ec2.amazonaws.com"] },
						"Action": ["sts:AssumeRole"]
					}]
				},
				"Path": "/"
			},
			"Condition": "CreateEC2IAMRole"
		},**

**Comment by lukeseawalker** [comment]
Hi @JeffNing,
what's your configuration file?

**Comment by JeffNing** [comment]
Hi @lukeseawalker,
Thanks for your response.
Here is my config file content:
key_name = spec_user
ec2_iam_role = spec_ec2
scheduler = slurm
master_instance_type = t2.micro
compute_instance_type = r5.12xlarge
tags = {"Name" : "dat-cfncluster", "owner" : "spec_user"}
base_os = ubuntu1404
custom_ami = ami-0e2f84e1426dad269
master_root_volume_size = 30
compute_root_volume_size = 30
compute_security_group = sg-415d1024

**Comment by lukeseawalker** [comment]
Hi @JeffNing,
I'm not able to reproduce the issue. Which version of ParallelCluster are you using?

**Comment by JeffNing** [comment]
Yes, I updated CfncCluster to the latest version, 1.6.1.

**Comment by lukeseawalker** [comment]
Hi @JeffNing,
I'm not able to reproduce your issue. I have created and configured a custom role with the following policy. Can you please double check that your policy is a superset of the following one?

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Resource": [
                "*"
            ],
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:AttachVolume",
                "ec2:DescribeInstanceAttribute",
                "ec2:DescribeInstanceStatus",
                "ec2:DescribeInstances"
            ],
            "Sid": "EC2",
            "Effect": "Allow"
        },
        {
            "Resource": [
                "*"
            ],
            "Action": [
                "dynamodb:ListTables"
            ],
            "Sid": "DynamoDBList",
            "Effect": "Allow"
        },
        {
            "Resource": [
                "arn:aws:sqs:*:*:cfncluster-*"
            ],
            "Action": [
                "sqs:SendMessage",
                "sqs:ReceiveMessage",
                "sqs:ChangeMessageVisibility",
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl"
            ],
            "Sid": "SQSQueue",
            "Effect": "Allow"
        },
        {
            "Resource": [
                "*"
            ],
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:DescribeTags",
                "autoScaling:UpdateAutoScalingGroup"
            ],
            "Sid": "Autoscaling",
            "Effect": "Allow"
        },
        {
            "Resource": [
                "arn:aws:dynamodb:*:*:table/cfncluster-*"
            ],
            "Action": [
                "dynamodb:PutItem",
                "dynamodb:Query",
                "dynamodb:GetItem",
                "dynamodb:DeleteItem",
                "dynamodb:DescribeTable"
            ],
            "Sid": "DynamoDBTable",
            "Effect": "Allow"
        },
        {
            "Resource": [
                "arn:aws:s3:::*-cfncluster/*"
            ],
            "Action": [
                "s3:GetObject"
            ],
            "Sid": "S3GetObj",
            "Effect": "Allow"
        },
        {
            "Resource": [
                "arn:aws:cloudformation:*:*:stack/cfncluster-*"
            ],
            "Action": [
                "cloudformation:DescribeStacks"
            ],
            "Sid": "CloudFormationDescribe",
            "Effect": "Allow"
        },
        {
            "Resource": [
                "*"
            ],
            "Action": [
                "sqs:ListQueues"
            ],
            "Sid": "SQSList",
            "Effect": "Allow"
        },
        {
            "Resource": [
                "arn:aws:logs:*:*:*"
            ],
            "Action": [
                "logs:*"
            ],
            "Sid": "CloudWatchLogs",
            "Effect": "Allow"
        }
    ]
}
```

**Comment by JeffNing** [comment]
Dear Luca,
Thank you so much for kind effort and the message. My account admin told me that my AWS account policy is more than satisfying the requirement you mentioned.
For the troubleshooting purpose, here is my info:

  *   CfnCluster version: 1.6.1
  *   configuration content:

[global]
cluster_template = datcluster
update_check = true
sanity_check = false
[cluster datcluster]
vpc_settings = veracyte
key_name = dat_user
ec2_iam_role = dat_ec2
template_url = http://s3-us-west-1.amazonaws.com/vcyt-dat-cfncluste/default_dat.cfn.json
compute_instance_type = r5.12xlarge
master_instance_type = t2.micro
initial_queue_size = 2
max_queue_size = 10
maintain_initial_size = false
scheduler = slurm
custom_ami = ami-0e2f84e1426dad269
s3_read_resource = arn:aws:s3:::vcyt-dat-cfncluster/*
base_os = ubuntu1404
tags = {"Name" : "dat-cfncluster", "owner" : "dat_user"}
compute_security_group = sg-415d1024

[vpc veracyte]
master_subnet_id = subnet-3f914966
vpc_id = vpc-426ad927

  *   CloudFormation log:

2018-12-11


Status


Type


Logical ID


Status Reason



14:04:17 UTC-0800


ROLLBACK_COMPLETE


AWS::CloudFormation::Stack


cfncluster-datcluster



14:04:16 UTC-0800


DELETE_COMPLETE


AWS::SQS::Queue


SQS



14:03:46 UTC-0800


DELETE_COMPLETE


AWS::DynamoDB::Table


DynamoDBTable



14:03:34 UTC-0800


DELETE_COMPLETE


AWS::EC2::SecurityGroup


MasterSecurityGroup



14:03:32 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::SecurityGroup


MasterSecurityGroup



14:03:31 UTC-0800


DELETE_COMPLETE


AWS::EC2::Volume


SharedVolume



14:03:31 UTC-0800


DELETE_COMPLETE


AWS::EC2::NetworkInterface


MasterENI



14:03:16 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::Volume


SharedVolume



14:03:16 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::NetworkInterface


MasterENI



14:03:16 UTC-0800


DELETE_IN_PROGRESS


AWS::SQS::Queue


SQS



14:03:15 UTC-0800


DELETE_IN_PROGRESS


AWS::DynamoDB::Table


DynamoDBTable



14:03:14 UTC-0800


DELETE_COMPLETE


AWS::EC2::Instance


MasterServer



14:02:44 UTC-0800


DELETE_COMPLETE


AWS::EC2::EIP


MasterEIP



14:02:44 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::EIP


MasterEIP



14:02:43 UTC-0800


DELETE_COMPLETE


AWS::EC2::EIPAssociation


AssociateEIP



14:02:29 UTC-0800


DELETE_COMPLETE


AWS::EC2::SecurityGroup


ComputeSecurityGroup



14:02:29 UTC-0800


DELETE_COMPLETE


AWS::SNS::Topic


SNS



14:02:28 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::SecurityGroup


ComputeSecurityGroup



14:02:28 UTC-0800


DELETE_IN_PROGRESS


AWS::SNS::Topic


SNS



14:02:27 UTC-0800


DELETE_COMPLETE


AWS::EC2::SecurityGroupIngress


ComputeSecurityGroupIngress



14:02:27 UTC-0800


DELETE_COMPLETE


AWS::EC2::SecurityGroupIngress


MasterSecurityGroupIngress



14:02:27 UTC-0800


DELETE_COMPLETE


AWS::SQS::QueuePolicy


SQSPolicy



14:02:26 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::Instance


MasterServer



14:02:26 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::EIPAssociation


AssociateEIP



14:02:26 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::SecurityGroupIngress


MasterSecurityGroupIngress



14:02:26 UTC-0800


DELETE_IN_PROGRESS


AWS::SQS::QueuePolicy


SQSPolicy



14:02:26 UTC-0800


DELETE_IN_PROGRESS


AWS::EC2::SecurityGroupIngress


ComputeSecurityGroupIngress



14:02:17 UTC-0800


ROLLBACK_IN_PROGRESS


AWS::CloudFormation::Stack


cfncluster-datcluster


The following resource(s) failed to create: [MasterServer]. . Rollback requested by user.



14:02:16 UTC-0800


CREATE_FAILED


AWS::EC2::Instance


MasterServer


Received FAILURE signal with UniqueId i-0896cd65d8fc44900



Physical ID:i-0896cd65d8fc44900



13:58:09 UTC-0800


CREATE_COMPLETE


AWS::EC2::EIPAssociation


AssociateEIP



13:57:59 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::Instance


MasterServer


Resource creation Initiated



13:57:58 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::Instance


MasterServer



13:57:54 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::EIPAssociation


AssociateEIP


Resource creation Initiated



13:57:53 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::EIPAssociation


AssociateEIP



13:57:52 UTC-0800


CREATE_COMPLETE


AWS::DynamoDB::Table


DynamoDBTable



13:57:52 UTC-0800


CREATE_IN_PROGRESS


AWS::DynamoDB::Table


DynamoDBTable


Did not have IAM permissions to process tags on AWS::DynamoDB::Table resource.



13:57:49 UTC-0800


CREATE_COMPLETE


AWS::EC2::NetworkInterface


MasterENI



13:57:46 UTC-0800


CREATE_COMPLETE


AWS::SQS::QueuePolicy


SQSPolicy



13:57:45 UTC-0800


CREATE_IN_PROGRESS


AWS::SQS::QueuePolicy


SQSPolicy


Resource creation Initiated



13:57:45 UTC-0800


CREATE_IN_PROGRESS


AWS::SQS::QueuePolicy


SQSPolicy



13:57:43 UTC-0800


CREATE_COMPLETE


AWS::EC2::SecurityGroupIngress


MasterSecurityGroupIngress



13:57:42 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::SecurityGroupIngress


MasterSecurityGroupIngress


Resource creation Initiated



13:57:42 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::SecurityGroupIngress


MasterSecurityGroupIngress



13:57:42 UTC-0800


CREATE_COMPLETE


AWS::EC2::SecurityGroupIngress


ComputeSecurityGroupIngress



13:57:41 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::SecurityGroupIngress


ComputeSecurityGroupIngress


Resource creation Initiated



13:57:41 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::SecurityGroupIngress


ComputeSecurityGroupIngress



13:57:40 UTC-0800


CREATE_COMPLETE


AWS::SNS::Topic


SNS



13:57:38 UTC-0800


CREATE_COMPLETE


AWS::EC2::Volume


SharedVolume



13:57:38 UTC-0800


CREATE_COMPLETE


AWS::EC2::EIP


MasterEIP



13:57:37 UTC-0800


CREATE_COMPLETE


AWS::EC2::SecurityGroup


ComputeSecurityGroup



13:57:36 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::SecurityGroup


ComputeSecurityGroup


Resource creation Initiated



13:57:32 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::NetworkInterface


MasterENI


Resource creation Initiated



13:57:32 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::NetworkInterface


MasterENI



13:57:31 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::SecurityGroup


ComputeSecurityGroup



13:57:28 UTC-0800


CREATE_IN_PROGRESS


AWS::SNS::Topic


SNS


Resource creation Initiated



13:57:28 UTC-0800


CREATE_IN_PROGRESS


AWS::SNS::Topic


SNS



13:57:26 UTC-0800


CREATE_COMPLETE


AWS::EC2::SecurityGroup


MasterSecurityGroup



13:57:25 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::SecurityGroup


MasterSecurityGroup


Resource creation Initiated



13:57:23 UTC-0800


CREATE_COMPLETE


AWS::SQS::Queue


SQS



13:57:22 UTC-0800


CREATE_IN_PROGRESS


AWS::SQS::Queue


SQS


The user does not have IAM permissions to process tags on AWS::SQS::Queue resource.



13:57:22 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::Volume


SharedVolume


Resource creation Initiated



13:57:22 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::EIP


MasterEIP


Resource creation Initiated



13:57:22 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::Volume


SharedVolume



13:57:21 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::EIP


MasterEIP



13:57:21 UTC-0800


CREATE_IN_PROGRESS


AWS::SQS::Queue


SQS


Resource creation Initiated



13:57:21 UTC-0800


CREATE_IN_PROGRESS


AWS::SQS::Queue


SQS



13:57:21 UTC-0800


CREATE_IN_PROGRESS


AWS::DynamoDB::Table


DynamoDBTable


Resource creation Initiated



13:57:21 UTC-0800


CREATE_IN_PROGRESS


AWS::DynamoDB::Table


DynamoDBTable



13:57:20 UTC-0800


CREATE_IN_PROGRESS


AWS::EC2::SecurityGroup


MasterSecurityGroup



13:56:51 UTC-0800


CREATE_IN_PROGRESS


AWS::CloudFormation::Stack


cfncluster-datcluster


User Initiated



  *   CfnCluster log:

2018-12-11 13:56:16,469 - DEBUG - cfncluster.cfncluster - CfnCluster cli starting

2018-12-11 13:56:16,483 - DEBUG - cfncluster.cfncluster - Namespace(cluster_name='datcluster', cluster_template=None, command='create', config_file='default_dat.conf', extra_parameters=None, func=<function create at 0x7faca12257d0>, norollback=False, nowait=False, region=None, tags=None, template_url=None)

2018-12-11 13:56:16,483 - INFO - cfncluster.cfncluster - Beginning cluster creation for cluster: datcluster

2018-12-11 13:56:16,483 - DEBUG - cfncluster.cfncluster - Building cluster config based on args Namespace(cluster_name='datcluster', cluster_template=None, command='create', config_file='default_dat.conf', extra_parameters=None, func=<function create at 0x7faca12257d0>, norollback=False, nowait=False, region=None, tags=None, template_url=None)

2018-12-11 13:56:17,269 - INFO - cfncluster.cfncluster - Creating stack named: cfncluster-datcluster

2018-12-11 13:56:17,630 - CRITICAL - cfncluster.cfncluster - Template format error: Unresolved resource dependencies [RootRole] in the Resources block of the template

2018-12-11 13:56:51,049 - DEBUG - cfncluster.cfncluster - CfnCluster cli starting

2018-12-11 13:56:51,058 - DEBUG - cfncluster.cfncluster - Namespace(cluster_name='datcluster', cluster_template=None, command='create', config_file='default_dat.conf', extra_parameters=None, func=<function create at 0x7fc0fb0617d0>, norollback=False, nowait=False, region=None, tags=None, template_url=None)

2018-12-11 13:56:51,058 - INFO - cfncluster.cfncluster - Beginning cluster creation for cluster: datcluster

2018-12-11 13:56:51,058 - DEBUG - cfncluster.cfncluster - Building cluster config based on args Namespace(cluster_name='datcluster', cluster_template=None, command='create', config_file='default_dat.conf', extra_parameters=None, func=<function create at 0x7fc0fb0617d0>, norollback=False, nowait=False, region=None, tags=None, template_url=None)

2018-12-11 13:56:51,495 - INFO - cfncluster.cfncluster - Creating stack named: cfncluster-datcluster

2018-12-11 13:56:51,853 - DEBUG - cfncluster.cfncluster - StackId: arn:aws:cloudformation:us-west-1:183449805178:stack/cfncluster-datcluster/7acb97c0-fcc5-11e8-88cb-06e649054ba8

2018-12-11 14:02:22,967 - DEBUG - cfncluster.cfncluster - Status: cfncluster-datcluster - ROLLBACK_IN_PROGRESS

2018-12-11 14:02:22,967 - CRITICAL - cfncluster.cfncluster -

Cluster creation failed.  Failed events:

2018-12-11 14:02:23,106 - INFO - cfncluster.cfncluster -   - AWS::EC2::Instance MasterServer Received FAILURE signal with UniqueId i-0896cd65d8fc44900

2018-12-11 14:02:23,107 - INFO - cfncluster.cfncluster -

  *

Your prompt help would be highly appreciated.
Regards
Jeff


________________________________

**Comment by JeffNing** [comment]
Dear Luca,
After taking your suggestion and appending the policy, all the permission issues appear to be resolved!
Now the issue seems to be the AWS default bootstrap scripts:

Here is the list of the errors in the order of the bootstrapping processes:

  1.  [ERROR] Command chef (chef-client --local-mode --config /etc/chef/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /etc/chef/dna.json) failed
  2.  Recipe: cfncluster::slurm_install
     *   Error executing action `run` on resource 'bash[copy license stuff]'
     *   Mixlib::ShellOut::ShellCommandFailed

STDERR: /tmp/chef-script20181211-1936-1saib0h: line 1: cd: slurm-slurm-16-05-3-1: No such file or directory

Any suggestion and/or advice would be appreciated.
Thanks
Jeff

________________________________

**Comment by lukeseawalker** [comment]
Hi @JeffNing,
from your config I see that your are using a custom AMI. 
From the error you reported it is likely that you started building your custom AMI from a different version of the product. You should start building your custom AMI from one of the following list:
for cfncluster 1.6.1 -> https://github.com/aws/aws-parallelcluster/blob/v1.6.1/amis.txt

L

**Comment by JeffNing** [comment]
Hi Luca,
Thank you so much for your kind help! With your advice of the new AMI us-west-1: ami-077e3b1efa9443476, I am able to move further and created a MasterServer. However, I encountered the new errors on launching ComputeFleet with the following logging errors:

Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack cfncluster-datcluster The following resource(s) failed to create: [ComputeFleet].
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 2 FAILURE signal(s) out of 2.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

When I login into the compute node, I found the error message in the cfn-init.log:

2018-12-12 19:40:32,650 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-1.amazonaws.com
2018-12-12 19:40:32,650 [DEBUG] Describing resource ComputeServerLaunchTemplate in stack cfncluster-datcluster
2018-12-12 19:40:32,880 [INFO] -----------------------Starting build-----------------------
2018-12-12 19:40:32,881 [DEBUG] Not setting a reboot trigger as scheduling support is not available
2018-12-12 19:40:32,881 [ERROR] -----------------------BUILD FAILED!------------------------
2018-12-12 19:40:32,885 [ERROR] Unhandled exception during build: No configuration found with name: getCookbooks
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 413, in __init__
    self._processConfigSetsDefinition(configSetsDef, initModel)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 433, in _processConfigSetsDefinition
    processedList = self._processConfigList(configList, model)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 501, in _processConfigList
    returnSet.extend(self._processConfigList(configDef, model))
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 488, in _processConfigList
    raise NoSuchConfigurationError("No configuration found with name: %s" % configList)
NoSuchConfigurationError: No configuration found with name: getCookbooks
2018-12-12 19:40:33,158 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-1.amazonaws.com
2018-12-12 19:40:33,158 [DEBUG] Signaling resource ComputeFleet in stack cfncluster-datcluster with unique ID i-05dfc39d41b5f94c6 and status FAILURE

What might I do inappropriately? Your prompt help will be appreciated.
Warm regards
Jeff

________________________________

**Comment by JeffNing** [comment]
Hi Luca,
Thank you so much for the help. I am able to create a default cfncluster with all the defaults.
However, when I added the option s3_read_resource = arn:aws:s3:::vcyt-dat-cfncluster/*, the error "Template format error: Unresolved resource dependencies [RootRole] in the Resources block of the template" comes back. Cannot I use S3 bucket for cfncluster?
Another issue: when changing the option compute_instance_type = r5.12xlarge instead of the default t2.micro, the cfncluster just creates one compute node instead of two nodes and also shows this error:
Status: cfncluster-datcluster - CREATE_FAILED
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack cfncluster-datcluster The following resource(s) failed to create: [ComputeFleet].
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 1 SUCCESS signal(s) out of 2.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
So what might go wrong with it?
Thanks
Jeff

________________________________

**Comment by lukeseawalker** [comment]
Hi @JeffNing,
I see three points here:
- "raise NoSuchConfigurationError("No configuration found with name: %s" % configList)
NoSuchConfigurationError: No configuration found with name: getCookbooks". The source of this problem could be your custom template template_url = http://s3-us-west-1.amazonaws.com/vcyt-dat-cfncluste/default_dat.cfn.json. I would double check it. Why the need to use a custom template?
- there is a bug in using the configuration "s3_read_resource". If you are using a custom role, you must attach the policy to read that bucket into your role and do not use s3_read_resource nor s3_read_write_resource
- "Received 1 SUCCESS signal(s) out of 2." Check your EC2 instance limit for the type you want to launch

L

**Comment by JeffNing** [comment]
Hi Luca,
Thank you so much for your kind, generous help! Yes, I can launch a CfnCluster with other instance types. And I can also access my S3 bucket with the policy into my role.
The reason to use a customized template is to remove some of the services so the launch process would be faster.
Best
Jeff
________________________________
