### ISSUE TITLE
Compute node shutdown unexpectedly

### ISSUE THREAD

**Issue by 91bsjun** [aws/aws-parallelcluster#781]
**Environment:**
 - aws-parallelcluster-2.0.2
 - OS: centos7
 - Scheduler: SGE
 - Master instance type: t2.xlarge
 - Compute instance type: c4.8xlarge

**Bug description and how to reproduce:**
Compute nodes were down unexpectedly.
The removed hosts are still remaining at <code>qhost</code>. I know that this is not a normal state.
<pre>
[centos@ip-172-31-21-156 LiSnPS]$ qhost
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
ip-172-31-16-131        lx-amd64       36    2   18   36     -   58.8G       -     0.0       -
ip-172-31-18-220        lx-amd64       36    2   18   36     -   58.8G       -     0.0       -
ip-172-31-19-211        lx-amd64       36    2   18   36 36.25   58.8G    6.1G     0.0     0.0
ip-172-31-19-71         lx-amd64       36    2   18   36     -   58.8G       -     0.0       -
ip-172-31-20-28         lx-amd64       36    2   18   36 36.03   58.8G    3.4G     0.0     0.0
</pre>
Part of <code>/var/log/sqswatcher</code>
<pre>
2018-12-18 19:48:02,688 INFO [sqswatcher:pollQueue] eventType=autoscaling:EC2_INSTANCE_TERMINATE
2018-12-18 19:48:02,689 INFO [sqswatcher:pollQueue] instanceId=i-032047debdb957f8b
2018-12-18 19:48:02,722 INFO [sge:removeHost] Removing ip-172-31-16-131
root@ip-172-31-21-156.us-east-2.compute.internal removed "ip-172-31-16-131.us-east-2.compute.internal" from administrative host list
root@ip-172-31-21-156.us-east-2.compute.internal modified "all.q" in cluster queue list
root@ip-172-31-21-156.us-east-2.compute.internal modified "@allhosts" in host group list
Host object "ip-172-31-16-131" is still referenced in cluster queue "all.q".
2018-12-18 19:48:02,788 ERROR [sge:__runSgeCommand] Failed to run ['/opt/sge/bin/lx-amd64/qconf', '-de', 'ip-172-31-16-131']

root@ip-172-31-21-156.us-east-2.compute.internal removed "ip-172-31-16-131.us-east-2.compute.internal" from submit host list
2018-12-18 19:50:03,154 INFO [sqswatcher:pollQueue] eventType=autoscaling:EC2_INSTANCE_TERMINATE
2018-12-18 19:50:03,154 INFO [sqswatcher:pollQueue] instanceId=i-0c52f2662a0e675a2
</pre>

Autoscaling group log

> Terminating EC2 instance: i-023db32f81c1169c5
> Terminating EC2 instance: i-023db32f81c1169c5
> At 2018-12-18T12:03:33Z instance i-023db32f81c1169c5 was taken out of service in response to a user request, shrinking the capacity from 5 to 4.

**Comment by extremoburo** [comment]
Hello, any luck with that ? I'm facing the a similar issue.
