### ISSUE TITLE
cfncluster/parallelcluster best configuration

### ISSUE THREAD

**Issue by carlitador** [aws/aws-parallelcluster#799]
Hi everybody,

I am a very new user of AWS ec2 and cfncluster.
I have a configuration which is working but I'm sure it could work way better so I need some advices...
Here is what I do and what would like to do:

- I have setup a instance with the software I use for computation installed on it and saved it as an AMI.
- I have mounted a s3 bucket on it so I can access the results of the computation even without any instance running on ec2 (probably not ideal... because quite slow). The thing is I want to use my local graphic/RAM ressources to see the results when calculations are finished.
- I would like to be able to see the calculations while they are running directly on my local machine. The software I use enables me to connect though a certain ip/port server. I am not familiar at all with security groups, vpc and subnets... And I have no idea how to configure it to be able to connect from my local machine on compute nodes

Any advice for my configuration is more than welcome
Thank you very much
Cheers

**Comment by carlitador** [comment]
> 
> 
> Hi everybody,
> 
> I am a very new user of AWS ec2 and cfncluster.
> I have a configuration which is working but I'm sure it could work way better so I need some advices...
> Here is what I do and what would like to do:
> 
>     * ```
>       I have setup a instance with the software I use for computation installed on it and saved it as an AMI.
>       ```
> 
>     * ```
>       I have mounted a s3 bucket on it so I can access the results of the computation even without any instance running on ec2 (probably not ideal... because quite slow). The thing is I want to use my local graphic/RAM ressources to see the results when calculations are finished.
>       ```
> 
>     * ```
>       I would like to be able to see the calculations while they are running directly on my local machine. The software I use enables me to connect though a certain ip/port server. I am not familiar at all with security groups, vpc and subnets... And I have no idea how to configure it to be able to connect from my local machine on compute nodes
>       ```
> 
> 
> Any advice for my configuration is more than welcome
> Thank you very much
> Cheers

**Comment by sean-smith** [comment]
Hi,

1. You should look into EFS, it does what you've done with S3 and allows you to mount the filesystem on your local machine, and has native parallelcluster support.

    See https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#efs and https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEFS.html#efs-create-file-system

2. You can specify `additional_sg` in the parallelcluster config, this allows you to open up a port to your machine / ip range. We support specifying this on cluster creation, so you can create 1 security group and attach it to your running clusters.

    See https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#additional-sg

    Another method of doing this is modifying the security group we create. In the AWS console go to EC2 > Security Groups and click on the group named `parallelcluster-[cluster-name]-ComputeSecurityGroup-...`, now you can modify the inbound rules to allow traffic from your ip address into the machine on the port you desire.

**Comment by carlitador** [comment]
Yes I think I figured it out but didnt have to try it yet :)
Thanks again

**Comment by carlitador** [comment]
Hi @sean-smith,
I tried a few things that you were proposing for my configuration.
I managed to mount an EFS volume on my local machine. I uploaded a few files on this EFS, but one thing I don't understand is how to use this actual EFS for my cluster ?
In the parallel cluster configuration file you can give :
shared_dir = efs
encrypted = false
performance_mode = generalPurpose
How should I do to choose my existing EFS with these parameters ? 
Something like "shared_dir = fs-xxxxxx" ?
Or should I prepare an instance with my EFS mounted somewhere on it, save the image, and use this custom image for master and compute nodes ?

Thank you again
Cheers :+1:

**Comment by enrico-usai** [comment]
Hi @carlitador,

when you added the `additional_sg` configuration parameter, the specified security group will be added to both Master and Compute instances, in addition to the default one, created by ParallelCluster itself:

![image](https://user-images.githubusercontent.com/10634438/52266207-1c394980-2936-11e9-8b11-2ba42a952d0c.png)

![image](https://user-images.githubusercontent.com/10634438/52266183-0cba0080-2936-11e9-97b1-38019d0f1cf5.png)

Please verifyt that you added the configuration parameter in the [vpc](https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#vpc) section and not in the _cluster_ one.

For completeness, another possibility is to use the [vpc_security_group_id](https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#vpc-security-group-id) configuration parameter. 
It can be used in association with the `additional_sg` parameter.
