### ISSUE TITLE
mpi4py not found and then won't build

### ISSUE THREAD

**Issue by exprexxo** [aws/aws-parallelcluster#80]
Since cfncluster uses a specific ami, that ami should have mpi4py already compelled and added to python so that the import mpi4py works.  After all that is the point f cfncluster is to be able to do mpi jobs 
When I try to build mpi4py on the amazon linux it does not succeed due to missing components

**Comment by sean-smith** [comment]
I'm going to close this ticket, for users who want to install `mpi4py` on their instances. See https://mpi4py.readthedocs.io/en/stable/install.html

You'll need the `python-devel` package for the compilation to succeed.
