### ISSUE TITLE
Poor MPI performance

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-parallelcluster#815]
**Environment:**
 - AWS ParallelCluster 
 - OS: CentOS
 - Scheduler: SGE
 - Master instance type: t2.micro
 - Compute instance type: m4.4xlarge

**Bug description and how to reproduce:**
I’m performing some tests with AWS Parallel Cluster and the performance has shown some funky behavior. The cluster creation process works fine but the issues are mostly related to communications and, more specifically to MPI operations. The basic configuration is one master instance (usually t2.micro) and two compute nodes. My initial test with two m4.2xlarge instances was pretty encouraging as I was essentially able to double up performance versus a single m4.2xlarge instance. However, further tests have resulted in much poorer performance (e.g. two m4.4xlarge instances or two m4a.2xlarge instances). I have isolated the problem to MPI communications as latency has really gone up significantly even for small packets (e.g. 400us vs. 12us for single instances). I understand that these instances do not have dedicated networking yet I don’t fully understand the discrepancy in behavior. Any advice on how to achieve better performance or how to guide the cluster-creation script in reserving the most optimal networking between instances?

**Additional context:**
Config file
[aws]
aws_region_name = us-west-2
aws_access_key_id = AKI***
aws_secret_access_key = 3DI***

[cluster ***]
vpc_settings = ***
key_name = ***
master_instance_type = t2.micro
compute_instance_type = m5.4xlarge
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
scheduler = sge
base_os = centos7

[vpc odyvpc]
master_subnet_id = subnet-2bb***
vpc_id = vpc-cd***

[global]
update_check = true
sanity_check = true
cluster_template = ***

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

**Comment by sean-smith** [comment]
### Placement Groups
First off you can easily optimize by using a placement group, placement groups ensure non-blocking, non-oversubscribed fully bi-sectional bandwidth. It's the lowest level of network grouping.

in your config you'd add:
```
[cluster ***]
placement_group = DYNAMIC
```
See https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#placement-group

### ENA
Next you can use ENA, make sure it's enabled by following the guide here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html

You'll also need to use an enhanced networking instance, this includes all M5's.

### MPI
What version of MPI are you using? How many ranks? Have you disabled hyperthreading?

**Comment by afernandezody** [comment]
Hi Sean,
Thank you for your insight. I'm using OpenMPI. I'm not hotplugging but simply performing some dual microbenchmarks by setting the number of MPI threads equal to the cores and the vCPUs. Proceeding this way provides some data about hyperthreading performance for MPI jobs.

**Comment by sean-smith** [comment]
Are you using the latest v4.0.0 version of OpenMpi?

**Comment by afernandezody** [comment]
MPI jobs are still not working properly. Using placement groups has not make any difference in performance (I’ve tried different combinations of M5 master/compute instances). 
It seems that ParallelCluster installs OMPI v1.10.7 by default. I installed OMPI v4.0.0 in a different directory (/opt/openmpi as recommended by the OMPI group) but always got the error message “There are not enough slots available in the system to satisfy the # slots that were requested by the application” when I tried to run a job regardless of the number of requested MPI ranks. Deleting the default installation of OMPI before installing OMPI v4.0.0 did not make things better either.

**Comment by sean-smith** [comment]
Hi,

You're correct that the Centos7 AMI includes Open MPI `v1.10.7`, however this is an artifact of the ami and not something we install.

I think your problem stems from running without a hostfile / not through the scheduler. I was able to install open mpi with the following:

    wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.0.tar.gz
    gunzip -c openmpi-4.0.0.tar.gz | tar xf -
    cd openmpi-4.0.0
    sudo ./configure --prefix=/opt/openmpi
    sudo make all install

Then submit a job (using sge):

    qsub -pe mpi 144 job.sh

Where `job.sh` contains:

    #!/bin/bash

    /opt/openmpi/bin/mpirun -np 144 [Your program]

The error `There are not enough slots available...` is most likely caused because you're running on the master instance, a t2.micro instead of the compute m5.4xlarge instances.

**Comment by afernandezody** [comment]
Hi Sean,
I wasn’t implying that OMPIv4.0.0 should be included in any specific AMI (and I don’t know who would be responsible for that task). I’ve tried about 4 times what you suggested and always ran into the same sort of troubles. Firstly, I changed the configuration to one m5.large master instance plus two compute instances of the same type to avoid any incompatibility with t2.micro as the master instance. However, this doesn’t seem to be the issue. Configuring and making OMPIv4.0.0 works apparently well, at least at first sight. However, launching jobs results in funky behavior. A summary of my attempts would be:
i)	If I try to launch from the master instance with a shell script per your suggestion, it doesn’t find the command mpirun (see problem iii)
ii)	If I call the command mpirun directly on the master instance, I get the error message (lack of slots) previously reported 
iii)	If I log in into one of the compute instances, the system is never able to find the command mpirun
Furthermore, when I log in into the compute instance, the directory /opt looks like corrupted. The subdirectory openmpi doesn’t appear (unlike in the master instance) and checking disk usage (sudo du -ks) returns the error messages:
du: cannot access ‘./proc/16538/task/16538/fd/3’: No such file or directory
du: cannot access ‘./proc/16538/task/16538/fdinfo/3’: No such file or directory
du: cannot access ‘./proc/16538/fd/4’: No such file or directory
du: cannot access ‘./proc/16538/fdinfo/4’: No such file or directory
I’m not sure if there is a synchronization (for the lack of a better technical expression) problem or something else that appears at my end but not at yours.
Thanks.

**Comment by sean-smith** [comment]
Hi,

Ok, I was able to re-produce your issue and found the following:

I can submit a job with sge like:
```
qsub -pe mpi 144 job.sh
```

Where my `job.sh` contains:
```
#!/bin/bash

/opt/openmpi/bin/mpirun [Your MPI program]
```
Strangely if I add the `-np 144` to the mpirun command I get the same slots not found error. This implies SGE is not communicating with mpirun correctly, despite compiling with the `--with-sge` flag (see above).

Note, openmpi needs to be install individually on each of the compute nodes, and cannot be installed in the shared directory.

I'm going to mark this as a bug for now, you can use the above to run your mpi jobs until we figure this out.

**Comment by sean-smith** [comment]
Hi,

Ok, I was able to re-produce your issue and found the following:

I can submit a job with sge like:
```
qsub -pe mpi 144 job.sh
```

Where my `job.sh` contains:
```
#!/bin/bash

/opt/openmpi/bin/mpirun [Your MPI program]
```
Strangely if I add the `-np 144` to the mpirun command I get the same slots not found error. This implies SGE is not communicating with mpirun correctly, despite compiling with the `--with-sge` flag (see above).

Note, openmpi needs to be install individually on each of the compute nodes, and cannot be installed in the shared directory.

I'm going to mark this as a bug for now, you can use the above to run your mpi jobs until we figure this out.

**Comment by afernandezody** [comment]
Hello Sean,
(After being busy with other projects) I was finally able to make this work following your suggestions. It's actually working well for hyperthreaded jobs, not so much for single-threaded ones. The problem is the following: If I have 64 CPUs (2 compute nodes x 16 cores/node x 2 threads), and submit a 64-ranks job, it works fine. However, when I submit a 32-ranks job, it allocates the job to a single node rather than distributing it single-threaded across the two nodes. In other clusters, I didn't face this issue while using mpirun. I'm unsure if this is related to the communication issues between SGE and mpirun that you mentioned previously or if it's entirely a different thing. 
To somewhat go around this issue, I'm also wondering if it would be possible to manually disable hyperthreading for the compute nodes of a cluster created with AWS-parallelcluster, and take it from there.
Thanks.

**Comment by sean-smith** [comment]
@afernandezody 

Yep, you can disable hyperthreading. There's two things you need to do disable hyperthreading.

1.  Set schedulers to use cores
See https://github.com/aws/aws-parallelcluster/issues/36#issuecomment-200983281
2. Turn off hyper-threading in a post-install script
See [Disabling Intel Hyper-Threading Technology on Amazon Linux](https://aws.amazon.com/blogs/compute/disabling-intel-hyper-threading-technology-on-amazon-linux/) (should be similar for centos 7)

**Comment by afernandezody** [comment]
Hi Sean,
It has taken me awhile to come back to this as I was checking out some other features. I tried hotplugging a couple of weeks ago but didn't work. At the time, I thought that the extra json would do the trick but it doesn't. I have tried different instances but I always arrive to the same point. The command 'qhost' returns
NCPU 2x(cores)   NCOR (cores)   NTHR 2
I cannot make the last figure to be 1. One of my scripts reads like:
[aws]
aws_region_name = us-west-2
aws_access_key_id = XXXX
aws_secret_access_key = XXXX

[cluster odycluster]
vpc_settings = odyvpc
placement_group = DYNAMIC
placement = compute
key_name = XXXX
master_instance_type = t2.micro
compute_instance_type = c5.large
initial_queue_size = 2
max_queue_size = 2
maintain_initial_size = true
scheduler = sge
base_os = centos7
extra_json = { "cfncluster" : { "cfn_scheduler_slots" : "cores" } }

[vpc odyvpc]
master_subnet_id = XXXX
vpc_id = XXXX

[global]
update_check = true
sanity_check = true
cluster_template = odycluster

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}
 
Thanks.

**Comment by sean-smith** [comment]
Hi @afernandezody,

Are you still having issues with this? How can we make this easier for you?

**Comment by afernandezody** [comment]
Hi Sean,
It has been working fine except when I tried to use a customized AMI (but that is another issue and I've abandoned this approach for the time being). Feel free to close the issue. Thank you.
