### ISSUE TITLE
ParallelCluster doesn't work well with Torque scheduler

### ISSUE THREAD

**Issue by darreninmasterson** [aws/aws-parallelcluster#819]
**Environment:**
 - AWS ParallelCluster
 - OS: alinux
 - Scheduler: Torque
 - Master instance type: e.g. m5.xlarge
 - Compute instance type: . m5.xlarge

**Bug description and how to reproduce:**
A clear and concise description of what the bug is and the steps to reproduce the behavior.
Problem description:
We deploy parallelcluster base on AWS document and torque as job scheduler. After parallelcluster created, we try to submit sample job, for example, hello world, the job run successfully in the beginning, and stuck a few minutes later. After that, we try to luanched a new cluster and watch status of compute node, we found status of compute are free in the beginning, and always change to down a few minut es later. After we restart pbs_mem service on the compute nodes, status of compute change to free, but compute cannot pick up jobs when I submit job on master node.
Is anyone have the same problem to launch parallelcluster when torque as job schedule, looking for your help, thanks.

**Comment by enrico-usai** [comment]
Hi @darreninmasterson ,

AWS ParallelCluster [is designed](https://aws-parallelcluster.readthedocs.io/en/latest/autoscaling.html) to automatically scale up/down compute nodes as needed.
If an instance had no jobs for some minutes (10 as default) the instance is terminated. 
It is possible to configure this timeout as described in the [documentation](https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#scaling-section).

If you need a fixed cluster size, you can configure the appropriate [initial queue size](https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#initial-queue-size) and set `maintain_initial_size = true` in the configuration.

Let us know if it helps.
