### ISSUE TITLE
MinSuccessfulInstancesPercent error

### ISSUE THREAD

**Issue by armedgorillas** [aws/aws-parallelcluster#822]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.1.1
 - OS: ubuntu1604
 - Scheduler: slurm
 - Master instance type: t2.micro
 - Compute instance type: r4.8xlarge

**Bug description and how to reproduce:**

According to [this comment on this issue](https://github.com/aws/aws-parallelcluster/issues/746#issuecomment-446898344), including `s3_read_resource` in the parallel cluster config file will result in:

```bash
  - AWS::AutoScaling::AutoScalingGroup ComputeFleet Received 0 SUCCESS signal(s) out of 2.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
```
.

I'm getting the same error even after removing that parameter from my configuration file. From the console, it looks like both worker nodes are spinning up, but it sits for about a half hour before giving me the error.

Are there other invalid parameters I'm using?

**Additional Info**

This is my configuration file
```ini
[global]
cluster_template = pcheck
update_check = true
sanity_check = true

[aws]
aws_region_name = us-east-1
aws_access_key_id =...
aws_secret_access_key = ...

[cluster pcheck]
key_name = ...
compute_instance_type = r4.8xlarge
initial_queue_size = 2
scheduler = slurm
cluster_type = spot
spot_price = .75
base_os = ubuntu1604
vpc_settings = pvpc
scaling_settings = pscaling

[vpc pvpc]
vpc_id = ...
master_subnet_id = ...

[scaling pscaling]
scaledown_idletime = 10
```

**Comment by sean-smith** [comment]
Hi,

The error message `ComputeFleet Received 0 SUCCESS signal(s)` is a general error message whenever the compute nodes fail to bootstrap.

The biggest thing I see is `spot_price = .75`, if it can't get two spot instances at that price in time it'll time out. This is also compounded by the `initial_queue_size = 2`, which requires two instances to be active before the cluster finishes creation.

1. Instances are booting up only to be reclaimed by spot before they finish bootstrap
2. It can't get two instances at that price in time (on demand is $2.128)

To address this you can get rid of `spot_price`, it'll use the current spot market price, which is always less than on demand. Read more about spot pricing here: https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/

You can also set `initial_queue_size = 0`, this way the cluster will create, then when you submit a job it'll scale up (without the create timeout).

**Comment by sean-smith** [comment]
oh and to clarify `spot_price` when used with slurm is a dollar figure **not** percentage.  See https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#spot-price

**Comment by armedgorillas** [comment]
works! Thank Sean. 

For the spot price, will the bid price for the cluster move with the market price, or is it fixed from the time of cluster creation?

**Comment by sean-smith** [comment]
If not specified it moves with the spot market price (capped at on demand). If `spot_price` is specified it'll stay at that price (or below).

**Comment by armedgorillas** [comment]
thanks for all your help!
