### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by mukulagrawal78** [aws/aws-parallelcluster#830]
Can we create a cluster of GPU machines?
If yes, can we use GPU instances only for compute nodes?

**Comment by sean-smith** [comment]
yes and yes

for example:

```
[cluster gpu]
...
master_instance_type = c5.large
compute_instance_type = p3.2xlarge
```

**Comment by mukulagrawal78** [comment]
Thanks @sean-smith 
We have customized AMI and I will like reduce number of AMIs to maintain.
So just a quick question. Can GPU AMI be used for non-GPU machines as well?

**Comment by lukeseawalker** [comment]
yes.
Actually our distributed AMI are GPU capable.
