### ISSUE TITLE
Add the possibility to encrypt the master OS disk

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-parallelcluster#834]
The ebs section helped encrypt the 20 GB drive indeed. Any method to encrypt the master OS disk?

_Originally posted by @ahmedelz in https://github.com/aws/aws-parallelcluster/issues/823#issuecomment-455735888_

**Comment by ProlucidDavid** [comment]
Is it correct to say there hasn't been any progress on this functionality? 

If I'm not mistaken, [this forum post](https://forums.aws.amazon.com/thread.jspa?messageID=720702&#720702) says I would need to create an AMI with an encrypted root drive and use that in the pcluster config file. Is this understanding correct? This post is a little old, is it still applicable?

**Comment by lukeseawalker** [comment]
Hi @ProlucidDavid,
the reported instructions are still applicable, and I'm reporting them here:

1. Create a custom AMI choosing one of the first two methods described in the official doc [here](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html):
   * [Modify an AWS ParallelCluster AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html#modify-an-aws-parallelcluster-ami)
   * [Build a Custom AWS ParallelCluster AMI](https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorials_02_ami_customization.html#build-a-custom-aws-parallelcluster-ami) 
2. Copy the AMI to a new one using encryption, as described [here](https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/)
3. Use the new encrypted AMI ID as `custom_ami` parameter value in ParallelCluster configuration file
4. Create the cluster 

The feature enhancement to enable encryption at launch instance time is tracked by this ticket.

**Comment by enrico-usai** [comment]
This ticket has been addressed by the patch: https://github.com/aws/aws-parallelcluster/pull/2652
It will be part of the 3.0.0 release.

**Comment by lukeseawalker** [comment]
this is available in [PCluster 3.0.0](https://github.com/aws/aws-parallelcluster/releases/tag/v3.0.0)
