### ISSUE TITLE
ParallelCluster compute nodes not scaling down when cloud formation stack is in status 'UPDATE_COMPLETE'

### ISSUE THREAD

**Issue by sanman-99** [aws/aws-parallelcluster#845]
**Environment:**
 - AWS ParallelCluster version aws-parallelcluster-2.0.2
 - OS: alinux
 - Scheduler: SGE
 - Master instance type: m5.2xlarge
 - Compute instance type: r5.2xlarge

**Bug description and how to reproduce:**
I noticed that after making any udpates to my cloud formation stack that was created for the parallel cluster then the scale down functionality handled by nodewatcher on the compute nodes would no longer work.  Even if the nodes didn't have any jobs for the period of inactivity threshold time (i.e. 10 min) the compute node still wouldn't be spun down.  This results in loss of valuable cash.  Looking at the nodewatcher logs it would always report the stack creation completion of False.

2019-02-06 12:45:07,040 INFO [nodewatcher:main] parallelcluster-fs-galprod1805-1a creation complete: False

I believe I have found why this is, but not sure the reasoning of being coded this way.  Looking in nodewatcher.py, in function stackCreationComplete, it would only ever return true if the stack is at status CREATE_COMPLETE, however if anyone makes an update to their stack, the status then changes to UPDATE_COMPLETE, thus breaking this functionality:

```
def stackCreationComplete(stack_name, region, proxy_config):
    log.info('Checking for status of the stack %s' % stack_name)
    cfn_client = boto3.client('cloudformation', region_name=region, config=proxy_config)
    stacks = cfn_client.describe_stacks(StackName=stack_name)
    log.info('Status %s' % stacks['Stacks'][0]['StackStatus'])
    return stacks['Stacks'][0]['StackStatus'] == 'CREATE_COMPLETE'
``` 

I would recommend this function be changed to handle this situation.  We often make changes to the stack, for example changing the compute node type.  Possibly change the return in that function to be (this is what I have done as a temporary patch):

return stacks['Stacks'][0]['StackStatus'] == 'CREATE_COMPLETE' or stacks['Stacks'][0]['StackStatus'] == 'UPDATE_COMPLETE'

**Comment by sean-smith** [comment]
This has been fixed, just not released yet:

https://github.com/aws/aws-parallelcluster-node/blob/develop/nodewatcher/nodewatcher.py#L159

**Comment by sanman-99** [comment]
Ok, perfect.  Is there an easy way I can get my compute nodes to use this version versus the current one?

**Comment by sean-smith** [comment]
yep, clone the repo and update the cluster to use a custom node package. 

See: https://aws-parallelcluster.readthedocs.io/en/latest/custom_node_package.html

Note, this will only apply to newly launched compute nodes. You can scale the asg to 0 nodes, then back up. Basically:

```
pcluster stop [your_cluster]
# wait a few mins for scale down
pcluster start [your_cluster]
```

**Comment by sean-smith** [comment]
Resolving. Feel free to re-open
