### ISSUE TITLE
Typos in ParallelCluster Documentation

### ISSUE THREAD

**Issue by RodneyMarable** [aws/aws-parallelcluster#851]
There is a typo in docs/configuration.rst under the "custom AMI" section.

"ID of a Custom AMI, to use instead of default published AMI’s."

should read:

"ID of a Custom AMI, to use instead of default published AMIs."

Please refer to Rule 2b: https://www.grammarbook.com/punctuation/apostro.asp

**Comment by sean-smith** [comment]
Nice catch 👍🏻

Feel free to submit a Pull Request to fix it (and other mistakes): https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by RodneyMarable** [comment]
I found some more typos.  I'll fix them and submit a pull request.

**Comment by RodneyMarable** [comment]
Pull request submitted: https://github.com/aws/aws-parallelcluster/pull/856
