### ISSUE TITLE
Retrieve efs shared_dir from cfnconfig file

### ISSUE THREAD

**Issue by JorikRemy** [aws/aws-parallelcluster#853]
**Environment:**
 - aws-parallelcluster-2.1.1
 - OS: Centos 7
 - Scheduler: slurm
 - Master instance type: m4.large
 - Compute instance type: m4.large

**Bug description and how to reproduce:**
I do not find the efs shared_dir in the /etc/parallelcluster/cfnconfig file but I can see the cfn_ephemeral_dir and the cfn_shared_dir from EBS.
Is there a way to retrieve the mountpoint ?

**Comment by sean-smith** [comment]
See `/etc/dna.json`, there's a key `cfn_efs_shared_dir` that has 5 parameters. 

See https://github.com/aws/aws-parallelcluster/blob/develop/cloudformation/aws-parallelcluster.cfn.json#L592

**Comment by JorikRemy** [comment]
Thanks for your answer. I'm going to use that solution but I do not find it in /etc/dna.json, only in /tmp/dna.json
Is it planned to put that information into the /etc/parallelcluster/cfnconfig file ? It would be really useful.

Thank

**Comment by sean-smith** [comment]
We don't have plans right now. The other thing you can do is retrieve that parameter from the cloudformation stack, with a bit of python code. Here's an example:

```python
import boto3

cfn = boto3.client(
        "cloudformation",
        region_name=[your_region]
)

stack_name = "parallelcluster-" + [cluster_name]
result_stack = cfn.describe_stacks(StackName=stack_name).get("Stacks")[0]
parameters = stack.get("Parameters")
efs_options = filter(lambda x: x.get("ParameterKey") == "EFSOptions", parameters)[0].get("ParameterValue")
shared_dir = efs_options.split(",")[0]
```
