### ISSUE TITLE
S3 access denied

### ISSUE THREAD

**Issue by gjparker9** [aws/aws-parallelcluster#854]
**Environment:**
 - aws-parallelcluster-2.1.1]
 - alinux
 - SGE
 - t3.any
 - t3.any

**Bug description and how to reproduce:**
Following https://aws.amazon.com/blogs/opensource/aws-parallelcluster/ but included aws_access_key_id and aws_secret_access_key in config under [aws] section (understand it's not best practice). in [cluster default] added s3_read_write_access_resource = arn:aws:s3:::mybucket/*, cluster_type = spot and spot_price = X. Cluster spins up fine and trivial tests of SGE is fine but no access to S3 (permission denied).

E.g. on the head node:
$ aws s3 ls
An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied

if i copy ~/.aws/credentials and ~/.aws/config to head node, then access to S3 is fine from head node and compute nodes.

i realize i can workaround w/ a post-install script, but....

i also understand i can add a custom AMI (based on cfncluster AMI), but i'm looking for a minimal change.

not clear why aws_access_key_id and aws_secret_access_key are not being propagated to parallelcluster.

**Comment by sean-smith** [comment]
@gjparker9 

The issue is the `arn:aws:s3:::mybucket/*` resource you specified gives you read/write access only to `mybucket`. You could do:

```
$ aws s3 ls s3://mybucket
```

However listing all buckets, like you did with `aws s3 ls` won't work.

The `aws_access_key_id` and `aws_secret_access_key` aren't copied onto the instance, a separate IAM role is created and the credentials are available on the instance magically (via [Instance Profile](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html) )

I know this arn schema is confusing, so I wrote https://aws-parallelcluster.readthedocs.io/en/latest/s3_resources.html to better explain it.

**Comment by gjparker9** [comment]
thanks for the response @sean-smith 

i was just saving typing in my comment.

$ aws s3 ls s3://mybucket 

still returns 

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied on head/compute nodes.

i'll dig around in the generated IAM role.... hmmm.  given that if i copy over ~/.aws to the head node, S3 access is ok, seems something fell over during this IAM creation.

so, i am correct, this should be working out-of-the-box?

**Comment by sean-smith** [comment]
Did you mean to specify `s3_read_write_resource ` instead of `s3_read_write_access_resource` ?

**Comment by gjparker9** [comment]
i did specify 's3_read_write_resource'. should have copied and pasted directly from config file.

**Comment by gjparker9** [comment]
the generated IAM role looks file (attached a policy called 'S3ReadWrite' which appears to have the correct info).

**Comment by sean-smith** [comment]
We should really add some logic to validate parameters that do nothing, like:

`Did you mean to specify X parameter? It has no effect.`

**Comment by gjparker9** [comment]
yes, warnings on unsupported parameters would be helpful...

still no joy, though.

**Comment by sean-smith** [comment]
oh I see, re-reading your previous comments, you specified `s3_read_write_resource` in your config. Can you paste your config? 

What does the generated IAM role look like? You can see it by clicking on `Master Server` > `IAM Role` in the EC2 Console.

**Comment by gjparker9** [comment]
here's config (X is redacted) (so S3 bucket is actually com.parker9.wp)

[aws]
aws_region_name = us-west-1
aws_access_key_id = X
aws_secret_access_key = X

[cluster default]
vpc_settings = public
key_name = X
compute_instance_type = t3.nano
cluster_type = spot
spot_price = 0.003
s3_read_write_resource = arn:aws:s3:::com.parker9.wp/*

[vpc public]
master_subnet_id = subnet-20b7f647
vpc_id = vpc-a2d061c5
ssh_from = X/32

[global]
update_check = true
sanity_check = true
cluster_template = default

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

**Comment by gjparker9** [comment]
IAM role on master automatically generated w/ name: parallelcluster-t3-nano-RootRole-1N78K7571BIOB

has two policies attached: parallelcluster and S3ReadWrite.

parallelcluster (account number redacted w/ X)

{
    "Statement": [
        {
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:AttachVolume",
                "ec2:DescribeInstanceAttribute",
                "ec2:DescribeInstanceStatus",
                "ec2:DescribeInstances"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow",
            "Sid": "EC2"
        },
        {
            "Action": [
                "dynamodb:ListTables"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow",
            "Sid": "DynamoDBList"
        },
        {
            "Action": [
                "sqs:SendMessage",
                "sqs:ReceiveMessage",
                "sqs:ChangeMessageVisibility",
                "sqs:DeleteMessage",
                "sqs:GetQueueUrl"
            ],
            "Resource": [
                "arn:aws:sqs:us-west-1:X:parallelcluster-t3-nano-SQS-CJPJIDW6Z837"
            ],
            "Effect": "Allow",
            "Sid": "SQSQueue"
        },
        {
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:UpdateAutoScalingGroup",
                "autoscaling:DescribeTags"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow",
            "Sid": "Autoscaling"
        },
        {
            "Action": [
                "cloudformation:DescribeStacks"
            ],
            "Resource": [
                "arn:aws:cloudformation:us-west-1:X:stack/parallelcluster-t3-nano/*"
            ],
            "Effect": "Allow",
            "Sid": "Cloudformation"
        },
        {
            "Action": [
                "dynamodb:PutItem",
                "dynamodb:Query",
                "dynamodb:GetItem",
                "dynamodb:DeleteItem",
                "dynamodb:DescribeTable"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-west-1:X:table/parallelcluster-t3-nano-DynamoDBTable-1TXX12M94IHKS"
            ],
            "Effect": "Allow",
            "Sid": "DynamoDBTable"
        },
        {
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::us-west-1-aws-parallelcluster/*"
            ],
            "Effect": "Allow",
            "Sid": "S3GetObj"
        },
        {
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::NONE/batch/*"
            ],
            "Effect": "Allow",
            "Sid": "S3PutObj"
        },
        {
            "Action": [
                "sqs:ListQueues"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow",
            "Sid": "SQSList"
        },
        {
            "Action": [
                "iam:PassRole"
            ],
            "Resource": [
                "arn:aws:iam::X:role/parallelcluster-*"
            ],
            "Effect": "Allow",
            "Sid": "BatchJobPassRole"
        }
    ]
}

and S3ReadWrite plocity:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::com.parker9.wp/*"
            ],
            "Effect": "Allow",
            "Sid": "S3ReadWrite"
        }
    ]
}

**Comment by gjparker9** [comment]
copy and paste didn't work, in S3ReadWrite policy the Resource value is

"arn:aws:s3:::com.parker9.wp/*"

similarly Action value is

"s3:*"

seems it's having problems pasting "*"...

**Comment by gjparker9** [comment]
ok, the fix was simple. in config, under [cluster default] needed this line:
s3_read_write_resource = arn:aws:s3:::com.parker9.wp*

note, no slash after the bucket name. i can get/put/list and delete objects in the bucket on both head and compute nodes now. woo woo!

you can close this issue.
