### ISSUE TITLE
Config vs Template

### ISSUE THREAD

**Issue by dayyehm** [aws/aws-parallelcluster#855]
Its more of a distinction question here as the tool help not fully explanatory here.

-c config file uses a configuration file that have the settings for the cloudformation template used to spin the stack,

but how that is different from the template_url , cluster_template as those parameter does not specify , does it mean that I can pcluster create test > then I can grab the CFN template , customize it and reference it in s3 bucket and use it again to do : pcluster -t customizedstack -u s3://customizedstacktmp

Appreciated.

**Comment by enrico-usai** [comment]
Hi @dayyehm ,

### --config

The `--config` parameter is useful when you want to use a configuration file that is not in the defaut path (`~/.parallelcluster/config`) or if you want to save different configuration files in your desktop in different location. 
```
$ tree ~/.parallelcluster/
.
+--- config
+--- config_custom_1
+--- config_custom_2
```
You can use this parameter to reference the appropriate file at cluster creation time:
```
$ pcluster create --config config_custom_1 ...
```
### --cluster-template
The `--cluster-template` specifies the `[config ...]` section to use in your configuration file. You can define different _cluster_ sections with specific configuration parameter and select the one to use at cluster creation time.
```
[global]
cluster_template = default
...
[cluster default]
scheduler = sge
vpc_settings = public
...
[cluster batch]
scheduler = awsbatch
vpc_settings = custom-for-batch
...

```
```
$ pcluster create --cluster-template batch ...
```

### --template-url

The `--template-url` instead is an "advanced" parameter, that can be used to specify a custom CloudFormation template. 
It is useful if you need to customize the [default CloudFormation Template](https://github.com/aws/aws-parallelcluster/blob/v2.1.1/cloudformation/aws-parallelcluster.cfn.json) by changing some internal resources settings. 
You need to upload your custom template to an S3 bucket and reference it with the `--template-url` parameter or by referencing it in the `[cluster ...]` section you are using. 
```
$ pcluster create --template-url https://s3.amazonaws.com/your-bucket/aws-parallelcluster-custom.cfn.json ...
```

```
[global]
cluster_template = test
...
[cluster test]
template_url =  https://s3.amazonaws.com/your-bucket/aws-parallelcluster-custom.cfn.json
...
```

**Comment by dayyehm** [comment]
Thank you very much

**Comment by robgpita** [comment]
Is a Cloudformation template created upon running the `pcluster create` command to spin up a new cluster? I'd like to modify the `Timeout` parameter on the `CreationPolicy` of the MasterServer.  It would save me considerable time to reference the CloudFormation template that was used to create the Parallel Cluster, as opposed to modifying the default CloudFormation Template to pass `template_url`.  My `post_install ` script takes ~90 minutes to run, and is showing `CREATE_FAILED The following resource(s) failed to create: [MasterServer].` , although I am able to specify `--nr`, view the logs, and verify my `post_install` script was successful.
