### ISSUE TITLE
Tags defined in the cluster configuration file cannot applied to EBS volumes

### ISSUE THREAD

**Issue by RodneyMarable** [aws/aws-parallelcluster#862]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 2.1.1
 - OS: ALL
 - Scheduler: ALL
 - Master instance type: ALL
 - Compute instance type: ALL

**Bug description and how to reproduce:**
I would like to tag EBS volumes using data supplied from the "tags" parameter that is defined in the pcluster config file.  This is important for showback/chargeback purposes, as large provisioned EBS RAID volumes could represent a significant portion of a cluster's operational costs.

Since there does not appear to be a mechanism that supports tagging EBS resources, this should be possible through the postinstall script by parsing the instanceId from EC2 metadata, listing all EBS volumes associated with that instanceId, and tagging the EBS volumes with the tags defined in the pcluster-config file. 

However, the default IAM role defined in the CloudFormation template does not permit EC2CreateTags, EC2DescribeTags, or EC2DeleteTags, and since I do not want to use a custom CloudFormation template or enable a custom_iam_role, this approach won't work.

For a short term solution, I am going to submit a pull request that will add these API calls to the default Cloudformation stack and provide documentation that describes how to perform arbitrary EBS volume tagging through the postinstall script.

**Additional context:**
A better long term fix would be to have Chef perform this tagging as part of "aws-parallelcluster-cookbook/blob/develop/recipes/base_config.rb" or in a separate recipe (tag_ebs_volumes.rb, or something to that effect).

I will open another feature request for this:

> Tags that are predefined in the ParallelCluster configuration file should be applied to all EBS volumes associated with the cluster stack.

**Comment by enrico-usai** [comment]
Closing in favour of: https://github.com/aws/aws-parallelcluster/issues/865
