### ISSUE TITLE
Feature Request: EBS volume tagging

### ISSUE THREAD

**Issue by RodneyMarable** [aws/aws-parallelcluster#865]
**Environment:**
 - aws-parallelcluster-2.1.0
 - OS: ALL
 - Scheduler: ALL
 - Master instance type: ALL
 - Compute instance type: ALL

**Bug description and how to reproduce:**
Tags that are predefined in the ParallelCluster configuration file should be applied to all EBS volumes associated with the cluster stack.  Users should not need to do anything in order to ensure that EBS volumes share the same tags as all other CloudFormation assets associated with a stack.

**Additional context:**
ParallelCluster does not currently provide support for applying tags defined in the pcluster-config file to EBS volumes.  Since large provisioned EBS volumes could compose a significant portion of the cluster's operational costs, we should provide a mechanism to track these assets.  As a short term fix, I have submitted a pull request (https://github.com/aws/aws-parallelcluster/pull/864) that will permit an operator to apply tags from the postinstall script.

Ideally, Chef will handle this as part of the stack installation process.  Including code to tag the EBS instances makes sense to include in aws-parallelcluster-cookbook/blob/develop/recipes/base_config.rb or as a separate recipe.

**Comment by enrico-usai** [comment]
I verified with ParallelCluster 3.0.2 with a configuration like this:

```
HeadNode:
  ...
  LocalStorage:
    RootVolume:
      Size: 50
    EphemeralVolume:
      MountDir: /test
...
SharedStorage:
  - MountDir: /ebs
    Name: myebs
    StorageType: Ebs
  - MountDir: /efs
    Name: myefs
    StorageType: Efs
Tags:
  - Key: testtag
    Value: tagvalue
```

and I can confirm the tags are correctly attached to both the ephemeral volume, the external EBS volume and EFS. Closing this.
