### ISSUE TITLE
Cluster creation with existing FSx fails sanity check

### ISSUE THREAD

**Issue by JiaweiZhuang** [aws/aws-parallelcluster#894]
**Environment:**
 - AWS ParallelCluster 2.2.1
 - OS: CentOS7
 - Scheduler: Slurm
 - Master instance type: c5n.large
 - Compute instance type: c5n.18xlarge

**Bug description and how to reproduce:**

I created a FSx file system manually and then launched a cluster with it through `fsx_fs_id`. It failed the sanity check:

```
$ pcluster create test-fsx
Beginning cluster creation for cluster: test-fsx
Config sanity error on resource FSXFSId: Credential should be scoped to a valid region, not 'us-east-1'.
```

I've got around this issue by setting `sanity_check = false`, and the cluster seems to be functioning correctly. Maybe something wrong with the sanity check?

**Additional context:**
The original pcluster config file is
```
[aws]
aws_region_name = us-east-1

[cluster hpctest]
vpc_settings = (master_subnet_id is the same as FSx's)
key_name = ...
base_os = centos7
master_instance_type = c5n.large
master_root_volume_size = 200
compute_instance_type = c5n.18xlarge
compute_root_volume_size = 20
initial_queue_size = 2
max_queue_size = 8
maintain_initial_size = false
scheduler = slurm
cluster_type = spot
placement_group = DYNAMIC
placement = cluster  
ebs_settings = shared
fsx_settings = fs

[ebs shared]
shared_dir = shared
volume_type = st1
volume_size = 500

[fsx fs]
shared_dir = /fsx
fsx_fs_id = fs-xxxx (my pre-created FSX id)

[global]
cluster_template = hpctest
update_check = true
sanity_check = true
```

**Comment by demartinofra** [comment]
Hi @JiaweiZhuang 

I tried to reproduce this issue but without any luck. If the fsx fs is in the correct region the cluster creation starts as expected while if the fs is in the wrong region it raises an error saying that it couldn't find the given fs. I was wondering if I'm missing anything from your setup.

Where are you running these commands from? Do you have any specific configuration for your AWS credentials? Do you have any default AWS region set outside of pcluster config?

**Comment by JiaweiZhuang** [comment]
Upgrading to `awscli-1.16.115` solves the problem. I was using `awscli-1.16.86`, which probably didn't support some FSx-related events.

You might consider asking users to run `pip install --upgrade awscli`, or simply require a minimum version of awscli for pcluster's pip install.

**Comment by demartinofra** [comment]
Thanks for the feedback. I think the issue is related to botocore a dependency of both boto3 and awscli. We need to increase the lower bound for boto3 in our requirements so to pull the latest version that supports FSx which is used during sanity checks. The rest should work as expected.
