### ISSUE TITLE
Fail to create FSx on-the-fly with the cluster

### ISSUE THREAD

**Issue by JiaweiZhuang** [aws/aws-parallelcluster#895]
**Environment:**
 - AWS ParallelCluster 2.2.1
 - OS: CentOS7
 - Scheduler: Slurm
 - Master instance type: c5n.large
 - Compute instance type: c5n.18xlarge

**Bug description and how to reproduce:**

I was able to use an existing FSx (despite a minor issue #894), but got an error when trying to create FSx on the fly. Here's the error message:

```
$ pcluster create --norollback clus-with-fsx
Beginning cluster creation for cluster: clus-with-fsx
Creating stack named: parallelcluster-clus-with-fsx
Status: parallelcluster-clus-with-fsx - CREATE_FAILED
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-clus-with-fsx The following resource(s) failed to create: [FSXSubstack, AssociateEIP, RootInstanceProfile, EBSCfnStack].
  - AWS::EC2::EIPAssociation AssociateEIP Resource creation cancelled
  - AWS::CloudFormation::Stack EBSCfnStack Resource creation cancelled
  - AWS::IAM::InstanceProfile RootInstanceProfile Resource creation cancelled
  - AWS::CloudFormation::Stack FSXSubstack Embedded stack arn:aws:cloudformation:us-east-1:753979222379:stack/parallelcluster-clus-with-fsx-FSXSubstack-12YDJ6T6SZVTY/13830d80-3ba1-11e9-85c8-122d883fe268 was not successfully created: The following resource(s) failed to create: [FileSystem].
```

In CloudFormation console, the earliest error in the `parallelcluster-clus-with-fsx-FSXSubstack-12YDJ6T6SZVTY` substack is:

> 
> Logical ID - FileSystem
> Status - CREATE_FAILED
> Status reason - The data repository import path is missing. (Service: AmazonFSx; Status Code: 400; Error Code: InvalidImportPath; Request ID: 72dbb484-342b-4260-814a-94f94fd832ff)
> 

**Additional context:**

The stack failed before the master server was created, so I could not login and check the log files despite the ` --norollback` option.

The pcluster config file is almost the same as #894, except the `fsx` section:

```
[aws]
aws_region_name = us-east-1

[cluster hpctest]
vpc_settings = (master_subnet_id is the same as FSx's)
key_name = ...
base_os = centos7
master_instance_type = c5n.large
master_root_volume_size = 200
compute_instance_type = c5n.18xlarge
compute_root_volume_size = 20
initial_queue_size = 2
max_queue_size = 8
maintain_initial_size = false
scheduler = slurm
cluster_type = spot
placement_group = DYNAMIC
placement = cluster  
ebs_settings = shared
fsx_settings = fs

[ebs shared]
shared_dir = shared
volume_type = st1
volume_size = 500

[fsx fs]
shared_dir = /fsx
storage_capacity = 3600
imported_file_chunk_size = 1024

[global]
cluster_template = hpctest
update_check = true
sanity_check = true
```

**Comment by JiaweiZhuang** [comment]
I guess `The data repository import path is missing` means the `import_path` for S3?  That shouldn't be required though?

**Comment by JiaweiZhuang** [comment]
OK setting `import_path` to whatever bucket fixes the problem.

**Comment by sean-smith** [comment]
The `import_path` argument is required when using the `imported_file_chunk_size` parameter.  I'll update the docs to make this clear.

The `imported_file_chunk_size` parameter doesn't do anything when used without a data repository. See https://aws-parallelcluster.readthedocs.io/en/v2.2.1/configuration.html#imported-file-chunk-size

**Comment by JiaweiZhuang** [comment]
Cool, just notice that, thanks!
