### ISSUE TITLE
Not mounting FSx with ubuntu16.04

### ISSUE THREAD

**Issue by JiaweiZhuang** [aws/aws-parallelcluster#896]
**Environment:**
 - AWS ParallelCluster 2.2.1
 - OS: ubuntu 16.04
 - Scheduler: Slurm
 - Master instance type: c5n.large
 - Compute instance type: c5n.18xlarge

**Bug description and how to reproduce:**
With `base_os = ubuntu1604`, FSx was created but not mounted to the cluster. Does it currently require `centos7`?

For example, centos7 would install Lustre client during launch as shown in `/var/log/cfn-init.log`:

```
Recipe: aws-parallelcluster::_lustre_install
  * remote_file[/opt/parallelcluster/sources/kmod-lustre-client-2.10.6.x86_64.rpm] action create (skipped due to not_if)
  * remote_file[/opt/parallelcluster/sources/lustre-client-2.10.6.x86_64.rpm] action create (skipped due to not_if)
  * yum_package[lustre_kmod] action install (up to date)
  * yum_package[lustre_client] action install (up to date)
```

With ubuntu, it doesn't seem to do anything with Lustre: 
- [cfn-init.log (from ubuntu1604)](https://github.com/aws/aws-parallelcluster/files/2918003/cfn-init.log)

**Comment by JiaweiZhuang** [comment]
I just notice `Support for FSx Lustre with Centos 7` in release notes. Doesn't seem to be mentioned in the docs though.

**Comment by demartinofra** [comment]
Hi @JiaweiZhuang 

Yes FSx is only supported with Centos 7 in the current release. 
I will update the docs accordingly and ideally we should also add a validation before cluster creation.

Thanks for reporting this!

**Comment by JiaweiZhuang** [comment]
Yes I can totally understand this because supporting OS should not delay the current release. That's already a significant enhancement and thanks for the great work :)

**Comment by sean-smith** [comment]
Fixed in https://github.com/aws/aws-parallelcluster/pull/904

We added validation to detect an unsupported instance type. Stayed tuned for more instance types soon!
