### ISSUE TITLE
Big slowdowns with more than 5 nodes

### ISSUE THREAD

**Issue by mikerossgithub** [aws/aws-parallelcluster#905]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 
aws-parallelcluster-2.0.0
 - OS: [e.g. alinux]
ubuntu
 - Scheduler: [e.g. SGE]
slurm
 - Master instance type: [e.g. m5.xlarge]
t3.small
 - Compute instance type: [e.g. c5.8xlarge]
p3.2xlarge

**Bug description and how to reproduce:**
I am using ParallelCluster for deep learning, and cannot seem to get reasonable performance as I scale. The cluster works fine for 4 nodes, but I am getting big volume slowdowns at 9 and 10 nodes. I thought it might be not having enough IOPS, but increased the IOPS without any effect.

Each node in the cluster works independently, and writes approximately 1.2 Gb every 3-5 minutes to the shared volume. By my calculations, 3000 IOPS should be sufficient for this. As a test, I increased the IOPS to 9000, and I am still having the problem. So I can't tell what is causing the problem. 

I am not sure how to diagnose the cause of the slowdown, whether it is related to the volume, or some bandwidth issue over NFS, or what. We're hoping to be able to run dozens of nodes at once for HPC, but if we can't scale beyond 4 or 5, it prevents our use case. Any help would be greatly appreciated.

**Comment by JiaweiZhuang** [comment]
Hmm why not use the new [FSx for Lustre](https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html?highlight=lustre#fsx)? I am getting quite performance from it (easily go >5GB/s). With NFS over a single EBS volume it is hard to get more than 500 MB/s.

For DL specific workloads you might also want to checkout this [DL best practices guide (IO section)](http://www.prace-ri.eu/best-practice-guide-deep-learning#id-1.5.9).

**Comment by mikerossgithub** [comment]
@JiaweiZhuang Thank you. FSx/Lustre looks like it might be a good solution.

**Comment by demartinofra** [comment]
I think the bottleneck in your setup is the master node. NFS server runs on the master node, hence choosing a low performance instance for the master will cause a degradation in the iops. Try to choose a master instance with higher networking throughput and let us know if this solves the issue.

FSx is a good alternative to this and doesn’t have this “limitation”

**Comment by mikerossgithub** [comment]
Switching master to m5.xlarge seems to have fixed the problem -- at least up to 12 nodes. Is there a systematic set of best practices for diagnosing these issues? If I experience slowdowns as I go up to 30 or 40 nodes, what is the best way to identify the bottlenecks assuming I have an accurate assessment of my per-node needs (write approx 1.5 Gb to master every 5 minutes)

**Comment by demartinofra** [comment]
At the moment unfortunately we don't have this set of best practices properly documented. I started a wiki page [here](https://github.com/aws/aws-parallelcluster/wiki/Best-Practices) and hopefully soon we will provide a more comprehensive documentation which includes a series of advices on how to configure the cluster based on specific requirements.

**Comment by JiaweiZhuang** [comment]
> hopefully soon we will provide a more comprehensive documentation

@demartinofra I wrote a ParallelCluster tutorial that might be useful: https://jiaweizhuang.github.io/blog/aws-hpc-guide/
(I've been trying to spread the use of cloud computing among the scientific community, so kind of knows the common pitfalls where novice users can get stuck at.)

**Comment by demartinofra** [comment]
@JiaweiZhuang very useful and well written blog post. 
In case we decide to add a dedicated section for ParallelCluster related blog posts to our docs/wiki, I'll make sure yours gets included too!
