### ISSUE TITLE
Disable sanity check during pcluster configure

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-parallelcluster#913]
I'm trying to configure ParallelCluster for the first time, and I try to modify the config file to not do the sanity check, but it keeps setting it back.  Is there a way to configure it on initial configuration so that it doesn't do the sanity check?

_Originally posted by @hellmersjl3ds in https://github.com/aws/aws-parallelcluster/issues/910#issuecomment-469891584_

**Comment by sean-smith** [comment]
Closing... seems like the better way forward is to fix the issues with `sanity_check`.

Until then you can do this with `sed` like so:

```
$ pcluster configure && sed -i .backup 's/sanity_check = true/sanity_check = false/' ~/.parallelcluster/config
```
