### ISSUE TITLE
pcluster configure fails in a clean environment

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-parallelcluster#920]
From: [HPC Forum - Failed with error: You must specify a region error](https://forums.aws.amazon.com/thread.jspa?threadID=299908)

**Environment:**
 - aws-parallelcluster-2.1.1

**Bug description and how to reproduce:**
* Remove `.aws/config` file, if there
* Execute `pcluster configure`
* It will fail with:

```
$ pcluster configure
Cluster Template [default]:
AWS Access Key ID []: test
AWS Secret Access Key ID []: test
Failed with error: You must specify a region.
Hint: please check your AWS credentials.
```

**Workaround:**
Set the default region it in the AWS CLI configuration file: `~/.aws/config`
```
[default]
region=us-east-1
```
The region is not enough. Once set, it fails `Failed with error: Unable to locate credentials`
so you also have to set the AWS credentials in the  `~/.aws/credentials`
```
[default]
aws_access_key_id = yourAccessKeyId
aws_secret_access_key = yourSecretAccessKey
```

**Comment by sean-smith** [comment]
You can set the credentials && region with:

```
$ aws configure
```

This is the preferred way to specify aws credentials. In the future we'll disable specifying your credentials in the parallel cluster config file and require you to set them via the aws cli (as shown above).
