### ISSUE TITLE
guidance: master node under EC2 retirement mandate; can I do the STOP|START dance?

### ISSUE THREAD

**Issue by chrisdag** [aws/aws-parallelcluster#928]
Looking for quick guidance as the last issue I found on this was  #418 and the answers were helpful but still in the "we have not really tested this much..." state. 

Has any more internal testing been done to verify behavior when the master node is STOPPED and then START'ed again to force the instance onto new hardware? I've got a long running cluster with a master node scheduled for maintenance/retirement in a week or so.  I don't think this will freak out the cloudformation stack or any other external thing.

I suspect this will work and I'm prepared to drain the queue and sort out NFS client issues after the start operation but was looking for quick guidance if this was even recommended when faced with an Ec2 master that is scheduled for replacement 

Thanks!

**Comment by chrisdag** [comment]
Going to close/resolve after leaving this comment. When the master node is under an AWS EC2 retirement notice performing the STOP/START dance to move the instance onto new hardware worked just fine. We did drain/disable the queues beforehand and also checked NFS clients after.

**Comment by sean-smith** [comment]
Thanks @chrisdag for the update!

We're evaluating an easier way to do this. I know it's painful.
