### ISSUE TITLE
automatically mounting existing efs

### ISSUE THREAD

**Issue by karlvirgil** [aws/aws-parallelcluster#934]
**Environment:**
 - AWS ParallelCluster version 2.2.1
 - OS: centos7
 - Scheduler: SGE
 - Master instance type: c5.4xlarge
 - Compute instance type: c5n.18xlarge]

**Bug description and how to reproduce:**
I get this error:
`$ )/usr/bin/pcluster create meredithk-fsx
Beginning cluster creation for cluster: meredithk-fsx
Config sanity error on resource EFSFSId: There is an existing Mount Target fsmt-0c92a544 in the Availability Zone us-east-1a for EFS fs-4b70dd00, and it does not have a security group with inbound and outbound rules that support NFS. Please modify the Mount Target's security group, or delete the Mount Target.`
when trying to create a parallelcluster

**Additional context:**
I've attached the config file 
[config.txt](https://github.com/aws/aws-parallelcluster/files/2972488/config.txt)

**Comment by karlvirgil** [comment]
I might add that the same efs share mounts just fine when using a post_install script.

**Comment by sean-smith** [comment]
just turn off config sanity and try re-running while we diagnose the bug:

```
sanity_check = false
```

**Comment by enrico-usai** [comment]
Hi @karlvirgil 

I suspect that could be a problem in the [Security Group validation](https://github.com/aws/aws-parallelcluster/blob/develop/cli/pcluster/config_sanity.py#L67)

Are you using the `sg-0b39ee73` specified in the `additional_sg` parameter for the EFS?
What CIDR do you have configured in the Security Group assigned to your Mount Target `fsmt-0c92a544`? 

Thank you

**Comment by demartinofra** [comment]
This issue was addressed in #1009 and released with version 2.4.0
