### ISSUE TITLE
Change linux usergroup of Compute user for EFS writing with awsbatch

### ISSUE THREAD

**Issue by kimyx** [aws/aws-parallelcluster#936]
**Environment:**
- aws-parallelcluster 2.1.1  
- awscli              1.16.96
- boto3               1.9.86 
- OS: alinux
- Scheduler: awsbatch
- Master instance type: t2.micro
- Compute instance type: c5.xlarge

**Bug description and how to reproduce:**
Not a bug, but something that isn't working how I need. My cluster config includes an EFS mount. That is set up and working. The problem is that files written to this mount (or the default /shared mount) by a simple cluster job are owned by linux user root in group root. I need the files to have a different user-defined linux group so that users of the cluster can manage their own files when produced by the computing jobs.

I know how to do this in linux with EFS and have done so on static EC2s, but I don't know how to do it on the dynamic compute nodes. Here's basically what I need to execute as Compute nodes spin up:
```
groupadd -g 1005 mygroup
usermod -g mygroup root
```
I'm guessing that I need to use the extra_json or additional_cfn_template parallelcluster config options, but don't know how to get started on this. Is there a really simple way to do it? I've looked at the dna.json file that appears in the /tmp directory on the cluster Master node, but I have a lot to learn about Chef before knowing what to do next.

**Additional context:**
Redacted config file attached.
[pcluster_config.txt](https://github.com/aws/aws-parallelcluster/files/2975374/pcluster_config.txt)

**Comment by kimyx** [comment]
I see this tantalizing code in aws-parallelcluster-cookbook-2.1.1/recipes/_compute_base_config.rb:
```
# Mount each volume with NFS
shared_dir_array.each do |dirname|
  # Created shared mount point
  directory dirname do
    mode '1777'
    owner 'root'
    group 'root'
    recursive true
    action :create
  end
```
and similar in efs_mount.rb.

I also see this in the Master node dna.json:
```
[ec2-user@ip-10-0-0-65 tmp]$ python -m json.tool dna.json
{
    "cfncluster": {
        "cfn_base_os": "alinux",
        "cfn_cluster_user": "ec2-user",
```
I've changed ec2-user on the Master node to have the desired primary group and files that it creates within the EFS mount directory have the desired group. So perhaps changing the ec2-user's primary group on the Compute nodes is a safer way to proceed.

**Comment by sean-smith** [comment]
Hi @kimyx 

We're working on this! See https://github.com/aws/aws-parallelcluster/pull/841

It sounds like running as `ec2-user` on the containers would solve your issue correct?

**Comment by kimyx** [comment]
@sean-smith - that's great! My search for existing issues didn't uncover that one. :)

I _think_ this will solve my problem, given how EFS uses UID/GID for ownership matching across clients. I'll have to test with your changes to know for sure.

**Comment by kimyx** [comment]
Second thoughts on my last comment. I think that the primary _group_ of the ec2-user will also need to be changed on the compute nodes. I'm pretty sure that the user's primary GID is the only one assigned to files that the user creates, which probably means the ec2-user _group id_ rather than one that helps us with EFS/NFS permissions.

Maybe there's some other kind of NFS trickery that would help. I'll look into that.

**Comment by kimyx** [comment]
It sounds like setgid may do what I need. I'll test it soon.

https://aws.amazon.com/about-aws/whats-new/2017/08/amazon-efs-now-supports-additional-permissions-for-finer-grained-control-of-directory-and-file-access/
http://www.softpanorama.org/Access_control/Permissions/setgid_bit_in_directories.shtml

But having cluster jobs run as ec2-user still seems like a useful change.

**Comment by demartinofra** [comment]
Hi @kimyx, were you able to make it work?

**Comment by kimyx** [comment]
Yes, as far as I've gotten. Using setgid via

chgrp mygroup myfolder
chmod g+s myfolder

causes files in myfolder to be owned by group mygroup even when the root user writes to them from an awsbatch job. However, it only applies to the one folder, and other users within mygroup can't modify those files because the root user is the owner.

I haven't yet tried the [NFS grpid](https://www.thegeekdiary.com/common-nfs-mount-options-in-linux/) option within EFS. That's supposed to cause inheritance of the sticky group behavior from the top down.

I _think_ that changing the runtime user of awsbatch jobs from root to ec2-user will solve the other problem. I can simulate that in a test but haven't gotten around to it yet.

You can close this ticket. Is there an expected release date for the ec2-user change #841?

**Comment by demartinofra** [comment]
Unfortunately it is very likely that it won't make it for the upcoming release. Hence I would assume the one right after should contain this enhancement.

**Comment by kimyx** [comment]
For the record, the grpid option in /etc/fstab fails for an EFS drive. From /var/log/messages:
```
Mar 23 14:41:04 ip-10-0-0-238 systemd: Mounting /tiegcm_efs...
Mar 23 14:41:04 ip-10-0-0-238 systemd: tiegcm_efs.mount mount process exited, code=exited status=32
Mar 23 14:41:04 ip-10-0-0-238 mount: mount.nfs4: an incorrect mount option was specified
Mar 23 14:41:04 ip-10-0-0-238 systemd: Failed to mount /tiegcm_efs.
```
Works fine without grpid, so apparently this isn't available for EFS.

I'm moving away from using the awsbatch scheduler for other reasons; instead using sge with centos7 to get the needed versions of developer tools. The post_install hook should let me put the `centos` user in the proper linux group.

**Comment by demartinofra** [comment]
Hi @kimyx,

thanks for sharing this! Consider also using Slurm instead of SGE. We are going to release several Slurm enhancements as part of the next release and also the scheduler is actively developed.
