### ISSUE TITLE
intermittent cfn-init failure behaviour

### ISSUE THREAD

**Issue by tkuzuhara** [aws/aws-parallelcluster#940]
**Environment:**
 - AWS ParallelCluster / CfnCluster version: aws-parallelcluster-2.1.1
 - OS: Centos
 - Scheduler: SGE
 - Master instance type: N/A
 - Compute instance type: N/A

**Bug description and how to reproduce:**
We had a bunch of machines fail cfn-init on 3/18.  They seem to have failed trying to restart sshd.

From `/etc/chef/local-mode-cache/cache/chef-stacktrace.out`:
```
Generated at 2019-03-18 10:28:15 -0700
Chef::Exceptions::MultipleFailures: Chef::Exceptions::MultipleFailures
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:293:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:280:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/shell_out.rb:124:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/provider/service/systemd.rb:146:in `enable_service'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/provider/service.rb:85:in `block in action_enable'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/provider.rb:227:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/provider/service.rb:84:in `action_enable'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/provider.rb:182:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/resource.rb:577:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:717:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:712:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:712:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:751:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/bin/chef-client:26:in `<top (required)>'
/bin/chef-client:75:in `load'
/bin/chef-client:75:in `<main>'

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: service[ssh] (openssh::default line 94) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /bin/systemctl --system enable sshd ----
STDOUT:
STDERR: Failed to execute operation: Connection timed out
---- End output of /bin/systemctl --system enable sshd ----
```

Nothing was different on our network configuration.  Later instances started just fine, so whatever the issue was appears to be triggered by something outside of our setup.

This is rather more a couple of questions than a bug report, since I don't think it is feasible to try and debug this given it happened in a short period of time and is not reproducible.

1. What is the expected behavior for a node that fails cfn-init?  In our case the node just sits there idle.  Is there not anything built into cfn-cluster to detect a node that failed cfn-init and terminate it?

2. I feel like I get hit time and time again with random cfn-init failures because of how complicated the chef initialization is.  I don't have any idea of what all the steps are but what I do know is that its behavior is somewhat unpredictable due to external dependencies.  Is there any way you can provide an alternate path that would bake whatever external dependencies required for initialization into the AMI so that we wouldn't have to have this unpredictable step that happens on every instance start?  Even a 1% failure rate on initialization translates to many hours of manual intervention trying to recover and figure out what happened.

**Comment by lukeseawalker** [comment]
Hi @tkuzuhara,
this is actually a bug that needs to be addressed. Thank you for reporting it.
At the moment the cfn-init failures are handled only during cluster creation time and are signaled back to the cloudformation.
Can you please also attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log`?

**Comment by tkuzuhara** [comment]
Logs attached from another recent random failure:

[cloud-init.log](https://github.com/aws/aws-parallelcluster/files/3153972/cloud-init.log)
[cfn-init-cmd.log](https://github.com/aws/aws-parallelcluster/files/3153973/cfn-init-cmd.log)
[cfn-init.log](https://github.com/aws/aws-parallelcluster/files/3153974/cfn-init.log)
[cfn-wire.log](https://github.com/aws/aws-parallelcluster/files/3153975/cfn-wire.log)

Note I did not see a `/var/log/cloud-init-output.log`.

**Comment by demartinofra** [comment]
This behaviour got significantly improved with version 2.4.0. Now when an instance fails the cfn-init it is automatically terminated and replaced with a new one. This allows to handle all sporadic and unpredictable chef failures that were causing instances to hang forever in an inconsistent state.
