### ISSUE TITLE
[Question] AWS parallelcluster how to use different schedulers with mpi

### ISSUE THREAD

**Issue by francesco-ismb** [aws/aws-parallelcluster#948]
**Environment:**
 - AWS ParallelCluster [aws-parallelcluster-2.1.1]
 - OS: [e.g. ubuntu1604]
 - Scheduler: SGE/torque/slurm/aws batch
 - Master instance type: [m5.xlarge]
 - Compute instance type: [m5.xlarge]

Dear all,

I'm using the aws parallel cluster template to run a simulation on a cluster on AWS using open MPI. The command I used to execute MPI is: 
`mpirun -hostfile /home/ubuntu/hostfile -np 16 -ppn 4 ./executable.exe` 

It seems that everithing works with the default scheduler (SGE) setted in the template file, but I don't understand how a scheduler setted in the template can influence the mpi command launched in the master node. Can someone explain this point? By running that command am I using SGE as scheduler or I have to change mpi command or mpi configuration file to use SGE?

**Comment by demartinofra** [comment]
Hi,

please take a look at these resources:
* SGE: https://www.open-mpi.org/faq/?category=sge
* Slurm: https://www.open-mpi.org/faq/?category=slurm
* Torque: https://www.open-mpi.org/faq/?category=tm

**Comment by sean-smith** [comment]
Hi @francesco-ismb,

By scheduling a job through the scheduler, you don't have to specify the hostfile. The scheduler takes care of that for you.

So in a scheduler, your command becomes:
```
#!/bin/bash

#$ -cwd
#$ -pe mpi 72
#$ -S /bin/bash

mpirun -np 72 -ppn 4 ./executable.exe
```

You can then submit the above file to sge with qsub:

```
$ qsub submit_script.sge
```

Best explanation is from the openmpi docs (linked [above](https://github.com/aws/aws-parallelcluster/issues/948#issuecomment-476116777)):

> Open MPI will automatically detect when it is running inside SGE and will just "do the Right Thing."
> Specifically, if you execute an mpirun command in a SGE job, it will automatically use the SGE mechanisms to launch and kill processes. There is no need to specify what nodes to run on — Open MPI will obtain this information directly from SGE and default to a number of processes equal to the slot count specified. For example, this will run 4 MPI processes on the nodes that were allocated by SGE.

See https://gist.github.com/sean-smith/d29e83b64d7ac3f2195e349447d2dbfe for a more in-depth tutorial.

**Comment by francesco-ismb** [comment]
Thank you for your response and for the tutorial.
