### ISSUE TITLE
Attempting to change base_OS to sles 12 sp3

### ISSUE THREAD

**Issue by kevinayres** [aws/aws-parallelcluster#949]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.0.0]
 - OS: [sles12 sp3]
 - Scheduler: [slurm]
 - Master instance type: [any]
 - Compute instance type: [any]

**Bug description and how to reproduce:**
Unable to change the os type to sles 12 sp3. I leveraged the develop branch and modified every reference I could find for base_os. See Fork kevinayres/aws-parallelcluster
Can you tell me what I'm missing please?

**Additional context:**
Error returned is: Parameter BaseOS failed to satisfy constraint: must be a supported base OS

 - configuration file without any credentials or personal data.
 - pre/post-install scripts, if any
 - screenshots, if useful
 - if the cluster fails creation, please re-execute `create` action using `--norollback` option and attach `/var/log/cfn-init.log`, `/var/log/cloud-init.log` and `/var/log/cloud-init-output.log` files from the Master node
 - if you encounter scaling problems please attach `/var/log/nodewatcher` from the Compute node and `/var/log/jobwatcher` and `/var/log/sqswatcher` from the Master node

 I'm also referencing it via local ~/.parallelcluster/config
[aws]
aws_region_name = us-west-2
aws_access_key_id = <>
aws_secret_access_key = <>

[cluster default]
vpc_settings = public
key_name = pup
base_os = sles1203
#custom_ami = ami-00c75ff88724f9e77

[vpc public]
master_subnet_id = subnet-5a2a2800
vpc_id = vpc-97d87eef

[global]
update_check = true
sanity_check = true
cluster_template = default

[aliases]
ssh = ssh {CFN_USER}@{MASTER_IP} {ARGS}

**Comment by demartinofra** [comment]
Hi @kevinayres ,

at the moment the supported OSs are the ones listed here: https://aws-parallelcluster.readthedocs.io/en/latest/configuration.html#base-os

Adding support for additional OSs is not as trivial as whitelisting them in the pcluster cli but you would have to implement all the required Chef recipes for the new OS at the very least. I would highly recommend you to use one of the supported OSs so that you won't diverge from the fully supported version of the product.

Cheers,
Francesco

**Comment by kevinayres** [comment]
Francesco, can you be more specific please? Wherein the cookbook need I specify the OS and AMI ID? I'm fairly new to CHEF.  The entire goal is specifically to launch the SLES for HPC images into cfn-cluster. Thanks.

**Comment by demartinofra** [comment]
It's not as simple as specifying an OS and AMI ID. If you really wanna dig into the [code](https://github.com/aws/aws-parallelcluster-cookbook) a good starting point is to look at the packer definition for a supported os (e.g. [centos](https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/amis/packer_centos7.json)). From there `aws-parallelcluster::default` recipe is called which is the entrypoint for a series of chef recipes that define the libraries, tools and configurations for all the OSs. Some of the recipes are customized for the specific OS which means you'll have to look into them and implement the missing parts for SLES.
If you are not familiar with Chef and Packer this won't be that simple. 

Most likely ParallelCluester will support SUSE in the future but at the moment we cannot commit to any date. Could you tell us a bit more about your use case and why support for SLES is a blocker?

**Comment by demartinofra** [comment]
Reopening in case additional help is needed. If you could share your use case and your requirements we could better understand what you are trying to achieve and eventually try to support your use case :)

**Comment by kevinayres** [comment]
Thanks Francesco. Our use-case is specific to SUSE and SLES. I work for SUSE and am pursuing SLES support within Pcluster. I'd like to work with you and David Duncan to get this working. SUSE has a number of initiatives with AWS and this is a priority. Thanks.

**Comment by enrico-usai** [comment]
Hi @kevinayres 

this feature enhancement remained opened for a long time.
For the foreseeable future we're not going to work on adding support for SLES, so I'm closing this thread. 

If you're still working on it and you have specific questions feel free to open a new issue, referencing this one.
Thanks
