### ISSUE TITLE
problem with double quoting post_install_args

### ISSUE THREAD

**Issue by hpcpony** [aws/aws-parallelcluster#966]
**Environment:**
 - AWS ParallelCluster / CfnCluster version 2.2.1
 - OS: alinux
 - Scheduler: slurm
 - Master instance type: t3.small
 - Compute instance type: t3.small

**Bug description and how to reproduce:**
post_install_args are wrapped in double quotes for /etc/parallelcluster/cfnconfig file which causes parsing/run error when postinstall script is run.  Double quote the args in the pcluster config file, and you'll have problems with the post install script runs.

**Additional context:**
There seems to be a bit of issue concerning how one quotes post_install_args.  Specifically, double quotes bad, single quotes less bad.  This only seems to matter for the _post_ args as the pre_args are handled slightly different.

In this first example we use double quotes in the pcluster config file:

>  ...
>  pre_install_args = "pre1 pre2"
>  post_install_args = "post1 post2"
>  ...

Once the cluster is up an running looking in the master and/or compute node /etc/parallelcluster/cfnconfig file:

>  ...
>  cfn_preinstall_args="pre1 pre2"
>  cfn_postinstall_args=""post1 post2""
>  ...

Note that for whatever reason, something has wrapped the post_install_args in another set of quotes!

Examining the master and/or compute /var/log/cfn-init.sh file:

>  ...
>  2019-03-30 17:15:36,982 [DEBUG] Running command runpostinstall
>  2019-03-30 17:15:36,982 [DEBUG] No test for command runpostinstall
>  2019-03-30 17:15:37,545 [INFO] Command runpostinstall succeeded
>  2019-03-30 17:15:37,545 [DEBUG] Command runpostinstall output: /etc/parallelcluster/cfnconfig: line 5: post2: command not found CFR: postinstall script
>  /tmp
>  Filesystem     1K-blocks    Used Available Use% Mounted on
>  devtmpfs          991660      64    991596   1% /dev
>  tmpfs            1002248       0   1002248   0% /dev/shm
>  /dev/nvme0n1p1  25669928 3931172  21638508  16% /
>  /dev/nvme1n1    20511312   45080  19401272   1% /shared
>  postinstall 1 arguments
>     s3://cfreese/parallelcluster/alinuxPostInstall.sh
>  /bin/rm: cannot remove ‘/tmp/tmp.8S039szQk8’: No such file or directory
>  ...

However, if you single quote:

pcluster config file:

>  ...
>  pre_install_args = 'pre1 pre2'
>  post_install_args = 'post1 post2'
>  ...

master/compute /etc/parallelcluster/cfnconfig file:

>  ...
>  cfn_preinstall_args='pre1 pre2'
>  cfn_postinstall_args="'post1 post2'"
>  ...

master/compute /var/log/cfn-init.sh file:

>  ...
>  2019-03-30 16:37:18,445 [DEBUG] Running command runpostinstall
>  2019-03-30 16:37:18,445 [DEBUG] No test for command runpostinstall
>  2019-03-30 16:37:19,377 [INFO] Command runpostinstall succeeded
>  2019-03-30 16:37:19,377 [DEBUG] Command runpostinstall output: CFR: postinstall script
>  /tmp
>  Filesystem     1K-blocks    Used Available Use% Mounted on
>  devtmpfs          991660      64    991596   1% /dev
>  tmpfs            1002248       0   1002248   0% /dev/shm
>  /dev/nvme0n1p1  25669928 3931176  21638504  16% /
>  /dev/nvme1n1    20511312   45080  19401272   1% /shared
>  postinstall 3 arguments
>     s3://cfreese/parallelcluster/alinuxPostInstall.sh
>     'post1
>     post2'
>  /bin/rm: cannot remove ‘/tmp/tmp.jdyzBfktJx’: No such file or directory
>  ...

You get the arguments but note the outer double quotes result in an extra single quote becoming part of the first and last argument string ;^(

It seems to me (though I"m a newbie to parallelcluster/cfn) that the _post_ args should be handled like the _pre_ args and support either single or double quotes consistently (or the documentation should be explicit about which quotes work).

For completeness here's the post install script:
```
  #!/bin/bash
  echo "CFR: postinstall script"
  pwd
  df -k
  echo "postinstall $# arguments"
  for arg in "$@"
  do
          echo "   $arg"
  done
```

**Comment by sean-smith** [comment]
yep, this a problem coming from [cfnconfig.erb #L5 ](https://github.com/aws/aws-parallelcluster-cookbook/blob/adedbf8693c78b296ec3224616cc252c83f5e784/templates/default/cfnconfig.erb#L5)

Thanks for pointing it out!
