### ISSUE TITLE
pcluster configure  ak/sk

### ISSUE THREAD

**Issue by frank622** [aws/aws-parallelcluster#969]
Parallelcluster Configure requires input AK/sk,but actuary needn't ak/sk when I was running.
Permissions provided by AWS configure.

**Comment by enrico-usai** [comment]
Hi @frank622,
do you have the same problem of https://github.com/aws/aws-parallelcluster/issues/920 ?

If yes, feel free to close the current issue,
if not, could you please add more details to be able to reproduce your issue?
Thank you

**Comment by sean-smith** [comment]
@frank622 You don't need to set `Access Key ID` or `Secret Access Key ID`, just hit enter. For example:

```
$ pcluster configure
Cluster Template [default]:
AWS Access Key ID []:
AWS Secret Access Key ID []:
You chose not to configure aws credentials in parallelcluster config file.
Please make sure you export a valid AWS_PROFILE or you have them exported in the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables.
```
