### ISSUE TITLE
Error following an upgrade

### ISSUE THREAD

**Issue by geekson** [aws/aws-parallelcluster#971]
**Environment:**
 - AWS  CfnCluster version 1.4.2

**Bug description and how to reproduce:**
When I try to upgrade cfncluster through a command prompt I get:  

C:\Python27\Scripts>easy_install -U cfncluster
Searching for cfncluster
Reading https://pypi.python.org/simple/cfncluster/
Best match: cfncluster 1.6.1
Processing cfncluster-1.6.1-py2.7.egg
cfncluster 1.6.1 is already the active version in easy-install.pth
Installing cfncluster-script.py script to c:\python27\Scripts
Installing cfncluster.exe script to c:\python27\Scripts
Installing cfncluster.exe.manifest script to c:\python27\Scripts

Using c:\python27\lib\site-packages\cfncluster-1.6.1-py2.7.egg
Processing dependencies for cfncluster
error: s3transfer 0.1.12 is installed but s3transfer<0.3.0,>=0.2.0 is required by set(['boto3'])

Can you help?

Regards,
David

**Comment by geekson** [comment]
ok upgrade aws cli fixed my problem. Ceers I close.

**Comment by enrico-usai** [comment]
Hi @geekson thank you for sharing your solution and closing the bug. 

In any case we'd like to encourage you to use AWS ParallelCluster, that is the AWS supported Open Source cluster management built on the CfnCluster project.
