### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by microbioticajon** [aws/aws-parallelcluster#984]
Hi Guys,

More of a question than an issue.

Was wondering, were you guys planning on adding support for Ubuntu 18.04? If so do you have a rough timeframe? 

Best,
J

**Comment by sean-smith** [comment]
TBD

**Comment by microbioticajon** [comment]
Just to place this information here. Linked to issue [993](https://github.com/aws/aws-parallelcluster/issues/993)

I have been hacking around with aws-parallelcluster-cookbook to build an ami with ubuntu1804. I had to make a few changes to the recipes (not entirely sure they are the correct changes) to progress the build, however I have hit a problem I cannot get past:

Error executing action `start` on resource 'service[ec2blkdev]'

If you are interested in taking a look, I have a fork of the repo here: https://github.com/microbioticajon/aws-parallelcluster-cookbook

Im calling ./build_ami.sh directly to simplify the process:
AWS_FLAVOR_ID=t2.large AWS_VPC_ID=vpc-12345 AWS_SUBNET_ID=subnet-54321 ./build_ami.sh --os ubuntu1804 --partition region --region eu-west-2

I think the problem lies in an incompatibility with this particular dependency:

https://github.com/dougalb/ec2-udev-scripts

These are my changes:
https://github.com/microbioticajon/aws-parallelcluster-cookbook/commit/de2ce33d966e562f2e9bc71449d26ab182e88001



Best,
J

**Comment by lukeseawalker** [comment]
coming in next release
