### ISSUE TITLE
jobwatcher support for array jobs

### ISSUE THREAD

**Issue by armaneshaghi** [aws/aws-parallelcluster#986]
I have two questions:

1) I wonder whether the `jobwatcher` considers array jobs for SGE in the queue to scale up the cluster? I suspect it does not because I have many array jobs in waiting and the cluster does not scale up (seems it has been previously raised here https://github.com/aws/aws-parallelcluster/issues/87 ) 

2) is there a way to only update one field using `pcluster`, say I just want to change the `max_queue_size` field without changing or using a new config file. 

Thank you.

**Comment by enrico-usai** [comment]
Hi @armaneshaghi did you find the answers to your questions? 
Could you share them with the other Parallelcluster users?

**Comment by armaneshaghi** [comment]
Hi Enrico, no I have not. Being a novice user I was not sure the above issue is a scaling issue or an actual specific problem related to job arrays. 

If anyone else can confirm that job arrays are not supported, please re-open.

**Comment by enrico-usai** [comment]
# Job arrays
The jobwatcher considers the size of the job array to scale up the cluster.
The [command](https://github.com/aws/aws-parallelcluster-node/blob/develop/jobwatcher/plugins/sge.py#L10) we are executing to calculate the number of required jobs returns a row for each single job of the array.

```
$ echo "sleep 1000" | qsub -t 1-10
Your job-array 1.1-10:1 ("STDIN") has been submitted

$ qstat -g d -s p -u '*'
job-ID  prior   name       user         state submit/start at     queue       slots ja-task-ID
----------------------------------------------------------------------------------------------
      1 0.55500 STDIN      centos       qw    04/05/2019 07:50:21                  1 1
      1 0.55500 STDIN      centos       qw    04/05/2019 07:50:21                  1 2
      1 0.55500 STDIN      centos       qw    04/05/2019 07:50:21                  1 3
      ...
      1 0.55500 STDIN      centos       qw    04/05/2019 07:50:21                  1 9
      1 0.55500 STDIN      centos       qw    04/05/2019 07:50:21                  1 10

$ tail -f /var/log/jobwatcher
...
2019-04-05 07:48:25,919 INFO [jobwatcher:_get_vcpus_by_instance_type] Instance c4.large has 2 vcpus.
...
2019-04-05 07:50:26,310 INFO [jobwatcher:_poll_scheduler_status] 5 nodes requested, 0 nodes running
2019-04-05 07:50:26,387 INFO [utils:get_asg_settings] min/desired/max 0/0/10
2019-04-05 07:50:26,388 INFO [jobwatcher:_poll_scheduler_status] Setting desired to 5 nodes, requesting 5 more nodes from asg.
```

# Updating max_queue_size
There are no ways to update a single configuration parameter.
You can change the `max_queue_size` value and perform the update command but it will always perform a cloudformation update.

In this specific case an alternative could be to go in the EC2 console and modify the *Max* configuration parameter of the Autoscaling Group associated to the cluster.

**Comment by armaneshaghi** [comment]
Thank you @enrico-usai for this great explanation.
