### ISSUE TITLE
Is there a way to use temporary security credentials in Parallel cluster configuration?

### ISSUE THREAD

**Issue by datsabk** [aws/aws-parallelcluster#998]
**Environment:**
 - AWS ParallelCluster / CfnCluster version [e.g. aws-parallelcluster-2.0.0]
 - OS: ubuntu1604
 - Scheduler: Slurm
 - Master instance type: t2.xx
 - Compute instance type: t2.xx

**Bug description and how to reproduce:**
I am trying to utilise temporary security credentials or assume role for the Parallel cluster creation. However, I am unable to do that. I do not wish to add permanent security credentials in the configuration. Is there a way this could work?

**Additional context:**
NA

**Comment by sean-smith** [comment]
yes, you can just setup the aws credentials as environment variables. Then when you run `pcluster configure` leave the AWS Access Key and Secret Access Key blank.

```
$ pcluster configure
Cluster Template [default]:
AWS Access Key ID []:
AWS Secret Access Key ID []:
You chose not to configure aws credentials in parallelcluster config file.
Please make sure you export a valid AWS_PROFILE or you have them exported in the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables.
```

See https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html

For assume role it's even easier, just associate the IAM role you need with the ec2 instance and you'll have the credentials available magically on that instance.
